frontend/src/components/IssueV1/components/Panel/IssueStatusActionPanel.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

chore(frontend): show warning for running tasks when cancelling issues

---

backend/plugin/parser/mysql/split.go

fix: ignore IF NOT EXISTS

---

backend/api/gitops/webhook.go
backend/api/v1/sql_service.go
backend/plugin/advisor/mysql/advisor_insert_row_limit.go
backend/plugin/advisor/mysql/advisor_statement_affected_row_limit.go

More friendly with params query likes `INSERT INTO t VALUES (@1);`.

chore: return 0 instead of error for explain affected rows

---

backend/plugin/parser/mysql/split.go
backend/plugin/parser/mysql/split_test.go
go.mod
go.sum

chore: split by delimiter if exists

---

frontend/src/components/User/Settings/CreateUserDrawer.vue
frontend/src/components/User/Settings/UserDataTable/cells/UserNameCell.vue

* move user type field to the front;
* add user name input when creating;

chore: update create member form

---

frontend/src/components/ExpirationSelector.vue
frontend/src/components/ProjectMember/AddProjectMember/AddProjectMemberForm.vue
frontend/src/components/ProjectMember/ProjectMemberTable/ProjectMemberRolePanel.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

Close BYT-5005
https://github.com/bytebase/bytebase/assets/24653555/3fe94f56-8613-4639-af74-e1caf0c5dc9e

chore: add reason field to add project member form

---

frontend/src/components/Database/DatabaseOverviewPanel.vue

fix: fetch database metadata with full view in database overview panel

---

backend/plugin/parser/errors/resources.go
backend/plugin/parser/pg/query_span_extractor.go
backend/plugin/parser/pg/test-data/query_span.yaml
backend/store/model/database.go

feat(query-span): support SQL Language Functions as the Table Source for PostgreSQL

---

frontend/src/components/IssueV1/components/StageSection/StageInfo/DatabaseInfo.vue
frontend/src/components/IssueV1/logic/utils.ts
frontend/src/components/v2/Model/DatabaseV1Name.vue

chore(frontend): show dropped database name in issue detail

---

frontend/package.json
frontend/pnpm-lock.yaml

will also solve NSelect problem

chore(frontend): upgrade vue version

---

frontend/src/components/SyncDatabaseSchema/SelectTargetDatabasesView.vue
frontend/src/components/SyncDatabaseSchema/index.vue
frontend/src/components/v2/Form/StepTab.vue

chore: tweak sync schema ui

---

backend/plugin/parser/pg/query_span_extractor.go
backend/plugin/parser/pg/test-data/query_span.yaml

feat(query-span): Support Language PLpgSQL Function for PostgreSQL

---

backend/component/iam/permission.yaml
frontend/src/components/Role/Setting/components/ImportPermissionFromRoleModal.vue
frontend/src/components/Role/Setting/components/RolePanel.vue
frontend/src/components/User/Settings/CreateUserDrawer.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json
frontend/src/types/iam/permission.ts

https://github.com/bytebase/bytebase/assets/24653555/01aafe6f-eea5-4014-8619-88ec59a14285

chore: add import permissions from role

---

frontend/src/bbkit/BBModal.vue
frontend/src/components/SyncDatabaseSchema/DiffViewPanel.vue
frontend/src/components/SyncDatabaseSchema/SchemaDiffViewer.vue
frontend/src/components/SyncDatabaseSchema/SchemaDiffViewerModal.vue
frontend/src/components/SyncDatabaseSchema/TargetDatabasesSelectPanel.vue

Close BYT-4927
https://github.com/bytebase/bytebase/assets/24653555/88ebee73-bea9-4708-b48e-7cfc82215ea8

feat: add fullscreen button to diff viewer

---

frontend/src/components/User/Settings/CreateUserDrawer.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json
frontend/src/types/iam/role.ts

chore: add roles group

---

frontend/src/components/ProvideSQLEditorContext.vue
frontend/src/views/sql-editor/SecondarySidebar/SheetTabPane/SheetTabPane.vue

chore: can show the worksheet content even if don't have access to the database

---

frontend/naive-ui.config.ts
frontend/src/App.vue
frontend/src/plugins/i18n.ts

chore: update query preserved field

---

frontend/src/components/Branch/BranchDataTable/cells/AsyncBranchNameCell.vue
frontend/src/components/Branch/BranchDataTable/index.vue

chore(frontend): fix parent branch name

---

frontend/src/components/Branch/BranchDataTable/cells/AsyncBranchNameCell.vue
frontend/src/store/modules/branch.ts

Also optimize the implementation for #10849

chore(frontend): refactor branch store cache

---

backend/plugin/advisor/mysql/advisor_statement_dml_dry_run.go
backend/tests/test-data/sql_review_mysql.yaml

fix(sql-review): check top level sql for dry run

---

backend/plugin/db/pg/pg.go

fix(pg): run set role for non-transaction statements

---

frontend/src/components/BannersWrapper.vue
frontend/src/store/modules/v1/actuator.ts

chore(frontend): default show banner false

---

frontend/src/components/ProvideSQLEditorContext.vue
frontend/src/store/modules/sqlEditorTree.ts
frontend/src/store/modules/tab.ts
frontend/src/utils/tab.ts
frontend/src/views/sql-editor/TabList/TabList.vue

chore(sql-editor): update initial connection from query

---

backend/plugin/advisor/advisor.go
backend/plugin/advisor/catalog/walk_through_for_mysql.go
backend/plugin/advisor/code.go
backend/plugin/advisor/config/sql-review.dev.yaml
backend/plugin/advisor/config/sql-review.prod.yaml
backend/plugin/advisor/mysql/advisor_event_disallow_create.go
backend/plugin/advisor/mysql/mysql_rules_test.go
backend/plugin/advisor/mysql/test/system_event_disallow.yaml
backend/plugin/advisor/sql_review.go
backend/plugin/advisor/utils_for_tests.go

chore(sql-review): add disallow create event for MySQL

---

backend/plugin/db/mongodb/mongodb.go
backend/plugin/db/mongodb/mongodb_test.go
backend/plugin/db/mongodb/sync.go
frontend/src/components/InstanceForm/DataSourceSection/DataSourceForm.vue
frontend/src/components/InstanceForm/DataSourceSection/SslCertificateForm.vue
frontend/src/utils/v1/instance.ts

And fix some compatible issues of DocumentDB.

feat: support tls of mongodb

---

frontend/src/components/ExpirationSelector.vue
frontend/src/components/Issue/panel/RequestExportPanel/index.vue
frontend/src/components/Issue/panel/RequestQueryPanel/index.vue
frontend/src/components/ProjectMember/AddProjectMember/AddProjectMemberForm.vue

chore(frontend): responsive grid for expiration days

---

frontend/src/views/sql-editor/TerminalPanel/CompactSQLEditor.vue
frontend/src/views/sql-editor/TerminalPanel/TerminalPanelV1.vue

chore(sql-editor): move the cursor to the end after typing up/down arrow key

---

backend/plugin/advisor/advisor.go
backend/plugin/advisor/code.go
backend/plugin/advisor/config/sql-review.dev.yaml
backend/plugin/advisor/config/sql-review.prod.yaml
backend/plugin/advisor/mysql/advisor_event_disallow_create.go
backend/plugin/advisor/mysql/advisor_function_disallow_create.go
backend/plugin/advisor/mysql/advisor_view_disallow_create.go
backend/plugin/advisor/mysql/mysql_rules_test.go
backend/plugin/advisor/mysql/test/system_function_disallow_create.yaml
backend/plugin/advisor/sql_review.go
backend/plugin/advisor/utils_for_tests.go

chore: add disallow create function rule

---

backend/plugin/parser/mysql/test-data/query-span/standard.yaml
backend/plugin/parser/pg/query_span_extractor.go
backend/plugin/parser/pg/test-data/query_span.yaml
backend/plugin/parser/tidb/query_span_extractor.go
backend/plugin/parser/tidb/test-data/query_span.yaml

fix(query-span): fix the table alias point asterisk with join select case

---

.github/workflows/frontend-tests.yml
frontend/src/components/v2/Model/Instance/InstanceV1Table/InstanceOperations.vue
frontend/src/plugins/i18n.test.ts

- Update notification for instance sync (the operation is asynchronous)
- Add i18n test for SQL review rules (to avoid missing localization for new rules)

chore: update i18n

---

backend/api/v1/sql_service_v2.go

fix(masking): right mask multi-column resource query

---

frontend/src/grpcweb/middlewares/errorNotificationMiddleware.ts

- Ignore notification for `UNAUTHENTICATED` error
- Add more info for `UNKNOWN` error

chore: update error message

---

backend/plugin/db/pg/dump.go

Follow the documentation, the usage of `SSLCERT`, `SSLKEY` and `SSLROOTCERT` environment variables are as same as the DSN parameters. And in DSN, they are the path of the corresponding files, instead of content.
https://www.postgresql.org/docs/current/libpq-envars.html
https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNECT-SSLCERT

fix(pg/tls): specify pem/key/cert path instead of content

---

backend/plugin/db/pg/dump.go
backend/plugin/db/pg/pg.go

I can connect and sync neon instance/database without this code.

refactor(driver/pg): remove the neon database hack code

---

frontend/src/components/SchemaTemplate/FieldTemplateForm.vue
frontend/src/components/SchemaTemplate/FieldTemplateTable.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

feat(frontend): support on_update for field templates

---

backend/plugin/parser/sql/ast/integer_def.go
backend/plugin/parser/sql/ast/variable_set_stmt.go
backend/plugin/parser/sql/engine/pg/convert.go
backend/plugin/parser/sql/engine/pg/convert_test.go

chore: update variable set stmt converter

---

frontend/src/components/Branch/BranchRebaseView/RebaseBranchSelect.vue
frontend/src/store/modules/dbGroup.ts

chore(frontend): database group when rebasing

---

backend/common/db_schema.go
frontend/src/components/Branch/BranchMergeView/MergeBranchValidationStateView.vue
frontend/src/components/Branch/BranchRebaseView/RebaseBranchValidationStateView.vue
frontend/src/components/Branch/BranchRebaseView/SelectBranchStep.vue
frontend/src/components/IssueV1/components/ActivitySection/Subscribers/SubscribeButton.vue
frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckRunButton.vue
frontend/src/components/IssueV1/components/Sidebar/ReviewSection/ReviewSection.vue
frontend/src/components/IssueV1/components/Sidebar/RollbackSection/LoggingButton.vue
frontend/src/components/SQLCheck/SQLCheckButton.vue
frontend/src/components/SchemaTemplate/ClassificationLevelBadge.vue
frontend/src/components/misc/UploadProgressButton.vue
frontend/src/plugins/ai/components/DynamicSuggestions.vue

fix: spiner size

---

frontend/src/components/IssueV1/components/ActivitySection/Activity/ActionCreator.vue
frontend/src/components/ProjectMember/AddProjectMember/AddProjectMemberForm.vue
frontend/src/components/ProjectMember/ProjectMemberTable/ProjectMemberTable.vue
frontend/src/components/User/Settings/UserDataTable/cells/UserNameCell.vue
frontend/src/components/misc/ServiceAccountTag.vue
frontend/src/components/misc/SystemBotTag.vue
frontend/src/components/v2/Select/UserSelect.vue

chore: allow to select service accounts in project

---

frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
frontend/src/components/Project/ProjectSidebarV1.vue
frontend/src/layouts/ProjectV1Layout.vue

- Database group is available for normal project
- Change history is available for tenant project

chore: database group is available for normal project

---

frontend/src/components/User/Settings/CreateUserDrawer.vue

Only show custom roles section if there is at least one custom role.

chore: update role groups in creating user form

---

frontend/src/components/TableDetailDrawer.vue
frontend/src/components/TableSchemaViewer.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/DatabaseSchema.vue
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/StringifyMetadataButton.vue
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/TableSchema.vue

chore: add view table definition in table detail drawer

---

backend/api/v1/branch_service.go
backend/plugin/advisor/oracle/advisor_index_key_number_limit.go
backend/plugin/parser/plsql/masking.go
backend/plugin/parser/plsql/plsql.go
backend/plugin/parser/plsql/query_span_extractor.go
backend/plugin/parser/plsql/replace.go
backend/plugin/schema/mysql/parse_to_metadata.go
backend/plugin/schema/mysql/parse_to_metadata_test.go
backend/plugin/schema/oracle/parse_to_metadata.go
backend/plugin/schema/oracle/parse_to_metadata_test.go
backend/plugin/schema/oracle/state.go
backend/plugin/schema/oracle/testdata/parse_to_metadata.yaml
backend/plugin/schema/pg/parse_to_metadata.go
backend/plugin/schema/pg/parse_to_metadata_test.go
backend/plugin/schema/schema.go
backend/plugin/schema/tidb/parse_to_metadata.go
backend/server/backfill.go
go.mod
go.sum

feat(branch): implement parse to metadata for Oracle

---

backend/plugin/parser/snowflake/snowflake_test.go
go.mod
go.sum

fix(parser): better snowsql syntax error message

---

backend/api/v1/database_service.go

fix: filter databases v2

---

backend/api/v1/worksheet_service.go
backend/server/onboard.go
backend/store/worksheet.go

Add individual store for worksheet, hide unnecessary concepts like payload, source, type, etc
Next:
Refactor the sheet store

chore: worksheet store

---

frontend/src/components/IssueV1/components/SQLCheckSection/OnlineMigrationAdviceExtra.vue
frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckSection.vue
frontend/src/components/IssueV1/components/Sidebar/GhostSection/common.ts
frontend/src/components/SQLCheck/SQLCheckButton.vue

chore(frontend): add changeType parameter to SQL check button when needed

---

frontend/src/components/User/Settings/CreateUserDrawer.vue

chore: update custom role description in role selector

---

frontend/src/components/Changelist/ChangelistDetail/context.ts
frontend/src/components/Database/context.ts
frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
frontend/src/utils/v1/database.ts
frontend/src/views/DatabaseGroupDetail.vue

chore(frontend): unify change data / alter schema permission checks

---

backend/plugin/db/mysql/sync.go
backend/plugin/db/tidb/sync.go

refactor: sync column default for MySQL and TiDB

---

backend/plugin/advisor/mssql/advisor_where_require.go
backend/plugin/advisor/mssql/test/statement_where_require.yaml
backend/plugin/advisor/mysql/advisor_stmt_where_required.go
backend/plugin/advisor/mysql/test/statement_where_require.yaml
backend/plugin/advisor/oracle/advisor_where_require.go
backend/plugin/advisor/oracle/test/statement_where_require.yaml
backend/plugin/advisor/snowflake/advisor_where_require.go
backend/plugin/advisor/snowflake/test/statement_where_require.yaml
backend/plugin/advisor/tidb/advisor_stmt_where_required.go
backend/plugin/advisor/tidb/test/statement_where_require.yaml

chore: require where only enforces select with a from clause (except PG)

---

backend/plugin/advisor/advisor.go
backend/plugin/advisor/code.go
backend/plugin/advisor/config/sql-review.dev.yaml
backend/plugin/advisor/config/sql-review.prod.yaml
backend/plugin/advisor/mysql/advisor_statement_disallow_using_temporary.go
backend/plugin/advisor/sql_review.go
backend/plugin/advisor/utils_for_tests.go

chore: implement disallow using temporary rule for MySQL

---

frontend/src/components/IssueV1/components/IssueStatusIconWithTaskSummary.vue
frontend/src/components/IssueV1/components/IssueTableV1.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

feat(frontend): show failed task count in issue list

---

backend/plugin/advisor/advisor.go
backend/plugin/advisor/code.go
backend/plugin/advisor/mysql/advisor_statement_where_no_equal_null.go
backend/plugin/advisor/mysql/mysql_rules_test.go
backend/plugin/advisor/mysql/test/statement_where_no_equal_null.yaml
backend/plugin/advisor/sql_review.go
backend/plugin/advisor/utils_for_tests.go

chore: implement no equal null rule for MySQL

---

backend/plugin/parser/plsql/split.go

fix: missing end semicolon for create procedure

---

backend/plugin/db/dm/dm.go
backend/plugin/db/obo/obo.go
backend/plugin/db/oracle/oracle.go

chore: oracle execute error with position info

---

.github/workflows/backend-tests.yml
.github/workflows/build-artifacts-and-draft-release.yml
.github/workflows/test_link.yml
README.md
go.mod
scripts/.goreleaser-for-darwin.yaml
scripts/.goreleaser-for-linux.yaml
scripts/Dockerfile
scripts/Dockerfile.aws
scripts/Dockerfile.bb
scripts/Dockerfile.depot
scripts/Dockerfile.render-demo
scripts/Dockerfile.sql-service
scripts/build_bytebase.sh

Reverts bytebase/bytebase#11052

chore: Revert "chore: Go 1.22.1"

---

frontend/src/components/SQLReview/components/RuleEngineIcon.vue
frontend/src/components/SQLReview/components/RuleEngineIcons.vue
frontend/src/components/v2/Model/Instance/RichEngineName.vue

chore: add tooltip for engine icon in sql review

---

backend/plugin/parser/pg/query_span_extractor.go
backend/plugin/parser/pg/test-data/query_span.yaml

feat(query-span): support PostgreSQL builtin functions as table source

---

backend/plugin/advisor/mysql/advisor_statement_disallow_using_filesort.go
backend/plugin/advisor/mysql/advisor_statement_disallow_using_temporary.go

fix: extra column checks

---

backend/api/v1/rollout_service.go

fix: validate plan steps

---

backend/plugin/advisor/code.go
backend/plugin/advisor/mysql/advisor_statement_join_strict_column_attrs.go
backend/plugin/advisor/mysql/advisor_statement_maximum_join_table_count.go
backend/plugin/advisor/mysql/advisor_table_disallow_set_charset.go
backend/plugin/advisor/utils_for_tests.go

chore: implement join column fields check

---

frontend/src/locales/zh-CN.json

chore: tweak sql rollback tips i18n

---

frontend/src/components/SchemaEditorLite/utils/columnDefaultValue.ts

chore(frontend): don't call `useI18n` outside `setup` scope

---

frontend/src/utils/v1/sql.ts
frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue
frontend/src/views/sql-editor/TabList/TabItem/Label.vue
frontend/src/views/sql-editor/TabList/TabItem/TabItem.vue

chore(frontend): generate "select top * from ..." SQL for mssql

---

frontend/src/components/SchemaEditorLite/Panels/TableColumnEditor/TableColumnEditor.vue
frontend/src/components/SchemaEditorLite/Panels/TableEditor.vue
frontend/src/components/SchemaTemplate/TableTemplateForm.vue

chore(frontend): disable changing primary keys for existed tables

---

frontend/src/views/sql-editor/SecondarySidebar/SheetTabPane/SheetList/SheetList.vue
frontend/src/views/sql-editor/Sheet/context.ts

chore: filter worksheet by project

---

frontend/src/components/IssueV1/components/Sidebar/RollbackSection/RollbackSection.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

chore: add maximum size tips of sql rollback

---

frontend/src/components/SchemaEditorLite/Panels/TableColumnEditor/TableColumnEditor.vue

maybe introduced by typescript 5
considering back to typescript 4?

chore(frontend): fix typescript complaints

---

frontend/src/components/IssueV1/components/IssueTableV1.vue
frontend/src/components/Project/ProjectIssuesPanel.vue
frontend/src/views/Home.vue
frontend/src/views/IssueDashboard.vue

Use data table for issue table to allow adjusting the header width
Close BYT-5188

chore: use data table for issue table

---

helm-charts/bytebase/templates/statefulset.yaml
helm-charts/bytebase/values.yaml

Add resources field in helm-charts

chore: Define bytebase resources in helm-charts

---

frontend/src/components/AnomalyCenter/AnomalyCenterDashboard.vue
frontend/src/components/Issue/panel/RequestExportPanel/ExportResourceForm/DatabaseResourceSelector.vue
frontend/src/components/Issue/panel/RequestQueryPanel/DatabaseResourceForm/DatabaseResourceSelector.vue
frontend/src/components/IssueV1/logic/initialize/create.ts
frontend/src/components/ProvideDashboardContext.vue
frontend/src/components/ProvideSQLEditorContext.vue
frontend/src/components/TransferDatabaseForm.vue
frontend/src/store/modules/v1/database.ts
frontend/src/views/InstanceDetail.vue

chore: remove listDatabases in frontend

---

backend/api/v1/database_service.go
frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
frontend/src/components/AnomalyCenter/AnomalyCenterDashboard.vue
frontend/src/components/Changelist/ChangelistDetail/ApplyToDatabasePanel/ApplyToDatabasePanel.vue
frontend/src/components/Issue/panel/RequestExportPanel/ExportResourceForm/DatabaseResourceSelector.vue
frontend/src/components/Issue/panel/RequestQueryPanel/DatabaseResourceForm/DatabaseResourceSelector.vue
frontend/src/components/IssueV1/components/IssueSearch/useSearchScopeOptions.ts
frontend/src/components/IssueV1/logic/initialize/create.ts
frontend/src/components/ProvideDashboardContext.vue
frontend/src/components/ProvideSQLEditorContext.vue
frontend/src/components/TransferDatabaseForm.vue
frontend/src/components/v2/Select/DatabaseSelect.vue
frontend/src/types/proto/v1/database_service.ts
frontend/src/views/InstanceDetail.vue
frontend/src/views/project/ProjectDatabaseDashboard.vue
proto/gen/grpc-doc/v1/README.md
proto/gen/grpc-doc/v1/index.html
proto/generated-go/v1/database_service.pb.go
proto/v1/database_service.proto

fix: filter in search database

---

frontend/public/help/routeMapList.json
frontend/src/components/DatabaseDetail/SQLEditorButtonV1.vue
frontend/src/components/IssueV1/components/HeaderSection/Actions/request/TinySQLEditorButton.vue
frontend/src/components/ProvideSQLEditorContext.vue
frontend/src/components/Quickstart.vue
frontend/src/router/index.ts
frontend/src/router/sqlEditor.ts
frontend/src/store/modules/sqlEditor/tab.ts
frontend/src/views/DashboardHeader.vue
frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue
frontend/src/views/sql-editor/EditorCommon/SharePopover.vue

chore(frontend): Unify SQL Editor URLs

---

backend/plugin/parser/base/strings.go
backend/plugin/parser/plsql/strings.go
backend/plugin/parser/plsql/strings_test.go
backend/plugin/parser/plsql/test-data/test_strings_manipulate.yaml
backend/plugin/schema/oracle/get_design_schema.go

feat(strings): oracle strings manipulator supports indexes

---

frontend/src/components/User/Settings/UserDataTableByRole/index.vue

chore: add project role tips to user data table by role

---

backend/api/v1/sql_service.go
backend/api/v1/sql_service_v2.go

chore: export only return the last result

---

backend/plugin/advisor/mysql/advisor_stmt_disallow_commit.go
backend/plugin/parser/pg/query_span_extractor.go
backend/plugin/parser/pg/test-data/query_span.yaml

feat(query-span): support PostgreSQL unnest function

---

frontend/src/utils/v1/database.ts

chore: fix database query checks

---

frontend/src/components/SQLReview/SQLReviewCreation.vue
frontend/src/components/v2/Form/StepTab.vue

chore(frontend): fix SQL review creation layout style

---

backend/enterprise/api/license.go
backend/enterprise/api/subscription.go
backend/enterprise/plugin/aws/aws.go
backend/enterprise/plugin/hub/hub.go
backend/enterprise/service/license.go

fix: enterprise limit

---

frontend/src/components/IssueV1/components/IssueTableV1.vue

Not use `EllipsisText` in `NDataTable`

fix: issue table ui

---

frontend/src/utils/v1/sql.ts
frontend/src/views/sql-editor/EditorCommon/ResultView/DataBlock.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/ColumnSortedIcon.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/TableCell.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DetailPanel.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/context.ts

chore(sql-editor): improved data sorting

---

frontend/src/components/IssueV1/components/Sidebar/ReviewSection/ReviewSection.vue

chore(frontend): tuning style

---

frontend/src/components/IssueV1/components/IssueTableV1.vue

fix: issue table height

---

backend/plugin/parser/plsql/plsql_test.go
go.mod
go.sum

chore: update plsql-parser to fix some bugs

---

backend/api/v1/auth_service.go

fix: reset service key

---

backend/plugin/advisor/mysql/advisor_statement_select_full_table_scan.go

Close https://github.com/bytebase/bytebase/issues/11267

fix: row type transform

---

backend/plugin/parser/tsql/query_span_extractor.go
backend/plugin/parser/tsql/test-data/query-span/standard.yaml

feat(query-span): support mssql view

---

frontend/src/components/IssueV1/components/IssueTableV1.vue

chore(frontend): fix issue table creator column render function

---

backend/api/v1/project_service.go
backend/plugin/vcs/gitlab/gitlab.go

pull request events are used for CI.
note/pull request events are used for interactions such as CI trigger.

chore: webhook event

---

frontend/src/components/IssueV1/components/IssueTableV1.vue

chore: fix user avatar title

---

backend/api/v1/rollout_service_plan_check.go

feat: skip plan checks for done tasks

---

backend/plugin/db/mysql/sync.go

Previously, we sync the compound statement body of function/procedure, it's hard to construct the original string because we need parameter types, names and so on.
Test passed on MySQL 5.7.23 and 8.0.32.

chore: sync full definition of procedure and function in mysql

---

backend/plugin/parser/mysql/completion.go
backend/plugin/parser/pg/completion.go

chore(completion): skip statements without semicolon

---

backend/plugin/parser/mysql/resource_change.go
backend/runner/plancheck/statement_report_executor.go

feat: resource-change mysql dml

---

frontend/src/components/ChangeHistory/ChangeHistoryTable.vue
frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/form/ChangeHistoryForm.vue
frontend/src/components/Database/DatabaseChangeHistoryPanel.vue
frontend/src/components/misc/TextOverflowPopover.vue
frontend/tsconfig.app.json
frontend/tsconfig.vitest.json

chore(frontend): renovate change history table

---

backend/plugin/parser/plsql/query_span_extractor.go

fix(query-span): fix default schema in view definition for Oracle

---

backend/api/v1/vcs_provider_service.go
frontend/src/components/DatabaseGroup/DatabaseGroupForm.vue
frontend/src/components/IdentityProviderCreateForm.vue
frontend/src/components/InstanceForm/InstanceForm.vue
frontend/src/components/Project/ProjectCreatePanel.vue
frontend/src/components/RepositoryForm.vue
frontend/src/components/Role/Setting/components/RolePanel.vue
frontend/src/components/VCS/VCSProviderBasicInfoPanel.vue
frontend/src/components/v2/Form/ResourceIdField.vue
frontend/src/views/SettingWorkspaceSSO.vue
frontend/src/views/SettingWorkspaceVCSDetail.vue
frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue

---
---
---
---
---
---
- Simplify code for the SSO form
- Remove unnecessary requirements for external URL

chore: ui optimize

---

backend/api/v1/issue_service.go
frontend/src/components/DataExportPrepForm/DataExportPrepForm.vue
frontend/src/components/DataExportPrepForm/index.ts
frontend/src/components/IssueV1/components/IssueTableV1.vue
frontend/src/components/Project/ProjectIssuesPanel.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json
frontend/src/utils/issue/index.ts
frontend/src/views/ExportCenter/index.vue

https://github.com/bytebase/bytebase/assets/24653555/d09fe82e-e273-4f80-82e8-a8aa6e2ce7c5

chore: use issue table in export center

---

frontend/src/components/Database/DatabaseChangeHistoryPanel.vue

chore(frontend): enable establish baseline for databases in tenant projects

---

frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

chore: add data export button in operations

---

backend/plugin/db/hive/dump.go
backend/plugin/db/hive/hive.go
backend/plugin/db/hive/hive_conn_pool.go
backend/plugin/db/hive/role.go
backend/plugin/db/hive/sync.go

It really takes a long time to sync instance as it do queries on after another, so I think maybe we should do something for a better performance.

chore(hive): query with connection pool

---

backend/plugin/advisor/mssql/test/column_maximum_varchar_length.yaml
backend/plugin/advisor/mssql/test/column_no_null.yaml
backend/plugin/advisor/mssql/test/column_required.yaml
backend/plugin/advisor/mssql/test/naming_identifier_no_keyword.yaml
backend/plugin/advisor/mssql/test/naming_table.yaml
backend/plugin/advisor/mssql/test/naming_table_no_keyword.yaml
backend/plugin/advisor/mssql/test/schema_backward_compatibility.yaml
backend/plugin/advisor/mssql/test/statement_select_no_select_all.yaml
backend/plugin/advisor/mssql/test/statement_where_require.yaml
backend/plugin/advisor/mssql/test/table_drop_naming_convention.yaml
backend/plugin/advisor/mssql/test/table_no_foreign_key.yaml
backend/plugin/advisor/mssql/test/table_require_pk.yaml
backend/plugin/advisor/mysql/advisor_statement_prior_backup_check.go
backend/plugin/advisor/tidb/advisor_statement_prior_backup_check.go

fix: prior backup check

---

frontend/src/views/sql-editor/EditorCommon/ResultView/DataBlock.vue

chore: reduce padding

---

backend/api/gitops/webhook.go
backend/plugin/vcs/bitbucket/bitbucket.go
backend/tests/fake/bitbucket.go
frontend/src/types/proto/v1/rollout_service.ts
proto/gen/grpc-doc/v1/README.md
proto/gen/grpc-doc/v1/index.html
proto/generated-go/v1/rollout_service.pb.go
proto/v1/rollout_service.proto

chore: bitbucket pr comment

---

backend/plugin/advisor/advisor.go
backend/plugin/advisor/code.go
backend/plugin/advisor/config/sql-review.prod.yaml
backend/plugin/advisor/mssql/advisor_column_type_disallow_list.go
backend/plugin/advisor/mssql/advisor_table_disallow_ddl.go
backend/plugin/advisor/mssql/mssql_rules_test.go
backend/plugin/advisor/mssql/test/table_disallow_ddl.yaml
backend/plugin/advisor/sql_review.go
backend/plugin/advisor/utils_for_tests.go
backend/plugin/parser/tsql/tsql.go
frontend/src/locales/sql-review/en-US.json
frontend/src/locales/sql-review/es-ES.json
frontend/src/locales/sql-review/ja-JP.json
frontend/src/locales/sql-review/vi-VN.json
frontend/src/locales/sql-review/zh-CN.json
frontend/src/types/sql-review-schema.yaml

chore(sql-review): implement disallow ddl for specific tables for SQL Server

---

frontend/src/components/RepositorySetupWizard.vue

chore: error on creating connector

---

backend/plugin/advisor/advisor.go
backend/plugin/advisor/code.go
backend/plugin/advisor/config/sql-review.prod.yaml
backend/plugin/advisor/mssql/advisor_table_disallow_dml.go
backend/plugin/advisor/mssql/mssql_rules_test.go
backend/plugin/advisor/mssql/test/table_disallow_dml.yaml
backend/plugin/advisor/sql_review.go
backend/plugin/advisor/utils_for_tests.go
frontend/src/locales/sql-review/en-US.json
frontend/src/locales/sql-review/es-ES.json
frontend/src/locales/sql-review/ja-JP.json
frontend/src/locales/sql-review/vi-VN.json
frontend/src/locales/sql-review/zh-CN.json
frontend/src/types/sql-review-schema.yaml

chore: implement disallow dml for specific tables rule

---

frontend/src/components/Project/ProjectSidebarV1.vue
frontend/src/router/dashboard/projectV1.ts
frontend/src/views/ExportCenter/index.vue

chore: add export center route in project

---

backend/api/v1/auth_service.go

Get should always show soft-deleted resource.

chore: show deleted user

---

backend/api/v1/rollout_service.go
backend/legacyapi/task.go
backend/store/task.go
frontend/src/components/IssueV1/components/DataExportSection/ExportOptionSection/ExportFormatSelector.vue
frontend/src/components/IssueV1/components/DataExportSection/ExportOptionSection/ExportOptionSection.vue
frontend/src/components/IssueV1/components/DataExportSection/ExportOptionSection/ExportPasswordInputer.vue
frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue

chore: implement update export config

---

frontend/src/components/IssueV1/components/HeaderSection/Actions/request/ExportArchiveDownloadButton.vue
frontend/src/components/IssueV1/components/HeaderSection/Actions/rollout/RolloutActionButton.vue
frontend/src/components/IssueV1/components/Panel/TaskRolloutActionPanel.vue
frontend/src/components/IssueV1/logic/action/task.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

chore: update rollout action text for data export issue

---

backend/api/v1/branch_service.go

Make it more predictable and controllable.

chore: use get design schema with empty baseline instead of dumped schema

---

frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/v1/database.ts
frontend/src/views/sql-editor/AsidePanel/SchemaPane/SchemaPane.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/SyncSchemaButton.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/common.ts

feat(sql-editor): add a button in the left bar to sync the specific database

---

backend/api/v1/project_service.go
frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
frontend/src/components/AlterSchemaPrepForm/SelectDatabaseGroupTable.vue
frontend/src/components/DatabaseGroup/DatabaseGroupForm.vue
frontend/src/components/DatabaseGroup/DatabaseGroupPanel.vue
frontend/src/components/DatabaseGroup/DatabaseGroupTable.vue
frontend/src/components/DatabaseGroup/utils.ts
frontend/src/components/v2/Model/DatabaseV1Table/DatabaseGroupTableRow.vue
frontend/src/components/v2/Model/DatabaseV1Table/DatabaseV1Table.vue
frontend/src/components/v2/Select/DatabaseGroupSelect.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/dbGroup.ts
frontend/src/types/dbGroup.ts
frontend/src/utils/databaseGroup/cel.ts
frontend/src/views/DatabaseDashboard.vue
frontend/src/views/DatabaseGroupDetail.vue
frontend/src/views/SchemaGroupDetail.vue

chore(database-group): move environment factor into cel expression

---

frontend/src/layouts/SplashLayout.vue

chore: hide branding images in auth pages

---

frontend/src/views/sql-editor/AsidePanel/WorksheetPane/SheetList/SheetList.vue

feat(sql-editor): sheet icon and adjust indents

---

frontend/src/utils/sqlEditor.ts
frontend/src/views/sql-editor/AsidePanel/WorksheetPane/SheetList/SheetList.vue
frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/ConnectionPane.vue
frontend/src/views/sql-editor/EditorCommon/EditorAction.vue
frontend/src/views/sql-editor/EditorCommon/SaveSheetModal.vue

feat(sql-editor): change connected database on the worksheet

---

backend/api/v1/sql_service.go

fix: file created time in zip

---

frontend/src/components/Issue/panel/RequestExportPanel/index.vue
frontend/src/components/Issue/panel/RequestQueryPanel/index.vue
frontend/src/components/QuickActionPanel.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json
frontend/src/views/sql-editor/EditorCommon/ResultView/RequestQueryButton.vue

chore: request query/export to request querier/exporter role

---

frontend/src/components/DataExportButton.vue
frontend/src/components/DataExportPrepForm/DataExportPrepForm.vue
frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

To be consistent with others like `Edit Schema`

chore: Data Export to Export Data

---

backend/runner/taskrun/data_export_executor.go
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunComment.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

chore: update task status words for export data issue

---

frontend/src/components/IssueV1/components/Sidebar/VCSInfo.vue

fix: vcs info sidebar

---

backend/api/gitops/github.go
backend/api/gitops/gitlab.go

mismatch webhook action and branch are expected

chore: optimize webhook wording

---

backend/api/v1/instance_service.go
backend/component/secret/vault.go
frontend/src/components/InstanceForm/DataSourceSection/DataSourceForm.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

chore: minor vault auth label tweak

---

backend/plugin/db/mssql/mssql.go
scripts/Dockerfile.depot

This reverts commit a05a7aa98c7ec2d181bd0dae74390c0963651cd3.

chore: Revert "ttttt (#11568)"

---

backend/api/v1/acl_iam.go
backend/api/v1/sql_service.go
backend/plugin/parser/mysql/mysql.go
backend/runner/taskrun/data_export_executor.go

Database level: `DELETE FROM test_c WHERE id = 11`
Instance level: `CREATE DATABASE test2`

chore: implement sql execute

---

backend/demo/data/default/README.md

To prepare to adjust demo for 2.15.0.

chore: update demo data from 2.12.0 to 2.15.0

---

frontend/src/components/IssueV1/components/Sidebar/VCSInfo.vue

Also add some common saved sheets to query the metadata

chore: add bb meta instance to the demo data

---

frontend/src/components/DataExportButton.vue
frontend/src/components/IssueV1/components/DataExportSection/ExportOptionSection/ExportPasswordInputer.vue
frontend/src/components/User/Settings/CreateUserDrawer.vue
frontend/src/views/ProfileDashboard.vue

Reference: https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#preventing_autofilling_with_autocompletenew-password

fix: disable autocomplete to inputs

---

frontend/src/store/modules/sqlEditor/tab.ts

[CAUTION] just syncing the overall tab-list, not the tabs theirselves
Syncing tabs' properties are way more complex and performance consuming.

chore(sql-editor): sync tab-list across browser windows

---

frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentList.vue
frontend/src/components/IssueV1/logic/subscriber.ts

chore: do not push notification when comment issue

---

frontend/src/components/IssueV1/components/IssueTableV1.vue

chore: make bordered optional

---

frontend/src/bbkit/BBAttention.vue
frontend/src/components/CreateDataSourceExample.vue
frontend/src/components/CreateDatabasePrepForm/CreateDatabasePrepForm.vue
frontend/src/components/CreateDatabasePrepForm/CreateDatabasePrepPanel.vue
frontend/src/components/Database/DatabaseChangeHistoryPanel.vue
frontend/src/components/Database/DatabaseSlowQueryPanel.vue
frontend/src/components/InstanceForm/InstanceForm.vue
frontend/src/components/LabelEditorDrawer.vue
frontend/src/components/RepositorySelectionPanel.vue
frontend/src/components/SlowQuery/Panel/SlowQueryPanel.vue
frontend/src/components/v2/Model/Instance/InstanceRoleTable/InstanceRoleTable.vue
frontend/src/components/v2/Select/EnvironmentSelect.vue
frontend/src/components/v2/Select/InstanceSelect.vue
frontend/src/layouts/ProjectV1Layout.vue
frontend/src/views/DatabaseDetail.vue
frontend/src/views/InstanceDetail.vue
frontend/src/views/TwoFactorRequired.vue
frontend/src/views/sql-editor/AsidePanel/AsidePanel.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue
frontend/src/views/sql-editor/ResultPanel/ResultPanel.vue
frontend/src/views/sql-editor/TerminalPanel/TerminalPanelV1.vue

- Allow change environment for instance
- Select instance will auto-select the environment during database creation
- Allow query data for unassigned databases in the SQL editor
- Other UI optimize

chore: allow change instance environment

---

frontend/src/views/auth/Signin.vue

chore(frontend): fix some compiler warnings

---

frontend/src/utils/sheet.ts

chore: update default max upload file size

---

frontend/src/components/AlterSchemaPrepForm/SelectDatabaseGroupTable.vue

Remove environment column since database group has no environment attr anymore.

fix: database group selection

---

backend/api/v1/rollout_service.go
backend/api/v1/rollout_service_task.go

feat: cross-env db group target

---

backend/plugin/parser/tsql/rollback.go
backend/plugin/parser/tsql/rollback_test.go
backend/plugin/parser/tsql/test-data/test_rollback.yaml
backend/runner/taskrun/data_update_executor.go
frontend/src/components/IssueV1/components/Sidebar/PreBackupSection/common.ts

feat: implement SQL Server pre-backup

---

frontend/src/views/sql-editor/AsidePanel/SchemaPane/HoverPanel/HoverPanel.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/HoverPanel/TablePartitionInfo.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/HoverPanel/hover-state.ts
frontend/src/views/sql-editor/AsidePanel/SchemaPane/SchemaPane.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/PartitionTableNode.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/common.ts

feat(sql-editor): display hover panel for table partitions

---

backend/plugin/parser/tsql/backup.go
backend/plugin/parser/tsql/test-data/test_backup.yaml

feat(backup): support specify FROM clause for MSSQL DELETE/UPDATE

---

backend/api/lsp/completion.go
backend/api/lsp/handler.go
backend/plugin/parser/mysql/split.go
backend/plugin/parser/mysql/split_test.go

feat(completion): add space as a trigger symbol

---

backend/api/gitops/azure.go
backend/api/gitops/bitbucket.go
backend/api/gitops/common.go
backend/api/gitops/github.go
backend/api/gitops/gitlab.go
backend/utils/utils.go
backend/utils/utils_test.go
frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/ActionCreator.vue
frontend/src/components/IssueV1/components/Sidebar/VCSInfo.vue

Do our best effect to convert non-utf8 content string from GitOps.

chore(gitops): handle non-utf8 encoding character

---

frontend/vite.config.ts

Reference: https://github.com/TypeFox/monaco-languageclient?tab=readme-ov-file#vite-dev-server-troubleshooting

chore: fix monaco editor initial error

---

backend/server/routers.go
backend/server/server.go
proto/README.md

Split of https://github.com/bytebase/bytebase/pull/11674/files

chore: refactor echo routes

---

frontend/package.json
frontend/src/components/Icon/FunctionIcon.vue
frontend/src/components/Icon/ProcedureIcon.vue
frontend/src/components/Icon/index.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json
frontend/src/views/sql-editor/AsidePanel/SchemaPane/HoverPanel/CodeViewer.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/HoverPanel/FunctionInfo.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/HoverPanel/HoverPanel.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/HoverPanel/ProcedureInfo.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/HoverPanel/hover-state.ts
frontend/src/views/sql-editor/AsidePanel/SchemaPane/SchemaPane.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/FunctionNode.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/Label.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/ProcedureNode.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/common.ts

feat(sql-editor): display procedures and functions

---

frontend/src/components/SchemaEditorLite/Panels/TableEditor.vue
frontend/src/components/SchemaEditorLite/index.ts
frontend/src/components/SchemaEditorLite/spec.ts

prepare for future refactoring

chore(schema-editor): re-organize schema editor engine specs

---

frontend/src/components/KBar/useProjectActions.ts
frontend/src/components/Project/useRecentProjects.ts
frontend/src/store/modules/v1/database.ts
frontend/src/store/modules/v1/projectIamPolicy.ts

chore: fix database permission checks

---

frontend/src/views/sql-editor/EditorCommon/BatchQueryDatabasesSelector.vue

chore(sql-editor): fix wrong column text and tuning style

---

frontend/src/components/v2/Model/Instance/InstanceV1Table/InstanceV1Table.vue
frontend/src/views/Archive.vue
frontend/src/views/InstanceDashboard.vue

chore: update InstanveV1Table to NDataTable

---

frontend/src/components/Project/ProjectSwitchModal.vue
frontend/src/components/v2/Model/Instance/InstanceV1Table/InstanceV1Table.vue
frontend/src/components/v2/Model/ProjectV1Table.vue
frontend/src/views/ProjectDashboard.vue

chore: update ProjectV1Table to NDataTable

---

frontend/src/components/SyncDatabaseSchema/DatabaseSchemaSelector.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

chore: update sync schema description

---

frontend/src/components/Changelist/ChangelistDashboard/ChangelistDashboard.vue
frontend/src/components/Changelist/ChangelistDashboard/ChangelistDataTable.vue
frontend/src/components/Changelist/ChangelistDashboard/context.ts
frontend/src/components/Project/ProjectSwitchModal.vue
frontend/src/components/v2/Model/ProjectV1Table.vue

chore: migrate ChangelistTable to NTable

---

frontend/src/views/sql-editor/AsidePanel/SchemaPane/common.ts

chore: fix node type checks

---

backend/plugin/db/mysql/mysql.go

manually change the necessary lines.

chore(release/2.15.0): cp #11770 2

---

frontend/src/components/Branch/BranchDetailView.vue
frontend/src/components/Branch/BranchMergeView/MergeBranchSelect.vue

- A feature branch is only allowed to be merged to its parent.
- Main branches are not allow be merged to any branch.
Close BYT-5489

chore(branch): merge branch limitations

---

frontend/src/components/IssueV1/components/Sidebar/EarliestAllowedTime.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

feat(frontend): update rollout time now can apply to more tasks

---

frontend/src/components/InstanceForm/InstanceForm.vue

chore(frontend): sid and serviceName is alternative required for oracle

---

frontend/src/views/sql-editor/EditorCommon/BatchQueryDatabasesSelector.vue

Just extended the keyword filter, no label value picker.
Close BYT-5471

chore(sql-editor): batch query database selector can now filter db label values

---

backend/api/v1/project_service.go

Fix error: `Internal desc = found multiple database groups`

chore: fix get db group

---

backend/store/worksheet.go

fix: upsert worksheet organizer

---

backend/api/v1/common.go
frontend/src/store/modules/v1/database.ts

Works with https://github.com/bytebase/bytebase/pull/11795/files

chore: remove maximum limit in pagination

---

frontend/src/store/modules/v1/database.ts

Not using pagination until we can handle. 
Close BYT-5499

chore(frontend): default pagesize for SearchDatabases

---

frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckSection.vue
frontend/src/components/IssueV1/components/Sidebar/GhostSection/common.ts

fix: pass change type

---

frontend/src/components/Changelist/ChangelistDetail/NavBar/ExportButton.vue
frontend/src/components/Changelist/ChangelistDetail/NavBar/ImportButton.vue
frontend/src/components/Changelist/ChangelistDetail/NavBar/NavBar.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

feat(frontend): import changelist via .sql or .zip file

---

backend/api/v1/instance_service.go
backend/plugin/db/hive/hive.go
backend/plugin/db/hive/hive_conn_pool.go
backend/plugin/db/sasl.go
backend/store/data_source.go
frontend/src/components/InstanceForm/DataSourceSection/DataSourceForm.vue
frontend/src/components/InstanceForm/InstanceForm.vue

chore: support config hive with kerberos

---

backend/common/cel.go
backend/runner/approval/runner.go
frontend/src/plugins/cel/types/factor.ts

chore: use source string

---

frontend/src/components/Database/DatabaseOverviewPanel.vue
frontend/src/components/EllipsisSQLView.vue
frontend/src/components/FunctionDataTable.vue
frontend/src/components/ViewDataTable.vue

chore: update sql view for data tables

---

frontend/src/components/InstanceForm/DataSourceSection/CreateDataSourceExample.vue
frontend/src/components/InstanceForm/DataSourceSection/DataSourceSection.vue
frontend/src/components/InstanceForm/InstanceForm.vue
frontend/src/components/ProvideInstanceContext.vue
frontend/src/components/User/Settings/CreateUserDrawer.vue
frontend/src/layouts/InstanceLayout.vue
frontend/src/types/v1/dataSource.ts

- Not use `if/else` for `slot` in `ProvideInstanceContext`, this will throw the render error
- Fetch databases for instance after the creation
- Allow set the password when creating users
- Other optimize

chore: frontend fix and update

---

backend/plugin/db/obo/sync.go

`SELECT OB_VERSION() FROM DUAL` does not work in older versions.
Revert to https://github.com/bytebase/bytebase/pull/8914/files#diff-f9bb4a6e931c234ddf9c5cf565565016271185219e8f83a80b16c20297d06801 with some modifications.
Most notably, change the regexp to handle both 4.0.0.0 and 2.3.20.

fix: obo select version

---

frontend/src/plugins/ai/components/ChatPanel.vue
frontend/src/plugins/ai/logic/utils.ts

chore: add column comments to prompt

---

frontend/src/components/DatabaseGroup/MatchedDatabaseView.vue
frontend/src/components/DatabaseGroup/MatchedTableView.vue

chore: use `NVirtualList` in matched database/table view

---

frontend/src/components/Changelist/ChangelistDashboard/CreateChangelistPanel.vue
frontend/src/components/Changelist/ChangelistDetail/NavBar/ImportButton.vue
frontend/src/components/Changelist/import.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

feat(frontend): upload file when creating changelist

---

frontend/src/components/ChangeHistory/AffectedTableSelect.vue
frontend/src/components/ChangeHistory/ChangeHistoryTable.vue
frontend/src/utils/v1/changeHistory.ts

chore: add filterable to affected table select

---

frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckDetail.vue

chore: hide docs reference in standalone mode

---

backend/plugin/db/mssql/dump.go

feat: implement dump mssql indexes

---

frontend/src/components/IssueV1/components/Panel/IssueReviewActionPanel.vue
frontend/src/components/IssueV1/components/Panel/IssueStatusActionPanel.vue

chore(frontend): button style and text

---

backend/component/masker/masker.go
backend/plugin/db/util/driverutil.go

chore: scan mssql (null)uniqueidentifier type

---

frontend/src/components/Branch/BranchRolloutView/BranchRolloutView.vue
frontend/src/components/Changelist/ChangelistDashboard/CreateChangelistPanel.vue
frontend/src/components/Changelist/ChangelistDetail/NavBar/ImportButton.vue
frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue
frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
frontend/src/components/IssueV1/logic/initialize/create.ts
frontend/src/components/IssueV1/logic/plan.ts
frontend/src/components/SyncDatabaseSchema/RawSQLEditor.vue
frontend/src/store/modules/v1/sheet.ts

Best efforts by now
Added some frontend logs when sheet.engine is undefined or ENGINE_UNSPECIFIED

chore(frontend): specify sheet.engine if possible in CreateSheet 

---

backend/plugin/db/mssql/sync.go
frontend/src/components/Database/DatabaseOverviewPanel.vue

feat: sync mssql func and procedures

---

backend/api/v1/audit_log_service.go
frontend/src/components/AuditLog/AuditLogSearch/AdvancedSearchBox.vue
frontend/src/components/AuditLog/AuditLogSearch/AuditLogSearch.vue
frontend/src/components/AuditLog/AuditLogSearch/ScopeMenu.vue
frontend/src/components/AuditLog/AuditLogSearch/ScopeTags.vue
frontend/src/components/AuditLog/AuditLogSearch/TimeRange.vue
frontend/src/components/AuditLog/AuditLogSearch/ValueMenu.vue
frontend/src/components/AuditLog/AuditLogSearch/index.ts
frontend/src/components/AuditLog/AuditLogSearch/useSearchScopeOptions.ts
frontend/src/components/AuditLog/AuditLogSearch/utils.ts
frontend/src/grpcweb/methods.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/v1/auditLog.ts
frontend/src/types/auditLog.ts
frontend/src/utils/v1/advanced-search/common.ts
frontend/src/views/SettingWorkspaceAuditLog.vue
frontend/src/views/project/ProjectAuditLogDashboard.vue

Close BYT-5520
https://github.com/bytebase/bytebase/assets/24653555/b5f3daeb-d3d8-4f6c-9433-0cebfac00a7a

chore: implement advanced search for audit logs

---

backend/store/task.go

chore: update sql

---

frontend/src/components/IssueV1/components/IssueLabelSelector.vue
frontend/src/components/IssueV1/components/IssueTableV1.vue
frontend/src/components/IssueV1/components/Sidebar/IssueLabels.vue

- Extract issue label component
- Not wrap the line for labels in the issue table
- Hide labels on small screen

chore: optimize issue labels

---

frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/AffectedRowsCell.vue
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/DurationCell.vue
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/StatementCell.vue
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/TaskRunLogTable.vue
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/common.ts
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/index.ts
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunTable.vue
frontend/src/components/misc/TextOverflowPopover.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json
frontend/src/utils/v1/sheet.ts

feat(frontend): show task run log detail

---

frontend/src/views/sql-editor/EditorPanel/Welcome.vue

Ensure the two buttons have the same widths. Otherwise it looks weird when hovering the second one.
Before
After

chore(sql-editor): minor style tweaking

---

frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckBadgeBar.vue
frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckBar.vue
frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckDetail.vue
frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckModal.vue
frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckPanel.vue

Part of BYT-5556
https://github.com/bytebase/bytebase/assets/24653555/a5cae757-4908-4db8-9c35-5154e63d634b

chore: add expand button to plan check bar

---

frontend/src/components/IssueV1/components/IssueLabelSelector.vue

chore: hide delete label button

---

frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/AffectedRowsCell.vue

chore(frontend): fallback to affectedRows

---

frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/TaskRunLogTable.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

chore(frontend): i18n

---

frontend/src/views/ExportCenter/DataExportIssueDataTable/DataExportIssueDataTable.vue
frontend/src/views/ExportCenter/index.vue

chore: add labels column to data export issue table

---

frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/DetailCell/AffectedRowsCell.vue
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/DetailCell/DetailCell.vue
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/DetailCell/ErrorCell.vue
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/DetailCell/common.ts
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/DetailCell/index.ts
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/TaskRunLogTable.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

feat(frontend): show task run log error

---

backend/plugin/db/mssql/sync.go

chore: distinguish functions and procedures for sql server

---

backend/api/lsp/completion.go

chore: no auto-complete for huge sql

---

frontend/src/components/Changelist/ChangelistDetail/ApplyToDatabasePanel/ApplyToDatabasePanel.vue

fix(frontend): Changelist issue creation failed when apply to multiple databases

---

backend/demo/data/default/README.md

* Demo data schema from 2.15.0 to 2.17.0
* Add issue label
* Improve custom approval setting
* Add number of affected row review policy
* A DML issue showing number of affected row review policy

chore: update demo data from 2.15.0 to 2.17.0

---

frontend/src/components/IssueV1/components/Sidebar/RollbackSection/common.ts

chore: fix rollback switch checks

---

backend/api/v1/rollout_service.go

chore: check doUpdateSheet in related specs without pipeline

---

frontend/src/components/AdvancedSearch/TimeRange.vue

fix(frontend): use endOf the day as the upper limit of date time filter

---

frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

Maybe removed by mistake in https://github.com/bytebase/bytebase/pull/12035

chore: add back i18n of review center

---

frontend/src/components/IssueV1/components/DataExportSection/ExportOptionSection/ExportOptionSection.vue
frontend/src/components/IssueV1/components/ReviewIssueSpecSection/ReviewOptionSection/ReviewOptionSection.vue

* only show edit buttion when issue is open;

chore: tweak issue options display

---

backend/migrator/migration/prod/2.18/0004##masking_exception_user_name.sql
backend/migrator/migrator_test.go

chore: update user name in masking exceptions

---

frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
frontend/src/components/AlterSchemaPrepForm/DatabaseGroupPrevEditorModal.vue
frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
frontend/src/components/AuditLog/AuditLogDataTable.vue
frontend/src/components/Plan/components/HeaderSection/Actions/create/CreateButton.vue
frontend/src/components/Plan/components/SpecListSection/SpecCard.vue
frontend/src/components/Plan/components/StatementSection/EditorView/EditorView.vue
frontend/src/components/Plan/logic/initialize/create.ts
frontend/src/components/Plan/logic/plan-check.ts
frontend/src/components/Plan/logic/plan.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/utils/databaseGroup/issue.ts

Part of BYT-5601
https://github.com/bytebase/bytebase/assets/24653555/809503fa-9d3b-4ac9-84ff-3c071f2919e6

chore: add sql review only checkbox when creating issue

---

frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/components/InstanceForm/InstanceForm.vue

chore(frontend): always test connection before updating/adding datasources

---

backend/plugin/parser/plsql/masking.go
backend/plugin/parser/plsql/query_span_extractor.go
go.mod
go.sum

feat: upgrade plsql parser to support unicode and improve performance

---

frontend/src/components/Branch/BranchCreateView.vue
frontend/src/components/Branch/BranchDetailView.vue
frontend/src/components/Branch/BranchMergeView/BranchMergeView.vue
frontend/src/components/Branch/BranchMergeView/MergeBranchSelect.vue
frontend/src/components/Branch/BranchRebaseView/BranchRebaseView.vue
frontend/src/components/Branch/BranchRebaseView/RebaseBranchSelect.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/router/dashboard/projectV1.ts

- Create branch
- Main (parent-less) branch: project owners only
- Feature branch: project developers and owners
- Merge branch
- Main (parent-less) branch: CANNOT be merged into any other branches
- Feature branch: can be merged into its parent branch, by the creator of the branch and project owners
- Rebase branch
- Main (parent-less) branch: can rebase other branches or database schema to main branches by project owners. Default to the baseline database of the branch.
- Feature branch: can only rebase its parent branch into a feature branch, by the creator of the branch and project owners.
- Rollout branch
- Main (parent-less) branch: project owners only
- Feature branch: CANNOT be rollouted

chore(branching): permission control

---

frontend/src/components/DatabaseDetail/Settings/DatabaseSettingsPanel.vue
frontend/src/components/User/Settings/CreateUserDrawer.vue

chore(frontend): notification style

---

frontend/src/components/InstanceForm/DataSourceSection/DataSourceForm.vue
frontend/src/components/InstanceForm/InstanceForm.vue

chore: bq iam auth

---

frontend/src/components/Plan/components/HeaderSection/Actions/create/CreateIssueButton.vue
frontend/src/components/Plan/components/SpecListSection/SpecCard.vue
frontend/src/components/Plan/components/StatementSection/EditorView/EditorView.vue
frontend/src/components/Plan/components/StepSection/StepCard.vue
frontend/src/components/Plan/logic/context.ts
frontend/src/components/Plan/logic/poll.ts

Close BYT-5611
* only allow to create issue when all plan checks passed;

chore: add more checks for plan check status

---

backend/plugin/db/dynamodb/dynamodb.go
backend/plugin/db/dynamodb/sync.go

feat: sync dynamodb instance

---

backend/plugin/db/dm/dm.go
backend/plugin/db/obo/obo.go
backend/plugin/db/oracle/oracle.go

chore: oracle explain

---

backend/api/v1/project_service.go
backend/component/webhook/manager.go
backend/plugin/webhook/webhook.go

This reverts commit 467c615a717de5e1128aeccc5764296eea463a84.

chore: revert "chore: remove unused (#12149)"

---

frontend/src/views/sql-editor/AsidePanel/WorksheetPane/SheetList/SheetList.vue

chore: update sheet filter

---

frontend/src/components/SchemaEditorLite/Panels/TableColumnEditor/TableColumnEditor.vue
frontend/src/components/SchemaEditorLite/Panels/TableColumnEditor/components/DefaultValueCell.vue
frontend/src/components/SchemaEditorLite/Panels/TableColumnEditor/components/index.ts
frontend/src/components/SchemaEditorLite/utils/columnDefaultValue.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

feat(frontend): renovate default value UI for SchemaEditor

---

backend/api/v1/project_service.go
backend/api/v1/project_service_test.go
backend/api/v1/setting_service.go
frontend/src/components/ExpirationSelector.vue
frontend/src/components/GeneralSetting/MaximumRoleExpirationSetting.vue
frontend/src/components/GeneralSetting/SecuritySetting.vue
frontend/src/components/GeneralSetting/SignInFrequencySetting.vue
frontend/src/components/Issue/panel/RequestExportPanel/index.vue
frontend/src/components/Issue/panel/RequestQueryPanel/index.vue
frontend/src/components/ProjectMember/AddProjectMember/AddProjectMemberForm.vue
frontend/src/components/ProjectMember/ProjectMemberRolePanel/RoleDescription.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

feat(frontend): implement maximum role expiration setting

---

frontend/src/components/ProjectMember/ProjectMemberRolePanel/index.vue
frontend/src/components/Quickstart.vue
frontend/src/components/SensitiveData/SensitiveColumnDrawer.vue
frontend/src/components/User/Settings/CreateGroupDrawer.vue
frontend/src/router/dashboard/workspace.ts
frontend/src/router/dashboard/workspaceRoutes.ts
frontend/src/router/dashboard/workspaceSetting.ts
frontend/src/views/DashboardSidebar.vue
frontend/src/views/SettingSidebar.vue

chore: update sidebar

---

backend/api/v1/acl_iam.go
backend/api/v1/sql_service.go
backend/plugin/parser/mysql/restore.go
backend/plugin/parser/mysql/test-data/test_restore.yaml
backend/runner/taskrun/data_update_executor.go
frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/IssueCommentAction.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/restore.ts
frontend/src/store/modules/v1/sql.ts

feat: implement the frontend part of restore sql

---

frontend/src/components/Issue/panel/RequestExportPanel/index.vue
frontend/src/components/Issue/panel/RequestQueryPanel/DatabaseResourceForm/DatabaseResourceSelector.vue
frontend/src/components/Issue/panel/RequestQueryPanel/DatabaseResourceForm/Label.vue
frontend/src/components/Issue/panel/RequestQueryPanel/DatabaseResourceForm/common.ts
frontend/src/components/SchemaEditorLite/Aside/Tree.vue
frontend/src/store/modules/v1/dbSchema.ts

Close BYT-5650
https://github.com/bytebase/bytebase/assets/24653555/0622f2f2-c8d0-4cc3-8852-939eefa05aa4

chore: add lazy loading for database resource selector

---

backend/plugin/db/oracle/sync.go

feat: sync oracle db links

---

frontend/src/router/index.ts
frontend/src/views/auth/Signin.vue

Close BYT-5654
https://github.com/bytebase/bytebase/assets/24653555/3a58321a-da73-4642-8732-e3b1464ba8c6

feat: support auto signin with idp params in url

---

backend/plugin/db/driver.go
backend/plugin/db/oracle/sync.go

feat: sync table and column comments for Oracle

---

backend/component/sheet/sheet.go
backend/plugin/db/dynamodb/dynamodb.go
backend/plugin/parser/partiql/split.go
backend/plugin/parser/partiql/split_test.go
backend/runner/taskrun/executor.go
backend/server/minimal.go
go.mod
go.sum

feat: implement dynamodb execute

---

frontend/src/components/ChangeHistory/ChangeHistoryDetail.vue
frontend/src/components/ChangeHistory/ChangeHistoryTable.vue
frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/form/ChangeHistoryChangeItem.vue
frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/form/ChangeHistoryForm.vue
frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/form/ChangeHistoryTable/ChangeHistoryTable.vue
frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/form/ChangeHistoryTable/IssueUID.vue
frontend/src/components/Changelist/ChangelistDetail/ChangeTable/Source.vue
frontend/src/components/CreateDatabasePrepForm/CreateDatabasePrepForm.vue
frontend/src/components/DatabaseDetail/ChangeHistoryBrief.vue
frontend/src/components/Issue/panel/RequestExportPanel/index.vue
frontend/src/components/Issue/panel/RequestQueryPanel/index.vue
frontend/src/components/ProjectMember/ProjectMemberRolePanel/RoleDescription.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/v1/changeHistory.ts
frontend/src/types/changeHistory.ts
frontend/src/views/ReviewCenter/SQLReviewIssueDataTable/SQLReviewIssueDataTable.vue

- Support filter by issue title. Close BYT-5603
- Optimize issue link (use issue name)

chore: optimize change history table

---

frontend/src/views/sql-editor/AsidePanel/GutterBar/GutterBar.vue

chore: fix button position

---

backend/api/v1/plan_service.go

Revert part of https://github.com/bytebase/bytebase/pull/12242

fix: revert update task

---

frontend/src/components/AlterSchemaPrepForm/SchemaEditorSQLCheckButton/SchemaEditorSQLCheckButton.vue
frontend/src/components/Branch/BranchSQLCheckButton.vue
frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckSection.vue
frontend/src/components/SQLCheck/SQLCheckButton.vue
frontend/src/components/SQLCheck/SQLCheckSummary.vue

And auto-popup the SQL review result model

chore: optimize sql review panel

---

frontend/src/components/ExpirationSelector.vue

chore: fix expiration options filter

---

backend/api/v1/sql_service.go
backend/plugin/parser/base/interface.go
backend/plugin/parser/base/span.go
backend/plugin/parser/errors/resources.go
backend/plugin/parser/mysql/completion.go
backend/plugin/parser/mysql/query_span.go
backend/plugin/parser/mysql/query_span_test.go
backend/plugin/parser/pg/completion.go
backend/plugin/parser/pg/query_span.go
backend/plugin/parser/pg/query_span_test.go
backend/plugin/parser/plsql/backup.go
backend/plugin/parser/plsql/plsql.go
backend/plugin/parser/plsql/query_span.go
backend/plugin/parser/plsql/query_span_extractor.go
backend/plugin/parser/plsql/query_span_test.go
backend/plugin/parser/plsql/replace.go
backend/plugin/parser/plsql/strings.go
backend/plugin/parser/plsql/test-data/query_span.yaml
backend/plugin/parser/snowflake/query_span.go
backend/plugin/parser/snowflake/query_span_test.go
backend/plugin/parser/tidb/query_span.go
backend/plugin/parser/tidb/query_span_test.go
backend/plugin/parser/tsql/completion.go
backend/plugin/parser/tsql/query_span.go
backend/plugin/parser/tsql/query_span_test.go
backend/plugin/schema/oracle/get_design_schema.go
backend/plugin/schema/oracle/parse_to_metadata.go
backend/runner/taskrun/data_export_executor.go
backend/store/model/database.go

feat: query span support database links for oracle

---

frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
frontend/src/components/AlterSchemaPrepForm/ProjectStandardView.vue
frontend/src/components/DatabaseDetail/SQLEditorButtonV1.vue
frontend/src/components/ExternalTableDetailDrawer.vue
frontend/src/components/TableDetailDrawer.vue
frontend/src/components/TransferDatabaseForm.vue
frontend/src/components/TransferDatabaseForm/MultipleDatabaseSelector.vue
frontend/src/components/TransferOutDatabaseForm/TransferOutDatabaseForm.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/v1/project.ts
frontend/src/types/v1/project.ts

- Fix: database filter not work in alter schema drawer
- Fix: invalid search scopes for database group
- Fix: cannot find the default project if we refresh page in the instance detail page
- Optimize: show selected databases in the tooltip

fix: database filter & default project

---

backend/plugin/parser/base/span.go
backend/plugin/parser/pg/query_span_extractor.go
backend/store/model/database.go

feat: support sequence for postgres query span

---

backend/plugin/parser/sql/ast/create_view_stmt.go
backend/plugin/parser/sql/engine/pg/convert.go
backend/plugin/parser/sql/engine/pg/convert_test.go

feat: convert create view statement for pg

---

frontend/src/components/EnvironmentForm/Form.vue
frontend/src/components/EnvironmentForm/context.ts
frontend/src/views/EnvironmentDashboard.vue
frontend/src/views/EnvironmentDetail.vue
frontend/src/views/sql-editor/Setting/Environment/Environment.vue
frontend/src/views/sql-editor/Setting/Sidebar/common.ts

This UI is simplified since we've hide the environment policy settings and SQL review settings.

feat(sql-editor): environment management in sql editor

---

frontend/src/store/modules/v1/subscription.ts

chore: datetime format for license expiration time

---

scripts/.air.toml

https://developer.apple.com/forums/thread/738275
https://go-review.googlesource.com/c/go/+/511355

fix: make go build work

---

frontend/src/components/ChangeHistory/ChangeHistoryDataTable.vue
frontend/src/components/ChangeHistory/ChangeHistoryDetail.vue
frontend/src/components/ChangeHistory/index.ts
frontend/src/components/Database/DatabaseChangeHistoryPanel.vue
frontend/src/components/ProjectChangeHistoryPanel.vue
frontend/src/utils/v1/changeHistory.ts

* prepare to implement pagination for change histories in frontend;

chore(frontend): update change history data table

---

backend/plugin/parser/pg/differ.go
backend/plugin/parser/pg/test-data/test_differ_data.yaml
backend/plugin/parser/sql/ast/create_view_stmt.go
backend/plugin/parser/sql/ast/select_stmt.go
backend/plugin/parser/sql/engine/pg/convert.go

feat: implement pg sync schema for view

---

frontend/src/components/InstanceForm/Form.vue
frontend/src/utils/util.ts
frontend/src/views/sql-editor/Setting/Instance/Instance.vue

- Sync URL hash
- Hide archive / restore button

chore(sql-editor): minor updates for setting -> instance

---

backend/plugin/parser/pg/differ.go
backend/plugin/parser/pg/test-data/test_differ_data.yaml
backend/plugin/parser/sql/ast/comment_stmt.go
backend/plugin/parser/sql/engine/pg/convert.go
backend/plugin/parser/sql/engine/pg/deparse.go

feat: pg sync schema supports comments of views

---

backend/api/v1/database_service.go
frontend/src/components/ChangeHistory/AffectedTableSelect.vue
frontend/src/components/ChangeHistory/ChangeHistoryDataTable.vue
frontend/src/components/ChangeHistory/ChangeTypeSelect.vue
frontend/src/components/ChangeHistory/PagedChangeHistoryTable.vue
frontend/src/components/ChangeHistory/index.ts
frontend/src/components/Database/DatabaseChangeHistoryPanel.vue
frontend/src/types/changeHistory.ts
scripts/.air.toml

https://github.com/bytebase/bytebase/assets/24653555/acf51554-f576-4eee-97ee-91b771f74d38

feat(frontend): implement pagination for change history table

---

frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
frontend/src/components/Changelist/ChangelistDashboard/CreateChangelistPanel.vue
frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/AddChangePanel.vue
frontend/src/components/CustomApproval/Settings/components/CustomApproval/ExternalApprovalNodesPanel/NodeDrawer.vue
frontend/src/components/DataExportPrepForm/DataExportPrepForm.vue
frontend/src/components/Database/DatabaseChangeHistoryPanel.vue
frontend/src/components/InstanceAssignment.vue
frontend/src/components/IssueV1/components/Panel/CommonDrawer.vue
frontend/src/components/LabelEditorDrawer.vue
frontend/src/components/Project/ProjectCreatePanel.vue
frontend/src/components/SensitiveData/components/SemanticTemplateDrawer.vue
frontend/src/components/User/Settings/CreateUserDrawer.vue

fix: limit drawer max with

---

frontend/src/components/ProjectWebhookForm.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/router/dashboard/workspace.ts
frontend/src/router/dashboard/workspaceRoutes.ts
frontend/src/store/modules/v1/setting.ts
frontend/src/types/v1/projectWebhook.ts
frontend/src/views/DashboardSidebar.vue
frontend/src/views/SettingWorkspaceIM.vue
frontend/src/views/SettingWorkspaceIntegrationSlack.vue

- Configure IM setting (Missing docs)
- Enable direct messages

chore: support set im

---

frontend/src/components/Plan/components/PlanCheckRunStatusIcon.vue
frontend/src/components/Plan/components/PlanDataTable/PlanDataTable.vue

chore: add plan check run status column

---

frontend/src/components/DatabaseGroup/DatabaseGroupPanel.vue
frontend/src/components/IssueV1/logic/plan.ts

chore: use `dbGroup.matchedDatabases` instead of fetching them

---

frontend/src/components/Database/DatabaseChangeHistoryPanel.vue
frontend/src/components/ProjectChangeHistoryPanel.vue

chore: fetch db metadata skip cache in db change history list page

---

frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
frontend/src/components/IssueV1/components/Sidebar/GhostSection/common.ts
frontend/src/components/IssueV1/logic/initialize/create.ts
frontend/src/components/Plan/logic/initialize/create.ts
frontend/src/components/SyncDatabaseSchema/index.vue

fix(frontend): refactor `sqlList` param to `sqlMap`

---

backend/plugin/parser/pg/backup.go
backend/plugin/parser/pg/backup_test.go
backend/plugin/parser/pg/pg.go
backend/plugin/parser/pg/test-data/test_backup.yaml
backend/runner/taskrun/data_update_executor.go
frontend/src/components/IssueV1/components/Sidebar/PreBackupSection/common.ts

feat: implement prior backup for postgres

---

backend/plugin/parser/pg/differ.go
backend/plugin/parser/pg/system_objects.go

chore: sync schema ignore backup schema

---

backend/plugin/db/pg/pg.go

chore: run single do statement without txn for pg

---

frontend/src/components/Project/ProjectCreatePanel.vue
frontend/src/components/TransferDatabaseForm.vue
frontend/src/components/v2/Model/DatabaseV1Table/DatabaseV1Table.vue
frontend/src/components/v2/Model/ProjectV1Table.vue
frontend/src/router/sqlEditor.ts
frontend/src/store/modules/v1/database.ts
frontend/src/views/sql-editor/AsidePanel/GutterBar/GutterBar.vue
frontend/src/views/sql-editor/Setting/Project/Detail.vue
frontend/src/views/sql-editor/Setting/Project/Project.vue
frontend/src/views/sql-editor/Setting/Sidebar/common.ts

feat(sql-editor): SQL Editor setting for project

---

backend/api/v1/setting_service.go
frontend/src/components/ProjectWebhookForm.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/views/SettingWorkspaceIM.vue

- For configured IM
- For webhook (if IM not configured)

chore: optimize IM config

---

backend/api/v1/sql_service.go

feat: view comments for oracle

---

backend/runner/approval/runner.go

Break the loop as early as possible:
1. Sort risks by level
2. Skip duplicate loop
3. We can break the loop once we found the highest level

chore: improve risk calculation speed

---

frontend/src/components/Plan/components/StatementSection/EditorView/EditorView.vue
frontend/src/components/Plan/logic/initialize/create.ts

Follow by https://github.com/bytebase/bytebase/pull/12265

chore(frontend): share one sheet among multiple specs in a plan

---

go.mod
go.sum

chore: upgrade plsql parser

---

backend/plugin/db/obo/sync.go

fix: fix obo schema metadata

---

backend/plugin/parser/mysql/completion.go
backend/plugin/parser/mysql/test-data/test_completion.yaml

feat(completion): support insert for mysql

---

frontend/src/store/modules/v1/database.ts
frontend/src/views/InstanceDetail.vue

fix: clear cache after sync

---

frontend/src/components/ProvideDashboardContext.vue

@boojack do you think this could resolve BYT-5704 ?

chore(frontend): avoid unnecessary requests

---

backend/plugin/advisor/mysql/advisor_insert_row_limit.go
backend/plugin/advisor/mysql/advisor_statement_affected_row_limit.go
backend/plugin/advisor/mysql/advisor_statement_disallow_using_filesort.go
backend/plugin/advisor/mysql/advisor_statement_disallow_using_temporary.go
backend/plugin/advisor/mysql/advisor_statement_dml_dry_run.go
backend/plugin/advisor/mysql/advisor_statement_query_minumum_plan_level.go
backend/plugin/advisor/mysql/advisor_statement_select_full_table_scan.go
backend/plugin/advisor/pg/advisor_insert_row_limit.go
backend/plugin/advisor/pg/advisor_statement_affected_row_limit.go
backend/plugin/advisor/pg/advisor_statement_dml_dry_run.go
backend/plugin/advisor/tidb/advisor_statement_dml_dry_run.go
backend/plugin/advisor/utils.go

fix: set role for pg advisor query

---

frontend/src/components/ChangeHistory/AffectedTableSelect.vue

chore(frontend): fix affected table filter in changelist 🔥

---

frontend/src/store/modules/sqlEditor/tab.ts
frontend/src/utils/web-storage.ts

- Namespacing
- Don't erase data when logging out

refactor(sql-editor): namespacing local storage keys by user uid

---

frontend/src/components/TransferOutDatabaseForm/TransferOutDatabaseForm.vue
frontend/src/components/v2/Select/ProjectSelect.vue

For project selector
For database transfer

chore: optimize project select in db transfer

---

backend/api/v1/org_policy_service.go
backend/api/v1/project_service.go
backend/component/webhook/manager.go
backend/migrator/migration/prod/2.20/0000##iam_policy_all_users.sql
backend/migrator/migrator_test.go
backend/runner/mail/slow_query_weekly_mail.go
backend/store/principal.go
backend/utils/member.go
backend/utils/utils.go
frontend/src/components/ProjectMember/ProjectMemberRolePanel/index.vue
frontend/src/types/v1/user.ts
frontend/src/utils/v1/project.ts
frontend/src/views/ProfileDashboard.vue

chore: update allUsers in IAM policy

---

frontend/src/components/IssueV1/components/Sidebar/EarliestAllowedTime.vue

chore: allow setting earliest allowed time to database group issues

---

frontend/src/components/EnvironmentForm/Form.vue

fix(frontend): update button disabled 🔥

---

backend/plugin/parser/mysql/query.go
backend/plugin/parser/mysql/query_test.go

feat: allow desc and show commands in sql editor read only mode for mysql

---

frontend/src/components/IssueV1/logic/initialize/create.ts
frontend/src/components/Plan/logic/initialize/create.ts

fix(frontend): initialSQL check condition 🔥

---

frontend/src/components/Plan/components/HeaderSection/Actions/create/CreateIssueButton.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

chore(review-center): add confirm dialog

---

backend/plugin/advisor/code.go
backend/plugin/advisor/oracle/advisor_statement_dml_dry_run.go
backend/plugin/advisor/sql_review.go
backend/plugin/parser/plsql/backup.go
backend/runner/plancheck/statement_report_executor.go
frontend/src/types/sql-review-schema.yaml

feat(advisor): implement oracle dry run

---

backend/api/v1/auth_service.go
backend/api/v1/setting_service.go
frontend/src/components/GeneralSetting/DomainRestrictionSetting.vue
frontend/src/components/GeneralSetting/SecuritySetting.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
go.mod
go.sum

* implement UI for domain restriction setting;
* add validator to check domain name in backend;

feat(frontend): domain restriction setting

---

backend/runner/taskrun/executor.go
backend/runner/taskrun/schema_update_ghost_cutover_executor.go

fix: fix the change resources for change list

---

frontend/src/locales/zh-CN.json

chore: tweak i18n of email

---

backend/plugin/db/mssql/mssql.go
backend/plugin/db/mssql/sync.go

fix: write pseudo definition of encrypted udf/view

---

frontend/src/components/GeneralSetting/DomainRestrictionSetting.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/views/SettingWorkspaceGeneral.vue
frontend/src/views/SettingWorkspaceMember.vue

chore: add popover to create group button

---

backend/api/lsp/completion.go
backend/api/lsp/handler.go

Reverts bytebase/bytebase#11666

chore: Revert "feat(completion): add newline as a trigger symbol"

---

frontend/src/components/MonacoEditor/editor.ts

https://github.com/microsoft/monaco-editor/issues/4270

chore: accessibilitySupport off

---

frontend/src/components/AdvancedSearch/useCommonSearchScopeOptions.ts
frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
frontend/src/components/DatabaseGroup/DatabaseGroupPanel.vue
frontend/src/components/ProvideDashboardContext.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/v1/instance.ts
frontend/src/views/sql-editor/AsidePanel/SchemaPane/SchemaPane.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/actions.tsx

1. Use project scope for SearchDatabases/SearchInstances ... requests if possible. (Close BYT-5764)
2. (SQL Editor) Ask for confirmation when double clicking the table name or "Preview table data" if the current editing statement is not empty. (Close BYT-5762)

chore(frontend): fixes for lx

---

backend/plugin/db/mysql/sync.go

close BYT-5767
mysql 5.7 doesn't support check constraints

fix: ignore check constraints for mysql 5.7

---

backend/legacyapi/policy.go
frontend/src/components/GeneralSetting/SecuritySetting.vue
frontend/src/components/Project/ProjectGeneralSettingPanel.vue
frontend/src/components/SQLCheck/SQLCheckPanel.vue

chore: support RESTRICT_ISSUE_CREATION_FOR_SQL_REVIEW policy in project level

---

frontend/src/components/IssueV1/IssueDetailPage.vue
frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckSection.vue
frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
frontend/src/components/IssueV1/components/StatementSection/SDLView/SDLView.vue
frontend/src/components/IssueV1/components/StatementSection/StatementSection.vue
frontend/src/components/IssueV1/components/StatementSection/useSQLAdviceMarkers.ts
frontend/src/components/Plan/PlanDetailPage.vue
frontend/src/components/Plan/components/SQLCheckSection/SQLCheckSection.vue
frontend/src/components/Plan/components/StatementSection/EditorView/EditorView.vue
frontend/src/components/Plan/components/StatementSection/StatementSection.vue
frontend/src/components/Plan/components/StatementSection/useSQLAdviceMarkers.ts
frontend/src/components/SQLCheck/SQLCheckButton.vue
frontend/src/components/SQLCheck/SQLCheckPanel.vue

feat(frontend): provide SQL advice markers while previewing issue

---

frontend/src/components/EmailInput.vue
frontend/src/components/GeneralSetting/BrandingSetting.vue
frontend/src/components/User/Settings/CreateGroupDrawer.vue
frontend/src/components/User/Settings/CreateUserDrawer.vue

Close BYT-5728
https://github.com/bytebase/bytebase/assets/24653555/6f038454-c0a1-4b32-8f7d-e5f803bb6370

chore: update email input with workspace domain

---

backend/plugin/parser/mysql/completion.go
backend/plugin/parser/partiql/completion.go
backend/plugin/parser/pg/completion.go
backend/plugin/parser/tsql/completion.go

chore: ignore symbols for completion

---

frontend/src/components/Project/ProjectSidebarV1.vue
frontend/src/components/Project/useProjectSidebar.ts
frontend/src/components/v2/Model/ProjectV1Table.vue

fix: switch project

---

backend/api/lsp/completion.go

chore: change candidate ordering

---

backend/api/lsp/commands.go

chore: add scene config for completion

---

backend/api/lsp/handler.go

chore: remove useless logs

---

backend/api/lsp/completion.go
backend/api/lsp/handler.go
backend/plugin/parser/base/complete.go
backend/plugin/parser/base/interface.go
backend/plugin/parser/mysql/completion.go
backend/plugin/parser/mysql/completion_test.go
backend/plugin/parser/partiql/completion.go
backend/plugin/parser/partiql/completion_test.go
backend/plugin/parser/pg/completion.go
backend/plugin/parser/pg/completion_test.go
backend/plugin/parser/tsql/completion.go
backend/plugin/parser/tsql/completion_test.go

feat: implement completion for different scenes

---

frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
frontend/src/components/MonacoEditor/composables/useAutoComplete.ts
frontend/src/components/Plan/components/StatementSection/EditorView/EditorView.vue
frontend/src/components/SchemaEditorLite/Panels/CommonCodeEditor.vue
frontend/src/views/sql-editor/EditorPanel/SQLEditor.vue

chore(frontend): set auto-complete scene

---

frontend/src/components/AdvancedSearch/useCommonSearchScopeOptions.ts
frontend/src/store/modules/v1/database.ts

chore(frontend): use store cache is need not to re-fetch data

---

backend/plugin/parser/mysql/differ.go
backend/plugin/parser/mysql/test-data/differ/test_differ_table.yaml

fix(differ): consider index category in differ

---

backend/plugin/webhook/wecom/app.go
backend/plugin/webhook/wecom/wecom.go

todo:
- validation
- cache token

feat: impl wecom dm

---

frontend/src/components/SQLReview/SQLReviewInfo.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

 chore: update sql review config desc for resource

---

frontend/src/components/EmailInput.vue
frontend/src/components/User/Settings/UserDataTable/cells/UserNameCell.vue
frontend/src/views/ProfileDashboard.vue

chore: update email input in user profile page

---

backend/plugin/db/clickhouse/clickhouse.go

fix: clickhouse convert tuple/array/map

---

backend/plugin/parser/tsql/completion.go
backend/plugin/parser/tsql/completion_test.go
backend/plugin/parser/tsql/test-data/test_completion.yaml

feat(completion): definition for mssql column

---

backend/api/lsp/completion.go

chore: specified candidate order for mssql

---

backend/plugin/parser/tsql/completion.go

chore: use correct root rule for mssql query

---

frontend/src/components/InstanceForm/DataSourceSection/DataSourceForm.vue

chore: tweak eslint warnings

---

frontend/src/components/SchemaEditorLite/Panels/IndexesEditor/IndexesEditor.vue

chore: disallow to edit pk for tidb

---

backend/plugin/db/redis/redis.go

chore: remove auto-detect redis cluster

---

backend/api/v1/auth_service.go
backend/store/principal.go
backend/store/stats.go
frontend/src/components/User/Settings/CreateUserDrawer.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

chore: not store the workspace member role

---

backend/plugin/schema/mysql/state.go
backend/plugin/schema/mysql/stringify_table.go
backend/plugin/schema/tidb/state.go

chore: write AUTO_INCREMENT uppercase in Bytebase standard format

---

backend/plugin/db/mysql/sync.go

fix: sync mysql check constraints at least 8.0.16

---

frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/views/sql-editor/EditorCommon/ExecuteHint.vue
frontend/src/views/sql-editor/EditorPanel/EditorPanel.vue
frontend/src/views/sql-editor/EditorPanel/Welcome.vue
frontend/src/views/sql-editor/context.ts

feat(sql-editor): add "Add a new instance" to SQL Editor welcome page

---

frontend/src/components/MonacoEditor/composables/useLineHighlights.ts

Fix [09] of BYT-5815
FYI @h3n4l

chore(frontend): delay 1 render frame

---

frontend/src/components/IssueV1/components/BatchIssueActionsV1.vue
frontend/src/components/IssueV1/components/Panel/BatchIssueStatusActionPanel.vue
frontend/src/components/IssueV1/components/Panel/IssueStatusActionPanel.vue
frontend/src/components/IssueV1/logic/action/issue.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

chore(frontend): rename "cancel" issue to "close" issue

---

frontend/src/components/IssueV1/components/BannerSection.vue
frontend/src/components/IssueV1/components/HeaderSection/Actions/Actions.vue
frontend/src/utils/v1/issue/rollout.ts

chore(frontend): hide review things when an issue is force rolled-out

---

backend/store/database.go

chore: update database show deleted

---

frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/views/sql-editor/ResultPanel/BatchQuerySelect.vue
frontend/src/views/sql-editor/ResultPanel/ResultPanel.vue

Useful when batch querying a lot of databases
Close BYT-5835

feat(sql-editor): add a switch to toggle show/hide empty results

---

frontend/src/components/Project/ProjectIssuesPanel.vue
frontend/src/views/MyIssues.vue

feat(frontend): memoize OPEN/CLOSE tab selection for issue filter

---

backend/api/v1/rollout_service.go
backend/api/v1/rollout_service_task.go
backend/store/deploy.go

chore: transfrom steps from deployment config

---

frontend/src/components/EmailInput.vue

chore(frontend): fix vue runtime warning

---

frontend/src/views/MyIssues.vue

chore(frontend): fix dual spinner

---

frontend/src/components/IssueV1/components/BannerSection.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

chore(frontend): issue "closed" wording

---

backend/api/v1/sql_service.go

fix: support db connection string as host

---

backend/plugin/parser/plsql/query_span_extractor.go

chore: consider db link name with dot

---

frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/sqlEditor/tree.ts
frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/ConnectionPane.vue
frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/DatabaseNode.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/RequestQueryButton.vue

chore: hide databases without query permissions by default

---

frontend/src/components/GitIcon.vue
frontend/src/components/TenantIcon.vue
frontend/src/views/DatabaseGroupDetail.vue

chore: update db group detail page

---

backend/plugin/db/bigquery/bigquery.go
backend/plugin/db/hive/hive.go
backend/plugin/db/spanner/spanner.go
frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue

chore: show both error msg and result rows

---

frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
frontend/src/components/AlterSchemaPrepForm/SchemaEditorSQLCheckButton/SchemaEditorSQLCheckButton.vue
frontend/src/components/SQLCheck/SQLCheckButton.vue

chore(frontend): can enable online migration in schema editor modal

---

backend/plugin/parser/pg/differ.go
backend/plugin/parser/pg/system_objects.go

Reverts bytebase/bytebase#12326
close BYT-5847

chore: Revert "chore: sync schema ignore backup schema"

---

frontend/src/components/ProjectDeploymentConfigPanel.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/v1/deploymentConfig.ts

chore: add reset button to deployment config

---

backend/api/v1/plan_service.go

chore: fix timestamp handler for issue comments

---

backend/api/v1/issue_service.go

chore: check task run status when updating issue status

---

frontend/src/Splash.vue
frontend/src/components/Project/useProjectSidebar.ts
frontend/src/components/ProvideDashboardContext.vue
frontend/src/components/v2/Model/ProjectV1Table.vue
frontend/src/main.ts
frontend/src/store/modules/v1/database.ts
frontend/src/views/DatabaseDashboard.vue

- An initial spinner
- Some optimizations
Will keep going

chore(frontend): performance optimization

---

frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/DetailCell/DatabaseSyncCell.vue
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/DetailCell/DetailCell.vue
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/DetailCell/StatusUpdateCell.vue
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/DetailCell/TransactionControlCell.vue
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/DurationCell.vue
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/LogTimeCell.vue
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/TaskRunLogTable.vue
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/common.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

- New taskRunLogEntryTypes supported
- DATABASE_SYNC
- TASK_RUN_STATUS_UPDATE
- TRANSACTION_CONTROL
- Add a "Time" column
- Add a popover to "Duration" to show start/end time in detail

chore(frontend): task run log extended

---

backend/api/v1/database_service.go

chore: update error message in getOpenAIResponse

---

frontend/src/main.ts

parse URL search params as early as possible

chore(frontend): fix lx theme

---

frontend/src/components/SensitiveData/ClassificationView.vue

fix: enable sync classification from comment

---

backend/plugin/parser/mysql/completion.go
backend/plugin/parser/partiql/completion.go
backend/plugin/parser/pg/completion.go
backend/plugin/parser/tsql/completion.go

fix: break before caret

---

backend/migrator/migration/prod/2.21/0003##deployment_config_plan.sql
backend/migrator/migrator_test.go

Update those plan with deployement config target to `all-databases` db group.

chore: add deployment config plans migrate script

---

frontend/src/components/AdvancedSearch/useCommonSearchScopeOptions.ts
frontend/src/components/ProvideDashboardContext.vue
frontend/src/store/modules/v1/instance.ts

- Reduce duplicated computation of `instanceList`
- Reduce duplicated computation of `useCommonSearchScopeOptions`

chore(frontend): performance optimization (part.3)

---

frontend/src/components/DatabaseGroup/DatabaseGroupForm.vue
frontend/src/components/DatabaseGroup/DatabaseGroupPanel.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

chore: add description to multitenancy

---

frontend/src/components/DatabaseGroup/DatabaseGroupDataTable.vue

chore: add multitenancy tag to db group table

---

backend/api/v1/sql_service.go
backend/plugin/advisor/change_type.go
backend/plugin/advisor/pg/test/statement_check_set_role_variable.yaml
backend/plugin/advisor/sql_review.go
backend/plugin/advisor/utils_for_tests.go

I plan to resolve BYT-5584 via change type

chore: whitelist for rule with change type

---

frontend/src/components/Project/ProjectSwitchModal.vue
frontend/src/components/v2/Model/DatabaseV1Table/cells/ProjectNameCell.vue
frontend/src/components/v2/Model/ProjectV1Name.vue
frontend/src/components/v2/Model/ProjectV1Table.vue

- While filtering by keyword, jump to the "All" tab if the filter result in the "Recent" tab is empty.
- Highlight search keywords.

chore(frontend): project switch modal improvements

---

backend/runner/schemasync/syncer.go

row count and data size should always change.

chore: one less cmp

---

backend/runner/schemasync/syncer.go

Line258 sets MysqlLowerCaseTableNames

chore: remove unused equalInstanceMetadata

---

backend/api/v1/sql_service.go
backend/plugin/parser/base/span.go
backend/plugin/parser/plsql/query_span_extractor.go
backend/plugin/parser/plsql/query_span_test.go
backend/plugin/parser/plsql/test-data/query_span.yaml
backend/store/model/database.go

fix: fix db link in query span

---

frontend/src/components/SensitiveData/ClassificationView.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

* Update demo data with data classification masking
* Add learn more link
* Improve `Sync classification from comment` label spacing

chore: data classification improvement

---

frontend/src/components/DatabaseDetail/Settings/DatabaseSettingsPanel.vue
frontend/src/components/SQLReview/components/SQLReviewAttachResourcesPanel.vue
frontend/src/components/SQLReview/components/SQLReviewRulesSelectPanel.vue
frontend/src/components/SQLReview/components/SQLRuleTable.vue
frontend/src/components/SQLReview/components/SQLRuleTableWithFilter.vue
frontend/src/components/v2/Model/DatabaseV1Table/cells/ProjectNameCell.vue
frontend/src/components/v2/Select/EnvironmentSelect.vue
frontend/src/components/v2/Select/ProjectSelect.vue

- Show bound review config in the resource selector
- Optimize rule data table size
- Use "Close" instead of "Cancel" in the rule select panel. Close BYT-5896

chore: optimize review ux

---

frontend/src/main.ts

chore: remove i18n plugin in splash

---

backend/store/data_source.go
backend/store/instance.go

Avoid round-trip query for every instances.

chore: single query for all data sources

---

frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
frontend/src/components/AlterSchemaPrepForm/SchemaEditorSQLCheckButton/OnlineMigrationAdviceExtra.vue
frontend/src/components/AlterSchemaPrepForm/SchemaEditorSQLCheckButton/SchemaEditorSQLCheckButton.vue
frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckBadge.vue
frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckBar.vue
frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckDetail.vue
frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckPanel.vue
frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/detail/OnlineMigrationDetail.vue
frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/detail/index.ts
frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckBadge.vue
frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckSection.vue
frontend/src/components/IssueV1/components/Sidebar/GhostSection/GhostSwitch.vue
frontend/src/components/Plan/components/PlanCheckSection/PlanCheckBar/PlanCheckBadge.vue
frontend/src/components/Plan/components/PlanCheckSection/PlanCheckBar/PlanCheckDetail.vue
frontend/src/components/Plan/components/PlanCheckSection/PlanCheckBar/PlanCheckPanel.vue
frontend/src/components/Plan/components/SQLCheckSection/SQLCheckBadge.vue
frontend/src/components/SQLCheck/SQLCheckButton.vue
frontend/src/components/SQLCheck/SQLCheckPanel.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/sql-review/en-US.json
frontend/src/locales/sql-review/es-ES.json
frontend/src/locales/sql-review/ja-JP.json
frontend/src/locales/sql-review/zh-CN.json
frontend/src/locales/zh-CN.json
frontend/tailwind.config.js

- code 1801
- code 1802
- code 1803

chore(frontend): online migration advise improvements

---

backend/api/v1/plan_service.go

* Disallow to update tasks if issue is done or canceled.
Close BYT-5193

chore: add issue status checks

---

frontend/src/components/AlterSchemaPrepForm/SchemaEditorSQLCheckButton/SchemaEditorSQLCheckButton.vue
frontend/src/components/Branch/BranchSQLCheckButton.vue
frontend/src/components/SQLCheck/SQLCheckButton.vue
frontend/src/components/SQLCheck/SQLCheckPanel.vue

ignore online-migration advises for
- Branch editing
- Schema Editor

chore(frontend): filter online migration advises for certain cases

---

backend/plugin/db/risingwave/risingwave.go

https://docs.risingwave.com/docs/current/sql-create-index/

chore: risingwave does not have magic non-transactional DDLs

---

frontend/src/components/GeneralSetting/RestrictIssueCreationConfigure.vue

fix(frontend): feature gate for project setting

---

frontend/src/components/ProvideDashboardContext.vue

chore(frontend): fix infinite loop

---

backend/api/v1/plan_service.go
backend/common/resource_name.go
backend/component/state/state.go
backend/runner/plancheck/scheduler.go
backend/store/plan_check_run.go

feat: implement cancel plan check runs

---

backend/plugin/parser/pg/query_span_extractor.go
backend/plugin/parser/pg/query_span_test.go
backend/plugin/parser/pg/test-data/query_span.yaml

feat: support to_jsonb/row_to_json/jsonb_each series function

---

backend/api/v1/acl_iam.go
frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckBadge.vue
frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckDetail.vue
frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckRunButton.vue
frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckSection.vue
frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckBadge.vue
frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckSection.vue
frontend/src/components/IssueV1/components/StatementSection/EditorView/useTempEditState.ts
frontend/src/components/IssueV1/components/StatementSection/StatementSection.vue
frontend/src/store/modules/v1/common.ts

Part of BYT-5774
https://github.com/user-attachments/assets/ea0257c9-7632-4cf6-9e64-9e766365703c

feat(frontend): cancel plan check runs

---

frontend/src/components/IssueV1/components/Sidebar/GhostSection/common.ts

fix(frontend): turning ghost off

---

frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckBar.vue
frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckPanel.vue

chore: remove plan check run expand button in issue page

---

frontend/src/components/IssueV1/components/HeaderSection/Actions/common/IssueStatusActionButtonGroup/ExtraActionDropdownItem.vue
frontend/src/components/IssueV1/components/HeaderSection/Actions/common/IssueStatusActionButtonGroup/IssueStatusActionButton.vue
frontend/src/components/IssueV1/components/HeaderSection/Actions/common/IssueStatusActionButtonGroup/IssueStatusActionButtonGroup.vue
frontend/src/components/IssueV1/components/TaskListSection/TaskExtraActionsButton.vue
frontend/src/components/IssueV1/logic/action/issue.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

chore: update action message for issue status buttons

---

frontend/src/components/SyncDatabaseSchema/TargetDatabasesSelectPanel.vue

`databaseIdList` -> `databaseNameList`

chore: tweak variable names

---

frontend/src/components/Branch/BaselineSchemaSelector.vue

chore(frontend): fix database.uid usecase

---

backend/plugin/parser/plsql/completion.go
backend/plugin/parser/plsql/split.go
backend/plugin/parser/plsql/test-data/test_completion.yaml

chore: fix bugs for auto completion

---

frontend/src/components/IssueV1/components/TaskRunSection/TaskRunDetail.vue
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunSession/Cells/StatementCell.vue
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunSession/Cells/TimeCell.vue
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunSession/Cells/index.ts
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunSession/PostgresSessionTable.vue
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunSession/TaskRunSession.vue
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunSession/index.ts
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunTable.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

Close BYT-5931
https://github.com/user-attachments/assets/a26931ad-e1b7-46e7-b04c-20a1f4f9819f

feat: implement task run session detail

---

backend/plugin/advisor/code.go
backend/plugin/advisor/mssql/advisor_statement_disallow_mix_ddl_dml.go
backend/plugin/advisor/mssql/mssql_rules_test.go
backend/plugin/advisor/mssql/test/statement_disallow_mix_ddl_dml.yaml
backend/plugin/advisor/sql_review.go
backend/plugin/parser/tsql/backup.go
frontend/src/types/sql-review-schema.yaml
frontend/src/types/sql-review.dev.yaml
frontend/src/types/sql-review.prod.yaml

feat(advisor): mssql disallow mix ddl dml

---

backend/plugin/parser/plsql/completion.go
backend/plugin/parser/plsql/test-data/test_completion.yaml

feat(completion): plsql completion supports column alias

---

backend/plugin/parser/plsql/completion.go
backend/plugin/parser/plsql/test-data/test_completion.yaml

feat(completion): support Oracle CTE

---

backend/utils/utils.go

CEL expressions support label selectors, allowing us to add label match conditions in db group matching.

feat: support label selector

---

backend/store/principal.go
backend/store/setting.go

I think we don't need to clear all the cache, SaaS probably only needs the setting/policy/principal

chore: clear cache

---

backend/plugin/db/hive/hive.go
backend/plugin/db/hive/hive_conn_pool.go
backend/plugin/db/sasl.go
scripts/Dockerfile

also added "apt install krb5-user" to Dockerfile.

fix(hive): support different kerberos realms

---

backend/plugin/parser/plsql/test-data/query_span.yaml
go.mod
go.sum

chore: upgrade plsql parser to fix join parse

---

backend/plugin/db/mssql/sync.go

chore: sync table and column comment for sql server

---

frontend/src/locales/zh-CN.json

Close BYT-5878. Refer to https://github.com/bytebase/bytebase/pull/9944

chore: tweak i18n of auto resolve issue

---

backend/plugin/schema/mysql/state.go
backend/plugin/schema/mysql/stringify_table.go

feat(stringify): support partitions for mysql

---

frontend/src/components/PlanCheckRun/PlanCheckRunDetail.vue
frontend/src/components/User/Settings/CreateUserDrawer.vue
frontend/src/views/InstanceDetail.vue

fix: find rule with engine and type

---

backend/plugin/parser/plsql/backup.go
backend/plugin/parser/plsql/backup_test.go
backend/plugin/parser/plsql/test-data/test_backup.yaml
backend/runner/taskrun/data_update_executor.go

fix(backup): fix some bugs for Oracle

---

frontend/src/components/IssueV1/components/BannerSection.vue
frontend/src/components/IssueV1/components/HeaderSection/Actions/Actions.vue
frontend/src/utils/v1/issue/rollout.ts

chore: update review action checks

---

backend/plugin/parser/pg/differ.go
backend/plugin/parser/pg/test-data/test_differ_data.yaml

fix(differ): fix the pg create-view order

---

backend/component/iam/manager.go
backend/store/role.go

Fix https://github.com/bytebase/bytebase/pull/12971

fix: use pointer

---

frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/IssueCommentAction.vue
frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/IssueCreatedComment.vue
frontend/src/components/IssueV1/components/Sidebar/PreBackupSection/PreBackupSection.vue
frontend/src/components/IssueV1/components/Sidebar/PreBackupSection/TaskRollbackButton.vue
frontend/src/components/IssueV1/components/Sidebar/PreBackupSection/common.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

Close BYT-5926
https://github.com/user-attachments/assets/4a343e60-301b-462c-8f93-a78c0bdaf1bf

chore(frontend): move rollback button from issue comment to issue sidebar

---

proto/store/policy.proto
proto/v1/org_policy_service.proto

chore: add data source query policy definition

---

backend/api/v1/acl.go

chore: remove instance check

---

frontend/src/components/AdvancedSearch/useCommonSearchScopeOptions.ts
frontend/src/components/DatabaseGroup/DatabaseGroupForm.vue
frontend/src/components/DatabaseGroup/utils.ts
frontend/src/types/quickAction.ts
frontend/src/views/DatabaseGroupDetail.vue

Part of removing `searchInstances` in frontend.

chore: use database's instance resources for db group

---

backend/plugin/parser/pg/system_objects.go

Followup of https://github.com/bytebase/bytebase/pull/12874/files

fix: fix typo columar_internal -> columnar_internal

---

backend/api/v1/issue_service.go

fix: issue status update reason

---

backend/plugin/parser/tsql/query_span_extractor.go
backend/plugin/parser/tsql/test-data/query-span/standard.yaml

fix(query-span): support mssql builtin functions

---

backend/api/v1/sql_service.go
backend/legacyapi/policy.go
backend/store/data_source.go
backend/store/instance.go
frontend/src/components/EnvironmentForm/AccessControlConfigure.vue
frontend/src/customAppProfile.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/types/appProfile.ts
frontend/src/views/project/ProjectSettingPanel.vue
frontend/src/views/sql-editor/EditorCommon/EditorAction.vue
frontend/src/views/sql-editor/EditorCommon/QueryContextSettingPopover.vue

feat(sql-editor): allow to query with selected data source

---

frontend/src/components/AnomalyCenter/AnomalyTable.vue
frontend/src/components/SensitiveData/SensitiveColumnView.vue
frontend/src/components/SlowQuery/Panel/SlowQueryPanel.vue
frontend/src/components/SlowQuery/Settings/SlowQuerySettings.vue
frontend/src/components/SlowQuery/Settings/components/SlowQueryPolicyTable.vue
frontend/src/components/TransferDatabaseForm.vue
frontend/src/components/TransferDatabaseForm/TransferSourceSelector.vue
frontend/src/layouts/InstanceLayout.vue
frontend/src/router/dashboard/workspaceSetting.ts
frontend/src/types/slowQuery.ts
frontend/src/views/Archive.vue
frontend/src/views/SettingWorkspaceSubscription.vue

chore: remove duplicated useInstanceStore

---

frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentList.vue
frontend/src/components/IssueV1/components/IssueCommentSection/Subscribers/SubscriberList.vue
frontend/src/components/IssueV1/components/IssueCommentSection/Subscribers/Subscribers.vue
frontend/src/components/IssueV1/logic/subscriber.ts

chore: add permission checks for issue subscribe section

---

frontend/src/components/SQLReview/components/SQLReviewAttachedResource.vue
frontend/src/components/SQLReview/components/useReviewConfigAttachedResource.ts

chore: skip fetch resource if no permission

---

backend/plugin/db/snowflake/snowflake.go

https://docs.snowflake.com/en/developer-guide/sql-api/submitting-multiple-statements

chore: snowflake MULTI_STATEMENT_COUNT 0

---

backend/api/v1/sql_service.go
backend/plugin/parser/base/interface.go
backend/plugin/parser/mysql/query.go
backend/plugin/parser/mysql/query_test.go
backend/plugin/parser/partiql/query.go
backend/plugin/parser/pg/query.go
backend/plugin/parser/pg/query_test.go
backend/plugin/parser/plsql/query.go
backend/plugin/parser/redis/query.go
backend/plugin/parser/redis/query_test.go
backend/plugin/parser/standard/query.go
backend/plugin/parser/standard/query_test.go
backend/plugin/parser/tidb/query.go
backend/plugin/parser/tsql/query.go

Used to determine whether Query() or Execute() should be used.

chore: introduce all query

---

backend/plugin/db/mssql/mssql.go

chore: one mssql query

---

frontend/src/components/Project/useProjectSidebar.ts
frontend/src/components/ProjectSettingPanel.vue

chore: hide branch related views

---

frontend/src/components/WorkspaceInstanceLicenseStats.vue
frontend/src/views/SettingWorkspaceSubscription.vue

**Workspace member without `bb.instances.list` permission**
**Workspace member with `bb.instances.list` permission**

fix: check permissions for instance license stats

---

frontend/src/App.vue
frontend/src/store/modules/auth.ts
frontend/src/views/OAuthCallback.vue

chore(frontend): request workspaceService.fetchIamPolicy after login

---

backend/demo/data/default/README.md
backend/resources/postgres/sample/0001##schema.sql

* Add index, trigger, functions
* Update demo data to include the latest sample schema. Otherwise, Schema Synchronization will include incorrect diff (e.g. `bbdataarchive` schema)

chore: update sample schema and demo data

---

frontend/src/components/Icon/SchemaIcon.vue
frontend/src/components/Icon/TableIcon.vue
frontend/src/components/Icon/ViewIcon.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/SchemaNode.vue

chore: improve table, schema, view icon

---

frontend/src/components/ExprEditor/ConditionGroup.vue

Part of BYT-6018
* Only enable raw expression button for db group;

chore: fix raw expression button checks

---

backend/plugin/parser/plsql/query_span_extractor.go
backend/plugin/parser/plsql/test-data/query_span.yaml

fix(query-span): fix alias.* with join for plsql

---

backend/plugin/db/dynamodb/dynamodb.go
backend/plugin/db/hive/hive.go
backend/plugin/db/mssql/mssql.go

Part of BYT-5956
The error message will be saved into task run result. 
https://github.com/bytebase/bytebase/blob/main/backend/runner/taskrun/schedulerv2.go#L481

chore: remove statement in error message

---

frontend/src/components/ColumnDataTable/SemanticTypeCell.vue
frontend/src/components/ColumnDataTable/index.vue
frontend/src/components/EnvironmentForm/AccessControlConfigure.vue
frontend/src/components/EnvironmentForm/Form.vue
frontend/src/components/SensitiveData/SensitiveColumnDrawer.vue
frontend/src/components/SensitiveData/useSemanticType.ts
frontend/src/components/v2/TabFilter/EnvironmentTabFilter.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/v1/dbSchema.ts

chore: update masking algorithm

---

frontend/src/components/IssueV1/components/TaskRunSection/TaskRunComment.vue
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunTable.vue

Close BYT-5956. Follow https://github.com/bytebase/bytebase/pull/13170
* Only show max of 3 rows and can be expanded with a single click.

chore: update task run comment view

---

frontend/src/customAppProfile.ts

chore(sql-editor): hide export data button in iframe

---

frontend/src/store/modules/user.ts

chore(frontend): invalid cache eagerly

---

frontend/src/App.vue
frontend/src/AuthContext.vue
frontend/src/components/Project/useRecentProjects.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/router/useRecentVisit.ts
frontend/src/store/modules/auth.ts
frontend/src/store/modules/v1/actuator.ts

show the model if the user changed
TODO:
Some local storage needs to bind with the current user. For example, https://github.com/bytebase/bytebase/blob/2b50f7e04443abf219de59356efed1ed4d085337/frontend/src/store/modules/uistate.ts#L10

chore: refresh pages if login as another user

---

frontend/src/components/Branch/BranchMergeView/BranchMergeView.vue
frontend/src/components/Branch/BranchMergeView/MergeBranchSelect.vue

chore(branching): restrict to merge to parent

---

frontend/src/views/SettingWorkspaceMember.vue

Seems this can fix it, but I don't know why!
https://github.com/user-attachments/assets/4151114e-aace-4335-8597-6de2a978de4f

fix: tab is crash

---

backend/plugin/parser/mysql/query_span_extractor.go
backend/plugin/parser/mysql/test-data/query-span/standard.yaml

chore(query-span): support JSON_TABLE for MySQL

---

frontend/src/components/DataExportButton.vue
frontend/src/components/Issue/panel/RequestExportPanel/MaxRowCountSelect.vue
frontend/src/components/Issue/panel/RequestExportPanel/index.vue
frontend/src/components/ProjectMember/AddProjectMember/AddProjectMemberForm.vue
frontend/src/components/ProjectMember/ProjectMemberRolePanel/EditProjectRolePanel.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

chore(frontend): better row limit experience

---

frontend/src/components/CustomApproval/Settings/components/RiskCenter/RiskDialog/RiskForm.vue
frontend/src/components/ExprEditor/ConditionGroup.vue
frontend/src/components/SensitiveData/components/MaskingRuleConfig.vue

fix: expr editor intial value

---

frontend/src/views/sql-editor/EditorPanel/Panels/Panels.vue

fix something left behind #13184

chore(sql-editor): fetch database metadata when needed

---

frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/DatabaseNode.vue

hide environment tags when `"bb.feature.sql-editor.hide-environments"` is `true`

chore(sql-editor): hide environment tag when not needed

---

frontend/src/components/SSO/IdentityProviderCreateForm.vue
frontend/src/utils/idp.ts

chore: add oauth2 template for microsoft entra

---

backend/legacyapi/plan.go

chore(sql-editor): make AI-augmentation feature free

---

backend/plugin/db/oracle/oracle.go

For Oracle, we think a statement like "SELECT xxx FROM DUAL" does not need a limit clause.
More details, xxx can not be a subquery.
close BYT-6045

chore: support Oracle sequence

---

frontend/src/components/DatabaseGroup/DatabaseGroupForm.vue
frontend/src/components/DatabaseGroup/DatabaseGroupPanel.vue
frontend/src/components/DatabaseGroup/ProjectDatabaseGroupPanel.vue
frontend/src/store/modules/dbGroup.ts
frontend/src/views/DatabaseGroupDetail.vue

chore: fix list database group requests

---

backend/plugin/db/mysql/mysql.go
backend/plugin/parser/mysql/mysql_test.go
backend/tests/sql_export_test.go
go.mod
go.sum

chore: upgrade mysql parser for more bin and hex

---

frontend/src/locales/ja-JP.json

Hi, I'm a Bytebase fan in Japan. 
In this PR, I have improved some Japanese to make it more natural to understand.
Many Japanese developers are comfortable with English, but Bytebase can attract many more users by providing high-quality Japanese.

fix(frontend): improve some japanese

---

frontend/src/utils/sqlEditor.ts
frontend/src/views/sql-editor/AsidePanel/SchemaPane/actions.tsx
frontend/src/views/sql-editor/EditorCommon/QueryContextSettingPopover.vue

fix(sql-editor): default data source

---

frontend/src/utils/workspaceApprovalSetting.ts

fix: custom approval setting

---

backend/api/v1/sql_service.go
backend/store/data_source.go
backend/store/instance.go

chore: set default data source

---

backend/api/lsp/completion.go
frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/components/MonacoEditor/MonacoTextModelEditor.vue
frontend/src/components/MonacoEditor/composables/index.ts
frontend/src/components/MonacoEditor/composables/useOverrideSuggestIcons.ts

chore(sql-editor): override some auto-complete popup icons

---

frontend/src/views/sql-editor/EditorPanel/Panels/ViewsPanel/ViewsTable.vue
frontend/src/views/sql-editor/EditorPanel/StandardPanel/StandardPanel.vue

- AI chatbox is invisible sometimes
- "Comment" should refer to "注释" other than "评论" in metadata scenes

chore(sql-editor): minor fixes

---

frontend/src/components/Role/Setting/RoleSetting.vue
frontend/src/components/Role/Setting/components/RoleDataTable/index.vue
frontend/src/components/Role/Setting/components/RolePanel.vue

chore: hide branch related permissions in frontend

---

backend/api/v1/role_service.go
backend/store/role.go
frontend/src/components/DatabaseDetail/Settings/components/Secrets.vue
frontend/src/components/Role/Setting/components/RoleDataTable/cells/RoleOperationsCell.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/utils.ts

chore: custom roles can be deleted only when no policy references them

---

frontend/src/components/SchemaEditorLite/Aside/LastUpdate.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

chore(frontend): display last update branch

---

frontend/src/components/GeneralSetting/MaximumSQLResultSizeSetting.vue
frontend/src/components/GeneralSetting/index.ts
frontend/src/views/sql-editor/Setting/General/General.vue

chore(sql-editor): also add max sql result size setting to SQLEditorSettingPage

---

backend/server/grpc_routes.go

fix: register all grpc to restful forwarder

---

backend/api/v1/schema_design_merge.go
backend/api/v1/testdata/schema_design_merge/try_merge.yaml
backend/plugin/db/mysql/sync.go
backend/plugin/parser/mysql/differ.go
backend/plugin/schema/mysql/state.go
backend/store/model/database.go
backend/utils/database_config_merge.go
frontend/src/components/SchemaEditorLite/Modals/FunctionNameModal.vue
frontend/src/components/SchemaEditorLite/Modals/ProcedureNameModal.vue

fix: merge partition

---

frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
frontend/src/components/SchemaEditorLite/Aside/NodeCheckbox/NodeCheckbox.vue
frontend/src/components/SchemaEditorLite/Aside/NodeCheckbox/ViewGroupNodeCheckbox.vue
frontend/src/components/SchemaEditorLite/Aside/NodeCheckbox/ViewNodeCheckbox.vue
frontend/src/components/SchemaEditorLite/Aside/NodePrefix.vue
frontend/src/components/SchemaEditorLite/Aside/Tree.vue
frontend/src/components/SchemaEditorLite/Aside/common.ts
frontend/src/components/SchemaEditorLite/Aside/context-menu.ts
frontend/src/components/SchemaEditorLite/Editor.vue
frontend/src/components/SchemaEditorLite/Modals/ViewNameModal.vue
frontend/src/components/SchemaEditorLite/Panels/ViewEditor.vue
frontend/src/components/SchemaEditorLite/TabsContainer.vue
frontend/src/components/SchemaEditorLite/algorithm/apply-selected.ts
frontend/src/components/SchemaEditorLite/algorithm/apply.ts
frontend/src/components/SchemaEditorLite/algorithm/diff-merge.ts
frontend/src/components/SchemaEditorLite/context/edit.ts
frontend/src/components/SchemaEditorLite/context/selection.ts
frontend/src/components/SchemaEditorLite/spec.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/utils/schemaEditor/filter.ts

chore(schema-editor): support editing views

---

backend/api/v1/branch_service.go
backend/api/v1/schema_design_merge.go
backend/plugin/parser/mysql/differ.go
backend/plugin/parser/mysql/test-data/differ/test_differ_view.yaml

chore: fail open for dendency columns not found in differ

---

backend/plugin/db/oracle/sync.go

fix(sync): fix sync db link for Oracle

---

frontend/src/components/Branch/BranchRebaseView/BranchRebaseView.vue

chore: rebase hide comparison if no conflict

---

backend/plugin/db/mssql/mssql.go

fix: mssql explain

---

frontend/src/components/SensitiveData/SensitiveColumnView.vue
frontend/src/store/modules/v1/common.ts
frontend/src/store/modules/v1/database.ts

chore(frontend): retire get database by uid

---

backend/plugin/db/hive/sync.go

fix(hive): fix table metadata and ignore partition errs

---

backend/plugin/parser/base/interface.go
backend/plugin/parser/base/transform.go
backend/plugin/parser/mysql/backup.go
backend/plugin/parser/mysql/backup_test.go
backend/plugin/parser/mysql/test-data/test_backup.yaml
backend/plugin/parser/pg/backup.go
backend/plugin/parser/pg/backup_test.go
backend/plugin/parser/plsql/backup.go
backend/plugin/parser/plsql/backup_test.go
backend/plugin/parser/tidb/backup.go
backend/plugin/parser/tsql/backup.go
backend/plugin/parser/tsql/backup_test.go
backend/runner/taskrun/data_update_executor.go

chore(backup): support MySQL generated column

---

backend/api/v1/sql_service.go
backend/plugin/parser/base/interface.go
backend/plugin/parser/base/restore.go
backend/plugin/parser/mysql/backup.go
backend/plugin/parser/mysql/restore.go
backend/plugin/parser/mysql/restore_test.go
backend/plugin/parser/mysql/test-data/test_restore.yaml

chore(restore): support MySQL generated column

---

frontend/src/components/User/Settings/CreateUserDrawer.vue
frontend/src/components/User/Settings/UserDataTable/index.vue
frontend/src/customAppProfile.ts
frontend/src/router/sqlEditor.ts
frontend/src/types/appProfile.ts
frontend/src/views/sql-editor/EditorPanel/Welcome/Welcome.vue
frontend/src/views/sql-editor/Setting/Members/Members.vue
frontend/src/views/sql-editor/Setting/Members/index.ts
frontend/src/views/sql-editor/Setting/Sidebar/common.ts

Simplified version
- No groups
- No custom roles and project roles
- No service accounts

chore(sql-editor): member management in SQL Editor setting

---

backend/plugin/db/mssql/mssql.go

chore: mssql sticky explain

---

backend/api/v1/database_service.go

chore: implement backup available

---

frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/TaskRunLogTable.vue

chore: use last instead of head for deploy id

---

frontend/src/components/Branch/common/BranchComparison.vue

We call this "Defensive debugging" T_T

chore(frontend): delay 1 frame to set value to branch comparison code editor

---

backend/api/v1/sql_service.go
backend/plugin/advisor/builtin_rules.go
backend/plugin/advisor/code.go
backend/plugin/advisor/mysql/advisor_builtin_prior_backup_check.go
backend/plugin/advisor/pg/advisor_builtin_prior_backup_check.go
backend/plugin/advisor/sql_review.go
backend/plugin/advisor/tidb/advisor_builtin_prior_backup_check.go
backend/runner/plancheck/statement_advise_executor.go
frontend/src/types/sql-review-schema.yaml
frontend/src/types/sql-review.dev.yaml
frontend/src/types/sql-review.prod.yaml

chore: introduce builtin sql review rules

---

backend/plugin/db/dm/dm.go
backend/plugin/db/dynamodb/dynamodb.go
backend/plugin/db/mssql/mssql.go
backend/plugin/db/mysql/mysql.go
backend/plugin/db/mysql/sync.go
backend/plugin/db/obo/obo.go
backend/plugin/db/oracle/oracle.go
backend/plugin/db/pg/pg.go
backend/plugin/db/redshift/redshift.go
backend/plugin/db/risingwave/risingwave.go
backend/plugin/db/snowflake/snowflake.go
backend/plugin/db/sqlite/sqlite.go
backend/plugin/db/starrocks/starrocks.go
backend/plugin/db/tidb/sync.go
backend/plugin/db/tidb/tidb.go

chore: keep original error

---

frontend/src/components/IssueV1/components/TaskRunSection/TaskRunDetail.vue
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunSection.vue
frontend/src/store/modules/v1/experimental-issue.ts

chore: only fetch task run log for selected task

---

frontend/src/components/InstanceForm/DataSourceSection/DataSourceForm.vue

chore(databricks): remove password authentication from frontend

---

frontend/src/components/IssueV1/logic/initialize/create.ts
frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue

chore: save statement into local storage

---

frontend/src/components/IssueV1/components/Panel/TaskRolloutActionPanel.vue
frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckSection.vue
frontend/src/components/IssueV1/components/Sidebar/EarliestAllowedTime.vue
frontend/src/components/IssueV1/components/StageSection/StageCard.vue
frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
frontend/src/components/IssueV1/components/StatementSection/useSQLAdviceMarkers.ts
frontend/src/components/IssueV1/components/TaskStatusIcon.vue
frontend/src/components/IssueV1/logic/base.ts
frontend/src/components/IssueV1/logic/context.ts
frontend/src/components/IssueV1/logic/plan-check.ts
frontend/src/components/IssueV1/logic/rollout.ts

chore: add cache map for `planCheckRunsForTask`

---

frontend/src/views/SettingWorkspaceVCS.vue

chore: add gitops doc learn more link

---

frontend/src/components/Project/ProjectSwitchModal.vue
frontend/src/components/v2/Model/ProjectV1Table.vue

chore: add virtual scroll to project switch modal

---

backend/api/v1/auth_service.go
backend/api/v1/setting_service.go

chore: check disallow password signin

---

backend/plugin/advisor/pg/advisor_builtin_prior_backup_check.go
backend/plugin/advisor/pg/test/builtin_prior_backup_check.yaml
backend/plugin/parser/sql/ast/update_stmt.go
backend/plugin/parser/sql/engine/pg/convert.go

chore: implement backup check

---

frontend/src/components/IssueV1/components/Sidebar/EarliestAllowedTime.vue
frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
frontend/src/components/IssueV1/logic/rollout.ts

fix: plan check runs for task

---

frontend/src/components/Member/utils.ts
frontend/src/components/v2/Select/UserSelect.vue
frontend/src/layouts/ProjectV1Layout.vue

- Optimize users/member filter
- Do not close the user selector if it is the multiply select mode
- Redirect users to the home page if an error occurs during the project fetch.

chore: optimize

---

frontend/src/views/DashboardHeader.vue

chore: add my issues button in header

---

frontend/src/store/modules/sqlEditor/webTerminal.ts
frontend/src/views/sql-editor/EditorCommon/AdminModeButton.vue
frontend/src/views/sql-editor/EditorCommon/EditorAction.vue
frontend/src/views/sql-editor/EditorPanel/TerminalPanel/CompactSQLEditor.vue

chore(sql-editor): split standard and admin mode's statements

---

frontend/src/bbkit/BBModal.vue

chore(frontend): fix kbar not working

---

frontend/src/components/KBar/KBarWrapper.vue

chore: update z-index for kbar positioner

---

backend/plugin/parser/plsql/query_span_extractor.go
backend/plugin/parser/plsql/query_span_test.go
backend/plugin/parser/plsql/test-data/query_span.yaml

fix(query-span): fix plsql view for query span

---

frontend/src/components/ProjectMember/AddProjectMember/AddProjectMemberForm.vue
frontend/src/components/ProjectMember/AddProjectMember/AddProjectMembersPanel.vue
frontend/src/components/v2/Model/DatabaseV1Table/DatabaseV1Table.vue

- Merge binding to avoid duplication. Close BYT-5954
- Add the address column in the database table. Close BYT-4526

chore: merge project bindings

---

frontend/src/components/IssueV1/components/IssueTableV1.vue
frontend/src/components/IssueV1/components/PagedIssueTableV1.vue
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunComment.vue
frontend/src/components/Project/ProjectIssuesPanel.vue
frontend/src/utils/localStorage.ts
frontend/src/views/DashboardHeader.vue
frontend/src/views/ExportCenter/index.vue
frontend/src/views/MyIssues.vue
frontend/src/views/ReviewCenter/index.vue

* trigger page reload after clicking `my issues`;
* remove unused props: loading, loadingMore

chore: update my issues action

---

backend/api/v1/instance_service.go
frontend/src/components/CreateDatabasePrepForm/CreateDatabasePrepForm.vue

fix: instance role name

---

frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
frontend/src/components/Branch/BranchCreateView.vue
frontend/src/components/Branch/BranchDetailView.vue
frontend/src/components/Branch/BranchRebaseView/RebaseBranchStep.vue
frontend/src/components/Branch/BranchRebaseView/SelectBranchStep.vue
frontend/src/components/Branch/BranchRolloutView/BranchRolloutView.vue
frontend/src/components/Branch/SchemaDesignEditorLite.vue
frontend/src/components/Branch/common/BranchComparison.vue
frontend/src/components/Branch/common/BranchDetailViewer.vue
frontend/src/components/SchemaEditorLite/Editor.vue
frontend/src/components/SchemaEditorLite/Panels/DatabaseEditor.vue
frontend/src/components/SchemaEditorLite/Panels/TableEditor.vue
frontend/src/components/SchemaEditorLite/Panels/TableSchemaPreview.vue
frontend/src/components/SchemaEditorLite/SchemaEditorLite.vue
frontend/src/components/SchemaEditorLite/context/index.ts
frontend/src/components/SchemaTemplate/TableTemplateForm.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/main.ts

feat(frontend): preview table schema text in schema editor

---

backend/plugin/advisor/mysql/advisor_builtin_prior_backup_check.go
backend/plugin/advisor/tidb/advisor_builtin_prior_backup_check.go

chore: implement tidb prior backup check

---

backend/plugin/parser/pg/backup.go
backend/plugin/parser/pg/test-data/test_backup.yaml

chore: backup in one table for large scale update statements

---

backend/plugin/schema/tidb/get_design_schema.go
backend/plugin/schema/tidb/state.go
backend/plugin/schema/tidb/testdata/get_design_schema.yaml

feat: tidb get design schema support view

---

frontend/src/views/DashboardHeader.vue

fix: link element in header

---

backend/plugin/parser/tidb/backup.go
backend/plugin/parser/tidb/backup_test.go
backend/plugin/parser/tidb/test-data/test_backup.yaml

close BYT-6116
close BYT-5543
I'll fix the line number in the next PR

chore: implement tidb backup for new design

---

backend/api/v1/audit_log_service.go

fix: user filter in audit log service

---

go.mod
go.sum

chore: upgrade antlr based tidb parser

---

frontend/src/components/Member/EditMemberRoleDrawer.vue

fix: member role update

---

backend/plugin/parser/tidb/backup.go
backend/plugin/parser/tidb/test-data/test_backup.yaml

fix(backup): fix position for tidb

---

backend/plugin/parser/mysql/backup.go
backend/plugin/parser/mysql/test-data/test_backup.yaml

chore: backup in one table for large scale update statements for mysql

---

backend/plugin/parser/pg/query_span_extractor.go

The code is never reached and should be handled by line 108 (	if allSystems ...).

refactor: pg span

---

backend/plugin/parser/tidb/split.go
backend/plugin/parser/tidb/tidb.go
backend/plugin/parser/tidb/util.go
backend/plugin/schema/tidb/parse_to_metadata.go
backend/plugin/schema/tidb/parse_to_metadata_test.go
backend/plugin/schema/tidb/state.go
backend/plugin/schema/tidb/testdata/parse_to_metadata.yaml
backend/plugin/schema/tidb/utils.go

feat: copy mysql parse to metadata to tidb

---

frontend/src/components/IssueV1/components/IssueTableV1.vue

fix: use name instead uid in issue table

---

frontend/src/views/sql-editor/EditorCommon/AdminModeButton.vue

chore: use solid line instead of dashed for admin button

---

frontend/src/components/IssueV1/components/TaskRunSection/TaskRunComment.vue
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunTable.vue

Close BYT-6172
https://github.com/user-attachments/assets/44d7d5f6-8d64-4cc5-a1af-4807f4197ba8

chore: tweak task run table style

---

frontend/src/views/sql-editor/EditorPanel/Panels/ExternalTablesPanel/ExternalTablesTable.vue
frontend/src/views/sql-editor/EditorPanel/Panels/FunctionsPanel/FunctionsTable.vue
frontend/src/views/sql-editor/EditorPanel/Panels/InfoPanel/InfoPanel.vue
frontend/src/views/sql-editor/EditorPanel/Panels/ProceduresPanel/ProceduresTable.vue
frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/TablesTable.vue
frontend/src/views/sql-editor/EditorPanel/Panels/ViewsPanel/ViewsTable.vue
frontend/src/views/sql-editor/EditorPanel/common.ts

chore(sql-editor): calc table height dynamically

---

frontend/src/components/GeneralSetting/SecuritySetting.vue
frontend/src/locales/en-US.json

* Co-locate signup/signin setting
* Use "Disallow" consistently.

chore: minor setting adjustment

---

frontend/src/components/SchemaEditorLite/Panels/TableEditor.vue
frontend/src/components/SchemaEditorLite/Panels/TableSchemaPreview.vue
frontend/src/components/SchemaEditorLite/spec.ts

- Hide procedures and functions for TIDB
- Adding new table partitions now have default type to HASH
- Preview table schema will not push error notifications

chore(frontend): branch editor minor tweaks

---

frontend/src/views/sql-editor/AsidePanel/SchemaPane/SchemaPane.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/actions.tsx
frontend/src/views/sql-editor/AsidePanel/SchemaPane/common.ts

- Single click events will be omitted if a double click comes in following 250ms
- Generated `SELECT * FROM ...` SQL will be executed without modifying the current sheet.

chore(sql-editor): improve double clicking preview table data experience

---

frontend/src/components/IssueV1/components/IssueSearch/Status.vue

chore: add `all` tab to issue status

---

frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
frontend/src/components/Branch/BranchCreateView.vue
frontend/src/components/Branch/BranchDetailView.vue
frontend/src/components/Branch/BranchRebaseView/RebaseBranchStep.vue
frontend/src/components/Branch/BranchRebaseView/SelectBranchStep.vue
frontend/src/components/Branch/BranchRolloutView/BranchRolloutView.vue
frontend/src/components/Branch/SchemaDesignEditorLite.vue
frontend/src/components/Branch/common/BranchComparison.vue
frontend/src/components/Branch/common/BranchDetailViewer.vue
frontend/src/components/SchemaEditorLite/Editor.vue
frontend/src/components/SchemaEditorLite/Panels/CommonCodeEditor.vue
frontend/src/components/SchemaEditorLite/Panels/PreviewPane.vue
frontend/src/components/SchemaEditorLite/Panels/TableEditor.vue
frontend/src/components/SchemaEditorLite/Panels/ViewEditor.vue
frontend/src/components/SchemaEditorLite/SchemaEditorLite.vue
frontend/src/components/SchemaEditorLite/context/index.ts
frontend/src/components/SchemaTemplate/TableTemplateForm.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

chore: view preview

---

backend/plugin/parser/pg/query_span_extractor.go
backend/plugin/parser/pg/test-data/query_span.yaml

chore(query-span): support UDF in expression for PG

---

frontend/src/assets/css/tailwind.css
frontend/src/views/sql-editor/AsidePanel/SchemaPane/SchemaPane.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/ColumnNode.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/CommonNode.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/common.ts

- Highlight selected items when selected in the right panel
- Show columns' nullable and type properties

chore(sql-editor): schema tree improvements

---

backend/runner/taskrun/data_export_executor.go

chore: remove duration in task run result for data export

---

backend/api/v1/sql_service.go
backend/component/iam/manager.go
backend/utils/member.go

chore: respect workspace iam policy

---

frontend/src/components/Member/MemberDataTable/cells/UserNameCell.vue
frontend/src/components/User/Settings/UserDataTable/cells/UserNameCell.vue
frontend/src/components/User/Settings/UserDataTableByGroup/cells/GroupMemberNameCell.vue
frontend/src/views/ProfileDashboard.vue

chore: fix linter warning

---

frontend/src/components/TenantDatabaseTable/DatabaseMatrixItem.vue
frontend/src/components/TenantDatabaseTable/DeployDatabaseTable.vue

chore: use virtual list for databases in deployment config

---

backend/plugin/parser/mysql/restore.go

chore: truncate sql for comments

---

frontend/src/components/TenantDatabaseTable/DatabaseMatrixGroup.vue
frontend/src/components/TenantDatabaseTable/DatabaseMatrixItem.vue
frontend/src/components/TenantDatabaseTable/DeploymentMatrixDataTable.vue

chore: update styles of deployment config data table

---

frontend/src/components/IssueV1/components/IssueStatusIcon.vue
frontend/src/components/IssueV1/components/IssueStatusIconWithTaskSummary.vue
frontend/src/components/IssueV1/components/IssueTableV1.vue

chore: update issue data table

---

frontend/src/components/DatabaseGroup/DatabaseGroupDataTable.vue
frontend/src/components/DatabaseGroup/ProjectDatabaseGroupPanel.vue
frontend/src/views/project/ProjectDatabaseGroupDashboard.vue

chore: add change menu to db group table

---

frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/utils/v1/issue/issue.ts

chore: update i18n of issue title

---

frontend/src/components/MonacoEditor/MonacoTextModelEditor.vue
frontend/src/components/MonacoEditor/composables/index.ts
frontend/src/components/MonacoEditor/composables/useSelection.ts
frontend/src/components/MonacoEditor/types.ts
frontend/src/composables/useExecuteSQL.ts
frontend/src/customAppProfile.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/types/appProfile.ts
frontend/src/types/sqlEditor/editor.ts
frontend/src/types/sqlEditor/tab.ts
frontend/src/utils/sqlEditor.ts
frontend/src/views/sql-editor/AsidePanel/SchemaPane/actions.tsx
frontend/src/views/sql-editor/EditorCommon/EditorAction.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/ErrorView.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue
frontend/src/views/sql-editor/EditorPanel/StandardPanel/SQLEditor.vue
frontend/src/views/sql-editor/EditorPanel/StandardPanel/StandardPanel.vue
frontend/src/views/sql-editor/EditorPanel/TerminalPanel/CompactSQLEditor.vue

- Issue mode. Keep as is. Just show a warning popup on the bottom right.
- SQL Editor Mode. Popup the warning dialog and ask whether user wants to continue (Similar to the SQL Review flow when we create an issue).
The looking might be improved shortly.
Close BYT-5898

chore(sql-editor): different check behavior for issue and editor mode

---

frontend/src/views/sql-editor/TabList/TabList.vue

chore(sql-editor): Make + sheet icon more obvious

---

backend/api/v1/auth_service.go

chore: auto active user via SSO

---

backend/api/v1/database_service.go
backend/api/v1/plan_service.go

chore: check backup available for database when updating plan

---

backend/api/v1/plan_service.go

fix: backup database name

---

frontend/src/components/Member/MembersBindingSelect.vue
frontend/src/components/ProjectMember/AddProjectMember/AddProjectMembersPanel.vue
frontend/src/components/ProjectMember/ProjectMemberRolePanel/EditProjectRolePanel.vue
frontend/src/components/ProjectMember/ProjectMemberRolePanel/index.vue
frontend/src/components/ProjectMember/utils.ts

fix: only allow update single user

---

frontend/src/components/IssueV1/components/Sidebar/PreBackupSection/PreBackupSwitch.vue
frontend/src/components/IssueV1/components/Sidebar/PreBackupSection/common.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

chore: add tooltip for backup switch

---

frontend/src/components/MonacoEditor/utils.ts
frontend/src/composables/useExecuteSQL.ts
frontend/src/views/sql-editor/EditorCommon/ResultView/ErrorView/AdviceItem.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/ErrorView/ErrorView.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/ErrorView/index.ts
frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
frontend/src/views/sql-editor/EditorPanel/StandardPanel/SQLEditor.vue
frontend/src/views/sql-editor/context.ts

Clicking "L2:C10" will focus the editor and locate the cursor. Useful when we have more than one warnings in editor mode.

chore(sql-editor): improve error style

---

frontend/src/bbkit/BBButtonConfirm.vue
frontend/src/components/Member/EditMemberRoleDrawer.vue
frontend/src/components/ProjectMember/ProjectMemberRolePanel/index.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

chore: update member revoke

---

frontend/src/components/Database/DatabaseChangeHistoryPanel.vue
frontend/src/store/modules/v1/changeHistory.ts

chore: tweak default page size of change history

---

backend/plugin/advisor/code.go
backend/plugin/advisor/mssql/advisor_builtin_prior_backup_check.go
backend/plugin/advisor/sql_review.go

feat(sql-review): implement MSSQL prior backup check

---

frontend/src/components/TransferDatabaseForm/TransferDatabaseForm.vue
frontend/src/components/TransferDatabaseForm/TransferSourceSelector.vue

chore: add env selector to database transfer drawer

---

backend/plugin/parser/pg/query_span_extractor.go
backend/plugin/parser/pg/test-data/query_span.yaml

Also add us query in regression test

fix: allow json and jsonb to recordset

---

frontend/src/views/sql-editor/AsidePanel/GutterBar/GutterBar.vue
frontend/src/views/sql-editor/EditorCommon/EditorAction.vue
frontend/src/views/sql-editor/EditorCommon/OpenAIButton.vue

It's a little bit weird to turn on/off the AI chatbox here. We may refine the click behavior of the button later.
Close BYT-6120

chore(sql-editor): move the Text2SQL button

---

backend/plugin/parser/tsql/backup.go
backend/plugin/parser/tsql/test-data/test_backup.yaml

feat(backup): backup in one table for large scale update statements for mssql

---

backend/plugin/webhook/wecom/app.go

chore: extend expiration time

---

frontend/src/utils/dom.ts
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue

only available in the result data table area
@RainbowDashy plz test

chore(sql-editor): prevent accidentally triggering the browsers go back gesture in SQL editor's result data table

---

backend/api/v1/branch_service.go

fix: correct proto cmp

---

frontend/src/components/SchemaEditorLite/Aside/Tree.vue
frontend/src/components/SchemaEditorLite/Modals/TableNameModal.vue
frontend/src/components/SchemaEditorLite/Panels/TableEditor.vue
frontend/src/components/SchemaEditorLite/edit.ts
frontend/src/components/SchemaTemplate/TableTemplateForm.vue
frontend/src/utils/v1/instance.ts

chore: tweak index name for mysql&tidb

---

backend/api/v1/auth_service.go

chore: skip domain checks for workspace admin

---

backend/component/webhook/manager.go

fix: webhook notifs should skip deleted users

---

frontend/src/components/SchemaEditorLite/Panels/PartitionsEditor/PartitionsEditor.vue
frontend/src/components/SchemaEditorLite/Panels/PreviewPane.vue

chore(schema-editor): fix partition edit status pollution by name

---

frontend/src/components/User/Settings/AADSyncDrawer.vue

chore: tweak linter warning

---

frontend/src/components/SchemaEditorLite/Aside/Tree.vue
frontend/src/components/SchemaEditorLite/algorithm/rebuild.ts

chore(schema-editor): keep tab status when toggling edit mode

---

backend/plugin/advisor/mssql/advisor_builtin_prior_backup_check.go
backend/plugin/advisor/mysql/advisor_builtin_prior_backup_check.go
backend/plugin/advisor/pg/advisor_builtin_prior_backup_check.go
backend/plugin/advisor/pg/test/builtin_prior_backup_check.yaml
backend/plugin/advisor/tidb/advisor_builtin_prior_backup_check.go

chore: tweak prior backup check wording

---

frontend/src/components/SchemaEditorLite/Panels/PartitionsEditor/PartitionsEditor.vue

default to HASH
part of BYT-6241

chore(schema-editor): default sub partition type

---

frontend/src/components/IssueV1/components/Sidebar/PreBackupSection/TaskRollbackButton.vue

chore: tweak rollback issue description to add spacing

---

frontend/src/components/SchemaEditorLite/Panels/PartitionsEditor/PartitionsEditor.vue
frontend/src/components/SchemaEditorLite/Panels/TableEditor.vue

others will follow the first one
Close BYT-6241

chore(schema-editor): only allow to editor the first partition/sub-partition

---

frontend/src/store/modules/sqlEditor/tab.ts

chore(sql-editor): one-way sync for currentTabId

---

frontend/src/components/IssueV1/logic/poll.ts
frontend/src/store/modules/v1/changeHistory.ts

chore: clear database change history cache

---

backend/api/v1/database_service.go
backend/plugin/advisor/builtin_rules.go
backend/plugin/advisor/code.go
backend/plugin/advisor/oracle/advisor_builtin_prior_backup_check.go
backend/plugin/advisor/sql_review.go
backend/plugin/parser/plsql/backup.go
backend/plugin/parser/plsql/completion.go
backend/plugin/parser/plsql/plsql.go
backend/plugin/parser/plsql/query_span_extractor.go
backend/plugin/parser/plsql/util.go

feat: prior backup check for Oracle

---

frontend/src/views/sql-editor/EditorCommon/ExecuteHint.vue

chore(sql-editor): open new browser tab when creating issue

---

frontend/src/views/sql-editor/AsidePanel/SchemaPane/common.ts

fix(sql-editor): parent key of column nodes

---

frontend/src/views/sql-editor/AsidePanel/SchemaPane/SchemaPane.vue

chore(sql-editor): split keyword for each tab

---

frontend/src/composables/useExecuteSQL.ts

chore(sql-editor): set minimal query interval to 1 second

---

backend/plugin/parser/plsql/backup.go
backend/plugin/parser/plsql/test-data/test_backup.yaml

feat: implement plsql backup for multi-updates

---

backend/plugin/parser/mysql/query.go
backend/plugin/parser/mysql/query_test.go
backend/plugin/parser/tidb/query.go
backend/plugin/parser/tidb/query_test.go

chore: admin executing explain analyze returns correct result

---

backend/api/lsp/commands.go
backend/api/lsp/completion.go
backend/api/lsp/handler.go
backend/plugin/parser/base/complete.go
backend/plugin/parser/pg/completion.go
backend/plugin/parser/tsql/completion.go
frontend/src/components/MonacoEditor/composables/useAutoComplete.ts

feat: add schema to lsp arguments

---

backend/runner/schemasync/syncer.go

feat: enable drift detection for oracle and mssql

---

frontend/src/components/CreateDatabasePrepForm/CreateDatabasePrepForm.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

chore: update i18n for creating database issue title

---

frontend/src/components/SensitiveData/SensitiveColumnDrawer.vue

fix: naiveui warning

---

frontend/src/views/sql-editor/EditorCommon/SchemaChooser.vue

chore: fix schema chooser overflow

---

frontend/src/components/Changelist/ChangelistDashboard/CreateChangelistPanel.vue
frontend/src/components/Changelist/ChangelistDetail/NavBar/ImportButton.vue
frontend/src/components/Changelist/import.ts
frontend/src/components/FileContentPreviewModal.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/utils/v1/common.ts

Close BYT-6274
https://github.com/user-attachments/assets/5b7b52db-7416-4eb7-8119-21da2a4f23bf

chore: allow to select encoding in changelist

---

backend/api/lsp/fs_handler.go
backend/plugin/parser/pg/diagnose.go
backend/plugin/parser/plsql/diagnose.go
backend/plugin/parser/snowflake/diagnose.go
backend/plugin/parser/tsql/diagnose.go

feat: diagnose for PostgreSQL/Oracle/Snowflake/SQL Server

---

backend/plugin/parser/redis/query.go

chore: allow redis keys command

---

backend/plugin/parser/mysql/diagnose.go
backend/plugin/parser/pg/diagnose.go
backend/plugin/parser/plsql/diagnose.go
backend/plugin/parser/snowflake/diagnose.go
backend/plugin/parser/tsql/diagnose.go

feat: allow to omit semicolon for the last statement in diagnose

---

backend/runner/taskrun/data_update_executor.go

feat: implement skip backup error

---

frontend/src/components/SchemaEditorLite/Modals/EditColumnForeignKeyModal.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

chore: allow to edit the name of foreign keys in schema editor

---

backend/api/v1/setting_service.go
frontend/src/components/SensitiveData/ClassificationView.vue
frontend/src/components/User/Settings/UserDataTable/index.vue

chore: update classification upload format

---

backend/plugin/parser/mysql/backup.go
backend/plugin/parser/mysql/test-data/test_backup.yaml

feat(backup): support CTE for MySQL

---

backend/api/v1/project_service.go

chore: add missing project setting

---

backend/plugin/advisor/catalog/test/pg_walk_through.yaml
backend/plugin/advisor/catalog/walk_through_for_pg.go

fix(walk-through): check if exists for drop index for pg

---

backend/plugin/db/oracle/sync.go

chore: sync large oracle functions

---

frontend/src/components/QuickActionPanel.vue
frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
frontend/src/store/modules/v1/projectIamPolicy.ts
frontend/src/utils/v1/database.ts
frontend/src/views/DatabaseDetail.vue
frontend/src/views/sql-editor/EditorCommon/BatchQueryDatabasesSelector.vue

chore: fix database related permission checks

---

backend/api/v1/database_service.go

chore: skip backup available check for pg

---

frontend/src/components/IssueV1/components/Sidebar/PreBackupSection/common.ts
frontend/src/components/IssueV1/logic/initialize/create.ts
frontend/src/components/Project/Settings/ProjectIssueRelatedSettingPanel.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

chore: add project default backup behavior setting

---

backend/api/v1/issue_service_convert.go
frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/ActionIcon.vue
frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/ActionSentence.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

chore: show backup error issue comment

---

backend/plugin/db/cockroachdb/dump.go

feat(cockroachdb): tiny schema dump for cockroachdb

---

frontend/src/components/TransferDatabaseForm/TransferDatabaseForm.vue

fix: prepare default databases

---

frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
frontend/src/components/Branch/BranchDetailView.vue
frontend/src/components/IssueV1/components/Sidebar/GhostSection/common.ts
frontend/src/components/IssueV1/components/Sidebar/PreBackupSection/TaskRollbackButton.vue
frontend/src/components/IssueV1/logic/initialize/create.ts
frontend/src/components/Plan/logic/initialize/create.ts
frontend/src/components/SlowQuery/Panel/IndexAdvisor.vue
frontend/src/components/SyncDatabaseSchema/index.vue
frontend/src/views/sql-editor/EditorCommon/ExecuteHint.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue

chore: move issue sql from url to local storage

---

backend/api/lsp/completion.go
backend/plugin/parser/mysql/diagnose.go
backend/plugin/parser/pg/completion.go
backend/plugin/parser/pg/diagnose.go
backend/plugin/parser/pg/differ.go
backend/plugin/parser/pg/query.go
backend/plugin/parser/pg/query_span.go
backend/plugin/parser/pg/resource_change.go
backend/plugin/parser/pg/split.go
backend/plugin/parser/plsql/diagnose.go
backend/plugin/parser/snowflake/diagnose.go
backend/plugin/parser/tsql/diagnose.go

feat: enable advanced feature for cockroachdb

---

frontend/src/components/User/Settings/AADSyncDrawer.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/views/SettingWorkspaceUsers.vue

chore: improve entra wording

---

frontend/src/views/sql-editor/EditorCommon/ResultView/ErrorView/ErrorView.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/ErrorView/PostgresError.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue

feat(sql-editor): display postgresError

---

frontend/src/components/GeneralSetting/DatabaseChangeModeSetting.vue
frontend/src/components/ProvideSQLEditorContext.vue
frontend/src/views/sql-editor/AsidePanel/AsidePanel.vue
frontend/src/views/sql-editor/SQLEditorSettingPage.vue

Some minor fixes from #13741 but picked ahead

chore(sql-editor): some minor fixes

---

frontend/src/components/ProvideSQLEditorContext.vue

chore(sql-editor): minor fix

---

frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/actions.tsx
frontend/src/views/sql-editor/EditorCommon/utils.ts
frontend/src/views/sql-editor/Sheet/context.ts

chore(sql-editor): set default data source for connection

---

frontend/src/utils/v1/sql.ts
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/TableCell.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DetailPanel.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue

chore(sql-editor): advanced sorting compare function

---

frontend/src/components/MonacoEditor/lsp-client.ts

fix: typo in websocket error

---

frontend/src/components/GeneralSetting/DatabaseChangeModeSetting.vue

chore(sql-editor): adjust gap

---

frontend/src/components/GeneralSetting/DatabaseChangeModeSetting.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

chore(sql-editor): missing i18n

---

frontend/src/components/Changelist/ChangelistDetail/ApplyToDatabasePanel/ApplyToDatabasePanel.vue
frontend/src/components/DatabaseGroup/DatabaseGroupDataTable.vue
frontend/src/components/DatabaseGroup/DatabaseGroupPanel.vue
frontend/src/components/DatabaseGroup/ProjectDatabaseGroupPanel.vue
frontend/src/components/IssueV1/logic/initialize/create.ts
frontend/src/components/v2/Model/DatabaseV1Table/DatabaseV1Table.vue
frontend/src/components/v2/Select/DatabaseGroupSelect.vue
frontend/src/store/modules/dbGroup.ts
frontend/src/utils/v1/changelist.ts

feat: apply changelist to database group

---

frontend/src/components/Plan/components/HeaderSection/Actions/create/CreateIssueButton.vue
frontend/src/components/SQLCheck/SQLCheckPanel.vue

chore(review-center): check policy when creating issue

---

frontend/src/views/auth/PasswordReset.vue

chore: tweak styles of password reset

---

frontend/src/components/Branch/BranchDetailView.vue
frontend/src/components/SyncDatabaseSchema/SelectTargetDatabasesView.vue
frontend/src/components/SyncDatabaseSchema/TargetDatabasesSelectPanel.vue
frontend/src/components/SyncDatabaseSchema/index.vue

fix: filter databases with no changes in sync schema

---

backend/api/auth/auth.go
backend/api/auth/header.go
backend/api/v1/auth_service.go
backend/server/grpc_routes.go
backend/server/init.go
backend/server/server.go
frontend/src/AuthContext.vue
frontend/src/components/ProfileDropdown.vue
frontend/src/grpcweb/middlewares/authInterceptorMiddleware.ts
frontend/src/main.ts
frontend/src/store/modules/auth.ts
frontend/src/views/Setup/ProvideSetupContext.vue
frontend/src/views/TwoFactorRequired.vue
frontend/src/views/auth/PasswordForgot.vue
frontend/src/views/auth/Signin.vue
frontend/src/views/auth/Signup.vue

- Frontend logout with redirect query
- Don't need to restart the backend server when the token duration changed

chore: optimize auth

---

frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue

chore(sql-editor): fix display for Long object

---

frontend/src/components/PasswordSigninForm.vue

chore(sql-editor): fix sign-in redirection

---

frontend/src/components/AdvancedSearch/AdvancedSearch.vue
frontend/src/components/ProjectDatabasesPanel.vue
frontend/src/views/DatabaseDashboard.vue

Close BYT-6331
https://github.com/user-attachments/assets/ceb5ef3e-97a4-4c77-821f-c146ebb10f9a

chore: set default project as filter in workspace databases page

---

frontend/src/components/EnvironmentForm/EnvironmentForm.vue
frontend/src/components/EnvironmentForm/context.ts
frontend/src/views/EnvironmentDashboard.vue
frontend/src/views/EnvironmentDetail.vue
frontend/src/views/sql-editor/Setting/Environment/Environment.vue

fix: feature guard for environment form

---

backend/demo/data/default/README.md

chore: update demo data from 2.22.0 to 2.23.0

---

frontend/src/components/Project/ProjectSwitchModal.vue
frontend/src/main.ts

fix: modal scroll

---

frontend/src/components/DeploymentConfigTool/DeploymentMatrix.vue
frontend/src/components/ProjectDatabasesPanel.vue

chore: move the no-db banner from deployment config to database panel

---

frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue

chore: remove unnecessary `cloneDeep`

---

backend/store/plan_check_run.go

fix: list plan check runs

---

frontend/src/views/SettingSidebar.vue
frontend/src/views/sql-editor/Setting/Sidebar/common.ts

* Swap order of Workspace and Profile
* For SQL Editor mode, auto expand IAM and Data Access, also move Workspace and Profile up

chore: sidebar optimize

---

backend/api/gitops/webhook.go

chore: cut sql review output

---

frontend/src/components/Database/DatabaseChangeHistoryPanel.vue
frontend/src/grpcweb/index.ts
frontend/src/locales/zh-CN.json
frontend/src/store/modules/common.ts
frontend/src/store/modules/index.ts
frontend/src/store/modules/release.ts
frontend/src/store/modules/revision.ts
frontend/src/store/modules/v1/changeHistory.ts
frontend/src/store/modules/v1/common.ts
frontend/src/store/modules/v1/database.ts
frontend/src/store/modules/v1/databaseList.ts
frontend/src/types/common.ts
frontend/src/types/index.ts
frontend/src/types/release.ts
frontend/src/views/DatabaseDetail.vue

feat(frontend): implement release and revision store

---

frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

chore: tweak i18n for large statement

---

backend/api/v1/query_result_masker.go

feat: enable tidb masking

---

frontend/src/components/Role/Setting/components/ImportPermissionFromRoleModal.vue

chore: filter branch related permissions

---

backend/api/v1/sql_service.go
backend/plugin/db/bigquery/bigquery.go
backend/plugin/db/bigquery/bigquery_test.go
backend/plugin/db/driver.go
backend/runner/taskrun/data_export_executor.go

chore: bq label

---

frontend/src/components/EnvironmentForm/AccessControlConfigure.vue
frontend/src/components/EnvironmentForm/RolloutPolicyConfig.vue
frontend/src/components/IssueV1/logic/action/task.ts
frontend/src/components/v2/Select/RoleSelect.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/subscription/en-US.json
frontend/src/locales/subscription/es-ES.json
frontend/src/locales/zh-CN.json

* Upper/lower case consistency
* Noun / verb fix. Rollout -> Roll out
* User friendly term. Data source -> Connection

docs: i18n consistency

---

backend/api/v1/sql_service.go

fix: missing attr of request row limit

---

frontend/src/components/SQLReview/components/SQLReviewTabsByEngine.vue

chore: order sql review engine

---

backend/plugin/advisor/oracle/advisor_builtin_prior_backup_check.go
backend/plugin/parser/plsql/completion.go
backend/plugin/parser/plsql/plsql.go
backend/plugin/parser/plsql/query_span_extractor.go
go.mod
go.sum

chore: upgrade plsql parser for general element

---

frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/v1/instance.ts
frontend/src/views/InstanceDetail.vue

chore: instance sync option

---

frontend/src/components/MonacoEditor/MonacoTextModelEditor.vue
frontend/src/components/MonacoEditor/composables/useLSPConnectionState.ts
frontend/src/components/MonacoEditor/lsp-client.ts
frontend/src/components/MonacoEditor/utils.ts

Send a heartbeat every 10 seconds to keep alive

feat(sql-editor): add heartbeat to lsp websocket

---

frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/utils/v1/sql.ts

chore: handle timestamp in sql results

---

frontend/src/components/AnomalyCenter/AnomalyCenterDashboard.vue
frontend/src/components/Database/DatabaseOverviewPanel.vue
frontend/src/components/GrantRequestPanel/GrantRequestPanel.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

* Fix Request Export Role title
* Fix anomaly doc link and descripton

chore: misc fix

---

backend/plugin/db/clickhouse/query.go
backend/plugin/db/mssql/mssql.go
backend/plugin/db/mssql/query.go
backend/plugin/db/pg/pg.go
backend/plugin/db/util/driverutil.go
frontend/src/utils/v1/sql.ts

follow convention except timezone format.

chore: pg timestamp/timestamptz format

---

backend/plugin/db/mysql/mysql.go
backend/plugin/db/mysql/query.go
backend/plugin/db/starrocks/query.go
backend/plugin/db/starrocks/starrocks.go
backend/plugin/db/tidb/query.go
backend/plugin/db/tidb/tidb.go
frontend/src/utils/v1/sql.ts

This gives us control over displaying timestamp without timezone in the UI.

chore: mysql timestamp

---

frontend/src/router/useRecentVisit.ts

fix: missing record when switch the project

---

backend/plugin/parser/pg/restore.go
backend/plugin/parser/pg/test-data/test_restore.yaml

fix(restore): use original set field text

---

frontend/src/components/GrantRequestPanel/DatabaseResourceForm/index.vue

chore: add missing feature guard

---

backend/plugin/parser/pg/pg.go
backend/plugin/parser/pg/query_span_extractor.go
backend/plugin/parser/pg/test-data/query_span.yaml
go.mod
go.sum

feat(query-span): support variables in function for PG

---

backend/plugin/db/mysql/sync.go

fix: expect null in mysql show create func

---

backend/plugin/parser/mysql/completion.go
backend/plugin/parser/partiql/completion.go
backend/plugin/parser/pg/completion.go
backend/plugin/parser/plsql/completion.go
backend/plugin/parser/tsql/completion.go

fix(completion): break for the first statement

---

frontend/src/components/SSO/IdentityProviderCreateForm.vue
frontend/src/views/auth/Signin.vue

chore: show error message when failed to request openid configuration
