backend/plugin/parser/pg/pg.go
backend/plugin/parser/pg/restore.go
backend/plugin/parser/pg/test-data/test_restore.yaml

fix(restore): pg set target

---

frontend/src/views/sql-editor/EditorCommon/ResultView/DataTableLite/useTableResize.ts

- Auto resize correctly when result set it empty
- Add maximum tries to save CPU

chore(sql-editor): minor fixes for auto-table resizing

---

backend/plugin/parser/tokenizer/tokenizer.go
backend/plugin/parser/tsql/restore.go
backend/plugin/parser/tsql/restore_test.go
backend/plugin/parser/tsql/test-data/test_restore.yaml
backend/plugin/parser/tsql/tsql.go
frontend/src/components/IssueV1/components/Sidebar/PreBackupSection/common.ts

feat(restore): implement MSSQL one-click restore

---

frontend/src/components/Release/ReleaseDetail/MigrationFileTable/index.ts
frontend/src/components/Release/ReleaseDetail/ReleaseDetail.vue
frontend/src/components/Release/ReleaseDetail/ReleaseFileTable/ReleaseFileDetailPanel.vue
frontend/src/components/Release/ReleaseDetail/ReleaseFileTable/ReleaseFileTable.vue
frontend/src/components/Release/ReleaseDetail/ReleaseFileTable/index.ts

chore: add release file detail panel

---

backend/api/v1/branch_service.go
backend/api/v1/branch_service_test.go

fix: avoid creating existed schema

---

backend/plugin/parser/tsql/query_span_extractor.go

fix(query-span): fix nil ctx

---

frontend/src/components/IssueV1/components/Sidebar/PreBackupSection/PreBackupSection.vue
frontend/src/components/IssueV1/components/Sidebar/ReleaseInfo.vue
frontend/src/components/IssueV1/components/Sidebar/Sidebar.vue
frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
frontend/src/components/IssueV1/components/StatementSection/useTaskSheet.ts
frontend/src/components/IssueV1/components/TaskListSection/TaskCard.vue
frontend/src/components/MonacoEditor/lsp-client.ts
frontend/src/components/Release/ReleaseDetail/NavBar/ApplyToDatabasePanel.vue
frontend/src/store/cache.ts
frontend/src/store/modules/release.ts
frontend/src/store/modules/v1/policy.ts

chore: show release info in issue page

---

backend/plugin/parser/pg/completion.go

feat(lsp): return all columns for the no table case

---

backend/plugin/parser/mysql/completion.go

feat(lsp): return all columns for MySQL no table case

---

backend/plugin/parser/plsql/completion.go
backend/plugin/parser/plsql/test-data/test_completion.yaml

feat(plsql-lsp): return all columns for no table

---

backend/api/lsp/completion.go
backend/plugin/parser/tsql/completion.go
backend/plugin/parser/tsql/test-data/test_completion.yaml

feat(mssql-lsp): return all columns for no table

---

frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

There are multiple ways to specify country code. We'd better provide the format hint.

chore: add phone country code prefix in the hint

---

backend/plugin/parser/base/complete.go
backend/plugin/parser/plsql/test-data/test_completion.yaml

fix(lsp): append definition to candidate ID

---

frontend/src/DummyRootView.ts

chore(sql-editor): default route for EDITOR mode should go before isDev

---

frontend/src/components/IssueV1/components/Sidebar/ReleaseInfo.vue
frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
frontend/src/components/IssueV1/components/TaskListSection/TaskCard.vue
frontend/src/components/Release/ReleaseDataTable.vue
frontend/src/components/Release/ReleaseDetail/BasicInfo.vue
frontend/src/components/Release/ReleaseDetail/NavBar/ApplyToDatabasePanel.vue
frontend/src/components/Release/ReleaseDetail/ReleaseDetail.vue
frontend/src/components/Release/ReleaseDetail/ReleaseFileTable/ReleaseFileTable.vue

chore: update release detail page

---

backend/plugin/parser/pg/resource_change.go
backend/plugin/parser/pg/resource_change_test.go

feat(pg): changed resources support DML

---

backend/plugin/parser/plsql/resource_change.go
backend/plugin/parser/plsql/resource_change_test.go

feat(oracle): changed resources support DML

---

frontend/src/components/ChangeHistory/ChangeHistoryDataTable.vue
frontend/src/components/Database/DatabaseChangeHistoryPanel.vue
frontend/src/components/Database/DatabaseRevisionPanel.vue
frontend/src/components/Revision/PagedRevisionTable.vue
frontend/src/components/Revision/RevisionDataTable.vue
frontend/src/components/Revision/index.ts
frontend/src/views/DatabaseDetail.vue

Part of BYT-6404. Also under `isDev` guard.

feat: add revisions tab to database detail page

---

backend/api/v1/instance_service.go
backend/migrator/migration/dev/20241014000001##release.sql
backend/store/instance.go
backend/store/release.go
backend/store/revision.go

chore(store): implement deleting release&revision

---

frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
frontend/src/components/AlterSchemaPrepForm/SchemaEditorSQLCheckButton/SchemaEditorSQLCheckButton.vue
frontend/src/components/Branch/BranchDetailView.vue
frontend/src/components/Branch/SchemaDesignEditorLite.vue
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunComment.vue
frontend/src/components/SQLCheck/SQLCheckButton.vue
frontend/src/components/SQLCheck/SQLCheckPanel.vue
frontend/src/components/SchemaEditorLite/common.ts
frontend/src/components/SchemaEditorLite/utils/metadata.ts

- Disallow to create the issue if failed to generate the statement. Close BYT-6171
- Fix the invisible "view change" on the small screen. Close BYT-6373

chore: disallow to create issue if generate statement failed

---

frontend/src/DummyRootView.ts
frontend/src/plugins/ai/components/ChatPanel.vue
frontend/src/plugins/ai/components/DynamicSuggestions.vue
frontend/src/plugins/ai/components/ProvideAIContext.vue
frontend/src/plugins/ai/logic/prompt.ts
frontend/src/plugins/ai/logic/useDynamicSuggestions.ts
frontend/src/plugins/ai/types/context.ts
frontend/src/views/sql-editor/EditorPanel/Panels/Panels.vue
frontend/src/views/sql-editor/EditorPanel/StandardPanel/SQLEditor.vue
frontend/src/views/sql-editor/EditorPanel/StandardPanel/state.ts

chore(sql-editor): cherry-pick some AI Assistant fixes to 2.23.1

---

frontend/src/components/IssueV1/components/Sidebar/GhostSection/GhostSection.vue
frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
frontend/src/components/IssueV1/components/TaskListSection/TaskCard.vue
frontend/src/components/Plan/components/HeaderSection/Actions/create/CreateIssueButton.vue

fix: missing issue description from plan

---

frontend/src/views/sql-editor/EditorPanel/context/index.ts
frontend/src/views/sql-editor/TabList/TabList.vue

chore(sql-editor): reset unrelated view state when adding new tab

---

frontend/src/utils/auto-route.ts

chore(sql-editor): auto-route should go to sql-editor routes only when databaseChangeMode is EDITOR

---

backend/api/v1/database_service.go
backend/plugin/parser/pg/filter.go
backend/plugin/parser/pg/filter_test.go
backend/plugin/parser/pg/pg.go
backend/plugin/parser/pg/test-data/filter.yaml
frontend/src/components/SyncDatabaseSchema/SelectTargetDatabasesView.vue
frontend/src/types/proto/v1/database_service.ts
frontend/src/utils/v1/instance.ts
proto/gen/grpc-doc/openapi.yaml
proto/gen/grpc-doc/v1/README.md
proto/gen/grpc-doc/v1/index.html
proto/generated-go/v1/database_service.pb.go
proto/v1/database_service.proto

feat(differ): ignore backup schema for PG in schema synchronization

---

backend/plugin/parser/base/interface.go
backend/plugin/parser/base/span.go
backend/plugin/parser/mysql/query_span_extractor.go
backend/plugin/parser/mysql/query_span_test.go
backend/plugin/parser/mysql/test-data/query-span/starrocks.yaml

chore(query-span): ignore cluster name for StarRocks

---

backend/plugin/advisor/code.go
backend/plugin/advisor/pg/advisor_table_comment_convention.go
backend/plugin/advisor/pg/pg_rules_test.go
backend/plugin/advisor/pg/test/table_comment.yaml
backend/plugin/advisor/sql_review.go
backend/plugin/parser/sql/engine/pg/convert.go
backend/tests/sql_review_test.go
backend/tests/test-data/sql_review_pg.yaml
frontend/src/types/sql-review-schema.yaml
frontend/src/types/sql-review.prod.yaml

feat(sql-review): table comment convention for postgres

---

backend/plugin/advisor/code.go
backend/plugin/advisor/pg/advisor_column_comment_convention.go
backend/plugin/advisor/pg/pg_rules_test.go
backend/plugin/advisor/pg/test/column_comment.yaml
backend/plugin/advisor/sql_review.go
backend/tests/sql.go
frontend/src/types/sql-review-schema.yaml
frontend/src/types/sql-review.prod.yaml

feat(sql-review): column comment convention for postgres

---

backend/plugin/advisor/code.go
backend/plugin/advisor/oracle/advisor_table_comment_convention.go
backend/plugin/advisor/oracle/oracle_rules_test.go
backend/plugin/advisor/oracle/test/table_comment.yaml
backend/plugin/advisor/pg/advisor_column_comment_convention.go
backend/plugin/advisor/pg/advisor_table_comment_convention.go
backend/plugin/advisor/sql_review.go
backend/plugin/parser/plsql/util.go
frontend/src/types/sql-review-schema.yaml
frontend/src/types/sql-review.prod.yaml

feat(sql-review): table comment convention for oracle

---

backend/component/iam/acl.yaml
backend/component/iam/permission.go
backend/component/iam/permission.yaml

bb.databases.queryExplain: explain select query.
bb.databases.queryInfo: system objects such as information schema.

chore: query permissions

---

backend/plugin/advisor/code.go
backend/plugin/advisor/oracle/advisor_column_comment_convention.go
backend/plugin/advisor/oracle/advisor_table_comment_convention.go
backend/plugin/advisor/oracle/advisor_table_no_foreign_key.go
backend/plugin/advisor/oracle/advisor_table_require_pk.go
backend/plugin/advisor/oracle/oracle_rules_test.go
backend/plugin/advisor/oracle/parser.go
backend/plugin/advisor/oracle/test/column_comment.yaml
backend/plugin/advisor/sql_review.go
frontend/src/types/sql-review-schema.yaml
frontend/src/types/sql-review.prod.yaml

feat(sql-review): column comment convention for oracle

---

frontend/src/components/Database/DatabaseRevisionPanel.vue
frontend/src/components/Release/ReleaseDataTable.vue
frontend/src/components/Release/ReleaseDetail/NavBar/ApplyToDatabasePanel.vue
frontend/src/components/Release/ReleaseDetail/ReleaseFileTable/ReleaseFileTable.vue
frontend/src/components/Revision/RevisionDataTable.vue
frontend/src/components/Revision/RevisionDetailPanel.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

Part of BYT-6404, and fix https://github.com/bytebase/bytebase/pull/14132#pullrequestreview-2377301612

chore: update revision detail panel

---

backend/plugin/advisor/mysql/advisor_insert_row_limit.go
backend/plugin/advisor/mysql/advisor_statement_affected_row_limit.go
backend/plugin/advisor/mysql/advisor_statement_disallow_using_filesort.go
backend/plugin/advisor/mysql/advisor_statement_disallow_using_temporary.go
backend/plugin/advisor/mysql/advisor_statement_dml_dry_run.go
backend/plugin/advisor/mysql/advisor_statement_query_minumum_plan_level.go
backend/plugin/advisor/mysql/advisor_statement_select_full_table_scan.go
backend/plugin/advisor/oracle/advisor_statement_dml_dry_run.go
backend/plugin/advisor/pg/advisor_insert_row_limit.go
backend/plugin/advisor/pg/advisor_statement_affected_row_limit.go
backend/plugin/advisor/pg/advisor_statement_dml_dry_run.go
backend/plugin/advisor/tidb/advisor_statement_dml_dry_run.go
backend/plugin/advisor/utils.go

fix(sql-review): run set role for Query

---

backend/plugin/advisor/code.go
backend/plugin/advisor/mysql/advisor_column_require_charset.go
backend/plugin/advisor/mysql/advisor_column_require_collation.go
backend/plugin/advisor/sql_review.go
frontend/src/locales/sql-review/en-US.json
frontend/src/locales/sql-review/es-ES.json
frontend/src/locales/sql-review/ja-JP.json
frontend/src/locales/sql-review/zh-CN.json
frontend/src/types/sql-review-schema.yaml
frontend/src/types/sql-review.prod.yaml

chore(sql-review-rules): require charset/collation for columns in mysql

---

frontend/src/utils/workspaceApprovalSetting.ts

fix: update approval setting checks

---

go.mod

chore: negative serial number

---

backend/plugin/db/mysql/query.go
backend/plugin/db/mysql/query_test.go

fix: mysql limit rewriter should respect `LIMIT m,n`

---

frontend/src/views/project/ProjectSyncDatabasePanel.vue

fix: add conciseHistory for Postgres and Oracle in ProjectSyncDatabasePanel

---

backend/api/v1/plan_service.go
frontend/src/components/DatabaseAndGroupSelector/DatabaseAndGroupSelector.vue
frontend/src/components/Release/ReleaseDetail/NavBar/ApplyToDatabasePanel.vue
frontend/src/components/Release/ReleaseDetail/NavBar/PreviewPlanDetail.vue
frontend/src/components/Release/ReleaseDetail/NavBar/utils.ts
frontend/src/components/Release/ReleaseDetail/ReleaseFileTable/ReleaseFileDetailPanel.vue
frontend/src/components/v2/Form/StepTab.vue
frontend/src/components/v2/Model/DatabaseView.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

feat: preview plan before creating issue

---

frontend/src/components/MonacoEditor/MonacoEditor.vue
frontend/src/components/MonacoEditor/MonacoTextModelEditor.vue
frontend/src/components/misc/SQLUploadButton.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/views/sql-editor/EditorPanel/StandardPanel/SQLEditor.vue
frontend/src/views/sql-editor/EditorPanel/StandardPanel/UploadFileButton.vue

feat(sql-editor): support upload sql file

---

frontend/src/components/IssueV1/logic/initialize/create.ts
frontend/src/components/Release/ReleaseDetail/NavBar/ApplyToDatabasePanel.vue

chore: remove unused release when creating issue

---

frontend/src/components/Release/ReleaseDetail/NavBar/ApplyToDatabasePanel.vue
frontend/src/components/Release/ReleaseDetail/NavBar/PreviewPlanDetail.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

chore: add checkbox for allow out of order

---

frontend/src/views/ProfileDashboard.vue

chore: unify inputs size

---

frontend/src/views/sql-editor/EditorCommon/ResultView/DataTableLite/DataTableLite.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
frontend/src/views/sql-editor/EditorPanel/TerminalPanel/TerminalPanel.vue

Similar to #13501
Close BYT-6531

chore(sql-editor): fix auto height when zoomed

---

frontend/src/components/ColumnDataTable/index.vue

chore(frontend): render nullable column with readonly checkbox

---

frontend/src/components/Release/ReleaseDetail/NavBar/ApplyToDatabasePanel.vue

https://github.com/user-attachments/assets/25a7e6e3-71a3-43db-85f2-33c1835bed1c

chore: allow change `allowOutOfOrder` in preview step

---

frontend/src/components/IssueV1/components/HeaderSection/Actions/review/IssueReviewButtonGroup.vue
frontend/src/store/modules/v1/issue.ts

chore: remove role checks

---

backend/plugin/advisor/mysql/advisor_builtin_prior_backup_check.go
backend/plugin/advisor/mysql/advisor_naming_identifier_no_keyword.go
backend/plugin/advisor/mysql/advisor_statement_disallow_mix_in_ddl.go
backend/plugin/advisor/mysql/advisor_statement_disallow_mix_in_dml.go
backend/plugin/advisor/mysql/advisor_statement_join_strict_column_attrs.go
backend/plugin/advisor/mysql/test/column_set_default_for_not_null.yaml
backend/plugin/advisor/mysql/test/statement_disallow_mix_in_ddl.yaml
backend/plugin/advisor/mysql/test/statement_disallow_mix_in_dml.yaml
backend/plugin/advisor/mysql/test/statement_max_execution_time.yaml
backend/plugin/advisor/mysql/test/statement_require_algorithm_option.yaml
backend/plugin/advisor/mysql/test/statement_require_lock_option.yaml

fix(sql-review): fix line number for MySQL sql review rule

---

frontend/src/components/PlanCheckRun/PlanCheckRunDetail.vue
frontend/src/components/SQLReview/components/SQLRuleEditDialog.vue
frontend/src/components/SQLReview/components/SQLRuleFilter.vue
frontend/src/components/SQLReview/components/SQLRuleTable.vue
frontend/src/locales/sql-review/en-US.json
frontend/src/locales/sql-review/es-ES.json
frontend/src/locales/sql-review/ja-JP.json
frontend/src/locales/sql-review/zh-CN.json
frontend/src/types/sqlReview.ts

chore: update getRuleLocalization to support engine-specific localization

---

backend/plugin/parser/mysql/query_span_extractor.go
backend/plugin/parser/pg/query_span_extractor.go
backend/plugin/parser/pg/test-data/query_span.yaml
backend/plugin/parser/plsql/query_span_extractor.go
backend/plugin/parser/tidb/query_span_extractor.go
backend/plugin/parser/tsql/query_span_extractor.go

fix: check NotFoundError in query span implementation

---

backend/plugin/parser/sql/ast/create_materialized_view_stmt.go
backend/plugin/parser/sql/ast/table_def.go
backend/plugin/parser/sql/engine/pg/convert.go
backend/plugin/parser/sql/engine/pg/convert_test.go

feat: add Postgres CREATE MATERIALIZED VIEW statement

---

frontend/src/components/IssueV1/logic/poll.ts
frontend/src/store/modules/v1/cache.ts
frontend/src/store/modules/v1/instance.ts
frontend/src/views/InstanceDetail.vue
frontend/src/views/ProfileDashboard.vue

fix: clear cache after issue done

---

frontend/src/components/GrantRequestPanel/DatabaseResourceForm/DatabaseResourceSelector.vue
frontend/src/components/GrantRequestPanel/DatabaseResourceForm/Label.vue
frontend/src/components/GrantRequestPanel/DatabaseResourceForm/common.ts

chore: cascade select tree node in database resource selector

---

backend/server/routers.go

no more annoying not found errors.

chore: reorder middlewares

---

frontend/src/components/IssueV1/components/Sidebar/ReleaseInfo.vue
frontend/src/components/Project/ProjectReleasesPanel.vue

Part of BYT-6523
* add tag for archived releases in issue detail page;
* remove show archived checkbox;

chore: add tag for archived releases

---

backend/plugin/parser/bigquery/query_span_extractor.go
backend/plugin/parser/bigquery/test-data/query-span/standard.yaml

feat(query-span): handle table subquery for bigquery query span

---

frontend/src/locales/ja-JP.json

Corrections have been made due to slight differences in Japanese translation nuances on general page.

fix(i18n): Fix japanese translation on general page

---

frontend/src/locales/ja-JP.json

Corrections have been made due to slight differences in Japanese translation nuances on sql editor.

fix(i18n): Fix japanese translations on sql editor

---

backend/plugin/parser/bigquery/query_span_extractor.go
backend/plugin/parser/bigquery/test-data/query-span/standard.yaml
go.mod
go.sum

feat(query-span): handle bigquery query span table wild in projection 

---

frontend/src/components/SQLCheck/SQLCheckButton.vue
frontend/src/composables/useExecuteSQL.ts

fix: should judge by the byte size

---

backend/api/v1/sql_service.go
frontend/src/components/GrantRequestPanel/DatabaseResourceForm/DatabaseResourceSelector.vue
frontend/src/components/GrantRequestPanel/DatabaseResourceForm/common.ts
frontend/src/components/GrantRequestPanel/GrantRequestPanel.vue
frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/DatabaseNode.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/RequestQueryButton.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue

chore: optimize grant access

---

backend/api/v1/database_service.go
backend/api/v1/plan_service.go
backend/api/v1/sql_service.go
backend/runner/schemasync/syncer.go

feat: store backup available when sync schema

---

frontend/src/components/GeneralSetting/DatabaseChangeModeSetting.vue
frontend/src/components/GeneralSetting/NetworkSetting.vue
frontend/src/composables/useExecuteSQL.ts
frontend/src/router/dashboard/workspaceSetting.ts
frontend/src/views/DashboardHeader.vue
frontend/src/views/DashboardSidebar.vue
frontend/src/views/SettingWorkspaceGeneral.vue

chore: consolidate settings sidebar

---

frontend/src/components/Project/ProjectReleasesPanel.vue
frontend/src/components/Release/ReleaseCreate/ReleaseCreate.vue
frontend/src/components/Release/ReleaseCreate/ReleaseFileTable/CreateReleaseFilesPanel.vue
frontend/src/components/Release/ReleaseCreate/ReleaseFileTable/ReleaseFileDetailPanel.vue
frontend/src/components/Release/ReleaseCreate/ReleaseFileTable/ReleaseFileTable.vue
frontend/src/components/Release/ReleaseCreate/ReleaseFileTable/index.ts
frontend/src/components/Release/ReleaseCreate/context.ts
frontend/src/components/Release/ReleaseCreate/index.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/router/dashboard/projectV1.ts

Part of BYT-6533, creating release with raw statements.

chore: release creation page

---

frontend/src/locales/ja-JP.json

Corrections have been made due to slight differences in Japanese translation nuances on project page.

fix(i18n): Fix japanese translations on project page

---

frontend/src/components/IssueV1/components/Sidebar/ReviewSection/Candidates.vue
frontend/src/components/IssueV1/components/Sidebar/ReviewSection/Timeline.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

chore: add more tips to issue approval flow popover

---

backend/plugin/db/mysql/sync.go

perf: optimize the CPU load of sync on MySQL instance

---

frontend/src/components/Changelist/ChangelistDetail/NavBar/ImportButton.vue
frontend/src/components/Release/ReleaseCreate/FileToCreateTable/CreateReleaseFilesPanel.vue
frontend/src/components/Release/ReleaseCreate/FileToCreateTable/UploadFilesButton.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

chore: import files/zip from local to release

---

backend/plugin/db/mysql/sync.go

fix: mysql information_schema charset

---

backend/plugin/parser/bigquery/split.go
backend/plugin/parser/bigquery/split_test.go

feat: bigquery split

---

frontend/src/components/Release/ReleaseDetail/BasicInfo.vue
frontend/src/components/Release/ReleaseDetail/NavBar/ApplyToDatabasePanel.vue
frontend/src/components/Release/ReleaseDetail/NavBar/PreviewPlanDetail.vue
frontend/src/components/Release/ReleaseDetail/ReleaseFileTable/ReleaseFileTable.vue

chore: tweak release detail page

---

frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTableLite/ColumnHeader.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTableLite/DataTableLite.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTableLite/useTableResize.ts

following #14224 
now they look almost pixel-perfect the same

chore(sql-editor): unify DataTable and DataTableLite style

---

frontend/src/components/ChangeHistory/ChangeHistoryDetail.vue
frontend/src/components/Changelist/ChangelistDetail/ChangeHistoryDetailPanel/ChangeHistoryDetailPanel.vue
frontend/src/components/Database/DatabaseChangeHistoryPanel.vue
frontend/src/views/ChangeHistoryDetail.vue

chore: use page instead of drawer for change history detail

---

frontend/src/components/VCS/utils.ts
frontend/src/plugins/i18n.ts
frontend/src/types/plan.ts
frontend/src/types/semanticTypes.ts
frontend/src/utils/v1/instance.ts

fix: not use useI18n in ts file

---

frontend/package.json
frontend/pnpm-lock.yaml

Reverts bytebase/bytebase#14289

chore: revert "chore: bump @intlify/unplugin-vue-i18n from 4.0.0 to 5.2.0 in /frontend"

---

frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue

chore(sql-editor): always show query result pagination

---

backend/api/v1/sql_service.go

feat(query): respect data source query environment policy for MySQL

---

backend/plugin/advisor/pg/advisor_statement_object_owner_check.go
backend/store/model/database.go

fix: fix the nil pointer error

---

frontend/src/components/IssueV1/logic/action/task.ts

chore: allow to cancel baseline task

---

frontend/src/layouts/ProjectV1Layout.vue

chore: always show grant request buttons

---

backend/api/v1/audit_log_service.go
frontend/src/components/DataExportButton.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/v1/auditLog.ts
frontend/src/types/proto/v1/audit_log_service.ts
frontend/src/views/SettingWorkspaceAuditLog.vue
frontend/src/views/project/ProjectAuditLogDashboard.vue
proto/gen/grpc-doc/openapi.yaml
proto/gen/grpc-doc/v1/README.md
proto/gen/grpc-doc/v1/index.html
proto/generated-go/v1/audit_log_service.pb.go
proto/v1/audit_log_service.proto

fix: export audit logs

---

backend/common/util.go
frontend/src/components/SQLCheck/SQLCheckButton.vue

chore: increase the size limit to 2M

---

frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorActionPopover.vue
frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
frontend/src/components/IssueV1/components/StatementSection/EditorView/InstanceRoleSelect.vue
frontend/src/components/IssueV1/components/StatementSection/EditorView/context.ts

Close BYT-6532
https://github.com/user-attachments/assets/a10643c4-5921-401d-845b-59f37d8262c4

chore: add role selector for postgres

---

backend/plugin/parser/pg/query_span_extractor.go
backend/plugin/parser/pg/query_type.go
backend/plugin/parser/pg/test-data/query_span.yaml

feat: implement query type for PG

---

backend/api/v1/sql_service.go
backend/plugin/parser/plsql/query_span_extractor.go
backend/plugin/parser/plsql/query_type.go
backend/plugin/parser/plsql/test-data/query_span.yaml

feat: implement query type for oracle

---

backend/api/v1/sql_service.go
backend/plugin/parser/tidb/query_span_extractor.go
backend/plugin/parser/tidb/query_type.go
backend/plugin/parser/tidb/test-data/query_span.yaml

feat: TiDB Query Type

---

backend/plugin/db/redis/sync.go

Reverts bytebase/bytebase#14114

fix: Revert "fix: redis get database with proxy"

---

backend/plugin/db/redis/sync.go

We use database count from both "config get databases" and "info keyspace".

chore: database count

---

backend/plugin/parser/base/span.go
backend/plugin/parser/mysql/query_type.go
backend/plugin/parser/pg/query_type.go
backend/plugin/parser/pg/test-data/query_span.yaml
backend/plugin/parser/tidb/query_type.go
backend/plugin/parser/tidb/test-data/query_span.yaml

feat: introduce explain analyze query type

---

frontend/src/components/PlanCheckRun/PlanCheckRunDetail.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

chore(frontend): add placeholder for plan check run detail

---

backend/plugin/advisor/code.go
backend/plugin/advisor/mysql/advisor_table_disallow_ddl.go
backend/plugin/advisor/mysql/advisor_table_disallow_dml.go
backend/plugin/advisor/sql_review.go
frontend/src/types/sql-review-schema.yaml
frontend/src/types/sql-review.prod.yaml

chore(sql-review-rule): disallow ddl/dml for specific tables

---

backend/plugin/advisor/mysql/advisor_function_disallowed_list.go
backend/plugin/parser/mysql/normalize.go

fix: advisor panic error

---

backend/bin/server/cmd/profile.go
backend/bin/server/cmd/root.go
backend/component/config/profile.go

https://github.com/bytebase/bytebase/issues/14374

feat: added json logging flag

---

frontend/src/components/SyncDatabaseSchema/index.vue

fix: database list value in sync schema

---

frontend/src/components/User/Settings/UserDataTable/cells/UserNameCell.vue

fix: button size

---

frontend/src/views/sql-editor/EditorCommon/ResultView/DataTableLite/DataTableLite.vue

chore(sql-editor): use correct row index

---

backend/plugin/parser/base/span.go
backend/plugin/parser/mysql/query_span_extractor.go
backend/plugin/parser/mysql/query_type.go
backend/plugin/parser/mysql/test-data/query-span/query_type.yaml
backend/plugin/parser/pg/query_span_extractor.go
backend/plugin/parser/pg/query_type.go
backend/plugin/parser/pg/test-data/query_type.yaml
backend/plugin/parser/tidb/query_span_extractor.go
backend/plugin/parser/tidb/query_span_test.go
backend/plugin/parser/tidb/query_type.go
backend/plugin/parser/tidb/test-data/query_type.yaml

chore: treat EXPLAIN ANALYZE as the inner statement type

---

frontend/src/components/Member/MemberDataTable/cells/UserOperationsCell.vue
frontend/src/components/Member/utils.ts
frontend/src/components/User/Settings/UserDataTable/cells/UserOperationsCell.vue
frontend/src/components/User/Settings/UserDataTable/index.vue
frontend/src/views/ProfileDashboard.vue
frontend/src/views/SettingWorkspaceUsers.vue

chore: redirect to profile page

---

frontend/src/locales/ja-JP.json

Corrected nuances in Japanese translation

fix(i18n): Fix japanese translations

---

backend/api/v1/sql_service.go

feat(query-type): disallow running unknown statement type

---

backend/migrator/migration/prod/3.1/0000##sheet_blob.sql
backend/migrator/migrator.go

use `ListInstanceChangeHistoryForMigrator`.
keep sheet.statement for several versions, just in case

fix: sheet blob

---

frontend/src/components/Rollout/RolloutDetail/RolloutDetailLayout.vue
frontend/src/components/Rollout/RolloutDetail/TaskDetail/BasicInfo.vue
frontend/src/components/Rollout/RolloutDetail/TaskDetail/Panels/Overview.vue
frontend/src/components/Rollout/RolloutDetail/TaskDetail/Panels/TaskRunLogs.vue
frontend/src/components/Rollout/RolloutDetail/TaskDetail/TaskDetail.vue
frontend/src/components/Rollout/RolloutDetail/TaskDetail/utils.ts
frontend/src/components/Rollout/RolloutDetail/context.ts
frontend/src/components/Rollout/RolloutDetail/poll.ts

chore: update task detail page

---

frontend/src/components/Database/DatabaseOverviewPanel.vue
frontend/src/components/Icon/PackageIcon.vue
frontend/src/components/Icon/index.ts
frontend/src/components/PackageDataTable.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/utils/v1/instance.ts
frontend/src/views/sql-editor/AsidePanel/SchemaPane/SchemaPane.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/SyncSchemaButton.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/Label.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/PackageNode.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/actions.tsx
frontend/src/views/sql-editor/AsidePanel/SchemaPane/common.ts
frontend/src/views/sql-editor/EditorPanel/GutterBar/TabItem.vue
frontend/src/views/sql-editor/EditorPanel/Panels/InfoPanel/InfoPanel.vue
frontend/src/views/sql-editor/EditorPanel/Panels/PackagesPanel/PackagesPanel.vue
frontend/src/views/sql-editor/EditorPanel/Panels/PackagesPanel/PackagesTable.vue
frontend/src/views/sql-editor/EditorPanel/Panels/PackagesPanel/index.ts
frontend/src/views/sql-editor/EditorPanel/Panels/Panels.vue
frontend/src/views/sql-editor/EditorPanel/context/index.ts
frontend/src/views/sql-editor/EditorPanel/types.ts

feat(frontend): display package metadata for ORACLE

---

backend/api/v1/sql_service.go
backend/plugin/parser/tsql/query_span_extractor.go
backend/plugin/parser/tsql/query_type.go
backend/plugin/parser/tsql/test-data/query-span/query_type.yaml
backend/plugin/parser/tsql/test-data/test_backup.yaml
backend/plugin/parser/tsql/tsql.go
go.mod
go.sum

feat: allow sql server declare variable

---

backend/api/v1/sql_service.go
backend/plugin/db/pg/pg.go
backend/runner/plancheck/statement_advise_executor.go
backend/runner/plancheck/statement_report_executor.go
backend/runner/taskrun/data_update_executor.go
backend/runner/taskrun/executor.go

chore: implement Postgres database tenant mode

---

frontend/src/components/SchemaEditorLite/Panels/TableColumnEditor/components/DefaultValueCell.vue

chore(sql-editor): default NULL should be disabled when NOT NULL

---

frontend/src/views/sql-editor/EditorCommon/ResultView/DataTableLite/DataTableLite.vue

chore(sql-editor): fix horizontal scrollbar visibility

---

backend/plugin/advisor/mysql/advisor_table_disallow_ddl.go

fix: fix npe in disallow ddl

---

frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/useTableResize.ts
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTableLite/DataTableLite.vue

Unified scrollbar style and logic across windows and mac, DataTable and DataTableLite

chore(sql-editor): more scrollbar fixes

---

frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
frontend/src/types/appProfile.ts

* only show the button when current user has related permissions

chore: update transfer in action position

---

backend/api/v1/sql_service.go
backend/plugin/advisor/advisor.go
backend/plugin/advisor/pg/advisor_insert_row_limit.go
backend/plugin/advisor/pg/advisor_statement_affected_row_limit.go
backend/plugin/advisor/pg/advisor_statement_dml_dry_run.go
backend/plugin/advisor/pg/advisor_statement_object_owner_check.go
backend/plugin/advisor/sql_review.go
backend/plugin/advisor/utils.go
backend/plugin/advisor/utils_for_tests.go
backend/runner/plancheck/statement_advise_executor.go

chore: set different default postgres role for sql review

---

frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/DetailCell/DetailCell.vue
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/DetailCell/ErrorCell.vue
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/DetailCell/PriorBackupCell.vue
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/common.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

chore: show prior backup tables in task run log

---

helm-charts/bytebase/templates/statefulset.yaml
helm-charts/bytebase/values.yaml

- Schedule bytebase pod to a specific node pool that uses "stable" nodes.

feat(helm): add nodeAffinity

---

frontend/src/components/Plan/components/HeaderSection/Actions/create/CreateButton.vue
frontend/src/components/Plan/components/SpecListSection/SpecCard.vue
frontend/src/components/Plan/components/SpecListSection/SpecListSection.vue

Following https://github.com/bytebase/bytebase/pull/14445

chore: fix flatten spec list

---

frontend/src/components/Project/ProjectSwitchPopover.vue
frontend/src/components/v2/Model/ProjectV1Table.vue
frontend/src/views/DashboardHeader.vue

More easy to change project and back to workspace with shorten mouse distance.
https://github.com/user-attachments/assets/a0a7b01d-a0ad-440c-b0ea-24dd3715649b

chore: use popover instead of model to change current project

---

backend/plugin/advisor/mysql/advisor_builtin_prior_backup_check.go
backend/plugin/advisor/mysql/advisor_table_disallow_dml.go
backend/plugin/parser/mysql/backup.go
backend/plugin/parser/mysql/backup_test.go
backend/plugin/parser/mysql/restore.go
backend/plugin/parser/mysql/test-data/test_backup.yaml
backend/plugin/parser/mysql/test-data/test_restore.yaml

feat: implement MySQL backup, restore and prior backup rule v2

---

backend/plugin/advisor/mysql/advisor_builtin_prior_backup_check.go
backend/runner/taskrun/data_update_executor.go

feat: implement 2M limit to backup

---

frontend/src/components/AdvancedSearch/TimeRange.vue

chore: use `datetimerange` for `issue`/`audit log` advanced search

---

frontend/src/components/SSO/IdentityProviderCreateForm.vue

chore: add tooltip for disabled sso feature

---

frontend/src/components/GeneralSetting/AccountSetting.vue

chore: account setting ui layout

---

frontend/src/views/project/ProjectVersionControlPanel.vue

feat: db group & base dir column for project vcs connectors page

---

frontend/src/components/v2/Select/DatabaseGroupSelect.vue

fix: dbgroup selector

---

backend/demo/data/default/README.md

Fix demo data prior-backup not available

chore: update demo data to record sync schema metadata

---

frontend/src/components/EnvironmentForm/Form.vue

chore: white color warning

---

helm-charts/helm_test.go

chore(helm): update tag helm artifact

---

frontend/src/components/ExpirationSelector.vue
frontend/src/components/GrantRequestPanel/GrantRequestPanel.vue
frontend/src/components/ProjectMember/AddProjectMember/AddProjectMemberForm.vue
frontend/src/components/SensitiveData/GrantAccessForm.vue
frontend/src/components/SensitiveData/MaskingExceptionUserTable.vue

chore:  expiration time precise to the second

---

backend/api/v1/database_converter.go
backend/plugin/db/mysql/sync.go

feat: sync MySQL event

---

helm-charts/bytebase/templates/statefulset.yaml
helm-charts/bytebase/values.yaml

Ref: https://github.com/bytebase/bytebase/issues/14476

feat(helm): Add Tolerations

---

backend/api/v1/sql_service.go
backend/plugin/advisor/advisor.go
backend/plugin/advisor/mssql/advisor_builtin_prior_backup_check.go
backend/plugin/advisor/mysql/advisor_builtin_prior_backup_check.go
backend/plugin/advisor/oracle/advisor_builtin_prior_backup_check.go
backend/plugin/advisor/sql_review.go
backend/plugin/advisor/tidb/advisor_builtin_prior_backup_check.go
backend/plugin/advisor/utils.go
backend/runner/plancheck/statement_advise_executor.go

chore: use metadata to check database exists for backup

---

frontend/src/components/EnvironmentForm/AccessControlConfigure.vue

fix: disallow ddl/dml should in the paid plan

---

frontend/src/components/Database/DatabaseOverviewPanel.vue
frontend/src/components/FunctionDataTable.vue
frontend/src/components/MonacoEditor/composables/useAutoComplete.ts
frontend/src/components/PackageDataTable.vue
frontend/src/components/SchemaDiagram/Navigator/TreeNode/Label.vue
frontend/src/components/SchemaEditorLite/spec.ts
frontend/src/components/TableDataTable.vue
frontend/src/components/TableDetailDrawer.vue
frontend/src/components/ViewDataTable.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/types/sqlEditor/editor.ts
frontend/src/utils/v1/instance.ts
frontend/src/views/sql-editor/AsidePanel/SchemaPane/SchemaPane.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/CommonNode.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/SchemaNode.vue
frontend/src/views/sql-editor/EditorCommon/SchemaChooser.vue
frontend/src/views/sql-editor/EditorPanel/Panels/common/SchemaSelectToolbar.vue
frontend/src/views/sql-editor/EditorPanel/StandardPanel/SQLEditor.vue
frontend/src/views/sql-editor/EditorPanel/TerminalPanel/CompactSQLEditor.vue
frontend/src/views/sql-editor/EditorPanel/context/index.ts

@h3n4l plz help some testing 🙏
Close BYT-6665

chore(frontend): support spanner "Default" schema

---

frontend/.pnpmfile.cjs
frontend/pnpm-lock.yaml

https://github.com/bytebase/bytebase/security/dependabot/65
Close BYT-6662

chore(frontend): fix security vulnerability

---

frontend/src/components/DatabaseAndGroupSelector/DatabaseAndGroupSelector.vue
frontend/src/components/ProjectDatabasesPanel.vue

chore: add database filter to apply database panel

---

backend/api/v1/org_policy_service.go
frontend/src/components/EnvironmentForm/AccessControlConfigure.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

Works with https://github.com/bytebase/bytebase/pull/14539

chore: move disallow ddl/dml to free

---

backend/api/v1/sql_service.go
frontend/src/utils/v1/database.ts
frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/DatabaseNode.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue

Close BYT-6672
@adela-bytebase plz help some testing 🙏

chore(sql-editor): query permissions in free/pro plan

---

frontend/src/components/Rollout/RolloutDetail/TaskDetail/Panels/Overview.vue

chore: add blocking task alter view

---

frontend/src/customAppProfile.ts
frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue

@adela-bytebase will help testing

chore(sql-editor): sql editor users should not see "Export Data" in sql editor in free/pro plan

---

frontend/src/components/ExternalTableDetailDrawer.vue
frontend/src/components/GrantRequestPanel/DatabaseResourceForm/index.vue
frontend/src/components/TableDetailDrawer.vue
frontend/src/views/DatabaseDetail/DatabaseDetail.vue
frontend/src/views/sql-editor/Setting/Instance/Instance.vue

- Hide SQL editor button if users don't have the permission
- Fix instance drawer header

chore: minor optimize

---

frontend/src/views/sql-editor/EditorCommon/OpenAIButton/Button.vue

fix(sql-editor): Open AI button is now shown on Safari

---

frontend/src/components/EnvironmentForm/AccessControlConfigure.vue
frontend/src/views/sql-editor/EditorCommon/ExecuteHint.vue

chore(frontend): enable environment DML/DDL policy settings for SQL Editor Mode

---

frontend/src/views/sql-editor/EditorCommon/ResultView/DetailPanel/DetailPanel.vue

chore(sql-editor): copy formatted value

---

frontend/src/views/DashboardLanding.vue

FYI @adela-bytebase 
https://github.com/user-attachments/assets/716b52d7-0ac7-4097-9dfe-3a48203009bc

chore: update draggable icon

---

backend/plugin/advisor/pg/advisor_builtin_prior_backup_check.go
backend/plugin/advisor/pg/test/builtin_prior_backup_check.yaml
backend/plugin/advisor/pg/test/column_comment.yaml
backend/plugin/advisor/pg/test/table_comment.yaml
backend/plugin/parser/pg/restore.go
backend/plugin/parser/pg/test-data/test_restore.yaml
backend/runner/taskrun/data_update_executor.go

chore: set role for backup and restore

---

backend/plugin/parser/base/interface.go
backend/plugin/parser/base/span.go
backend/plugin/parser/tsql/query_span_extractor.go
backend/plugin/parser/tsql/query_span_test.go
backend/plugin/parser/tsql/test-data/query-span/standard.yaml

feat: support declare temp table

---

frontend/src/utils/useDashboardSidebar.ts

chore: update integration settings in dashboard sidebar

---

frontend/src/components/PlanCheckRun/PlanCheckRunDetail.vue

chore: fix plan checks placeholder display

---

frontend/src/components/TransferDatabaseForm/TransferDatabaseForm.vue
frontend/src/store/modules/v1/database.ts
frontend/src/views/InstanceDetail.vue

- Add advanced search for instance databases panel
- Use batch update databases API

chore: optimize databases

---

backend/plugin/db/spanner/spanner.go

circumvent https://github.com/googleapis/google-cloud-go/issues/11194

fix: spanner open db

---

backend/api/v1/database_converter.go
backend/plugin/db/pg/sync.go

feat: sync sequence owner for pg

---

backend/api/v1/project_service.go
frontend/src/components/ExpirationSelector.vue
frontend/src/components/GrantRequestPanel/GrantRequestPanel.vue
frontend/src/components/ProjectMember/AddProjectMember/AddProjectMemberForm.vue

- fix: allow never expire
- allow set project settings during creation (will used by Terraform)

fix: allow never expire

---

go.mod
go.sum

chore: upgrade plsql-parser

---

backend/api/v1/sql_service.go
backend/plugin/parser/snowflake/query_span_extractor.go
backend/plugin/parser/snowflake/query_type.go
backend/plugin/parser/snowflake/test-data/query-span/cte.yaml
backend/plugin/parser/snowflake/test-data/query-span/pivot.yaml
backend/plugin/parser/snowflake/test-data/query-span/set-operator.yaml
backend/plugin/parser/snowflake/test-data/query-span/standard.yaml
backend/plugin/parser/snowflake/test-data/query-span/subquery.yaml
go.mod
go.sum

feat: snowflake statement type

---

backend/plugin/db/snowflake/snowflake.go

feat: snowflake multiple statement

---

backend/plugin/db/pg/sync.go

chore: sync pg partition key

---

frontend/src/components/AdvancedSearch/ScopeMenu.vue
frontend/src/components/AdvancedSearch/types.ts
frontend/src/components/IssueV1/components/IssueSearch/useIssueSearchScopeOptions.ts
frontend/src/components/Rollout/RolloutDetail/Panels/TaskAdvancedSearch/TaskAdvancedSearch.vue
frontend/src/components/Rollout/RolloutDetail/Panels/TaskAdvancedSearch/index.ts
frontend/src/components/Rollout/RolloutDetail/Panels/Tasks.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/utils/v1/advanced-search/common.ts

chore: advanced search for rollout tasks

---

frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
frontend/src/components/Branch/BranchDetailView.vue
frontend/src/components/IssueV1/components/Sidebar/GhostSection/common.ts
frontend/src/components/IssueV1/components/Sidebar/PreBackupSection/TaskRollbackButton.vue
frontend/src/components/IssueV1/logic/initialize/create.ts
frontend/src/components/Plan/logic/initialize/create.ts
frontend/src/components/SlowQuery/Panel/IndexAdvisor.vue
frontend/src/components/SyncDatabaseSchema/index.vue
frontend/src/store/modules/v1/index.ts
frontend/src/store/modules/v1/storage.ts
frontend/src/views/sql-editor/EditorCommon/ExecuteHint.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue

Use IndexedDB instead of local storage to pass initial statements for creating issues.

chore: implement kv storage store to pass initial statements for creating issues

---

frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
frontend/src/components/IssueV1/components/Sidebar/GhostSection/common.ts
frontend/src/components/IssueV1/logic/initialize/create.ts
frontend/src/components/Plan/logic/initialize/create.ts
frontend/src/components/SyncDatabaseSchema/index.vue
frontend/src/store/modules/v1/storage.ts

chore: update `storage.get` types

---

backend/plugin/schema/mysql/stringify_table.go

fix: fix mysql dump index key part

---

backend/api/v1/database_converter.go
backend/plugin/db/pg/sync.go

feat: sync partition table indexes

---

frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
frontend/src/components/IssueV1/components/StatementSection/StatementSection.vue

chore: add before unload handler

---

backend/api/v1/query_result_masker.go
backend/plugin/parser/base/span.go
backend/plugin/parser/bigquery/test-data/query-span/standard.yaml
backend/plugin/parser/mysql/query_span_extractor.go
backend/plugin/parser/mysql/test-data/query-span/case_insensitive.yaml
backend/plugin/parser/mysql/test-data/query-span/standard.yaml
backend/plugin/parser/mysql/test-data/query-span/starrocks.yaml
backend/plugin/parser/pg/test-data/query_span.yaml
backend/plugin/parser/plsql/test-data/query_span.yaml
backend/plugin/parser/snowflake/test-data/query-span/cte.yaml
backend/plugin/parser/snowflake/test-data/query-span/pivot.yaml
backend/plugin/parser/snowflake/test-data/query-span/set-operator.yaml
backend/plugin/parser/snowflake/test-data/query-span/standard.yaml
backend/plugin/parser/snowflake/test-data/query-span/subquery.yaml
backend/plugin/parser/spanner/test-data/query-span/standard.yaml
backend/plugin/parser/tidb/test-data/query_span.yaml
backend/plugin/parser/tsql/test-data/query-span/case-sensitivity.yaml
backend/plugin/parser/tsql/test-data/query-span/join.yaml
backend/plugin/parser/tsql/test-data/query-span/standard.yaml

feat(mysql): fallback to full mask if the field come from expr

---

frontend/src/components/SensitiveData/ClassificationView.vue
frontend/src/components/SensitiveData/MaskingAlgorithmsView.vue

The import icon looks like download.
Before:
After:

fix: upload icon

---

backend/api/v1/database_converter.go
backend/plugin/db/pg/sync.go

feat: sync pg index inheritance

---

backend/plugin/db/redshift/redshift.go

fix: redshift query

---

frontend/src/composables/useExecuteSQL.ts
frontend/src/utils/sqlEditor.ts
frontend/src/views/sql-editor/EditorCommon/QueryContextSettingPopover.vue

chore(sql-editor): ensure default datasource selection according to policy in SQL Editor

---

backend/api/v1/database_service.go
backend/api/v1/setting_service.go
backend/legacyapi/setting.go
backend/server/init.go
frontend/src/components/GeneralSetting/AIAugmentationSetting.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/plugins/ai/components/ChatPanel.vue
frontend/src/plugins/ai/components/ProvideAIContext.vue
frontend/src/plugins/ai/logic/useDynamicSuggestions.ts
frontend/src/plugins/ai/types/context.ts
frontend/src/types/common.ts
frontend/src/types/setting.ts

add model name setting when calling openai api instead of hardcode to gpt3.5

feat: add model name setting when calling openai api instead of hardcode

---

backend/plugin/db/clickhouse/sync.go

Reference: https://clickhouse.com/docs/en/operations/system-tables/information_schema#columns

fix(clickhouse): sync column's default value

---

backend/plugin/db/pg/sync.go

feat(sync): ignore extension objects

---

frontend/src/views/sql-editor/EditorPanel/StandardPanel/SQLEditor.vue
frontend/src/views/sql-editor/EditorPanel/StandardPanel/StandardPanel.vue

feat(sql-editor): execute query in new tab

---

frontend/src/views/sql-editor/AsidePanel/HistoryPane/HistoryPane.vue

Clicking query history while the editing statement is not empty will behave like "Generate SQL".
Close BYT-6651

chore(sql-editor): clicking query history improvements

---

frontend/src/views/sql-editor/TabList/TabList.vue

chore(sql-editor): sticky Add tab button

---

frontend/src/components/SSO/IdentityProviderTable.vue
frontend/src/store/modules/idp.ts
frontend/src/views/Archive.vue

fix: archived data

---

frontend/src/components/MarkdownEditor/MarkdownEditor.vue

fix: z-index of issue list popover

---

backend/api/v1/database_converter.go
backend/plugin/db/pg/sync.go

feat: sync pg enum

---

backend/api/v1/sql_service.go
backend/plugin/schema/clickhouse/get_design_schema.go
backend/plugin/schema/clickhouse/state.go
backend/server/ultimate.go

chore(clickhouse): metadata to string

---

frontend/src/main.ts
frontend/src/polyfill.ts

chore: polyfill `String.prototype.replaceAll`

---

frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable/DataTable.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable/TableCell.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTableLite/ColumnHeader.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTableLite/DataTableLite.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTableLite/TableCell.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/common/selection-logic.ts

feat(sql-editor): select and copy data by row/column

---

frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/main.ts
frontend/src/polyfill.ts
frontend/vite.config.ts

Close BYT-6764
* use `@vite/plugin-legacy` to auto generate common polyfill scripts;
* define `WeakRef` manully;

chore: use vite legacy plugin

---

frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable/DataTable.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable/TableCell.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTableLite/ColumnHeader.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTableLite/TableCell.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/common/selection-logic.ts

Following #14762
https://github.com/user-attachments/assets/280f99eb-f8bf-407b-a855-351060a3f93c

chore(sql-editor): implement multi-selection in data table

---

backend/api/v1/database_converter.go
backend/plugin/db/pg/sync.go

feat: sync pg materialized view indexes

---

backend/plugin/parser/mysql/differ.go
backend/plugin/parser/tidb/differ.go
frontend/src/components/Changelist/ChangelistDetail/ChangeTable/Source.vue
frontend/src/components/Changelog/ChangelogDetail.vue
frontend/src/components/SyncDatabaseSchemaV1/DatabaseSchemaSelector.vue
frontend/src/components/SyncDatabaseSchemaV1/index.vue

chore: tweak changelog related views

---

backend/api/v1/auth_service.go
backend/api/v1/group_service.go

Use the raw string provided by the IdP instead of the formatted string by us in error message.

chore: update error message of email validation

---

backend/resources/postgres/sample_instance.go

Sometimes, "test" is started on port+0, other times "prod". Because the order is not consistent when ranging over maps. Changed to slice to ensure orders.

fix: sample instance port

---

frontend/src/components/SyncDatabaseSchemaV1/index.vue

fix: sync schema with changelog

---

frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
frontend/src/components/AlterSchemaPrepForm/SchemaEditorSQLCheckButton/SchemaEditorSQLCheckButton.vue
frontend/src/components/Branch/BranchDetailView.vue
frontend/src/components/Branch/BranchRolloutView/BranchRolloutView.vue
frontend/src/components/Branch/SchemaDesignEditorLite.vue
frontend/src/components/SQLCheck/SQLCheckButton.vue
frontend/src/components/SQLCheck/SQLCheckPanel.vue
frontend/src/components/SchemaEditorLite/common.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/v1/experimental-issue.ts

chore: update action buttons in sql check panel

---

frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable/DataTable.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTableLite/DataTableLite.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/common/selection-logic.ts
frontend/src/views/sql-editor/EditorCommon/ResultView/SelectionCopyTooltips.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue

chore: add tips to copy query result

---

backend/plugin/db/pg/dump.go
backend/plugin/parser/base/topo_sort.go
backend/plugin/parser/pg/differ.go
backend/plugin/parser/pg/query_span_extractor.go
backend/plugin/parser/pg/test-data/test_differ_data.yaml

feat(differ): support materialized view for PostgreSQL

---

backend/plugin/db/cosmosdb/cosmosdb.go
backend/plugin/db/driver.go
go.mod
go.sum

feat(cosmos): support cosmosdb query simply 

---

backend/api/v1/database_converter.go
backend/plugin/db/pg/sync.go

chore: sync pg dependency

---

frontend/src/composables/useExecuteSQL.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/views/sql-editor/EditorCommon/ConnectChooser.vue
frontend/src/views/sql-editor/EditorCommon/ContainerChooser.vue
frontend/src/views/sql-editor/EditorCommon/EditorAction.vue

chore: cosmos db select table

---

frontend/src/components/IssueV1/components/Sidebar/ReviewSection/Timeline.vue
frontend/src/components/IssueV1/components/Sidebar/ReviewSection/TimelineIcon.vue

chore: update trigger of approval flow node popover

---

backend/api/v1/rollout_service.go

chore: improve no stage create errmsg

---

backend/plugin/parser/pg/differ.go
backend/plugin/parser/pg/test-data/test_differ_data.yaml
backend/plugin/parser/sql/ast/create_function_stmt.go
backend/plugin/parser/sql/engine/pg/convert.go

fix(differ): fix the safe order for functions and tables

---

backend/plugin/db/mysql/sync.go

fix: unescaped quote for mysql dump

---

frontend/src/components/IssueV1/components/TaskListSection/TaskCard.vue

chore: add database link to task card

---

backend/plugin/advisor/catalog/walk_through.go
backend/plugin/advisor/catalog/walk_through_for_pg.go

fix(walk-through): ignore view for pg alter table

---

frontend/src/components/Project/ProjectReleasesPanel.vue
frontend/src/components/Project/useProjectSidebar.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

chore: remove dev guard of releases

---

backend/plugin/db/pg/dump.go
backend/tests/schema_update_test.go

fix: dump supports pg 9.6+

---

frontend/src/components/PlanCheckRun/PlanCheckRunModal.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

chore: tweak sql oversized tips

---

backend/plugin/db/cosmosdb/cosmosdb.go
go.mod
go.sum

feat(cosmos): handle cosmosdb query result

---

frontend/src/components/Database/DatabaseChangelogPanel.vue

fix: export changelogs

---

backend/plugin/db/elasticsearch/elasticsearch.go

chore: optimize es connect

---

frontend/src/components/AnomalyCenter/AnomalyCenterDashboard.vue

chore: tweak project anomalies page

---

backend/plugin/advisor/mysql/advisor_builtin_prior_backup_check.go
backend/plugin/advisor/oracle/advisor_builtin_prior_backup_check.go
backend/plugin/parser/plsql/backup.go
backend/plugin/parser/plsql/test-data/test_backup.yaml

feat: implement oracle prior backup v2

---

frontend/src/components/TransferDatabaseForm/TransferDatabaseForm.vue
frontend/src/components/TransferOutDatabaseForm/TransferOutDatabaseForm.vue
frontend/src/components/v2/Select/ProjectSelect.vue
frontend/src/utils/v1/sql.ts
frontend/src/views/DatabaseDetail/DatabaseDetail.vue

- Fix default select statement for es. Close BYT-6674
- Add the database full name (id) in the database detail page

fix: default select statement for es

---

frontend/src/components/SyncDatabaseSchemaV1/DatabaseSchemaSelector.vue
frontend/src/components/SyncDatabaseSchemaV1/RawSQLEditor.vue
frontend/src/components/SyncDatabaseSchemaV1/SelectTargetDatabasesView.vue
frontend/src/components/SyncDatabaseSchemaV1/SourceSchemaInfo.vue
frontend/src/components/SyncDatabaseSchemaV1/index.vue

chore: show source schema info

---

frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTableLite.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/TableCell.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/common/selection-logic.ts
frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue

Close BYT-6838
https://github.com/user-attachments/assets/4ebc45d1-b970-4e49-b403-035fe7ca6113

chore(sql-editor): allow select table cell to copy

---

frontend/src/components/IssueV1/components/Panel/IssueReviewActionPanel.vue
frontend/src/components/IssueV1/components/Panel/IssueStatusActionPanel.vue
frontend/src/components/IssueV1/components/Panel/TaskRolloutActionPanel.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

chore: add warning about previous unrolled stages

---

frontend/src/components/Rollout/RolloutDetail/Panels/Overview/Overview.vue

Following https://github.com/bytebase/bytebase/pull/14992

chore: fix merged stages

---

frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTableLite.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/useTableResize.ts

Use system default scrollbar instead of `NScrollbar`, close BYT-6845

chore(sql-editor): use native scrollbar

---

frontend/src/components/SlowQuery/Panel/LogFilter.vue
frontend/src/components/SlowQuery/Panel/SlowQueryPanel.vue
frontend/src/components/SlowQuery/Panel/types.ts

fix: slow query search

---

frontend/src/components/ColumnDataTable/utils.ts
frontend/src/components/SchemaEditorLite/Panels/TableColumnEditor/components/SemanticTypeCell.vue
frontend/src/components/SchemaEditorLite/context/config.ts
frontend/src/components/SchemaTemplate/FieldTemplateTable.vue
frontend/src/components/SchemaTemplate/TableTemplateForm.vue
frontend/src/store/modules/v1/databaseCatalog.ts

Close BYT-6836
PS: the semantic type/classification in the schema template not work, because the templates are using the catalog while the editor is using the database config.

fix: column catalog

---

frontend/src/views/EnvironmentDashboard.vue

chore: move environment related actions into NTabs

---

frontend/src/components/ColumnDataTable/index.vue
frontend/src/components/DBExtensionDataTable.vue
frontend/src/components/ExternalTableDataTable.vue
frontend/src/components/FunctionDataTable.vue
frontend/src/components/PackageDataTable.vue
frontend/src/components/PartitionTablesDataTable.vue
frontend/src/components/ProjectWebhookPanel.vue
frontend/src/components/Role/Setting/components/RoleDataTable/index.vue
frontend/src/components/SequenceDataTable.vue
frontend/src/components/TableDataTable.vue
frontend/src/components/TriggerDataTable.vue
frontend/src/components/ViewDataTable.vue
frontend/src/views/SettingWorkspaceSSO.vue
frontend/src/views/SettingWorkspaceVCS.vue
frontend/src/views/project/ProjectVersionControlPanel.vue

fix: missing row key

---

backend/plugin/parser/bigquery/query_span_extractor.go
backend/plugin/parser/spanner/query_span_extractor.go
go.mod
go.sum

chore: bump google-sql-parser version

---

backend/plugin/db/pg/sync.go

chore: support citus foreign keys

---

backend/plugin/parser/pg/differ.go
backend/plugin/parser/pg/test-data/test_differ_constraint.yaml
backend/plugin/parser/pg/test-data/test_differ_data.yaml
backend/plugin/parser/pg/test-data/test_differ_merge.yaml
backend/plugin/parser/pg/test-data/test_differ_schema.yaml
backend/plugin/parser/pg/test-data/test_differ_sequence.yaml
backend/tests/sync_schema_test.go

fix(differ): print header if needed

---

frontend/src/utils/v1/database.ts

Should sort by the environment's order in ascending order

fix: update sort order in database list

---

frontend/src/components/User/Settings/CreateGroupDrawer.vue
frontend/src/store/modules/v1/group.ts

fix: do not use upsert for group

---

frontend/src/components/IssueV1/components/BannerSection.vue
frontend/src/components/IssueV1/logic/action/task.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

Use word "rollout" one word instead of "roll out" or "roll-out"

chore: tweak wording

---

frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/TableCell.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/common/selection-logic.ts
frontend/src/views/sql-editor/EditorCommon/ResultView/SelectionCopyTooltips.vue

Close BYT-6874
* Do not unselect after copy succeeds.
* Detect `ctrl`/`cmd` + click on a cell to select the row.
* Detect `Esc` to unselect.

chore(sql-editor): update data table select actions

---

frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable.vue

chore: max width of table cell

---

frontend/src/components/TableDetailDrawer.vue

fix: classification badge style

---

backend/plugin/db/tidb/query.go
backend/plugin/db/tidb/query_test.go

chore: add `RestoreStringWithoutDefaultCharset` to tidb restore

---

frontend/src/components/IssueV1/components/Sidebar/Sidebar.vue
frontend/src/components/IssueV1/components/Sidebar/TaskCheckSummarySection/AffectedRowsView.vue
frontend/src/components/IssueV1/components/Sidebar/TaskCheckSummarySection/FailedTasksView.vue
frontend/src/components/IssueV1/components/Sidebar/TaskCheckSummarySection/TaskCheckSummarySection.vue
frontend/src/components/IssueV1/components/Sidebar/TaskCheckSummarySection/index.ts
frontend/src/components/PlanCheckRun/PlanCheckRunDetail.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

feat: task summary reports view in issue sidebar

---

frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/DetailCell/AffectedRowsCell.vue
frontend/src/components/Project/ProjectReleasesPanel.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

* release wording
* Affected row -> Estimated affected row

chore: wording improvement

---

frontend/src/DummyRootView.ts
frontend/src/components/InstanceForm/DataSourceSection/DataSourceForm.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

chore: support vault app role

---

frontend/src/components/Changelog/ChangelogDataTable.vue
frontend/src/components/IssueV1/components/Sidebar/TaskCheckSummarySection/TaskCheckSummarySection.vue

chore: add baseline to changelog type

---

frontend/src/components/BannersWrapper.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/subscription/en-US.json
frontend/src/locales/subscription/es-ES.json
frontend/src/locales/subscription/ja-JP.json
frontend/src/locales/subscription/zh-CN.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/v1/subscription.ts
frontend/src/views/BannerSubscription.vue

chore: license expires banner

---

frontend/src/components/GeneralSetting/RestrictIssueCreationConfigure.vue
frontend/src/components/GeneralSetting/SecuritySetting.vue
frontend/src/components/SensitiveData/MaskingExceptionUserTable.vue
frontend/src/store/modules/v1/policy.ts
frontend/src/utils/issue/cel.ts
frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue

- Add loading for policy
- Batch request to parse the expression

chore: perf for masking exception policy

---

go.mod
go.sum

chore: bump snowflake parser

---

backend/plugin/db/mssql/sync.go

feat(mssql): sync mssql foreign key

---

backend/common/util.go
backend/component/sheet/sheet.go
backend/plugin/db/redshift/stats.go
backend/plugin/parser/pg/resource_change.go
backend/runner/plancheck/statement_report_executor.go

feat: support statement report for redshift

---

frontend/src/components/AuditLog/AuditLogDataTable.vue
frontend/src/components/Changelog/ChangelogDataTable.vue
frontend/src/components/Project/ProjectIssuesPanel.vue
frontend/src/components/Project/ProjectReleasesPanel.vue
frontend/src/components/Project/ProjectRolloutsPanel.vue
frontend/src/components/Revision/RevisionDataTable.vue
frontend/src/components/v2/Model/PagedTable.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/views/ExportCenter/index.vue
frontend/src/views/MyIssues.vue
frontend/src/views/ReviewCenter/index.vue
frontend/src/views/SettingWorkspaceAuditLog.vue
frontend/src/views/project/ProjectAuditLogDashboard.vue

chore: optimize pagination UX

---

backend/plugin/parser/base/span.go
backend/plugin/parser/bigquery/test-data/query-span/standard.yaml
backend/plugin/parser/mysql/test-data/query-span/case_insensitive.yaml
backend/plugin/parser/mysql/test-data/query-span/query_type.yaml
backend/plugin/parser/mysql/test-data/query-span/standard.yaml
backend/plugin/parser/mysql/test-data/query-span/starrocks.yaml
backend/plugin/parser/pg/test-data/query_span.yaml
backend/plugin/parser/pg/test-data/query_type.yaml
backend/plugin/parser/plsql/test-data/query_span.yaml
backend/plugin/parser/snowflake/test-data/query-span/cte.yaml
backend/plugin/parser/snowflake/test-data/query-span/pivot.yaml
backend/plugin/parser/snowflake/test-data/query-span/set-operator.yaml
backend/plugin/parser/snowflake/test-data/query-span/standard.yaml
backend/plugin/parser/snowflake/test-data/query-span/subquery.yaml
backend/plugin/parser/spanner/test-data/query-span/standard.yaml
backend/plugin/parser/tidb/test-data/query_span.yaml
backend/plugin/parser/tidb/test-data/query_type.yaml
backend/plugin/parser/tsql/query_span_extractor.go
backend/plugin/parser/tsql/query_span_predicate.go
backend/plugin/parser/tsql/query_span_test.go
backend/plugin/parser/tsql/test-data/query-span/case-sensitivity.yaml
backend/plugin/parser/tsql/test-data/query-span/predicate.yaml
backend/plugin/parser/tsql/test-data/query-span/query_type.yaml
backend/plugin/parser/tsql/test-data/query-span/standard.yaml

feat: extract predicate columns for MSSQL

---

backend/bin/server/cmd/profile_dev.go

Switch from bbdev to bb for dev build embedded pg user/database.

chore: dev user

---

frontend/src/components/AdvancedSearch/useCommonSearchScopeOptions.ts
frontend/src/components/AuditLog/AuditLogSearch/AuditLogSearch.vue
frontend/src/components/IssueV1/components/IssueTableV1.vue
frontend/src/components/KBar/useProjectActions.ts
frontend/src/components/Plan/components/PlanDataTable/PlanDataTable.vue
frontend/src/components/Project/ProjectCreatePanel.vue
frontend/src/components/Project/Settings/ProjectGeneralSettingPanel.vue
frontend/src/components/v2/Model/ProjectV1Table.vue
frontend/src/components/v2/Select/ProjectSelect.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json
frontend/src/utils/v1/database.ts
frontend/src/utils/v1/project.ts
frontend/src/views/ExportCenter/DataExportIssueDataTable/DataExportIssueDataTable.vue
frontend/src/views/ReviewCenter/SQLReviewIssueDataTable/SQLReviewIssueDataTable.vue
frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/DatabaseNode.vue

chore: retire project's key in frontend

---

frontend/src/components/IssueV1/components/IssueTableV1.vue

chore: add project column to issue table

---

backend/api/v1/predicate_columns_check.go
backend/api/v1/sql_service.go

feat: check sensitive predicate columns for MSSQL

---

backend/plugin/advisor/mssql/advisor_builtin_prior_backup_check.go
backend/plugin/parser/tsql/backup.go
backend/plugin/parser/tsql/test-data/test_backup.yaml

feat: implement backup dml for mssql v2

---

backend/plugin/parser/tsql/statement_type.go
backend/plugin/parser/tsql/statement_type_test.go
backend/plugin/parser/tsql/test-data/test_statement_type.yaml
backend/runner/plancheck/statement_report_executor.go

feat: statement types for mssql

---

backend/plugin/advisor/pg/advisor_builtin_prior_backup_check.go
backend/plugin/advisor/pg/test/builtin_prior_backup_check.yaml
backend/plugin/parser/pg/backup.go
backend/plugin/parser/pg/test-data/test_backup.yaml

feat: implement pg backup v2

---

frontend/src/components/DataExportButton.vue

chore: format JSON in data export

---

backend/plugin/db/mssql/mssql.go

fix: mssql close

---

frontend/src/components/v2/Model/ProjectV1Table.vue

chore: add width to project id cell

---

backend/migrator/migration/LATEST.sql

consistent with pg_dump format.

chore: lower-case column type

---

backend/api/v1/audit.go

fix: response could be nil

---

frontend/src/store/modules/user.ts

fix: add all user in the cache

---

backend/plugin/db/pg/dump.go

chore(dump): add if not exists for schema

---

frontend/src/components/AlterSchemaPrepForm/SchemaEditorSQLCheckButton/SchemaEditorSQLCheckButton.vue
frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckSection.vue
frontend/src/components/Plan/components/SQLCheckSection/SQLCheckSection.vue
frontend/src/components/SQLCheck/SQLCheckButton.vue

chore: use check release in sql check button

---

backend/api/v1/predicate_columns_check.go
backend/api/v1/sql_service.go

fix: use user for sensitive predicate

---

backend/api/v1/risk_service.go
backend/store/risk.go
frontend/src/components/CustomApproval/Settings/components/RiskCenter/RiskDialog/RiskForm.vue
frontend/src/components/CustomApproval/Settings/components/RiskCenter/RiskDialog/RiskSourceSelect.vue
frontend/src/components/CustomApproval/Settings/components/common/utils.ts
frontend/src/store/modules/risk.ts

Allow changing the risk source if the condition factors are compatible

chore: allow change risk source

---

frontend/src/components/SQLCheck/SQLCheckButton.vue
frontend/src/components/SQLCheck/SQLCheckPanel.vue
frontend/src/utils/util.ts

chore: show risk level and affected rows of release check result

---

backend/plugin/db/pg/sync.go

chore: ignore extension schema

---

frontend/src/components/IssueV1/components/Sidebar/GhostSection/GhostFlagsPanel.vue
frontend/src/components/IssueV1/components/TaskListSection/TaskCard.vue
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunComment.vue
frontend/src/components/IssueV1/logic/action/task.ts
frontend/src/components/IssueV1/logic/base.ts
frontend/src/components/IssueV1/logic/rollout.ts
frontend/src/components/IssueV1/logic/utils.ts
frontend/src/components/Rollout/RolloutDetail/utils.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json
frontend/src/types/v1/issue/rollout.ts
frontend/src/utils/v1/issue/issue.ts

chore(frontend): remove old task type

---

frontend/src/components/Database/DatabaseChangelogPanel.vue

fix: changelog paged table

---

backend/plugin/db/driver.go
backend/plugin/db/pg/sync.go

fix: fix sync sequence owner

---

backend/api/v1/release_service_check.go
backend/common/cel.go
backend/runner/approval/runner.go
backend/store/sheet.go
frontend/src/components/CustomApproval/Settings/components/common/utils.ts
frontend/src/plugins/cel/types/factor.ts
frontend/src/plugins/cel/types/operator.ts
frontend/src/views/EnvironmentDashboard.vue

chore: support sql statement check in risk

---

backend/plugin/advisor/mysql/advisor_online_migration.go
frontend/src/components/IssueV1/components/Sidebar/GhostSection/GhostSwitch.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

chore: check database exists in ghost

---

backend/component/ghost/config.go
frontend/src/components/IssueV1/components/Sidebar/GhostSection/FlagsForm/constants.ts

feat: add ghost flags

---

backend/api/v1/release_service_check.go

chore: add syntax advices to CheckRelease

---

frontend/src/views/SettingWorkspaceSubscription.vue

chore: update subscription page

---

frontend/src/components/CustomApproval/Settings/components/common/utils.ts
frontend/src/components/ExprEditor/components/MultiSelect.vue
frontend/src/components/SensitiveData/GlobalMaskingRulesView.vue
frontend/src/components/SensitiveData/components/utils.ts

Unify the UX with the ProjectSelector/InstanceSelector/EnvironmentSelector

chore: optimize resource selector in expr editor

---

frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckBadge.vue
frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckSection.vue
frontend/src/components/IssueV1/components/Sidebar/GhostSection/GhostSection.vue
frontend/src/components/SQLCheck/SQLCheckButton.vue
frontend/src/components/SQLCheck/SQLCheckPanel.vue

chore: show affected rows in sql check bar

---

frontend/src/components/IssueV1/components/TaskRunSection/TaskRunComment.vue

fix: ghost view change

---

frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckBadge.vue
frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckSection.vue
frontend/src/components/IssueV1/components/TaskStatusIcon.vue
frontend/src/components/PlanCheckRun/PlanCheckRunBadge.vue
frontend/src/components/PlanCheckRun/PlanCheckRunBadgeBar.vue
frontend/src/components/PlanCheckRun/PlanCheckRunButton.vue
frontend/src/components/WorkspaceInstanceLicenseStats.vue
frontend/src/views/DashboardHeader.vue
frontend/src/views/SettingWorkspaceSubscription.vue

Following https://github.com/bytebase/bytebase/pull/15310, close BYT-6620

chore: unify check's status icons

---

backend/api/v1/plan_service.go
backend/store/task.go

feat: allow to update task type

---

backend/api/lsp/custom.go
backend/api/lsp/fs_handler.go
backend/api/lsp/handler.go
backend/api/lsp/utils.go
backend/api/lsp/utils_test.go

feat(postgres): simple splitter for $/textDocument/statementRanges in lsp

---

frontend/src/components/IssueV1/components/Sidebar/GhostSection/GhostSwitch.vue

chore: allow to toggle ghost after task created

---

backend/plugin/db/cockroachdb/cockroachdb.go

Part of BYT-6953
https://www.cockroachlabs.com/docs/v25.1/cluster-settings#setting-version

fix: cockroach version

---

backend/api/v1/database_service.go
backend/plugin/parser/cockroachdb/differ.go
backend/plugin/parser/pg/differ.go
frontend/src/components/SyncDatabaseSchemaV1/types.ts

chore: schema diff for cockroach

---

README.md
frontend/src/components/IssueV1/components/StatementSection/SDLView/SDLView.vue
frontend/src/components/ProfileDropdown.vue
frontend/src/components/Project/ProjectReleasesPanel.vue
frontend/src/components/ReleaseRemindModal.vue
frontend/src/components/SensitiveData/GlobalMaskingRulesView.vue
frontend/src/views/BannerDemo.vue
go.mod
go.sum
scripts/check_link_test.go

Check if a link exists in sitemap.xml according to @boojack 's suggestion.

fix: test link test

---

frontend/src/components/EnvironmentForm/Buttons.vue

Following https://github.com/bytebase/bytebase/pull/15338

chore: remove unused comment

---

backend/plugin/advisor/pg/advisor_column_default_disallow_volatile.go
backend/plugin/advisor/pg/test/column_default_disallow_volatile.yaml
backend/plugin/parser/sql/ast/bool_def.go
backend/plugin/parser/sql/engine/pg/convert.go
backend/plugin/parser/sql/engine/pg/convert_test.go

fix(pg): volatile checks for bool type

---

backend/plugin/advisor/pg/advisor_column_default_disallow_volatile.go
backend/plugin/advisor/pg/test/column_default_disallow_volatile.yaml

chore: do not check new tables for column default value

---

backend/api/v1/issue_service_convert.go
backend/api/v1/rollout_service.go
backend/component/iam/acl.yaml
backend/runner/taskrun/schedulerv2.go
frontend/src/types/proto/v1/issue_service.ts
proto/gen/grpc-doc/openapi.yaml
proto/gen/grpc-doc/v1/README.md
proto/gen/grpc-doc/v1/index.html
proto/generated-go/v1/issue_service.pb.go
proto/v1/issue_service.proto

chore: update rollout policy

---

frontend/src/locales/sql-review/en-US.json
frontend/src/locales/sql-review/es-ES.json
frontend/src/locales/sql-review/ja-JP.json
frontend/src/locales/sql-review/vi-VN.json
frontend/src/locales/sql-review/zh-CN.json

chore: fix description of volatile rule

---

backend/tests/testcontainer.go

chore: testcontainers start timeout

---

frontend/src/components/MonacoEditor/MonacoEditor.vue
frontend/src/components/MonacoEditor/themes/bb-dark.ts
frontend/src/components/MonacoEditor/themes/bb.ts
frontend/src/views/sql-editor/EditorPanel/StandardPanel/SQLEditor.vue

chore: use inline decorations collection for range select by cursor

---

frontend/src/components/IssueV1/components/Sidebar/ReviewSection/Timeline.vue

fix: candidates render

---

backend/api/v1/database_service.go
backend/api/v1/instance_service.go
backend/api/v1/project_service.go
backend/store/database.go
frontend/src/components/DatabaseEditEnvironmentDrawer.vue
frontend/src/components/TransferDatabaseForm/TransferDatabaseForm.vue
frontend/src/components/TransferOutDatabaseForm/TransferOutDatabaseForm.vue
frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/v1/database.ts
frontend/src/types/appProfile.ts

feat: batch update databases environment

---

frontend/src/store/modules/v1/database.ts
frontend/src/store/modules/v1/project.ts
frontend/src/store/modules/v1/projectIamPolicy.ts

fix: duplicate request

---

frontend/src/views/DatabaseDetail/DatabaseDetail.vue
frontend/src/views/InstanceDetail.vue
frontend/src/views/ProfileDashboard.vue

chore: fix unknown database title

---

backend/tests/tenant_test.go

chore: test reconcile plan

---

frontend/src/views/DatabaseDetail/DatabaseDetail.vue

fix: unknown database

---

backend/api/v1/query_result_masker.go
backend/api/v1/sql_service.go
backend/plugin/parser/base/span.go
backend/plugin/parser/errors/resources.go
backend/plugin/parser/pg/query_span_extractor.go

chore: add func not supported error

---

go.mod
go.sum

fix(mssql): freetext

---

frontend/src/components/AuditLog/AuditLogSearch/AuditLogSearch.vue
frontend/src/components/IssueV1/components/IssueSearch/IssueSearch.vue

fix: infinite requests of list users

---

backend/store/instance.go
backend/store/model/database.go

feat: case sensitivity for ob

---

frontend/src/components/GeneralSetting/AIAugmentationSetting.vue

fix: update ai setting

---

frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/TaskName.vue
frontend/src/components/IssueV1/components/Sidebar/TaskCheckSummarySection/AffectedRowsView.vue
frontend/src/components/IssueV1/components/Sidebar/TaskCheckSummarySection/FailedTasksView.vue
frontend/src/components/IssueV1/components/TaskStatusIcon.vue

chore: normalize task target

---

backend/store/task.go

fix: update task

---

backend/plugin/db/pg/sync.go

so there is no need to set it back.

chore: make set search path local to the tx

---

frontend/src/components/AnomalyCenter/AnomalyCenterDashboard.vue

Fix
https://github.com/user-attachments/assets/60de0415-e6b5-4682-ab37-b5703f54d321

chore: fix flashing content in database anomaly page

---

backend/api/v1/catalog_masking.go
backend/api/v1/catalog_masking_test.go
backend/api/v1/sql_service.go
backend/plugin/parser/base/json_path.go
backend/plugin/parser/base/json_path_test.go
backend/plugin/parser/base/span.go
backend/plugin/parser/cosmosdb/query_span.go
backend/plugin/parser/cosmosdb/query_span_test.go
backend/plugin/parser/cosmosdb/split.go
backend/plugin/parser/mysql/query_span_extractor.go
backend/plugin/parser/tsql/query_span_extractor.go
go.mod
go.sum

feat: disallow to access sensitive field in where clause for cosmos db

---

frontend/src/components/CustomApproval/Settings/components/common/utils.ts

chore: add schema name to risk factors

---

frontend/src/plugins/cel/types/factor.ts
frontend/src/plugins/cel/types/operator.ts

fix: operators of schema name

---

backend/api/v1/rollout_service.go
backend/runner/taskrun/schedulerv2.go

fix: create task run

---

frontend/src/components/AdvancedSearch/useCommonSearchScopeOptions.ts
frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
frontend/src/components/DataExportPrepForm/DataExportPrepForm.vue
frontend/src/components/DatabaseAndGroupSelector/DatabaseAndGroupSelector.vue
frontend/src/components/IssueV1/components/IssueSearch/useIssueSearchScopeOptions.ts
frontend/src/components/ProjectDatabasesPanel.vue
frontend/src/components/SyncDatabaseSchemaV1/TargetDatabasesSelectPanel.vue
frontend/src/store/modules/v1/database.ts
frontend/src/utils/v1/advanced-search/common.ts
frontend/src/views/DatabaseDashboard.vue
frontend/src/views/InstanceDashboard.vue
frontend/src/views/InstanceDetail.vue
frontend/src/views/ReviewCenter/index.vue
frontend/src/views/sql-editor/Setting/Instance/Instance.vue

The `database` filter is only used by issue/export search

chore: simplify the advanced search

---

backend/plugin/idp/ldap/ldap.go

ldap.DialTLS/ldap.Dial are deprecated.

chore: migrate to ldap.DialURL()

---

frontend/src/components/v2/Select/ProjectSelect.vue

chore: fetch orphan project

---

frontend/src/components/CustomApproval/Settings/components/CustomApproval/FlowsPanel/FlowTable.vue

chore: remove creator column in flow table

---

backend/plugin/advisor/sql_review.go
frontend/src/components/PlanCheckRun/PlanCheckRunDetail.vue

chore: remove view definition from sql review result

---

backend/api/v1/rollout_service.go
backend/component/webhook/event.go
backend/component/webhook/manager.go
backend/plugin/webhook/webhook.go
backend/runner/taskrun/schedulerv2.go
backend/store/task.go

feat: webhook msg without issues

---

frontend/src/components/v2/Select/DatabaseSelect.vue

fix: parent for list database

---

frontend/src/components/GeneralSetting/AIAugmentationSetting.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json
frontend/src/plugins/ai/components/ChatPanel.vue
frontend/src/plugins/ai/logic/useDynamicSuggestions.ts

chore: support switch ai provider

---

frontend/src/components/User/Settings/CreateUserDrawer.vue

chore: remove fixed email suffix for service accounts

---

frontend/src/components/User/Settings/CreateUserDrawer.vue

chore: update email domain for service accounts

---

backend/api/v1/release_service_check.go

fix: engine checks in check release

---

backend/api/auth/auth.go
backend/api/v1/auth_service_test.go
backend/api/v1/user_service.go
frontend/src/components/EnvironmentForm/AccessControlConfigure.vue
frontend/src/components/EnvironmentForm/Form.vue
frontend/src/components/EnvironmentForm/RolloutPolicyConfig.vue
frontend/src/components/GeneralSetting/RestrictIssueCreationConfigure.vue
frontend/src/components/GeneralSetting/SecuritySetting.vue
frontend/src/components/Member/EditMemberRoleDrawer.vue
frontend/src/components/Member/MembersBindingSelect.vue
frontend/src/components/Project/ProjectSwitch/ProjectSwitchContent.vue
frontend/src/components/Project/Settings/ProjectGeneralSettingPanel.vue
frontend/src/components/SQLReview/components/SQLReviewForResource.vue
frontend/src/components/SensitiveData/GrantAccessForm.vue
frontend/src/components/User/Settings/CreateGroupDrawer.vue
frontend/src/components/User/Settings/CreateUserDrawer.vue
frontend/src/components/User/Settings/UserDataTable/cells/UserOperationsCell.vue
frontend/src/composables/useExecuteSQL.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json
frontend/src/views/SettingWorkspaceUsers.vue

- Unify some UI, also remove unused code
- Fix check workspace admin count when deleting the user
- Fix show service account key after creation

chore: ui otimize and bug fix

---

backend/demo/demo.go
backend/migrator/migrator.go

Use principal table to check if data is initialized.

chore: principal table

---

backend/api/v1/worksheet_service.go
frontend/src/store/modules/v1/database.ts
frontend/src/store/modules/v1/worksheet.ts
frontend/src/views/sql-editor/EditorCommon/SheetConnectionIcon.vue

chore: show worksheet even if the database not found

---

backend/plugin/db/oracle/sync.go

feat: sync oracle triggers

---

frontend/src/components/TableSchemaViewer.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/actions.tsx
frontend/src/views/sql-editor/context.ts

feat: show view schema in SQL editor

---

frontend/src/components/misc/Watermark.vue

feat: version watermark

---

frontend/src/components/IssueV1/components/Sidebar/GhostSection/GhostSwitch.vue
frontend/src/components/IssueV1/components/StageSection/StageCard.vue
frontend/src/components/IssueV1/components/TaskListSection/TaskCard.vue
frontend/src/components/IssueV1/logic/context.ts
frontend/src/utils/v1/instance.ts

chore: update display name for unknown instance

---

frontend/src/components/IssueV1/DataExportIssueDetailPage.vue
frontend/src/components/IssueV1/IssueDetailPage.vue
frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue
frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckBadge.vue
frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckButton.vue
frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckSection.vue
frontend/src/components/IssueV1/components/SQLCheckSection/common.ts
frontend/src/components/IssueV1/components/SQLCheckSection/context.ts
frontend/src/components/IssueV1/components/StageSection/StageCard.vue
frontend/src/components/IssueV1/components/StatementSection/StatementSection.vue
frontend/src/components/IssueV1/components/TaskStatusIcon.vue
frontend/src/components/SQLCheck/SQLCheckButton.vue
frontend/src/components/SQLCheck/common.ts

chore: run sql check for all tasks before issue created

---

frontend/src/types/v1/database.ts

chore: remove empty database

---

backend/plugin/idp/ldap/ldap.go

Close BYT-7185
sort of revert logic/fix #15573

fix: ldap SecurityProtocolNone

---

backend/api/v1/role_service.go
backend/store/principal.go
backend/store/role.go
frontend/src/components/Role/Setting/components/RoleDataTable/cells/RoleOperationsCell.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

chore: show related resources when delete role failed

---

frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/components/MonacoEditor/lsp-client.ts

chore: bump monaco-languageclient

---

frontend/src/components/MonacoEditor/lsp-client.ts

Close https://github.com/bytebase/bytebase/pull/15717#discussion_r2024507390

chore: apply copilot suggestion

---

frontend/package.json
frontend/pnpm-lock.yaml

chore: bump vscode-ws-jsonrpc

---

action/file.go
backend/api/v1/release_service.go
backend/api/v1/release_service_check.go
frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue
frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckButton.vue
frontend/src/components/Release/ReleaseDataTable.vue
frontend/src/components/Release/ReleaseDetail/NavBar/PreviewPlanDetail.vue
frontend/src/components/Release/ReleaseDetail/ReleaseFileTable/ReleaseFileDetailPanel.vue
frontend/src/components/Release/ReleaseDetail/ReleaseFileTable/ReleaseFileTable.vue
frontend/src/components/SQLCheck/SQLCheckButton.vue
frontend/src/types/proto/v1/release_service.ts
frontend/src/utils/index.ts
frontend/src/utils/release.ts
proto/gen/grpc-doc/openapi.yaml
proto/gen/grpc-doc/v1/README.md
proto/gen/grpc-doc/v1/index.html
proto/generated-go/v1/release_service.pb.go
proto/v1/release_service.proto

chore: change statement type of release file to bytes

---

backend/plugin/db/cassandra/cassandra.go
backend/plugin/parser/standard/query.go
frontend/src/utils/v1/sql.ts
go.mod

feat: cassandra query

---

frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/StageName.vue
frontend/src/components/IssueV1/components/Panel/TaskRolloutActionPanel.vue
frontend/src/components/IssueV1/components/Sidebar/GhostSection/GhostFlagsPanel.vue
frontend/src/components/IssueV1/components/StageSection/StageCard.vue
frontend/src/components/Rollout/RolloutDetail/Panels/Overview/StageCard.vue

chore: show environment's title for stages

---

frontend/src/components/GrantRequestPanel/DatabaseResourceForm/DatabaseResourceSelector.vue
frontend/src/store/modules/sqlEditor/editor.ts
frontend/src/store/modules/sqlEditor/tree.ts
frontend/src/views/sql-editor/AsidePanel/AsidePanel.vue
frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/ConnectionPane.vue

chore: support load more in database tree

---

backend/api/v1/auth_service.go
backend/api/v1/idp_service.go
backend/migrator/migration/3.5/0017##oidc_scopes.sql
backend/migrator/migrator_test.go
backend/plugin/idp/oidc/oidc.go
backend/plugin/idp/oidc/oidc_test.go
frontend/src/components/SSO/IdentityProviderCreateForm.vue
frontend/src/types/proto/store/idp.ts
frontend/src/types/proto/v1/idp_service.ts
proto/gen/grpc-doc/openapi.yaml
proto/gen/grpc-doc/store/README.md
proto/gen/grpc-doc/store/index.html
proto/gen/grpc-doc/v1/README.md
proto/gen/grpc-doc/v1/index.html
proto/generated-go/store/idp.pb.go
proto/generated-go/v1/idp_service.pb.go
proto/store/idp.proto
proto/v1/idp_service.proto

chore: expose scopes config of oidc

---

frontend/src/components/DatabaseGroup/MatchedDatabaseView.vue
frontend/src/components/DatabaseGroup/ProjectDatabaseGroupPanel.vue
frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue
frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
frontend/src/components/IssueV1/components/TaskListSection/TaskListSection.vue
frontend/src/components/IssueV1/logic/initialize/create.ts
frontend/src/components/IssueV1/logic/plan.ts
frontend/src/components/Plan/components/HeaderSection/Actions/create/CreateButton.vue
frontend/src/components/Plan/components/StatementSection/EditorView/EditorView.vue
frontend/src/components/Plan/logic/initialize/create.ts
frontend/src/components/Plan/logic/plan.ts
frontend/src/store/modules/v1/experimental-issue.ts
frontend/src/views/project/ProjectDatabaseGroupDetail.vue

chore: fetch issue related databases per page

---

backend/plugin/db/elasticsearch/elasticsearch.go
backend/plugin/parser/elasticsearch/diagnose.go
backend/plugin/parser/elasticsearch/parser.go
backend/plugin/parser/elasticsearch/parser_test.go
backend/plugin/parser/elasticsearch/test-data/parse-elasticsearch-rest.yaml
backend/server/ultimate.go

feat(diagnose): diagnose for es

---

frontend/src/components/IssueV1/components/SQLCheckSection/AdviceStatusIcon.vue
frontend/src/components/IssueV1/components/SQLCheckSection/context.ts
frontend/src/components/IssueV1/components/StageSection/StageSummary.vue
frontend/src/components/IssueV1/components/TaskListSection/TaskCard.vue
frontend/src/components/IssueV1/components/TaskListSection/TaskFilter.vue
frontend/src/components/IssueV1/components/TaskListSection/TaskListSection.vue
frontend/src/components/IssueV1/components/TaskListSection/filter.ts
frontend/src/components/IssueV1/components/TaskStatusIconV1.vue
frontend/src/components/IssueV1/logic/utils.ts
frontend/src/types/v1/instance.ts

feat: task filters

---

backend/api/lsp/fs_handler.go
backend/plugin/parser/base/interface.go
backend/plugin/parser/elasticsearch/parser.go
backend/plugin/parser/elasticsearch/statement_ranges.go
backend/plugin/parser/elasticsearch/statement_ranges_test.go
backend/plugin/parser/elasticsearch/test-data/parse-elasticsearch-rest.yaml
backend/plugin/parser/elasticsearch/test-data/statement-ranges.yaml

feat(elastic): elastic search statement range

---

backend/api/v1/audit.go
backend/api/v1/sql_service.go
backend/tests/sensitive_data_test.go
backend/tests/sql_review_test.go
frontend/src/composables/useExecuteSQL.ts
frontend/src/store/modules/sqlEditor/webTerminal.ts
frontend/src/store/modules/v1/sql.ts
frontend/src/types/proto/v1/sql_service.ts
frontend/src/utils/iam/permission-utils.ts
frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
proto/gen/grpc-doc/openapi.yaml
proto/gen/grpc-doc/v1/README.md
proto/gen/grpc-doc/v1/index.html
proto/generated-go/v1/sql_service.pb.go
proto/v1/sql_service.proto

1. Should check "allow export" with real response count (not the limit count in the request)
2. Should set the "allow export" in each result set
Close BYT-7211

chore: allow export should set in each result set

---

frontend/src/components/User/Settings/CreateGroupDrawer.vue

chore: allow no member and no owner in group

---

frontend/src/views/sql-editor/AsidePanel/SchemaPane/SchemaPane.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/common.ts

chore: remove depenedent column from schema pane

---

action/gitlab.go
action/main.go

https://docs.gitlab.com/ci/testing/code_quality/
https://docs.gitlab.com/ci/testing/code_quality/#code-quality-report-format
```
artifacts:
reports:
junit: bytebase_junit.xml
codequality: bytebase_codequality.json
```

chore: code quality json

---

frontend/src/components/Changelist/ChangelistDashboard/ChangelistDashboard.vue
frontend/src/components/Changelist/ChangelistDashboard/CreateChangelistPanel.vue
frontend/src/components/Changelist/ChangelistDashboard/NavBar.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/v1/issue.ts
frontend/src/store/modules/v1/plan.ts
frontend/src/types/release.ts
frontend/src/types/v1/group.ts
frontend/src/types/v1/projectWebhook.ts
frontend/src/utils/v1/changelog.ts

refactor: remove part of empty id

---

frontend/src/store/modules/v1/environment.ts
frontend/src/views/EnvironmentDetail.vue

feat: update environment_store to use environmentSetting

---

frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/sqlEditor/tab.ts
frontend/src/store/modules/sqlEditor/tree.ts
frontend/src/types/sqlEditor/tree.ts
frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/ConnectionPane.vue
frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/GroupingBar/FactorTags.vue
frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/DatabaseNode.vue
frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/Label.vue

- Not calculate the expanded keys, default expand all nodes.
- Fix: selected keys not work

chore: default expand all

---

frontend/src/views/ProjectDashboard.vue

chore: tweak data table style in project dashboard

---

backend/api/v1/acl.go
frontend/src/types/proto/v1/database_service.ts
proto/gen/grpc-doc/openapi.yaml
proto/gen/grpc-doc/v1/README.md
proto/gen/grpc-doc/v1/index.html
proto/generated-go/v1/database_service.pb.go
proto/generated-go/v1/database_service.pb.gw.go
proto/generated-go/v1/database_service_grpc.pb.go
proto/v1/database_service.proto

chore(proto): batch get databases

---

frontend/src/components/SensitiveData/components/SemanticTypesTable.vue

fix: zero index

---

action/azure_devops.go
action/main.go

chore(action): azure devops

---

action/azure_devops.go

chore(action): code position for azure devops

---

frontend/public/help/en/help.instance.md
frontend/public/help/ja/help.instance.md
frontend/public/help/zh/help.instance.md
frontend/src/components/InstanceForm/DataSourceSection/CreateDataSourceExample.vue

Following https://github.com/bytebase/bytebase.com/commit/e1ccdeb9714c0438f849885e7e0c3ca7d400d6bb

chore: update docs link

---

backend/migrator/migration/3.6/0002##remove_environment_perms.sql
backend/migrator/migrator_test.go

chore: remove bb.environments.* perms from role

---

frontend/src/store/modules/v1/environment.ts

fix: instance environment table

---

action/bitbucket.go
action/gitlab.go

chore: bitbucket risk report

---

frontend/src/components/Member/MemberDataTable/cells/UserRolesCell.vue
frontend/src/components/Quickstart.vue
frontend/src/components/User/Settings/UserDataTable/cells/UserRolesCell.vue
frontend/src/layouts/BodyLayout.vue
frontend/src/layouts/IssueLayout.vue
frontend/src/views/sql-editor/SQLEditorHomePage.vue

- Uniq user roles in the IAM table
- Update quick start

chore: minor updates

---

backend/api/v1/sql_service.go

fix: nil optional access check

---

frontend/src/App.vue
frontend/src/AuthContext.vue
frontend/src/components/PasswordSigninForm.vue
frontend/src/components/v2/Model/PagedTable.vue
frontend/src/grpcweb/middlewares/authInterceptorMiddleware.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/auth.ts
frontend/src/views/auth/SigninModal.vue

chore: update auth context

---

frontend/src/store/modules/v1/experimental-issue.ts

Temporary solution to ensure the database. We can change to the BatchGetDatabases API later.
Close BYT-7257

fix: fetch issue database

---

backend/plugin/db/cockroachdb/query.go
backend/plugin/db/pg/query.go
backend/plugin/db/redshift/query.go
backend/plugin/db/risingwave/query.go

fix: pg date infinity

---

backend/api/v1/error.go
backend/api/v1/sql_service.go
backend/plugin/parser/redis/query.go
backend/plugin/parser/redis/query_test.go

chore: read command for redis and better error message

---

backend/api/v1/issue_service.go
backend/api/v1/issue_service_convert.go
backend/api/v1/issue_service_test.go
backend/component/webhook/manager.go
backend/migrator/migration/3.6/0004##deprecate_approval_node_group_value.sql
backend/migrator/migrator_test.go
frontend/src/types/proto/google/protobuf/descriptor.ts
frontend/src/types/proto/google/protobuf/wrappers.ts
frontend/src/types/proto/store/approval.ts
proto/gen/grpc-doc/store/README.md
proto/gen/grpc-doc/store/index.html
proto/generated-go/store/approval.pb.go
proto/store/approval.proto

chore: P branch 197

---

backend/api/v1/release_service_check.go

feed the errors into the errors. otherwise issue creation will be blocked by the failed CheckRelease request on the frontend

fix: block creating issues

---

backend/plugin/parser/tsql/completion.go
backend/plugin/parser/tsql/test-data/test_completion.yaml

fix: ignore column in FROM clause

---

frontend/src/components/TransferDatabaseForm/TransferDatabaseForm.vue
frontend/src/components/TransferDatabaseForm/TransferSourceSelector.vue
frontend/src/components/v2/Select/InstanceSelect.vue
frontend/src/types/v1/environment.ts
frontend/src/views/InstanceDetail.vue

fix: invalid environment name

---

backend/plugin/db/cassandra/cassandra.go

feat: cassandra execute

---

frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

chore: show schema drifted warning before creating issue

---

backend/plugin/db/pg/pg.go

fix: execute panic

---

backend/plugin/parser/tsql/restore.go
backend/plugin/parser/tsql/restore_test.go
backend/plugin/parser/tsql/test-data/test_restore.yaml
backend/store/model/database.go

feat: restore dml by uk for mssql

---

backend/api/v1/auth_service.go

fix: npe of new user

---

backend/plugin/parser/tsql/restore.go

chore: skip pk check

---

backend/api/v1/database_service.go
frontend/src/components/IssueV1/components/DataExportSection/DataExportSection.vue
frontend/src/store/modules/v1/database.ts
frontend/src/store/modules/v1/experimental-issue.ts

chore: batch get databases

---

backend/api/directory-sync/webhook.go
backend/api/v1/auth_service.go

fix: reload iam cache

---

backend/plugin/db/cockroachdb/cockroachdb.go
backend/plugin/db/dm/dm.go
backend/plugin/db/driver.go
backend/plugin/db/dynamodb/dynamodb.go
backend/plugin/db/mysql/mysql.go
backend/plugin/db/obo/obo.go
backend/plugin/db/oracle/oracle.go
backend/plugin/db/pg/pg.go
backend/plugin/db/redshift/redshift.go
backend/plugin/db/risingwave/risingwave.go
backend/plugin/db/tidb/tidb.go
frontend/src/types/proto/google/protobuf/descriptor.ts
frontend/src/types/proto/google/protobuf/wrappers.ts
frontend/src/types/proto/store/task_run.ts
proto/gen/grpc-doc/store/README.md
proto/gen/grpc-doc/store/index.html
proto/generated-go/store/task_run.pb.go
proto/store/task_run.proto

refactor: use common position

---

frontend/src/utils/v1/iam.ts

fix: approval node workspace role

---

backend/api/v1/sql_service.go
backend/store/query_history.go
frontend/src/composables/useExecuteSQL.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/sqlEditor/queryHistory.ts
frontend/src/types/proto/v1/sql_service.ts
frontend/src/views/sql-editor/AsidePanel/HistoryPane/HistoryPane.vue
proto/gen/grpc-doc/openapi.yaml
proto/gen/grpc-doc/v1/README.md
proto/gen/grpc-doc/v1/index.html
proto/generated-go/v1/sql_service.pb.go
proto/v1/sql_service.proto

chore: filter and pagination for query history

---

frontend/src/components/Quickstart.vue

chore: remove book demo banner from the bottom

---

backend/plugin/db/tidb/sync.go
backend/plugin/db/tidb/sync_test.go

The table charset information is not available from information_schema.tables;

chore: fix tidb table charset

---

backend/plugin/parser/mysql/backup.go
backend/plugin/parser/mysql/backup_test.go
backend/plugin/parser/mysql/restore.go
backend/plugin/parser/mysql/test-data/test_restore.yaml

feat: restore dml by uk for mysql

---

backend/plugin/parser/plsql/restore.go
backend/plugin/parser/plsql/restore_test.go
backend/plugin/parser/plsql/test-data/test_restore.yaml

feat: restore dml by uk for Oracle

---

backend/plugin/parser/pg/restore.go
backend/plugin/parser/pg/restore_test.go
backend/plugin/parser/pg/test-data/test_restore.yaml

feat: restore dml by uk for PostgreSQL

---

backend/plugin/db/mssql/stmt_type.go
frontend/src/types/proto/v1/sql_service.ts
proto/gen/grpc-doc/openapi.yaml
proto/gen/grpc-doc/v1/README.md
proto/gen/grpc-doc/v1/index.html
proto/generated-go/v1/sql_service.pb.go
proto/v1/v1/sql_service.proto

feat: introduce query message proto

---

frontend/src/components/MonacoEditor/MonacoTextModelEditor.vue
frontend/src/components/MonacoEditor/composables/useAutoComplete.ts
frontend/src/components/MonacoEditor/editor.ts

chore: disable lsp by default for readonly editors

---

backend/api/lsp/completion.go

fix: nil error of lsp completion items

---

frontend/src/types/v1/environment.ts
frontend/src/types/v1/instance.ts
frontend/src/utils/v1/instance.ts
frontend/src/views/EnvironmentDashboard.vue

chore: remove empty environment

---

frontend/src/locales/zh-CN.json

chore: data source ->数据源 consistently

---

frontend/src/components/SensitiveData/GrantAccessForm.vue
frontend/src/components/SensitiveData/MaskingExceptionUserTable.vue
frontend/src/components/SensitiveData/types.ts

chore: support description in masking exception

---

frontend/src/components/ExpirationSelector.vue

chore: support custom expiration days in local storage

---

frontend/src/components/AdvancedSearch/AdvancedSearch.vue
frontend/src/components/IssueV1/components/IssueSearch/useIssueSearchScopeOptions.ts
frontend/src/components/Project/ProjectIssuesPanel.vue
frontend/src/utils/v1/advanced-search/common.ts
frontend/src/utils/v1/advanced-search/issue/utils.ts
frontend/src/views/ExportCenter/index.vue
frontend/src/views/MyIssues.vue

chore: support multiple for search issues via labels

---

scripts/Dockerfile
scripts/Dockerfile.aws

chore: increase alpine stack size

---

backend/bin/server/cmd/profile.go
backend/bin/server/cmd/profile_dev.go
backend/bin/server/cmd/profile_release.go
backend/bin/server/cmd/root.go
backend/component/config/profile.go
backend/runner/monitor/monitor.go
backend/server/server.go

feat: memory monitor

---

frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

chore: wording

---

backend/store/task.go
frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/ActionSentence.vue

fix: earliest allowed ts should be nil when task created

---

frontend/src/components/GeneralSetting/DatabaseChangeModeSetting.vue
frontend/src/components/HelpDrawer/HelpDrawer.vue
frontend/src/layouts/DashboardLayout.vue
frontend/src/store/modules/auth.ts
frontend/src/views/EnvironmentDashboard.vue
frontend/src/views/EnvironmentDetail.vue
frontend/src/views/ProjectDashboard.vue
frontend/src/views/Setup/Setup.vue
frontend/src/views/Setup/WorkspaceMode.vue
frontend/src/views/auth/Signup.vue
frontend/src/views/sql-editor/Setting/Environment/Environment.vue

- Fix the environment button position
- Remove padding in the project dashboard to unify the layout
- Remove duplicate code for database change mode setting
- Fix: redirect after signup
- Move the help code to the help drawer

chore: several ui fix & code refactor

---

frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/ConnectionPane.vue

fix(sql-editor): unknown database

---

backend/plugin/db/tidb/sync.go
backend/plugin/parser/tidb/tidb.go

fix: tidb zero time

---

frontend/src/components/IssueV1/components/TaskListSection/TaskFilter.vue
frontend/src/components/IssueV1/components/TaskListSection/TaskListSection.vue

- Fix: we will not fetch the database if multiple stages have the same page index. For example (the databases in the Test stage are actually PG without the instance license)
- Move the state to the map, and make it related to the stage
- TODO(ed): found a legacy bug - if the issue is to create the database, then we cannot get the valid info, cause the database does not exist yet.

fix: switch issue stage

---

frontend/src/components/InstanceAssignment.vue
frontend/src/components/InstanceForm/Form.vue
frontend/src/components/IssueV1/components/Sidebar/ReviewSection/utils.ts
frontend/src/components/IssueV1/components/TaskListSection/TaskCard.vue
frontend/src/components/IssueV1/logic/utils.ts
frontend/src/store/modules/v1/database.ts
frontend/src/store/modules/v1/instanceResource.ts

Handle the instance license change

fix: reactive instance

---

frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue

Part of BYT-7355
Remove the code that may cause performance issue when there are too many tasks.

chore: remove tasks param

---

backend/plugin/db/starrocks/starrocks.go
backend/plugin/parser/doris/diagnose.go
backend/plugin/parser/doris/doris.go
backend/plugin/parser/doris/doris_test.go
backend/plugin/parser/doris/query.go
backend/plugin/parser/doris/split.go
backend/plugin/parser/doris/split_test.go
backend/plugin/parser/mysql/query.go
backend/plugin/parser/mysql/query_span.go
backend/plugin/parser/mysql/split.go
backend/server/ultimate.go
go.mod
go.sum

close BYT-7343
close BYT-7342
Introduce Doris parser to support Doris specific grammars, such as ARRAY, LATERAL VIEW and catalog.
Remove Doris query span.
There are still many details that need to be improved, but it works for now.

feat: introduce doris parser

---

frontend/src/layouts/ProjectV1Layout.vue
frontend/src/views/project/ProjectIssueDetail.vue

Revert part of https://github.com/bytebase/bytebase/pull/16075

chore: fix height of project layout

---

backend/api/v1/risk_service.go
frontend/src/types/proto/v1/risk_service.ts
proto/gen/grpc-doc/openapi.yaml
proto/gen/grpc-doc/v1/README.md
proto/gen/grpc-doc/v1/index.html
proto/generated-go/v1/risk_service.pb.go
proto/generated-go/v1/risk_service.pb.gw.go
proto/generated-go/v1/risk_service_grpc.pb.go
proto/v1/v1/risk_service.proto

It's strange we have `CUD` without `R`, and the terraform provide will need the GET API

chore: implement get risk

---

frontend/src/components/IssueV1/components/TaskListSection/TaskFilter.vue
frontend/src/components/IssueV1/components/TaskListSection/filter.ts
frontend/src/components/Plan/components/SpecListSection/CurrentSpecSection.vue
frontend/src/components/Plan/components/SpecListSection/SpecCard.vue
frontend/src/components/Plan/components/SpecListSection/SpecFilter.vue
frontend/src/components/Plan/components/SpecListSection/SpecListSection.vue
frontend/src/components/Plan/components/SpecListSection/filter.ts
frontend/src/components/Plan/logic/initialize/create.ts
frontend/src/locales/en-US.json
frontend/src/store/modules/v1/plan.ts

chore: update spec list section

---

frontend/src/components/Member/MemberDataTable/cells/UserNameCell.vue
frontend/src/components/Member/MemberDataTable/cells/UserOperationsCell.vue
frontend/src/components/Member/MemberDataTable/index.vue
frontend/src/components/Member/MemberDataTableByRole.vue
frontend/src/components/Member/types.ts
frontend/src/components/Member/utils.ts
frontend/src/components/ProjectMember/ProjectMemberPanel.vue
frontend/src/components/User/Settings/UserDataTableByGroup/cells/GroupNameCell.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json
frontend/src/views/SettingWorkspaceMembers.vue
frontend/src/views/SettingWorkspaceUsers.vue

chore: show removed users and groups in the IAM

---

frontend/src/components/IssueV1/components/TaskListSection/TaskCard.vue

fix: actions in task card

---

backend/api/v1/user_service.go
frontend/src/types/proto/v1/user_service.ts
proto/gen/grpc-doc/openapi.yaml
proto/gen/grpc-doc/v1/README.md
proto/gen/grpc-doc/v1/index.html
proto/generated-go/v1/user_service.pb.go
proto/generated-go/v1/user_service.pb.gw.go
proto/generated-go/v1/user_service_grpc.pb.go
proto/v1/v1/user_service.proto

chore: batch get users

---

backend/plugin/parser/doris/normalize.go
backend/plugin/parser/doris/query_span.go
backend/plugin/parser/doris/query_span_extractor.go
backend/plugin/parser/doris/query_type.go

feat: support doris access control

---

frontend/src/components/IssueV1/components/CurrentApproverV1.vue
frontend/src/components/IssueV1/components/Sidebar/ReviewSection/ReviewSection.vue
frontend/src/components/IssueV1/logic/review.ts
frontend/src/components/Member/MembersBindingSelect.vue
frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
frontend/src/components/v2/Model/Instance/InstanceV1Table/InstanceOperations.vue
frontend/src/store/modules/release.ts
frontend/src/store/modules/rollout.ts
frontend/src/store/modules/user.ts
frontend/src/store/modules/v1/changelist.ts
frontend/src/store/modules/v1/experimental-issue.ts
frontend/src/store/modules/v1/group.ts
frontend/src/store/modules/v1/issue.ts
frontend/src/store/modules/v1/projectIamPolicy.ts
frontend/src/store/modules/v1/worksheet.ts
frontend/src/store/modules/workspaceApprovalSetting.ts
frontend/src/utils/v1/advanced-search/issue/ui-filter.ts
frontend/src/views/SettingWorkspaceAuditLog.vue
frontend/src/views/SettingWorkspaceMailDelivery.vue
frontend/src/views/project/ProjectAuditLogDashboard.vue

chore: use batchGetUsers in frontend

---

frontend/src/store/modules/user.ts

Fix https://github.com/bytebase/bytebase/pull/16100

fix: user name checks

---

frontend/src/composables/useExecuteSQL.ts
frontend/src/types/sqlEditor/tab.ts
frontend/src/utils/sqlEditor.ts
frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue
frontend/src/views/sql-editor/EditorPanel/ResultPanel/BatchQuerySelect.vue
frontend/src/views/sql-editor/EditorPanel/ResultPanel/ResultPanel.vue
frontend/src/views/sql-editor/EditorPanel/TerminalPanel/TerminalPanel.vue

Put the result history into the memory. 
---

chore: cache query result

---

frontend/src/views/sql-editor/EditorPanel/ResultPanel/BatchQuerySelect.vue

chore: tweak tabs' padding

---

backend/api/v1/database_group_service.go
backend/tests/grouping_change_test.go
backend/tests/tenant_test.go
frontend/src/components/Changelist/ChangelistDetail/ApplyToDatabasePanel/ApplyToDatabasePanel.vue
frontend/src/components/DatabaseAndGroupSelector/DatabaseAndGroupSelector.vue
frontend/src/components/DatabaseGroup/DatabaseGroupDataTable.vue
frontend/src/components/DatabaseGroup/DatabaseGroupForm.vue
frontend/src/components/DatabaseGroup/ProjectDatabaseGroupPanel.vue
frontend/src/components/Plan/components/SpecListSection/SpecCard.vue
frontend/src/components/Release/ReleaseDetail/NavBar/ApplyToDatabasePanel.vue
frontend/src/components/v2/Model/DatabaseGroupName.vue
frontend/src/components/v2/Select/DatabaseGroupSelect.vue
frontend/src/store/modules/dbGroup.ts
frontend/src/types/dbGroup.ts
frontend/src/types/proto/v1/database_group_service.ts
frontend/src/utils/databaseGroup/issue.ts
proto/gen/grpc-doc/openapi.yaml
proto/gen/grpc-doc/v1/README.md
proto/gen/grpc-doc/v1/index.html
proto/generated-go/v1/database_group_service.pb.go
proto/v1/v1/database_group_service.proto

- Remove `databaseGroupName` in the `ComposedDatabaseGroup`. It's too confused so that we have several mistakes
- Rename `database_placeholder` to `title`

chore: update database group message

---

frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

chore: tweak data source query restriction policy wording

---

frontend/src/components/ExprEditor/components/MultiSelect.vue
frontend/src/components/ExprEditor/components/SingleSelect.vue

fix: expr selector

---

backend/runner/taskrun/schedulerv2.go
backend/store/task.go

feat: block tasks within the same pipeline

---

frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/ConnectionPane.vue

fix: connect instead of batch if no connection

---

backend/api/v1/release_service_check.go

fix: env args for cacl risk level

---

backend/api/v1/release_service_check.go
backend/api/v1/risk_service_calculator.go
backend/runner/approval/runner.go
frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckSection.vue

Part of BYT-7387
* show risk level in UI before creating issue;

chore: risk level calculate func

---

frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/ConnectionPane.vue

fix: layout in small screen

---

backend/plugin/parser/base/c3.go

chore: control c3 recursion depth

---

backend/common/cel.go

fix: risk cel variables

---

backend/runner/approval/runner.go

https://github.com/bytebase/bytebase/blob/43d454c021aeac491f7b03944a2cc86104a3bb72/backend/runner/approval/runner.go#L572

chore: use partial eval consistently

---

backend/api/v1/plan_service.go
backend/api/v1/rollout_service.go
backend/api/v1/rollout_service_task.go
backend/runner/approval/runner.go
frontend/src/components/CustomApproval/Settings/components/common/utils.ts

Apparently, we don't set the schema name and table name attributes on condition eval.

chore: update approval runner

---

backend/api/v1/rollout_service.go
backend/api/v1/rollout_service_converter.go
backend/runner/taskrun/schedulerv2.go
backend/store/task.go
backend/store/task_run.go

feat: impl taskRun runAt

---

backend/migrator/migration/3.7/0003##approval_setting_cleanup.sql
backend/migrator/migrator_test.go

- REQUEST_EXPORT are removed.
- REQUEST_QUERY are replaced by REQUEST_ROLE.

chore: backfill approval rules

---

backend/plugin/db/pg/sync.go
backend/plugin/schema/pg/get_database_definition.go
frontend/src/types/proto/v1/database_service.ts
proto/gen/grpc-doc/openapi.yaml
proto/gen/grpc-doc/store/README.md
proto/gen/grpc-doc/store/index.html
proto/gen/grpc-doc/v1/README.md
proto/gen/grpc-doc/v1/index.html
proto/generated-go/store/database.pb.go
proto/generated-go/v1/database_service.pb.go
proto/store/store/database.proto
proto/v1/v1/database_service.proto

chore: sync and dump pg check constraints

---

backend/runner/taskrun/schedulerv2.go
backend/store/task_run.go

feat: set StartAt when it really starts

---

frontend/src/components/FeatureGuard/FeatureAttention.vue

fix: show feature attention

---

backend/api/v1/release_service.go
backend/api/v1/sheet_service.go
backend/component/sheet/sheet.go
frontend/src/types/proto/v1/sheet_service.ts
proto/gen/grpc-doc/openapi.yaml
proto/gen/grpc-doc/v1/README.md
proto/gen/grpc-doc/v1/index.html
proto/generated-go/v1/sheet_service.pb.go
proto/generated-go/v1/sheet_service.pb.gw.go
proto/generated-go/v1/sheet_service_grpc.pb.go
proto/v1/v1/sheet_service.proto

chore: batch create sheets - rename

---

frontend/src/components/IssueV1/components/Panel/TaskRolloutActionPanel.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

feat: set run time in task rollout panel

---

frontend/src/components/Changelog/ChangelogDataTable.vue
frontend/src/components/Database/DatabaseChangelogPanel.vue

fix: refresh changelog table after establish baseline

---

frontend/src/components/IssueV1/DataExportIssueDetailPage.vue
frontend/src/components/IssueV1/IssueDetailPage.vue
frontend/src/components/IssueV1/components/HeaderSection/Actions/Actions.vue
frontend/src/components/IssueV1/components/IssueCommentSection/Subscribers/SubscriberList.vue
frontend/src/components/IssueV1/components/IssueCommentSection/Subscribers/Subscribers.vue
frontend/src/components/IssueV1/components/IssueTableV1.vue
frontend/src/components/IssueV1/logic/initialize/create.ts
frontend/src/components/Plan/PlanDetailPage.vue
frontend/src/components/Plan/components/HeaderSection/Actions/create/CreateIssueButton.vue
frontend/src/components/Plan/components/SQLCheckSection/index.ts
frontend/src/store/modules/v1/experimental-issue.ts
frontend/src/store/modules/v1/issue.ts
frontend/src/types/v1/issue/issue.ts

chore: remove creator entity from composed issue

---

backend/api/v1/sql_service.go
backend/runner/taskrun/data_export_executor.go

Make it more reasonable, do not hack the data source in the sql_service

refactor: export data source

---

backend/plugin/webhook/discord.go

fix: discord webhook handles 204

---

backend/base/engine.go
backend/runner/plancheck/statement_report_executor.go

feat: enable summary report for MariaDB

---

frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue
frontend/src/components/Release/ReleaseDetail/NavBar/ApplyToDatabasePanel.vue
frontend/src/components/Release/ReleaseDetail/NavBar/PreviewPlanDetail.vue

chore: rename spec list

---

backend/plugin/schema/mssql/get_database_definition.go

chore: support column store index for mssql

---

backend/api/directory-sync/webhook.go
frontend/src/components/GrantRequestPanel/GrantRequestPanel.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/SchemaPane.vue

- Fix: wrong feature guard for SCIM sync (lucky they all require the enterprise plan)
- Reduce SQL Editor tree node offset, close BYT-7428

chore: some minor updates

---

frontend/src/components/IssueV1/components/DataExportSection/ExportOptionSection/ExportOptionSection.vue
frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
frontend/src/components/Plan/components/Sidebar/GhostSection/GhostFlagsPanel.vue
frontend/src/components/Plan/components/Sidebar/GhostSection/GhostSection.vue
frontend/src/components/Plan/components/Sidebar/GhostSection/GhostSwitch.vue
frontend/src/components/Plan/components/Sidebar/GhostSection/context.ts
frontend/src/components/Plan/components/Sidebar/PreBackupSection/PreBackupSwitch.vue
frontend/src/components/Plan/components/Sidebar/PreBackupSection/context.ts
frontend/src/components/Plan/components/StatementSection/EditorView/EditorView.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json
frontend/src/views/project/ProjectPlanDetail.vue

chore: adjust gh-ost and backup checks in frontend

---

backend/plugin/advisor/mssql/advisor_column_no_null.go
backend/plugin/advisor/mssql/advisor_index_not_redundant.go
backend/plugin/schema/mssql/get_database_metadata.go
backend/plugin/schema/mssql/get_database_metadata_test.go
backend/plugin/schema/mssql/test-data/test_get_database_metadata.yaml
backend/plugin/schema/schema.go
go.mod
go.sum

feat: implement get database schema metadata for SQL Server

---

frontend/src/components/IssueV1/components/TaskRunSection/TaskRunComment.vue

chore: use LocaleString

---

frontend/src/components/v2/Select/DatabaseSelect.vue
frontend/src/components/v2/Select/InstanceSelect.vue
frontend/src/components/v2/Select/UserSelect.vue

fix: auto reset in selector

---

backend/api/v1/sql_service.go
backend/base/database.go
backend/component/ghost/config.go
backend/plugin/advisor/mysql/advisor_online_migration.go
backend/plugin/advisor/utils_for_tests.go
backend/plugin/schema/pg/get_database_definition.go
backend/runner/plancheck/ghost_sync_executor.go
backend/runner/schemasync/syncer.go
backend/runner/taskrun/schema_update_ghost_executor.go
backend/tests/ghost_test.go

chore: unify bbdataarchive references

---

frontend/src/components/IssueV1/components/Panel/TaskRolloutActionPanel.vue

chore: fix display of plan check runs

---

backend/api/v1/instance_service.go
frontend/src/components/EditEnvironmentDrawer.vue
frontend/src/components/Instance/InstanceSyncButton.vue
frontend/src/components/ProjectDatabasesPanel.vue
frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
frontend/src/components/v2/Model/Instance/InstanceV1Table/InstanceOperations.vue
frontend/src/store/modules/v1/instance.ts
frontend/src/types/proto/v1/instance_service.ts
frontend/src/views/DatabaseDashboard.vue
frontend/src/views/InstanceDashboard.vue
frontend/src/views/InstanceDetail.vue
proto/gen/grpc-doc/openapi.yaml
proto/gen/grpc-doc/v1/README.md
proto/gen/grpc-doc/v1/index.html
proto/generated-go/v1/instance_service.pb.go
proto/generated-go/v1/instance_service.pb.gw.go
proto/generated-go/v1/instance_service_grpc.pb.go
proto/v1/v1/instance_service.proto

(not support batch in store level

feat: batch update instances

---

backend/enterprise/service/license.go

```
==================
WARNING: DATA RACE
Read at 0x00c0180ce9a8 by goroutine 1113:
github.com/bytebase/bytebase/backend/enterprise/service.(*LicenseService).LoadSubscription()
/Users/p0ny/bytebase/backend/enterprise/service/license.go:56 +0x40
github.com/bytebase/bytebase/backend/enterprise/service.(*LicenseService).GetEffectivePlan()
/Users/p0ny/bytebase/backend/enterprise/service/license.go:111 +0x60
github.com/bytebase/bytebase/backend/enterprise/service.(*LicenseService).IsFeatureEnabled()
/Users/p0ny/bytebase/backend/enterprise/service/license.go:73 +0x3c
github.com/bytebase/bytebase/backend/component/iam.(*Manager).CheckPermission()
/Users/p0ny/bytebase/backend/component/iam/manager.go:56 +0xa4
github.com/bytebase/bytebase/backend/api/v1.doIAMPermissionCheck() …
```

fix: data race in license service

---

backend/plugin/schema/differ.go

chore: implement database schema metadata differ

---

backend/demo/README.md
backend/demo/data/dump.sql

* 3.7.0 syncs the postgres checks metadata

chore: update demo data from 3.6.2 to 3.7.0

---

backend/plugin/parser/base/statement_ranges.go
backend/plugin/parser/doris/statement_ranges.go
backend/plugin/parser/doris/statement_ranges_test.go
backend/plugin/parser/doris/test-data/statement-ranges/doris-features.yaml
backend/plugin/parser/doris/test-data/statement-ranges/standard.yaml

feat: statement ranger for doris

---

backend/plugin/advisor/oceanbase/advisor_insert_row_limit.go
backend/plugin/advisor/oceanbase/advisor_statement_affected_row_limit.go
backend/plugin/advisor/oceanbase/common.go

Introduce InsertRowLimitAdvisor to enforce a maximum row limit on
INSERT statements for OceanBase. The advisor parses SQL ASTs and uses
EXPLAIN to estimate inserted row counts for queries with subselects,
and counts value lists for direct inserts. It generates advice if the
row count exceeds the configured threshold, helping prevent large
inserts that may impact database performance or stability.

feat(oceanbase): add insert row limit advisor

---

backend/plugin/schema/mssql/generate_migration.go
backend/plugin/schema/mssql/generate_migration_test.go
backend/plugin/schema/mssql/test-data/test_migration_constraints.yaml
backend/plugin/schema/mssql/test-data/test_migration_functions.yaml
backend/plugin/schema/mssql/test-data/test_migration_indexes.yaml
backend/plugin/schema/mssql/test-data/test_migration_procedures.yaml
backend/plugin/schema/mssql/test-data/test_migration_safe_order.yaml
backend/plugin/schema/mssql/test-data/test_migration_tables.yaml
backend/plugin/schema/mssql/test-data/test_migration_views.yaml

feat: view safe order with topo sort for sql server

---

backend/demo/data/dump.sql

* Fix DDL moderate risk level setup
* Re-baseline hr db to remove drift.

chore: fix demo data

---

backend/api/v1/rollout_service_converter.go
frontend/src/types/proto/v1/plan_service.ts
proto/gen/grpc-doc/openapi.yaml
proto/gen/grpc-doc/v1/README.md
proto/gen/grpc-doc/v1/index.html
proto/generated-go/v1/plan_service.pb.go
proto/v1/v1/plan_service.proto

* Using to check if plan is editable.

chore: add rollout to plan

---

action/github/github.go

string(int32) is converted to a character

fix: use strconv

---

frontend/src/components/ProjectMember/ProjectMemberRolePanel/EditProjectRolePanel.vue

fix: check update binding

---

backend/plugin/schema/mysql/get_database_definition.go

refactor(mysql): extract charset and sql mode writes into helper

---

backend/enterprise/api/plan.yaml

Otherwise the yaml plugin in the frontend cannot parse it correctly

fix: use the camel case for key

---

frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/DatabaseNode.vue

chore: optimize connection

---

backend/plugin/parser/pg/pg.go
backend/plugin/schema/pg/get_database_metadata.go
backend/plugin/schema/pg/get_database_metadata_test.go
backend/plugin/schema/pg/testdata/get_database_metadata.yaml
go.mod
go.sum

feat: get database metadata for pg

---

backend/plugin/schema/differ.go

chore: skip dump for differ

---

frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/sqlEditor/tab.ts
frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
frontend/src/views/sql-editor/EditorPanel/ResultPanel/ResultPanel.vue

- Support remove query history
- Support copy query statement

chore: optimize query result

---

backend/api/v1/database_service.go
backend/api/v1/worksheet_service.go
frontend/src/views/sql-editor/EditorCommon/SharePopover.vue

- Ignore deleted database in BatchGetDatabases
- Star worksheet only need have the "read" access

fix: ignore deleted database in BatchGetDatabases

---

backend/plugin/schema/differ.go
backend/plugin/schema/mssql/test-data/test_migration_safe_order.yaml
backend/plugin/schema/pg/generate_migration.go
backend/plugin/schema/pg/generate_migration_testcontainer_test.go

feat: generate migration for pg

---

backend/plugin/db/mysql/sync.go
backend/plugin/schema/differ.go
backend/plugin/schema/mysql/generate_migration.go
backend/plugin/schema/mysql/generate_migration_testcontainer_test.go

feat: implement mysql generate migration

---

backend/plugin/schema/tidb/generate_migration.go
backend/plugin/schema/tidb/generate_migration_testcontainer_test.go

feat: implement generate migration for TiDB

---

frontend/src/components/IssueV1/components/Sidebar/Sidebar.vue
frontend/src/components/SyncDatabaseSchemaV1/DatabaseSchemaSelector.vue

fix: filter only done changelogs in sync schema

---

frontend/src/components/DatabaseAndGroupSelector/DatabaseAndGroupSelector.vue
frontend/src/components/DatabaseGroup/DatabaseGroupDataTable.vue
frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/BatchQueryDatabaseGroupSelector.vue

chore: external link in database group table

---

backend/server/routers.go

chore: remove timeout middleware

---

backend/plugin/schema/mssql/get_database_definition.go
backend/plugin/schema/mssql/get_database_definition_testcontainer_test.go

chore: fix bugs and add tests for mssql dump

---

frontend/src/components/IdentityProvider/IdentityProviderEditForm.vue
frontend/src/components/IdentityProvider/IdentityProviderTable.vue
frontend/src/components/Plan/components/Configuration/Configuration.vue
frontend/src/router/dashboard/workspace.ts
frontend/src/router/dashboard/workspaceRoutes.ts
frontend/src/store/modules/v1/common.ts
frontend/src/utils/idp.ts
frontend/src/utils/useDashboardSidebar.ts
frontend/src/views/SettingWorkspaceSSO.vue
frontend/src/views/SettingWorkspaceSSODetail.vue
frontend/src/views/sql-editor/Setting/SSO/SSO.vue

chore: rename sso routes

---

frontend/src/components/Plan/components/Configuration/GhostSection/GhostSwitch.vue
frontend/src/components/v2/Model/ProjectV1Table.vue

chore: remove instance license checks for gh-ost

---

frontend/src/components/IssueV1/components/Sidebar/PreBackupSection/TaskRollbackSection.vue
frontend/src/components/IssueV1/components/Sidebar/Sidebar.vue
frontend/src/components/Plan/components/Configuration/PreBackupSection/PreBackupSection.vue
frontend/src/components/Plan/components/Configuration/PreBackupSection/context.ts

fix: backup setting display

---

frontend/src/utils/v1/sql.ts
frontend/src/views/sql-editor/EditorPanel/ResultPanel/BatchQuerySelect.vue

- Trim the suffix and prefix `"` in string value
- Fix the empty query result

chore: update query result

---

backend/plugin/db/clickhouse/query.go
go.mod

the uuid import is wrong somehow so the type cast doesn't match.
#16601

fix: clickhouse uuid

---

frontend/src/store/modules/v1/project.ts

Following https://github.com/bytebase/bytebase/pull/16615

chore: fix get current project

---

frontend/src/components/Plan/components/Configuration/GhostSection/GhostSection.vue

fix: overflow wrap in gh-ost setting

---

frontend/src/components/AdvancedSearch/useCommonSearchScopeOptions.ts
frontend/src/components/AuditLog/AuditLogDataTable.vue
frontend/src/components/Project/ProjectSwitch/ProjectSwitchContent.vue
frontend/src/components/v2/Model/PagedProjectTable.vue

- Support pagination in switch project modal, close BYT-7538
- Hide the instance filter is user doesn't have the "bb.instances.list" permission, close BYT-7525
- Fix render audit log error `Error: Do not know how to serialize a BigInt` in `JSON.stringify`

chore: support pagination in switch project modal

---

frontend/src/views/SettingWorkspaceAuditLog.vue
frontend/src/views/project/ProjectAuditLogDashboard.vue

fix: export log page size

---

frontend/src/components/Plan/components/HeaderSection/TitleInput.vue
frontend/src/components/Plan/components/IssueReviewView/ActivitySection/ActivitySection.vue
frontend/src/components/Plan/components/IssueReviewView/ActivitySection/index.ts
frontend/src/components/Plan/components/IssueReviewView/IssueReviewView.vue
frontend/src/components/Plan/components/IssueReviewView/Sidebar/Sidebar.vue

chore: issue activities in review section

---

frontend/src/store/modules/v1/project.ts

cherrypick: [release/3.6.1] fix: fetch project

---

frontend/src/components/SchemaTemplate/FieldTemplateTable.vue
frontend/src/components/SchemaTemplate/TableTemplateTable.vue

fix: cannot apply the template

---

action/main.go

fix: bytebase-action rollout

---

frontend/src/store/modules/v1/worksheet.ts

fix: failed to convert proto

---

frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentList.vue
frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/ActionIcon.vue
frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/IssueCreatedComment.vue
frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/TaskName.vue
frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/common.ts
frontend/src/components/IssueV1/components/IssueTableV1.vue
frontend/src/components/IssueV1/components/Panel/CommonDrawer.vue
frontend/src/components/IssueV1/components/Sidebar/Sidebar.vue
frontend/src/components/MarkdownEditor/MarkdownEditor.vue
frontend/src/components/Plan/components/HeaderSection/Actions/Actions.vue
frontend/src/components/Plan/components/HeaderSection/Actions/create/CreateIssueButton.vue
frontend/src/components/Plan/components/HeaderSection/Actions/panels/IssueReviewActionPanel.vue
frontend/src/components/Plan/components/HeaderSection/Actions/panels/IssueStatusActionPanel.vue
frontend/src/components/Plan/components/HeaderSection/Actions/panels/index.ts
frontend/src/components/Plan/components/HeaderSection/Actions/unified/UnifiedActionButton.vue
frontend/src/components/Plan/components/HeaderSection/Actions/unified/UnifiedActionGroup.vue
frontend/src/components/Plan/components/HeaderSection/Actions/unified/index.ts
frontend/src/components/Plan/components/HeaderSection/Actions/unified/types.ts
frontend/src/components/Plan/logic/context.ts
frontend/src/components/Plan/logic/initialize/index.ts
frontend/src/components/Plan/logic/issue-review.ts
frontend/src/components/Plan/logic/poll.ts
frontend/src/store/modules/v1/issue.ts
frontend/src/utils/v1/issue/rollout.ts
frontend/src/views/ExportCenter/DataExportIssueDataTable/DataExportIssueDataTable.vue
frontend/src/views/project/ProjectPlanDetail.vue

chore: issue status/review actions in plan detail page

---

frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue

chore: run pre-checks for database change issues only

---

frontend/src/components/Release/ReleaseDetail/NavBar/ApplyToDatabasePanel.vue
frontend/src/components/Rollout/RolloutDetail/context.ts
frontend/src/store/modules/v1/experimental-issue.ts

chore: handle error from preview rollout

---

backend/api/v1/database_service.go
backend/plugin/db/mysql/sync.go
backend/plugin/schema/mysql/generate_migration.go
backend/plugin/schema/mysql/generate_migration_testcontainer_test.go
backend/plugin/schema/mysql/get_database_definition.go
backend/plugin/schema/mysql/get_database_definition_testcontainer_test.go
frontend/src/components/SyncDatabaseSchemaV1/SelectTargetDatabasesView.vue

feat: use new differ for sync schema and fix bugs

---

backend/plugin/schema/pg/generate_migration.go
backend/plugin/schema/pg/generate_migration_testcontainer_test.go

chore: more test cases and bug fix for pg

---

backend/plugin/db/mysql/sync.go
backend/plugin/db/tidb/sync.go
backend/plugin/db/tidb/sync_test.go
backend/plugin/schema/tidb/generate_migration_testcontainer_test.go

chore: more cases for tidb

---

frontend/src/components/IssueV1/GrantRequestIssueDetailPage.vue
frontend/src/components/Project/ProjectCreatePanel.vue
frontend/src/utils/grpcweb.ts

- Use "Never" for no expiration. Close BYT-7555
- Fix: will always throw error when create resource

fix: FE throw error message

---

README.md
docs/dev-guide.md

Move dev environemnt setup to dev-guide.md

chore: remove obsoleted readme

---

frontend/src/router/index.ts
frontend/src/store/modules/sqlEditor/tab.ts

- Prevent back to auth page if user already login
- Not clean SQL editor tabs in the local storage

chore: not clean tab

---

frontend/src/components/EmailInput.vue
frontend/src/components/GeneralSetting/DomainRestrictionSetting.vue
frontend/src/components/User/Settings/CreateGroupDrawer.vue
frontend/src/components/User/Settings/CreateUserDrawer.vue
frontend/src/views/ProfileDashboard.vue

- Support multiply domain
- Optimize the email input

chore: support multiple domain

---

frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/IssueCommentAction.vue
frontend/src/components/Plan/components/IssueReviewView/Sidebar/Sidebar.vue
frontend/src/components/Plan/components/PlanCheckSection/PlanCheckSection.vue
frontend/src/components/Plan/components/RolloutView/RolloutView.vue
frontend/src/components/Plan/components/RolloutView/RunTasksButton.vue
frontend/src/components/Plan/components/RolloutView/StageCard.vue
frontend/src/components/Plan/components/RolloutView/StagesView.vue
frontend/src/components/Plan/components/RolloutView/TaskFilter.vue
frontend/src/components/Plan/components/RolloutView/TaskRolloutActionPanel.vue
frontend/src/components/Plan/components/RolloutView/TaskRunTable.vue
frontend/src/components/Plan/components/RolloutView/TaskStatusActions.vue
frontend/src/components/Plan/components/RolloutView/TaskTable.vue
frontend/src/components/Plan/components/RolloutView/TaskView.vue
frontend/src/components/Plan/components/RolloutView/index.ts
frontend/src/components/Rollout/RolloutDataTable.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json
frontend/src/router/dashboard/projectV1.ts
frontend/src/views/project/CICDLayout.vue

chore: task actions

---

backend/plugin/db/mysql/sync.go
backend/plugin/schema/mysql/get_database_metadata.go
backend/plugin/schema/mysql/get_database_metadata_testcontainer_test.go

feat: implement mysql get database metadata

---

frontend/src/components/Plan/components/RolloutView/RolloutView.vue
frontend/src/components/Plan/components/RolloutView/RunTasksButton.vue
frontend/src/components/Plan/components/RolloutView/StageCard.vue
frontend/src/components/Plan/components/RolloutView/TaskOperations.vue
frontend/src/components/Plan/components/RolloutView/TaskRolloutActionPanel.vue
frontend/src/components/Plan/components/RolloutView/TaskTable.vue
frontend/src/components/Plan/components/RolloutView/TaskTableView.vue
frontend/src/components/Plan/components/RolloutView/taskPermissions.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

Part of BYT-7417, close BYT-7346

chore: permission checks for task action

---

backend/plugin/advisor/catalog/walk_through.go
backend/plugin/advisor/code.go
backend/plugin/advisor/sql_review.go

chore: warning for walkthrough refernece other database

---

frontend/src/store/modules/sqlReview.ts

feat: fe connect rpc migration

---

backend/plugin/db/oracle/sync.go
backend/plugin/schema/oracle/generate_migration.go
backend/plugin/schema/oracle/get_database_definition.go
backend/plugin/schema/oracle/get_database_metadata.go
backend/plugin/schema/oracle/get_database_metadata_test.go

feat: implement oracle get database metadata

---

frontend/src/composables/useExecuteSQL.ts
frontend/src/store/modules/sqlEditor/editor.ts

fix: handle legacy enum value in localStorage

---

backend/plugin/schema/mysql/generate_migration.go
backend/plugin/schema/mysql/generate_migration_testcontainer_test.go
backend/plugin/schema/mysql/get_database_metadata.go

fix: mysql schema model bugs

---

frontend/src/layouts/BodyLayout.vue
frontend/src/layouts/IssuesLayout.vue
frontend/src/views/sql-editor/SQLEditorHomePage.vue

Only show Quickstart when enable sample to avoid 404 requests for sample project/issue...

chore: check enableSample for quick start

---

action/command/api.go
action/command/azure_devops.go
action/command/bitbucket.go
action/command/check.go
action/command/file.go
action/command/file_test.go
action/command/gitlab.go
action/command/platform.go
action/command/rollout.go
action/command/root.go
action/main.go

refactor: action pkgs

---

frontend/src/components/Plan/components/PlanDataTable/PlanDataTable.vue
frontend/src/components/Plan/components/RolloutView/RolloutView.vue
frontend/src/components/Plan/components/RolloutView/RunTasksButton.vue
frontend/src/components/Plan/components/RolloutView/StageCard.vue
frontend/src/components/Plan/components/RolloutView/StageView.vue
frontend/src/components/Plan/components/RolloutView/StagesView.vue
frontend/src/components/Plan/components/RolloutView/TaskRolloutActionPanel.vue
frontend/src/components/Plan/components/RolloutView/TaskView.vue
frontend/src/components/Plan/logic/poller/poller.ts
frontend/src/components/Rollout/RolloutDataTable.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json
frontend/src/utils/v1/issue/rollout.ts

chore: update rollout stages

---

backend/api/v1/plan_service.go
backend/store/plan.go
frontend/src/store/modules/v1/plan.ts
frontend/src/types/proto-es/v1/plan_service_pb.d.ts
frontend/src/views/project/ProjectPlanDashboard.vue
proto/gen/grpc-doc/openapi.yaml
proto/gen/grpc-doc/v1/README.md
proto/gen/grpc-doc/v1/index.html
proto/generated-go/v1/plan_service.pb.go
proto/v1/v1/plan_service.proto

chore: add title.matches to search plans

---

frontend/src/views/project/CICDLayout.vue

* redirect all creating database and exporting data issues to legacy page.

chore: redirect to legacy issue page

---

frontend/src/components/Plan/components/AddSpecDrawer.vue
frontend/src/components/Plan/components/ChecksView/ChecksView.vue
frontend/src/components/Plan/components/HeaderSection/Actions/create/CreateButton.vue
frontend/src/components/Plan/components/IssueReviewView/ActivitySection/ActivitySection.vue
frontend/src/components/Plan/components/IssueReviewView/IssueReviewView.vue
frontend/src/components/Plan/components/IssueReviewView/OverviewSection.vue
frontend/src/components/Plan/components/Overview.vue
frontend/src/components/Plan/components/PlanCheckSection/PlanCheckSection.vue
frontend/src/components/Plan/logic/poller/poller.ts
frontend/src/components/Project/useProjectSidebar.ts
frontend/src/composables/useIssueLayoutVersion.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json
frontend/src/router/dashboard/projectV1.ts
frontend/src/views/project/CICDLayout.vue
frontend/src/views/project/PlanSpecsView.vue

chore: merge tabs in new ci/cd page

---

frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json
frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/ConnectionPane.vue
frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/tree.ts

chore: hide empty environments by default

---

backend/component/iam/acl.yaml

chore: sqlEditorUser bb.databases.sync

---

backend/migrator/migrator.go

Remove SET ROLE to database owner during schema migration as it can cause permission issues in certain deployment scenarios. The migration process should use the connection's default role instead.

fix: remove database owner role switching in schema migration

---

action/command/rollout.go
backend/api/v1/rollout_service.go
backend/tests/action_test.go
backend/tests/gitops_test.go

feat: allow to return rollout without tasks

---

frontend/src/components/Plan/components/RolloutView/StageCard.vue
frontend/src/components/Plan/components/common/DatabaseDisplay.vue
frontend/src/components/Plan/logic/poller/poller.ts
frontend/src/components/Rollout/kits/TaskStatus.vue

chore: show tasks for active stage

---

backend/plugin/db/redshift/redshift.go

refactor: cleanup redshift magic

---

frontend/src/components/Plan/components/PlanCheckRunStatusIcon.vue
frontend/src/components/Plan/components/RefreshIndicator.vue
frontend/src/components/Plan/logic/poller/index.ts
frontend/src/components/Plan/logic/poller/poller.ts
frontend/src/components/Plan/logic/poller/utils.ts

Close BYT-7709. The polling strategy starts at 2s and doubles each interval (2s → 4s → 8s → 16s → 30s max).

chore: update resources poller

---

frontend/src/views/sql-editor/EditorCommon/QueryContextSettingPopover.vue

chore: add icon

---

frontend/src/AppRootContext.ts
frontend/src/components/Instance/InstanceArchiveRestoreButton.vue
frontend/src/components/Project/ProjectArchiveRestoreButton.vue
frontend/src/store/modules/v1/cache.ts

chore: fix page hang when restore instance/project

---

action/command/root.go

won’t print secret in the help message this way

chore(action): get env var in pre run

---

frontend/src/components/Plan/components/RolloutView/StageCard.vue
frontend/src/components/Plan/components/RolloutView/StageView.vue
frontend/src/components/Plan/components/RolloutView/TaskFilter.vue
frontend/src/components/Plan/components/RolloutView/TaskTable.vue

chore: prepare databases

---

backend/migrator/migration/3.9/0000##plan_deleted.sql
backend/migrator/migration/LATEST.sql
backend/migrator/migrator_test.go

chore: add deleted to plan table

---

frontend/src/components/Plan/components/RolloutView/TaskRunTable.vue
frontend/src/components/Plan/components/RolloutView/TaskTable.vue

chore: show latest task run detail in task table

---

frontend/src/components/Plan/logic/initialize/index.ts

fix: redirect to legacy page for issues without plan

---

frontend/src/components/Plan/components/PlanDataTable/PlanDataTable.vue
frontend/src/components/Plan/components/RolloutView/TaskTable.vue
frontend/src/components/Rollout/RolloutDataTable.vue
frontend/src/components/misc/Timestamp.vue

chore: unify timestamp display

---

frontend/src/components/CustomApproval/Settings/components/common/utils.ts

fix: enum to string

---

.claude/commands/lint.md

chore: add claude lint command

---

backend/api/v1/actuator_service.go
backend/api/v1/setting_service.go

refactor: remove convertProtoToProto

---

frontend/src/components/Plan/components/PlanDataTable/PlanDataTable.vue

chore: add ellipsis to plan data table

---

frontend/src/components/Plan/components/RolloutView/TaskOperations.vue
frontend/src/components/Plan/components/RolloutView/TaskStatusActions.vue
frontend/src/components/Plan/components/RolloutView/TaskView.vue

fix: allow to run canceled tasks

---

frontend/src/components/Rollout/RolloutDataTable.vue

chore: add title to rollout data table

---

frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue

fix: create plan with title

---

frontend/src/components/Plan/components/RolloutView/StageCard.vue
frontend/src/components/Plan/components/RolloutView/TaskRunRollbackDrawer.vue
frontend/src/components/Plan/components/RolloutView/TaskView.vue
frontend/src/components/Plan/components/SpecDetailView/TargetListSection.vue
frontend/src/components/Plan/components/common/DatabaseDisplay.vue
frontend/src/utils/v1/database.ts

feat: link to db (some)

---

frontend/src/components/Plan/components/HeaderSection/Actions/Actions.vue
frontend/src/components/Plan/components/RefreshIndicator.vue
frontend/src/components/Plan/logic/context.ts
frontend/src/components/Plan/logic/issue-review.ts
frontend/src/components/Plan/logic/poller/poller.ts
frontend/src/views/project/CICDLayout.vue

fix: plan poller for issue/rollout refresh

---

frontend/src/components/IssueV1/logic/initialize/create.ts

fix: set issue title

---

backend/api/v1/query_result_masker.go
backend/api/v1/sql_service.go
backend/runner/schemasync/syncer.go
backend/store/model/database.go

fix: create a new config instead of in-place changes to avoid shared-map

---

backend/api/v1/database_service.go

chore: filter out archive objects

---

frontend/src/components/Plan/components/RolloutView/TaskRolloutActionPanel.vue
frontend/src/components/Plan/components/RolloutView/taskPermissions.ts

fix: task run permission checks

---

frontend/src/components/Plan/components/IssueReviewView/ActivitySection/ActivitySection.vue

fix: order of using hook

---

backend/plugin/db/driver.go
backend/runner/schemasync/syncer.go
backend/runner/taskrun/data_update_executor.go
backend/runner/taskrun/executor.go
backend/runner/taskrun/schema_update_executor.go
backend/runner/taskrun/schema_update_ghost_executor.go

refactor: remove driver.MigrationType

---

backend/runner/taskrun/schedulerv2.go

Close BYT-7838
An attempt to fix.

fix: handle scheduler states revertings

---

backend/plugin/db/tidb/sync.go

feat: sync tidb generated column

---

backend/api/v1/rollout_service_converter.go
backend/generated-go/v1/plan_service.pb.go
backend/store/plan.go
frontend/src/components/Plan/components/PlanCheckSection/PlanCheckSection.vue
frontend/src/components/Plan/logic/poller/poller.ts
frontend/src/store/modules/v1/plan.ts
frontend/src/types/proto-es/v1/plan_service_pb.d.ts
proto/gen/grpc-doc/openapi.yaml
proto/gen/grpc-doc/v1/README.md
proto/gen/grpc-doc/v1/index.html
proto/v1/v1/plan_service.proto

chore: show running status for plan check runs

---

frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/components/DataExportButton.vue
frontend/src/components/IssueV1/components/HeaderSection/Actions/request/ExportArchiveDownloadButton.vue
frontend/src/store/modules/v1/auditLog.ts

Refer to https://devblogs.microsoft.com/typescript/announcing-typescript-5-9/#notable-behavioral-changes
Close https://github.com/bytebase/bytebase/pull/17061

chore: update typescript to 5.9.2 and fix arraybuffer compatibility

---

backend/store/principal.go

fix: filter users in the project

---

backend/store/issue.go
frontend/src/components/Plan/components/HeaderSection/Actions/panels/IssueCreationActionPanel.vue

fix: new created issue's title and description

---

backend/tests/webhook_test.go

chore: add webhook tests

---

frontend/src/components/Plan/components/ChecksView/ChecksView.vue
frontend/src/components/Plan/components/HeaderSection/Actions/panels/IssueCreationActionPanel.vue
frontend/src/components/Plan/components/IssueReviewView/OverviewSection.vue
frontend/src/components/Plan/components/PlanCheckRunStatusIcon.vue
frontend/src/components/Plan/components/PlanCheckSection/PlanCheckSection.vue
frontend/src/components/Plan/components/PlanCheckStatusCount.vue
frontend/src/components/Plan/components/RolloutView/TaskRolloutActionPanel.vue
frontend/src/components/Plan/logic/index.ts
frontend/src/components/Plan/logic/usePlanCheckStatus.ts

chore: unify plan check run status count display across components

---

frontend/src/components/Plan/components/RolloutView/StageCard.vue
frontend/src/components/Plan/components/RolloutView/TaskTable.vue
frontend/src/components/Plan/components/RolloutView/TaskView.vue
frontend/src/components/Plan/components/common/DatabaseDisplay.vue

chore: improve task run time display in rollout views

---

backend/api/v1/plan_service.go
backend/api/v1/plan_service_plan_check.go

chore: disallow create plan check runs for plan with release

---

frontend/src/components/Plan/components/SpecDetailView/SpecDetailView.vue
frontend/src/components/Plan/logic/usePlanCheckStatus.ts

chore: hide plan check runs for specs with release

---

README.md

https://github.com/bytebase/bytebase/pull/17106 followup

chore: README broken links

---

frontend/src/components/Plan/components/HeaderSection/Actions/Actions.vue
frontend/src/components/Plan/components/HeaderSection/Actions/unified/UnifiedActionButton.vue
frontend/src/components/Plan/components/HeaderSection/Actions/unified/UnifiedActionGroup.vue
frontend/src/components/Plan/components/StatementSection/EditorView/EditorView.vue
frontend/src/components/Plan/logic/useEditorState.ts
frontend/src/components/Plan/logic/useNavigationGuard.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json
frontend/src/views/project/CICDLayout.vue

feat: prevent navigation when editing SQL statements in plan editor

---

frontend/src/components/ExprEditor/ConditionGroup.vue

fix: component re-render cause the state reset

---

README.md

Context: https://linear.app/docs/creating-issues#create-an-issue-via-email

chore: use linear email to triage support tickets

---

backend/runner/taskrun/schema_update_sdl_executor.go

feat: use execFunc for sdl task executor

---

frontend/src/components/Plan/components/HeaderSection/Actions/unified/UnifiedActionGroup.vue
frontend/src/components/Plan/components/RolloutView/TaskStatusActions.vue
frontend/src/components/Plan/components/RolloutView/TaskView.vue
frontend/src/components/Plan/components/SpecDetailView/SpecListSection.vue
frontend/src/components/Plan/logic/utils.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json
frontend/src/utils/v1/issue/plan.ts

chore: add navigation from tasks to related spec changes

---

backend/plugin/db/oracle/query.go

fix: only for select add limit

---

frontend/src/AuthContext.vue
frontend/src/components/Member/MemberDataTable/index.vue
frontend/src/components/ProjectMember/ProjectMemberRolePanel/index.vue
frontend/src/components/ProvideDashboardContext.vue
frontend/src/components/ProvideSQLEditorContext.vue
frontend/src/components/User/Settings/UserDataTableByGroup/index.vue
frontend/src/layouts/SQLEditorLayout.vue
frontend/src/store/modules/v1/group.ts

fix: load groups before workspace IAM policy to resolve dependencies

---

backend/plugin/schema/mysql/get_database_metadata.go
backend/plugin/schema/mysql/get_database_metadata_testcontainer_test.go

fix: index compare for mysql

---

frontend/src/AuthContext.vue
frontend/src/components/Member/MembersBindingSelect.vue
frontend/src/components/User/Settings/UserDataTable/index.vue
frontend/src/components/v2/Select/GroupSelect.vue
frontend/src/store/modules/v1/group.ts
frontend/src/views/SettingWorkspaceUsers.vue

Following https://github.com/bytebase/bytebase/pull/17181

fix: group table and selectors showing only partial groups

---

frontend/src/AuthContext.vue
frontend/src/components/ProvideDashboardContext.vue
frontend/src/router/index.ts

- Reorganize router logic into clear sections with better comments
- Move password reset handling from AuthContext to router
- Remove redundant router hooks from ProvideDashboardContext
also fixed testing connection for SSO

refactor: router navigation

---

frontend/src/components/Plan/components/RolloutView/TaskTable.vue

fix: get latest taskrun

---

frontend/src/router/index.ts

Follow-up to https://github.com/bytebase/bytebase/pull/17195

fix: infinite redirect in navigation guard

---

frontend/src/components/Revision/RevisionDataTable.vue

Versioned or declarative
Close BYT-7861

feat(UI): show revision type

---

frontend/src/components/Release/ReleaseDataTable.vue
frontend/src/components/Release/ReleaseDetail/BasicInfo.vue
frontend/src/components/Release/ReleaseDetail/NavBar/ApplyToDatabasePanel.vue
frontend/src/components/Release/ReleaseDetail/ReleaseFileTable/ReleaseFileDetailPanel.vue
frontend/src/components/Release/ReleaseDetail/context.ts
frontend/src/components/Revision/CreateRevisionDrawer.vue
frontend/src/store/modules/release.ts
frontend/src/types/release.ts

refactor: remove `ComposedRelease` type

---

frontend/src/components/Plan/components/IssueReviewView/ActivitySection/ActivitySection.vue
frontend/src/components/Plan/components/IssueReviewView/DescriptionSection/DescriptionSection.vue
frontend/src/components/Plan/components/IssueReviewView/DescriptionSection/index.ts
frontend/src/components/Plan/components/IssueReviewView/IssueReviewView.vue
frontend/src/components/Plan/components/IssueReviewView/OverviewSection.vue
frontend/src/components/Plan/components/IssueReviewView/Sidebar/Sidebar.vue

chore: move plan description from sidebar for main view

---

frontend/src/components/Plan/components/IssueReviewView/DescriptionSection/DescriptionSection.vue
frontend/src/components/Plan/components/SpecDetailView/FailedTaskRunsSection.vue
frontend/src/components/Plan/components/SpecDetailView/SpecDetailView.vue

fix: section visibility in plan

---

backend/plugin/schema/pg/generate_migration.go
backend/plugin/schema/pg/generate_migration_testcontainer_test.go
backend/plugin/schema/pg/get_database_metadata.go
backend/plugin/schema/pg/sdl_validation_testcontainer_test.go
backend/plugin/schema/pg/view_comparer.go

chore: introduce sdl test and fix bugs

---

.github/workflows/build-push-action-image.yml
.github/workflows/docker-tag-latest.yml

Close BYT-7939.
Manually trigger to build latest image.

chore(action-image): latest or versioned

---

backend/plugin/schema/pg/get_database_definition.go
backend/plugin/schema/pg/get_database_definition_testcontainer_test.go
backend/plugin/schema/pg/sdl_validation_testcontainer_test.go

fix: fk on update/delete options

---

frontend/src/components/Plan/components/HeaderSection/DescriptionInput.vue
frontend/src/components/Plan/components/HeaderSection/HeaderSection.vue
frontend/src/components/Plan/components/HeaderSection/TitleInput.vue

chore: add description input for plans without issue

---

backend/plugin/schema/pg/ast/expression_ast.go
backend/plugin/schema/pg/ast/expression_comparer_production_test.go
backend/plugin/schema/pg/ast/expression_comparer_strict_test.go
backend/plugin/schema/pg/ast/expression_normalizer.go
backend/plugin/schema/pg/ast/expression_parser.go
backend/plugin/schema/pg/ast/expression_parser_parentheses_test.go
backend/plugin/schema/pg/ast/expression_visitor.go
backend/plugin/schema/pg/get_database_metadata.go
backend/plugin/schema/pg/get_database_metadata_testcontainer_test.go

chore: enhance expression comparer

---

action/command/root.go

chore(action): wake up cloud

---

backend/plugin/schema/differ.go
backend/plugin/schema/expression_comparer.go
backend/plugin/schema/pg/ast/expression_comparer.go
backend/plugin/schema/pg/ast/expression_comparer_production_test.go
backend/plugin/schema/pg/ast/expression_comparer_strict_test.go
backend/plugin/schema/pg/ast/expression_comparer_test.go

feat: implement expression comparison interface and clean up PostgreSQL codebase

---

backend/api/v1/plan_service_plan_check.go

chore: check sheets for plan check run creates

---

frontend/src/components/Plan/components/StatementSection/ReleaseView/ReleaseView.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

feat: file type in release view

---

backend/api/v1/sql_service_ai.go
frontend/src/components/GeneralSetting/AIAugmentationSetting.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

chore: support gemini & claude

---

frontend/src/components/CustomApproval/Settings/components/common/utils.ts
frontend/src/components/v2/Model/DatabaseV1Table/DatabaseV1Table.vue
frontend/src/components/v2/Model/EnvironmentV1Name.vue
frontend/src/components/v2/Model/Instance/InstanceV1Table/InstanceV1Table.vue

Show the environment color if it is configured

chore: show environment color

---

frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/IssueCreatedCommentV1.vue
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunComment.vue
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunSection.vue
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunTable.vue
frontend/src/components/Plan/components/SpecDetailView/FailedTaskRunsSection.vue
frontend/src/store/modules/v1/experimental-issue.ts
frontend/src/store/modules/v1/taskRunLog.ts
frontend/src/types/v1/issue/issue.ts
frontend/src/types/v1/issue/rollout.ts

chore: remove ComposedTaskRun type

---

frontend/src/components/Plan/components/RolloutView/TaskRolloutActionPanel.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

feat: check automatic rollout policy when run tasks

---

action/command/rollout.go

chore(action): default release title

---

frontend/src/components/IssueV1/IssueDetailPage.vue
frontend/src/components/Plan/components/HeaderSection/Actions/Actions.vue
frontend/src/components/Plan/components/HeaderSection/Actions/panels/IssueReviewActionPanel.vue
frontend/src/components/Plan/components/HeaderSection/Actions/panels/IssueStatusActionPanel.vue
frontend/src/components/Plan/components/HeaderSection/Actions/unified/UnifiedActionButton.vue
frontend/src/components/Plan/components/HeaderSection/Actions/unified/UnifiedActionGroup.vue
frontend/src/components/Plan/components/HeaderSection/Actions/unified/types.ts
frontend/src/components/Plan/components/IssueReviewView/DatabaseChangeView.vue
frontend/src/components/Plan/components/IssueReviewView/DatabaseCreateView.vue
frontend/src/components/Plan/components/IssueReviewView/DatabaseExportView.vue
frontend/src/components/Plan/components/IssueReviewView/IssueBaseLayout.vue
frontend/src/components/Plan/components/IssueReviewView/index.ts
frontend/src/components/Plan/components/RolloutView/TaskRolloutActionPanel.vue
frontend/src/components/Plan/components/RolloutView/TaskRunTable.vue
frontend/src/components/Plan/logic/poller/poller.ts
frontend/src/utils/v1/issue/rollout.ts
frontend/src/views/project/CICDLayout.vue
frontend/src/views/project/IssueDetailV1View.vue

Close BYT-7912, use flattened information instead of stage/task groups.

refactor: creating database issue page

---

frontend/src/components/DatabaseInfo.vue
frontend/src/components/IssueV1/components/HeaderSection/HeaderSection.vue
frontend/src/components/Plan/components/PlanCheckSection/PlanCheckSection.vue
frontend/src/components/Plan/components/RolloutView/TaskRunTable.vue
frontend/src/views/project/PlanSpecsView.vue

- Add empty template to PlanSpecsView component to fix missing template warning
- Fix invalid watch source in PlanCheckSection by using getter function for selectedSpec.value.id
- Include other staged UI improvements

fix: resolve Vue warnings

---

frontend/src/components/Release/ReleaseDetail/ReleaseFileTable/ReleaseFileTable.vue

a conclusion of file type and change type

feat: display release file type

---

backend/api/v1/setting_service.go
frontend/src/components/GeneralSetting/AIAugmentationSetting.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

chore: disable ai setting in the saas mode

---

frontend/src/components/DatabaseGroup/DatabaseGroupDataTable.vue
frontend/src/components/DatabaseGroup/DatabaseGroupForm.vue
frontend/src/components/DatabaseGroup/ProjectDatabaseGroupPanel.vue
frontend/src/store/modules/dbGroup.ts
frontend/src/types/dbGroup.ts
frontend/src/utils/databaseGroup/issue.ts

refactor: remove ComposedDatabaseGroup type and simplify data flow

---

frontend/src/views/InstanceDashboard.vue

fix: engine in instance filter

---

frontend/src/components/AdvancedSearch/ScopeTags.vue

fix: improve advanced search filter tag layout structure

---

action/command/file.go

fix(action): remove ext

---

backend/api/v1/release_service_check.go
backend/common/cel.go
backend/runner/approval/runner.go
frontend/src/components/CustomApproval/Settings/components/CustomApproval/RuleDialog/RuleDialog.vue
frontend/src/components/CustomApproval/Settings/components/CustomApproval/RuleDialog/RuleForm.vue
frontend/src/components/CustomApproval/Settings/components/CustomApproval/common/StepsTable.vue
frontend/src/components/CustomApproval/Settings/components/common/utils.ts

- Support instance_id in risk condition. Close BYT-8094
- Fix approval flow UI. Close BYT-8089

chore: support instance_id in risk condition

---

backend/plugin/schema/differ.go
backend/plugin/schema/pg/get_sdl_diff.go
backend/plugin/schema/pg/view_sdl_diff_test.go

feat: support pg view in SDL differ

---

backend/plugin/schema/pg/generate_migration.go
backend/plugin/schema/pg/view_migration_integration_test.go

feat: generate view migration for AST only diff

---

backend/plugin/schema/pg/generate_migration.go
backend/plugin/schema/pg/sequence_migration_integration_test.go

feat: support generate pg sequence migration for ast-only

---

backend/plugin/schema/pg/generate_migration.go
backend/plugin/schema/pg/table_migration_integration_test.go

feat: support genereate pg index migration for ast-only

---

frontend/src/components/Plan/components/HeaderSection/Actions/Actions.vue
frontend/src/components/Plan/components/RolloutView/TaskRolloutActionPanel.vue
frontend/src/components/Plan/components/SpecDetailView/TargetsSelectorDrawer.vue
frontend/src/locales/zh-CN.json

- Refactor task grouping logic in TaskRolloutActionPanel with proper type safety
- Improve parent path handling for batch operations
- Update Chinese translations for better clarity (targets -> target databases)

refactor: improve plan task rollout UI and code organization

---

backend/server/grpc_routes.go

chore: grpc gateway routing error

---

frontend/src/components/Plan/components/Configuration/Configuration.vue
frontend/src/components/Plan/components/Configuration/GhostSection/GhostSection.vue
frontend/src/components/Plan/components/Configuration/InstanceRoleSection/InstanceRoleSection.vue
frontend/src/components/Plan/components/Configuration/InstanceRoleSection/context.ts
frontend/src/components/Plan/components/Configuration/IsolationLevelSection/IsolationLevelSection.vue
frontend/src/components/Plan/components/Configuration/IsolationLevelSection/IsolationLevelSelect.vue
frontend/src/components/Plan/components/Configuration/IsolationLevelSection/context.ts
frontend/src/components/Plan/components/Configuration/IsolationLevelSection/index.ts
frontend/src/components/Plan/components/Configuration/PreBackupSection/PreBackupSection.vue
frontend/src/components/Plan/components/Configuration/TransactionModeSection/TransactionModeSection.vue
frontend/src/components/Plan/components/Configuration/TransactionModeSection/TransactionModeSwitch.vue
frontend/src/components/Plan/components/Configuration/TransactionModeSection/context.ts

- Unify layout and styling across all configuration sections
- Standardize label, tooltip, and control positioning
- Simplify context provider interfaces and logic
- Reorder sections for better logical flow (instance → transaction → isolation → backup/ghost)
- Replace inconsistent tooltip implementations with standardized icons
- Remove unused selectedTask parameters from context providers

refactor: improve plan configuration UI and component consistency

---

frontend/src/views/sql-editor/AsidePanel/SchemaPane/actions.tsx

chore: not change the schema when navigating between different database objects

---

frontend/src/components/Plan/components/RolloutView/TaskRolloutActionPanel.vue

fix: hide automatic rollout info when tasks have task runs

---

backend/plugin/parser/pg/statement_type.go

Close BYT-8121
- handle drop view correctly
- view and materialized view are both identified as CREATE_VIEW 
currently
- handle create view correctly

fix: pg statement type

---

backend/api/v1/database_service.go
backend/plugin/schema/pg/get_database_definition.go
backend/plugin/schema/pg/get_database_definition_sdl_test.go
backend/plugin/schema/schema.go

feat: support pg sdl format dump

---

backend/plugin/schema/pg/get_sdl_diff.go
backend/plugin/schema/pg/get_sdl_diff_test.go

chore: support sdl init

---

backend/plugin/schema/pg/get_database_definition.go
backend/runner/taskrun/schema_update_sdl_executor.go
backend/runner/taskrun/schema_update_sdl_executor_test.go
backend/tests/action_test.go

feat: use new sdl workflow

---

backend/api/v1/plan_service.go

we need to be able to update earliestAllowedTime previously, and I 
believe that’s why we have this if 
condition.

chore: more strict update check

---

backend/plugin/schema/pg/column_rewrite_test.go
backend/plugin/schema/pg/get_database_definition.go
backend/plugin/schema/pg/get_sdl_diff.go

feat: handle column drift in SDL workflow

---

backend/plugin/schema/pg/column_rewrite_test.go
backend/plugin/schema/pg/constraint_rewrite_test.go
backend/plugin/schema/pg/get_database_definition.go
backend/plugin/schema/pg/get_database_definition_sdl_test.go
backend/plugin/schema/pg/get_sdl_diff.go

feat: handle table constraint drift in SDL workflow

---

backend/plugin/schema/pg/constraint_rewrite_test.go
backend/plugin/schema/pg/get_database_definition.go
backend/plugin/schema/pg/get_database_definition_sdl_test.go
backend/plugin/schema/pg/get_sdl_diff.go
backend/plugin/schema/pg/index_rewrite_test.go
backend/plugin/schema/pg/sdl_validation_testcontainer_test.go

feat: handle index drift in SDL workflow

---

frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/TableCell.vue

chore: allow select & copy partial value

---

frontend/src/components/Plan/components/Configuration/Configuration.vue
frontend/src/components/Plan/components/StatementSection/EditorView/EditorView.vue
frontend/src/components/Plan/components/StatementSection/StatementSection.vue

chore: issue page layout
