- frontend/src/components/Issue/IssueDetailLayout.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
> feat: add hint for changing SQL in tenant mode

- frontend/src/components/Issue/PipelineStageList.vue
> chore(frontend): wording and styling issue pipeline

- frontend/src/plugins/issue/logic/initialize/assignee.ts
- frontend/src/plugins/issue/logic/initialize/index.ts
> feat(frontend): select a default assignee on the frontend when creating an issue

- api/setting.go
- change IMType type
- don't send ApprovalCode to the frontend
@boojack FYI
> fix: settingAppIMValue

- plugin/parser/ast/constraint_def.go
- plugin/parser/engine/pg/convert.go
- plugin/parser/engine/pg/convert_test.go
- plugin/parser/engine/pg/deparse.go
- plugin/parser/engine/pg/test-data/test_alter_table_data.yaml
> feat: support deparse alter table add constraint unique spec

- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/router/index.ts
- frontend/src/types/setting.ts
- frontend/src/utils/role.ts
- frontend/src/views/DashboardHeader.vue
- frontend/src/views/SettingSidebar.vue
- frontend/src/views/SettingWorkspaceGeneral.vue
- frontend/src/views/SettingWorkspaceIMIntegration.vue
- server/setting.go
Close BYT-1772
https://user-images.githubusercontent.com/24653555/199914125-da3915cb-39e3-4612-92a7-83733b6f4ef5.mp4
> feat(frontend): IM integration setting

- frontend/src/components/ProjectOverviewPanel.vue
- frontend/src/views/Home.vue
> fix: view all link style

- plugin/parser/differ/pg/differ.go
- plugin/parser/differ/pg/test-data/test_differ_data.yaml
- plugin/parser/differ/pg/test-data/test_differ_schema.yaml
> refactor(parser): refactor schema info in pg differ and support DROP TABLE

- plugin/parser/differ/pg/differ.go
- plugin/parser/differ/pg/test-data/test_differ_data.yaml
- plugin/parser/engine/pg/deparse.go
- plugin/parser/engine/pg/test-data/test_alter_table_data.yaml
> feat(parser): support to sync CHECK constraints

- frontend/src/components/InstanceUserTable.vue
> fix: text overflow in instance user table

- frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue
> feat: add env name to instance in SQL Editor

- plugin/db/mysql/binlog_stream_parser.go
- plugin/db/mysql/rollback.go
- plugin/db/mysql/rollback_test.go
- tests/rollback_test.go
This is part of the DML task flashback feature.
> feat(flashback): generate rollback SQL from binlog

- server/application_runner.go
- server/setting.go
Return on empty value, which is the dafault.
Close BYT-1787
> fix: handle default setting

- server/application_runner.go
- server/task_scheduler.go
- remove unnecessary parameters.
- inline err
> refactor: app runner

- server/application_runner.go
Only look into the latest task check run to decide whether to create external appoval.
> fix: should create approval

- frontend/src/views/SheetDashboard.vue
Fix BYT-1794
---
We only allow delete sheet in `My Sheets` tab.
> fix: remove delete sheet button in starred tab

- api/project_member.go
- server/project.go
- server/sheet.go
Followup of https://github.com/bytebase/bytebase/pull/3354.
This should be the last piece to lock down the Sheet ACL in backend.
> feat: only allow workspace developers to create sheet in the project where they have membership

- api/project_member.go
- frontend/src/store/modules/sheet.ts
- server/acl.go
- server/acl_casbin_policy_dba.csv
- server/acl_casbin_policy_developer.csv
- server/acl_casbin_policy_owner.csv
- server/project.go
- server/sheet.go
- tests/tests.go
> chore: move `sync-sheet` api route to `/project` based

- frontend/src/components/Issue/IssueTaskStatementPanel.vue
Close BYT-1513
1. Watch the event BEFORE switching tasks, and store the temp edit state.
2. Watch the event AFTER switching tasks, and restore the temp edit state if possible.
> feat(frontend): independent editing state for each task

- plugin/parser/differ/pg/differ.go
As conversation in https://github.com/bytebase/bytebase/pull/3341#discussion_r1021044474, we should put the constraint map into `tableInfo` instead of the `schemaInfo` because the constraint name is unique in one table namespace.
Some experiments:
What's the output of pg_dump if we using `ALTER TABLE ADD CONSTRAINT constraint_name USING INDEX` to create the unique constraint?
PostgreSQL will rename the index name to constraint name:
```sql
h3n4l@127:test> CREATE TABLE a(id INT);
CREATE TABLE
h3n4l@127:test> CREATE TABLE b(id INT);
CREATE TABLE
h3n4l@127:test> CREATE UNIQUE INDEX b_unique_idx ON b(id);
CREATE INDEX
h3n4l@127:test> CREATE UNIQUE INDEX a_unique_idx ON a(id);
CREATE INDEX
h3n4l@127:test> ALTER TABLE a ADD CONSTRAINT unique_constraint UNIQUE USING INDEX a_unique_idx;
ALTER …
```
> fix: move constraint map into table info

- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/types/plan.ts
- frontend/src/views/SettingWorkspaceIMIntegration.vue
> feat: set IM approval as enterprise plan in frontend

- api/sheet.go
- frontend/src/components/ProvideSQLEditorContext.vue
- frontend/src/store/modules/sheet.ts
- frontend/src/types/sheet.ts
- frontend/src/utils/sheet.ts
- frontend/src/views/SheetDashboard.vue
- frontend/src/views/sql-editor/EditorPanel/EditorPanel.vue
- store/sheet.go
> chore: update sheet payload definition

- plugin/parser/ast/create_index_stmt.go
- plugin/parser/ast/drop_index_stmt.go
- plugin/parser/differ/pg/differ.go
- plugin/parser/differ/pg/test-data/test_differ_data.yaml
- plugin/parser/engine/pg/convert.go
- plugin/parser/engine/pg/convert_test.go
- plugin/parser/engine/pg/deparse.go
- plugin/parser/engine/pg/deparse_test.go
- plugin/parser/engine/pg/test-data/test_drop_index_data.yaml
> feat(differ): support to sync index

- frontend/src/components/PricingTable/PricingTable.vue
- frontend/src/views/SettingWorkspaceSubscription.vue
- server/metric_reporter.go
Based on @candy2255's feedback
Before:
After:
> fix: update the UI on the subscription page

- frontend/src/components/PricingTable/PricingTable.vue
- frontend/src/views/SettingWorkspaceSubscription.vue
* chore: collect principal name
* fix: ui in subscription page
* chore: revert change
> fix: (cherry-pick) update the UI on the subscription page (#3374)

- frontend/src/views/SettingWorkspaceIMIntegration.vue
Close BYT-1805
https://user-images.githubusercontent.com/24653555/201660571-12e9145e-102d-4f61-9532-c5cb3825dce2.mp4
> fix: upsert feishu integration setting

- api/plan.go
- frontend/src/components/SyncDatabaseSchemaPrepForm.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/types/plan.ts
* fix: feature matrix for sync schema
* chore: rename
* Update frontend/src/types/plan.ts
Co-authored-by: Tianzhou (天舟) <t@bytebase.com>
Co-authored-by: Tianzhou (天舟) <t@bytebase.com>
> fix: (cherry-pick) feature matrix for sync schema (#3372)

- frontend/src/components/ProjectMemberPanel.vue
> feat(frontend): add a hint on project settings page that RBAC is a paid feature

- frontend/src/components/DatabaseSelect.vue
- frontend/src/components/SyncDatabaseSchemaPrepForm.vue
> feat(sync-schema): allow select PG instance in dev mode

- plugin/parser/edit/edit.go
- plugin/parser/edit/mysql/edit.go
- plugin/parser/edit/mysql/edit_test.go
Register schema edit plugin for using at the server level.
> chore: register schema edit plugin

- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/views/sql-editor/TabList/TabList.vue
> chore(sql-editor): Improve the wording for closing a unsaved sheet

- bin/server/cmd/root.go
- server/acl_casbin_policy_dba.csv
- server/acl_casbin_policy_developer.csv
- server/acl_casbin_policy_owner.csv
> chore: register mysql edit driver

- tests/schema_update_test.go
I have no idea why the test case has passed...
> test: fix TestVCS

- frontend/src/components/Issue/logic/extra.ts
> feat(frontend): Allow workspace owner and DBA to edit issue name and description

- plugin/app/feishu/feishu.go
- server/application_runner.go
- server/issue.go
> feat: improve feishu approval info

- server/application_runner.go
Use map to get the most recent task check for each type of task check and see if there is any error.
> fix: app runner task check

- server/application_runner.go
- server/issue.go
Try to cancel the external approval on issue cancellation.
> fix: cancel external approval on issue cancellation

- server/application_runner.go
Don't send external approvals if the stage environment approval policy is auto-approve.
> fix: don't send for auto-approvals

- frontend/src/bbkit/index.ts
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/views/SettingSidebar.vue
- frontend/src/views/SettingWorkspaceIMIntegration.vue
* Set as default enabled when creating;
* Add beta badge;
* Add description and docs link;
* Add data requesting status;
> chore: update IM integration UI

- plugin/vcs/github/github.go
- plugin/vcs/gitlab/gitlab.go
- plugin/vcs/vcs.go
- server/webhook.go
- tests/fake/github.go
- tests/fake/gitlab.go
- tests/fake/provider.go
- tests/schema_update_test.go
* feat(vcs): filter commits by commits compare
* fix: fix TestWildcardInVCSFilePathTemplate
* refactor: reduce the duplicate code
Co-authored-by: h3n4l <oysterdays@gmail.com>
> chore: cherrypick feat(vcs): filter commits in push event webhook by commits diff (#3411)

- server/setting.go
> fix: check empty values on update feishu setting

- plugin/parser/differ/pg/differ.go
- plugin/parser/differ/pg/test-data/test_differ_constraint.yaml
> feat(differ): support to sync foreign keys

- plugin/db/pg/dump.go
pg_dump allow the server to be back to 9.2, and up to any minor release of our own major version. So we need to bump the pg_dump version to 15.1 to support newest PostgreSQL 15.
| Arch | Build PostgreSQL Env | Modify ShareLibrary |
| --- | --- | --- |
| Linux x86 | AWS Ubuntu18.04 | patchelf --set-rpath='../lib/' pg_dump |
| Linux arm64 | AWS Ubuntu18.04 | patchelf --set-rpath='../lib/' pg_dump |
| OSX amd64 | MBA i5 Chip Monterey  | install_name_tool -change /usr/local/pgsql/lib/libpq.5.dylib @loader_path/../lib/libpq.5.dylib pg_dump |
Linux build script:
```shell
wget https://ftp.postgresql.org/pub/source/v15.1/postgresql-15.1.tar.gz && tar -xzf postgresql-15.1.tar.gz
sudo apt update
sudo apt install build-essential
sudo apt install libreadline-dev
sudo apt-get install zlib1g zlib1g-dev …
```
> fix: bump pg_dump version to 15.1

- plugin/vcs/github/github_test.go
- plugin/vcs/gitlab/gitlab_test.go
Ref: https://github.com/bytebase/bytebase/pull/3411#discussion_r1024863727
> test(vcs): GetDiffFileList

- server/rollback_runner.go
- server/webhook.go
1. remove verbose logging in ticker
2. fix error returning
3. defensive programming for https://github.com/bytebase/bytebase/pull/3411#discussion_r1024842959
> fix: update

- frontend/src/utils/role.ts
> chore: update `im-integration` role

- plugin/db/driver.go
> feat: add sensitive policy struct

- resources/postgres/postgres.go
We bump the pg_dump version to 15 in #3437 and #3443, we need to reinstall them for the exist users.
> feat: reinstall PostgreSQL resources

- frontend/src/bbkit/BBTable/BBTable.vue
- frontend/src/bbkit/types.ts
- frontend/src/components/ColumnTable.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/subscription/en-US.json
- frontend/src/locales/subscription/zh-CN.json
- frontend/src/locales/zh-CN.json
- frontend/src/store/modules/policy.ts
- frontend/src/types/plan.ts
- frontend/src/types/plan.yaml
- frontend/src/types/policy.ts
- frontend/src/types/store.ts
- frontend/src/utils/role.ts
- frontend/src/views/TableDetail.vue
Part of BYT-1816
- Enterprise only
- Writable to DBAs / Workspace owners. Readable to everyone.
> feat(frontend): setting table columns' sensitive data mask policy 

- api/database.go
- plugin/parser/edit/mysql/edit.go
- plugin/parser/edit/mysql/edit_test.go
> feat: transform alter/drop table of DatabaseEdit into DDL

- api/policy.go
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/router/index.ts
- frontend/src/store/modules/policy.ts
- frontend/src/types/policy.ts
- frontend/src/types/store.ts
- frontend/src/views/SettingSidebar.vue
- frontend/src/views/SettingWorkspaceSensitiveData.vue
Part of BYT-1816
- Enterprise only
- Writable to DBAs / Workspace owners. Readable to everyone.
> feat(frontend): workspace settings for sensitive data

- plugin/parser/differ/mysql/column_test.go
- plugin/parser/differ/mysql/constraint_test.go
- plugin/parser/differ/mysql/differ.go
- plugin/parser/differ/mysql/table_test.go
- plugin/parser/differ/mysql/utils_test.go
This can provide users with better segmentation results.
> chore: write another new line at the end of the each statement

- frontend/src/components/Issue/PagedIssueTable.vue
Close BYT-1838
We changed the condition to judge if we've reached the last page.
> feat(frontend): Hide "Load more" when there is no more issues to load

- frontend/src/store/modules/issue.ts
- frontend/src/types/store.ts
- frontend/src/views/IssueDetail.vue
> feat(frontend): add loading state when creating issue

- frontend/src/components/SyncDatabaseSchemaPrepForm.vue
> chore: set max-height to code-diff block

- plugin/parser/utils.go
- plugin/parser/utils_test.go
> feat(parser): add ExtractDatabaseList function

- api/task.go
- store/task.go
Reverts bytebase/bytebase#3444
Per offline discussion, we plan to put the RollbackFromTaskID in the task payload.
> feat: Revert "feat(store): use task rollback relation in dev"

- store/migration/dev/20221115000000##task_rollback.sql
- store/migration/dev/LATEST.sql
Reverts bytebase/bytebase#3383
Per offline discussion, we plan to put the RollbackFromTaskID in the task payload.
> feat: Revert "feat(schema): add rollback_by column to table task"

- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
> chore: missing i18n wording for sensitive data feature

- plugin/parser/engine/pg/deparse.go
- plugin/parser/engine/pg/deparse_test.go
- plugin/parser/engine/pg/test-data/test_create_sequence_data.yaml
After #3484 , we need to deparse bb create sequence ast.
> feat: deparse PostgreSQL create sequence statement

- frontend/src/components/ColumnTable.vue
> fix(frontend): ColumnTable text alignment

- frontend/src/store/modules/tab.ts
While switching a tab's mode between read-only and admin mode, the query results will be inherited. That's not what we want.
See this video as an example.
https://user-images.githubusercontent.com/2749742/203481613-1a366f33-a55c-4c68-aab9-9b2b2e1eca74.mp4
So we should clear the related states while switching `tab.mode`.
> fix(sql-editor): clear states when switching tab mode

- tests/sensitive_data_test.go
- tests/tests.go
> test: add integration tests for masking sensitive columns

- server/issue.go
Fix https://github.com/bytebase/bytebase/pull/3456#discussion_r1030076019
> chore: check rollback db type

- frontend/src/components/ColumnTable.vue
- frontend/src/utils/role.ts
- frontend/src/views/SettingSidebar.vue
- frontend/src/views/SettingWorkspaceSensitiveData.vue
R = Read
W = Write
**Project level** (the database table details page)
- Project developer: R
- Project owner: R+W
- DBA: (refer to the role in the project)
- Workspace owner: R+W
**Workspace level** (the workspace settings page)
- Developer: N/A
- DBA: R
- Workspace owner: R+W
> feat(frontend): detailed permissions of sensitive data

- frontend/src/components/ColumnTable.vue
- frontend/src/utils/role.ts
- frontend/src/views/SettingSidebar.vue
R = Read
W = Write
**Project level** (the database table details page)
- Project developer: R
- Project owner: R
- DBA: R+W
- Workspace owner: R+W
**Workspace level** (the workspace settings page)
- Developer: N/A
- DBA: R+W
- Workspace owner: R+W
> feat(frontend): update permission matrix of sensitive data feature

- frontend/src/types/principal.ts
- frontend/src/views/ProfileDashboard.vue
> feat(frontend): allow editing principal email

- bin/server/cmd/profile.go
- bin/server/cmd/root.go
- plugin/app/feishu/feishu.go
- plugin/app/feishu/feishu_test.go
- server/application_runner.go
- server/config.go
- server/server.go
- tests/external_approval_test.go
- tests/fake/feishu.go
- tests/tests.go
Add integration test for feishu approval integration.
Create a fake feishu API server to mock.
Completing BYT-1792
> test: integration test for feishu approval

- frontend/src/router/index.ts
> fix(frontend): hide the Troubleshoot button

- plugin/parser/ast/alter_sequence_stmt.go
- plugin/parser/ast/drop_sequence_stmt.go
- plugin/parser/ast/sequence_def.go
- plugin/parser/engine/pg/convert.go
- plugin/parser/engine/pg/convert_test.go
- plugin/parser/engine/pg/deparse.go
- plugin/parser/engine/pg/deparse_test.go
- plugin/parser/engine/pg/test-data/test_alter_sequence_data.yaml
- plugin/parser/engine/pg/test-data/test_create_sequence_data.yaml
> feat(parser): support ALTER SEQUENCE statements

- frontend/src/router/index.ts
**Test cases**
- http://localhost:3000/auth?redirect=/issue/create-database-a1-101
- http://localhost:3000/auth?redirect=four-oh-four
- http://localhost:3000/auth
> feat(frontend): handle redirect param when already logged in

- api/database.go
- plugin/parser/edit/mysql/edit.go
- plugin/parser/edit/mysql/edit_test.go
Support rename table in mysql edit plugin.
> feat: support rename table

- .github/workflows/update-render-staging-service.yml
We need staging14 to smoke test that our release is compatible with PG 14 as the meta store
> chore: add step to update staging14.bytebase.com using pg 14

- frontend/src/types/UIEditor.ts
- frontend/src/utils/UIEditor/diffColumn.test.ts
- frontend/src/utils/UIEditor/diffColumn.ts
- frontend/src/utils/UIEditor/diffTable.test.ts
- frontend/src/utils/UIEditor/diffTable.ts
- frontend/src/utils/UIEditor/transform.ts
This PR is the related frontend changes to #3518 and #3521.
> chore: update diff for tables and columns

- frontend/src/types/common.ts
- frontend/src/types/policy.ts
> feat(frontend): type definitions for access control policy

- server/database.go
Remove getConnectionConfig and just inline the code. To be consistent with tryGetReadOnlyDatabaseDriver
> refactor: cleanup getAdminDatabaseDriver

- server/deploy.go
- server/deploy_test.go
- server/issue.go
This will allow us to merge deployment matrices.
> refactor: getDatabaseMatrixFromDeploymentSchedule should include empty stage

- server/task.go
We allow approver to force mark the task as done.
> chore: allow any task status transition to done

- frontend/src/views/sql-editor/EditorHeader.vue
> feat(sql-editor): missing branding in SQL Editor

- frontend/src/components/OnboardingGuides/CreateDatabaseGuide.vue
> fix: stuck in the onboarding guide

- frontend/src/composables/useExecuteSQL.ts
- frontend/src/types/index.ts
- frontend/src/types/sql.ts
- frontend/src/types/sqlAdvice.ts
- frontend/src/types/sqlAdviceCode.ts
> feat(sql-editor): mute "sql review policy not found" warnings since they are too annoying

- frontend/src/components/Issue/StatusTransitionForm.vue
My fault. Sry for this, guys.
#3551
> fix(frontend): something missing in 3551

- frontend/src/views/sql-editor/TerminalPanel/TerminalPanel.vue
> fix(sql-editor): clear retained dirty status

- frontend/src/views/sql-editor/TerminalPanel/TerminalPanel.vue
> fix(sql-editor): disable editing while executing SQL

- frontend/src/composables/useExecuteSQL.ts
- server/sql.go
The current warning in SQL editor is a bit annoying.
> chore: remove SQL review policy not configured from backend

- frontend/src/components/Issue/IssueStatusTransitionButtonGroup.vue
- frontend/src/components/Issue/StatusTransitionForm.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
Close BYT-1886
- Improved modal dialog title wording.
- Show the task list to be approved (scroll when there are too many).
- Show the task count on the button.
- Merge similar tasks into one item.
> feat(frontend): more detailed information while approving current stage 

- frontend/src/views/sql-editor/EditorCommon/EditorAction.vue
- frontend/src/views/sql-editor/TerminalPanel/TerminalPanel.vue
- Remove the split lines in admin mode.
- Remove the [save] and [share] buttons in admin mode.
> feat(sql-editor): web terminal improvements

- store/feature_flag.go
- store/feature_flag_dev.go
- store/feature_flag_prod.go
A poor man version to track ongoing features requiring schema changes to prod
> chore: add feature gate to store module to better track ongoing features

- frontend/src/components/Issue/IssueRollbackButton.vue
Close BYT-1907
Still guarded by `isDev`
> feat(frontend): enable rollback button for VCS workflow projects

- server/task_executor_database_create.go
> fix: update the statement in the payload for creating database (#3578)

- docs/life-of-a-feature.md
Followup https://github.com/bytebase/bytebase/pull/3575
> docs: add how to use feature flag for backend

- tests/fake/docs.go
- tests/fake/fake.go
- tests/fake/feishu.go
- tests/fake/github.go
- tests/fake/gitlab.go
Remove echo banner to reduce noise
> refactor: unify how we create echo server in test

- frontend/src/components/SyncDatabaseSchemaPrepForm.vue
> chore: remove sync schema guard for pg (#3586)

- frontend/src/views/sql-editor/TerminalPanel/CompactSQLEditor.vue
> feat(sql-editor): trigger run when pressing Enter key (cherry-pick #3590)

- frontend/src/components/DatabaseListSidePanel.vue
- frontend/src/components/DeploymentConfigTool/DeploymentMatrix.vue
> feat(frontend): tenant ui improvement (cherry-pick #3591)

- helm-charts/helm_test.go
> test: add a unit test to test our artifact metadata exists

- .github/workflows/update-render-staging-service.yml
> chore: using matrix in update staging service action

- frontend/src/components/SyncDatabaseSchemaPrepForm.vue
> fix: database migration history(#3585, #3597)

- tests/sync_schema_test.go
- tests/tests.go
> test(sync_schema): add sync schema integration test

- plugin/parser/edit/mysql/edit.go
- plugin/parser/edit/mysql/edit_test.go
> feat: transform column type string to FieldType

- frontend/src/views/SettingWorkspaceDebugLog.vue
> chore: sort debug logs in creation DESC order

- frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue
| before | after | 
| - | - |
| <img width="338" alt="image" src="https://user-images.githubusercontent.com/24653555/204488599-d4d63466-3d75-49f0-bc29-08e4a2eaebe6.png"> | <img width="344" alt="image" src="https://user-images.githubusercontent.com/24653555/204488658-3156ee0d-ce1d-420a-88ee-fdc36cc2008d.png"> |
> chore: update database tree scrollbar style

- frontend/src/views/sql-editor/TerminalPanel/CompactSQLEditor.vue
Thanks for the reporting from @h3n4l
> fix(web-terminal): the Enter to execute feature should not prevent default behaviors when not needed.

- frontend/src/components/InstanceForm.vue
> fix: edit RO data source replica info

- frontend/src/components/InstanceForm.vue
> fix: edit RO data source for instance (#3621)

- plugin/parser/utils.go
- plugin/parser/utils_test.go
- server/sql.go
This PR is the part of database access control.
FYI @LiuJi-Jim May need to modify the frontend.
close BYT-1617
> feat: disallow cross-database query if specify database

- frontend/src/components/AccessControl/AddRuleForm.vue
- frontend/src/components/DatabaseTable.vue
- frontend/src/components/EnvironmentForm.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/subscription/en-US.json
- frontend/src/locales/subscription/zh-CN.json
- frontend/src/locales/zh-CN.json
- frontend/src/router/index.ts
- frontend/src/types/plan.ts
- frontend/src/types/plan.yaml
- frontend/src/types/policy.ts
- frontend/src/utils/role.ts
- frontend/src/views/SettingSidebar.vue
- frontend/src/views/SettingWorkspaceAccessControl.vue
> feat(frontend): workspace settings for access control feature

- plugin/db/pg/dump.go
- plugin/db/pg/pg.go
Also don't use super user to create extension and comment on extension.
> chore: fix extension creation on AWS Aurora PG

- frontend/src/components/DatabaseTable.vue
- frontend/src/components/ProjectOverviewPanel.vue
- frontend/src/store/modules/policy.ts
- frontend/src/utils/index.ts
- frontend/src/utils/policy.ts
- frontend/src/views/DatabaseDetail.vue
> feat(frontend): disable SQL editor link button when access denied

- frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
- frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
- frontend/src/utils/UIEditor/index.ts
- frontend/src/views/DatabaseDetail.vue
> feat: update UI editor entry

- plugin/webhook/webhook.go
- server/activity_manager.go
Retry 3 times maximum if we encounter any error when sending project webhooks.
> fix: retry posting webhook

- frontend/src/components/DatabaseTable.vue
- frontend/src/components/ProjectOverviewPanel.vue
> fix(frontend): put fetchPolicyList inside <DatabaseTable>

- frontend/src/components/SyncDatabaseSchemaPrepForm.vue
> fix: filter migration history list (#3646)

- frontend/src/components/ProvideSQLEditorContext.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/store/modules/sqlEditor.ts
- frontend/src/types/sqlEditor.ts
- frontend/src/types/store.ts
- frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue
- frontend/src/views/sql-editor/SQLEditorPage.vue
> feat(sql-editor): disable databases that the current user is not allowed to access

- frontend/src/components/UIEditor/DatabaseTree.vue
- frontend/src/components/UIEditor/Panels/DatabaseEditor.vue
- frontend/src/components/UIEditor/Panels/TableEditor.vue
> chore: update table editor action button position

- api/activity.go
- frontend/src/components/Issue/IssueActivityPanel.vue
follow up of https://github.com/bytebase/bytebase/pull/3608
make this unmodifiable
> feat: disallow modify comment for approval rejected comments

- frontend/src/components/MemberAddOrInvite.vue
Cherrypick from https://github.com/bytebase/bytebase/pull/3657
> fix: fix terraform doc link (#3657)

- server/webhook.go
- tests/schema_update_test.go
Close BYT-1778
Improve the issue description via GitOps.
It would be something like
```
By VCS files:
Prod/ideo#2022110300001#data#update_eos leads.sql
Prod/ide0#2022110400001#migrate#create_bind_log.sql
Prod/ideo#2022110400002#migrate#create_privacy_call_info.sql
Prod/ide0#2022110400003#migrate#create_eos_city.sql
Prod/ideo#2022110400004#data#feos_city_add.sql
Prod/ideo#2022110400005#data#add_eos_expand_template_data.sql
```
> fix: improve issue description generated by vcs

- plugin/advisor/utils_for_tests.go
- plugin/db/clickhouse/clickhouse.go
- plugin/db/clickhouse/migrate.go
- plugin/db/driver.go
- plugin/db/mysql/mysql.go
- plugin/db/pg/pg.go
- plugin/db/snowflake/migrate.go
- plugin/db/snowflake/snowflake.go
- plugin/db/sqlite/sqlite.go
- plugin/db/util/driverutil.go
- tests/rollback_test.go
This is the first step for the feature which will return the affected rows in our SQL Editor.
> feat: return rows effected when execute sql in driver interface

- common/util.go
- server/anomaly_scanner.go
- server/backup_runner.go
- server/database.go
- server/factory/dbfactory/dbfactory.go
- server/instance.go
- server/issue.go
- server/openapi_sql.go
- server/rollback_runner.go
- server/server.go
- server/sql.go
- server/task_check_executor_database_connect.go
- server/task_check_executor_migration_schema.go
- server/task_check_executor_pitr_mysql.go
- server/task_check_executor_statement_advisor_composite.go
- server/task_executor.go
- server/task_executor_database_backup.go
- server/task_executor_database_create.go
- server/task_executor_pitr_cutover.go
- server/task_executor_pitr_restore.go
- server/task_executor_schema_update_ghost_cutover.go
- server/task_executor_schema_update_sdl.go
- server/webhook.go
Move driver util to a database driver factory.
> refactor: move driver utils to a server component dbfactory

- api/issue.go
- store/issue.go
Add `AssigneeNeedAttention` field to the `issue` API.
Will probably also add to `issueCreate` & `issuePatch` as we move further.
> feat: assignee_need_attention api

- frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
- frontend/src/components/UIEditor/DatabaseTree.vue
- frontend/src/components/UIEditor/EmptyTips.vue
- frontend/src/components/UIEditor/Panels/DatabaseEditor.vue
- frontend/src/components/UIEditor/Panels/TableEditor.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
> feat: update i18n for UI editor

- frontend/src/components/EnvironmentForm.vue
- frontend/src/components/EnvironmentForm/AssigneeGroupEditor.vue
> fix(frontend): the Revert button when editing environment didn't work

- frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
> fix(frontend): fix merge problem

- api/plan.go
* chore: collect principal name
* fix: enable the sql review ci in release
> fix: enable the sql review ci in release🔥 (#3681) - cherrypick

- api/plan.go
- common/feature_flag.go
- common/feature_flag_dev.go
- common/feature_flag_prod.go
- server/project.go
use common.FeatureFlag going forward
> refactor: consolidate feature enablement

- api/instance.go
- api/v1/instance.go
- server/instance.go
- server/openapi_instance.go
- store/instance.go
TODO: support database field in GetAdminDatabaseDriver().
> feat: add database field to instance entity for Postgres

- frontend/src/components/Issue/PipelineGhostFlow.vue
- frontend/src/components/Issue/PipelinePITRFlow.vue
- frontend/src/components/Issue/PipelineSimpleFlow.vue
- frontend/src/components/Issue/PipelineTenantFlow.vue
- frontend/src/components/Issue/StatusTransitionForm.vue
- frontend/src/components/Issue/TaskMarkAsDoneButton.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
https://user-images.githubusercontent.com/2749742/205475892-3f87f69c-65ee-4a2c-abf3-27155f4cc3a4.mp4
> feat(frontend): Allow users with high-privileged users to mark task status to DONE

- plugin/parser/edit/mysql/edit.go
> chore: update error message for column type

- frontend/src/components/SyncDatabaseSchemaPrepForm.vue
> chore: update input width in sync schema dialog

- tests/schema_update_test.go
> fix: testing assert order

- frontend/src/components/Issue/IssueSidebar.vue
- frontend/src/components/Issue/IssueTable.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/types/common.ts
- frontend/src/types/issue.ts
- Show a bell icon button for the issue creator to set the issue "need assignee's attention".
- It's also visible to the assignee if the issue is set to need the assignee's attention.
- Show the issue names in bold font in the issue list if it needs attention.
This feature is not strongly bound to IM integration. If we don't have IM integration feature or we didn't turn on it, the bell icon still works with visual effects only.
https://user-images.githubusercontent.com/2749742/205869085-52a28b7c-6101-4b66-ae9a-380a979e9f4b.mp4
> feat(frontend): set issue to need assignee attention

- plugin/db/util/driverutil_test.go
- plugin/db/util/mask_sensitive_data.go
> feat: masking sensitive field supports associated subqueries

- frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
- frontend/src/components/UIEditor/Panels/DatabaseEditor.vue
- frontend/src/utils/UIEditor/index.ts
Close BYT-1987, BYT-1996, BYT-2011, BYT-2017, BYT-2021
> fix: UI Editor test feedbacks part1

- plugin/db/util/driverutil_test.go
- plugin/db/util/mask_sensitive_data.go
> feat: masking sensitive column supports non-recursive CTE

- plugin/parser/edit/mysql/deparse.go
- plugin/parser/edit/mysql/edit_test.go
> chore: add `\n` to generated stmt

- frontend/src/components/UIEditor/DatabaseTree.vue
- frontend/src/components/UIEditor/TabsContainer.vue
- frontend/src/store/modules/UIEditor.ts
Close BYT-2028, BYT-2026, BYT-2024
> fix: database tree in UI editor

- frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
- frontend/src/plugins/pitr/index.ts
- frontend/src/utils/database.ts
- frontend/src/utils/util.ts
> fix: semver compare

- enterprise/service/license.go
- server/database.go
- server/issue.go
- server/server.go
- server/task_executor.go
- server/task_executor_data_update.go
- server/task_executor_database_backup.go
- server/task_executor_database_create.go
- server/task_executor_default.go
- server/task_executor_pitr_cutover.go
- server/task_executor_pitr_restore.go
- server/task_executor_schema_baseline.go
- server/task_executor_schema_update.go
- server/task_executor_schema_update_ghost_cutover.go
- server/task_executor_schema_update_ghost_sync.go
- server/task_executor_schema_update_sdl.go
- server/task_scheduler.go
- Moved progress update to task execution.
- Used components in task executors.
> refactor: componentize server in task executor

- frontend/src/views/SettingWorkspaceDebugLog.vue
> feat(frontend): close button on top of debug log modal

- frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
- frontend/src/components/UIEditor/DatabaseTree.vue
- frontend/src/components/UIEditor/Modals/TableNameModal.vue
- frontend/src/components/UIEditor/Panels/DatabaseEditor.vue
- frontend/src/components/UIEditor/Panels/TableEditor.vue
- frontend/src/components/UIEditor/TabsContainer.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/store/modules/UIEditor.ts
Close BYT-2009 and related BYT-1986, BYT-2029, BYT-2001, BYT-1990, BYT-1993, BYT-2014
> feat: auto-save changes in UI editor

- plugin/parser/ast/create_extension_stmt.go
- plugin/parser/ast/drop_extension_stmt.go
- plugin/parser/engine/pg/convert.go
- plugin/parser/engine/pg/convert_test.go
> feat(parser): support to parse create/drop extension statement

- frontend/src/components/CreateInstanceForm.vue
- frontend/src/components/InstanceForm.vue
- frontend/src/types/common.ts
- frontend/src/types/instance.ts
- frontend/src/types/sql.ts
> feat(frontend): add "database" field for PostgreSQL instances

- frontend/src/components/Issue/logic/TenantModeProvider.ts
Sry for the ridiculous typos lol 😂
> fix(frontend): should not show "apply to other tasks" in tenant mode

- frontend/src/bbkit/BBTabFilter.vue
- frontend/src/components/Issue/TaskCheckBar.vue
https://user-images.githubusercontent.com/2749742/206197533-61f924cd-bbb7-4bd0-9c97-57856efafa34.mp4
> fix(frontend): task check dialog overflows

- frontend/src/components/DatabaseLabels/DatabaseLabelPropItem.vue
- frontend/src/components/DatabaseLabels/DatabaseLabelProps.vue
- frontend/src/components/TransferDatabaseForm/SelectDatabaseLabel.vue
> feat(frontend): allow editing lable value even if it's in the db name template 

- plugin/parser/differ/pg/differ.go
- plugin/parser/differ/pg/test-data/test_differ_data.yaml
> feat(differ): support gin index in a simple way

- frontend/src/components/Environment/ProtectedEnvironmentIcon.vue
- frontend/src/views/sql-editor/TabList/TabItem/AdminLabel.vue
- frontend/src/views/sql-editor/TabList/TabItem/Prefix.vue
- frontend/src/views/sql-editor/TabList/TabItem/TabItem.vue
- frontend/src/views/sql-editor/TabList/TabList.vue
> feat(sql-editor): give the admin mode tabs a new style

- resources/README.md
- resources/mongoutil/mongoutil.go
- resources/mongoutil/mongoutil_test.go
- resources/mongoutil/resources_darwin_amd64.go
- resources/mongoutil/resources_darwin_arm64.go
- resources/mongoutil/resources_linux_amd64.go
This is the first step to support MongoDB in Bytebase. We use mongosh to run the command input from user.
> feat: embed mongoutil which only contains mongosh and libs

- frontend/src/components/UIEditor/Panels/TableEditor.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/types/UIEditor.ts
- frontend/src/types/common.ts
- frontend/src/utils/UIEditor/index.ts
- frontend/src/utils/UIEditor/transform.ts
- plugin/parser/edit/mysql/deparse.go
- plugin/parser/edit/mysql/edit_test.go
Close BYT-1992, BYT-2005 and related BYT-2023, BYT-1995, BYT-2010
> fix: default/nullable field table editor

- server/runner/apprun/runner.go
> feat: include issue id in feishu approval card

- plugin/parser/ast/create_function_stmt.go
- plugin/parser/ast/drop_function_stmt.go
- plugin/parser/ast/function_def.go
- plugin/parser/engine/pg/convert.go
- plugin/parser/engine/pg/convert_test.go
the function in PostgreSQL is unique by schema name, function name and IN/INOUT/VARIADIC parameters
close BYT-2034
> feat(parser): support CREATE/DROP FUNCTION statements

- frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
- frontend/src/components/Issue/IssueDetailLayout.vue
- frontend/src/components/Issue/logic/IssueLogic.ts
- frontend/src/components/Issue/logic/common.ts
- frontend/src/utils/UIEditor/validate.ts
Close BYT-2002 and related BYT-2004, BYT-2000, BYT-1991
> fix: preview issue in UI editor

- plugin/parser/ast/create_trigger_stmt.go
- plugin/parser/ast/drop_trigger_stmt.go
- plugin/parser/ast/trigger_def.go
- plugin/parser/engine/pg/convert.go
- plugin/parser/engine/pg/convert_test.go
> feat(parser): support CREATE/DROP trigger

- plugin/parser/differ/pg/differ.go
- plugin/parser/differ/pg/test-data/test_differ_data.yaml
- plugin/parser/engine/pg/deparse.go
- plugin/parser/engine/pg/deparse_test.go
- plugin/parser/engine/pg/test-data/test_trigger_data.yaml
> feat(differ): support to sync trigger

- frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
https://user-images.githubusercontent.com/24653555/206757327-c9cb44af-936f-40ef-8629-7c03b4361658.mp4
> feat: support upload sql file

- frontend/src/components/CreateInstanceForm.vue
- frontend/src/components/InstanceForm.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- server/instance.go
- Ensure the instance name is unique
- Check the data source list
> chore: add checks for instance create/update

- store/cache.go
- store/policy.go
Finding active stage is a popular usage in task scheduler. This is used to speed up task scheduler.
> chore: cache approval policy

- frontend/src/bbkit/BBContextMenuButton.vue
- frontend/src/components/Issue/IssueStatusTransitionButtonGroup.vue
> feat(frontend): Display "Approve current stage" by default when more than one task is in the stage

- frontend/src/components/Issue/PipelineSimpleFlow.vue
- frontend/src/components/Issue/PipelineTenantFlow.vue
- frontend/tailwind.config.js
Close BYT-1971
We also added a visual indicator to inform users that the list is scrollable.
https://user-images.githubusercontent.com/2749742/206952387-6a224790-8cc8-49f5-92e2-af2f06f9a287.mp4
On very wide screens (21:9)
> feat(frontend): Optimize the task list display on the issue page

- plugin/parser/ast/create_type_stmt.go
- plugin/parser/ast/data_type.go
- plugin/parser/ast/drop_type_stmt.go
- plugin/parser/ast/enum_type_def.go
- plugin/parser/engine/pg/convert.go
- plugin/parser/engine/pg/convert_test.go
> feat(parser): support PostgreSQL enum type

- frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
> chore: add beta badge for UI editor

- plugin/parser/differ/pg/differ.go
- plugin/parser/differ/pg/test-data/test_differ_data.yaml
- plugin/parser/engine/pg/deparse.go
- plugin/parser/engine/pg/deparse_test.go
- plugin/parser/engine/pg/test-data/test_type_data.yaml
> feat(diff): support to sync ENUM type

- frontend/src/bbkit/BBBetaBadge.vue
- frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
> chore: update beta badge font size

- api/task_check_run.go
- server/runner/taskrun/scheduler.go
- store/task_check_run.go
Also, some refactoring to canUpdateTaskStatement().
> chore: optimize passCheck() by reducing the number of queries

- frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
- frontend/src/components/UIEditor/Panels/DatabaseEditor.vue
- frontend/src/components/UIEditor/Panels/TableEditor.vue
Use multi-line string instead of JSON string.
Further plan: show the validation results in a dialog, like SQL Review result.
> chore: update validation message display

- server/runner/taskrun/scheduler.go
- store/task.go
Also avoid to use database ordering because that's already done by task dependency in GitOps flow.
> feat: improve task scheduling by avoiding to load all open pipelines

- frontend/src/components/ColumnTable.vue
> feat(frontend): show sensitive data feature only for mysql

- frontend/src/bbkit/BBContextMenuButton.vue
- frontend/src/components/DatabaseListSidePanel.vue
- frontend/src/components/Issue/IssueStatusTransitionButtonGroup.vue
- frontend/src/components/Issue/PipelineSimpleFlow.vue
- frontend/src/components/Issue/PipelineTenantFlow.vue
- frontend/src/components/ProjectCreate.vue
- frontend/src/composables/useScrollState.ts
- frontend/src/utils/deployment.ts
- frontend/src/views/DatabaseDetail.vue
- frontend/src/views/TableDetail.vue
Close BYT-2081, BYT-2084, BYT-2085, BYT-2088
> fix(frontend): some minor user experience fixes

- frontend/src/bbkit/BBContextMenuButton.vue
- frontend/src/components/DatabaseListSidePanel.vue
- frontend/src/components/Issue/IssueStatusTransitionButtonGroup.vue
- frontend/src/components/Issue/PipelineSimpleFlow.vue
- frontend/src/components/Issue/PipelineTenantFlow.vue
- frontend/src/components/ProjectCreate.vue
- frontend/src/composables/useScrollState.ts
- frontend/src/utils/deployment.ts
- frontend/src/views/DatabaseDetail.vue
- frontend/src/views/TableDetail.vue
* fix: fix BYT-2088, BYT-2081
* fix: fix BYT-2084
* fix: fix BYT-2085
* fix: remove comments
* chore: remove logs
* fix: update default db name template
> fix(frontend): cherry-pick #3816

- frontend/src/components/ProjectDeploymentConfigPanel.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
> chore: improve database name template wording

- frontend/src/components/ProjectDeploymentConfigPanel.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
* chore: improve database name template wording
* Update frontend/src/locales/en-US.json
Co-authored-by: Danny Xu <98006139+d-bytebase@users.noreply.github.com>
> chore: (cherrypick 3814) improve database name template wording (#3814)

- store/policy.go
> fix: allow to delete AccessControl policy

- frontend/src/components/CreateDatabasePrepForm.vue
- frontend/src/components/DatabaseDetail/CreatePITRDatabaseForm.vue
- frontend/src/components/DeploymentConfigTool/SelectorItem.vue
- frontend/src/components/Issue/IssueSidebar.vue
- frontend/src/components/TenantDatabaseTable/DatabaseMatrixItem.vue
- frontend/src/components/TransferDatabaseForm/SelectDatabaseLabel.vue
- frontend/src/utils/label.ts
* feat: hide location label
* feat: hide tenant when not needed
> feat(frontend): hide location label (cherry-pick #3822)

- store/policy.go
fix https://github.com/bytebase/bytebase/pull/3821#pullrequestreview-1214695032
> chore: update comments and error content

- store/policy.go
> fix: allow to delete AccessControl policy (cherry-pick #3821 #3826)

- frontend/src/components/ProjectCreate.vue
> feat(frontend): hide db name template while creating projects

- enterprise/api/license.go
- enterprise/service/license.go
- server/subscription.go
> chore: refresh the cache for subscription

- store/policy.go
FYI @LiuJi-Jim 
close BYT-2099
> chore: support to delete normal status database access control policy

- store/policy.go
> chore: support to delete normal status database access control policy(cherry-pick #3836)

- frontend/src/components/SchemaEditor/SchemaEditor.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
> fix: missing renaming items (#3846)(cherrypick)

- server/acl_casbin_policy_developer.csv
> chore: allow developer to sync schema

- server/sql.go
> fix: skip database access control policy check for workspace owners and DBAs

- plugin/db/clickhouse/clickhouse.go
- plugin/db/mysql/mysql.go
- plugin/db/pg/pg.go
- plugin/db/snowflake/snowflake.go
- plugin/db/sqlite/sqlite.go
* chore: ignore no affected rows error for snowflake execute
> chore: ignore no affected rows error for snowflake execute (cherrypick #3855)

- api/project.go
- api/project_test.go
- frontend/src/components/RepositorySetupWizard.vue
- server/issue.go
- server/project.go
- server/runner/taskrun/database_create_executor.go
- server/runner/taskrun/executor.go
- server/utils/utils.go
- server/utils/utils_test.go
- server/webhook.go
- tests/tenant_test.go
Regardless of database name template, all databases in the tenant project will be in the same group.
> chore: remove the group concept from tenant mode

- frontend/src/components/Issue/PipelineGhostFlow.vue
- frontend/src/components/Issue/PipelinePITRFlow.vue
- frontend/src/components/Issue/PipelineSimpleFlow.vue
- frontend/src/components/Issue/PipelineTenantFlow.vue
- frontend/src/components/Issue/TaskExtraActionsButton.vue
https://user-images.githubusercontent.com/2749742/207482232-092eaf68-8020-4467-a6fe-a9389d3f33ca.mp4
> feat(frontend): change "mark task as done" button to dropdown

- server/sql.go
close BYT-2105
* fix: skip database access control policy check for workspace owners and DBAs
* chore: fix typo
* fix: use principalID
* chore: address comments
* fix: fix build
* refactor: refactor code
* refactor: remove function
> fix: skip database access control policy check for workspace owners and DBAs (cherry-pick #3852)

- frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
> feat: only show ghost migration selector for altering table in Schema Editor

- frontend/src/components/ProvideSQLEditorContext.vue
- frontend/src/views/EnvironmentDashboard.vue
- frontend/src/views/EnvironmentDetail.vue
- frontend/src/views/sql-editor/SQLEditorPage.vue
…cy properly (#3863)
* feat: upsert environment level access-control policy
* feat: hide inaccessible databases
* chore: remove debugger
> feat(access-control): handle protected instance's access control policy properly (cherry-pick #3863)

- frontend/src/components/SyncDatabaseSchemaPrepForm.vue
> fix: unwanted error notification when selecting database

- frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
- frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
> chore: add tips for tenant project in Schema Editor

- frontend/src/components/Issue/logic/GhostModeProvider.ts
- frontend/src/components/Issue/logic/common.ts
- frontend/src/plugins/issue/logic/initialize/ghost.ts
- frontend/src/plugins/issue/logic/initialize/standard.ts
- frontend/src/plugins/issue/logic/initialize/tenant.ts
- frontend/src/types/issue.ts
> chore(frontend): deprecate database name from migration context

- frontend/src/locales/zh-CN.json
> fix(i18n): Missing Environment Name In Update Environment Notify Message

- frontend/src/store/modules/uistate.ts
* feat: set default format-on-save to false
* Update frontend/src/store/modules/uistate.ts
Co-authored-by: p0ny <p0uy@outlook.com>
Co-authored-by: Danny Xu <98006139+d-bytebase@users.noreply.github.com>
Co-authored-by: p0ny <p0uy@outlook.com>
> feat(frontend): set default format-on-save to false (cherry-pick #3893)

- frontend/src/components/ColumnTable.vue
- frontend/src/components/DatabaseOverviewPanel.vue
- frontend/src/components/IndexTable.vue
- frontend/src/components/TableTable.vue
- frontend/src/router/index.ts
- frontend/src/store/modules/dbSchema.ts
- frontend/src/utils/table.ts
- frontend/src/views/TableDetail.vue
This PR mainly change the data of table/column/index list views to db schema.
> feat: display database's table/column/index list with db schema

- frontend/src/components/AuditLog/AuditLogTable.vue
> style: not wrap in audit type badge

- server/issue.go
Did the check on the frontend, now also add it to the backend.
Close BYT-1615
> feat(backend): forbid creating new issues in the default project

- frontend/src/store/modules/activity.ts
With the help of https://github.com/bytebase/bytebase/pull/3895, we can reduce the requests made to fetch activities (by specifying all levels we need in one try).
> refactor(frontend): make use of multiple levels to reduce request count

- frontend/src/views/SettingWorkspaceSensitiveData.vue
- The `Column`, `Table`, `Database`, `Instance`, `Environment`, `Project` columns are both `flex-1`
- The `Operation` column is fixed width
- The `Updated` column is fixed width and hidden on small screens.
> feat(frontend): re-implement sensitive columns table using BBGrid

- api/activity.go
- frontend/src/components/ProjectActivityPanel.vue
- frontend/src/components/ProjectOverviewPanel.vue
- frontend/src/store/modules/activity.ts
- server/activity.go
- server/runner/taskcheck/lgtm_executor.go
- store/activity.go
> fix: revert activity related changes

- tests/backup_restore_test.go
- tests/data_source_test.go
- tests/database_edit_test.go
- tests/external_approval_test.go
- tests/ghost_test.go
- tests/project_test.go
- tests/rollback_test.go
- tests/schema_update_test.go
- tests/sensitive_data_test.go
- tests/sheet_vcs_test.go
- tests/sql_editor_test.go
- tests/sql_review_test.go
- tests/start_test.go
- tests/subscription_test.go
- tests/sync_schema_test.go
- tests/tenant_test.go
- tests/tests.go
This also fixed the test not using the right release mode.
> refactor: avoid tests using seed data

- frontend/src/locales/subscription/en-US.json
- frontend/src/locales/subscription/zh-CN.json
- frontend/src/types/plan.yaml
Add the `Terraform Provider` feature. Close BYT-2060
> chore: update pricing page

- api/activity.go
- frontend/src/components/ProjectActivityPanel.vue
- frontend/src/components/ProjectOverviewPanel.vue
- frontend/src/store/modules/activity.ts
- server/activity.go
- server/runner/taskcheck/lgtm_executor.go
- store/activity.go
This reverts https://github.com/bytebase/bytebase/pull/3917.
> feat: roll forward activity related changes

- server/runner/taskrun/scheduler.go
- store/task.go
> fix: Revert "feat: improve task scheduling by avoiding to load all open pipelines (#3812)" (#3935)"

- frontend/src/components/DatabaseOverviewPanel.vue
- frontend/src/components/TableTable.vue
- frontend/src/components/ViewTable.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/router/index.ts
- frontend/src/store/modules/dbSchema.ts
- frontend/src/views/TableDetail.vue
> fix: show schema name for postgres tables

- api/task.go
- frontend/src/components/Issue/IssueTaskStatementPanel.vue
- frontend/src/components/Issue/logic/GhostModeProvider.ts
- frontend/src/components/Issue/logic/IssueLogic.ts
- frontend/src/components/Issue/logic/TenantModeProvider.ts
- frontend/src/components/Issue/logic/common.ts
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/types/common.ts
- frontend/src/types/issue.ts
- frontend/src/types/pipeline/task.ts
> feat: support upload large size sql file with sheet

- plugin/advisor/mysql/advisor_index_key_number_limit.go
wrap the indexList's additem procedure into a func,  make the code more concise and easier to read
> refactor: refactor /plugin/advisor/mysql/advisor_index_key_number_limit

- frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
- frontend/src/components/SchemaEditor/DatabaseTree.vue
- frontend/src/components/SchemaEditor/Modals/TableNameModal.vue
- frontend/src/components/SchemaEditor/Panels/DatabaseEditor.vue
- frontend/src/components/SchemaEditor/Panels/TableEditor.vue
- frontend/src/components/SchemaEditor/TabsContainer.vue
- frontend/src/store/modules/schemaEditor.ts
- frontend/src/types/schemaEditor/index.ts
- frontend/src/utils/schemaEditor/transform.ts
Update schema editor store definition with https://github.com/bytebase/bytebase/pull/3942
> chore: update schema editor store

- frontend/src/components/SchemaDiagram/Canvas/Canvas.vue
- frontend/src/components/SchemaDiagram/Canvas/libs/fitView.ts
- frontend/src/components/SchemaDiagram/ER/TableNode.vue
- frontend/src/components/SchemaDiagram/SchemaDiagram.vue
- frontend/src/components/SchemaDiagram/common/geometry.ts
- frontend/src/components/SchemaDiagram/common/index.ts
- frontend/src/components/SchemaDiagram/types/context.ts
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
Close BYT-2152
https://user-images.githubusercontent.com/2749742/208846555-13a0d055-2e35-466a-9e28-48ec81fe3e3d.mp4
> feat(schema-diagram): fit content within view

- frontend/src/components/Issue/IssueTaskStatementPanel.vue
- frontend/src/store/modules/sheet.ts
- frontend/src/types/sheet.ts
- server/sheet.go
Backend changes: https://github.com/bytebase/bytebase/pull/3953
> chore: set readonly for incomplete sheet

- frontend/src/components/AuditLog/PagedAuditLogTable.vue
- frontend/src/components/PagedActivityTable.vue
- frontend/src/components/ProjectActivityPanel.vue
- frontend/src/components/ProjectOverviewPanel.vue
- frontend/src/store/modules/activity.ts
- frontend/src/store/modules/auditLog.ts
- frontend/src/types/activity.ts
- frontend/src/views/SettingWorkspaceAuditLog.vue
https://user-images.githubusercontent.com/56376387/208867933-d75c57b4-c28e-4ae0-8b29-61611dbd68a4.mp4
https://user-images.githubusercontent.com/56376387/208867943-1ad27b29-7d33-4984-81c5-775899f2c753.mp4
> feat(frontend): pagination for project activities and audit logs

- frontend/src/store/modules/activity.ts
> fix(frontend): use a separate request to get activities of issue

- frontend/src/plugins/issue/logic/initialize/index.ts
- frontend/src/views/IssueDetail.vue
> fix(frontend): reactivity of issue entity

- frontend/src/views/SettingSidebar.vue
co-locate with other security related items.
> chore: move audit log setting item

- server/runner/taskrun/scheduler.go
- server/task.go
We allow marking PendingApproval & Failed tasks as Done
> fix: check task status when marking as done

- plugin/db/util/driverutil.go
https://github.com/snowflakedb/gosnowflake/blob/0450f0b16a4679b216baecd3fd6cdce739dbb683/connection.go#L166
> fix: disallow readonly mode for snowflake driver

- frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
When
- Tenant mode
- DDL
- Exactly one database in the pipeline
We will downgrade to normal pipeline rather than tenant pipeline. But we've missed the databaseList parameter in this case.
> fix(frontend): missing databaseList parameters in new issue URL

- frontend/src/components/AuditLog/AuditLogTable.vue
- frontend/src/views/SettingWorkspaceAuditLog.vue
> feat(frontend): reorder audit log table columns and detail fields

- store/task.go
Use [subscripts](https://www.postgresql.org/docs/14/datatype-json.html#JSONB-SUBSCRIPTING) to visit JSONB property is not supported until PostgreSQL 14.
This PR changes to a more compatible SQL, at least down to PostgreSQL 11.
ref
https://dba.stackexchange.com/questions/295298/how-to-update-a-property-value-of-a-jsonb-field
> chore: use compatible sql for jsonb update

- plugin/db/pg/sync.go
- tests/syncer_test.go
The same as #3968 but for PostgreSQL
> feat: support to get PostgreSQL foreign key metadata

- frontend/src/components/AuditLog/AuditLogTable.vue
> style: highlight audit log level instead of type

- frontend/src/views/SettingWorkspaceAuditLog.vue
https://user-images.githubusercontent.com/56376387/209289734-a19956dd-9d3a-4867-a196-675ee4c070a4.mp4
> feat(frontend): audit log creator select

- api/project.go
- api/v1/instance.go
- server/acl_casbin_policy_dba.csv
- server/acl_casbin_policy_owner.csv
- server/openapi_instance.go
- store/project.go
curl 'http://localhost:3000/v1/auth/login' \
--data-raw '{"email":"d@bytebase.com","password":"d"}' \
-X POST
curl 'http://localhost:3000/v1/instance/NewInstance/database/db0' \
-H 'Authorization: bearer eyJhbGciOiJIUzI1NiIsImtpZCI6InYxIiwidHlwIjoiSldUIn0.eyJuYW1lIjoiRCIsImlzcyI6ImJ5dGViYXNlIiwic3ViIjoiMTAxIiwiYXVkIjpbImJiLnVzZXIuYWNjZXNzLmRldiJdLCJleHAiOjE2NzE3ODczNTYsImlhdCI6MTY3MTc4MDE1Nn0.N0mLAMjVUuIT5I7Y1FutgO8UjbOlMVOGdZjLlWTDT_Y' \
--data-raw '{"project":"h1"}' \
-X PATCH
> feat: add instance database patch API for updating its project

- server/runner/taskrun/scheduler.go
> fix: condition

- plugin/db/pg/role.go
- server/openapi_instance.go
- fix: add connection_limit and valid_until validation for role
- fix: role attribute update
Close BYT-2202, BYT-2200, BYT-2199
> fix: add validation for role

- frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
- frontend/src/components/SchemaEditor/Modals/EditColumnForeignKeyModal.vue
- frontend/src/components/SchemaEditor/Panels/TableEditor.vue
- frontend/src/components/SchemaEditor/utils/table.ts
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/store/modules/schemaEditor.ts
- frontend/src/types/schemaEditor/atomType.ts
- frontend/src/types/schemaEditor/index.ts
- frontend/src/types/store.ts
- frontend/src/utils/schemaEditor/diffSchema.ts
- frontend/src/utils/schemaEditor/index.ts
- frontend/src/utils/schemaEditor/transform.ts
https://user-images.githubusercontent.com/24653555/209462626-7e0ab852-bf11-4c73-90e0-3c8078fb2b0d.mp4
related backend changes #4015
> feat(schema-editor): support to edit foreign key

- frontend/src/components/SchemaEditor/Modals/TableNameModal.vue
- frontend/src/components/SchemaEditor/Panels/TableEditor.vue
- frontend/src/components/SchemaEditor/utils/table.ts
- frontend/src/utils/schemaEditor/diffSchema.ts
- plugin/parser/edit/mysql/deparse.go
- plugin/parser/edit/mysql/deparse_test.go
Including:
* auto set nullable to false when setting PK, and disable nullable checkbox when column is PK;
* fix rename and alter table order in generated DDL;
* sync fk's reference table name when renaming table.
> chore: update table editor for pk/fk

- frontend/src/views/auth/Signup.vue
- server/principal.go
> chore: user email to lower case

- plugin/db/mongodb/mongodb.go
> feat(mongodb): support mongodb query

- frontend/src/bbkit/BBSelect.vue
- frontend/src/components/AuditLog/TypeSelect.vue
- frontend/src/components/DeploymentConfigTool/ResponsiveTags.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/views/SettingWorkspaceAuditLog.vue
Extend `BBSelect` to support multiple selections.
https://user-images.githubusercontent.com/56376387/209522914-d6cafa2e-69cb-4542-9cca-d8e630f4299f.mp4
> feat(frontend): filter multiple audit types

- frontend/src/components/Issue/IssueTaskStatementPanel.vue
- frontend/src/components/Issue/logic/GhostModeProvider.ts
- frontend/src/components/Issue/logic/IssueLogic.ts
- frontend/src/components/Issue/logic/base.ts
> fix: apply task create state to others (#4032)

- frontend/src/bbkit/BBContextMenuButton.vue
- frontend/src/components/Issue/IssueTaskStatementPanel.vue
https://user-images.githubusercontent.com/24653555/209562540-9fabf236-a0ab-488d-b4d3-1167f36d7c20.mp4
> chore: update issue upload sql button style

- frontend/src/bbkit/BBContextMenuButton.vue
- frontend/src/components/Issue/IssueTaskStatementPanel.vue
> chore: update issue upload sql button style (#4038)

- frontend/src/components/Issue/IssueTaskStatementPanel.vue
> chore: update `apply task to others` button style

- plugin/parser/engine/pg/deparse.go
- plugin/parser/engine/pg/test-data/test_create_table_data.yaml
It's for PostgreSQL schema editor
> feat: deparse table constraints

- plugin/parser/engine/pg/deparse.go
- plugin/parser/engine/pg/test-data/test_alter_table_data.yaml
It's for PostgreSQL schema editor
> feat: deparse RENAME TABLE statements

- frontend/src/components/Issue/IssueTaskStatementPanel.vue
> chore: update apply task to others button style (#4041)

- plugin/parser/engine/pg/deparse.go
- plugin/parser/engine/pg/test-data/test_alter_table_data.yaml
It's for PostgreSQL schema editor
> feat: deparse rename column statements

- api/data_source.go
- api/v1/data_source.go
- server/component/dbfactory/dbfactory.go
- server/database.go
- server/instance.go
- server/openapi_instance.go
- store/data_source.go
- store/instance.go
- store/migration/dev/LATEST.sql
- store/migration/prod/1.10/0005##data_source.sql
- store/migration/prod/LATEST.sql
- store/pg_engine_test.go
- tests/data_source_test.go
Moving host/port/database to data source table. Remove "override" from host/port fields.
> chore: data source schema refactoring

- api/data_source.go
- api/instance.go
- api/v1/data_source.go
- frontend/src/components/InstanceForm.vue
- frontend/src/types/dataSource.ts
- frontend/src/types/instance.ts
- server/instance.go
- tests/data_source_test.go
related backend PR: https://github.com/bytebase/bytebase/pull/4053
> chore: update data source definition in frontend

- api/database.go
- plugin/parser/edit/mysql/deparse.go
- plugin/parser/edit/mysql/edit.go
- plugin/parser/edit/pg/deparse.go
- plugin/parser/edit/pg/deparse_test.go
- plugin/parser/edit/pg/edit.go
- plugin/parser/edit/pg/validate.go
- plugin/parser/edit/pg/validate_test.go
- server/server.go
> feat(schema-editor): deparse `DatabaseEdit` to DDL statement for postgres

- api/data_source.go
- api/instance.go
- api/v1/data_source.go
- frontend/src/components/InstanceForm.vue
- frontend/src/types/dataSource.ts
- frontend/src/types/instance.ts
- server/instance.go
- tests/data_source_test.go
> chore: update data source definition (#4057)(#4061) 

- frontend/src/components/InstanceEngineIcon.vue
- frontend/src/components/Issue/IssueTaskStatementPanel.vue
- frontend/src/components/MonacoEditor/MonacoEditor.vue
- frontend/src/components/MonacoEditor/useMonaco.ts
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/types/sqlEditor.ts
- frontend/src/utils/instance.ts
- frontend/src/views/sql-editor/EditorPanel/SQLEditor.vue
- frontend/src/views/sql-editor/SQLEditorPage.vue
- frontend/src/views/sql-editor/TerminalPanel/CompactSQLEditor.vue
> chore: cherry-pick feat(frontend): better MongoDB support while using MonacoEditor #4052

- plugin/db/mongodb/sync.go
See more detail in [linear issue 2230](https://linear.app/bytebase/issue/BYT-2230/mongodb-connect-to-atlas-m0m2m5).
> fix: privilege issue for atlas M0/M2/M5

- resources/mongoutil/mongoutil.go
- resources/mysqlutil/mysqlutil.go
- resources/postgres/postgres.go
It takes a while and people thought it was stuck and would restart it
> chore: add installing utility log

- frontend/src/bbkit/BBContextMenuButton.vue
> fix: `BBContextMenuButton` style

- frontend/src/components/Issue/IssueActivityPanel.vue
- frontend/src/components/Issue/activity/ActionSentence.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/types/activity.ts
- frontend/src/types/pipeline/stage.ts
- frontend/src/types/projectWebhook.ts
- server/component/activity/manager.go
- server/runner/taskrun/scheduler.go
> chore: cherry-pick feat(frontend): stage status change activity #4042

- plugin/db/mongodb/migrate.go
- plugin/db/mongodb/sync.go
- plugin/db/util/driverutil.go
- plugin/db/util/driverutil_test.go
* chore: update data source definition (#4057)
* fix: patch data source in instance detail page (#4061)
* fix: patch data source in instance detail page
> chore: cherry-pick #4072 #4075

- frontend/src/bbkit/BBContextMenuButton.vue
> fix: `BBContextMenuButton` style (#4078)

- frontend/src/views/sql-editor/EditorHeader.vue
https://user-images.githubusercontent.com/56376387/209903231-62575d91-fbc9-4d3a-9d96-210633e85c89.mp4
> feat: audit log tab in SQL Editor

- frontend/src/components/Issue/TaskCheckBar.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
> feat(frontend): add a label to task check bar

- frontend/src/router/index.ts
- frontend/src/views/DatabaseDetail.vue
> chore: skip db schema cache in database detail page (#4080)

- frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
- server/issue.go
> feat(mongodb): forbid user run non-data migration for MongoDB database

- plugin/db/clickhouse/clickhouse.go
> fix(clickhouse): using empty tls config instead of nil

- frontend/src/components/CreateDataSourceExample.vue
> chore: add connection info for mongodb

- frontend/src/views/sql-editor/AsidePanel/TableSchema.vue
> feat(frontend): indicate that the row count is estimated

- frontend/src/components/CreateInstanceForm.vue
- frontend/src/components/InstanceForm.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
We don't require instance name to be unique anymore. We use resource id now.
> fix(frontend): instance name description

- api/database.go
- frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
- frontend/src/components/SchemaEditor/DatabaseTree.vue
- frontend/src/components/SchemaEditor/Modals/EditColumnForeignKeyModal.vue
- frontend/src/components/SchemaEditor/Modals/SchemaNameModal.vue
- frontend/src/components/SchemaEditor/Panels/DatabaseEditor.vue
- frontend/src/components/SchemaEditor/Panels/TableEditor.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/store/modules/schemaEditor.ts
- frontend/src/types/schemaEditor/index.ts
- frontend/src/utils/schemaEditor/diffColumn.test.ts
- frontend/src/utils/schemaEditor/diffColumn.ts
- frontend/src/utils/schemaEditor/diffSchema.ts
- frontend/src/utils/schemaEditor/index.ts
- frontend/src/utils/schemaEditor/transform.ts
- plugin/parser/edit/pg/deparse.go
- plugin/parser/edit/pg/deparse_test.go
https://user-images.githubusercontent.com/24653555/210053349-b619e994-663e-4a91-a818-c80297ca21d1.mp4
> feat(schema-editor): support PostgreSQL database

- frontend/src/components/AlterSchemaPrepForm/ProjectStandardView.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
Close BYT-2235
https://user-images.githubusercontent.com/2749742/210313792-100608ac-95c0-4ad3-b794-52d2e82adff5.mp4
> feat(frontend): foldable database list for multi-stage issue creation

- store/instance.go
Need to insert empty host and port value
> fix: create instance

- frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
- frontend/src/components/SchemaEditor/DatabaseTree.vue
- frontend/src/components/SchemaEditor/Panels/DatabaseEditor.vue
- frontend/src/components/SchemaEditor/Panels/TableEditor.vue
- frontend/src/store/modules/schemaEditor.ts
- frontend/src/types/schemaEditor/atomType.ts
- frontend/src/types/schemaEditor/index.ts
Close BYT-2228, BYT-2205 and BYT-2015
> chore: update table editor

- plugin/parser/ast/rename_schema_stmt.go
- plugin/parser/engine/pg/convert.go
- plugin/parser/engine/pg/convert_test.go
- plugin/parser/engine/pg/deparse.go
- plugin/parser/engine/pg/deparse_test.go
- plugin/parser/engine/pg/test-data/test_rename_schema_data.yaml
It's for schema editor
FYI @boojack
> feat(parser): support RENAME SCHEMA statements

- frontend/src/views/SettingWorkspaceAccessControl.vue
> fix(frontend): wait for the delete request before re-fetching the list

- frontend/src/views/SettingWorkspaceSensitiveData.vue
> feat(frontend): link to database detail page

- frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
- frontend/src/components/SchemaEditor/DatabaseTree.vue
- frontend/src/components/SchemaEditor/Modals/EditColumnForeignKeyModal.vue
- frontend/src/components/SchemaEditor/Modals/SchemaNameModal.vue
- frontend/src/components/SchemaEditor/Modals/TableNameModal.vue
- frontend/src/components/SchemaEditor/Panels/DatabaseEditor.vue
- frontend/src/components/SchemaEditor/Panels/TableEditor.vue
- frontend/src/components/SchemaEditor/TabsContainer.vue
- frontend/src/components/SchemaEditor/utils/schema.ts
- frontend/src/components/SchemaEditor/utils/table.ts
- frontend/src/components/SchemaEditor/utils/useMetadataForDiagram.ts
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/store/modules/schemaEditor.ts
- frontend/src/types/schemaEditor/atomType.ts
- frontend/src/types/schemaEditor/index.ts
- frontend/src/utils/schemaEditor/diffSchema.ts
- plugin/parser/edit/pg/deparse.go
- plugin/parser/edit/pg/deparse_test.go
* add uuid to schema type
* support rename/drop schema in UI
https://user-images.githubusercontent.com/24653555/210530668-65d3c3b9-1dda-4dd0-9cbe-280505a6b462.mp4
> feat(schema-editor): support rename/drop schema for pg

- frontend/src/components/SchemaDiagram/ER/ForeignKeyLine.vue
- frontend/src/components/SchemaDiagram/ER/libs/SVGLine.vue
> feat(schema-diagram): add an arrow for foreign key lines to indicate "to-many" relationship

- server/api/v1/environment_service.go
- store/environment.go
- store/instance.go
- fix: nil pointer for env
- fix: missing tier in creation
> fix: nil pointer for env

- frontend/src/components/TableTable.vue
> chore: update `TableTable` field list for PostgreSQL

- frontend/src/views/TableDetail.vue
> chore: hide `ColumnTable` for MongoDB

- frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
- frontend/src/components/SchemaEditor/Modals/TableNameModal.vue
- frontend/src/components/SchemaEditor/Panels/DatabaseEditor.vue
- frontend/src/utils/schemaEditor/diffSchema.ts
- plugin/parser/edit/pg/deparse.go
- plugin/parser/edit/pg/deparse_test.go
* merge diff results with same database id;
* add `CASCADE` into drop schema stmt.
> chore: update diff schema functions

- frontend/src/components/PricingTable/PricingTable.vue
- frontend/src/components/PricingTable/types.ts
> chore: update pricing for enterprise

- frontend/src/components/CreateInstanceForm.vue
- frontend/src/components/InstanceForm.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
> chore(mongodb): using radio button group to show srv option

- api/project_member.go
- api/slug.go
- server/api/v1/project_service.go
- server/database.go
- server/issue.go
- server/project.go
- server/project_member.go
- server/project_webhook.go
- server/runner/taskrun/database_create_executor.go
- server/runner/taskrun/executor.go
- server/sheet.go
- server/sql.go
Separating store and API messages and less composition.
> refactor: migrate internal project usage to store.ProjectMessage

- frontend/src/components/DatabaseOverviewPanel.vue
> fix: use computed params in database overview page

- frontend/src/components/SchemaDiagram/ER/TableNode.vue
> chore(schema-diagram): render long schema and table names

- frontend/src/plugins/issue/logic/initialize/helper.ts
> fix(frontend): default SQL statement for establish baseline task

- plugin/db/ssl.go
After this PR, we can connect the TiDB Cloud Serverless
> chore(ssl): add intermediates cert

- frontend/src/utils/util.ts
> chore: add comment about using semverCompare to handle the database pseudo semantic version

- server/server.go
- server/sql.go
- store/activity.go
- store/stats.go
Also removed activity backfill as it's done.
> chore: add commits

- frontend/src/components/FeatureAttention.vue
- frontend/src/components/FeatureModal.vue
- frontend/src/components/TrialModal.vue
Users will directly trial the enterprise plan
> chore: enterprise plan trial

- frontend/src/router/index.ts
- frontend/src/store/modules/instance.ts
- frontend/src/types/id.ts
- frontend/src/utils/slug.ts
- frontend/src/views/MigrationHistoryDetail.vue
Following #4197 , change migrationHistoryId type to string on the frontend.
> feat(frontend): change migrationHistoryId to string

- plugin/db/spanner/statement_parser.go
- plugin/db/spanner/statement_parser_test.go
> fix: filter out empty sql

- frontend/src/views/SheetDashboard.vue
> fix: remove sync sheet from vcs release guard

- frontend/src/components/SchemaEditor/DatabaseTree.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
> chore: update fetch schema failed handler

- frontend/src/components/Issue/IssueTaskStatementPanel.vue
> chore: update save button disabled style

- frontend/src/components/SchemaEditor/Panels/TableEditor.vue
- frontend/src/components/SchemaEditor/utils/column.ts
> feat(schema-editor): highlight changed column

- frontend/src/views/sql-editor/AsidePanel/AsidePanel.vue
- frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue
- frontend/src/views/sql-editor/AsidePanel/TreeNode/InstancePrefix.vue
- frontend/src/views/sql-editor/AsidePanel/TreeNode/Prefix.vue
- frontend/src/views/sql-editor/AsidePanel/TreeNode/Suffix.vue
- frontend/src/views/sql-editor/TabList/TabItem/AdminLabel.vue
- frontend/src/views/sql-editor/TabList/TabList.vue
* feat: add parentheses around env names
* feat: tuning style
* feat: show instances view only for high-privileged users (BYT-2281)
* chore: tuning styles BYT-2289
* chore: change icon (BYT-2287)
* feat: close table schema panel when needed (BYT-2291)
* chore: make the tree not selectable (BYT-2280)
* fix: wrap issue (BYT-2279)
* chore: remove gradient shadows (BYT-2282)
* fix: more precise css selector
> feat(sql-editor): some minor improvements and fixes (cherry-pick #4228)

- frontend/src/components/SchemaEditor/DatabaseTree.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
> chore: update fetch schema failed handler (#4231)

- frontend/src/components/Issue/IssueTaskStatementPanel.vue
> chore: update save button disabled style (#4229)

- plugin/db/pg/dump.go
- plugin/db/pg/pg.go
- server/issue.go
> fix: allow postgres user name with hyphen

- frontend/src/components/ProvideSQLEditorContext.vue
> chore(sql-editor): hide unassigned databases

- frontend/src/components/CreateDataSourceExample.vue
- frontend/src/components/CreateInstanceForm.vue
- frontend/src/components/InstanceForm.vue
- Add a red asterisk for mandatory fields, i.e., credentials & database
- Hide CreateDataSourceExample for spanner
> feat: spanner instance creation ui minr improvements

- frontend/src/components/SchemaEditor/Panels/TableEditor.vue
- frontend/src/components/SchemaEditor/utils/column.ts
> feat(schema-editor): highlight changed column (#4234)

- frontend/src/store/modules/instance.ts
> fix(frontend): get migration history id from data

- frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
> fix(mongodb): don't filter the mongodb database out if trigger by change data

- frontend/src/views/SettingWorkspaceSensitiveData.vue
> feat(frontend): make the entire row of sensitive data list clickable

- frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
- frontend/src/views/DatabaseDetail.vue
> fix(mongodb): hide alter schema button for MongoDB instance in database detail page

- frontend/src/components/CreateInstanceForm.vue
- frontend/src/components/InstanceForm.vue
- plugin/db/pg/pg.go
* feat(db): support PostgreSQL SSL connection
* chore: deal with error
> feat(db): support PostgreSQL SSL connection (cherry-pick #4261)

- frontend/src/components/CreateInstanceForm.vue
> chore: remove frontend spanner release guard

- frontend/src/components/CreateInstanceForm.vue
/cherry-pick-me
add beta badge for mongo & spanner on instance creation.
screenshots:
> feat(frontend): beta badge for mongo & spanner

- frontend/src/bbkit/BBModal.vue
- frontend/src/views/DatabaseDetail.vue
FYI @RainbowDashy 
**Before**
**After**
> fix(frontend): <BBModal> scrollbar

- store/migration/prod/1.10/0002##resource_id.sql
> chore: change the uuid generation to be compatible with older version of postgres (#4274)

- frontend/src/components/CreateInstanceForm.vue
> fix: adjust instance type logo grid

- store/project.go
Fix https://github.com/bytebase/bytebase/pull/4170/files#r1068930812
> fix: patch project type conversion

- plugin/db/pg/sync.go
> fix: sync empty schema

- server/api/v1/project_service.go
- store/project_member.go
Data in PostgreSQL:
For VCS:
Close `Sync From VCS`:
> feat(api): implement get project IAM policy

- plugin/db/snowflake/sync.go
> fix: sync empty schema for snowflake

- plugin/db/mongodb/migrate.go
* fix(mongodb): hide alter schema button for MongoDB instance in database detail page (#4258)
* fix(mongodb): don't filter the mongodb database out if trigger by change data (#4257)
> chore: cherry-pick #4299

- frontend/src/store/modules/tab.ts
- frontend/src/utils/tab.ts
- frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue
- frontend/src/views/sql-editor/EditorCommon/AdminModeButton.vue
- frontend/src/views/sql-editor/EditorCommon/SaveSheetModal.vue
> feat(sql-editor): use database or instance name as the default sheet name

- frontend/src/components/SQLReview/SQLReviewPreview.vue
- frontend/src/components/SQLReview/components/SQLReviewSidebar.vue
- frontend/src/components/SQLReview/components/SQLRuleLevelBadge.vue
- frontend/src/components/SQLReview/components/SQLRuleLevelSummary.vue
- frontend/src/views/SettingWorkspaceSQLReviewDetail.vue
> feat(frontend): display the number of sql review rules

- frontend/src/components/CreateInstanceForm.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
Add descriptions and links to our docs for spanner instance creation.
> chore: add description for spanner instance creation

- frontend/src/bbkit/BBTable/BBTable.vue
- frontend/src/components/MemberTable.vue
- frontend/src/views/SettingWorkspaceMember.vue
Close BYT-1905
- Add numbers to show the count of each role.
- Add searchboxes.
> feat(frontend): member management UI improvement

- plugin/parser/differ/pg/differ.go
- plugin/parser/differ/pg/test-data/test_differ_constraint.yaml
- plugin/parser/differ/pg/test-data/test_differ_data.yaml
- plugin/parser/differ/pg/test-data/test_differ_merge.yaml
- plugin/parser/differ/pg/test-data/test_differ_schema.yaml
- plugin/parser/differ/pg/test-data/test_differ_sequence.yaml
- tests/sync_schema_test.go
> chore(differ): add the empty line between differ statements

- frontend/src/types/connectionTree.ts
- frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue
- frontend/src/views/sql-editor/AsidePanel/TableSchema.vue
> feat(sql-editor): show schema names for tables in PostgreSQL

- api/plan.go
- frontend/src/types/plan.ts
- frontend/src/types/plan.yaml
- frontend/src/types/sqlReview.ts
> chore: enable sql review policy for all plans

- frontend/src/views/sql-editor/EditorCommon/DataTable.vue
> fix(sql-editor): handle empty column name

- frontend/src/components/ProjectWebhookCard.vue
> chore: remove updater for project webhook (#4321)

- common/error.go
- server/runner/taskcheck/statement_type_executor.go
- server/runner/taskcheck/statement_type_executor_test.go
> chore: disallow CREATE/DROP DATABASE statements in task

- plugin/db/pg/dump.go
- tests/schema_update_test.go
* fix: use reader instead of scanner to fix "bufio.Scanner: token too long"
* fix: address comments
* chore: fix tests and address comments
* chore: fix test
* refactor: use func
> fix: use reader instead of scanner to fix "bufio.Scanner: token too long" (cherry-pick #4323)

- frontend/index.html
- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/components/SchemaDiagram/Canvas/Canvas.vue
- frontend/src/components/SchemaDiagram/Canvas/DummyCanvas.vue
- frontend/src/components/SchemaDiagram/ER/TableNode.vue
- frontend/src/components/SchemaDiagram/SchemaDiagram.vue
- frontend/src/components/SchemaDiagram/common/geometry.ts
- frontend/src/components/SchemaDiagram/types/context.ts
Close BYT-2169
FYI @tianzhou @Candybase 
The page's render thread may possibly hang for a couple of seconds while capturing large (tens of tables) schemas. But that will not be too painful.
https://user-images.githubusercontent.com/2749742/212815110-a2df955d-8001-46ed-863f-0acbcbd1d024.mp4
> feat(schema-diagram): export diagram screenshot to PNG

- frontend/src/App.vue
- frontend/src/views/auth/Signup.vue
- server/api/v1/auth_service.go
- server/issue.go
- tests/fake/gitlab.go
> chore: update grpc api error format

- api/idp.go
- store/idp.go
> feat: implement store module for idp table

- api/task_check_run.go
- server/runner/taskcheck/statement_advisor_composite_executor.go
- tests/test-data/sql_review_mysql.yaml
- tests/test-data/sql_review_pg.yaml
> chore: add Line in taskCheckResult

- backend/common/retry.go
- backend/component/activity/manager.go
- go.mod
> fix: use exponential backoff for retrying posting webhook event

- backend/store/demo/default/10060##instance.sql
- backend/store/demo/default/10070##db.sql
* remove host, port from instance table
* remove character_set, collation from db table
> fix: fix the demo data according to the recent schema change

- frontend/src/components/Breadcrumb.vue
- frontend/src/router/index.ts
> fix(frontend): missing breadcrumbs in issue detail page

- frontend/src/components/ProjectMemberPanel.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
Clean unused i18n items after PR https://github.com/bytebase/bytebase/pull/4353
> chore: remove unused i18n items for syncing member from VCS

- frontend/src/components/Issue/PipelineGhostFlow.vue
- frontend/src/components/Issue/PipelinePITRFlow.vue
- frontend/src/components/Issue/PipelineSimpleFlow.vue
- frontend/src/components/Issue/PipelineTenantFlow.vue
> chore(frontend): wrapping text when database name is too long

- backend/legacyapi/plan.go
- frontend/src/locales/subscription/en-US.json
- frontend/src/types/plan.ts
- frontend/src/types/plan.yaml
> feat: move schema drift detection from TEAM to Enterprise

- backend/runner/rollbackrun/runner.go
- backend/runner/taskrun/scheduler.go
- backend/server/stage.go
- backend/server/webhook.go
- backend/store/issue.go
- backend/store/pipeline.go
- backend/store/stage.go
- backend/store/task.go
Remove the number of queries by doing batch task finds.
> chore: improve pipeline composition

- backend/api/v1/auth_service.go
- backend/bin/server/cmd/root.go
- frontend/src/store/modules/index.ts
- frontend/src/store/modules/user.ts
- frontend/src/views/ProfileDashboard.vue
> chore: disallow SSO user to change email

- frontend/src/components/IdentityProviderCreateForm.vue
* only show resource id input when creating;
* make display name and email inputs optional;
* put OIDC type into dev mode;
> chore: update identity provider form

- frontend/src/components/SchemaDiagram/Canvas/Canvas.vue
- frontend/src/components/SchemaDiagram/Canvas/composables/index.ts
- frontend/src/components/SchemaDiagram/Canvas/composables/useDragCanvas.ts
- frontend/src/components/SchemaDiagram/Canvas/composables/useFitView.ts
- frontend/src/components/SchemaDiagram/Canvas/const.ts
- frontend/src/components/SchemaDiagram/Navigator/index.ts
> refactor(schema-diagram): split canvas dragging and fitView features to individual composable functions

- frontend/src/components/IdentityProviderCreateForm.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/router/index.ts
- frontend/src/store/modules/idp.ts
- frontend/src/utils/idp.ts
- frontend/src/utils/index.ts
- frontend/src/views/ProfileDashboard.vue
- frontend/src/views/SettingWorkspaceSSO.vue
> feat: add configuration templates for OAuth2

- backend/enterprise/config/config.go
- backend/enterprise/service/license.go
- backend/legacyapi/plan.go
- backend/server/acl_casbin_policy_dba.csv
- backend/server/acl_casbin_policy_developer.csv
- backend/server/acl_casbin_policy_owner.csv
- backend/server/plan.go
- backend/server/server.go
- frontend/src/components/FeatureAttention.vue
- frontend/src/components/FeatureModal.vue
- frontend/src/components/RepositoryForm.vue
- frontend/src/locales/subscription/en-US.json
- frontend/src/locales/subscription/zh-CN.json
- frontend/src/main.ts
- frontend/src/store/modules/subscription.ts
- frontend/src/types/plan.ts
- frontend/src/types/plan.yaml
- frontend/src/types/sqlReview.ts
- frontend/src/types/subscription.ts
- Update quota for seat and instance
- Disable RBAC for the FREE plan
- Disable SQL review for the FREE plan
- Add `/feature` endpoint to unify the feature matrix for the backend and the frontend
> chore: update plan feature & unify feature matrix

- frontend/src/assets/schema-diagram.svg
- frontend/src/components/SchemaDiagram/SchemaDiagramIcon.vue
> chore: improve schema diagram icon

- backend/server/server.go
> chore: highlight the sample issue title

- backend/server/server.go
> feat: improve onboarding sample issue

- backend/plugin/advisor/mysql/advisor_syntax.go
- backend/plugin/advisor/pg/advisor_syntax_test.go
- backend/plugin/advisor/pg/parser.go
- backend/runner/taskcheck/statement_advisor_simple_executor.go
> feat(advisor): add Line information for Syntax Task Check

- frontend/src/assets/css/tailwind.css
- frontend/src/components/IdentityProviderCreateForm.vue
- frontend/src/components/ShowMoreIcon.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/utils/idp.ts
- frontend/src/views/SettingWorkspaceSSO.vue
> chore: update hint text for creating SSO form

- frontend/src/utils/project.ts
> chore(frontend): Project - Default should be changed to Project - Unassigned

- frontend/src/layouts/BodyLayout.vue
- frontend/src/router/index.ts
- frontend/src/views/sql-editor/TerminalPanel/TerminalPanel.vue
Close BYT-2318
FYI @tianzhou @Candybase
> feat(frontend): Highlight SQL Editor Entry Button and remove "New Project", "Manage User" in home view

- frontend/src/components/Issue/logic/useSQLAdviceMarkers.ts
Following #4455 
FYI @rebelice
> feat(frontend): support statement.syntax errors

- frontend/src/components/RepositoryTable.vue
> fix(frontend): remove creator column from repository table

- frontend/src/components/Quickstart.vue
> chore: improve quickstart highlighting

- frontend/src/components/ProvideSQLEditorContext.vue
> chore(sql-editor): show unassigned databases in instance view

- backend/api/v1/auth_service.go
- backend/api/v1/idp_service.go
- backend/store/idp.go
- backend/store/principal.go
- frontend/src/components/IdentityProviderCreateForm.vue
> chore: remove release guards for OAuth 2

- frontend/src/components/Quickstart.vue
- frontend/src/layouts/BodyLayout.vue
> chore: highlight quickstart

- frontend/src/components/Issue/TaskRunTable.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
> chore: change “View migration” to “View change”

- frontend/src/layouts/BodyLayout.vue
- frontend/src/views/Home.vue
> chore(frontend): adjust alignments

- frontend/src/views/OAuthCallback.vue
> fix: vcs oauth event type (#4487)

- frontend/src/components/ProjectVersionControlPanel.vue
- frontend/src/components/RepositoryPanel.vue
- frontend/src/types/project.ts
> fix(frontend): patch project.workflowType after deleting its repository

- backend/plugin/db/mysql/dump.go
We execute `SHOW MASTER STATUS` query to get the binlog info which can help us do rollback DML. See more details in #3287. 
For self-host MySQL, this query return 5 columns but 4 columns for rds and MariaDB.
Introduce dynamically scan.
FYI @tianzhou
> fix(query): dynamically scan the column for SHOW MASTER STATUS query

- backend/plugin/db/mysql/dump.go
> chore: cherry-pick #4494

- backend/plugin/advisor/config/sql-review.dev.yaml
- backend/plugin/advisor/config/sql-review.prod.yaml
- backend/plugin/advisor/pg/test/system_comment_length.yaml
- backend/plugin/advisor/sql_review.go
- frontend/src/locales/sql-review/en-US.json
- frontend/src/locales/sql-review/zh-CN.json
- frontend/src/types/sql-review-schema.yaml
- frontend/src/types/sqlReview.ts
* feat(advisor): add PostgreSQL rules in frontend
* test: fix tests
> feat(advisor): add PostgreSQL rules in frontend (cherry-pick #4498)

- backend/runner/taskrun/executor.go
See the difference of the migration history shown in the list
Fix BYT-2426
> feat: concate issue title and task name as the migration description

- frontend/src/components/PricingTable/PricingTable.vue
* chore: update plan config
* fix: add missing translation
* chore: update wording
* chore: update ui
* fix: pricing ui
> fix(cherry-pick): pricing ui (#4506)

- backend/runner/taskrun/executor.go
> chore: cherrypick: concate issue title and task name as the migration description

- frontend/src/components/PricingTable/PricingTable.vue
> chore: improve contact us enterprise form

- frontend/src/views/SettingWorkspaceAccessControl.vue
> chore: add feature attention for access control policy

- backend/legacyapi/plan.go
> fix: add access control feature flag

- backend/common/util_test.go
- backend/store/migration/prod/1.12/0003##obfuscate.sql
* fix: convert text to bytea by convert_to()
* chore: remove key
---------
Co-authored-by: d-bytebase <d@bytebase.com>
> cherrypick: convert text to bytea by convert_to() (#4518)

- backend/api/v1/common.go
- backend/api/v1/project_service.go
- backend/api/v1/project_service_test.go
- backend/store/deploy.go
- frontend/src/types/proto/v1/project_service.ts
- proto/generated-go/v1/project_service.pb.go
- proto/v1/project_service.proto
> feat(api): implement project deploy config in project service

- scripts/Dockerfile
- scripts/Dockerfile.render-demo
> fix: mkdir -p /var/opt/bytebase/pgdata-demo to fix docker permission error

- frontend/src/router/index.ts
> fix: sso setting page permission

- backend/api/v1/auth_service.go
- frontend/src/views/ProfileDashboard.vue
> fix: disallow SSO user to change password

- frontend/src/components/IdentityProviderCreateForm.vue
- frontend/src/components/ShowMoreIcon.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
> chore: add copy button to redirect url input

- backend/store/setting.go
- backend/store/store.go
> perf(cache): add cache for workspace setting

- backend/plugin/parser/split_multi_sql_test.go
- backend/plugin/parser/tokenizer.go
- backend/plugin/parser/utils.go
* fix(parser): filter the empty statement
* chore: address comments
> cherrypick(parser): filter the empty statement (#4533)

- scripts/Dockerfile
- scripts/Dockerfile.render-demo
https://github.com/bytebase/bytebase/pull/4522
> (cherrypick): fix dockerfile demo error (#4522)

- backend/store/demo/reset.sql
https://github.com/bytebase/bytebase/pull/4523
> (cherrpick): fix demo data 

- frontend/src/views/auth/AuthFooter.vue
> fix(frontend): selected language highlighting on "Sign up" page

- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/views/sql-editor/EditorCommon/EditorAction.vue
- frontend/src/views/sql-editor/TerminalPanel/CompactSQLEditor.vue
- frontend/src/views/sql-editor/TerminalPanel/TerminalPanel.vue
- frontend/src/views/sql-editor/TerminalPanel/useHistory.ts
> feat(sql-editor): split history items and query items (cherry-pick #4544)

- frontend/src/locales/sql-review/zh-CN.json
> fix: sql review localization

- frontend/src/locales/sql-review/zh-CN.json
* fix: sql review localization
* fix: sql review localization
> fix(cherry-pick): sql review localization (#4553)

- frontend/src/components/FeatureModal.vue
- frontend/src/components/TrialModal.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
> chore: remove dismiss button in the upgrade modal

- frontend/src/components/VCSCard.vue
- frontend/src/views/SettingWorkspaceAccessControl.vue
- frontend/src/views/SettingWorkspaceSensitiveData.vue
* chore: remove created time from vcs list
> chore: remove created time from vcs list (#4558)

- frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
- frontend/src/components/AlterSchemaPrepForm/ProjectTenantView.vue
- frontend/src/components/QuickActionPanel.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
> chore(frontend): Issue preparation UI layout improvement

- frontend/src/components/IdentityProviderCreateForm.vue
- frontend/src/components/ShowMoreIcon.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/views/SettingWorkspaceSSO.vue
> chore: update create identity provider form

- frontend/src/locales/sql-review/zh-CN.json
> fix: sql review rule localization

- frontend/src/components/PricingTable/PricingTable.vue
- frontend/src/locales/subscription/en-US.json
- frontend/src/locales/subscription/zh-CN.json
> chore: use ‘start at’ instead of ‘start from’

- frontend/src/locales/subscription/en-US.json
- frontend/src/locales/subscription/zh-CN.json
- frontend/src/types/plan.yaml
> chore: add SSO to pricing

- frontend/src/locales/subscription/en-US.json
- frontend/src/locales/subscription/zh-CN.json
Need another string to add to the main feature list
> chore: add missing SSO string

- frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
- frontend/src/components/AlterSchemaPrepForm/ProjectStandardView.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
Close BYT-2454
- Move the searchbox up, and remove the description texts.
- Remove the "Last sync status" column. Replace it with "Instance" column
- Responsive dialog width according to screen width.
> feat(frontend): issue preparation dialog UI layout improvements (part.2)

- frontend/src/locales/subscription/en-US.json
- frontend/src/locales/subscription/zh-CN.json
- frontend/src/types/plan.yaml
> chore: add schema-editor schema-diagram to pricing table

- frontend/src/components/Breadcrumb.vue
- frontend/src/shims-vue-router.d.ts
Fix: breadcrumb is not displaying correctly when using dynamic/async document title. E.g., issue detail page.
> fix(frontend): breadcrumb from route title

- frontend/src/views/sql-editor/EditorHeader.vue
> feat(sql-editor): hide "Audit Log" item for developer roles

- frontend/src/router/index.ts
- frontend/src/views/SettingSidebar.vue
> fix(frontend): wrong sidebar of user profile detail page

- frontend/src/components/ProjectDeploymentConfigPanel.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
Part of BYT-2312
FYI @Candybase
> chore(frontend): update db name template tips wording

- README.md
- docs/design/source-code-tour.snb.md
- frontend/src/components/SQLReview/SQLReviewPreview.vue
- frontend/src/components/SQLReview/components/SQLRuleConfig.vue
- frontend/src/views/SettingWorkspaceSQLReview.vue
Corresponding to the doc change https://github.com/bytebase/bytebase.com/pull/778
> chore: lift the review rule link corresponding to the doc change

- frontend/src/assets/css/tailwind.css
- frontend/src/views/sql-editor/AsidePanel/SchemaPanel/AlterSchemaButton.vue
- frontend/src/views/sql-editor/AsidePanel/SchemaPanel/DatabaseSchema.vue
- frontend/src/views/sql-editor/AsidePanel/SchemaPanel/ExternalLinkButton.vue
- frontend/src/views/sql-editor/AsidePanel/SchemaPanel/SchemaDiagramButton.vue
- frontend/src/views/sql-editor/AsidePanel/SchemaPanel/SchemaPanel.vue
- frontend/src/views/sql-editor/AsidePanel/SchemaPanel/TableSchema.vue
Close BYT-2456
- New table schema panel with slide up/down animation and embedded visual style.
- "Detail" external link button.
- The same cursor highlighted line style to the database tree.
- Removing unnecessary fields.
https://user-images.githubusercontent.com/2749742/216862510-eac66a64-d5f3-4dac-bdb4-74f5a5fabac9.mp4
> feat(sql-editor): schema panel improvement

- frontend/src/components/InstanceForm.vue
Should open instance.ExternalLink instead of dataSource.Host
Close BYT-2486
> fix(frontend): instance external link

- frontend/src/views/sql-editor/EditorCommon/DataTable.vue
- frontend/src/views/sql-editor/EditorCommon/TableView.vue
- frontend/src/views/sql-editor/TerminalPanel/TerminalPanel.vue
> feat(sql-editor): move paging control to the top toolbar

- backend/api/v1/acl.go
> fix: rbac feature checker

- frontend/src/components/Issue/IssueDescriptionPanel.vue
> chore(frontend): default height of issue description textarea

- frontend/src/components/CreateInstanceForm.vue
- frontend/src/components/InstanceForm.vue
- frontend/src/components/InstanceForm/SpannerCredentialInput.vue
- frontend/src/components/InstanceForm/SpannerHostInput.vue
- frontend/src/components/InstanceForm/index.ts
- frontend/src/components/misc/DroppableTextarea.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- Split ProjectID and InstanceID into two input boxes. (Close BYT-2427)
- Support upload credentials file. (Close BYT-2425)
- Correct the CSS style of the description. (Close BYT-2424)
- Remove the "Empty" checkbox for password/credentials. (Close BYT-2428)
> feat(frontend): Spanner UI improvement

- frontend/src/views/DatabaseDetail.vue
> fix(frontend): inherit attrs for DatabaseDetail

- frontend/src/views/sql-editor/EditorCommon/ConnectionPathBar.vue
> feat(sql-editor): don't show read-only datasource warning in admin mode

- frontend/src/views/sql-editor/TabList/TabItem/AdminLabel.vue
- frontend/src/views/sql-editor/TabList/TabItem/Suffix.vue
- frontend/src/views/sql-editor/TabList/TabItem/TabItem.vue
> feat(sql-editor): Use the same black background and green text for the admin Tab

- frontend/src/components/InstanceForm.vue
> fix(frontend): remove host/port in RO datasource for Spanner

- backend/runner/backuprun/runner.go
- frontend/src/views/DatabaseDetail.vue
1. skip spanner auto backup
2. hide backup and restore tab for spanner
> fix(spanner): disable auto backup & hide backup tab

- frontend/src/components/Issue/PagedIssueTable.vue
- frontend/src/store/modules/auth.ts
> fix(frontend): make isLoggedIn more accurate

- backend/api/v1/instance_role_service.go
- backend/plugin/db/mysql/role.go
> feat: implement MySQL role CRUD

- backend/api/v1/idp_service.go
- frontend/src/components/IdentityProviderCreateForm.vue
> fix: allow update idp without client secret

- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/views/SettingWorkspaceVCS.vue
> chore: update vcs description

- frontend/src/components/RepositoryForm.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
This is not how Bytebase behaves anymore.
> fix: remove outdated gitops tip

- backend/store/idp.go
- backend/store/principal.go
> fix: hide those idp archived user

- backend/legacyapi/principal.go
- backend/store/principal.go
- frontend/src/components/MemberTable.vue
- frontend/src/main.ts
- frontend/src/store/modules/principal.ts
- frontend/src/types/principal.ts
- frontend/src/views/ProfileDashboard.vue
- frontend/src/views/SettingWorkspaceSSO.vue
> feat: show domain name for idp users

- frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
- frontend/src/store/modules/connectionTree.ts
- frontend/src/store/modules/project.ts
- frontend/src/views/sql-editor/AsidePanel/AsidePanel.vue
- frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue
- frontend/src/views/sql-editor/AsidePanel/SchemaPanel/AlterSchemaButton.vue
- frontend/src/views/sql-editor/AsidePanel/SchemaPanel/DatabaseSchema.vue
- frontend/src/views/sql-editor/AsidePanel/SchemaPanel/SchemaPanel.vue
- frontend/src/views/sql-editor/AsidePanel/SchemaPanel/TableSchema.vue
- frontend/src/views/sql-editor/SQLEditorPage.vue
It will be much cooler if we can automatically open the target editing table. But that needs more work.
https://user-images.githubusercontent.com/2749742/217403178-e3349c71-f55b-4096-a7bc-cfe213aca9c8.mp4
> feat(sql-editor): call SchemaEditor for alter schema

- frontend/src/components/SchemaDiagram/SchemaDiagramIcon.vue
- frontend/src/components/SchemaEditor/DatabaseTree.vue
- frontend/src/components/SchemaEditor/Panels/DatabaseEditor.vue
- frontend/src/components/SchemaEditor/Panels/TableEditor.vue
- frontend/src/components/SchemaEditor/TabsContainer.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
> feat: update layout of schema editor

- frontend/public/demo/schema-migration-history/demo.json
- frontend/public/help/en/help.project.md
- frontend/public/help/routeMapList.json
- frontend/public/help/zh/help.project.md
- frontend/src/components/Breadcrumb.vue
- frontend/src/components/DatabaseTable.vue
- frontend/src/components/ProjectTable.vue
- frontend/src/components/ProjectVersionControlPanel.vue
- frontend/src/components/RepositoryPanel.vue
- frontend/src/components/RepositorySetupWizard.vue
- frontend/src/components/RepositoryTable.vue
- frontend/src/components/RepositoryVCSProviderPanel.vue
- frontend/src/components/VCSCard.vue
- frontend/src/components/VCSProviderBasicInfoPanel.vue
- frontend/src/components/VCSProviderConfirmPanel.vue
- frontend/src/components/VCSProviderOAuthPanel.vue
- frontend/src/components/VCSSetupWizard.vue
- frontend/src/layouts/ProjectLayout.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/router/index.ts
- frontend/src/store/modules/router.ts
- frontend/src/types/store.ts
- frontend/src/views/InstanceDetail.vue
- frontend/src/views/ProjectDetail.vue
- frontend/src/views/SettingSidebar.vue
- frontend/src/views/SettingWorkspaceVCS.vue
- frontend/src/views/SettingWorkspaceVCSCreate.vue
- frontend/src/views/SettingWorkspaceVCSDetail.vue
- quickstart/README.md
Our non-gitops workflow also has Version Control, so this is confusing.
Fix BYT-2471
> refactor: change “version control” to “GitOps”

- backend/api/v1/auth_service.go
- backend/bin/server/cmd/profile.go
- backend/bin/server/cmd/root.go
- backend/component/config/profile.go
- backend/legacyapi/actuator.go
- backend/server/actuator.go
- backend/server/auth.go
- backend/server/server.go
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/store/modules/actuator.ts
- frontend/src/types/actuator.ts
- frontend/src/views/SettingWorkspaceVCSDetail.vue
- frontend/src/views/auth/Signin.vue
- frontend/src/views/auth/Signup.vue
In the SaaS modal, we should disallow sign up for every Bytebase instance and generate the owner account for users
> chore: introduce disallow-signup flag

- frontend/src/components/RepositoryForm.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
> chore(frontend): wording

- frontend/src/components/AccessControl/AddRuleForm.vue
- frontend/src/components/AlterSchemaPrepForm/ProjectStandardView.vue
- frontend/src/components/DatabaseTable.vue
- frontend/src/components/Environment/ProductionEnvironmentIcon.vue
- frontend/src/components/EnvironmentForm.vue
- frontend/src/components/EnvironmentSelect.vue
- frontend/src/components/InstanceTable.vue
- frontend/src/components/Issue/IssueSidebar.vue
- frontend/src/components/Issue/IssueTable.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/utils/policy.ts
- frontend/src/views/DatabaseDetail.vue
- frontend/src/views/EnvironmentDashboard.vue
- frontend/src/views/SettingWorkspaceAccessControl.vue
- frontend/src/views/SettingWorkspaceSensitiveData.vue
- frontend/src/views/sql-editor/AsidePanel/TreeNode/InstancePrefix.vue
- frontend/src/views/sql-editor/EditorCommon/ConnectionPathBar.vue
- frontend/src/views/sql-editor/TabList/TabItem/AdminLabel.vue
Close BYT-2479
(No backend value changes)
> chore: rename "Protected" environment to "Production"/"生产环境"

- backend/component/state/state.go
- backend/legacyapi/task.go
- backend/plugin/db/mysql/binlog_stream_parser.go
- backend/plugin/db/mysql/binlog_stream_parser_test.go
- backend/plugin/db/mysql/rollback.go
- backend/runner/rollbackrun/runner.go
- backend/runner/taskrun/executor.go
- backend/runner/taskrun/scheduler.go
- backend/server/task.go
- backend/store/task.go
- backend/tests/rollback_test.go
Support canceling rollback generation as it cloud take a long time.
Set payload.RollbackEnabled will cancel the generation.
Close BYT-2507
FYI @LiuJi-Jim
> feat: cancel rollback generation

- frontend/src/components/Issue/IssueTaskStatementPanel.vue
- frontend/src/components/Issue/TaskRunTable.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
> chore: improve baselining issue UX and message

- backend/api/v1/idp_service.go
- frontend/src/components/IdentityProviderCreateForm.vue
> chore: allow test connection without client secret in idp detail page

- frontend/src/components/ActivityTable/ActivityTypeLink.vue
Display nothing instead of a wrong link.
> fix(frontend): downgrade for legacy commit data

- frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
> chore: align buttons in schema editor

- frontend/src/locales/en-US.json
- frontend/src/locales/subscription/en-US.json
- frontend/src/locales/subscription/zh-CN.json
- frontend/src/locales/zh-CN.json
- frontend/src/types/plan.yaml
Old category: Database Development, Collaboration, Admin & Security, Branding
New category: Change Management, SQL Editor,  Collaboration, Data Security and Governance, Bespoke
> chore: update pricing table

- README.md
- docs/design/source-code-tour.snb.md
- frontend/src/components/ProjectDeploymentConfigPanel.vue
Corresponding to https://github.com/bytebase/bytebase.com/pull/791
> chore: update the tenant database doc link

- frontend/src/components/PricingTable/PricingTable.vue
* Add left, right border
* Enlarge section title
> chore: improve pricing table

- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
fix the part that #4673 missed when fixing #4669
> fix: IM integration i18n key name

- frontend/src/components/IdentityProviderCreateForm.vue
Remove object reference for editing state.
> chore: fix object reference

- backend/plugin/db/util/driverutil_test.go
- backend/plugin/db/util/mask_sensitive_data.go
- backend/plugin/parser/engine/pg/convert.go
> feat: mask sensitive fields for PostgreSQL simple cases

- backend/plugin/db/mysql/binlog_stream_parser_test.go
add a test case using the binlog generated by a DML task with `select 1`.
> chore: add testcase for binlog stream parser

- backend/plugin/vcs/github/github.go
- backend/plugin/vcs/gitlab/gitlab.go
- backend/plugin/vcs/vcs.go
- backend/runner/taskrun/executor.go
- backend/tests/fake/gitlab.go
- backend/tests/schema_update_test.go
- backend/tests/tests.go
We allow writeback latest file for issues created from UI.
1) repo branch has no wildcard.
2) baseline, regular and gh-ost schema changes.
> chore: writeback to vcs for UI issues

- backend/plugin/db/util/driverutil_test.go
- backend/plugin/db/util/mask_sensitive_data.go
> feat: mask sensitive fields for PostgreSQL JOIN and SET OPERATION

- backend/plugin/db/util/driverutil_test.go
- backend/plugin/db/util/mask_sensitive_data.go
> feat: mask sensitive field for PostgreSQL CTE

- frontend/src/components/MemberSelect.vue
> fix(frontend): hide inactive users

- frontend/src/components/misc/Watermark.vue
> feat(frontend): email in watermark

- frontend/src/components/BannersWrapper.vue
- frontend/src/views/BannerDebug.vue
Also use info style for readonly banner
> feat: decrease the height of banner debug and banner readonly to save space

- frontend/src/components/QuickActionPanel.vue
> chore: decrease quick action bar height&font to save space

- frontend/src/components/Issue/IssueDetailLayout.vue
- frontend/src/components/Issue/IssueTaskStatementPanel.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
> feat: make SQL Review paywall less intrusive

- frontend/src/views/DashboardHeader.vue
Try to reduce accent color button
> chore: use emerald for the want help button

- frontend/src/layouts/BodyLayout.vue
> chore: make SQL Editor button less intrusive while still be obvious 

- frontend/src/components/DatabaseMigrationHistoryPanel.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
> feat(frontend): disallow establish baseline to unassigned databases

- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/views/Home.vue
- frontend/src/views/auth/Signin.vue
- frontend/src/views/auth/Signup.vue
> chore: enable auto trialing

- frontend/src/components/Issue/rollback/RollbackStatus.vue
Remove the link to the original task because we already have a better one.
> chore: update rollback issue description

- backend/api/v1/auth_service.go
- backend/store/principal.go
https://user-images.githubusercontent.com/24653555/218385588-eb2e3bca-e277-477e-898c-0e3a24f99d4b.mp4
Close BYT-2540
> chore: update the latest userinfo synchronously

- backend/component/config/profile.go
- backend/legacyapi/project.go
- backend/server/server.go
- backend/tests/schema_update_test.go
- backend/tests/tests.go
- frontend/src/components/Issue/TaskCheckRunPanel.vue
Also fix the error code anchor in the SQL advisor violation message.
Fix BYT-2536
> feat: configure a Sample SQL Review Policy

- backend/plugin/db/pg/pg.go
> fix: support to run PostgreSQL CREATE INDEX CONCURRENTLY statements

- backend/tests/issue.go
https://github.com/bytebase/bytebase/actions/runs/4160113518/jobs/7197233222
> chore: retry task check not pass error

- frontend/src/components/IdentityProviderCreateForm.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
> chore: update archive description

- backend/store/migration/prod/1.12/0007##vcs_to_idp.sql
- backend/store/pg_engine_test.go
Related code changes: https://github.com/bytebase/bytebase/pull/4727
---
Thanks @RainbowDashy and @rebelice
> chore: add vcs to idp dml

- backend/api/v1/org_policy_service.go
- backend/legacyapi/policy.go
- backend/server/server.go
- backend/server/sql.go
- frontend/src/components/ColumnTable.vue
- frontend/src/types/policy.ts
- frontend/src/views/SettingWorkspaceSensitiveData.vue
- frontend/src/views/TableDetail.vue
> fix: add schema info to sensitive data policy and add onboarding

- backend/runner/apprun/runner.go
See code comments.
Close BYT-2548
> chore: remove spammy and not-so-useful logging in app runner

- frontend/src/components/SchemaDiagram/common/context.ts
> fix(schema-diagram): fitView broken after taking screenshot

- frontend/src/components/misc/DroppableTextarea.vue
Now we can
- Input or paste directly.
- Drag and drop a file into the box.
- Click the button to select a file.
https://user-images.githubusercontent.com/2749742/218679858-fa4806b4-401d-46cc-af20-b4e1b9aa4cae.mp4
> feat(frontend): support click to upload file

- frontend/src/components/CreateInstanceForm.vue
- frontend/src/components/InstanceForm.vue
- frontend/src/components/InstanceForm/SpannerHostInput.vue
- frontend/src/utils/instance.ts
Close BYT-2558
- Inputting error projectId won't cause the instanceId disappear, vice versa.
- Missing or invalid projectId / instanceId will block the "Create" or "Update" button.
> feat(frontend): make spanner host input component robuster

- frontend/src/components/SchemaEditor/Modals/TableNameModal.vue
> chore(schema-editor): uppercase column type

- frontend/src/components/ProjectDeploymentConfigPanel.vue
> fix(tenant): using resource id instead of name when add new stage

- frontend/src/components/SQLReview/SQLReviewConfig.vue
- frontend/src/components/SQLReview/SQLReviewInfo.vue
- frontend/src/components/SQLReview/components/SQLReviewCategorySummaryFilter.vue
- frontend/src/components/SQLReview/components/index.ts
- frontend/src/store/modules/sqlReview.ts
- frontend/src/views/SettingWorkspaceSQLReviewDetail.vue
Reused and extracted some codes from SettingWorkspaceSQLReviewDetail.vue
Close BYT-2451
> feat(frontend): support filtering when creating and editing sql review rules

- backend/api/v1/auth_service.go
- backend/server/auth.go
- backend/store/principal.go
- frontend/src/components/IdentityProviderCreateForm.vue
- frontend/src/views/SettingWorkspaceSSO.vue
- frontend/src/views/SettingWorkspaceSSODetail.vue
* union find user by email when sign in with SSO
* make domain field optional
* also close BYT-2555
> feat(sso): union find user by email

- frontend/src/components/Issue/rollback/LogButton.vue
- frontend/src/components/Issue/rollback/LoggingButton.vue
- frontend/src/components/Issue/rollback/RollbackStatus.vue
- frontend/src/components/Issue/rollback/RollbackSwitch.vue
- frontend/src/components/Issue/rollback/TaskRollbackView.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
Close BYT-2549, BYT-2550, BYT-2570
--
> feat(frontend): SQL rollback button UI update

- backend/api/v1/auth_service.go
- backend/server/auth.go
- backend/store/principal.go
- frontend/src/components/IdentityProviderCreateForm.vue
- frontend/src/views/SettingWorkspaceSSO.vue
- frontend/src/views/SettingWorkspaceSSODetail.vue
> feat(sso): union find user by email (cherrypick #4748)

- frontend/src/components/Issue/rollback/LogButton.vue
- frontend/src/components/Issue/rollback/LoggingButton.vue
- frontend/src/components/Issue/rollback/RollbackStatus.vue
- frontend/src/components/Issue/rollback/RollbackSwitch.vue
- frontend/src/components/Issue/rollback/TaskRollbackView.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
* feat: button UI update
* chore: update style
> feat(frontend): SQL rollback button UI update (cherry-pick #4739)

- frontend/src/views/sql-editor/EditorCommon/ConnectionPathBar.vue
> chore(sql-editor): update path bar style

- frontend/src/components/IdentityProviderCreateForm.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
> chore: update computed redirect url value (#4771)

- backend/api/v1/idp_service.go
- frontend/src/utils/sso.ts
https://user-images.githubusercontent.com/24653555/218997085-ff15335c-4288-45ac-9461-ea048216cf28.mp4
> fix: test connection for OIDC

- frontend/src/components/Issue/BatchIssueActions.vue
> chore(frontend): allow high-privileged user to change issue status

- backend/plugin/db/mysql/binlog_stream_parser.go
- backend/plugin/db/mysql/restore.go
- backend/plugin/db/mysql/rollback.go
- backend/runner/rollbackrun/runner.go
- backend/tests/rollback_test.go
Return more user-friendly error msg to the frontend.
Close BYT-2573
> fix: improve rollback error msg

- frontend/src/components/Issue/TaskCheckRunPanel.vue
> fix(frontend): handle undefined taskCheckResult.code

- backend/server/auth.go
- backend/server/principal.go
- backend/store/principal.go
Disallow sign up with existing email in console UI. Not for SSO sign in.
> fix: disallow signup with existing email in console

- backend/server/server.go
This reverts commit 1f86849bde95cf9ddd366c830f47fa95008fad64.
> chore: revert "feat: enable rollback runner (#4750)"

- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/views/auth/Signin.vue
> chore: explicitly list demo email and password in case auto fill not working

- frontend/src/components/BytebaseLogo.vue
- frontend/src/layouts/DashboardLayout.vue
- frontend/src/views/DashboardHeader.vue
- frontend/src/views/DashboardSidebar.vue
- frontend/src/views/SettingSidebar.vue
> chore(frontend): move logo position

- backend/api/v1/auth_service.go
- backend/server/principal.go
Add email unique checker when updating users in api level.
> fix: check email unique when updating user

- frontend/src/views/sql-editor/EditorCommon/AdminModeButton.vue
- frontend/src/views/sql-editor/EditorCommon/ConnectionPathBar.vue
- frontend/src/views/sql-editor/EditorCommon/EditorAction.vue
- frontend/src/views/sql-editor/EditorCommon/TableView.vue
- frontend/src/views/sql-editor/SQLEditorPage.vue
It just looks not that awful, features still not guaranteed to work smoothly.
> feat(sql-editor): simple mobile layout for sql editor

- backend/api/v1/auth_service.go
- backend/server/auth.go
- backend/server/principal.go
- frontend/src/store/modules/principal.ts
Add lower email codes in backend and frontend.
> chore: update email format with lower case

- backend/enterprise/config/config.go
- backend/enterprise/config/config_dev.go
- backend/enterprise/config/config_release.go
- backend/enterprise/service/license.go
- backend/enterprise/service/provider.go
- backend/enterprise/service/utils.go
- backend/legacyapi/setting.go
- go.mod
- Introduce `bb.hub.internal-token` setting to store the internal token
- Use the internal token to call the hub to fetch the license
> feat: refresh subscription license

- frontend/src/layouts/BodyLayout.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/views/BannerDemo.vue
Also indicate demo on the bottom left
> chore: replace demo text with demo appointment link

- frontend/src/components/GeneralSetting/WatermarkSetting.vue
> chore(frontend): update watermark setting layout

- frontend/src/components/InstanceForm.vue
> chore(frontend): remove the revert button for instance ssl cert form

- backend/legacyapi/sheet.go
- backend/server/database.go
- backend/store/database.go
- backend/store/sheet.go
> feat: update related sheets's project id when transferring database

- frontend/src/components/Issue/IssueSidebar.vue
-- For newly created database
-- For existed database
> chore(frontend): add a SQL Editor terminal icon to issue sidebar

- frontend/src/components/ProjectGeneralSettingPanel.vue
- frontend/src/types/project.ts
BYT-2587
This works after #4827 Thanks @d-bytebase
> feat(frontend): support switching project tenant mode

- backend/runner/taskrun/scheduler.go
Should use the updated issue.
Close BYT-2622
> fix: webhook issue staleness

- frontend/src/bbkit/BBSwitch.vue
- frontend/src/components/Issue/rollback/LogButton.vue
- frontend/src/components/Issue/rollback/LoggingButton.vue
- frontend/src/components/Issue/rollback/RollbackStatus.vue
- frontend/src/components/Issue/rollback/RollbackSwitch.vue
- frontend/src/components/Issue/rollback/TaskRollbackView.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
Only UI updates. No logic changes.
- Wail for the user docs' done and will add a "Learn more" link later.
> feat(frontend): update SQL rollback UI

- frontend/src/components/EnvironmentForm.vue
- frontend/src/components/ResourceIdField.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
To make a better UX of resource id field, we need a bound input field for the resource title and resource ID. This PR add a `ResourceIdField` component with following functions:
* generate random resource id from resource title;
* static validation of the resource id.
https://user-images.githubusercontent.com/24653555/220279170-6433204d-241c-4aee-802f-42f15e542c90.mp4
> feat: introduce `ResourceIdField` component

- frontend/src/store/modules/user.ts
- frontend/src/store/modules/v1/auth.ts
- frontend/src/store/modules/v1/common.ts
- frontend/src/store/modules/v1/environment.ts
- frontend/src/types/const.ts
- frontend/src/utils/common.ts
* add auth v1 store;
* update environment and user v1 store.
And these stores are not used right now.
> feat: add auth v1 store

- frontend/src/components/EnvironmentForm.vue
- frontend/src/components/ResourceIdField.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/utils/grpcweb.ts
https://user-images.githubusercontent.com/24653555/220837565-32888a69-1100-44fa-bd20-d225731caae6.mp4
> feat: check duplicated resource id

- frontend/src/components/Issue/IssueDetailLayout.vue
- frontend/src/components/Issue/IssueTaskSDLPanel.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
Close BYT-2577
FYI @rebelice @Candybase 
https://user-images.githubusercontent.com/2749742/220833868-5ed6e1dd-e955-4fa8-977f-b8f7b7482daf.mp4
> feat(frontend): display SDL issue's change detail

- frontend/src/components/EnvironmentForm.vue
- frontend/src/components/IdentityProviderCreateForm.vue
- frontend/src/components/ResourceIdField.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/store/modules/v1/common.ts
https://user-images.githubusercontent.com/24653555/221079416-fc6b00fe-c347-439c-975d-a65509817137.mp4
> feat: use `ResourceIdField` in SSO

- backend/legacyapi/activity.go
- backend/server/activity.go
Introducing a more structured rollback activity so that we can make smarter suggestions for the user on the frontend.
We will pop up a dialog informing that there's already a rollback issue if the user clicked the "rollback" button the second time. @LiuJi-Jim
> feat: rollback activity

- frontend/src/components/Issue/IssueHighlightPanel.vue
- frontend/src/components/Issue/IssueRollbackFromTips.vue
- frontend/src/components/Issue/logic/base.ts
- frontend/src/components/Issue/logic/common.ts
- frontend/src/components/Issue/rollback/RollbackStatus.vue
- frontend/src/components/Issue/rollback/common.ts
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/plugins/issue/logic/initialize/standard.ts
- frontend/src/store/modules/issue.ts
- frontend/src/utils/slug.ts
Since a rollback issue is no more special other than other DML issues. Now we use a typical two-phase issue creation flow.
FYI @RainbowDashy @Candybase 
https://user-images.githubusercontent.com/2749742/220855510-20140772-1b99-45bf-8579-73bc5e3a6328.mp4
> feat(frontend): preview rollback issue

- frontend/src/layouts/BodyLayout.vue
> feat: use control color gray-100 as the sidebar bg

- frontend/src/layouts/BodyLayout.vue
> chore: use the border-block-border instead of border-control-border

- frontend/src/components/Issue/IssueDetailLayout.vue
- frontend/src/components/Issue/IssueTaskSDLPanel.vue
- frontend/src/store/modules/database.ts
- frontend/src/store/modules/instance.ts
Featured by #4871 and #4869, now we can preview schema diff, generated DDL before an SDL task's executed.
FYI @Candybase
> feat(frontend): preview SDL changes

- backend/bin/server/cmd/root.go
- backend/common/config.go
- backend/common/docs.go
- backend/common/util.go
- backend/server/project.go
- backend/server/server_frontend_embed.go
> feat: reject GitOps workflow config if —external-url is not set

- frontend/src/components/ResourceIdField.vue
* remove random string in suggestions.
https://user-images.githubusercontent.com/24653555/221456651-afde9c84-b8cc-45eb-b38b-c3291896eb41.mp4
> chore: update resource id suggestion

- backend/plugin/idp/oidc/oidc.go
Closes https://linear.app/bytebase/issue/BYT-2625 cc @changyuwong 
CI
> fix(oidc): skip checking nonce if expected to be empty

- frontend/src/components/Issue/logic/base.ts
- frontend/src/components/Issue/rollback/RollbackStatus.vue
- frontend/src/components/Issue/rollback/common.ts
- frontend/src/locales/zh-CN.json
- frontend/src/store/modules/activity.ts
- frontend/src/types/activity.ts
> feat(frontend): create rollback issue comment with structured info

- backend/legacyapi/instance.go
- backend/server/common.go
- backend/server/instance.go
- backend/tests/backup_restore_test.go
- backend/tests/common.go
- backend/tests/data_source_test.go
- backend/tests/database_edit_test.go
- backend/tests/external_approval_test.go
- backend/tests/ghost_test.go
- backend/tests/project_test.go
- backend/tests/rollback_test.go
- backend/tests/schema_update_test.go
- backend/tests/sensitive_data_test.go
- backend/tests/sql_editor_test.go
- backend/tests/sql_review_test.go
- backend/tests/sync_schema_test.go
- backend/tests/syncer_test.go
- backend/tests/tenant_test.go
- frontend/src/components/InstanceForm.vue
- frontend/src/types/instance.ts
* update `InstanceCreate` legacy api to prevent big changes;
* add `ResourceIdField` to `InstanceForm`;
https://user-images.githubusercontent.com/24653555/221497719-c2a10920-2f6d-4634-b1a3-7e0d20cfcecc.mp4
> feat: add resource id field to instance

- backend/plugin/db/mysql/rollback.go
mysqlbinlog binary outputs error to stderr. If there is anything in stderr, it means that mysqlbinlog has failed and we should return its error.
Close BYT-2589
> fix(rollback): should fail if stderr is not empty

- backend/legacyapi/project.go
- backend/server/project.go
- backend/tests/backup_restore_test.go
- backend/tests/database_edit_test.go
- backend/tests/external_approval_test.go
- backend/tests/ghost_test.go
- backend/tests/project_test.go
- backend/tests/rollback_test.go
- backend/tests/schema_update_test.go
- backend/tests/sensitive_data_test.go
- backend/tests/sheet_vcs_test.go
- backend/tests/sql_editor_test.go
- backend/tests/sql_review_test.go
- backend/tests/sync_schema_test.go
- backend/tests/syncer_test.go
- backend/tests/tenant_test.go
- frontend/src/components/ProjectCreate.vue
- frontend/src/components/ProjectGeneralSettingPanel.vue
- frontend/src/components/ResourceIdField.vue
- frontend/src/grpcweb/index.ts
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/store/modules/v1/common.ts
- frontend/src/store/modules/v1/project.ts
- frontend/src/types/project.ts
https://user-images.githubusercontent.com/24653555/221507884-2016ab5c-3af5-479d-a1ba-2246f637568d.mp4
> feat: add resource id field to project

- frontend/src/assets/css/tailwind.css
- frontend/src/components/Issue/rollback/TaskRollbackView.vue
- frontend/src/components/LearnMoreLink.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
Close BYT-2561
FYI @RainbowDashy @Candybase
> feat(frontend): add a link to user docs for the SQL Rollback tooltip

- frontend/src/utils/idp.ts
> chore: update `OAuth2` to `OAuth 2.0`

- backend/common/error.go
- backend/plugin/parser/utils.go
- backend/runner/taskcheck/statement_type_executor.go
- backend/runner/taskrun/schema_update_sdl_executor.go
- backend/runner/utils/sdl_utils.go
- backend/server/server.go
- backend/tests/schema_update_test.go
> feat: check DROP operation for SDL task

- frontend/src/components/CreateDatabasePrepForm.vue
- frontend/src/components/DatabaseDetail/CreatePITRDatabaseForm.vue
> fix(frontend): hide db name template when not needed

- frontend/src/views/sql-editor/EditorCommon/TableView.vue
> fix(sql-editor): admin mode result table layout

- frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
- frontend/src/views/DatabaseDetail.vue
> chore: don't show not found database in schema editor

- frontend/src/components/Issue/TaskCheckBar.vue
- frontend/src/components/Issue/TaskCheckRunPanel.vue
- frontend/src/components/SQLReview/SQLReviewConfig.vue
- frontend/src/components/SQLReview/SQLReviewCreation.vue
- frontend/src/components/SQLReview/components/SQLRuleEditDialog.vue
- frontend/src/components/SQLReview/components/SQLRuleTable.vue
- frontend/src/components/SQLReview/components/index.ts
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/store/modules/sqlReview.ts
- frontend/src/types/policy.ts
- frontend/src/types/sqlReview.ts
- frontend/src/views/SettingWorkspaceSQLReviewDetail.vue
* feat: two-phases editing for sql-review policy
* chore: wording
* chore: reorder imports
* feat: set custom description
* feat: display rule detail dialog
> feat(frontend): support custom sql review rule description (cherry-pick #4922)

- backend/plugin/parser/transform/mysql/transform.go
- backend/plugin/parser/transform/mysql/transform_test.go
- backend/plugin/parser/transform/transform.go
The Normalize function helps us to show more readable SDL diffs.
> feat(transform): add normalize for transformer

- frontend/src/views/auth/Signin.vue
> chore(frontend): don't stop tab focus on the link on the sign-in page

- frontend/src/components/Issue/rollback/RollbackStatus.vue
- Will show the current status (OPEN, RESOLVED, CANCELLED) of the rollback issue.
> feat(frontend): show the status of rollbackByIssue

- backend/store/migration/dev/20230303000000##principal_mfa_config.sql
- backend/store/migration/dev/LATEST.sql
> feat: add `mfa_config` fields to principal table

- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/views/Home.vue
> chore: show a button in trialing modal

- backend/server/sql.go
Mongo & Spanner will fail on this line.
```sql
sqlDB, err := driver.GetDBConnection(ctx, exec.DatabaseName)
```
> fix: 🔥mongo&spanner have no sql.db

- frontend/src/types/proto/store/user.ts
followup with https://github.com/bytebase/bytebase/pull/4981
> chore: generate user store proto to TypeScript

- backend/api/v1/auth_service.go
- fix user type for the service account
- count users instead of list users
> fix: create user type

- backend/plugin/parser/differ/mysql/differ.go
- backend/plugin/parser/transform/mysql/transform.go
- backend/plugin/parser/transform/mysql/transform_test.go
- backend/tests/schema_update_test.go
> chore: add empty line after SDL statements and SET statements

- backend/plugin/mfa/otp/otp.go
- backend/plugin/mfa/otp/otp_test.go
- go.mod
- go.sum
* implement the current timestamp(of minutes) based secret generator;
* validate OTP code within the secrets in the past five minutes;
Close BYT-2706
> feat: implement time-based OTP secret generator

- backend/runner/taskcheck/statement_advisor_composite_executor.go
- backend/server/openapi_sql.go
- backend/server/sql.go
- backend/server/webhook.go
- backend/store/catalog.go
close BYT-2698
close BYT-2701
close BYT-2693
> feat: support SDL mode SQL review

- backend/api/v1/auth_service.go
- backend/store/setting.go
- Return 409 if the principal exists
- Always force to get the profile setting
> chore: update for saas

- frontend/src/views/SheetDashboard.vue
> fix(sql-editor): use resourceId as selector key

- backend/server/webhook.go
> feat: support SDL for tenant mode GitOps

- backend/api/v1/project_service.go
- backend/component/activity/manager.go
- backend/legacyapi/project_webhook.go
- backend/legacyapi/slug.go
- backend/server/project_webhook.go
- backend/store/project.go
- backend/store/project_webhook.go
Also migrate legacy project webook store to v1 store.
> feat(api): implement project webhook service

- backend/plugin/parser/differ/mysql/column_test.go
- backend/plugin/parser/differ/mysql/differ.go
- backend/plugin/parser/differ/mysql/table_test.go
> fix(differ): improve MySQL DDL safe order

- frontend/src/components/ProjectGeneralSettingPanel.vue
- frontend/src/components/RepositoryForm.vue
- frontend/src/components/VCSProviderBasicInfoPanel.vue
- enlarge the clickable area for VCS provider selection (Close BYT-2691)
- update the placeholder wording for tenant mode projects (Close BYT-2718)
- remove the schema migration type selector from the project general settings (Close 2704)
> feat(frontend): VCS configuration minor improvements and bugfixes

- backend/plugin/advisor/catalog/test/mysql_walk_through.yaml
- backend/plugin/advisor/catalog/walk_through.go
> chore(catalog): check default value with column type in walk through for MySQL

- frontend/src/components/Issue/rollback/common.ts
> feat(frontend): add activities when turned on/off sql rollback log

- backend/api/v1/auth_service.go
- backend/store/principal.go
- frontend/src/components/MFAChallengeModal.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/store/modules/user.ts
- frontend/src/types/index.ts
- frontend/src/types/mfa.ts
- frontend/src/views/auth/Signin.vue
This PR implements the MFA challenge when user sign in. And the 2FA setup will be in a separate PR.
https://user-images.githubusercontent.com/24653555/223680172-bd61870b-f3ac-4794-bc84-e1fac4660c2d.mp4
> feat: challenge MFA when signin

- .github/workflows/build-push-ci-image.yml
- backend/server/auth.go
- backend/server/principal.go
- Looks like we're missing several args in the release-ci
- Should return 409 if the principal exists
> fix: several fix

- frontend/src/composables/useExecuteSQL.ts
- frontend/src/plugins/silent-request.ts
- frontend/src/views/sql-editor/EditorCommon/TableView.vue
> chore(sql-editor): better handling for critical errors

- frontend/src/layouts/BodyLayout.vue
- frontend/src/views/DashboardSidebar.vue
Make the blue part sticky while scrolling. Only the red part is scrollable.
PTAL @tianzhou
> chore(frontend): adjust the scrollable area of sidebar

- frontend/src/components/MonacoEditor/sqlParser.ts
- frontend/src/composables/useExecuteSQL.ts
- frontend/src/views/sql-editor/EditorCommon/ExecuteHint.vue
Close BYT-1526
Priority when multiple statements: DDL > DML
> feat(sql-editor): detect DML/DDL when there are multiple statements

- frontend/src/components/InstanceForm.vue
> chore(frontend): add beta badge for redis instance creation

- backend/server/server.go
-  default id use system bot
-  check issue id
> fix: backfill instance change history

- frontend/src/components/Issue/IssueTable.vue
- frontend/src/components/QuickActionPanel.vue
* Align the batch selection checkbox with other elements
* Expand a bit space between the quick action icon and text
> chore: beautify home layout

- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
Followup https://github.com/bytebase/bytebase/pull/5061
> chore: wording change for ChatSQL

- frontend/src/components/SQLReview/components/SQLRuleTable.vue
> chore(frontend): allow editing while a sql review rule is disabled

- backend/bin/server/cmd/root.go
- frontend/src/components/SchemaEditor/Modals/ActionConfirmModal.vue
- frontend/src/utils/sso.ts
- frontend/src/views/OAuthCallback.vue
- frontend/src/views/ProfileDashboard.vue
- frontend/src/views/auth/Signin.vue
> chore: use redirect instead of open a new window when sign in with SSO

- backend/api/v1/auth_service.go
- frontend/src/views/auth/Signin.vue
only check SSO enabled when creating new user.
> chore: allow user sign in with SSO after license expired

- frontend/src/views/ProfileDashboard.vue
- frontend/src/views/TwoFactorSetup.vue
- frontend/src/views/auth/MultiFactor.vue
Also update the logo layout in MFA page:
| Before | After |
| - | - |
| <img width="353" alt="image" src="https://user-images.githubusercontent.com/24653555/224646045-f5ed136a-5f86-4330-b06f-ad2d3660f711.png"> | <img width="333" alt="image" src="https://user-images.githubusercontent.com/24653555/224645764-53c4abdc-c3e6-4f1a-9ff3-9acd32c6cf3d.png"> |
> chore(2fa): update user doc link

- backend/server/server.go
This will make the external url flag usable again.
> fix: upsert the external url

- backend/server/webhook.go
- backend/store/migration/prod/1.14/003##update_env_id.sql
- backend/store/pg_engine_test.go
- backend/tests/schema_update_test.go
Also, made {{ENV_ID}} matching case-sensitive.
> chore: backfill from ENV_NAME to ENV_ID

- frontend/src/components/CreateDataSourceExample.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
> feat(frontend): add tips for redis create user example

- backend/legacyapi/plan.go
- frontend/src/types/plan.ts
- Define custom approval and risk level feature with FeatureCustomApproval = "bb.feature.custom-approval"
- Define it as an enterprise-only feature.
> feat: define custom approval feature

- frontend/src/components/SQLReview/components/SQLRuleEditDialog.vue
- frontend/src/components/misc/AutoHeightTextarea.vue
- frontend/src/composables/useVModel.ts
- frontend/src/utils/util.ts
> feat(frontend): support multiple line for SQLRuleEditDialog

- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/plugins/ai/components/DynamicSuggestions.vue
> chore: minor tweak ChatSQL UX

- frontend/src/components/RepositoryForm.vue
> fix(frontend): replace placeholders in example

- frontend/src/components/Issue/TaskRunTable.vue
> fix(frontend): view-change link for SDL task runs

- frontend/src/components/GeneralSetting/AIAugmentationSetting.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/plugins/ai/components/AIChatToSQL.vue
- frontend/src/plugins/ai/components/MockInputPlaceholder.vue
Clicking on the "input" will redirect to the Settings-General-AI Augmentation section
> feat(chat-sql): add a mock prompt input when the feature is not enabled

- backend/plugin/db/clickhouse/migrate.go
- backend/plugin/db/driver.go
- backend/plugin/db/mysql/migrate.go
- backend/plugin/db/pg/migrate.go
- backend/plugin/db/snowflake/migrate.go
- backend/server/server.go
Or we get the error `extended protocol limited to 65535 parameters` and OOM.
> fix: backfill migration history by chunks

- backend/plugin/parser/transform/mysql/transform.go
- backend/plugin/parser/transform/mysql/transform_test.go
> chore: add constraint name check for SDL format

- frontend/src/plugins/ai/components/AIChatToSQL.vue
- frontend/src/plugins/ai/components/ChatPanel.vue
- frontend/src/plugins/ai/components/ChatView/CodeView.vue
- Remove and disable "Run automatically"
- Remove the restriction of "SELECT", when we ask a question that might be DML or DDL, the AI's answer might start with some natural languages. Then we need to modify the statements manually before executing.
FYI @Candybase
> feat(sql-editor): minor improvements of ChatSQL

- frontend/src/plugins/sql-lsp/server/complete/candidates/keywords/index.ts
> fix(frontend): vite lint warning

- frontend/src/components/RepositoryForm.vue
> chore(frontend): "learn more" link for "Schema change type"

- frontend/src/plugins/ai/store/conversation.ts
This won't break the JS but we fix it.
> fix(chatsql): cleanup chat db without exceptions

- backend/store/migration/dev/LATEST.sql
Forgot about that in https://github.com/bytebase/bytebase/pull/5167 ...
> fix(schema): missed dev schema

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/grpcweb/index.ts
- frontend/src/main.ts
hopefully to solve the uint64 problems.
> chore(frontend): upgrade nice-grpc-web version

- backend/api/v1/common.go
- backend/api/v1/review_service.go
- backend/api/v1/review_service_test.go
- backend/server/server.go
- impl review service GetReview
- ApproveReview is TBD
Note that only review.ApprovalTemplates and review.Approvers are set.
> feat: impl review service GetReview

- backend/store/risk.go
So that we have a consistent order.
> feat: sort risk rows

- backend/plugin/vcs/bitbucket/bitbucket.go
- backend/plugin/vcs/bitbucket/bitbucket_test.go
- backend/plugin/vcs/internal/oauth/oauth.go
- backend/server/project.go
- backend/server/webhook.go
- frontend/src/types/oauth.ts
This PR implements the webhook handling logic for Bitbucket Cloud.
Create issue from webhook:
Latest writeback:
The integration test will be added in a subsequent PR.
---
Part of https://github.com/bytebase/bytebase/issues/4857
> feat(bbc): handle webhook for repository pushes

- frontend/src/components/GeneralSetting/AIAugmentationSetting.vue
So user can relate this to the OpenAI console
> chore: reveal last 4 letters for the api key

- backend/legacyapi/task_check_run.go
- backend/runner/taskcheck/scheduler.go
- backend/runner/taskcheck/statement_type_report_executor.go
- backend/server/server.go
> feat: impl statemet type report task check

- frontend/src/components/SQLReview/components/SQLRuleTable.vue
- frontend/src/locales/sql-review/en-US.json
- frontend/src/locales/sql-review/zh-CN.json
* Update SQL review locales;
* Add description field into rule table;
> chore: update sql review locales

- backend/legacyapi/task_check_run.go
- backend/runner/taskcheck/scheduler.go
- backend/runner/taskcheck/statement_affected_rows_report_executor.go
- backend/server/server.go
> feat: task check statement affected rows report

- backend/plugin/db/mysql/mysql.go
https://sourcegraph.com/github.com/go-sql-driver/mysql/-/blob/README.md?L288
> chore: unset max allowed packet size

- backend/runner/approval/runner.go
Set ApprovalFindingDone to true directly for issues with unknown risk source.
> fix: no need to find for RiskSourceUnknown issues

- frontend/src/components/GeneralSetting/AIAugmentationSetting.vue
> chore(frontend): update open ai docs link

- backend/legacyapi/task_check_run.go
- backend/runner/taskcheck/scheduler.go
- backend/runner/taskcheck/statement_affected_rows_report_executor.go
- backend/runner/taskcheck/statement_type_report_executor.go
> fix: disable task reports for large sql

- backend/api/v1/review_service.go
- backend/bin/server/cmd/profile_dev.go
- backend/bin/server/cmd/profile_release.go
- backend/component/config/profile.go
- backend/runner/approval/runner.go
- backend/runner/apprun/runner.go
- backend/runner/taskrun/scheduler.go
- backend/server/issue.go
- backend/server/server.go
- backend/server/stage.go
- backend/server/task.go
- backend/server/webhook.go
- backend/tests/external_approval_test.go
- backend/tests/issue.go
- backend/tests/tests.go
- backend/utils/utils.go
- set ApprovalFindingDone to false when patching task statement
- check if approved when deploying
> feat: dismiss stale review & check if approved when deploying

- frontend/src/store/modules/actuator.ts
- frontend/src/views/auth/Signin.vue
- Auto login
- Not show the upgrade remind modal
> chore: optimize for saas

- backend/api/v1/risk_service.go
- backend/api/v1/setting_service.go
- backend/runner/approval/runner.go
- backend/server/issue.go
- backend/server/server.go
Add feature guard for risk center and custom approval. They share the bb.feature.custom-approval tag.
> chore: add feature guard

- frontend/src/components/InstanceForm.vue
> chore: update instance list style

- backend/store/risk.go
- backend/store/store.go
You can't tell from unset and nil array using atomic.Value....
> fix: risks cache

- backend/plugin/vcs/bitbucket/bitbucket.go
- backend/tests/fake/bitbucket.go
- backend/tests/fake/github.go
- backend/tests/schema_update_test.go
Closes https://github.com/bytebase/bytebase/issues/4857
> test(bbc): add schema update integration test

- backend/server/project_member.go
- backend/store/project.go
- backend/store/project_member.go
> fix: backfill project member id

- frontend/src/components/CustomApproval/Settings/components/CustomApproval/RulesPanel/RuleSelect.vue
- frontend/src/components/CustomApproval/Settings/components/RiskCenter/RiskDialog/RiskDialog.vue
- frontend/src/components/CustomApproval/Settings/components/RiskCenter/RiskTable.vue
- frontend/src/components/CustomApproval/Settings/components/common/ExprEditor/ConditionGroup.vue
- frontend/src/components/CustomApproval/Settings/components/common/ExprEditor/components/common.ts
- frontend/src/components/CustomApproval/Settings/components/common/RiskFilter/RiskFilter.vue
- frontend/src/components/InstanceForm.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/utils/instance.ts
- Update and add missing placeholders and tooltips' wording.
- Update risk config modal dialog.
- Won't switch to another panel when viewing approval flow on the approval rule panel. (Close BYT-2908)
- Adjust risk table layout.
- Adjust risk and approval rule filter layout.
- Adjust the order of db engines, using the same order as the instance creation form. (Close BYT-2909)
FYI @Candybase
> fix(frontend): minor fixes for risk center, approval flow and issue review

- frontend/src/components/Issue/TaskCheckResultDefinitionModal.vue
- frontend/src/components/Issue/TaskCheckRunPanel.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/types/pipeline/task.ts
Followup https://github.com/bytebase/bytebase/pull/5302
> chore: add check result details modal

- backend/api/v1/acl_config.go
only DBAs and owners can update/create/delete risks.
> fix(acl): risk service

- frontend/src/components/Issue/IssueHighlightPanel.vue
- frontend/src/components/Issue/review/IssueReviewForm.vue
- frontend/src/components/Issue/review/IssueReviewSidebarSection.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/plugins/issue/logic/review/context.ts
- frontend/src/plugins/issue/logic/review/index.ts
- frontend/src/store/modules/review.ts
- frontend/src/views/IssueDetail.vue
- Layout of the review approval confirm dialog
- Some wordings
FYI @RainbowDashy @Candybase
> feat(frontend): show issue review flow generation error and retry 

- backend/runner/approval/runner.go
Use done because some tasks need wait for task reports
Delete the issue if
- encountered errors
- finished finding (done)
> fix: approval finder, use done because some tasks need wait for task reports

- frontend/src/components/Issue/IssueHighlightPanel.vue
- frontend/src/utils/role.ts
… (#5318)
* chore: allow DBAs to manage risk center and custom approval
* fix: rollout button
> chore(frontend): allow DBAs to manage risk center and custom approval (cherry-pick #5318)

- frontend/src/components/PricingTable/PricingTable.vue
- frontend/src/views/Home.vue
Not sure why the auto cp failed https://github.com/bytebase/bytebase/pull/5335#issuecomment-1490072024
* chore: optimize for saas
* fix: subscription
* fix: lint
> chore: cherry pick 1.15.0

- backend/plugin/db/mysql/rollback.go
- backend/plugin/db/mysql/rollback_test.go
The body could be "" and would lead to error.
Close BYT-2928
> fix: get rollback, skip if the body is empty

- frontend/src/locales/sql-review/en-US.json
- frontend/src/locales/sql-review/zh-CN.json
> chore: update enforce NOT NULL column description

- frontend/src/components/Issue/BatchTaskActionForm.vue
- frontend/src/components/Issue/IssueStatusTransitionButtonGroup.vue
- frontend/src/components/Issue/TaskExtraActionsButton.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/utils/task.ts
Close BYT-2709
https://user-images.githubusercontent.com/2749742/229677526-e51e61d3-283d-432d-b9fd-13fffe943783.mp4
> feat(frontend): batch skip failed tasks in current stage

- frontend/src/components/CreateDataSourceExample.vue
https://github.com/bytebase/bytebase/pull/5356 followup
> chore: refine snowflake grant instruction

- frontend/src/components/InstanceForm.vue
> chore: use grid-cols-4 for engine list in instance form

- frontend/src/components/Issue/IssueSidebar.vue
> feat(frontend): display instance label for low privileged users

- frontend/src/components/Issue/IssueTaskStatementPanel.vue
Sry for something left behind to commit in #5408
> fix(frontend): wrong importing path

- backend/legacyapi/policy.go
> feat: add slow query policy

- backend/legacyapi/plan.go
- frontend/src/components/SlowQuery/Settings/SlowQuerySettings.vue
- frontend/src/components/SlowQuery/Settings/components/SlowQueryPolicyTable.vue
- frontend/src/components/SlowQuery/Settings/components/index.ts
- frontend/src/components/SlowQuery/Settings/index.ts
- frontend/src/components/SlowQuery/index.ts
- frontend/src/components/v2/Form/SpinnerSwitch.vue
- frontend/src/components/v2/Form/index.ts
- frontend/src/components/v2/Model/EnvironmentName.vue
- frontend/src/components/v2/Model/InstanceName.vue
- frontend/src/components/v2/Model/index.ts
- frontend/src/components/v2/TabFilter/EnvironmentTabFilter.vue
- frontend/src/components/v2/TabFilter/TabFilter.vue
- frontend/src/components/v2/TabFilter/index.ts
- frontend/src/components/v2/TabFilter/types.ts
- frontend/src/components/v2/index.ts
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/router/index.ts
- frontend/src/store/modules/index.ts
- frontend/src/store/modules/slowQueryPolicy.ts
- frontend/src/types/plan.ts
- frontend/src/types/policy.ts
- frontend/src/utils/instance.ts
- frontend/src/utils/role.ts
- frontend/src/views/SettingSidebar.vue
- frontend/src/views/SettingWorkspaceSlowQuery.vue
> feat(frontend): workspace slow query settings

- frontend/src/locales/zh-CN.json
- frontend/src/views/BannerExternalUrl.vue
- frontend/src/views/SettingWorkspaceGeneral.vue
Moreover
* Do not translate external url
* Put external url setting at first since it's the basic setting
> chore: navigate external-url banner to the general setting

- frontend/src/locales/zh-CN.json
Close BYT-2943
Caution: legacy data won't be updated.
> chore(frontend): translation for custom approval

- frontend/src/components/Issue/IssueTable.vue
- frontend/src/components/Issue/review/CurrentApprover.vue
- frontend/src/components/Issue/review/IssueReviewPanel.vue
- frontend/src/components/Issue/review/index.ts
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/plugins/issue/logic/review/index.ts
- frontend/src/store/modules/issue.ts
> feat(frontend): show current approver in issue list

- frontend/src/components/MemberTable.vue
- frontend/src/views/SettingWorkspaceMember.vue
> chore: add 2FA enabled column to member table

- frontend/src/bbkit/BBCheckbox.vue
- frontend/src/components/GeneralSetting/SecuritySetting.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
> chore: add require 2FA setting in UI

- frontend/src/assets/css/tailwind.css
- frontend/src/bbkit/BBGrid/BBGrid.vue
- frontend/src/bbkit/types.ts
- frontend/src/components/TransferDatabaseForm/TransferMultipleDatabaseForm.vue
> feat(frontend): group databases by environment while transferring databases

- frontend/src/components/TransferDatabaseForm.vue
- frontend/src/components/TransferDatabaseForm/TransferSourceSelector.vue
- frontend/src/components/v2/Form/SearchBox.vue
- frontend/src/components/v2/Form/index.ts
- frontend/src/components/v2/Select/InstanceSelect.vue
- frontend/src/components/v2/Select/index.ts
- frontend/src/components/v2/index.ts
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
> feat(frontend): support filtering instance while transferring databases

- frontend/src/components/Issue/logic/common.ts
- frontend/src/components/MonacoEditor/MonacoEditor.vue
> fix(frontend): make format statement feature works only for SQL language

- frontend/src/bbkit/BBCheckbox.vue
Still have dirty state bug, revert the changes first.
> chore: revert BBCheckbox changes

- frontend/src/components/GeneralSetting/SecuritySetting.vue
Use naiveui checkbox to prevent dirty state.
> chore: use naiveui checkbox

- backend/runner/taskrun/scheduler.go
Fix the bug where we have two "stage begins" activities.
> fix: stage activity begin

- frontend/src/components/CustomApproval/Settings/components/common/ExprEditor/components/FactorSelect.vue
- frontend/src/components/CustomApproval/Settings/components/common/ExprEditor/components/OperatorSelect.vue
- frontend/src/components/CustomApproval/Settings/components/common/utils.ts
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
> feat(frontend): readable factor and operator texts for risk condition configuring

- frontend/src/utils/tab.ts
- frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue
> feat(sql-editor): remove incorrect actions from context menu

- backend/api/v1/setting_service.go
- backend/server/setting.go
> chore: skip check external url when it's empty
