bytebase/bytebase

go.mod
go.sum
server/project.go

IMPORTANT: Unresolved CVE on latest release (CVE-2021-3538 )
https://github.com/satori/go.uuid/issues/115
Add deprecation notice in favor of github.com/gofrs/uuid and archive
this repo
https://github.com/satori/go.uuid/issues/84
more issues: https://github.com/satori/go.uuid/issues/
use github.com/google/uuid, which is more active

Replace unmaintained uuid package

---

plugin/db/pg/pg.go

Rename excludedDatabases to excludedDatabaseList to match the naming in mysql and clickhouse.

Rename excludedDatabases for consistency

---

plugin/db/pg/pg.go

Skip providers created databases used for monitoring, audit and etc. when using PostgreSQL.

fix #30: skip internal databases from cloud service providers

---

frontend/src/assets/css/tailwind.css

Fixed #29. By making tooltip-wrapper position:relative. But it may still be clipped by its ancestor(s).

Fix tooltip position

---

server/activity_manager.go

Break CreateActivity into smaller parts to improve readability.
Creation of the `WebhookContext` is extracted as a new method and moved outside the loop, so that it's not repeated for each webhook.

refactor: Break CreateActivity into smaller parts to improve readability

---

frontend/src/bbkit/BBAttention.vue
frontend/src/bbkit/BBStepTab.vue
frontend/src/components/DatabaseMigrationHistoryPanel.vue
frontend/src/components/InboxList.vue
frontend/src/components/PrincipalAvatar.vue
frontend/src/components/ProjectMigrationHistoryPanel.vue
frontend/src/components/ProjectVersionControlPanel.vue
frontend/src/components/ProjectWebhookForm.vue
frontend/src/components/ProjectWebhookPanel.vue
frontend/src/components/RepositoryConfigPanel.vue
frontend/src/components/RepositoryForm.vue
frontend/src/components/RepositorySelectionPanel.vue
frontend/src/components/RepositorySetupWizard.vue
frontend/src/components/RepositoryVCSProviderPanel.vue
frontend/src/components/VCSProviderBasicInfoPanel.vue
frontend/src/components/VCSProviderConfirmPanel.vue
frontend/src/components/VCSProviderOAuthPanel.vue
frontend/src/components/VCSSetupWizard.vue
frontend/src/layouts/DashboardLayout.vue
frontend/src/views/IssueDashboard.vue
frontend/src/views/MigrationHistoryDetail.vue
frontend/src/views/OAuthCallback.vue
frontend/src/views/ProjectWebhookCreate.vue
frontend/src/views/ProjectWebhookDetail.vue
frontend/src/views/SettingWorkspaceGeneral.vue
frontend/src/views/SettingWorkspaceVCS.vue
frontend/src/views/SettingWorkspaceVCSCreate.vue
frontend/src/views/TableDetail.vue

Also fixed some potential bugs.
* `import xxx from "@vue/runtime-core"` -> `import xxx from "vue"`
* `import xxx from "@vue/reactivity"` -> `import xxx from "vue"`
Recommend alway import from `"vue"` when we use some Vue's API

fix: fixed the reactive api is not worked bug

---

Dockerfile

The "Build and push" step has been broken since the introduction of `typescript-eslint/eslint-plugin@5.4.0` in this [commit](https://github.com/bytebase/bytebase/commit/4449dcdce6e5a137bd4914a427863bf3b04a1701).
In this PR, the base Docker image is changed to use node 14.17.3.

fix: typescript-eslint/eslint-plugin@5.4.0 requires ^14.17.0

---

plugin/advisor/mysql/mysql_migration_compatibility_advisor.go
plugin/advisor/mysql/mysql_migration_compatibility_advisor_test.go
plugin/advisor/mysql/mysql_syntax_advisor.go

All failed Go tests are fixed, now we can run `go test ./...`.

refactor: Fix method comment, simplify code and fix tests

---

plugin/db/util/driverutil.go

Introduced in https://github.com/bytebase/bytebase/commit/3c583ac3aea8dd88936dafc3632d6dc2eb3107e6

fix: correct the comment about why we skip getting the current db upon migration

---

frontend/package.json
frontend/src/components/BookmarkListSidePanel.vue
frontend/src/components/DatabaseListSidePanel.vue
frontend/src/components/KBar/KBarFooter.vue
frontend/src/components/KBar/KBarHelper.vue
frontend/src/components/KBar/KBarWrapper.vue
frontend/src/components/KBar/RenderResults.vue
frontend/src/components/KBar/useRecentVisit.ts
frontend/src/components/KBar/utils.ts
frontend/src/components/ProjectListSidePanel.vue
frontend/src/components/QuickActionPanel.vue
frontend/src/locales/en.yml
frontend/src/locales/zh-CN.yml
frontend/src/views/DashboardHeader.vue
frontend/yarn.lock

- Introduce Recent Visit actions to kbar, with `g, 1|2|3` shortcuts.
- Introduce i18n selection actions in kbar, with nested actions UI experience.
- Majority of kbar actions now supports i18n.
screenshots

feat(frontend): better kbar experience

---

frontend/src/shims-vue-globals.d.ts

Now volar will complain no more about custom variables and function in templates.
e.g. humanizeTs(), isRelease
Before:
After:

feat(frontend): add type shims to vue custom globals

---

frontend/src/components/MemberTable.vue

Find two small bugs need to fix:
- The role column in the member table need to add `whitespace-nowrap` class, otherwise Chinese string will force to wrap
English looks good:
But Chinese will force to wrap:
After add the class:
- The tooltip in the role column should hidden if no content to show
Before: you can get a empty tooltip, pretty like a strange bug
After:

fix: ui fix for member selector

---

store/migration/10001__init_schema.sql

This is the `shema` change for allowing users to specify the earliest allowed execution time for a task

feat: added not_before_ts to TABLE task

---

frontend/.prettierrc

To ensure the same formatting result in every developer's editor

feat(frontend): specify prettier printWidth to 80

---

helm-charts/bytebase/.helmignore
helm-charts/bytebase/Chart.yaml
helm-charts/bytebase/README.md
helm-charts/bytebase/templates/_helpers.tpl
helm-charts/bytebase/templates/service.yaml
helm-charts/bytebase/templates/statefulset.yaml
helm-charts/bytebase/values.yaml

Create a Helm chart for Bytebase so that it can be installed into a Kubernetes cluster in one command.
The attached screenshot shows Bytebase running inside my Kubernetes cluster, accessed through a forwarded port to my host.

chore: create Helm chart for Bytebase

---

bin/server/cmd/root.go

Systems like Kubernetes expect containers to trigger graceful shutdown within some period after receiving a SIGTERM.
As discussed in https://github.com/bytebase/bytebase/discussions/165, Windows is not a target system of Bytebase, so it's OK to just use `syscall.SIGTERM`. Otherwise, we'll have to use conditional build based on operating systems.

feat: trigger graceful shutdown on both SIGINT and SIGTERM

---

frontend/src/shims-vue-globals.d.ts

This will fix a TypeScript complaint when using `moment` in vue templates.
Before:
After:

fix(frontend): fix moment type importing

---

api/repository.go
external/gitlab/gitlab.go
server/project.go
server/task_executor_schema_update.go
server/webhook.go
store/repository.go

https://github.com/bytebase/bytebase/issues/108
GitLab has implemented the access token expiration with 2h duration since version 14.X. The issue above happens when we use an expired token to call GitLab with oauth errors in the HTTP response. Then we would use the error response for actual usage such as schema migration. The fix is to refresh access token on token expiration oauth error and write through repository.

fix(issue-108): refresh access token and update repository when it's expired

---

frontend/src/App.vue
frontend/src/bbkit/BBModal.vue
frontend/src/bbkit/BBModalStack.vue
frontend/src/components/KBar/KBarWrapper.vue
frontend/src/components/StatusTransitionForm.vue
frontend/src/components/TaskCheckBar.vue

Now, `BBModal` can stack.
- Introducing a new component `BBModalStack` to manage all `BBModal` instances.
- Only the foremost `BBModal` will response to `ESC` keypress.
- The semitransparent mask of `BBModal` has been moved to `BBModalStack`. It's now global unique no matter how many modal dialogs are visible at the same time. (Otherwise the background will become dimmer and dimmer when we have more and more modal dialogs)
- Disable kbar when any `BBModal` is shown.
- Allow to check alter schema check detail status when approving the issue. (this is a first-step practicing of this feature)

feat(frontend): allow modal dialogs stacking

---

store/label.go

Should not include old labels in return values.

fix(tenancy): fix SetDatabaseLabelList return

---

frontend/src/locales/zh-CN.yml

`Sign in` should be translate to `登录` or `登入` but not `登陆`.

fix: signin word error in i18n

---

frontend/src/components/AlterSchemaPrepForm.vue
frontend/src/components/ProjectMemberPanel.vue

Wrap inputs in labels to make them easier to click on.
I have encountered a problem though:
When the `input` elements are moved inside the `label` element, they get moved down a little bit and are not aligned vertically with the labels. Any idea how to fix this?

style: wrap input in labels

---

frontend/src/components/KBar/RenderResults.vue

fix(frontend): fix kbar word wrapping and overflowing

---

server/task_check_scheduler.go

changed payload field from marshal entire `task` to `api.TaskCheckEarliestAllowedTimePayload`

fix: fixed marshal payload

---

frontend/src/store/modules/database.ts

Now, at Project Detail page, when transferring a database, the Database table is not updated (needs to refresh manually).
This change will fix this. By maintaining both `databaseListByInstanceId` and `databaseListByProjectId`.

fix(frontend): update both list map when upserting database(s)

---

plugin/db/ssl.go
plugin/webhook/dingtalk.go
plugin/webhook/discord.go
plugin/webhook/feishu.go
plugin/webhook/slack.go
plugin/webhook/teams.go
plugin/webhook/wecom.go

The `io/ioutil` package has been deprecated in Go 1.16 (See https://golang.org/doc/go1.16#ioutil). This PR replaces the existing `io/ioutil` functions with their new definitions in `io` and `os` packages.

refactor: move from io/ioutil to io and os packages

---

frontend/src/main.ts
frontend/src/store/modules/auth.ts
frontend/src/store/modules/issueSubscriber.ts

This may cause some wrong state update at the frontend.
I spotted this bug when I started Bytebase in demo + readonly mode. 
Most HTTP methods are forbidden under readonly mode, however, I was still able to update some states at the frontend.

fix: error should be passed down to the caller,  NOT be negelected in the interceptor

---

plugin/vcs/gitlab/gitlab.go
server/project.go
server/task_executor_schema_update.go
server/webhook.go

There are 2 bugs fixed in this PR
1. Add the missing access token when passing to the underlying vcs method; Also use the full path when creating/overwriting the schema file during schema file writeback. This was broken when doing the vcs refactor at https://github.com/bytebase/bytebase/pull/312
2. Only return error during token refresh if it's an oauth error from the response body. For response body returning status code like 404, we do not return error, and instead just return the resp as is. This behavior was accidentally changed when adding the refresh token logic at https://github.com/bytebase/bytebase/pull/173

fix(vcs): fix the broken VCS integration

---

frontend/package.json
frontend/src/components/DatabaseBackupCreateForm.vue
frontend/src/components/InboxList.vue
frontend/src/components/IssueActivityPanel.vue
frontend/src/components/IssueHighlightPanel.vue
frontend/src/components/IssueSidebar.vue
frontend/src/main.ts
frontend/src/plugins/dayjs.ts
frontend/src/shims-vue-globals.d.ts
frontend/src/utils/util.ts
frontend/src/views/MigrationHistoryDetail.vue
frontend/test/dayjs.test.ts
frontend/vite.config.ts
frontend/yarn.lock

Add the complete test case in `/frontend/test/dayjs.test.ts`
After installing `vitest`, we can use the script: `yarn test` to test the API conformance of `dayjs` with `moment.js`
When merging this PR. Next time I will remove the dependency of moment.

refactor(frontend): replace moment using dayjs

---

server/task_check_executor_timing.go
server/task_check_scheduler.go
server/task_scheduler.go

Before this PR, all tasks need to pass timing task check during scheduling, and the logic in the task check will block this task from being scheduled.

fix: enabled timing task check only for schema update

---

api/issue.go
api/task.go
plugin/db/driver.go
plugin/db/mysql/mysql_migration_schema.sql
server/issue.go
server/server.go
server/task.go
server/task_check_scheduler.go
server/task_executor.go
server/task_executor_data_update.go
server/task_executor_schema_update.go
server/task_scheduler.go
server/webhook.go

Add the dedicated data update issue and task type. It's mostly similar to the corresponding schema update issue and task type. We make them separate so it's easier to extend them individually later.
The leftover is tenant mode doesn't support data migration. We need to do some refactoring to make it work (the current logic is kind of coupled with scheme update)
Part of supporting https://github.com/bytebase/bytebase/issues/337

feat: backend support for data migration (DML change)

---

.github/workflows/build-release-image.yml

This action builds and pushes Docker images with the tag that triggers it, which is like `*.*.*` (e.g. `1.0.0`).
I've tested it in my repo, see https://github.com/qsliu2017/bytebase/actions/runs/1711168368.

chore(ci): add build release image workflow

---

api/project.go
api/project_test.go

We allow {{ENV_NAME}} and {{DESCRIPTION}} as optional placeholder in the repo file path template.
We allow {{ENV_NAME}} as optional placeholder in the schema file template.
Also fix the test case

fix: allow optional placeholder in the file path template and schema path template

---

.github/workflows/build-release-image.yml

see my run result https://github.com/qsliu2017/bytebase/actions/runs/1711762777.
e.g. when push branch named `chore/pre_release_1.0.0`, this action builds and pushes `bytebase/bytebase:1.0.0` and `bytebase/bb:1.0.0`.

chore(ci): build release image on pushing branch `chore/pre_release_*.*.*`

---

frontend/src/components/InstanceConnectionForm.vue
frontend/src/components/InstanceForm.vue
frontend/src/views/SettingSidebar.vue

Noticed this when observing peers setting up the instance.
1. Provide guidance on how to start a MySQL instance.
2. Trim hard to find whitespace

fix: add link to our mysql setup guide and trim the enclosing whitespace

---

.github/workflows/notify-dependency-changes.yml

This grants access to the GITHUB_TOKEN so the action can make calls to GitHub's rest API

fix(ci): trigger `notify-dependency-changes` on `pull_request_target`

---

frontend/package.json
frontend/vite.config.ts
frontend/yarn.lock

`vite-plugin-icons` has been renamed to [unplugin-icons](https://github.com/antfu/unplugin-icons#unplugin-icons)
and this package has been deprecated 
https://www.npmjs.com/package/vite-plugin-icons
and also this package `vite-plugin-components`  has been deprecated

refactor(frontend): use the unplugin instead old plugin

---

frontend/src/layouts/ProjectLayout.vue

- Refactor the logic to find selected tab bar's index by URL hash. Use dynamic searching instead of hard-coded indices.
- Put "Deployment Config" before "Settings" in tenant mode.
- Hide "Migration History" in tenant mode. (Advised by @d-bytebase ).

feat: allowing dynamic ordering of tab items

---

frontend/src/bbkit/BBSelect.vue

Refactor `<BBSelect>` using naive-ui components.
Components effected by this change: `<IssueStatusSelect>`, `<MemberSelect>`, `<ProjectRoleSelect>`, `<RoleSelect>`, `<DatabaseLebelForm>`.
This benefits us by:
- Moving the popup out of the `<div>` wrapping `<button>` to the `<body>`, allowing `<button>` to be "overflow:hidden".
- naive-ui will manage the popup's placement dynamically when it is closed to the edge of window.
Why do not we use `<NSelect>` of naive-ui?
- Hard to overwrite the button's style of `<NSelect>`.
- Complex data type conversion.
Why do not we use `<NPopselect>` of naive-ui?
- Hard to overwrite the popup's style of `<NPopselect>`.
- Complex data type conversion.
- Currently existing a bug that the popup's width can't follow to the button's. (Posted to the author …

feat(frontend): refactor BBSelect using naive-ui components

---

plugin/db/util/driverutil.go

this PR just simple do not execute baseline script except for creating database. later we will remove baseline migration type
Close #394

fix: baseline will not execute sql

---

frontend/src/locales/en.yml
frontend/src/locales/zh-CN.yml
frontend/src/views/AnomalyCenterDashboard.vue
server/anomaly_scanner.go

Add feature guard for schema drift.
But I'm confused about this feature, seems users cannot config it in the UX? It's hard to show what this feature is and what it can bring to users.

feat: feature guard for schema drift

---

frontend/src/store/modules/inbox.ts
server/acl.go
server/acl_casbin_policy_dba.csv
server/acl_casbin_policy_developer.csv
server/acl_casbin_policy_owner.csv
server/inbox.go

Fixed: improper authorization to view another user's inbox.
The main reason of this problem in code level is that inboxFind.ReceiverID is passed in query parameter which could be different from the saved current principalID in jwt. So the user could pass another user id to get their inbox.

feat: add GET_SELF handler in `acl.go`

---

scripts/.air.toml

Send SIGINT to backend when restarting to make sure the sqlite database is closed properly.
This PR is blocked by [a PR for air](https://github.com/cosmtrek/air/pull/223).
After this change, I start to see the "BYE" banner when I make a change:

fix: send SIGINT to clean up resources

---

frontend/src/components/DatabaseLabels/DatabaseLabelPropItem.vue
frontend/src/components/DatabaseLabels/DatabaseLabelProps.vue
frontend/src/components/DatabaseLabels/index.ts
frontend/src/views/DatabaseDetail.vue

- Render db labels as if they are normal props.
- A label is not editable if it's a placeholder in dbNameTemplate.
Screenshot

feat: render db labels as if they are normal props

---

frontend/src/components/CreateDatabasePrepForm.vue
frontend/src/components/Issue/IssueSidebar.vue
frontend/src/views/DatabaseDetail.vue

Enable label-related features for standard mode projects.
**This is a proposal PR**, so feel free to reject if it's not good.
These features are now also available for standard mode projects.
- Allow to set Tenant and Location as optional props when creating database.
- Allow to display and edit Tenant and Location in the upper area of database detail page.
- Display Tenant and Location in issue sidebar.

feat: enable label related features for standard mode projects

---

.github/workflows/tests.yml
go.mod
go.sum

Signed-off-by: tison <wander4096@gmail.com>
A follow up to https://github.com/bytebase/bytebase/pull/611 so that we can get a clean, converged go.mod & go.sum.
This also prevents developers getting a dirty workspace locally when building with a tidy step without effectively dep changes.
cc @tianzhou @d-bytebase sorry to make it a follow up instead of integrated with #611.

test: add tidy ci task

---

frontend/src/components/Issue/IssueDetailLayout.vue
frontend/src/components/Issue/IssueStatusTransitionButtonGroup.vue
frontend/src/components/Issue/IssueTaskStatementPanel.vue
frontend/src/plugins/issue/DatabaseDataUpdateTemplate.ts
frontend/src/plugins/issue/DatabaseSchemaUpdateTemplate.ts
frontend/src/views/IssueDetail.vue

We are going to retire issue rollback feature. 
This PR will retire these features below:
- "Rollback" button in the upper part of issue detail page.
- "Rollback SQL" code text area in the middle part of issue detail and creation page.
- Related logic code to create rollback issue according to `rollbackIssueId`.

feat: retire issue rollback feature

---

frontend/src/locales/en.yml
frontend/src/locales/zh-CN.yml
frontend/src/views/SettingWorkspaceLabel.vue

**Before**
**Improvements**
1. Capitalize.  Location, Tenant, Environment
2. Add a text describing the usage and include the link to our doc
3. Use "Manage" link which jumps to the environment page instead of having a disabled "+" button
**After**

chore: label setting improvement

---

frontend/package.json
frontend/yarn.lock

We are upgrading these packages because they are reported as vulnerable by github.
- follow-redirects (depended by axios)
- nanoid (depended by postcss)
- ansi-regex (depended by eslint-formatter-summary and more)
We are fixing them by
- upgrading axios from ^0.21.2 to ^0.26.0, which upgraded follow-redirects from ^1.14.0 to ^1.14.8
- upgrading postcss from ^8.3.5 to ^8.4.6, which upgraded nanoid from ^3.1.30 to ^3.3.1
- removing eslint-formatter-summary, which also removes ansi-regex@^2.0.0, ansi-regex@^3.0.0, ansi-regex@^4.1.0, so now we depends only on ansi-regex@^5.0.1 (hoisted from eslint and naive-ui)

chore: upgrade vulnerable packages

---

frontend/src/bbkit/BBSwitch.vue

BBSwitch maintains an inner state (`on`) to update its appearance, which violates the principle that child-component should be rendered according to its properties passed by its parent.

fix: fixed inconsistent in bbswitch

---

frontend/src/components/MonacoEditor/sqlParser.ts
frontend/src/composables/useExecuteSQL.ts
frontend/src/locales/en.yml
frontend/src/locales/zh-CN.yml
frontend/src/views/SqlEditor/EditorPanel/ExecuteHint.vue

Resolve the issue: https://linear.app/bbteam/issue/BYT-155/run-non-select-dml-should-navigate-to-the-data-change-dml-workflow
We distinguish whether the SQL statement is a DDL or a DML statement by the keywords:
DDL: `create`、`alter`、`drop`
DML: `insert`、`update`、`delete`

feat(sql-editor): run non-SELECT SQL navigate to the different workflow

---

frontend/src/components/TenantDatabaseTable/DatabaseMatrix.vue
frontend/src/components/TenantDatabaseTable/DatabaseMatrixItem.vue
frontend/src/components/TenantDatabaseTable/DeployDatabaseTable.vue
frontend/src/components/TenantDatabaseTable/TenantDatabaseTable.vue
frontend/src/components/TenantDatabaseTable/YAxisRadioGroup.vue

- The card is simplified, with more concentration on db's status by the larger icon.
- The whole card is not clickable anymore. The db name and schema version are clickable instead, redirecting to different tabs of db detail page.
- The labels in popover is rendered as normal db properties, with better text alignment.
- Last successful sync time is no longer displayed on the card. It's only displayed on the popover.
- "Group by" label is removed. Users will learn it after 1st use.
Screenshot

feat: new database matrix UI

---

frontend/src/bbkit/BBModalStack.vue

https://github.com/bytebase/bytebase/pull/176#issuecomment-1051602532

fix: bbkit modal mask is not prevent clicking on elements below the mask layer

---

api/project.go
api/project_member.go
frontend/src/components/ProjectMemberPanel.vue
frontend/src/components/ProjectMemberTable.vue
frontend/src/locales/en.yml
frontend/src/locales/zh-CN.yml
server/project.go
server/project_member.go
store/migration/10001__init_schema.sql
store/pg_engine.go
store/project_member.go
store/project_member_test.go

For project_member table, instead for UNIQUE(project_id, principal_id), we would use UNIQUE(project_id, principal_id, role_provider)
Thus during syncing the role provider, we don't remove the existing member, we just add new members from the new providers.
At at point in time, only members whose role_provider is the same as the project current role_provider is active.
By doing this, switching the role_provider back and forth is just flipping which parts of the project members are active.
The existing behavior of deleting project members would be painful if existing project has a lot of members.

feat: project member with multiple role provider

---

frontend/src/locales/en.yml
frontend/src/locales/zh-CN.yml
frontend/src/views/DatabaseDetail.vue

SQL editors can only query databases in the projects available to the user. For databases in the default project, we should disable or put a warning if the user wants to navigate from database console to SQL editor.

feat: database incorrect project warning

---

server/recover.go

When panic occurs, currently it's difficult to point out the line of code that triggers the panic.
1. Add a panic in some route, for example, `GET /project`
2. Run `go test -run ^TestServiceRestart$ ./...`
`
2022-03-04T14:48:57.228+0800    ERROR   Middleware PANIC RECOVER        {"error": "oops"}
{"time":"2022-03-04T14:48:57+08:00","method":"GET","uri":"/api/project","status":500,"error":""}
/Users/dragonly/bb/bytebase/tests/start_test.go:23: http response error code 500 body "{\"message\":\"Internal Server Error\"}\n"
`
`
2022-03-04T14:50:01.293+0800    ERROR   Middleware PANIC RECOVER        {"error": "oops", "stack": "github.com/bytebase/bytebase/server.recoverMiddleware.func1.1\n\t/Users/dragonly/bb/bytebase/server/recover.go:18\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:10 …

feat: add stack trace to recover middleware

---

frontend/src/views/SqlEditor/AsidePanel/DatabaseTree.vue

[Linear Issue](https://linear.app/bbteam/issue/BYT-264/[sql-editor]-unnecessary-separator-shown-when-using-database-search-bo)
The search result highlights the node uses the CSS Variables `--n-node-color-active` which `naive-ui` provided.

style(sql-editor): use node active color instead the underline style

---

frontend/src/components/PricingTable.vue
frontend/src/locales/en.yml
frontend/src/locales/zh-CN.yml
frontend/src/types/plan.ts

- Use separate lines for 3rd-party login and member sync
- Update the wording in the action button
Before:
After:

feat: several improvements for the subscription page

---

go.mod
go.sum

Bypass pingcap/tidb dependency and fix the security vulnerability introduced by dgrijalva/jwt-go.

fix: fix jwt-go vulnerability

---

store/seed/release/10001__init_seed.sql

in MySQL quickstart, we start a MySQL instance with the empty root password. change this might reduce confuse.

chore: use empty db password in seed

---

plugin/db/util/driverutil.go
tests/tests.go

Fix query result column type name.
For example, the primary key with number type should be `1` not `"1"`.

fix: query result column type name

---

frontend/src/types/tab.ts
frontend/src/views/SqlEditor/TablePanel/TableView.vue
plugin/db/util/driverutil.go
tests/schema_update_test.go
tests/tests.go

Now we only show the column name in the result table. So it will be pretty nice that if we can display its type.
This PR is to add the column types in backend API for future usage.
(BTW, we now use NDataTable to show the query result. But it might be unable to display `type` into it. Maybe I need to write our DataTable component to strengthen the result viewer.)

feat: add query result column types

---

api/auth.go
frontend/src/types/auth.ts
frontend/src/views/auth/Signin.vue
server/auth.go

Before, we pass the oauth content directly from the frontend, making it possible for a middleman attack.
After this PR, we will fetch the oauth content at the backend via an ID provided by the frontend.

fix: fixed a security issue caused by fake VCS

---

server/task.go

Validate PATCH `/pipeline/:pipelineID/task/:taskID/status` assignee ID in backend API level.

fix: validate patch task status assignee

---

plugin/db/mysql/mysql.go

Mysql backup failed when dash('-') in database name, for example: `bytebase_test-blog`.
Test schema can be generated by:
```
sed -i 's/bytebase_test_blog/`bytebase_test-blog`/g' quickstart/test_schema/mysql/2_blog.sql
```

fix: backup failed when dash('-') in database name

---

frontend/src/views/SqlEditor/EditorPanel/SharePopover.vue
frontend/src/views/SqlEditor/TabListContainer.vue

related [issue](https://linear.app/bbteam/issue/BYT-323/consider-using-a-lock-icon-for-the-private-sheet-and-also-show-the)

refactor(sql-editor): show the sheet icon when sheet is not `PRIVATE`

---

store/seed/test/10200__label.sql

Seed DB ID's have been shifted since new DB was inserted.
This PR will fix the ID mapping relationship.

fix: re-mapping db label values

---

plugin/db/mysql/mysql_migration_schema.sql
plugin/db/pg/pg_migration_schema.sql
plugin/db/sqlite/sqlite_migration_schema.sql

This will also improve the query with the where clause of "version < xxxx" without a source.

chore: use unique index (namespace, version) instead of (namespace, source, version) because version should be unique within a namespace

---

frontend/src/plugins/naive-ui.ts

This solution comes from [样式元素位置 - Naive UI](https://www.naiveui.com/zh-CN/light/docs/style-position).

fix: css reset conflicts between tailwindcss v3 and naive-ui

---

frontend/index.html
frontend/src/App.vue

I'm a little bit scared to use `!important` on `<body>`, so I changed a way to set body's font-size, PTAL.

fix: use a more moderate way to set body's font-size

---

bin/server/cmd/profile_dev.go
store/migration/10002__add_vcs_github_com.sql

Adds a migration script to make `GITHUB_COM` be a valid value for both Git and role provider. 
---
Part of https://github.com/bytebase/bytebase/issues/928

feat: add migration for GITHUB_COM to be a valid Git and role provider

---

frontend/src/components/MonacoEditor/MonacoEditor.vue

style(sql-editor): narrow the sql block highlight style

---

plugin/vcs/github/github.go
plugin/vcs/github/github_test.go
plugin/vcs/gitlab/gitlab.go
plugin/vcs/vcs.go

This PR implements the necessary methods of [vcs.Provider](https://github.com/bytebase/bytebase/blob/4dd938f3a58d960bb42576f8ff569c51aa1f0df5/plugin/vcs/vcs.go#L96) interface to support adding GitHub.com as a VCS provider.
1. `retry` is re-structured without `goto`, and respects context cancellation.
1. Signature of `FetchUserInfo` is changed to be provider-agnostic.
1. Functions like `retry`, `refreshToken` and `getOAuthErrorDetails` could be factored out to be used for both GitLab and GitHub, if we want to do that, I can send a followup PR.
---
Part of https://github.com/bytebase/bytebase/issues/928

feat: implement methods of VCS provider workflow for GITHUB_COM

---

Dockerfile

we don't use go-sqlite3 anymore

chore: get rid of CGO

---

frontend/src/shims-vue-globals.d.ts

After switching to pmpm we cannot resolve "@vue/runtime-core" as a phantom dependency. So this breaks the vscode's type hints of our custom global properties in vue templates.
In the latest [Vue's doc](https://vuejs.org/guide/typescript/options-api.html#augmenting-global-properties) it's recommended to augment `vue` instead of `@vue/runtime-core`.

fix: vue global properties's type shims

---

api/auth.go
api/oauth.go
api/repository.go
api/vcs.go
common/oauth.go
frontend/src/components/RepositorySelectionPanel.vue
frontend/src/components/RepositorySetupWizard.vue
frontend/src/components/RepositoryVCSProviderPanel.vue
frontend/src/components/VCSSetupWizard.vue
frontend/src/store/modules/auth.ts
frontend/src/store/modules/gitlab.ts
frontend/src/store/modules/oauth.ts
frontend/src/store/modules/vcs.ts
frontend/src/types/auth.ts
frontend/src/types/project.ts
frontend/src/views/SettingWorkspaceVCSDetail.vue
frontend/src/views/auth/Signin.vue
plugin/vcs/github/github.go
plugin/vcs/gitlab/gitlab.go
plugin/vcs/vcs.go
server/acl.go
server/acl_casbin_policy_dba.csv
server/acl_casbin_policy_developer.csv
server/acl_casbin_policy_owner.csv
server/auth.go
server/oauth.go
server/server.go
server/vcs.go
store/principal.go

function effected:
1. `login via VCS` **both access token and application secret is invisible to the frontend**
2. `set up a VCS for the workspace` **for the user need to set up the secret for the first time, no logic changed**
3. `set up a VCS repo for the project`  **application secret is invisible to the frontend, the access token will still return by the backend for we may still need the token to access VCS resource** 
Possible improvement: store the gitlab token in the cookie just like how we store our access token

feat: move oauth token exchange logic to the backend

---

.goreleaser.yaml

suit goreleaser to our release flow

chore: modify GitHub release page

---

.github/workflows/tests.yml

We're failing tests with
panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt
https://github.com/golangci/golangci-lint/issues/2649

fix: update golangcli-lint to 1.45.2

---

bin/bb/cmd/migrate.go
common/util.go
plugin/db/driver.go
server/issue.go
server/task.go
server/task_executor.go
server/task_executor_database_restore.go
store/pg_engine.go
tests/tests.go

We were using second-level timestamp precision which is the source of the flaky test where consecutive migrations will receive version string conflict error if they are processed within the same second.

fix: add sleep time between issues in tests

---

frontend/src/store/modules/table.ts
frontend/src/types/table.ts

1. Create a table via Bytebase
2. Go to the created table
3. Get exception due to empty indexList

fix: perform correctly when table.indexList is empty

---

plugin/db/driver.go
server/task_executor.go
tests/fake/gitlab.go
tests/tenant_test.go
tests/tests.go

Signed-off-by: cluas <cluas@live.cn>
case:
- tenant template: `{{DB_NAME}}_{{TENTANT}}`
- tenants: `a, b`
- demo db: `demo`
- file path template: `{{DB_NAME}}__{{VERSION}}__{{TYPE}}__{{DESCRIPTION}}.sql`
- example push file: `demo__v0.1.0__migrate__demo.sql`
- tasks after gitops webhook: `task1 {database: demo_a, namespace: demo_a}},  task2 {database: demo_b, namespace: demo_b}}`
but here it parse `{{DB_NAME}}`, in this case,  always is `demo`. so subsequent tasks will immediately go wrong.

fix: tenant mode VSC with DatebaseNameTemplate task execute error

---

plugin/db/mysql/mysql.go

If we have a database name with space in it like "some db name", then `go run bin/bb/main.go dump` will fail on that database because of SQL syntax error.

fix: quote database name in dump statement

---

api/task.go
server/task.go

In https://github.com/bytebase/bytebase/pull/1051, the type of`BlockedBy` is `[]int`, which is enough but is unfortunately not supported by jsonapi (https://github.com/google/jsonapi/issues/209). So in this PR, I change the type to `[]*Task`.

feat(gh-ost): task blocked by implementation

---

bin/bb/cmd/dump.go
bin/bb/cmd/dump_test.go
bin/bb/cmd/migrate.go
bin/bb/cmd/migrate_test.go
bin/bb/cmd/restore.go
bin/bb/cmd/utils.go
bin/bb/cmd/utils_test.go
go.mod
go.sum

Support DSN flag like `--dsn mysql://bytebase@localhost:3306/`
This flag can simplify database settings. Replace
`bb migrate --dbType mysql --username bytebase --password passwd --host localhost --port 3306 --database todo`
with just
`bb migrate --dsn mysql://bytebase:passwd@localhost:3306/todo`.
This simplicity is useful when more than one database is needed in one command, e.g. `bb diff`(coming soon).
we use `xo/dburl` to parse dsn, so that all formats of it are supported. (see https://pkg.go.dev/github.com/xo/dburl#hdr-Example_URLs)

feat(cli): replace db flags with dsn flag

---

api/sheet.go
server/sheet.go
store/demo/dev/10220__sheet.sql
store/sheet.go

* Add `PrincipalID` to make sure that we only find private/project sheets which related project containing PrincipalID as an active member;
* Make `CreatorID` optional to find public sheets.

feat: find sheet with `PrincipalID`

---

plugin/vcs/github/github.go
plugin/vcs/gitlab/gitlab.go

If the address of the host is not the same as the one actually filled in, the error here is not caught and the token actually fails to be fetched, the gitlab returned error is as follows :
```json
{
"error": "invalid_grant",
"error_description": "The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."
}
```
This PR  catches such errors. 
Fixed a few bugs in passing, `http.Response.Body` forget `Close()`

fix: handle gitlab error case

---

frontend/src/types/common.ts

Refactor `unknown` and `empty` function using function overload definitions. They are widely used in our project.
The return type can be inferred from the input argument. So we need no more to use `as XXXX` to do an explicit type conversion when we call them. Here is an example

refactor: typed unknown and empty function

---

store/project_member.go

I don't know why the api.Role conversion is used here, but these operations cause the value of role_provider to become empty when the sql is actually executed

fix: wrong type cause role_provider missing

---

frontend/src/views/SheetDashboard.vue

import `lodash-es` instead of `lodash` in sheetDashboard component.

fix: import `lodash-es` in sheetDashboard

---

frontend/src/locales/en.yml

Fix typo: `listting` to `listing`.

fix: all project description typo

---

frontend/src/components/EnvironmentForm.vue
frontend/src/router/index.ts
frontend/src/store/modules/schemaSystem.ts
frontend/src/views/SettingWorkspaceSchemaReview.vue
frontend/src/views/SettingWorkspaceSchemaReviewCreate.vue
frontend/src/views/SettingWorkspaceSchemaReviewDetail.vue

**Users can redirect to the schema review detail page from the environment page**
**If the environment doesn't have the schema review policy:**
- If the user has permission (is owner or DBA), he can redirect to the creation page with the selected environment:
- Otherwise just show the "no schema review policy" label:
Note:
Add the `isDev` check. This feature is not available for users yet.

feat: show the schema review in the env page

---

frontend/tsconfig.json

This will fix TypeScript complaints about "Cannot write file 'xxxx.js' because it would overwrite input file."
This only effects Visual Studio Code and will apply no effects to our build process. Since vite will re-write the `outDir` of tsconfig.

fix(frontend): typescript complaints

---

frontend/src/views/DashboardHeader.vue

We have highlight for navbar items.
But it failed when diving into nested routes.
And this PR will fix
P.S. this is a very ugly workaround fix. Since if we want to fix it gracefully, we may need a dangerous refactor to our router structure definitions.

fix: highlight navbar items for nested routes

---

api/plan.go
api/schema_system.go
server/server.go
server/task.go
server/task_check_executor_statement_advisor_composite.go
server/task_check_executor_statement_advisor_simple.go
server/task_check_scheduler.go
server/task_scheduler.go

Next step, we need to remove the existed code for `api.TaskCheckDatabaseStatementCompatibility` after we initial the schema review policy for users' environments.

chore: add backward compatibility to schema review policy

---

frontend/src/components/AlterSchemaPrepForm/ProjectTenantView.vue
frontend/src/components/CreateDatabasePrepForm/DatabaseLabelForm.vue
frontend/src/components/DatabaseLabels/DatabaseLabelProps.vue
frontend/src/components/DatabaseLabels/DatabaseLabels.vue
frontend/src/components/DatabaseListSidePanel.vue
frontend/src/components/Issue/IssueSidebar.vue
frontend/src/components/ProjectDeploymentConfigPanel.vue
frontend/src/components/ProjectOverviewPanel.vue
frontend/src/components/ProvideDashboardContext.vue
frontend/src/components/TransferDatabaseForm/SelectDatabaseLabel.vue
frontend/src/store/modules/label.ts
frontend/src/views/SettingWorkspaceLabel.vue

The label list is widely shared in many components. We do not need to fetch it repeatedly. So we
- Keep only one copy of the label list globally.
- Fetch the label list in the global scope (DashboardContextProvider).
- This will also fix a bug that when we sign out an error notification says "Missing access token". (see screenshot below)
- Re-order imports, 3rd-party go upper.

refactor(frontend): fetch label list globally

---

.gitpod.yml

As `init` will be skipped when restarting a Gitpod workspace, the current configuration does not work. `cd frontend` command should be done in `before` to execute both on launching a new workspace and on restarting the stopped workspace.
https://www.gitpod.io/docs/config-start-tasks#restart-a-workspace
On terminating the workspace (after 30/60 min inactive, for example), PostgreSQL server does not always stop correctly but remains `postmaster.pid` file. We should make sure the file does not exist on launching a new/existing workspace.
1. Open https://gitpod.io/#github.com/tnir/bytebase/tree/tnir/gitpod-rework to launch a new workspace on Gitpod cloud.
2. Make sure the Go/JS server launched successfully by confirming the login UI. 👀 
3. Stop the workspace from command palette like `Gitpod: …

chore(gitpod): make it usable on restarting workspace

---

frontend/src/directives/highlight.js

Suppresses warnings from browser console:
```
Deprecated as of 10.7.0. highlightBlock will be removed entirely in v12.0
Deprecated as of 10.7.0. Please use highlightElement now.
```
https://github.com/highlightjs/highlight.js/releases/tag/10.7.0
> Deprecations:
> [...]
> - highlightBlock(el) deprecated as of 10.7.
>    - Please use highlightElement(el) instead.
>    - Plugin callbacks renamed before/after:highlightBlock => before/after:highlightElement
>    - Plugin callback now takes el vs block attribute
>    - The old API and callbacks will be supported until v12.
Follows up 3cdfc37c0484a1caccd77fa8cab20f238b1b797e
Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>

fix(deprecation): replace deprecated highlightBlock with highlightElement

---

frontend/src/layouts/DashboardLayout.vue

| screen size | before | after |
|-|-|-|
| mobile | ![readonly-mode-mobile-before](https://user-images.githubusercontent.com/10229505/167237504-9752c81a-a15b-4231-a9be-0be6e951a269.png) | ![readonly-mode-mobile-after](https://user-images.githubusercontent.com/10229505/167237500-652cef83-dd9f-4a12-aa3a-fe911c750081.png) |
| PC (no regression should be confirmed) | ![readonly-mode-pc-after](https://user-images.githubusercontent.com/10229505/167237502-2f3f6a0a-7f55-4a11-9ab3-9b3702e98a1a.png) | ![readonly-mode-pc-before](https://user-images.githubusercontent.com/10229505/167237503-9ab68d5c-15e2-47bf-b90e-3395459af08d.png) |
Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>

fix(ui): tweak warning message in readonly mode

---

plugin/advisor/advisor.go
plugin/advisor/mysql/advisor_column_required.go
plugin/advisor/mysql/advisor_migration_compatibility.go
plugin/advisor/mysql/advisor_naming_table.go
plugin/advisor/mysql/advisor_naming_table_test.go
plugin/advisor/mysql/advisor_stmt_where_required.go
plugin/advisor/mysql/advisor_syntax.go
server/task_check_executor_statement_advisor_composite.go

- rename `advisorList` to `adviceList` (typo).
- rename `MySQLTableNamingConvention` to `MySQLNamingTableConvention`.
- Let all naming rules have the same prefix `MySQLNamingXxx`.

chore: rename variables in plugin/advisor

---

common/error.go
plugin/advisor/advisor.go
plugin/advisor/mysql/advisor_column_required.go
plugin/advisor/mysql/advisor_naming_column.go
plugin/advisor/mysql/advisor_naming_column_test.go
plugin/advisor/mysql/advisor_naming_table.go
plugin/advisor/mysql/advisor_naming_table_test.go
plugin/advisor/mysql/utils.go
server/task_check_executor_statement_advisor_composite.go

Support MySQL column naming rule.
- Implement a new advisor `MySQLNamingColumnConvention`
- Add a unit test for `MySQLNamingColumnConvention`
- Rename `TableNamingXxx` to `NamingTableXxxx`
Close BYT-459

feat(schema system): support MySQL column naming convention

---

frontend/src/components/Issue/TaskRunTable.vue

This should fix [BYT-483](https://linear.app/bbteam/issue/BYT-483/text-overlapping-happens-when-the-comments-is-too-long)

fix: allow force word break to prevent text overlapping

---

docs/design/pitr-mysql.md

Add a design doc about the Point-in-time Recovery (PITR) feature.
Currently, the design doc focuses on MySQL.
Closes BYT-471.

doc: add design doc about PITR

---

frontend/src/components/Issue/TaskCheckBadgeBar.vue
frontend/src/components/Issue/TaskCheckBar.vue

This should provide a better style when we have more taskCheck items but low screen width. (reported by @dragonly )
Screenshot
Before
After

fix: task-check-bar with more items and lower screen resolution

---

frontend/src/components/Issue/TaskCheckBadgeBar.vue

The current logic to generate `filteredTaskCheckRUnList` is wrong, it results in the duplicate `task check run`.
Close CON-133

fix: wrong `filteredTaskCheckRunList`

---

api/data_source.go
api/instance.go
frontend/src/components/CreateInstanceForm.vue
frontend/src/components/InstanceForm.vue
frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json
frontend/src/types/dataSource.ts
frontend/src/types/instance.ts
server/database.go
server/instance.go

Currently, we sync the schema upon adding/patching the instance, this provides a better UX since the user will see the schema after adding the instance.
However, for instances having large schemas, the request will timeout and prevents them from adding the instance at all.
The solution is to add a "Sync schema afterward" checkbox to allow users to disable the sync if needed. The checkbox only appears if connection-related info is changed.
Also improve existing logic:
1. Add the syncing schema logic after adding/patching the data source.
2. Remove the unneeded Username, Password, UseEmptyPassword field in instancePatch since it has been moved to data source.
3. Also refetch the user info after adding/patching the instance.

feat: make sync schema optional after adding/patching the instance connection info

---

frontend/src/store/modules/oauth.ts
frontend/src/views/SettingWorkspaceVCSDetail.vue
server/oauth.go

https://github.com/bytebase/bytebase/issues/1263
When the user provides a new `application secret`, we need to use the old application secret to perform the oauth process to verify the validity of the `application secret`. So the front-end needs to pass the application secret to the back-end so that the back-end can use the new `application secret` **instead of the back-end using the old `application secret` that fetches from db.**

fix: using new application secret to process oauth 

---

frontend/src/components/Issue/IssueActivityPanel.vue
frontend/src/components/Issue/IssueBanner.vue
frontend/src/components/Issue/IssueDescriptionPanel.vue
frontend/src/components/Issue/IssueDetailLayout.vue
frontend/src/components/Issue/IssueHighlightPanel.vue
frontend/src/components/Issue/IssueOutputPanel.vue
frontend/src/components/Issue/IssueSidebar.vue
frontend/src/components/Issue/IssueStagePanel.vue
frontend/src/components/Issue/IssueStatusTransitionButtonGroup.vue
frontend/src/components/Issue/logic/IssueLogic.ts
frontend/src/components/Issue/logic/base.ts
frontend/src/components/Issue/logic/common.ts
frontend/src/components/Issue/logic/extra.ts
frontend/src/components/Issue/logic/index.ts

This is the last part of the IssueDetail refactor. This time we extract some less-important logic to logic/extra.ts. And extract some base logic to logic/base.ts.
Now IssueDetailLayout.vue has very less logic, and becomes almost a pure view component.
The nested components such as IssueActivityPanel, IssueBanner, IssueSidebar, etc. now can get states and logic from `useExtraIssueLogic()` and `useIssueLogic()`, instead of passing by properties and emitting events.

refactor(frontend): IssueDetail part.4

---

plugin/db/pg/pg.go

compatible with pg 10 trigger event syntax.
https://www.postgresql.org/docs/10/sql-createeventtrigger.html

feat: dump schema support PROCEDURE syntax

---

api/project.go
api/project_test.go
server/issue.go

When the project DBNameTemplate contains regular characters, due to https://github.com/bytebase/bytebase/blob/4da6d230309c8274b7638da7560172cc1ec60b7e/server/deploy.go#L132 
if return name with regular escape, it causes a mismatch.

fix: create issue error when DBNameTemplate include regex string

---

plugin/webhook/custom.go
plugin/webhook/dingtalk.go
plugin/webhook/discord.go
plugin/webhook/feishu.go
plugin/webhook/wecom.go
server/activity.go
server/auth.go
server/bookmark.go
server/database.go
server/environment.go
server/inbox.go
server/instance.go
server/issue.go
server/issue_subscriber.go
server/jwt.go
server/label.go
server/member.go
server/policy.go
server/principal.go
server/project.go
server/project_member.go
server/project_webhook.go
server/setting.go
server/sheet.go
server/sheet_organizer.go
server/sql.go
server/subscription.go
server/task.go
server/vcs.go
server/webhook.go

Use "[Mm]alformed" consistently across the codebase to replace "[Mm]alformatted".
---
Follow up of https://github.com/bytebase/bytebase/pull/998#discussion_r863824174

chore: use "malformed" consistently

---

frontend/src/components/ProjectWebhookForm.vue

Reproduce:
https://user-images.githubusercontent.com/87714218/168457626-38ab62ce-bc52-4067-ba4d-c66ef6335001.mp4
Fix:
https://user-images.githubusercontent.com/87714218/168457629-e91bae42-1b8e-4ab0-a2b6-daa189a1798b.mp4
**Still allows the user to cancel the activity on modification to temporarily stop the webhook**

fix: only allow to create the webhook when activity list is non-empty

---

api/backup.go
bin/bb/cmd/dump.go
docs/design/pitr-mysql.md
plugin/db/clickhouse/clickhouse.go
plugin/db/driver.go
plugin/db/mysql/mysql.go
plugin/db/pg/pg.go
plugin/db/snowflake/snowflake.go
plugin/db/sqlite/sqlite.go
plugin/db/util/driverutil.go
plugin/restore/mysql/mysql.go
plugin/restore/mysql/mysql_test.go
server/anomaly_scanner.go
server/database.go
server/issue.go
server/task_executor_database_backup.go
server/task_executor_schema_update_ghost_sync.go
store/backup.go
store/migration/dev/20220516000000__backup.sql
store/migration/dev/LATEST.sql
tests/backup_restore_test.go

Improve the logical backup process to also get the current binlog position as is described in the [design doc](https://github.com/bytebase/bytebase/blob/main/docs/design/pitr-mysql.md#full-backup).
Closes BYT-468.

feat(PITR): implement the logical backup process

---

plugin/restore/mysql/mysql.go
plugin/restore/mysql/mysql_test.go
plugin/vcs/vcs.go
server/issue.go
server/server.go
server/task_executor_pitr_restore.go
server/task_executor_schema_update_ghost_sync.go
tests/backup_restore_test.go

Now we can create a PITR restore issue, and the first task will be performed.
Some detailed implementations like applying binlog is still TODO.
```
mysql> show databases;
+----------------------+
| Database             |
+----------------------+
| bytebase             |
| information_schema   |
| mysql                |
| performance_schema   |
| sbtest               |
| sys                  |
| test                 |
| test2                |
| test_pitr_1652788936 |
+----------------------+
9 rows in set (0.00 sec)
```

feat(PITR): add task executor for PITR restore task

---

tests/backup_restore_test.go

wait for `SwapPITRDatabase()` can handle the case that the original database does not exist.

chore: fix PITR test case

---

frontend/src/components/DatabaseSchemaReview/SchemaReviewCreation.vue
frontend/src/components/DatabaseSchemaReview/SchemaReviewEmptyView.vue
frontend/src/components/EnvironmentForm.vue
frontend/src/components/Issue/TaskCheckRunPanel.vue
frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json
frontend/src/types/error.ts
frontend/src/views/SettingWorkspaceSchemaReview.vue
frontend/src/views/SettingWorkspaceSchemaReviewCreate.vue
frontend/src/views/SettingWorkspaceSchemaReviewDetail.vue

- Fix: environment validation while editing or creating the schema review policy
- Optimize: Users can redirect to schema review policy setting view from `TaskCheckRunPanel`
- Optimize: The table in `TaskCheckRunPanel` is a little strange, update the table cell there. We can also find other better ways to optimize the UI later.
Before:
After:

chore: optimize UX for schema review policy

---

frontend/src/components/CreateDatabasePrepForm.vue

- Check `databaseOwnerName` only when necessary.
- Otherwise when we creating a non-PG database the "Create" button will always be disabled.
- Pass `owner` value to [POST] /api/issue only when necessary.
- When we change the "Instance" dropdown value the `state.databaseOwnerName` might be dirty. So we pass it via the POST body only when necessary.

fix(frontend): validate database owner name 🔥 

---

frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json

- Add missing localization for the foreign key
- Remove localization for the primary key
-  I found the `{` and `}` will be treated as the variable template after we switch to JSON from YAML. Haven't found ways to render the bracket yet, so I just change to the `<` and `>`
Before:
After:

fix: localization for schema review rules

---

frontend/src/components/Issue/logic/base.ts
frontend/src/components/Issue/logic/common.ts
frontend/src/plugins/issue/logic/initialize/standard.ts
frontend/src/store/modules/instance.ts
frontend/src/views/DatabaseDetail.vue

This PR follows #1357 
- Do not pass `databaseName` in `createContext` when creating standard pipelines. The server-side won't use it.
- Fallback to standard pipeline view when 
- The issue type is `"bb.issue.database.data.update"`.
- There's only one task in the pipeline.
- Enable the "Change Data" button on the DB detail page.
- Changing data from SQL Editor is also supported now.

feat(frontend): support single tenant data change

---

server/oauth.go

Because it's possible to have no `clientId` or `clientSecret` in the request body, we should get them with `vcsId` even if it's stale. When the vcs information is stale, we should ask users to update them.

fix: vcs oauth error in project configure vcs page

---

server/task.go

When clicking the "Backup Now" button, the server logs errors.
```
{"time":"2022-05-25T09:49:29+08:00","method":"POST","uri":"/api/database/7034/backup","status":200,"error":""}
2022-05-25T09:49:30.100+0800	ERROR	Failed to change task status.	{"id": 11023, "name": "backup-task-default-prod-20220525T094928", "old_status": "PENDING", "new_status": "RUNNING", "error": "failed to find issue with pipeline ID 9012, task: backup-task-default-prod-20220525T094928"}
2022-05-25T09:49:30.100+0800	ERROR	Failed to schedule next running task	{"pipeline_id": 9012, "error": "failed to find issue with pipeline ID 9012, task: backup-task-default-prod-20220525T094928"}
```
And the pipeline status will be stuck at "OPEN", though the task status will be eventually pushed to "DONE", and the backup file is …

fix: ignore error and log warning when pipeline belongs to no issue

---

server/task_executor_schema_update_ghost_cutover.go
server/task_executor_schema_update_ghost_sync.go
tests/ghost_test.go

The gh-ost parser cannot parse the following SQL statement, so we have to trim the string for it.
```sql
ALTER TABLE
test
ADD
COLUMN ghost_play_2 int;
```

fix: trim statement for gh-ost parser

---

bin/server/cmd/profile_dev.go
tests/external_pg_test.go
tests/tests.go

Otherwise, if we run `TestBootWithExternalPg`, there will be a `tests/resources` dir created in the codebase.

refactor: add temp dir as data dir for external pg in test

---

server/task_executor.go
server/webhook.go

* Return more readable messages so we know why the webhook event is ignored
* Add debug logging when responding to the webhook event
* Add debug logging when executing migration

chore: verbose logging for VCS workflow and schema migration

---

tests/tests.go

This design eliminates the former happened (several times) incidents that some test ports range overlaps with another, maybe because of concurrent development.

refactor: make test port allocation more clear

---

api/activity.go
api/api.go
frontend/src/store/modules/activity.ts
server/activity.go
server/webhook.go
store/activity.go

The previous implementation only returns the `updated_ts DESC` order if `limit` is specified. This is only used when fetching the recent 5 activities for the project overview. The current implementation has couple of problems:
1. Sort order varies among different use cases, issue activity wants ASC while view recent activities wants DESC
2. We don't have `updated_ts` index on the activity table, we only have `created_ts` index
So the fix is to let client specify the sort order and if specified, we order it on `created_ts` instead of `updated_ts`

fix: return the project activity in created_ts DESC order

---

frontend/src/components/MonacoEditor/sqlFormatter.ts

Fix unexpected behavior of clearing editor when language is not normal for `sql-formatter`.
refer: https://github.com/zeroturnaround/sql-formatter/blob/master/docs/language.md#options

fix: sql formatter language checker

---

.vscode/launch.json
scripts/.air.toml

We can now easily attach to a running bytebase server and debug it on the fly!
<video src="https://user-images.githubusercontent.com/8433465/170415155-b53d237a-4fd5-4b92-a11f-c5296f32c55b.mov" />

chore: add vscode config to attach to running golang process

---

server/task.go

The deleted codes in this PR will cause race conditions with https://github.com/bytebase/bytebase/blob/05ea4d8eb741ccd9416320faa98caf7c81272809/server/task_scheduler.go#L82
Both will try to patch task status from `PENDING` to `RUNNING` thus causing a race condition.

fix: patch task race condition

---

frontend/src/bbkit/BBModal.vue
frontend/src/components/Issue/IssueStatusTransitionButtonGroup.vue
frontend/src/components/Issue/logic/index.ts
frontend/src/components/Issue/logic/transition.ts

This might somehow help to avoid concurrency and race conditions when patching an issue or a task.
When a user clicked the issue/task status transition button:
- Fetch the latest issue entity from the server-side before doing a PATCH.
- Check whether the patching is applicable via the latest issue and pipeline status.
- Preventing the user from clicking the "Approve" or "Run" button in a very short time again via a mask layer with a spinning icon.
-

feat: check issue/task status transition again before patching

---

.github/workflows/codeql-analysis.yml
common/security.go
server/webhook.go
store/activity.go

ref: https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/
> On March 30, 2022, we released CodeQL Action v2, which runs on the Node.js 16 runtime. The CodeQL Action v1 will be deprecated at the same time as GHES 3.3, which is currently scheduled for December 2022.

chore: upgrade codeql

---

plugin/restore/mysql/mysql.go
server/database.go
server/task_executor_pitr_cutover.go
server/task_executor_pitr_restore.go
tests/backup_restore_test.go
tests/mysql.go
tests/mysql_test.go

To complete MySQL PITR, we embed the MySQL client, we need to pass the connection config to the MySQL client so that it can connect to the MySQL server. If we do the same way when focusing on the PostgreSQL PITR, we can add a function signature likes `getConnectionConfig()` in `Driver` interface.
Completing BYT-521

feat(PITR): add connection config as an argument to new mysql restore

---

plugin/restore/mysql/mysql.go
plugin/restore/mysql/mysql_test.go

As discussed offline, we are not yet sure whether MySQL 8.0 clients can support MySQL 5.7 servers.
Completing BYT-449

fix(PITR): we only support MySQL version >= 8.0 for MySQL PITR

---

plugin/vcs/github/github.go
plugin/vcs/github/github_test.go
plugin/vcs/gitlab/gitlab.go
plugin/vcs/gitlab/gitlab_test.go
tests/fake/gitlab.go

Implements `FetchCommitByID` for GitHub VCS provider, adds unit tests for both GitHub and GitLab.

feat: implement `FetchCommitByID` for GitHub VCS provider

---

frontend/src/components/Issue/logic/common.ts

Following #1419 
For tenant project create database tasks, we go through the common checkpoints.
- The issue status is OPEN.
- The currentUser is the creator of the issue.
- The project is UI workflow.
- The selected task status is PENDING or PENDING_APPROVAL or FAILED.

fix: allow users to editor statement for tenant project create database task part.2

---

frontend/src/components/ProjectCreate.vue
frontend/src/components/QuickActionPanel.vue

[BYT-544](https://linear.app/bbteam/issue/BYT-544/cannot-set-the-default-deployment-config-on-a-newly-created-tenant)
- Generate and save the default deployment config (by environments) when a tenant mode project is successfully created.
- Add a mask with a spinning indicator when requesting network APIs.

feat(frontend): auto generate and save default deployment config after a tenant project created

---

common/log/logger.go
plugin/db/driver.go
plugin/db/util/driverutil.go
server/task_executor.go
server/task_executor_database_restore.go
server/task_executor_pitr_cutover.go
server/task_executor_pitr_restore.go
server/task_executor_schema_update_ghost_sync.go

After we successfully swapped the pitr/original database, we also insert a BASELINE migration record.
Closes BYT-557.

feat(PITR): add a baseline migration history at the end of PITR cutover

---

frontend/src/components/DatabaseTable.vue

[BYT-564](https://linear.app/bbteam/issue/BYT-564/let-users-know-if-a-database-is-deleted)
1. Mark "NOT_FOUND" in red in the table of databases.
2. Sort the database table, putting NOT_FOUND DBs at the top (then by db.id ASC).

feat(frontend): database table improvement

---

frontend/src/components/AlterSchemaPrepForm/ProjectTenantView.vue
frontend/src/components/ProjectDeploymentConfigPanel.vue
frontend/src/components/TenantDatabaseTable/DeployDatabaseTable.vue
frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json

Provide an immediate live preview section below the config tool instead of the Preview button which opens a preview dialog.
We still need more systematic design to improve the UX of the tenancy mode. 😅

feat(frontend): deployment config improvement

---

frontend/src/components/MemberTable.vue
frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json
frontend/src/views/SettingWorkspaceMember.vue

[BYT-478](https://linear.app/bbteam/issue/BYT-478/the-issue-is-assigned-to-a-unknown-user-bytebase-when-i-create-a)
- Show [Bytebase] as a "System Bot" in Settings -> Workspace -> Members.
- Not showing the "Updated Time" because [Bytebase]'s updated time timestamp is 0 (1970/1/1), which makes it meaningless.

feat(frontend): show Bytebase as a system bot in member list

---

server/backup_runner.go

There are ERROR logs like this.
```
2022-06-01T12:53:02.779+0800	ERROR	Failed to create automatic backup for database	{"databaseID": 7048, "error": "failed to connect database at 127.0.0.1: with user \"root\": Error 1049: Unknown database '*'", "stack": ""}
```

fix: skip scheduled backup job for wildcard database *

---

.goreleaser.yaml

goreleaser release mode `append` appends the current release notes to the existing notes
https://goreleaser.com/customization/release/#:~:text=is%20%60keep%2Dexisting%60.-,mode%3A%20append,-%23%20Header%20template%20for

chore: append release note if exists

---

frontend/src/components/Issue/PipelineGhostFlow.vue
frontend/src/components/Issue/PipelinePITRFlow.vue

This element is unnecessary but it blocks the click event of the avatar button on the top right corner.

fix(frontend): remove unexpected extra elements

---

frontend/src/components/DatabaseDetail/PITRRestoreButton.vue

Before: the default time is the timestamp when the user visited the page.
After: reset the default time to "now" every time when the user opening the dialog.

feat(frontend): reset default pitr restore time to "now" every time when opening the dialog

---

frontend/src/components/Issue/TaskCheckBadgeBar.vue
frontend/src/components/Issue/TaskCheckBar.vue

- Reset the selected tab index when re-opening the modal dialog. (Fix [BYT-599](https://linear.app/bbteam/issue/BYT-599/bug-wrong-version-state))
- Make the selected TaskCheckRun item reactive when it's still running. (Fix [BYT-594](https://linear.app/bbteam/issue/BYT-594/bug-status-not-synced))
- chore: reorder the imports, 3rd-party on the top.

fix(frontend): TaskCheckRunBar improvement

---

api/database.go
frontend/src/components/ProvideSQLEditorContext.vue
frontend/src/store/modules/database.ts
frontend/src/store/modules/sqlEditor.ts
frontend/src/types/database.ts
frontend/src/types/sqlEditor.ts
server/database.go
store/database.go

* filter database when fetch database in SQL editor with `syncStatus=OK`;
* update `fetchDatabaseList` module action with `DatabaseFind` which could be more useful;
* add `syncStatus` queryparam to GET `/api/database` (I just put the changes into this PR because it's so simple);

fix: filter database list with `syncStatus: 'OK'` for SQL editor

---

frontend/src/components/DatabaseSchemaReview/SchemaReviewConfig.vue
frontend/src/components/DatabaseSchemaReview/SchemaReviewCreation.vue
frontend/src/components/DatabaseSchemaReview/SchemaReviewEmptyView.vue
frontend/src/components/DatabaseSchemaReview/SchemaReviewInfo.vue
frontend/src/components/DatabaseSchemaReview/SchemaReviewPreview.vue
frontend/src/components/DatabaseSchemaReview/components/SchemaReviewCard.vue
frontend/src/components/DatabaseSchemaReview/components/SchemaReviewSidebar.vue
frontend/src/components/DatabaseSchemaReview/components/SchemaReviewTemplates.vue
frontend/src/components/DatabaseSchemaReview/components/SchemaRuleConfig.vue
frontend/src/components/EnvironmentForm.vue
frontend/src/components/InputWithTemplate/InputWithTemplate.vue
frontend/src/components/Issue/TaskCheckRunPanel.vue
frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json
frontend/src/types/schemaSystem.ts
frontend/src/views/SettingWorkspaceSchemaReview.vue
frontend/src/views/SettingWorkspaceSchemaReviewCreate.vue
frontend/src/views/SettingWorkspaceSchemaReviewDetail.vue
plugin/advisor/mysql/advisor_naming_column_test.go
plugin/advisor/mysql/advisor_naming_table_test.go
tests/schema_system_test.go
tests/tests.go

Updated:
- https://linear.app/bbteam/issue/BYT-598/show-the-rule-sidebar-in-the-configure-rule-step-as-well
- https://linear.app/bbteam/issue/BYT-589/the-control-for-linking-environment-to-policy-should-use-radio-button
- https://linear.app/bbteam/issue/BYT-591/schema-review-template-wording
- https://linear.app/bbteam/issue/BYT-593/expand-icon-should-be-top-aligned-instead-of-central-aligned】
- https://linear.app/bbteam/issue/BYT-595/too-much-bottom-padding-for-the-expanded-policy
- https://linear.app/bbteam/issue/BYT-597/add-the-hover-effect-when-mouse-over-the-field-template
- https://linear.app/bbteam/issue/BYT-600/disabled-review-policy-wording
- https://linear.app/bbteam/issue/BYT-601/the-environment-field-should-be-a-link-to-the-particular-environment
- …

chore: ux fix and optimize for schema review policy

---

frontend/src/components/MonacoEditor/AutoCompletion.ts
frontend/src/components/MonacoEditor/MonacoEditor.vue
frontend/src/components/MonacoEditor/useMonaco.ts
frontend/src/views/sql-editor/EditorPanel/EditorPanel.vue
frontend/src/views/sql-editor/EditorPanel/SQLEditor.vue

The `MonacoEditor` and `useMonaco` should not depend on any store, so that it can be used elsewhere. e.g. issueDetailPage

refactor: remove stores from `useMonaco`

---

metric/collector/policy_count.go

Found this bug during configuring the Metabase. The `key` is invalid as the `value` is empty.

fix: policy metric

---

plugin/restore/mysql/mysql.go

We need to close the binlog record in the cutover stage of PITR, otherwise the user will have the error that the table already exists when the user performs a second pitr on the same database without deleting the old database. Also, PITR itself shouldn't have an effect on the binlog.

fix(PITR): using connection to keep consistent

---

frontend/src/assets/css/tailwind.css
frontend/src/components/EnvironmentForm.vue
frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json
frontend/src/views/EnvironmentDetail.vue

- Fixes: Updating Approval Policy will lose selection on Database backup schedule policy
- Feat: Display applicable conditions for Environment policies. Add a tip in red "The policy is not applied retroactively" when users are updating Environment policies.
| before | after |
| :---: | :---: |
| ![CleanShot 2022-06-07 at 11 17 35](https://user-images.githubusercontent.com/56376387/172288366-174f7b51-c3af-49b3-bb58-f85d760e4327.gif) | ![CleanShot 2022-06-07 at 11 14 51](https://user-images.githubusercontent.com/56376387/172288272-e9ec2688-745f-44b4-aa54-8de54bfdd76f.gif) |

feat(frontend): display applicable conditions for Environment policies

---

store/anomaly.go

Do filter in SQL instead of code because it causes recursive call since `GetInstanceByID` call `FindAnomaly`.

fix: filter anomaly belongs to archived instance

---

.github/workflows/build-release-image.yml
.github/workflows/release-binary.yml

The example from the official doc runs the action on tags creation. Many other examples from source graph did the same thing.
https://github.com/goreleaser/goreleaser-action#run-on-new-tag

fix: run goreleaser on push tags

---

api/backup.go
plugin/restore/mysql/mysql.go
plugin/restore/mysql/mysql_test.go
server/task_executor_pitr_restore.go

According to the mysqlbinlog source code, there would be fake binlog events in the output.
https://github.com/mysql/mysql-server/blob/8.0/client/mysqlbinlog.cc#L1209-L1212
And the output format is `end_log_pos %s`.
https://github.com/mysql/mysql-server/blob/8.0/sql/log_event.cc#L1407
So the fix is ignore lines with `end_log_pos 0`.
Completing BYT-696.

fix: ignore fake binlog event header of mysqlbinlog output

---

api/backup.go
plugin/restore/mysql/mysql.go
plugin/restore/mysql/mysql_test.go
server/task_executor_pitr_restore.go

We update the schema of the backup table. The payload field of stale full backup is empty. And backup of database with binlog disabled also has empty payload.
So that we need to skip it when parsing the event timestamp.
Completing BYT-699.

fix: don't parse binlog event timestamp of backup which binlogInfo field is empty

---

frontend/src/components/Issue/IssueStatusIcon.vue
frontend/src/components/Issue/TaskStatusIcon.vue
frontend/tailwind.config.js

Close BYT-704
The screenshot GIF's quality is quite low to show the actual effect.

feat(frontend): make the running status icon more obvious

---

server/task_executor_schema_update_ghost_sync.go

Disable auto removing the old table. We require the user to manually drop the old table.

feat: disable auto removing the old table

---

frontend/src/components/PricingTable.vue
frontend/src/views/SettingWorkspaceSubscription.vue

As we will remove the /pricing page in the hub in the future, we need to update the URL in the console first.

chore: update pricing page url

---

frontend/src/components/Issue/IssueStatusTransitionButtonGroup.vue
frontend/src/components/Issue/StatusTransitionForm.vue
frontend/src/components/Issue/logic/transition.ts
frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json

- The server-side will run tasks sequentially, so the frontend will still see outdated task status like in #1535 .
Close BYT-722

feat(frontend): allow approve/run all tasks in a stage for tenant mode issue

---

plugin/db/driver.go
plugin/db/util/driverutil.go
server/task_executor.go
server/task_executor_database_create.go

This allows users to retry the migration by well-considering the existing migration history record. In most cases, the statement execution is executed with an error or not executed yet. In rare cases, the execution was successful but the status is PENDING since the status update wasn't completed previously. Users should inspect the database and differentiate these two cases. The force option provides an option for users to retry the migration for the former case.

chore: add force option to migration

---

api/actuator.go
bin/server/cmd/profile_dev.go
bin/server/cmd/profile_release.go
frontend/src/layouts/BodyLayout.vue
frontend/src/store/modules/actuator.ts
frontend/src/types/actuator.ts
scripts/.air.toml
scripts/.air_bb.toml
server/actuator.go
server/config.go

This is for locating the revision, especially for development builds.
Also pass the build info when building bytebase/bb via air

feat: add git commit hash of the build and display it as the tooltip when hovering on the version

---

.vscode/launch.json

This enables us to debug the compiled dev binary by `air`.

chore: add vscode launch option to debug golang binary

---

frontend/src/components/DatabaseBackupPanel.vue

Per discussion, we need to remove PITR button from this release.
And this PR should also be cherry-picked to release 1.2.0.

chore: add release guard to pitr restore button

---

frontend/src/components/CreateInstanceForm.vue

fix: if a user didn't touch anything about SSL Connection, we should fall back to NONE (using 3 empty strings).

fix(frontend): default ping SSL parameters when creating clickhouse instance

---

api/sql.go
server/sql.go
store/instance.go

The server can handle the request for the test connection in the ClickHouse instance detail page now.
Fix BYT-713

fix: test connection in instance detail page

---

frontend/src/utils/pipeline.ts

Close BYT-747
Canceling a task is somehow meaningless. While canceling an issue is meaningful.

feat(frontend): remove "Cancel" button for task status transition

---

Dockerfile

We need to copy the timezone file from the backend stage in the docker file.

fix: missing timezone file in alpine

---

.github/workflows/release-binary.yml

We now create tag in advance, and this workflow is triggered on tag push. So creating tag inside the workflow will trigger error.

fix: remove tag step since we have altered the release steps

---

README.md

The main reason is to reduce the work of changing version string during upgrade

docs: link the install to the doc site

---

server/task_executor_schema_update_ghost_sync.go

Line 112 sets the ReplicaServerId to config.serverID, and then line 117 sets it back to the default.
It must be that I forgot to remove this line.
This should fix BYT-776.

fix: remove default replicaServerId

---

frontend/src/bbkit/BBBetaBadge.vue

chore: improve beta label style

---

go.mod
go.sum
server/task_executor_schema_update_ghost_sync.go

1. Add timestamp to all table names created by gh-ost by default.
The name is like `~table_1656377385_gho`
1. Update go.mod gh-ost fork version.
Close BYT-784

feat: add timestamp to gh-ost created table names

---

plugin/db/mysql/restore.go

This bug is reported by @LiuJi-Jim .
The current check is too strict and cannot let go of "9:58:06".
Leave the time format errors to `time.ParseInLocation`.

fix: relax the time parse check

---

Dockerfile

`HEALTHCHECK --interval=5m --timeout=60s CMD curl -f http://localhost:80/healthz || exit 1` in docker file needs curl.

feat: install curl in debian

---

go.mod
go.sum
server/task_executor_schema_update_ghost_sync.go

Update to this commit https://github.com/bytebase/gh-ost/commit/aac285eb72df5f82e7cfb22a65b733e2c703b527.
The previous version is this commit https://github.com/bytebase/gh-ost/commit/d497834632ba92ca2e61646c5e13c6833ce11bc5
The changes are
- change gh-ost logger to `zap.Logger`
- `panic` in `Log.Fatal` because we use gh-ost as a library and dont't want to bring down the whole process.
Close BYT-818

chore: update gh-ost fork version

---

Dockerfile.render
Dockerfile.render-preview
scripts/demo.sh
scripts/staging.sh

In Debian, `sh` is soft linked to bash by default.
Demo of deploying after fixed: https://zpdev-bytebase-demo.onrender.com/

fix: using bash syntax instead of sh

---

plugin/advisor/advisor.go

We use `pg_query_go` as the PostgreSQL parser instead of https://github.com/auxten/postgresql-parser. Now we can turn on the PostgreSQL syntax check.
related PR: #1698

chore: turn on PostgreSQL syntax check

---

go.sum
plugin/db/driver.go
plugin/db/mysql/dump.go
plugin/db/mysql/restore.go
server/sql.go
server/task_executor_database_backup.go
server/task_executor_pitr_cutover.go
tests/backup_restore_test.go

This change is for the later PITR algorithm fix, which needs to perform locking in the same DB session during the cutover.

refactor(PITR): use single db session to swap in cutover task

---

server/task_check_executor_ghost_sync.go

For gh-ost task check, don't generate postpone flag file because postpone flag file is irrelevant to a dry run and it creates a flie left undeleted each time running, which is sort of annoying.

feat: no postpone flag file for gh-ost sync task check

---

.github/workflows/update-render-staging-service.yml

Using [render's API](https://api-docs.render.com/reference/update-service) with GitHub Action allows us to switch the monitor branch of Bytebase staging web service in render to the new release branch when we create the `release/x.y.z` branch.
Here is a [demo](https://github.com/h3n4l/render-cd-test).
Completing BYT-726.

feat(CD): trigger render staging listening new release branch when creating release branch

---

plugin/parser/ast/rename_column_stmt.go
plugin/parser/ast/utils.go
plugin/parser/engine/pg/convert.go
plugin/parser/engine/pg/convert_test.go

In `RenameColumnStmt`, we only need `ColumnName` rather than `ColumnDef`.

chore: use ColumnName instead of ColumnDef in RenameColumnStmt

---

.github/workflows/tests.yml

- Separate test steps to better view how long it takes to run tests.
- Increase timeout minutes because 10 minutes seems to be too strict for "test release".

chore: separate test steps & increase timeout minutes

---

plugin/db/pg/sync.go

It is a tiny fix, we need to add an integration test in the next cycle.

fix: PostgreSQL double quotes in name

---

api/api.go
server/activity.go
store/activity.go

PR https://github.com/bytebase/bytebase/pull/1767 is a wrong fix, because the `find.Order` is constant string ASC/DESC and cannot be a prepared argument, which causes syntax error.

fix: activity sorting order

---

.github/workflows/build-push-release-image.yml
.github/workflows/codeql-analysis.yml
.github/workflows/draft-release.yml
.github/workflows/tests.yml
.github/workflows/update-render-staging-service.yml

`setup-go@v3` supports caching go dependencies.

chore: update gha setup-go and checkout

---

.github/workflows/tests.yml

This could save gha quota and make one less item in the checklist.
@tianzhou This PR requires removing `golangci` and `go-tidy` from the required check list, and add `go-static-checks` after merged.

chore: merge gha static checks CI

---

tests/tests.go

In the PITR integration test, we need to approve only one task instead of approving a stage or a pipeline.
Completing BYT-881.

feat: support wait one task with approval in integration test

---

frontend/src/views/BannerDemo.vue

chore: update demo banner link

---

store/demo/dev/10110__task.sql
store/demo/dev/10111__task_dag.sql
store/demo/dev/10130__issue.sql

Removed the "drop original table" task.

chore: update gh-ost seed data

---

plugin/vcs/github/github.go
plugin/vcs/github/github_test.go
plugin/vcs/gitlab/gitlab.go

This PR implements the `FetchRepositoryActiveMemberList` method of the `vcs.Provider` interface for the GitHub.com.

feat(github): implement `FetchRepositoryActiveMemberList`

---

plugin/vcs/github/github.go
plugin/vcs/github/github_test.go
plugin/vcs/gitlab/gitlab.go
plugin/vcs/gitlab/gitlab_test.go

It is possible that members of a GitHub repository has configured to not expose email publicly. This PR makes sure it returns an error to _behave consistently_ with the GitLab implementation (doesn't mean this is the optimal UX).
Also added unit tests for both providers.

fix(github): return an error when member is missing public email

---

resources/utils/extract.go

Avoid using io.Copy for decompressing data #1770.

chore: replace Copy with CopyN to address gosec G110

---

plugin/db/mysql/restore.go
tests/backup_restore_test.go

ref: https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html

fix(PITR): support case sensitive database name in replaying binlog process

---

frontend/src/components/DatabaseBackupPanel.vue
frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json

The title was hard-coded to be "weekly backup" before. Even if the environment's backup policy is set to be "daily".
In this PR, the title's wording is based on the environment's backup policy.

feat(frontend): backup panel title wording

---

.github/workflows/build-artifacts-and-draft-release.yml
.github/workflows/tests.yml
.goreleaser-for-linux.yaml

We do not have a mysqlbinlog binary for linux arm64 combination.

chore: do not release linux-arm64

---

frontend/src/utils/pipeline.ts

Per discussion, we will remove the "Run" button on the issue detail page.
A task is defined as "runnable" if
1. Its status is "PENDING".
2. All its task checks are success or warning, with no error.
If a task is or turns "runnable" it will definitely be scheduled to run automatically. So it's not necessary to click the run button and run it manually.
We are also planning to introduce a new UI state sth. like "Scheduling" or "Queueing" for "PENDING" tasks.

feat(frontend): do not show run button for PENDING tasks

---

plugin/vcs/github/github.go
plugin/vcs/github/github_test.go
plugin/vcs/gitlab/gitlab.go
plugin/vcs/gitlab/gitlab_test.go

This PR implements the `FetchRepositoryFileList` method of the `vcs.Provider` interface for the GitHub.com.
Piggybacks:
1. Make `FetchRepositoryFileList` method of the GitLab provider support pagination.
1. Added unit tests for the method of the GitLab provider.
---
Part of https://linear.app/bbteam/issue/BYT-855/implement-missing-methods-of-vcsprovider-interface

feat(github): implement `FetchRepositoryFileList`

---

server/task.go

PENDING task could be scheduled by task_scheduler at any time and turns RUNNING. We should disallow change the statement of a PENDING task.

fix: disallow change PENDING task statement

---

plugin/vcs/github/github.go
plugin/vcs/github/github_test.go
plugin/vcs/gitlab/gitlab.go
plugin/vcs/gitlab/gitlab_test.go

This PR implements the `ReadFileMeta` and `ReadFileContent` methods of the `vcs.Provider` interface for the GitHub.com.
Piggybacks:
1. Added unit tests for `ReadFileMeta` and `ReadFileContent` methods of the GitLab provider.
---
Part of https://linear.app/bbteam/issue/BYT-855/implement-missing-methods-of-vcsprovider-interface, stacked on https://github.com/bytebase/bytebase/pull/1885

feat(github): implement `ReadFileMeta` and `ReadFileContent`

---

plugin/vcs/github/github.go
plugin/vcs/github/github_test.go
plugin/vcs/gitlab/gitlab.go
plugin/vcs/gitlab/gitlab_test.go

This PR implements the `CreateFile` and `OverwriteFile` methods of the `vcs.Provider` interface for the GitHub.com.
Piggybacks:
1. Added unit tests for `CreateFile` and `OverwriteFile` methods of the GitLab provider.
---
Part of https://linear.app/bbteam/issue/BYT-855/implement-missing-methods-of-vcsprovider-interface

feat(github): implement `CreateFile` and `OverwriteFile`

---

plugin/vcs/github/github.go
plugin/vcs/github/github_test.go
plugin/vcs/gitlab/gitlab.go
plugin/vcs/gitlab/gitlab_test.go
plugin/vcs/internal/oauth/oauth.go
plugin/vcs/internal/oauth/oauth_test.go

This PR implements the `CreateWebhook`, `PatchWebhook` and `DeleteWebhook` methods of the `vcs.Provider` interface for the GitHub.com.
Piggybacks:
1. Added unit tests for `CreateWebhook`, `PatchWebhook` and `DeleteWebhook` methods of the GitLab provider.
2. Tided up few places to be consistent on error handling patterns.
_It is easier to review by commmit._
---
The last PR to fix https://linear.app/bbteam/issue/BYT-855/implement-missing-methods-of-vcsprovider-interface

feat(github): implement `CreateWebhook`, `PatchWebhook` and `DeleteWebhook`

---

frontend/src/components/Issue/logic/common.ts
frontend/src/components/Issue/logic/extra.ts
frontend/src/types/pipeline/stage.ts
frontend/src/types/pipeline/task.ts

Per discussion, we will use (last) `updatedTs` as an optimistic lock to avoid some kind of race condition issues.
The updated POST payload looks like

feat(frontend): patch task with updatedTs field

---

frontend/src/components/Issue/logic/common.ts
frontend/src/components/Issue/logic/index.ts
frontend/src/components/Issue/logic/utils.ts

Per discussion, a task is defined to be editable when 
- Its status is "PENDING_APPROVAL" or "FAILED"
- Or, its status is "PENDING" but it will NOT be scheduled, which means
- At least one of its task checks' results is "error", which means it's blocked to be scheduled due to its pre-flight checks are not all fulfilled.

feat(frontend): narrow the condition to judge if a task is editable

---

api/project_member.go
plugin/vcs/github/github.go
plugin/vcs/gitlab/gitlab.go
server/project.go
server/project_member.go
server/task_executor.go
server/webhook.go
tests/fake/gitlab.go

This PR updates code logics that are hard-coded for `GitLabSelfHost` to have logical branches or be compatible to handle `GitHubCom`.
Fix BYT-933, https://linear.app/bbteam/issue/BYT-933/update-call-sites-to-the-implemented-methods-of-vcsprovider

feat(github): update call sites of `vcs.Provider` methods to reach parity with GitLab

---

server/server.go

There are 13 route printing in the test log and each takes about 900 lines, adding up to 10k+ lines of useless information.
It also slows down the Github action log search UI.

chore: remove debug logging routes

---

server/task.go

Allow changing the statement of a Pending Task if it can't be scheduled.

fix: task statement update prerequisite

---

api/issue.go

This is the first step of [BYT-813](https://linear.app/bbteam/issue/BYT-813/pitr-to-a-new-database). Frontend can pass the value of `CreateDatabaseCtx` and then the backend can restore the target database to a new database by creating a two tasks pipeline.

feat(PITR): add databaseName field for PITRContext

---

plugin/db/clickhouse/migrate.go
plugin/db/mysql/migrate.go
plugin/db/pg/migrate.go
plugin/db/snowflake/migrate.go
plugin/db/sqlite/migrate.go

IMO, it is a copy-paste error.
We should return an error instead of nil if `SetupMigrationIfNeeded()` encounter some errors. Otherwise, the user may boot Bytebase web server successfully although our migration is failed.

fix: return error if SetupMigrationIfNeeded encounter some errors

---

.golangci.yaml
api/deploy.go
common/error.go
enterprise/service/license.go
plugin/db/clickhouse/dump.go
plugin/db/clickhouse/sync.go
plugin/db/mysql/dump.go
plugin/db/mysql/restore.go
plugin/db/mysql/sync.go
plugin/db/pg/sync.go
plugin/db/snowflake/sync.go
plugin/db/sqlite/sync.go
plugin/db/util/driverutil.go
plugin/vcs/github/github.go
plugin/vcs/gitlab/gitlab.go
server/database.go
server/task_check_executor_database_connect.go
server/task_check_executor_ghost_sync.go
server/task_check_executor_migration_schema.go
server/task_check_executor_statement_advisor_composite.go
server/task_check_executor_statement_advisor_simple.go
server/task_check_executor_timing.go
server/task_executor.go
server/task_executor_schema_update_ghost_cutover.go
server/task_executor_schema_update_ghost_sync.go
store/label.go
store/pg_engine.go

This PR makes the `common.Errorf` function to support formatting (i.e. embedding `fmt.Errorf`), and adds `common.WithError` for the cases where we already have the error object.
This is for two reasons:
1. Almost all of our [call sites for `common.Errorf` are in combination with `fmt.Errorf`](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/bytebase/bytebase%24+common.Errorf%28&patternType=literal).
2. The way it's been used currently isn't Go idiomatic, i.e. a function ending with `f` often implies formatting.
Since we're no longer directly using the `fmt.Errorf`, `go vet` would stop checking the type mismatch between formatting verbs and variables we provide, thus adds a new rule in `.golangci.yaml` for checking type mismatch for `common.Errorf`, it works as …

fix: make `common.Errorf` support formatting

---

server/acl_casbin_policy_dba.csv
server/acl_casbin_policy_developer.csv
server/acl_casbin_policy_owner.csv
server/task.go

This PR features a new HTTP endpoint `/pipeline/:pipelineID/task/all` which can be used to patch all tasks in the same issue.

feat: HTTP endpoint to patch all tasks in an issue

---

plugin/advisor/pg/advisor_column_required.go
plugin/vcs/github/github.go
plugin/vcs/github/github_test.go
plugin/vcs/gitlab/gitlab.go

This PR tweaks the GitHub implementation of `vcs.Provider` to support custom instance URL, which effectively makes the implementation [GitHub Enterprise Server](https://docs.github.com/en/enterprise-server@3.5/admin/overview/about-github-enterprise-server) ready.
However, the full support of GitHub Enterprise Server is not the primary intent but a side effect, we are doing this only because we need to be able to write a fake GitHub instance for integration testing.
---
Part of https://linear.app/bbteam/issue/BYT-856/add-integration-tests

refactor(github): make `Provider` support custom instance URL

---

frontend/src/components/DatabaseTable.vue
frontend/src/components/QuickActionPanel.vue
frontend/src/components/TransferDatabaseForm.vue
frontend/src/components/TransferDatabaseForm/TransferMultipleDatabaseForm.vue
frontend/src/components/TransferDatabaseForm/TransferSingleDatabaseForm.vue
frontend/src/components/TransferDatabaseForm/TransferSourceSelector.vue
frontend/src/components/TransferDatabaseForm/index.ts
frontend/src/components/TransferDatabaseForm/utils.ts

Close BYT-956, BYT-938
Proposed by @changyuwong, @candy2255 
- Support multi-selection when transferring databases INTO a project.
- Hide the labels setting form.
- Not available for tenant mode projects.
https://user-images.githubusercontent.com/2749742/180975867-fab14fb6-a584-4fc4-b5c7-d7041482c234.mov

feat(frontend): BYT-956 support multi-selection when transferring databases into a project

---

frontend/src/components/DatabaseTable.vue
plugin/db/mysql/restore.go
plugin/db/mysql/restore_test.go

refactor(PITR): use _del as old table suffix in consistent with gh-ost and review policy

---

frontend/src/components/DatabaseDetail/MigrationHistoryBrief.vue
frontend/src/components/DatabaseDetail/PITRRestoreButton.vue
frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json
frontend/src/plugins/pitr/index.ts

Close BYT-965
FYI @candy2255 @changyuwong @dragonly @h3n4l @d-bytebase 
- Support PITR to the point before the last migration. 
- Means 1 second before the last migration history's `createdTs`.
https://user-images.githubusercontent.com/2749742/181202876-27ad1df7-c81f-45cb-b65b-8a3cbd3b54a8.mov

feat(frontend): PITR to the point before last migration

---

tests/fake/gitlab.go
tests/fake/provider.go
tests/schema_update_test.go
tests/sheet_vcs_test.go
tests/tenant_test.go
tests/tests.go

This PR abstracts a `fake.VCSProvider` interface out of the existing fake GitLab VCS provider implementation, it is necessary to make it possible to swap in the fake GitHub VCS provider later for the VCS integration testing.
There is no change to how existing tests are done or what is being tested.
---
Part of https://linear.app/bbteam/issue/BYT-856/add-integration-tests

test(gitlab): abstract `fake.VCSProvider` for VCS integration testing

---

tests/backup_restore_test.go
tests/external_pg_test.go
tests/fake/gitlab.go
tests/fake/provider.go
tests/ghost_test.go
tests/schema_update_test.go
tests/sheet_vcs_test.go
tests/sql_review_test.go
tests/start_test.go
tests/tenant_test.go
tests/tests.go

This PR makes the test `controller` assume no internal knowledge about a `fake.VCSProvider` implementation.

refactor(tests): make `controller` accept a constructor for creating VCS provider

---

frontend/src/components/Issue/PipelineGhostFlow.vue
frontend/src/components/Issue/TaskProgressPie.vue
frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/task.ts
frontend/src/types/common.ts
frontend/src/types/pipeline/task.ts

Close BYT-1025
Backend supported by @RainbowDashy 
https://user-images.githubusercontent.com/2749742/181420287-04741ad8-a075-4995-8521-2ec5e1e8f425.mov

feat(frontend): UI support for gh-ost sync task progress

---

plugin/db/mysql/restore.go
tests/backup_restore_test.go
tests/tests.go

Try to fix this error: https://github.com/bytebase/bytebase/runs/7553600250?check_suite_focus=true#step:7:4658
The speculated execution is:
1. the first PITR done, backup is scheduled
2. data update
3. backup is taken
Clue: according to the log, the PITR backup's binlog coordinate is 763950, and the targetTs's binlog coordinate is 768283 (just a bit before the PITR backup), so the chosen backup is the first, which is wrong.
This test run also revealed the fact that there's a small **unrecoverable** range after each PITR (before the backup is taken).

fix(test): wait for PITR auto backup done, and update data

---

frontend/src/components/Issue/IssueDescriptionPanel.vue

Fix: when the page is loaded, the textarea's height should be auto-adjusted.
Thanks for the reporting from @dragonly

fix(frontend): auto adjust textarea height

---

plugin/parser/ast/constraint_def.go
plugin/parser/ast/drop_database_stmt.go
plugin/parser/engine/pg/convert.go
plugin/parser/engine/pg/convert_test.go

It's for the SCHEMA COMPATIBILITY rule.

chore: support PG ADD CHECK and DROP DATABASE

---

go.mod
go.sum
server/task_check_executor_ghost_sync.go
server/task_executor_schema_update_ghost_sync.go

Update to https://github.com/bytebase/gh-ost/commit/11d9c90276516c156726ff25eac74e9a4d9951ea
The previous version is https://github.com/bytebase/gh-ost/commit/aac285eb72df5f82e7cfb22a65b733e2c703b527
Diff: https://github.com/bytebase/gh-ost/compare/aac285eb72df5f82e7cfb22a65b733e2c703b527...11d9c90276516c156726ff25eac74e9a4d9951ea
The previous update PR is https://github.com/bytebase/bytebase/pull/1695

chore: update gh-ost fork

---

plugin/parser/ast/alter_table_stmt.go
plugin/parser/ast/drop_table_stmt.go
plugin/parser/ast/rename_table_stmt.go
plugin/parser/ast/set_schema_stmt.go
plugin/parser/engine/pg/convert.go
plugin/parser/engine/pg/convert_test.go

Only add the statements that the Migration-Compatibility rule needs.

chore: refactor ALTER TABLE stmt and partial support ALTER VIEW, DROP VIEW

---

.github/workflows/tests.yml

Currently, the output contains 30k+ garbage like this: https://github.com/bytebase/bytebase/runs/7573944337?check_suite_focus=true
After this PR: https://github.com/bytebase/bytebase/runs/7573980270?check_suite_focus=true
Guess the root cause is that we have already enabled cache in `actions/setup-go`.

chore: golangci-lint skip cache

---

plugin/db/mysql/restore.go

Reasons:
1. The written bytes are checked with crc32 checksum, so it’s just **incomplete**.
2. Retry download will complete the file content by rewriting the existing bytes and appending new bytes to the end.

refactor: verify binlog checksum events and do not remove incomplete binlog files

---

server/task_executor_schema_update_ghost_cutover.go
server/task_executor_schema_update_ghost_sync.go
server/task_scheduler.go

This PR shares some states between gh-ost sync and cutover task because after the migration_history insertion logic was moved to the cutover task, we need some mechanism to know if the migration succeeds.
Close BYT-1001
By the way, naming is hard as hell.

feat: share gh-ost states between sync and cutover task

---

plugin/parser/ast/alter_column_type_stmt.go
plugin/parser/engine/pg/convert.go
plugin/parser/engine/pg/convert_test.go

It's for the MIGRATION COMPATIBILITY rule

chore: partial support ALTER COLUMN TYPE

---

bin/server/cmd/root.go

The TODO is used to explain why we disable --pg. We forgot to remove the comment when enabling --pg

chore: remove the obsolete todo

---

README.md

* Add code walkthrough to the new `learn the codebase` section
* Put the optional steps at last to avoid confusing user

docs: add code walkthrough and re-order development steps

---

tests/backup_restore_test.go

Extract common routines:
1. `setUpForPITRTest` for setting up common PITR testing.
2. `createPITRIssue` for creating PITR issue.
Close BYT-901.

refactor: PITR tests

---

server/issue.go

We have to make this exception to allow users to resolve schema drift.

chore: allow DDL for a single tenant database

---

api/plan.go
server/issue.go
server/subscription.go

There could be scaling issues if there are too many tasks created.

chore: add plan limit for maximum tasks that can be created for DDL/DML

---

frontend/src/components/Issue/logic/base.ts

We only expose this feature on the database detail page in this PR. Since it's more difficult to integrate the single database selection and tenant mode matrix in one issue creation modal dialog, which will be supported in the near future.

feat(frontend): allow to alter single db's schema in tenant project

---

frontend/src/bbkit/BBModal.vue
frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
frontend/src/components/AlterSchemaPrepForm/ProjectTenantView.vue
frontend/src/components/DatabaseTable.vue
frontend/src/components/Issue/logic/base.ts

Close BYT-1050
Following #2137 , we are now allowed to alter single database's schema in a tenant project via the universal "Alter Schema" quick action button.
https://user-images.githubusercontent.com/2749742/182337120-5f620f97-eaca-45cc-a820-e4580cf6d918.mov

feat(frontend): BYT-1050 allow to alter single db's schema in tenant project (part.2)

---

plugin/db/driver.go
plugin/db/mysql/mysql.go
server/anomaly_scanner.go
server/backup_runner.go
server/database.go
server/instance.go
server/issue.go
server/task_check_executor_database_connect.go
server/task_check_executor_migration_schema.go
server/task_executor.go
server/task_executor_database_backup.go
server/task_executor_database_create.go
server/task_executor_database_restore.go
server/task_executor_pitr_cutover.go
server/task_executor_pitr_restore.go
server/task_executor_schema_update_ghost_cutover.go

The second step of using mysqldump to speed up the dump and restore. Dump() in MySQL driver need it to build the path of some embed binaries.

feat: MySQL driver will take the resrouceDirectory

---

plugin/db/mysql/mysql.go
plugin/db/mysql/restore.go
resources/mysqlutil/mysqlutil.go
resources/mysqlutil/mysqlutil_test.go
server/backup_runner.go
server/server.go
server/task_executor_pitr_cutover.go
server/task_executor_pitr_restore.go
tests/mysql.go
tests/mysql_test.go

The 3rd step of using mysqldump to speed up the backup and restore. After merging the #2144 , we don't need mysqlutilinstance anymore.
Completing BYT-975

refactor: remove mysqlutil instance

---

plugin/vcs/github/github.go
plugin/vcs/gitlab/gitlab.go

Compare with the const `apiPageSize` is more future-proof than hard-coded literals.

fix(vcs): compare results length with const instead of literals

---

frontend/src/components/VCSProviderOAuthPanel.vue
frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json

"Homepage URL" is a required field for creating an OAuth application on GitHub, providing an example value helps the user think less.
This PR also fixes the missing i18n strings for copy notifications on this page.

fix(github): provide example value for "Homepage URL"

---

frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json
frontend/src/views/auth/Signin.vue

Fix tooltip for GitHub.com when auth is disabled by using the neutral language.

fix(github): tooltip when the auth is disabled

---

frontend/src/components/RepositorySelectionPanel.vue
frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json
plugin/vcs/github/github.go
plugin/vcs/github/github_test.go

We are using the `affiliation=owner` filter for fetching the repositories list of the authenticated user, but this resulted in only personal repositories being listed.
Unfortunately, GitHub API does not provide a native filter for admin permissions, thus we need to first fetch all repositories and then filter down the list using the `permissions.admin` field.
This PR also fixes the missing "Attention needed" text:

fix(github): list all repositories the user has admin permissions

---

bin/bb/cmd/utils.go

Implement a part of bb support in #2159 .
To keep bb stateless, mysqlutil will be installed every time bb starts some operations about MySQL instead of support `--data` option.

feat: install mysqlutil in bb cmd

---

bin/bb/cmd/restore.go
plugin/db/clickhouse/clickhouse.go
plugin/db/clickhouse/dump.go
plugin/db/driver.go
plugin/db/mysql/dump.go
plugin/db/mysql/restore.go
plugin/db/pg/dump.go
plugin/db/pg/pg.go
plugin/db/snowflake/dump.go
plugin/db/snowflake/snowflake.go
plugin/db/sqlite/dump.go
plugin/db/sqlite/sqlite.go
plugin/db/util/driverutil.go
server/sql.go
server/task_executor_database_restore.go
server/task_executor_pitr_restore.go
tests/backup_restore_test.go

The first step of we use the MySQL client to speed up the restore.
Complete BYT-975.

chore: restore function in driver interface accepts a reader parameter to be more general

---

server/pipeline.go
server/task.go
server/task_check_executor_timing.go
server/task_check_scheduler.go
server/task_scheduler.go

Previously, the timing task check returns an error if the time condition is not met, which will stop the assignee from approving and is not what we expect.
In this PR, we make it returns a warning so that it won't prevent approval. We check the time when the task scheduler tries to run the task to implement the "timing" feature.
Close BYT-1070

fix(timing): task executes after earliest allowed time

---

frontend/src/components/DatabaseTable.vue
frontend/src/components/Issue/IssueActivityPanel.vue
frontend/src/components/Issue/activity/ActionSentence.vue
frontend/src/components/MigrationHistoryTable.vue
frontend/src/components/misc/SQLPreviewPopover.vue

Close BYT-1053
Proposed by @candy2255 
- Cut the displayed SQL statement if it's too long.
- Color the SQL statement a little bit darker to make it easier to be distinguished as "from ... to ..." pattern.
- We also extracted the "action sentence" from plain text to a component. Enabling us to render richer activity action sentences in the future.
The `actionSentence` is complex, that's why we didn't refactor it to template logic this time.
See "CREATE TABLE ......"

feat(frontend): BYT-1053 make SQL change activity more readable

---

api/backup.go
bin/server/cmd/profile.go
bin/server/cmd/profile_dev.go
bin/server/cmd/profile_release.go
bin/server/cmd/root.go
frontend/src/components/DatabaseBackupPanel.vue
frontend/src/types/backup.ts
server/backup_runner.go
server/config.go
server/database.go
server/server.go
server/task_executor_pitr_cutover.go

1. Do not pass backup storage backend from the frontend when creating a backup manually
2. Read backup storage backend from the server profile
When we later add command line flags to choose from local or s3/gcs buckets, the backup storage backend in the profile will be set accordingly.

refactor: read backup storage backend from server profile

---

api/task.go

We need the target database name to restore a full backup.

feat: add database name in restore task field

---

sql-server/advise.go

Add source and version, so that we can figure out if the API call is from the GitHub Action in a specific version

chore: update metric for SQL Service

---

plugin/db/driver.go
plugin/db/driver_test.go
server/webhook.go

This PR addresses two edge cases for `db.ParseMigrationInfo`:
1. Use `path.Join` instead of `filepath.Join` because if the Bytebase happens to run on Windows, the result would be something like `bytebase\testdb__migrate__20220811000000.sql`, and it is never going to be matched with the file path sent from the VCS because all known VCS uses Unix style OS separators (`/`).
2. Escape the `.` characters before sending to be compiled as a regex, it would match any single character instead of `.` literals. See added test case for a failure case.

fix(db): handle edge cases for `ParseMigrationInfo`

---

api/policy.go

Validate assigneeGroupList in ApprovalPolicy
The issueType should be one of
- IssueDatabaseSchemaUpdate
- IssueDatabaseSchemaUpdateGhost
- IssueDatabaseDataUpdate
The issueType in the AssigneeGroupList should not have duplicates.

feat(assignee-group): validate policy

---

server/stage.go
server/task.go

Previously, we only allow
-  the owners and the DBAs if the assignee is the system bot
-  the assignee if set otherwise
to patch the task status.
Now, we judge who can change task status by their roles and the environment policy.
The workspace owners and the DBAs can change the task status no matter what.
The project owners can also change the task status if the policy says so.
@h3n4l FYI

feat: validate change task status privilege by role & policy

---

common/error.go
frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json

Baseline is NOT a pre-requisite for applying migration for VCS-based project. Applying the schema migration will record the latest schema snapshot, which essentially is a baselining.
The code has already relaxed this, we forgot to update the instruction.

fix: update the baseline instruction

---

plugin/db/driver.go
plugin/db/util/driverutil.go
server/task_executor_database_create.go
store/pg_engine.go
tests/schema_update_test.go

Rationale:
1. Make code more readable. I stumbled on `if (m.Type == db.Baseline && !m.CreateDatabase) doMigrate = false` at first. Until I figured we pass Baseline for CREATE DATABASE. It's easy to just remember all Baseline does NOT perform schema change at all.
2. We already use MIGRATE for our own migration in pg_engine.go and because that could mix CREATE DATABASE and other DDL, thus we can not use BASELINE there anyway.
After change:

fix: use MIGRATE instead of BASELINE type for CREATE DATABASE

---

frontend/src/components/EllipsisText.vue
frontend/src/components/TableTable.vue

On 1080P monitors, this may be a problem that long column names would overflow. With texts surrounded with `EllipsisText`, long texts will be truncated, and a tooltip will be used to display the full original content.
https://user-images.githubusercontent.com/56376387/184598939-fad91e72-3a63-40fc-b042-21647fe539b3.mp4

fix(frontend): long name text overflow

---

common/log/logger.go

We now use `github.com/pkg/errors` to create errors, which already have stack info.

chore: remove stack in error logging

---

api/repository.go
api/sql.go
api/task.go
common/log/logger.go
common/util.go
docs/api-style-guide.md
docs/design/pipeline.md
docs/design/pitr-mysql.md
docs/dev-guide.md
enterprise/service/license.go
frontend/src/bbkit/BBTooltipButton.vue
frontend/src/plugins/types.ts
frontend/src/router/index.ts
frontend/src/store/modules/task.ts
frontend/src/types/pipeline/task.ts
plugin/advisor/mysql/advisor_migration_compatibility.go
plugin/advisor/sql_review.go
server/jwt.go
server/metric_reporter.go
store/backup.go

"such as": formal and inclusion.
"like": less formal and comparison.
https://www.grammarbank.com/such-as-vs-like.html
https://pediaa.com/difference-between-like-and-such-as/

docs: use "such as" instead of "like"

---

bin/bb/cmd/migrate.go
plugin/advisor/advisor.go
plugin/advisor/db/db.go
plugin/db/driver.go
plugin/vcs/vcs.go

Change `// nolint` to `//nolint`.
`nolint` is a directive, so it should be `//nolint`, like `//go:build`
refer https://go.dev/doc/comment#:~:text=Arabic%2C%0A%20%20%20%20%22Armenian%22%3A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20Armenian%2C%0A%20%20%20%20...%0A%7D-,Syntax,-Go%20doc%20comments

fix: indent

---

server/webhook.go
server/webhook_test.go

This PR addresses the edge case by escaping the `.` characters before sending to be compiled as a regex, it would match any single character instead of `.` literals. See added test case for a failure case.
Related PR: https://github.com/bytebase/bytebase/pull/2229

fix(webhook): handle edge case for `isSkipGeneratedSchemaFile`

---

plugin/db/mysql/mysql.go
plugin/db/mysql/restore.go
plugin/db/mysql/restore_test.go
server/backup_runner.go

Metadata for binlog files are the source of truth when we deal with binlog files.
Usage of it will be in the following PRs.
We can later add support for GTID Set.
Example metadata file content:
```
$ cat binlog.000108.meta
{"first_event_ts":1660875988}
```
Example tree structure:
```
$ tree backup/instance/6001
backup/instance/6001
├── binlog.000080
├── binlog.000080.meta
...
├── binlog.000108
└── binlog.000108.meta
```

feat(PITR): write binlog metadata file on downloading

---

plugin/db/pg/pg.go
server/issue.go

On Cloud RDS, the data source role isn't the actual superuser with sudo privilege. We need to grant the database owner to the data source admin role so that Bytebase can have permission on the database.

feat: grant database owner to datasource role

---

api/policy.go

Add a new environment policy type "environment tier". It's more like a tag/tier rather than a policy. Users can tag tiers on an environment, and we will add visual indicators based on the "environment tier". For now, we only have the "Protected" tier, but we may add more in the future.
Completing BYT-385

feat(backend): environment visual indicator

---

api/environment.go
store/environment.go
store/policy.go

Compose `environmentTier` into `environment` so that the frontend doesn’t have to fetch the policy for every environment, which is a hassle.

feat: compose environmentTier into environment

---

frontend/src/assets/css/tailwind.css
frontend/src/components/DatabaseBackup/DatabaseBackupSettingForm.vue
frontend/src/components/DatabaseBackup/utils.ts

Close BYT-1063
Proposed by @candy2255 . FYI @dragonly .
The default value is 7 days (`retentionPeriodTs = 604800`). When the textbox is empty it will no longer show a red border.

feat(frontend): default value and placeholder of retention period

---

frontend/src/bbkit/BBSelect.vue
frontend/src/bbkit/BBTab.vue
frontend/src/bbkit/types.ts
frontend/src/components/AlterSchemaPrepForm/ProjectStandardView.vue
frontend/src/components/DatabaseTable.vue
frontend/src/components/Environment/ProtectedEnvironmentIcon.vue
frontend/src/components/EnvironmentForm.vue
frontend/src/components/EnvironmentSelect.vue
frontend/src/components/Issue/IssueSidebar.vue
frontend/src/components/Issue/IssueTable.vue
frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json
frontend/src/types/environment.ts
frontend/src/types/plan.ts
frontend/src/types/policy.ts
frontend/src/views/DatabaseDetail.vue
frontend/src/views/EnvironmentDashboard.vue
frontend/src/views/EnvironmentDetail.vue

BYT-386
Configuration
Database list and issue list
Database detail
Environment selector dropdown
Issue sidebar
I consider we need to compose the environment-tier policy value as an environment's attribute to make the shield icon's display logic much more simple. wdyt @RainbowDashy

feat(frontend): Allow to mark an environment as protected

---

plugin/db/pg/sync.go

More detail in linear issue. We use oid as much as possible.
Edge case:
Normal case(pagila):

fix: handle PostgreSQL double quotes properly when getting tables information

---

server/issue.go
server/pipeline.go
server/task.go
server/task_executor.go
server/task_scheduler.go
server/task_test.go

Currently, we run the tasks in the pipeline one by one, though some can be run at the same time.
This PR makes it possible to run tasks that are in the same stage and have no dependencies concurrently.
Close BYT-932

feat: run tasks concurrently

---

api/project.go
store/repository.go

As discussed in https://github.com/bytebase/bytebase/pull/2283#discussion_r950858531, using `*string` as the current workaround.
Note that this field is not used at all currently, but is updated to be future-proof. 
---
Changes are extracted from https://github.com/bytebase/bytebase/pull/2333, stack on https://github.com/bytebase/bytebase/pull/2389, part of https://linear.app/bbteam/issue/BYT-1065/implement-sbm-mvp-version

fix(project): remove use of unsupported pointer type

---

store/migration/dev/20220807000000__add_project_schema_migration_type.sql
store/migration/dev/LATEST.sql

This PR adds a DB migration to add the `project.schema_migration_type` column, which will be used to store what type of schema migration the project uses.
DDL stands for Data Definition Language and SDL stands for Schema Definition Language.
---
Changes are extracted from https://github.com/bytebase/bytebase/pull/2333, part of https://linear.app/bbteam/issue/BYT-1065/implement-sbm-mvp-version

feat(db): add `schema_migration_type` column to `project` table

---

plugin/vcs/gitlab/gitlab.go
server/webhook.go
server/webhook_test.go

State-based migration needs to be able to read from a modified schema file, thus we need to make it possible to include the list of modified files from the webhook payload.
---
Changes are extracted from https://github.com/bytebase/bytebase/pull/2333, part of https://linear.app/bbteam/issue/BYT-1065/implement-sbm-mvp-version

feat(webhook): support optionally including modified files from payload

---

plugin/db/mysql/restore.go
tests/mysql_test.go

This is not necessary for now. Remove for simplicity.

refactor: do not deal with truncated binlog files

---

go.mod
plugin/advisor/advisor.go
plugin/advisor/generator/README.md
plugin/advisor/generator/main.go
plugin/advisor/generator/mysql.template
plugin/advisor/generator/mysql_test.template
plugin/advisor/mysql/advisor_column_disallow_changing_type.go
plugin/advisor/mysql/advisor_column_disallow_changing_type_test.go

I write a SQL review rule framework code generator to help us implement rules quickly.
This is only for MySQL now. I'll support PostgreSQL in the following PR.
The files in this PR: `plugin/advisor/mysql/advisor_column_disallow_changing_type.go` and `plugin/advisor/mysql/advisor_column_disallow_changing_type_test.go` are generated by this generator. I'll implement them later.

chore: add a SQL review rule framework code generator

---

plugin/db/pg/dump.go
plugin/db/pg/pg.go

CREATE EVENT TRIGGER statement only supports EXECUTE PROCEDURE in version 10 and before, while newer version supports both EXECUTE { FUNCTION | PROCEDURE }.
Since we use pg_dump version 14, the dump uses a new style even for an old version of PostgreSQL. We should convert EXECUTE FUNCTION to EXECUTE PROCEDURE to make the restoration work on old versions.
https://www.postgresql.org/docs/14/sql-createeventtrigger.html

fix: convert EXECUTE FUNCTION to PROCEDURE for CREATE EVENT TRIGGER statements

---

frontend/src/bbkit/BBContextMenuButton.vue
frontend/src/bbkit/BBTooltipButton.vue
frontend/src/bbkit/index.ts
frontend/src/bbkit/types.ts
frontend/src/components/DatabaseDetail/PITRRestoreButton.vue
frontend/src/components/Issue/IssueStatusTransitionButtonGroup.vue
frontend/src/utils/pipeline.ts

Re-implement the task approval button and pitr restore button. Who's style and logic are very similar to GitHub's create pull request button. 
The selected action will be stored in the user's browser localStorage, and set as the default selection next time if possible.
FYI @dragonly 
----
----

feat(frontend): GitHub style button with context menu

---

frontend/src/components/Issue/IssueTaskStatementPanel.vue

Close BYT-1257
call `setEditorAutoCompletionContext` automatically when `databaseList` and `tableList` changed.

fix(frontend): auto-complete does not work in the standard project with multi-tasks

---

frontend/src/components/Issue/IssueTaskStatementPanel.vue
frontend/src/components/MonacoEditor/MonacoEditor.vue
frontend/src/components/MonacoEditor/useMonaco.ts
frontend/src/store/modules/sqlEditor.ts
frontend/src/views/sql-editor/EditorPanel/SQLEditor.vue

Provide **lexical level** auto-completion suggestions.
- if the input is `"x."` x might be
- `"{database_name}."` (mysql)
- `"{table_name}."` (mysql)
- also try `"public.{table_name}."` as a table name, since `"public"` schema can be omitted by default (postgresql only)      
-  `"{schema_name}."` (postgresql) - will implement next time
- alias (can not recognize yet)
- if the input is `"x.y."` it might be
- `"{database_name}.{table_name}."` (mysql)
- `"{schema_name}.{table_name}."` (postgresql)
- `"{database_name}.{schema_name}."` (postgresql) - will implement next time
- if the input is `"x.y.z."` it might be
- `"{database_name}.{schema_name}.{table_name}."` (postgresql only)
So we can provide different types (table names of a database, or column names of a table) of suggestions.
- We …

feat(sql-editor): auto-completion improvement

---

.github/workflows/codenotify.yml

By default, Codenotify can't post comments to a PR from forked repositories, thus we give the action minimum explicit permissions to be able to read repository files and post comments to pull requests.
Ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions

chore: always allow Codenotify to post comments

---

server/server_frontend_embed.go

This can save some MBs of data transfering.
Close BYT-1274

chore: cache static assets

---

frontend/src/components/MonacoEditor/MonacoEditor.vue
frontend/src/components/MonacoEditor/useMonaco.ts
frontend/src/utils/types.ts

- Add return type annotation for `useMonaco`.
- Rename `getEditorInstance` to `initEditorInstance`.
- Remove unused typescript language support for monaco editor.

chore(sql-editor): add type annotation

---

plugin/db/mysql/dump.go

With an empty database, the SQL would be `FLUSH TABLES  WITH READ LOCK;` which requires a global lock and cannot be unlocked.
Thanks to @candy2255 for reporting this issue.

fix: do not flush tables when dumping an empty database

---

server/task_executor_pitr_restore.go

`payload.TargetInstanceID != nil` is always true here.

chore: remove dead code

---

plugin/db/mysql/restore.go
plugin/db/mysql/restore_test.go
server/task_executor_pitr_restore.go

This enables us to download as fewer binlog files as possible when replaying binlog from the cloud storage.
It also makes the progress estimation more accurate.

feat: get the binlog replay list with an end

---

bin/bb/cmd/var.go
store/metadb.go

Several popular services such as render.com, supabase use postgres://.

feat: allow postgres:// scheme for --pg

---

plugin/parser/ast/alter_table_stmt.go
plugin/parser/ast/create_index_stmt.go
plugin/parser/ast/create_table_stmt.go
plugin/parser/ast/ddl_node.go
plugin/parser/ast/drop_database_stmt.go
plugin/parser/ast/drop_index_stmt.go
plugin/parser/ast/drop_table_stmt.go
plugin/parser/ast/rename_index_stmt.go
server/task_check_executor_statement_type.go
server/task_check_executor_statement_type_test.go

Tips:
- PostgreSQL parser cannot parse all DDL statements now. I'll enhance it in the future.

fix: only block DDL/SELECT/EXPLAIN statement in CHANGE DATA

---

frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/composables/useExecuteSQL.ts
frontend/src/views/sql-editor/TablePanel/DataTable.vue
frontend/src/views/sql-editor/TablePanel/TableView.vue

- Using native `<table>` instead of `<NDataTable>` in naive-ui. Fewer features but better performance.
- Frontend pagination. Won't show too many rows on a page. And we won't struggle with virtual rendering for large amount of rows.
- Horizontal scrolling is enabled when there are too many columns.
- Similar style to tables in Bytebase control.
- Throttled event handler for the search box.
- A common user story (with pagination and filtering)
- Another user story (with the Bytebase example employee dataset)
- Stress test (the server-side has limited the maximum row count of response to 10k)
- Horizontal scrolling. Text in the table header won't wrap.

feat(frontend): SQL editor query result table improvement

---

tests/backup_restore_test.go

This test is **identical** to the "Drop Database" test.
The database name is generated from the test name and already has both uppercase and lowercase letters.

test: remove unneeded PITR case sensitive test

---

frontend/src/views/sql-editor/TablePanel/DataTable.vue
frontend/src/views/sql-editor/TablePanel/useTableResize.ts

- Automatically calculate columns' widths according to the table header and content (with min/max width limitation).
- Drag to resize a column.
- Double-click to auto-fit column width.

feat(sql-editor): support table column resizing

---

tests/backup_restore_test.go
tests/tests.go

By diff, `TestPITRBuggyApplication` is a subset of `TestPITRSchemaMigrationFailure`.
This PR merges them and rename it to `TestPITRGeneral`, which tests for the general cases.

chore: merge unnecessary test cases

---

server/task_check_executor_statement_advisor_composite.go
tests/sql_review_test.go

We need to find other ways to guide users to new features.

chore: don't warn on empty sql review policy

---

frontend/src/components/RepositoryForm.vue

The use of `sheetPathTemplate` is independent of DDL or SDL.

chore(sdl): display `sheetPathTemplate` setting

---

frontend/src/views/sql-editor/TabListContainer.vue

We once used a shared state for all tabs incorrectly. This PR will fix it.

fix(sql-editor): render sheet icon independently for each tab

---

api/issue.go
api/task.go
server/issue.go
server/task_executor.go
server/task_executor_data_update.go
server/task_executor_schema_update.go
server/task_executor_schema_update_ghost_cutover.go
server/webhook.go

This way, we can process the VCS-created issue even if the path template is changed before the issue is running.
This also passes the schema version of the migration info into the task payload. This enables us to find tasks with a specific schema version. Then we can utilize the modified files in VCS push events to change pending/failed task's SQL statement.

chore: pass migration info from vcs webhook

---

plugin/db/mysql/dump.go
plugin/db/mysql/dump_test.go

Align with mysqldump implementation for MySQL backup.
1) disabled unique and foreign-key checkers to disrespect the schema and data dependency;
2) created temporary view and recreate final views to address the view to table schema dependency.

fix: align with mysqldump

---

server/oauth.go
server/server_frontend_embed.go
server/server_frontend_not_embed.go

After https://github.com/bytebase/bytebase/pull/2608
We consolidate the backend and frontend addresses into a single `--external-url`. We can do this because our release build bundles backend and frontend together.
On the other hand, this brings complexity to our development environment. Our dev environment runs backend and frontend on separate ports. This is for getting frontend hot reloading. The major obstacle is the OAuth redirect URL which points to the frontend address. 
To overcome this, This PR overrides the redirect URL when frontend is not embedded in the backend and returns our default frontend address http://localhost:3000 used in our dev environment.

feat: improve local development for VCS integration

---

scripts/.air.toml
server/server_frontend_not_embed.go

Followup of https://github.com/bytebase/bytebase/pull/2625
Make BB_REDIRECT_URL more explicit so developers working on our codebase can understand the hidden magic.

feat: introduce BB_REDIRECT_URL for non-embedded mode

---

api/project.go
frontend/src/components/ProjectGeneralSettingPanel.vue
frontend/src/components/RepositoryConfigPanel.vue
frontend/src/components/RepositoryForm.vue
frontend/src/components/RepositoryPanel.vue
frontend/src/components/RepositorySetupWizard.vue
frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/project.ts
frontend/src/types/project.ts
server/task_executor.go
server/webhook.go
store/migration/dev/20220807000000__add_project_schema_change_type.sql
store/migration/dev/20220807000000__add_project_schema_migration_type.sql
store/migration/dev/LATEST.sql
store/project.go
tests/schema_update_test.go

We have started using the term "SchemaChangeType" instead of "SchemaMigrationType" since https://github.com/bytebase/bytebase/pull/2618 as our product language, this PR updates all other places to be consistent with our product language, do it now or suffer later.
CI and manually tested.
---
cc @tianzhou

refactor(sbm): rename SchemaMigrationType to SchemaChangeType

---

frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
frontend/src/components/Issue/IssueTaskStatementPanel.vue
frontend/src/types/repository.ts
frontend/src/views/DatabaseDetail.vue

Close BYT-1344
Try to replace the segments from left to the right as long as possible.
Once we meet a "dynamic" segment that has a pattern that cannot be replaced, we won't push it, nor the segments behind it.
E.g., the `filePathTemplate` is
`configure/{{ENV_NAME}}/20220707-wechat/{{TYPE}}/**/**/**/{{DB_NAME}}__{{VERSION}}__{{DESCRIPTION}}.sql`
The segments are
- configure
- {{ENV_NAME}}
- 20220707-wechat
- {{TYPE}}
- **
- **
- **
When
- `DB_NAME=what_ever`
- `ENV_NAME=dev`
- `TYPE=migrate`
we are confident enough that the path will be started with `/configure/dev/20220707-wechat/migrate`
That's our best effort.

feat(frontend): open the VCS filePathTemplate as long as possible

---

api/issue.go
server/issue.go
server/task_executor.go
server/webhook.go

This PR minimizes the difference between UI and VCS migration.

chore: do not parse VCS file name in task executor

---

api/cache.go
api/label.go
store/database.go
store/label.go

Currently, database label queries are made whenever we read the database. We should cache it by database ID.

chore: add cache for database labels

---

api/anomaly.go
store/anomaly.go

We need `anomaly.database` to display the schema drift diff dialog. And I'd like to compose it in backend instead of fetching it in frontend.

chore: compose instance and database into anomaly

---

plugin/db/mysql/restore.go
plugin/storage/s3/s3.go

This avoids the situation that the source and target files are in different volumns, which triggers the error "invalid cross-device link" for `os.Rename`.
Fix BYT-1419.

fix: rename in the same directory

---

server/project.go
store/pg_engine.go
store/project.go

1. patch project key cannot be empty
2. return more specific errors when the project key exists
Thanks to @candy2255 for reporting the issue.

fix: patch project key errors

---

plugin/advisor/catalog/state.go
plugin/advisor/catalog/walk_through.go
plugin/advisor/catalog/walk_through_test.go

support:
1. CREATE TABLE ... LIKE ...
2. ALTER DATABASE
3. DROP DATABASE
4. RENAME TABLE
5. return error for CREATE DATABASE
close BYT-1339

feat(catalog): walk-through support some MySQL statements

---

api/issue.go
docs/design/gh-ost-integration.md
frontend/src/components/Issue/logic/GhostModeProvider.ts
frontend/src/components/Issue/logic/TenantModeProvider.ts
frontend/src/components/Issue/logic/common.ts
frontend/src/plugins/issue/logic/initialize/ghost.ts
frontend/src/plugins/issue/logic/initialize/standard.ts
frontend/src/plugins/issue/logic/initialize/tenant.ts
frontend/src/types/issue.ts
server/issue.go
server/webhook.go
tests/ghost_test.go
tests/schema_update_test.go
tests/sql_review_test.go
tests/tenant_test.go

The struct was intended for updating schema in the beginning but the name should be migration for repurposing to data change.

chore: rename UpdateSchema to Migration in issue creation

---

frontend/src/store/modules/activity.ts

Close Editor history does not work
We once fetch only query history items that were executed successfully. Now we also fetch the items that were executed without error but with warnings.
The `/api/activity` API endpoint doesn't support multiple `level` filters in a request. So we request them both and then mix them at the frontend side.

fix(sql-editor): Editor history does not work

---

server/webhook.go

Do not prepare the issue for DDL if the project type is SDL.
This change split the implementation of DDL and SDL. It makes a later PR to create issue(s) per commit(s) possible, which can contain multiple files.

refactor(VCS): do not call DDL from SDL

---

frontend/src/plugins/i18n.ts

The output of `import.meta.glob` is changed. We don’t know the order of the walkthrough, need to use the deep merge to ensure the localization files merge succeeded.

fix: localization file merge

---

store/backup.go

Fix the panic:
```
2022-09-17T00:03:01.670+0800	ERROR	Auto backup runner PANIC RECOVER	{"error": "runtime error: invalid memory address or nil pointer dereference", "panic-stack": "[github.com/bytebase/bytebase/server.(*BackupRunner).Run.func1.1\n\t/Users/danny/src/bytebase/server/backup_runner.go:61\nruntime.gopanic\n\t/opt/homebrew/Cellar/go/1.19.1/libexec/src/runtime/panic.go:890\nruntime.panicmem\n\t/opt/homebrew/Cellar/go/1.19.1/libexec/src/runtime/panic.go:260\nruntime.sigpanic\n\t/opt/homebrew/Cellar/go/1.19.1/libexec/src/runtime/signal_unix.go:835\ngithub.com/bytebase/bytebase/server.(*BackupRunner).startAutoBackups\n\t/Users/danny/src/bytebase/server/backup_runner.go:307\ngithub.com/bytebase/bytebase/server.(*BackupRunner).Run.func1\n\t/Users/danny/src/bytebase/server/backup_runne …
```

fix: must find a database in composeBackupSetting

---

store/backup.go
store/database.go
store/migration/prod/1.4/0002__delete_wildcard_database_backup_settings.sql
store/pg_engine_test.go

The backup settings could point to wildcard databases previously causing in composeBackupSettings() to fail because GetDatabase() will return nil for the wildcard database.
1. We should prevent database settings upserts for wildcard databases.
2. change data to delete any previous backup settings for wildcard databases.

chore: don't upsert backup settings for wildcard databases

---

frontend/src/components/Issue/PagedIssueTable.vue
frontend/src/components/ProjectOverviewPanel.vue
frontend/src/store/modules/auth.ts
frontend/src/views/Home.vue
frontend/src/views/IssueDashboard.vue

Close BYT-1324
It's complex and dangerous to cache the issue list.
So we just memorize how many times the user clicks the "load more" button, and load the first N pages in the first fetch.
E.g., if the user clicked "load more" 4 times, then the first time will set the `limit` to `pageSize * 5`.
The session will be reset in 1 minute after the last visit to the issue list.
Though the first fetch might be a little bit slower if the `limit` gets larger. It's more stable than fetching the pages one-by-one since an async request chain if quite complex to control.

feat(frontend): memorize pagination state

---

frontend/src/types/sqlReview.ts
frontend/src/views/SettingWorkspaceSQLReviewDetail.vue

After we add a new rule in the SQL review, we won’t migrate existing policies in the user’s database. So we need to show these new rules in the frontend with disabled level status.

fix: show new rules with disabled level in the frontend

---

frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue

We used to need to click the icon to set the tab's connection.
That was weird and not discoverable to users.
Now since we've solved the problem of mutating a sheet tab's connection unexpectedly in #2576 and #2612 , we are getting rid of the icon. Just click the tree node to set the connection.

feat(sql-editor): click the tree node to set connection

---

frontend/src/bbkit/BBSelect.vue

`isEmpty(2)` of lodash returns `true`. We shouldn't use it here.
Thanks for the reporting from @dragonly

fix(frontend): BBSelect placeholder disappears

---

frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/components/MonacoEditor/MonacoEditor.vue
frontend/src/components/MonacoEditor/useMonaco.ts
frontend/src/plugins/sql-lsp/client/useLanguageClient.ts
frontend/src/plugins/sql-lsp/server/server.ts

- Use a safer way. Import `@codingame/monaco-vscode-api` directly rather than import it via `vscode` and module alias.
- A better implementation of `MonacoEnvironment` (ref: [using monaco-editor in vite](https://github.com/microsoft/monaco-editor/blob/main/docs/integrate-esm.md#using-vite))
- Added some debug logs.
Reason
Seems that using module alias makes someone of vite/typescript/pnpm perform differently between the dev stage and release stage.

fix(sql-editor): auto-completion doesn't work in release build

---

store/backup.go

We will later reuse this validation for batch updating backup settings for all databases in an environment.

refactor: extract validation logic for backup setting

---

plugin/parser/differ/mysql/column_test.go
plugin/parser/differ/mysql/differ.go

NOTE: MySQL will help us to drop the column comment if the comment option does not exists in the alter table modify column spec.

feat: generate alter table stmt modify column specs if the comments of two columns not match

---

frontend/src/components/EnvironmentSelect.vue

fix(frontend): remove the color reverse for <EnvironmentSelect> when hovered

---

frontend/src/plugins/sql-lsp/client/useLanguageClient.ts

Store pending commands when the client is not connected yet. And execute them the first time when the connection starts.
We only keep the latest command for each type and drop the outdated ones.
So we don't need to know the perfect timing to call `executeCommand` neither in <MonacoEditor> nor wherever. Just call it.

feat(sql-editor): store pending commands

---

frontend/src/components/QuickActionPanel.vue

Before
After
Thanks for the reporting from @unknwon

fix(frontend): vertical align quick action items

---

api/task_check_run.go
server/server.go
server/task_check_executor_lgtm.go
server/task_check_scheduler.go

Add a new task checker which will look for "LGTM" comments from project members or project owners.
We won't schedule the LGTM task checker if it's disabled.
The LGTM checker checks by testing `comment == "LGTM"`, so only typing "LGTM" or clicking the LGTM button counts as valid LGTM. And of course, an "LGTM" by the issue creator doesn't count.

feat: lgtm task checker

---

frontend/src/components/OnboardingGuide.vue

Fetching the data directly instead of useStore to prevent data cached in store.

fix: fetch data directly for onboarding guide

---

server/task_check_executor_ghost_sync.go
server/task_executor_schema_update_ghost_sync.go

- Abstract a new func `getGhostConfig`.
- Remove some local vars.

refactor: gh-ost new migration context

---

server/server.go
server/task_scheduler.go

When Bytebase stops, there may be running tasks such as backup for a big database, which can take hours to finish. When the process exits, the task executors exit too. However, the task status in the metadata is still RUNNING.
This PR cancels the running tasks on the server start, so the state is correct.
Fix BYT-1348.
Fix BYT-1349.

feat: cancel running tasks on server start

---

server/task_executor.go

Currently, migrationInfo.Environment is nil in the VCS code path, which will results in invalid schema file for write back.
Issue example:
failed to create file after applying migration 5 to "db-1": failed to create file through URL https://gitlab.bytebase.com/api/v4/projects/63/repository/files/bytebase%2F%2F.db-1__LATEST.sql, status code: 400, body: {"branch":"main","content":"SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;\nSET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;\n--\n-- Table structure for `t1`\n--\nCREATE TABLE `t1` (\n  `id` int DEFAULT NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;\n\n--\n-- Table structure for `t4`\n--\nCREATE TABLE `t4` (\n  `id` int NOT NULL,\n  PRIMARY KEY (`id`)\n) ENGINE=InnoDB DEFAULT …

fix(vcs): nil environment for schema file write back

---

plugin/vcs/github/github.go
plugin/vcs/github/github_test.go
plugin/vcs/gitlab/gitlab.go
plugin/vcs/gitlab/gitlab_test.go
plugin/vcs/internal/oauth/oauth.go
plugin/vcs/internal/oauth/oauth_test.go
scripts/.air.toml
tests/fake/gitlab.go

[Older versions of GitLab did not handle reading large file requests perfectly](https://gitlab.com/gitlab-org/gitlab-pages/-/issues/315). We move to use [another API](https://docs.gitlab.com/ee/api/repository_files.html#get-raw-file-from-repository) to get raw file content.

chore: use raw api to get GitLab file content

---

frontend/src/store/modules/sqlEditor.ts
frontend/src/views/sql-editor/AsidePanel/QueryHistoryContainer.vue

- Fetch the latest 20 query history items.
- Disable deleting.
- Since we have only one action now, we removed the dropdown and leave only the [copy to clipboard] button.

fix(sql-editor): disable deleting query history

---

frontend/src/components/Issue/IssueDetailLayout.vue
frontend/src/components/Issue/TaskCheckBadgeBar.vue
frontend/src/components/Issue/TaskCheckBar.vue
frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json
frontend/src/types/pipeline/task.ts

We now show the <TaskCheckBar> for all task types. Just check if `task.taskCheckRunList.length > 0`
Close BYT-1529

feat(frontend): show task check bar for more task types

---

server/project.go

Currently, all of the VCS repositories have the same `WebhookEndpointID` (workspace ID). This results in a bug when reading file content form the VCS for a multiple repo setup.
This PR changes the `WebhookEndpointID` to "workspace ID / current unix timestamp". This also enables us to know the creation time of the webhook, which makes debug easier.

fix: differentiate vcs repo's webhook endpoint ID

---

frontend/src/views/sql-editor/SQLEditorPage.vue
frontend/src/views/sql-editor/TabListContainer.vue

We once used a static calculation for the containers' heights. Now we use flex that will be responsive whenever the debug banner is on or off.
Before
After

fix(sql-editor): responsive height when debug banner is on

---

server/webhook.go

Repository log contains repeated creator info, which spams the log.

chore: reduce log of repo internal structure

---

frontend/src/components/Issue/IssueActivityPanel.vue
frontend/src/components/Issue/IssueDetailLayout.vue

- Automatically re-run task checks after an "LTGM" comment (either the LGTM button or manually comment "LGTM").
- The run task checks API endpoint will run all check types if possible. I consider it will be better to support running specified type(s) of task checks. wdyt @RainbowDashy

feat(frontend): run task checks after an LGTM

---

frontend/src/components/Issue/IssueActivityPanel.vue
frontend/src/components/Issue/IssueDetailLayout.vue

- Automatically re-run task checks after an "LTGM" comment (either the LGTM button or manually comment "LGTM").
- The run task checks API endpoint will run all check types if possible. I consider it will be better to support running specified type(s) of task checks. wdyt @RainbowDashy

chore(1.5.0): cherrypick pr #2846

---

frontend/src/store/modules/sqlEditor.ts
frontend/src/types/tab.ts
frontend/src/utils/tab.ts
frontend/src/views/sql-editor/AsidePanel/TableSchema.vue
frontend/src/views/sql-editor/EditorPanel/EditorPanel.vue

Remove `connection.projectId` since it can be inferred from `connection.databaseId` via the database's detail fields.

refactor(sql-editor): remove Connection.projectId

---

frontend/src/store/modules/tab.ts
frontend/src/types/store.ts

Refactor the tab store with [pinia setup api](https://pinia.vuejs.org/core-concepts/#setup-stores). No code logic changes.
This refactor is a preparation for the upcoming tab list local store (BYT-1538).

refactor(sql-editor): tab store with setup api

---

frontend/src/components/ProvideSQLEditorContext.vue
frontend/src/store/modules/sqlEditor.ts
frontend/src/types/store.ts
frontend/src/utils/dom.ts
frontend/src/utils/index.ts
frontend/src/utils/util.ts
frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue
frontend/tsconfig.json

- Won't re-build the tree when redirecting from the "Sheets" page.
- Expand, highlight and locate the corresponding tree node when switching tabs or the current tab's connection params changed.
Highlighting
Scroll the node into view if needed
Also: close BYT-1517

feat(sql-editor): database tree improvement

---

api/project.go
frontend/src/components/TransferDatabaseForm/SelectDatabaseLabel.vue
plugin/db/driver.go
server/database.go
server/deploy.go
server/issue.go

Currently, we only allow two possible values `{{DB_NAME}}` and `{{DB_NAME}}_{{TENANT}}` to be used as the database name template for tenant projects with GitOps workflow. Both of them imply a single file change will only apply to a single database.
This PR adds the support to allow a third possible value wildcard (`*`) to be used as the database name template, which implies a single file change will be applied to _all_ databases within the project.
One file commit changes all (two) databases in the project:
- I will add integration tests once the approach looks good.

feat: allow wildcard (`*`) as database template name for tenant projects

---

api/project.go
frontend/src/components/ProjectCreate.vue
frontend/src/components/TransferDatabaseForm/SelectDatabaseLabel.vue
plugin/db/driver.go
server/database.go
server/deploy.go
server/deploy_test.go
server/issue.go

1. Use database name template {{DB_NAME}} for the case that each tenant belongs to a standalone database instance and all tenant databases have the same name.
2. Use an empty database name template for the cases in that we don't restrict tenant database naming. And all tenant databases in the same project belong to the same group.
3. Change default database name template to {{DB_NAME}}_{{TENANT}} in Frontend.

chore: use empty database name template for naming unrestricted mode

---

frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
frontend/src/components/AlterSchemaPrepForm/ProjectTenantView.vue
frontend/src/components/ProjectCreate.vue
frontend/src/components/TenantDatabaseTable/TenantDatabaseTable.vue
frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json

The database name template is rebranded to restrict the format of database naming. 
1. The "Create Project" form allows users to decide whether all tenant databases should follow a naming template.
2. All tenant databases for empty dbNameTemplate project will be the same group.
TODO1: we need to tune the tenant database matrix to better display tenant databases. Right now, it looks quite strange even for both empty and non-empty dbNameTemplate cases.
TODO2: allow users to update dbNameTemplate after the project is created.

feat: frontend support for empty database name template

---

api/data_source.go
api/database.go
api/instance.go
frontend/src/components/CreateInstanceForm.vue
frontend/src/components/InstanceForm.vue
frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json
frontend/src/types/dataSource.ts
frontend/src/types/instance.ts
server/database.go
server/instance.go
server/schema_syncer.go
server/sql.go
server/task_executor_database_create.go
store/database.go
tests/sql_review_test.go

1. Remove the "Sync Now" option.
2. On instance creation, we will first sync the database list, engine version, and user list of the instance. Then we will sync the schema of its databases asynchronously.
TODO: optimize schema sync runner to sync instances and databases.

chore: sync instance offline on instance creation

---

README.md

Reverts bytebase/bytebase#2872
Updated kill delay instead.

chore: Revert "docs: use air 1.29.0"

---

server/webhook.go

Reduce the complexity of the function `processFile()`.
This PR also makes it easier to implement the logic of creating one issue per push event for DDL migration while preserving the behavior of creating one issue per schema file for state-based migration.

refactor: extract logic of creating issue

---

frontend/src/assets/css/tailwind.css
frontend/src/views/sql-editor/TablePanel/DataTable.vue

A very hacky CSS technique @_@
Close BYT-1543
Before
After
And this only reproduces when using a mouse or setting the "Show scroll bars" to "Always" in the system general settings.

fix(frontend): scrollbar z-index

---

server/acl_casbin_policy_dba.csv
server/acl_casbin_policy_developer.csv
server/acl_casbin_policy_owner.csv
server/task.go
server/task_executor.go
server/task_executor_schema_update_ghost_sync.go
server/task_scheduler.go

Add a new HTTP endpoint`POST /pipeline/:pipelineID/task/:taskID/cancel` which cancels a running task executor.
This task cancellation feature leverages golang context behind the scene.
In this PR, only canceling gh-ost sync task is implemented.
We can only cancel tasks by canceling the whole issue before. Now we can have an open issue with some canceled tasks which were not possible before IIUC. We may need to revisit the UI and logic of this part afterward.
Close BYT-1386

feat: cancel gh-ost sync task

---

api/project.go
api/project_test.go
server/project.go

Tenant projects with empty database name template imply wildcard matching for all databases, thus we also need to allow the `filePathTemplate` to be able to omit `{{DB_NAME}}` for this type of projects.

feat: allow omit `{{DB_NAME}}` in `filePathTemplate` for wildcard tenant projects

---

README.md
scripts/.air.toml

The "additional runtime parameters such as --backup-bucket" in https://github.com/bytebase/bytebase#steps never work.
1. We need to use bin instead of full_bin for taking additional runtime parameters.
2. air 1.30.0 hasn’t yet supported additional runtime parameters yet.
3. The latest air will not shutdown PostgreSQL server gracefully. So we have to use a forked repo with the patch.

chore: use bin instead of full_bin

---

frontend/src/components/Issue/IssueActivityPanel.vue
frontend/src/components/Issue/StatusTransitionForm.vue
frontend/src/components/Issue/TaskStatusIcon.vue
frontend/src/components/Issue/activity/ActionSentence.vue
frontend/src/components/Issue/logic/GhostModeProvider.ts
frontend/src/components/Issue/logic/base.ts
frontend/src/utils/pipeline.ts

It's awkward that canceling the ghost sync task (the first task) leaves the ghost cutover task (the second task) PENDING_APPROVAL. This is weird that the second task can never be scheduled because it's blocked by the first one. Making the issue meaningless as if it's dead.
We might detect this situation and automatically close/cancel the entire issue. wdyt @RainbowDashy 
--
--

feat(frontend): allow cancelling gh-ost sync tasks

---

frontend/src/views/sql-editor/TablePanel/DataTable.vue
frontend/src/views/sql-editor/TablePanel/useTableResize.ts

1. The table header track scrolls with the content.
2. Sometimes we see assigning to an undefined value's property in the console (only occurs in dev hot reload mode).

fix(sql-editor): result table fixes

---

api/policy.go
server/task.go

Close BYT-1612
skip manual approval -> require dba or workspace owner
payload is
```
{"value":"MANUAL_APPROVAL_ALWAYS","assigneeGroupList":[]}
```
require project owner -> dba or workspace owner
payload is
```
{"value":"MANUAL_APPROVAL_ALWAYS","assigneeGroupList":[{"issueType":"bb.issue.database.schema.update","value":"WORKSPACE_OWNER_OR_DBA"},{"issueType":"bb.issue.database.data.update","value":"WORKSPACE_OWNER_OR_DBA"},{"issueType":"bb.issue.database.schema.update.ghost","value":"WORKSPACE_OWNER_OR_DBA"}]}
```
The assignee group value "WORKSPACE_OWNER_OR_DBA" is not handled on the backend, which leads to "invalid AssingeeGroupValue" error.
Because some users may already have "WORKSPACE_OWNER_OR_DBA" value stored, we fix the problem by adding it on the backend instead of removing it from …

fix: assigneeGroupValue

---

frontend/src/components/EnvironmentForm/AssigneeGroupEditor.vue

As mentioned in #2982 
When switching from "skip manual approval" -> "require manual approval", the policy payload becomes 
```
{"value":"MANUAL_APPROVAL_ALWAYS","assigneeGroupList":[]}
```
But when switching from "require project owner" -> "dba or workspace owner", the policy payload becomes
```
{"value":"MANUAL_APPROVAL_ALWAYS","assigneeGroupList":[{"issueType":"bb.issue.database.schema.update","value":"WORKSPACE_OWNER_OR_DBA"},{"issueType":"bb.issue.database.data.update","value":"WORKSPACE_OWNER_OR_DBA"},{"issueType":"bb.issue.database.schema.update.ghost","value":"WORKSPACE_OWNER_OR_DBA"}]}
```
They are equivalent since our logic fallbacks to the second one ("MANUAL_APPROVAL_ALWAYS" + "WORKSPACE_OWNER_OR_DBA") when seeing the first one. But it's confusing that different values have …

fix(frontend): fill the value correctly when switching from "skip" to "require"

---

server/task.go

Set the `result` field which will eventually show on the task run table on the frontend.

feat: add cancel task result msg

---

frontend/src/router/index.ts
frontend/src/views/DatabaseDetail.vue

- Hide the [Alter Schema] and [Change Data] buttons in the quick action list of the default project.
- Hide the [Alter Schema] and [Change Data] buttons on the database detail page which belongs to the default project.
- It's better to show the buttons anyway and inform the user we should transfer the database to a project before migrating. Hiding them are just a quick way to prevent errors.
Thanks for the suggestions from @dragonly 
Close BYT-1616

feat(frontend): Disable creating issue in the default project

---

plugin/parser/ast/serial.go
plugin/parser/engine/pg/convert.go
plugin/parser/engine/pg/convert_test.go
plugin/parser/engine/pg/deparse.go
plugin/parser/engine/pg/deparse_test.go

Before this, we expanded the serial type in the parser. Now we realize that we shouldn't expand it. Because the parser should only parse the statement.

chore(parser): not expand the serial type

---

frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue
frontend/src/views/sql-editor/AsidePanel/utils.ts

fix(sql-editor): Miss database logo before instance label in the SQL editor left navigation

---

.github/workflows/build-artifacts-and-draft-release.yml
.github/workflows/tests.yml

- [GitHub Actions: All Actions will begin running on Node16 instead of Node12](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)
- [pnpm/action-setup/#56](https://github.com/pnpm/action-setup/pull/56/files)
- [pnpm/action-setup/release/v2.2.3](https://github.com/pnpm/action-setup/releases/tag/v2.2.3)

chore: bump the version of pnpm/action-setup to 2.2.3

---

plugin/parser/differ/mysql/differ.go
plugin/parser/differ/mysql/index_test.go

When we try to update the index with the same name, we cannot update it in place but drop it first and then create the new one.
We introduce `inplaceDropNodeList` and `inplaceAddNodeList` to handle this, and `inplaceDropNodeList` will restore after the newNodeList, and the `inplaceAddNodeList` will restore after `inplaceDropNodeList`.

fix(SBM): update same name index

---

server/activity_manager.go
server/issue.go

The current issue status change webhook will post the old issue in the event.
This PR changes to post the updated issue.
Also changed event message names to be consistent with the create issue event.

fix: webhook should post the updated issue

---

server/project.go

> / is a resource separator, which conveys timestamp is a child resource under workspaceid.
Ref: https://github.com/bytebase/bytebase/pull/2818#issuecomment-1278484456

chore: change delimiter of webhook endpoint ID

---

frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
frontend/src/views/DatabaseDetail.vue

P.S. we use the local timezone of the UI operator's system.
Close BYT-1652
Thanks for the suggestion from @dragonly

feat(frontend): add timezone to auto-generated default issue name

---

frontend/src/views/SettingWorkspaceDebugLog.vue

fix: cannot resolve component DebugLogsEmptyView

---

plugin/advisor/mysql/advisor_syntax.go
plugin/parser/utils.go
plugin/parser/utils_test.go
server/task_check_executor_statement_type.go

We now rely on TiDB's parser for parsing MySQL statements, but TiDB parser doesn't support **at least** the following statements:
1. `DELIMITER`
2. `CREATE FUNCTION`
3. `CREATE PROCEDURE`
4. `CREATE EVENT`
5. `CREATE TRIGGER`
So we need to extract these statements before sending input to TiDB parser. We match them by using regexp.
To simplify the regexp, we only match our MySQL dump format for the above SQLs like **CREATE DEFINER=\`root\`@\`%\` TRIGGER \`tri\` xxxxxx**.
Complete BYT-1663.
A part of #3080.

fix: cannot running CREATE TRIGGER/FUNCTION/PROCEDURE/EVENT in DDL issue

---

plugin/parser/differ/mysql/column_test.go
plugin/parser/differ/mysql/constraint_test.go
plugin/parser/differ/mysql/differ.go
plugin/parser/differ/mysql/differ_test.go
plugin/parser/differ/mysql/table_test.go
plugin/parser/differ/mysql/unsupport_object_test.go

mysqldump does not guarantee topological sorting.
Let's say we want to migrate from:
```sql
CREATE TABLE t1(id INT PRIMARY KEY);
```
to:
```sql
CREATE TABLE t1(id INT PRIMARY KEY, t2_id INT, CONSTRAINT FOREIGN KEY(t2_id) REFERENCES t2(id));
CREATE TABLE t2(id INT PRIMARY KEY);
```
Now we generate
```sql
ALTER TABLE t1 ADD COLUMN(t2_id INT);
ALTER TABLE t1 ADD CONSTRAINT FOREIGN KEY (t2_id) REFERENCES t2(id);
CREATE TABLE t2(id INT PRIMARY KEY);
```
We will encounter an error because there is no table t2.
We can use `SET FOREIGN_KEY_CHECKS=0;` to handle this problem like mysqldump does.

fix(sbm): disable foreign key check

---

frontend/src/types/sql-review-schema.yaml
plugin/advisor/sql_review.go

We will publish the PostgreSQL SQL review rule in the future.

fix: disallow SchemaRuleIndexKeyNumberLimit for PostgreSQL

---

plugin/parser/utils.go
plugin/parser/utils_test.go

After #3084, we allow users to run `CREATE TRIGGER/EVENT/PROCEDURE/FUNCTION` statement in Bytebase DDL issues. Also, we should allow users to run the corresponding `DROP` statement.

fix: running DROP TRIGGER/EVENT/PROCEDURE/FUNCTION in DDL issue

---

plugin/parser/differ/mysql/differ.go
plugin/parser/differ/mysql/differ_test.go

We introduce disabled foreign key check statement in #3091. We use `go-sql-driver` as our MySQL driver, and [it uses `go/sql`'s connection pool](https://github.com/go-sql-driver/mysql#connection-pool-and-timeouts). We should enable foreign key check after running diff SQLs.

fix: diable foreign key checks after diff SQL

---

server/activity_manager.go
store/activity.go
store/task.go

1. Introduced a batch activity creation function.
2. Removed the where clause for task_id, otherwise we may get transaction conflict.
2022-10-23 00:57:22.721 CST [53872] ERROR:  could not serialize access due to read/write dependencies among transactions
2022-10-23 00:57:22.721 CST [53872] DETAIL:  Reason code: Canceled on identification as a pivot, during write.
2022-10-23 00:57:22.721 CST [53872] HINT:  The transaction might succeed if retried.
2022-10-23 00:57:22.721 CST [53872] STATEMENT:  
UPDATE task
SET updater_id = $1, status = $2
WHERE id in (125) 
RETURNING id, creator_id, created_ts, updater_id, updated_ts, pipeline_id, stage_id, instance_id, database_id, name, status, type, payload, earliest_allowed_ts
2022-10-23T00:57:22.721+0800	ERROR	Failed to change task status.	{"id": …

chore: create activity in batch

---

resources/postgres/postgres.go

This fixes the warning for
could not open statistics file "pg_stat_tmp/global.stat": Operation not permitted

chore: set stats_temp_directory to tmp

---

plugin/db/mysql/mysql.go
plugin/db/mysql/mysql_test.go
plugin/parser/differ/mysql/differ.go
plugin/parser/utils.go
plugin/parser/utils_test.go

Now, the users cannot run DELIMITER commands in the DDL issue, which may cause some problems. For example, the users always use the below format to create the function via MySQL client:
```sql
DELIMITER ;;
CREATE FUNCTION xxx
END ;;
DELIMITER ;
```
But MySQL server side does not support `DELIMITER` command. We can easily replace the delimiter with the default delimiter ';', and then send to the go-sql-driver.
Completing BYT-1679:

feat: support running DELIMITER commands in DDL issue

---

frontend/src/components/InstanceEngineIcon.vue
frontend/src/components/ProvideSQLEditorContext.vue
frontend/src/composables/useExecuteSQL.ts
frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/sheet.ts
frontend/src/store/modules/sql.ts
frontend/src/store/modules/sqlEditor.ts
frontend/src/store/modules/tab.ts
frontend/src/types/sheet.ts
frontend/src/types/tab.ts
frontend/src/utils/sheet.ts
frontend/src/utils/tab.ts
frontend/src/views/sql-editor/EditorPanel/EditorAction.vue
frontend/src/views/sql-editor/EditorPanel/EditorPanel.vue
frontend/src/views/sql-editor/EditorPanel/TabModeSelect.vue
frontend/src/views/sql-editor/TabList/TabItem/TabItem.vue

**Execute query in admin mode** (early 🛴 edition) BYT-1708
- Using the query admin API (introduced by #3135)
- Available for DBAs and Workspace owners.
- Non-restricted SQL statement type. (Query, DDL, DML, and database management or whatever)
- Able to run multiple SQL statements in one execution. (e.g., `use database; show tables;`)
https://user-images.githubusercontent.com/2749742/197985552-a640c0c3-5068-4092-a8ce-2cca326872a3.mp4
- Inform users that this is an extremely dangerous zone.
- Interactive "Query-Result" loop user experience. (somehow like [Google Colaboratory](https://colab.research.google.com/) or [Jupyter Notebook](https://jupyter.org/try-jupyter/retro/notebooks/?path=notebooks/Intro.ipynb))

feat(sql-editor): Execute query in admin mode

---

plugin/parser/differ/mysql/column_test.go
plugin/parser/differ/mysql/constraint_test.go
plugin/parser/differ/mysql/differ.go
plugin/parser/differ/mysql/utils_test.go

The steps of the algorithm are simple, we iterate the new column slice, and each column will be one of the following cases:
1. New column, we always specify the column position in ALTER TABLE ADD COLUMN statement.
2. Exist column, leaving the column definition behind, we consider the column position. Let's say the column position in the old column slice and the new column slice are x and y. We should address the column order if there is a not null intersection in the oldColumns[:x] and the newColumns[y+1:] because the relative order of this column in the old column slice has changed.
This algorithm works well in most cases. But our differ follow the sequence of operations below:
1. Add new nodes.
2. Inplace update.
3. Inplace drop.
4. Inplace add.
5. Drop.
This leads to the problem that …

feat: support address column order

---

server/acl_casbin_policy_dba.csv
server/acl_casbin_policy_developer.csv
server/acl_casbin_policy_owner.csv
server/database.go

This will return the database schema in text format. This API is used for syncing database schema.

feat: add a database schema API

---

frontend/src/types/plan.ts
frontend/src/utils/role.ts
frontend/src/views/ProfileDashboard.vue

Similar to how we declare FEATURE_MATRIX, so that anyone can learn the role permission at a glance.
This PR adds the first entry. If we are happy with this approach. Will add other permissions in a followup PR.

refactor: introduce WORKSPACE_FEATURE_MATRIX

---

go.mod
go.sum
plugin/parser/edit/mysql/schema_test.go

I am a bot from renovate. 🤖️
Make [TiDB parser restore more pretty](https://github.com/bytebase/tidb/pull/2?notification_referrer_id=NT_kwDOBTppqrM0NzAzMDkyODEzOjg3NzE0MjE4#pullrequestreview-1159318269) to fix the double space case in #3154

chore(deps): update dependency @bytebase/tidb to latest

---

store/policy.go

We load the environment tier policy in GetEnvironment(), which is used almost everywhere. The value needs to be cached to improve the query latency. This is the first step of improving the database.list() latency.

chore: cache environment tier policy

---

server/project.go
server/task_executor.go
server/webhook.go

Users are relying on branch filters in GitOps. Let’s keep the support until we find a solution to write-back the latest schema file for baseline migration.

fix: support wildcard branch filter

---

frontend/src/components/Quickstart.vue
frontend/src/router/index.ts
frontend/src/views/DashboardHeader.vue
frontend/src/views/sql-editor/EditorHeader.vue

Now bb.feature.dba-workflow is only used to determine the QuickActionbar. In other places, use "bb.permission.workspace.manage-instance" permission check against the current user role

refactor: reduce the bb.feature.dba-workflow usage

---

frontend/src/router/index.ts
frontend/src/utils/role.ts

Whether a project developer can create or transfer database depends on whether the dba-workflow is enabled. And dba-workflow is only enabled in enterprise version.
This PR keeps the same logic, just make the code more manageable. A particular behavior does not depend on the plan, instead it depends on the feature gate for a plan. This makes change easier if we want to toggle feature gate for a plan.

refactor: extract create-or-transfer-database and change-database project permission

---

frontend/src/components/ProjectSettingPanel.vue
frontend/src/layouts/ProjectLayout.vue
frontend/src/utils/role.ts

Our backend always allows DBA and Owner to manage any project (we do have customers using the owner's access token to call our API to manage projects). But previously, we don't allow this from UI. So this PR makes the behavior consistent.
We didn't allow DBA and Owner to manage any project to prevent them changing the application developers' projects by accident. We can alternatively add a lock UI later to prevent this if this does cause a problem.

fix: allow workspace DBA and Owner to manage any project from UI

---

plugin/parser/engine/pg/deparse.go
plugin/parser/engine/pg/deparse_test.go
plugin/parser/parser.go

This PR changes the deparse format:
1. use lower case for data type, because data type is the identifier
2. for CREATE TABLE, we deparse it as
``` SQL
CREATE TABLE table_name (
column_one ...,
column_two ...
);
```

chore: modify the deparse format as pg_dump

---

frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
frontend/src/types/repository.ts
frontend/src/views/DatabaseDetail.vue

Update the placeholder replacements when opening VCS URL.
- {{TYPE}}
- `migrate` -> `ddl`
- `data` -> `dml`

chore: update vcs url

---

server/acl.go
server/acl_casbin_policy_dba.csv
server/acl_casbin_policy_developer.csv
server/acl_casbin_policy_owner.csv

e.g. If the role allows PATCH, then there is no need to specify a separate PATCH_SELF in the casbin config

refactor: simplify ACL logic to make XXX as a superset of XXX_SELF in casbin config

---

frontend/src/components/RepositoryForm.vue
frontend/src/components/RepositoryPanel.vue
frontend/src/components/RepositorySetupWizard.vue
frontend/src/types/repository.ts
server/project.go
server/task_executor.go
server/webhook.go

Have to continue the support for wildcard matching. The user could use two Bytebase projects (Prod and Dev) pointing into the same GitLab project. Dev needs to match branch "*/*" while Prod needs to match the exact branch "main". We need a wildcard to provide isolation between Dev and Prod projects.

chore: support wildcard branch still

---

api/setting.go
enterprise/api/license.go
server/acl_casbin_policy_dba.csv
server/acl_casbin_policy_owner.csv
server/instance.go
server/server.go
server/subscription.go

This is the backend part for support to start free trialing from the console.
We will use the setting table to store the license struct in JSON string format.

chore: support free trial from console (backend)

---

plugin/db/clickhouse/migrate.go
plugin/db/mysql/migrate.go
plugin/db/pg/migrate.go
plugin/db/snowflake/migrate.go
plugin/db/sqlite/migrate.go

The currently failing test cases (such as https://github.com/bytebase/bytebase/actions/runs/3367174445/jobs/5584411970#step:8:1700) are triggered when some of the migration histories have the same `created_ts`.
This PR uses the autoincremental ids to sort them, which is unique and has the same order as the created_ts.
Thanks to @RainbowDashy for reporting this issue.

fix: use id to sort migration history

---

plugin/parser/differ/pg/test-data/test_differ_data.yaml
plugin/parser/engine/pg/deparse.go
plugin/parser/engine/pg/test-data/test_alter_table_data.yaml
plugin/parser/engine/pg/test-data/test_create_schema_data.yaml
plugin/parser/engine/pg/test-data/test_create_table_data.yaml
plugin/parser/engine/pg/test-data/test_drop_schema_data.yaml

As discussion in #3209 , we need to write the `;` at the end of the deparse statement.

feat: write semicolon in PostgreSQL deparse procedure

---

plugin/db/mysql/rollback.go
plugin/db/mysql/rollback_test.go
resources/mysql/mysql.go
tests/rollback_test.go
tests/tests.go

This PR implements the function that generates the rollback SQL statements from a transaction parsed from the binlog events. This is a key part of the rollback task feature.
Close BYT-1718.

feat(flashback): get rollback SQL for a binlog transaction

---

plugin/db/mysql/mysql.go

This keeps the thread ID executing the migration unchanged. Thus it's easy to get the thread ID when we need to generate the rollback SQL.

chore: use a single connection to execute migration in the lifetime of a MySQL driver

---

server/acl.go
server/acl_test.go
server/project.go

This PR also tightens the ACL check, the existing logic does allow Developer 123 can fetch projects from Developer 124.
The plan is to centralize the project ACL logic for the workspace developer

refactor: move the GET /project ACL check to acl.go

---

frontend/src/components/ProjectSettingPanel.vue
frontend/src/utils/role.ts

From the backend API perspective bb.permission.project.archive-restore is not different from  bb.permission.project.manage-general, thus consolidate them.

chore: remove bb.permission.project.archive-restore, just use bb.permission.project.manage-general

---

.github/workflows/tests.yml

golangci-lint runs for ~3m. Parallelizing them can make the overall time reduced by ~3m.

chore: separate golangci-lint GHA

---

api/external_approval.go
store/external_approval.go

Paving the road for Feishu approval integration (2/n).
Previously, `external_approval` schema in https://github.com/bytebase/bytebase/pull/3160
This PR defines `ExternalApproval` API struct and implements storing.
Note that `ExternalApproval` only lives in the backend.

feat: external approval api & store

---

api/task.go
plugin/db/mysql/dump.go
server/task_executor.go

This is part of the MySQL DML task rollback feature.
Close BYT-1717.

feat(flashback): store binlog coordinates for MySQL DML task

---

frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json
frontend/src/views/DashboardHeader.vue

When users have trouble in Bytebase console use (FREE Plan only), click the button to open the page "https://www.bytebase.com/docs/faq#how-to-reach-us" to get contact information. For Chinese users, show the qrcode to let them join our wechat group.
https://user-images.githubusercontent.com/56376387/199670495-e9e5c083-2e66-4cb1-a8a7-e95e35902bf1.mp4

feat(frontend): display support information on console

---

frontend/src/views/sql-editor/EditorPanel/ExecuteHint.vue

Close BYT-1519
Our frontend SQL parser cannot handle SQL dialects perfectly. "Beautify"-ing may break the correctness of the SQL statement. 
So when creating a DDL/DML issue from the SQL Editor, we use the input SQL statement as-is without any modifiying.

fix(sql-editor): don't re-format SQL when creating DDL/DML issues

---

frontend/src/router/index.ts
frontend/src/utils/role.ts
frontend/src/views/DatabaseDetail.vue

"Create database" and "Transfer database" has different complexity. In particular, transfer database has more complex rules depending on the from/to project.
Thus separate them

refactor: seprate transfer and create database permission

---

api/plan.go
api/project_member.go
server/subscription.go

* The project permission will be used to gate the backend API
* Moving the feature gate to API module so that other modules can access it without bringing in the server module. This PR shows an example that ProjectPermission needs this. Also, this will help the permission unit tests later.

refactor: introduce project permission in backend and move feature gate from server module to API module

---

frontend/src/views/sql-editor/AsidePanel/TableSchema.vue

- When clicking the [Alter Schema] button on the table schema panel, open the VCS path in a new browser window if the project is VCS workflow.

feat(sql-editor): open VCS path in new window if needed

---

frontend/src/store/modules/sqlEditor.ts
frontend/src/views/sql-editor/AsidePanel/QueryHistoryContainer.vue

Close BYT-1540
- Clicking a query history item will open a new tab (instead of replacing the current one) with statement and connection info recovery, if possible
It's awkward that we stored instanceName and databaseName rather than IDs in the history activity entity.
We may try our best to find the correct database and instance by searching the name.

feat(sql-editor): open history item in new tab with connection info if possible

---

plugin/db/mysql/rollback.go
plugin/db/mysql/rollback_test.go
tests/rollback_test.go

There may be multiple tables in a transaction. We should parse the table name to match against the provided table map to get the column names.

refactor(flashback): parse table name

---

frontend/src/utils/pipeline.ts
server/task.go
tests/schema_update_test.go

- Transit task status to `PendingApproval` on EarliestAllowedTime & SQL statement modifications if the task status is `Pending`.
- Retry failed tasks will set the task status to `PendingApproval`.
Close BYT-1605
@LiuJi-Jim FYI

feat: dismiss stale reviews for Pending tasks & failed tasks retry as PendingApproval

---

bin/server/cmd/root.go

chore: fix dataDir format error when the `--data` arguments is `/`

---

plugin/db/mysql/restore.go
plugin/db/mysql/restore_test.go

This is needed in the generation process of rollback SQLs. We need to parse the start/end binlog file names.

refactor: parse binlog filename

---

api/issue.go
plugin/vcs/util.go
server/webhook.go
server/webhook_test.go
tests/schema_update_test.go
tests/tenant_test.go
tests/tests.go

This PR adds support for using YAML in place of DML files with a flexible database selection capability for tenant projects, as defined in the [RFC](https://docs.google.com/document/d/1toyY5tao8wsqmCJp9zB_lmRXSQHAgrtWsdTUpbQhdU0/edit#).
In other words, use the file extension `.yml` instead of `.sql` would do the switch automatically:
```diff
-{{DB_NAME}}##{{VERSION}}##{{TYPE}}.sql
+{{DB_NAME}}##{{VERSION}}##{{TYPE}}.yml
```
Based on the RFC, the database name in the file path is then ignored completely.
So far, only select databases by their names is implemented:
```yaml
databases:
- name: mydb
statement: |
INSERT INTO book (name) VALUES ('Star Wars')
```

feat(vcs): support YAML file in place of SQL for DML

---

plugin/vcs/internal/oauth/oauth.go

The function returned by `requester` could be called multiple times, which means that `body` would be read multiple times. However, `io.Reader` can only be read once. This would cause every subsequent read returns empty content.
So we first read everything from `io.Reader` and build the reader from the bytes to solve this problem.
Minimal reproduction:
- before https://go.dev/play/p/kzivKFuXVU2
- after https://go.dev/play/p/eoPN3LQZFKb

fix: io.Reader can only be read once

---

api/task.go
server/task_executor.go

1. Refactor task_executor to get the updated task. The latest task struct is needed for the later implementation of the rollback runner.
2. Add migration ID to the DML task payload. This is needed to parse the migration schema when generating the rollback SQL.

refactor(flashback): improve DML task payload

---

plugin/parser/ast/create_index_stmt.go
plugin/parser/ast/index_def.go
plugin/parser/ast/index_key_def.go
plugin/parser/engine/pg/convert.go
plugin/parser/engine/pg/convert_test.go
plugin/parser/engine/pg/deparse.go
plugin/parser/engine/pg/deparse_test.go
plugin/parser/engine/pg/test-data/test_create_index_data.yaml

This PR supports
```
CREATE [ UNIQUE ] INDEX [ [ IF NOT EXISTS ] name ] ON table_name [ USING method ]
( { column_name | ( expression ) } [ ASC | DESC ] [ NULLS { FIRST | LAST } ] [, ...] )
```
And for `method`, this PR only supports and tests for `btree` .

feat(parser): support CREATE INDEX statements

---

plugin/db/mysql/rollback.go
plugin/db/mysql/rollback_test.go

Before generating the rollback SQL for a DML task, we must parse the migration schema and get the table columns.

feat(flashback): get table columns from schema

---

api/activity.go
frontend/src/store/modules/sqlEditor.ts
frontend/src/types/activity.ts
server/server.go
server/sql.go
store/activity.go

InstanceID is unique than instance name. We will keep both database ID and name for getting the database object and readable name.

chore: backfill instance and database ID for SQL editor query activities

---

plugin/parser/ast/drop_constraint_stmt.go
plugin/parser/differ/pg/differ.go
plugin/parser/differ/pg/differ_test.go
plugin/parser/differ/pg/test-data/test_differ_constraint.yaml
plugin/parser/engine/pg/convert.go
plugin/parser/engine/pg/convert_test.go
plugin/parser/engine/pg/deparse.go
plugin/parser/engine/pg/test-data/test_alter_table_data.yaml

This PR support diff unique constraint in PostgreSQL, and the input must come from pg_dump.
We use the `CASCADE` keyword to drop some objects, such as tables and columns. And this leads to hard decisions about generating a `DROP CONSTRAINT` statement, so we always generate a `DROP CONSTRAINT` statement and set the `IF EXISTS` field.

feat: support sync unique constraint

---

api/sheet.go
frontend/src/store/modules/sheet.ts
frontend/src/types/sheet.ts
server/sheet.go
store/sheet.go
tests/schema_update_test.go
tests/sheet_vcs_test.go
tests/tests.go

We currently don't use them at all. These query parameters will complicate permission processing in our acl middleware. This is because we need to check whether the caller can access the sheets related to a particular databaseId/projectId for those endpoints.

refactor: remove databaseId/projectId query parameter when fetching my/shared/starred sheets

---

store/migration/dev/LATEST.sql
store/migration/prod/1.8/0001##drop_db_label_key_value_fkey.sql
store/migration/prod/LATEST.sql
store/pg_engine_test.go

We'd like to allow project owners to label databases without depending on labels defined at workspace level.

feat: remove the foreign key constraint for db_label to tabel label_value

---

api/project_member.go
server/acl.go
server/acl_project_test.go
server/acl_sheet_test.go
server/acl_test_helper.go

* Split the ACL test.
* Use more human-readable ACL error messages in the existing project ACL check as well as this new sheet ACL check.
There is one missing case to be added in the followup PR. To enforce developer can only create a sheet into the project where she has a membership. It's hard to do this in acl.go because this requires us to consume the request body stream and fetch the project id in the request, however, the request handler also needs to consume the request body. Thus we will do the check in the request handler.
It's a bit unfortunate that we can't centralize all ACL checks in one place though.

feat: enforce sheet ACL on the backend

---

server/acl.go
server/acl_project_test.go
server/acl_sheet_test.go

Also return the ACL error directly instead of in the internal error.
Followup of https://github.com/bytebase/bytebase/pull/3354

fix: handle unknown sheet for ACL check

---

server/issue.go
server/issue_test.go
tests/schema_update_test.go

In VCS, users could push multiple migrations for the same database. We should put task dependencies based on their schema version ID so that failures from prior task will block the execution for a latter task.

feat: add task dependencies based on schema version

---

plugin/parser/engine/pg/deparse.go
plugin/parser/engine/pg/test-data/test_alter_table_data.yaml

This PR supports to deparse `ALTER TABLE ADD CONSTRAINT constraint_name PRIMARY KEY` statement.
Completing BYT-1762.

feat: support to deparse alter table add primary key constraint

---

frontend/src/components/ProvideSQLEditorContext.vue
frontend/src/router/index.ts
frontend/src/store/modules/sheet.ts
frontend/src/store/modules/sqlEditor.ts
frontend/src/store/modules/tab.ts

Close BYT-1795
Now, if error occurs while opening a sheet or an unsaved tab, we will be redirected to the 404 page. Via this PR we can handle the errors more gracefully.
- If error occurs when opening a sheet (e.g., the sheet has been deleted somewhere else), fallback to an unsaved tab. The connection params and SQL statement of the sheet will be kept if possible.
- If error occurs when opening an unsaved tab (e.g., the database or instance has been transferred to an unaccessible project), fallback to disconnected state.

chore(sql-editor): gracefully fallback if error occurs while opening a sheet

---

server/project.go

This was introduced in https://github.com/bytebase/bytebase/commit/6a51ebb8eb6da7b28aecea31f22f9e511f42b635#diff-0c812e31ab390c0fee9f18e8423f33c1f9fa59e3a54742a9470275604723fcf8L107-L112

fix: should not break when iterating the project list to find a user's projects

---

frontend/src/components/ProjectCreate.vue
frontend/src/components/ProjectDeploymentConfigPanel.vue
frontend/src/store/modules/deployment.ts
frontend/src/utils/deployment.ts
server/project.go
store/deploy.go
store/environment.go

This is the first attempt to unify the issue creation for tenant and non-tenant mode projects. Both should rely on deployment configuration to produce the pipeline/stage/tasks.

chore: move default deployment configuration generation to backend

---

plugin/app/feishu/feishu.go
server/setting.go

Clear cache on update so that we won't use the previous token when we try to create new approval definition.

fix: clear token cache on patch

---

plugin/vcs/github/github.go
plugin/vcs/gitlab/gitlab.go
plugin/vcs/vcs.go
server/webhook.go
tests/fake/github.go
tests/fake/gitlab.go
tests/fake/provider.go
tests/schema_update_test.go

The VCS provider (GitLab/GitHub) sends a push event webhook containing commits of the PR/MR when merged. Bytebase will use the commits in the push event to generate issue(s). However, users can merge other branches in the PR/MR, which contains files that are already merged into the main branch.
In the current implementation, Bytebase will generate additional tasks for the merged-in files even if they already exist when the PR/MR is merged.
This PR introduces the commits diff as a filter. We first get the diff before and after the PR/MR is merged, and filter out files that are not in the diff. This prevents the issue described above.
Fix BYT-1785.

feat(vcs): filter commits in push event webhook by commits diff

---

api/setting.go
server/application_runner.go
server/issue.go
server/setting.go

Force close old external approval.
It didn't work because we do `cancelOldExternalApprovalIfNeeded` before updating the issue status to canceled.

fix: force close external approval

---

server/issue.go

Cancel external approval after patching the issue, otherwise, we will have a short period of time when the external approval is canceled, but the issue status is still open, which leads to `ScheduleApproval` sending a new external approval.

fix: cancel external approval on cancellation timing

---

server/task_check_scheduler.go
store/task.go

Only schedule LGTM checks if the environment approval policy is `MANUAL_APPROVAL_ALWAYS`.
Close BYT-1833

fix: lgtm check if manual approval

---

store/migration/dev/20221115000000##task_rollback.sql
store/migration/dev/LATEST.sql

This is a strong reference between the two tasks to indicate the rollback relationship.
For example, if task1.id=1, task2.id=2, task2.rollback_from=1, then task2 is the generated rollback task for task1.
A NULL rollback_from field means the task is not a generated rollback task of any other task.
Multiple tasks may be generated with the same rollback_from value. We should check this before executing the task. If there's one successful task with the same rollback_from value, we should fail the current one.

feat(schema): add rollback_by column to table task

---

plugin/vcs/github/github_test.go
plugin/vcs/gitlab/gitlab_test.go

Reduce boilerplate and indentations by extracting a `newMockProvider` helper function.

refactor(test): reduce boilerplate

---

server/task.go

Treat every principal/member as an owner if RBAC is not enabled.
Close BYT-1818

fix: principal role

---

api/project_test.go
plugin/db/driver_test.go
plugin/db/mysql/binlog_stream_parser_test.go
plugin/db/mysql/rollback_test.go
tests/schema_update_test.go
tests/sheet_vcs_test.go
tests/tenant_test.go

It should have been detected by https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#range-val-in-closure. I have no idea why.
The current implementation only runs the last test case in paralleled subtests.

fix: parallel test must not use the loop var in the closure

---

frontend/src/components/DatabaseTable.vue
frontend/src/views/DashboardSidebar.vue
frontend/src/views/DatabaseDetail.vue
frontend/src/views/TableDetail.vue

To promote usage as SQL Editor has become more mature. Solid icon is more obvious.
Also reposition the terminal icon before the database name to align properly.
Fix BYT-1839

feat: use solid terminal icon for SQL Editor

---

tests/backup_restore_test.go
tests/data_source_test.go
tests/external_pg_test.go
tests/ghost_test.go
tests/project_test.go
tests/schema_update_test.go
tests/sheet_vcs_test.go
tests/sql_review_test.go
tests/start_test.go
tests/tenant_test.go
tests/tests.go

We don't need to start a fake VCS server for every test.
We would do something like 
```go
if vcsProviderCreator != nil {
ctl.vcsProvider = vcsProviderCreator(vcsPort)
ctl.vcsURL = fmt.Sprintf("http://localhost:%d", vcsPort)
}
```
First, we compose everything into a config because we'll have more parameters in the future (more fake providers).

refactor: move test controller parameter to a configuration

---

tests/backup_restore_test.go
tests/data_source_test.go
tests/external_pg_test.go
tests/ghost_test.go
tests/mysql_test.go
tests/project_test.go
tests/rollback_test.go
tests/schema_update_test.go
tests/sheet_vcs_test.go
tests/sql_review_test.go
tests/start_test.go
tests/tenant_test.go
tests/tests.go

Even with t.Parallel(), the tests are running inside the same process so that we can use a shared integer to allocate the port.

refactor: improve test port allocation

---

tests/fake/github.go
tests/fake/gitlab.go
tests/fake/provider.go
tests/schema_update_test.go

Previously, we create branches inside `getRepositoryBranch` method of fake VCS providers. This means that when we want to get a branch, we first create it. But we shouldn't allow users to bind vcs settings on a branch that doesn't exist. And the previous test methodology will never reveal this bug.
So in this PR, I created a standalone `CreateBranch` method. When writing tests, we should explicitly create a branch after creating a fake repo. Otherwise, if we try to bind vcs settings on a branch that doesn't exist, the test should detect that.

test(vcs): add a standalone method to create branches in repos

---

api/plan.go
api/policy.go
server/policy.go
store/policy.go

Sensitive data policy is only supported at database level.
curl 'http://localhost:3000/api/policy/database/103?type=bb.policy.sensitive-data' \
-X 'PATCH' \
--data-raw '{"data":{"type":"policyUpsert","attributes":{"payload":"{\"sensitiveDataList\":[{\"table\":\"hello\",\"column\":\"world\",\"type\":\"WILDCARD\"}]}"}}}' \
--compressed

feat: introduce sensitive data policy

---

api/policy.go

Still keep WILDCARD for the enum name instead of default. I'd like to avoid having default value, and the mask type is required.

chore: use mask in the name

---

bin/server/cmd/root.go
server/config.go
server/server.go

Benefits:
1. Give the user a clean failure log. Previously, a bunch of runners have already started and emitted logs
2. Reduce side effects. We want to avoid that we start Bytebase, does the possible schema migration, and then find we are unable to start server.

chore: precheck server port availability

---

plugin/parser/ast/create_sequence_stmt.go
plugin/parser/ast/sequence_def.go
plugin/parser/engine/pg/convert.go
plugin/parser/engine/pg/convert_test.go

To support PostgreSQL sync schema, we should convert the `pg_query_go` create sequence statement to our create sequence statement.

feat: support convert create sequence statement

---

go.mod
go.sum
plugin/parser/ast/unconverted_data_type.go
plugin/parser/differ/pg/test-data/test_differ_data.yaml
plugin/parser/engine/pg/convert.go
plugin/parser/engine/pg/convert_test.go
plugin/parser/engine/pg/deparse.go

related PR https://github.com/bytebase/pg_query_go/pull/3
We do not convert all data type.
Here we use the result from the `pg_query_go deparser` instead of converting all data type for differ.

chore(parser): set text deparsed by pg_query_go to unconverted data type

---

frontend/src/components/Issue/IssueHighlightPanel.vue
frontend/src/components/Issue/IssueRollbackButton.vue
frontend/src/components/Issue/IssueRollbackFromTips.vue
frontend/src/components/Issue/IssueTaskStatementPanel.vue
frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/issue.ts
frontend/src/types/issue.ts
frontend/src/types/pipeline/task.ts
frontend/src/utils/link.ts
frontend/src/utils/task.ts

**Condition**
- Issue type and task type are DML
- [and] Task status is "DONE"
- [and] Project workflow type is "UI"
- [and] Database engine type is "MYSQL"
**Who can click the [Rollback] button?**
- The issue creator
- [or] The issue assignee
- [or] Project owners
- [or] DBAs and workspace owners
**The [Rollback] button**
**The generated rollback issue**
**Screen recording**
https://user-images.githubusercontent.com/2749742/203516799-02a9350f-c501-4521-bf76-7ab302abb825.mp4

feat(frontend): Generate rollback issue for a DML task

---

plugin/parser/ast/drop_sequence_stmt.go
plugin/parser/engine/pg/convert.go
plugin/parser/engine/pg/convert_test.go

We should drop the redundant sequence in PostgreSQL sync schema. This PR is the preparation work to allow us to restore our bb drop sequence AST.

feat: convert drop sequence and deparse PostgreSQL drop sequence statement

---

api/principal.go
store/principal.go

Support modifying principal email.
Because when using feishu approval integration, we require users to have the same email both on Bytebase and feishu side. Users may want to change their emails in Bytebase.
Completing BYT-1870

feat: support modifying user email (backend)

---

server/application_runner.go
server/issue.go

Force cancel external approval for non-open issues.
Though we have force-closed external approvals when closing/resolving an issue, we still double-check here.

fix: force cancel external approval

---

plugin/app/feishu/feishu.go
plugin/app/feishu/feishu_test.go
server/setting.go
tests/fake/feishu.go

We require to enable bot on the feishu, which represents bytebase system bot.
We can get rid of "default email" this way #3509 
Close BYT-1887

feat: implement feishu bot api callers

---

server/sql.go

We may get stale data for reading from read replica instance.

fix: use admin driver for sync schema

---

api/database.go
plugin/parser/edit/mysql/edit.go
plugin/parser/edit/mysql/edit_test.go

We should use `CHANGE COLUMN` to allow renaming column instead of `MODIFY COLUMN`.

feat: use `CHANGE COLUMN` instead `MODIFY`

---

frontend/src/components/Issue/IssueActivityPanel.vue
frontend/src/components/Issue/IssueRollbackButton.vue
frontend/src/components/Issue/activity/Comment.ts

- Automatically comment on the issue with the newly created rollback issue id.
- Recognize "#{issue_id}" patterns in comment activities and render them as a link to the issue.

feat(frontend): generate a comment when rollbacking a task

---

api/policy.go

Access control policy includes a list of disallow rules. We only support the disallow rule that turns off access for the full database. In the future, we can add table, column, expiration time to the rule.
To disable the access for the whole environment, we should add policy with
```
inheritFromParent: true (default)
disallowRuleList: {
{
FullDatabase: true,
},
}
```
To allow access for certain databases under an environment, we should add policy at database level with
```
inheritFromParent: false
disallowRuleList: {
}
```

feat: define access control policy

---

server/application_runner.go

We should continue if we fail to approve the stage; otherwise, we will send another approval because we archived the old external approval.
Completing BYT-1890

fix: application runner, continue on failing to approve stage

---

frontend/src/views/sql-editor/EditorCommon/ConnectionPathBar.vue

BYT-1898
- Put the connection info closer to the database tree. This also makes it looks more like VSCode.
- Update the delimiter's style.
**Before**
**After**

feat(sql-editor): improve connection info indicator

---

plugin/parser/differ/pg/differ.go
plugin/parser/differ/pg/test-data/test_differ_data.yaml
plugin/parser/differ/pg/test-data/test_differ_schema.yaml

also, I remove the default for unsupported statement here. The reason is pg_dump returns SET statement but our parser does not support it. I'll add it back later.

chore(differ): remove IF EXISTS and CASCADE for drop objects

---

plugin/parser/differ/pg/differ.go
plugin/parser/differ/pg/differ_test.go
plugin/parser/differ/pg/test-data/test_differ_data.yaml
plugin/parser/differ/pg/test-data/test_differ_merge.yaml

We execute the following statement in PostgreSQL:
```sql
CRAETE TABLE tbl(id serial);
```
and pg_dump give us:
```SQL
CREATE TABLE public.tbl(
id integer NOT NULL
);
CREATE SEQUENCE public.tbl_id_seq
AS integer
START WITH 1
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
CACHE 1;
ALTER SEQUENCE public.tbl_id_seq OWNED BY public.tbl.id;
ALTER TABLE ONLY public.tbl ALTER COLUMN id SET DEFAULT nextval('public.tbl_id_seq'::regclass);
```
And now we generate diff table result when we found a `CRAETE TABLE` statement in new statements.
So we need to merge the `ALTER TABLE ONLY public.tbl ALTER COLUMN id SET DEFAULT nextval('public.tbl_id_seq'::regclass);` into `CREATE TABLE` statement. 
This also lays the groundwork for SBM, if SBM supports such syntax.

feat: support merge PostgreSQL ALTER TABLE SET DEFAULT statement

---

frontend/src/components/CreateInstanceForm.vue
frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json

Closing BYT-1889
- Show a "connecting..." indicator while we test the connection.
- Disable related buttons while testing the connection.

feat(frontend): prevent repeat clicking while creating instances

---

go.mod
go.sum
plugin/db/pg/pg.go
tests/sql_review_test.go

* Address the SSL error when connecting to pg instance from render.com  (FATAL: SSL/TLS required (SQLSTATE 28000)), this is likely pgx didn't handle ssl mode properly in the previous version. I am not able to locate the exact pgx fix, the closest one is https://github.com/jackc/pgx/issues/282. However, this fix should already be in the v4 version.
* Make the 1st DNS guess as the username, pg server from render requires an explicit database name.
* Accordingly, return error if user is not specified in the connection string.

feat: upgrade pgx v4 to v5 to fix ssl issue

---

server/server.go

This is the start of the series of refactoring I am going to do.
I noticed we introduced some engine-specific fields to the driver interface. This is something we really need to avoid. I will try to refactor this piece this time, but in the future, we shouldn't allow this to happen in the first place.
**THIS IS NOT THE CODE QUALITY WE LIVE UP TO**
https://sourcegraph.com/github.com/bytebase/bytebase/-/blob/plugin/db/driver.go?L160&subtree=true
Looking at the above image, we already have a bad smell to pass "" to pgInstanceDir.

chore: only log embedded pg info if embedded is used.

---

api/task.go
server/database.go
server/issue.go
server/task.go
server/task_executor_database_create.go
tests/tests.go

Previously, we allow users to edit the schema in create database issue if there is any error. However, the schema in the create database issue may be stale while creating the database.

chore: move create tenant database schema generation from task creation to task execution

---

plugin/parser/differ/pg/differ.go
plugin/parser/differ/pg/differ_test.go
plugin/parser/differ/pg/test-data/test_differ_sequence.yaml
plugin/parser/engine/pg/deparse.go
plugin/parser/engine/pg/deparse_test.go
plugin/parser/engine/pg/test-data/test_drop_sequence_data.yaml

There are some notes for reviewing this PR:
1. `pg_dump` will separate the OWNED BY clause into a ALTER SEQUENCE statement to avoid dependency conflicts. We need to consider this cases.
2. The same as `pg_dump`, we separate the OWNED BY to avoid dependency conflicts. More details:
- We need to print SQL as `ALTER SEQUENCE OWNED BY NONE` -> `DROP SEQUENCE` -> `DROP TABLE/COLUMN`. The 
reason is that PostgreSQL will automatically drop the sequence s1 when dropping the column t1.c1 if sequence s1 is 
owned by column t1.c1.
- We need to print SQL as `CREATE SEQUENCE` -> `CREATE TABLE/COLUMN` -> `ALTER SEQUENCE OWNED BY`. The `CREATE TABLE/COLUMN` depends on the sequence because we can set `DEFAULT nextval('sequence_s1'::regclass)`
- https://www.postgresql.org/docs/15/sql-createsequence.html
> …

feat(differ): support to sync PostgreSQL sequence

---

server/anomaly_scanner.go
server/backup_runner.go
server/database.go
server/instance.go
server/issue.go
server/openapi_sql.go
server/rollback_runner.go
server/server.go
server/sql.go
server/task_check_executor_database_connect.go
server/task_check_executor_migration_schema.go
server/task_check_executor_pitr_mysql.go
server/task_check_executor_statement_advisor_composite.go
server/task_executor.go
server/task_executor_database_backup.go
server/task_executor_database_create.go
server/task_executor_pitr_cutover.go
server/task_executor_pitr_restore.go
server/task_executor_schema_update_ghost_cutover.go
server/task_executor_schema_update_sdl.go
server/webhook.go

* Fix getAdminDatabaseDriver
* Add the driver config for tryGetReadOnlyDatabaseDriver
Followup https://github.com/bytebase/bytebase/pull/3541

fix: populate correct binDir according to the instance engine type

---

server/issue.go
store/deploy.go

The function getTenantDatabaseMatrix() will no longer be a shared function (right now two references) as a follow-up change. We will only rely on getDatabaseMatrixFromDeploymentSchedule().

refactor: deployment configuration refactoring to consolidate pipeline generation

---

bin/bb/cmd/utils.go
resources/mysql/mysql.go
resources/postgres/postgres.go
server/database.go
server/instance.go
server/server.go
store/metadb.go
store/pg_engine_test.go
tests/backup_restore_test.go
tests/external_pg_test.go
tests/ghost_test.go
tests/mysql_test.go
tests/rollback_test.go
tests/schema_update_test.go
tests/sensitive_data_test.go
tests/sql_review_test.go

To decouple the pg utility binaries usage from the postgres server used in embed mode. In both embed and external mode, the pg utility binaries are always needed, so we always install them (because we bundle postgres and utility binaries together , thus in such case, we would still install the unneeded postgres binary, this is a minor issue that we can stay with for now).
While pgDataDir and initdb are only needed in embed mode.
----
This completes the refactor around how we pass around db specific binaries
https://github.com/bytebase/bytebase/pull/3539
https://github.com/bytebase/bytebase/pull/3541
https://github.com/bytebase/bytebase/pull/3543
https://github.com/bytebase/bytebase/pull/3544

refactor: remove pgInstance to split the code path between embed and external pg mode

---

plugin/parser/differ/pg/differ.go
plugin/parser/differ/pg/differ_test.go
plugin/parser/differ/pg/test-data/test_differ_data.yaml
plugin/parser/differ/pg/test-data/test_differ_sequence.yaml

This PR fix two bugs:
1. The PostgreSQL differ needs to drop objects as the safe order, so that we cannot skip dropping index `schema_a.index_a` if `schema_a` need to be dropped. We should drop the `index_a` firstly and then drop the `schema_a`;
2. The correct order to drop sequences is that:
drop sequence owned by -> drop table/column -> drop sequence
The reason is that some columns may depend on sequences by DEFAULT clause. And after `dropping sequence owned by`, dropping a table/column does not drop dependent sequences. This is as expected.
related issues #3542

chore(differ): fix bugs for dropping statements in differ

---

store/migration/dev/20221128000000##database_in_instance.sql
store/migration/dev/LATEST.sql

We currently guess the connecting database name following the order: username, bytebase, postgres, template1.
The instance might not have any of those databases (e.g. Render), so we need to give the user an explicit way to specify the database name.

feat: add database name field to instance table

---

api/principal.go
server/jwt.go
server/principal.go

* Explain PrincipalType difference
* Change "BOT" to "SYSTEM_BOT" to match the underlying schema
* Extract access key prefix

chore: annotate PrincipalType

---

resources/postgres/postgres.go
server/instance.go
server/server.go
store/metadb.go
store/pg_engine_test.go
tests/external_pg_test.go

Keep stderr and suppress stdout.
The underlying PG message is not useful.

chore: suppress PG stdout message

---

frontend/src/components/DatabaseListSidePanel.vue
frontend/src/components/DeploymentConfigTool/DeploymentMatrix.vue

- Hide "(1)" in the sidebar's database list when there's only one database in a group.
- Put all databases into one group if we are using wildcard dbNameTemplate while previewing the deployment config.

feat(frontend): tenant ui improvement

---

frontend/src/views/sql-editor/TerminalPanel/CompactSQLEditor.vue

When
- the SQL ends with ";"
- [and] the cursor is at the end of the editor
- then press "Enter"
We trigger the "execute" event
Close BYT-1928

feat(web-terminal): trigger run when pressing Enter key

---

resources/mysql/mysql.go
tests/mysql_test.go

1. It cannot be in the data directory.
2. We want to share resource/binary directory across all tests.
Thus, we need a separate directory for my.cnf.

refactor: move my.cnf to a separate directory

---

api/activity.go
api/external_approval.go
frontend/src/components/Issue/activity/ActionSentence.vue
frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json
frontend/src/types/activity.ts
frontend/src/types/externalApproval.ts
frontend/src/types/index.ts
server/application_runner.go
server/issue.go
server/server.go
store/external_approval.go

retry #3531 
Reusing exsiting activity type "bb.issue.comment.create".
We create the activity if the feishu approval is rejected.
The newly-added field `rejected` is necessary for us to tell if it's the first time we encounter this so that we would not create the activity multiple times.
Completing BYT-1831
The comment can be modified since we are using "bb.issue.comment".

feat: create activity on external approval rejected

---

frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json
frontend/src/views/auth/Signin.vue

fix(frontend): wrong login wording with GitHub provider configured

---

store/pg_engine.go

I think there are 2 ways to deal with migration history
* Option 1, if the latest migration is DONE, we immediately fail the migration and require human inspection.
* Option 2, find the most recent DONE migration.
Our existing logic adopts option 2. Then if there is no DONE migration in the migration history, we should treat it the same as no migration happened instead of returning an error.
---
I encountered this when deploying render probably because there is multiple Bytebase render services accessing the same database.

feat: do not return error if we don’t find DONE migration history

---

server/application_runner.go
tests/fake/feishu.go

Feishu API requires the `user_id` in [cancelExternalApproval](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/approval-v4/instance/cancel) request equals the `open_id` in [createExternalApproval](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/approval-v4/instance/create). (which is not explicitly expressed in their docs tho)
Bug introduced in #3512

fix: feishu cancel approval user id

---

server/application_runner.go

Try to update the approval definition if external approval is enabled, because our approval definition may have changed.

fix: try update approval definition on application runner start

---

frontend/src/components/SyncDatabaseSchemaPrepForm.vue

We should only list migration history with `BASELINE`/`MIGRATE`/`BRANCH` type.

fix: filter migration history list

---

common/util.go
common/util_test.go
plugin/app/feishu/feishu.go
plugin/app/feishu/feishu_test.go
plugin/webhook/webhook.go
plugin/webhook/webhook_test.go
server/application_runner.go
server/task.go

Close BYT-1864
Improve feishu approval card information by sending the SQLs of tasks.
We can't send the SQLs as is because if SQLs get too long, it's impossible to view them on Feishu.
Our strategies are
- For tasks having identical statements, merge them into one task group.
-  Send the SQL of at most five task groups.
- For each task group, truncate the SQL to fit within the limit of 450 characters.
The SQL in the feishu approval card might get stale because we won't recall & resend on modifying SQL on Bytebase for now. This problem is to be solved together with https://github.com/bytebase/bytebase/issues/3558 in the follow-ups of #3640.
```
=========================
The SQL statement of every task
=========================
-- 用来测试 SQL Editor 的 SQL
-- 3309 / ggg
select
id, …
```

fix: improve feishu approval card info

---

frontend/src/components/DatabaseBackupPanel.vue
frontend/src/utils/database.ts
frontend/src/views/DatabaseDetail.vue

On the database detail page, the buttons below will be hidden
- Transfer Database
- Establish baseline
- Enable auto backup
- Edit auto backup (when enabled)
- Restore to point in time
- Backup Now
- Restore (in the backup list)
Close BYT-1970

feat(frontend): disable transfer db, establish baseline and backup/restore features for archived database

---

plugin/app/feishu/feishu.go
plugin/app/feishu/feishu_test.go
server/application_runner.go
tests/external_approval_test.go

Close BYT-1955
Use the application as the bot if the assignee cannot be found.
Also need to modify the user doc later.

feat: requester fallback to bot if creator not found

---

plugin/db/mysql/mysql.go
plugin/db/pg/pg.go
plugin/db/util/driverutil.go
tests/sql_editor_test.go
tests/tests.go

This feature is only suitable for MySQL/PostgreSQL family.
If the user submits only one SQL via SQL Editor, and the statement type is UPDATE/DELETE/INSERT, the backend will return the affected rows. 
~~In that case, the `data` field in `SQLResultSet` will only contain one number.~~
FYI @LiuJi-Jim

feat(sql-editor): return effected rows if sql editor submit a single SQL and the type is UPDATE/DELETE/INSERT

---

frontend/src/components/Issue/IssueActivityPanel.vue
frontend/src/components/misc/HumanizeTs.vue

We still use the `humanizeTs` as the default display to keep it clear and consistent, but add a tooltip to show the exact time while hovering.
The `<HumanizeTs>` is also useful everywhere in the future.

feat(frontend): show exact time in issue activity

---

server/task_scheduler.go

`passCheck` is called per check per task per second, which may output lots of lines, while this log is not very useful.

chore: remove spamming log

---

api/issue.go
server/application_runner.go
server/issue.go
server/task.go
server/task_scheduler.go
server/webhook.go
store/issue.go
tests/external_approval_test.go
tests/tests.go

Prev #3676 
Completing #3558 
This PR implements `assignee_need_attention` related logic and couples external approval with it.
`assignee_need_attention` represents that the issue should be checked out by the assignee.
The life of an external approval is no longer than the corresponding `assignee_need_attention`.
The application runner in `application_runner.go` periodically scans open issues whose assignee needs attention and tries to 1. cancel stale external approvals and 2. send external approvals.
For GitOps workflow, the `assignee_need_attention` is always true to keep our previous behavior which is auto-sending external approvals.
For UI workflow, the `assignee_need_attention` is set to true by users clicking a button on the frontend. For now, we only allow setting …

feat(backend): manually trigger external approval with assignee need attention

---

store/migration/dev/20221206000000##db_schema.sql
store/migration/dev/LATEST.sql

This is the first step of denormalizing other database metadata tables.

feat: introduce db_schema table for storing database schema metadata and dump

---

server/component/dbfactory/dbfactory.go
server/instance.go

Postgres has strong isolation for databases and required database connection parameter. Right now, we are guessing the database parameter in guessDSN, but we should allow users to specify one without guessing because guesses could be incorrect.

feat: only allow setting database connection parameter for Postgres

---

README.md

It's covered by GitHub action and external contributions don't always follow this step.

docs: remove pre-commit step

---

plugin/db/util/driverutil_test.go
plugin/db/util/mask_sensitive_data.go

> Partition, subpartition, column, index, stored routine, event, and resource group names are not case-sensitive on any platform, nor are column aliases.
https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html

fix: use case-insensitive column name

---

frontend/src/components/ProvideSQLEditorContext.vue
frontend/src/utils/policy.ts
frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue
frontend/src/views/sql-editor/SQLEditorPage.vue

Close BYT-2042
- Disallow to set a connection to protected instances
- The node is still expandable since some children might be accessible.

fix(sql-editor): disallow to set connection to protected instances

---

store/migration/dev/20221209000000##mongo_instance_type.sql
store/migration/dev/LATEST.sql

This PR makes MONGODB a valid engine type in Bytebase's instance table.
We did not declare a name for the check constraint at first, so the drop constraint statement may not work.

feat: migrate instance schema to make mongodb valid

---

frontend/src/components/TransferDatabaseForm.vue
frontend/src/components/TransferDatabaseForm/TransferSourceSelector.vue
frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json
frontend/src/utils/database.ts

Close BYT-1973, BYT-1972
- Transferring databases into the default project now supports filtering.
- Filtering databases while transferring databases now also supports project, instance, and environment names.

feat(frontend): database transferring improvement

---

frontend/src/components/CreateDataSourceExample.vue
frontend/src/components/CreateInstanceForm.vue
frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json
frontend/src/types/instance.ts

We should show the correct instance type in the hint message when user click the copy button of the connection info block.

fix: show correct instance type

---

frontend/src/components/ProjectDatabasesPanel.vue
frontend/src/components/ProjectDeploymentConfigPanel.vue
frontend/src/components/ProjectOverviewPanel.vue
frontend/src/layouts/ProjectLayout.vue
frontend/src/views/ProjectDetail.vue

Close BYT-1892
- Remove databases on the tab "Overview"
- Add a new tab "Databases" after "Overview"
- Standard projects: list all databases on the tab "Databases", and support searching by database name, env name
- Tenant projects: rename the tab "Deployment config" as "Databases", and move the database info from the bottom to the top
- 
-
-

feat(frontend): put database list into an independent tab in project detail page

---

frontend/src/components/Issue/PipelineGhostFlow.vue
frontend/src/components/Issue/PipelinePITRFlow.vue
frontend/src/components/Issue/PipelineSimpleFlow.vue
frontend/src/components/Issue/PipelineTenantFlow.vue
frontend/src/router/index.ts

We optimized the API calls. We use `databases.list(project_id)` instead of `databases.get()` many times. And removed some unnecessary API calls.

fix(frontend): improve issue preview load latency

---

plugin/parser/ast/add_enum_label_stmt.go
plugin/parser/ast/alter_type_stmt.go
plugin/parser/differ/pg/differ.go
plugin/parser/differ/pg/test-data/test_differ_data.yaml
plugin/parser/engine/pg/convert.go
plugin/parser/engine/pg/convert_test.go
plugin/parser/engine/pg/deparse.go
plugin/parser/engine/pg/test-data/test_type_data.yaml

We cannot remove labels from enum types, but we can add enum labels.
In most changing schema scenarios, we always add enum labels, so this PR add this feature for enum labels.
close BYT-2037

feat(differ): support to add enum labels if possible

---

frontend/src/components/UIEditor/Panels/TableEditor.vue
frontend/src/store/modules/UIEditor.ts
frontend/src/types/UIEditor.ts
frontend/src/utils/UIEditor/diffColumn.test.ts
frontend/src/utils/UIEditor/diffColumn.ts
frontend/src/utils/UIEditor/diffTable.test.ts
frontend/src/utils/UIEditor/diffTable.ts
frontend/src/utils/UIEditor/transform.ts

`TableOrColumnStatus` is a status field for table/column in UI Editor. It now has three values.
* `normal` means that the object(table/column) is in a non-special status;
* `created` means that the object is newly created;
* `dropped` means that the object was deleted;

refactor: add `normal` to `TableOrColumnStatus`

---

store/environment.go
store/policy.go

* fix: nil pointer and cache
* chore: should not compose env if the resource type is not env
Co-authored-by: d-bytebase <d@bytebase.com>

fix: nil pointer and the cache for policy (#3810)

---

frontend/src/components/CreateDatabasePrepForm.vue
frontend/src/components/DatabaseDetail/CreatePITRDatabaseForm.vue
frontend/src/components/DeploymentConfigTool/SelectorItem.vue
frontend/src/components/Issue/IssueSidebar.vue
frontend/src/components/TenantDatabaseTable/DatabaseMatrixItem.vue
frontend/src/components/TransferDatabaseForm/SelectDatabaseLabel.vue
frontend/src/utils/label.ts

Close BYT-2089, BYT-2079
- Remove (hide) `location` labels.
- Won't show `Tenent` input while creating databases in non-tenant projects.
-
-
-
- If we meet "location" condition in legacy deployment config, it will still be displayed but not selectable any more.
-

feat(frontend): hide location label

---

api/activity.go
server/activity.go
server/runner/taskcheck/lgtm_executor.go
store/activity.go

Make it possible to get activities with a range of typePrefixes. 
Now with a request to `/api/activity?typePrefix=bb.member&typePrefix=bb.project`, we'll get activities that are either of the `bb.member` type or of the `bb.project` type. 
While it is still compatible with cases like `/api/activity?typePrefix=bb.member` for activities only of the single `bb.member` type.
This change is to pave the road for audit logs so that we can request multiple determined types of activities at one time.

feat: support finding activities with multiple typePrefixes

---

server/openapi_instance.go
store/instance.go

- fix missing override for data source
- rename the instance for archive (to avoid the duplicate name)

fix: missing override for data source

---

frontend/src/components/ProvideSQLEditorContext.vue
frontend/src/views/EnvironmentDashboard.vue
frontend/src/views/EnvironmentDetail.vue
frontend/src/views/sql-editor/SQLEditorPage.vue

Close BYT-2073
- UPSERT environment-level access-control policy when changing an environment's tier. (@rebelice PTAL)
- Hide inaccessible databases and instances in the SQL Editor's database tree.

feat(access-control): handle protected instance's access control policy properly

---

store/migration/dev/20221214000000##add_idx_db_project_id.sql
store/migration/dev/LATEST.sql

Add index on db(project_id) as finding databases by project_id is frequent.

chore: add idx on project_id for table db

---

api/issue.go
server/issue.go
server/webhook.go
tests/tenant_test.go

This is no longer needed as we have change to use empty database name and empty database ID for tenant mode migration regardless of the database name template value.

chore: deprecate database name from migration context

---

frontend/src/bbkit/BBDialog.vue
frontend/src/components/AuditLog/AuditLogEmptyView.vue
frontend/src/components/AuditLog/AuditLogTable.vue
frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json
frontend/src/router/index.ts
frontend/src/store/modules/auditLog.ts
frontend/src/store/modules/index.ts
frontend/src/types/auditLog.ts
frontend/src/types/index.ts
frontend/src/types/store.ts
frontend/src/utils/role.ts
frontend/src/views/SettingSidebar.vue
frontend/src/views/SettingWorkspaceAuditLog.vue

I'll introduce pagination for activities (and also audit logs) in the next PR.
For now, audit logs record the following activity types:
- bb.member.create
- bb.member.role.update
- bb.member.activate
- bb.member.deactivate
- bb.project.database.transfer

feat: workspace-level audit log for owners and DBAs

---

frontend/src/assets/css/tailwind.css
frontend/src/bbkit/BBGrid/BBGrid.vue
frontend/src/bbkit/BBGrid/index.ts
frontend/src/bbkit/BBGrid/useResponsiveGridColumns.ts
frontend/src/bbkit/index.ts
frontend/src/bbkit/types.ts
frontend/src/components/InstanceTable.vue

Benefiting from using `display: grid`, we may control the columns' widths more precisely, responsively, and flexibly. Especially when the columns are mixed with fixed width, auto width and flex width.
We may replace some `<BBTable>`s with `<BBGrid>`. Starting from the `<InstanceTable>`, which is not too complex.
https://user-images.githubusercontent.com/2749742/207763023-c3577eca-d7a9-42ad-9c3b-4dae1f68c53d.mp4

feat(frontend): introducing <BBGrid> - a responsive, flexible <BBTable> alternative

---

frontend/src/components/ReleaseRemindModal.vue
frontend/src/layouts/BodyLayout.vue
frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/actuator.ts
frontend/src/types/actuator.ts
frontend/src/types/store.ts

We will fetch the GitHub release API to find the latest version and show the reminder modal.
Users can choose not to show this modal till the next release.
It's okay to fail as some users may not connect to the internet.
Close BYT-745
BTW I don’t have other suitable icons to mean "new version available"..

feat: support new version reminder

---

frontend/src/components/ProjectActivityPanel.vue
frontend/src/components/ProjectOverviewPanel.vue
frontend/src/store/modules/activity.ts

With the help of https://github.com/bytebase/bytebase/pull/3823, we can reduce the requests made to fetch activities (by specifying all typePrefixes we need in one try).
This PR is also to pave the road of pagination for activities.

refactor(frontend): make use of multiple typePrefixes to reduce request count

---

api/activity.go
server/activity.go
store/activity.go

Similar to https://github.com/bytebase/bytebase/pull/3823, but support the `level` field this time.
Make it possible to get activities with a range of levels. Now with a request to `/api/activity?level=INFO&level=WARN`, we'll get activities that are either of the INFO level or of the WARN level.
I'm making this change because I'm adding pagination support to activities (also audit logs), and [here](https://sourcegraph.com/github.com/bytebase/bytebase/-/blob/frontend/src/store/modules/activity.ts?L164) at the front-end we are using two separate requests to fetch activities of either INFO level or WARN level. We can support it on the server side to not only reduce client-side requests but also make it easy for pagination.

feat: support finding activities with multiple levels

---

server/runner/taskrun/scheduler.go

We should set assignee_need_attention to false if there isn't any pendingApproval task in the stage.
Before the PR, we did this when we were moving to the next stage, which is not correct.

fix: auto-set need attention to false

---

frontend/src/components/ProvideSQLEditorContext.vue
frontend/src/router/index.ts
frontend/src/store/modules/connectionTree.ts
frontend/src/store/modules/index.ts
frontend/src/store/modules/sqlEditor.ts
frontend/src/types/connectionTree.ts
frontend/src/types/index.ts
frontend/src/types/sqlEditor.ts
frontend/src/types/store.ts
frontend/src/views/sql-editor/AsidePanel/AsidePanel.vue
frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue
frontend/src/views/sql-editor/AsidePanel/TableSchema.vue

Both connectionTree and sqlEditor are getting more complex, so we split them into two.

refactor(frontend): split the connectionTree in sqlEditorStore into an independent module

---

frontend/src/components/IndexTable.vue
plugin/db/driver.go
plugin/db/mongodb/sync.go

After #3912, implement the sync index schema.

feat(mongodb): sync mongodb index schema (part2)

---

server/runner/taskrun/scheduler.go
store/task.go

This reverts commit 086e1711e3efee95fd7da863d56be0e90af0d763.
Was attempt to make a refinement on top of it. However, it's more complex to retain the intentional benefit of avoiding fetching pipeline, while keeping the stage execution order.
So play safe first.

fix: Revert "feat: improve task scheduling by avoiding to load all open pipelines (#3812)"

---

api/activity.go
frontend/src/store/modules/activity.ts
frontend/src/store/modules/auditLog.ts
frontend/src/types/common.ts
server/activity.go
store/activity.go

Modified the response structure of getting the activity list.
-> GET `/api/activity?limit=10`
```json5
"data": {
"type": "",
"attributes": {
"nextToken": "MTA5"
},
"relationships": {
"activityList": {
"data": [...10 items]
}
}
},
"included": {...}
```
Reference: 
- Server-side: https://github.com/bytebase/bytebase/pull/2381
- Client-side: https://github.com/bytebase/bytebase/pull/2404

feat: pagination support for activity list

---

frontend/src/components/SchemaDiagram/ER/TableNode.vue
frontend/src/components/SchemaDiagram/common/index.ts
frontend/src/components/SchemaDiagram/common/schema.ts

Close BYT-2155
- Use yellow `key` icons to indicate primary keys.
- Use gray `diamond` icons to indicate indexes (similar to Navicat).

feat(schema-diagram): primary keys and indexes

---

frontend/src/bbkit/BBGrid/BBGrid.vue
frontend/src/components/AccessControl/AddRuleForm.vue
frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
frontend/src/components/AlterSchemaPrepForm/ProjectStandardView.vue
frontend/src/components/DatabaseTable.vue
frontend/src/components/ProjectDatabasesPanel.vue
frontend/src/components/TransferDatabaseForm/TransferMultipleDatabaseForm.vue
frontend/src/store/modules/database.ts
frontend/src/views/DatabaseDashboard.vue

- Pagination - we've tried a couple of ways to optimize the performance when first rendering, but finally, we have to do pagination.
- Use BBGrid - better responsive column widths.
- Partial scrolling for modal dialogs with `<DatabaseTable>`, such as alter schema dialog, and transfer DB dialog. We could always see the [Cancel][Next] button groups without scrolling to the bottom.
Now we can finish the first rendering of 100 databases in an average of 1~2 seconds and scroll at 60FPS after that.

feat(frontend): database list improvement

---

server/runner/taskrun/scheduler.go

passCheck should only check the results of a "DONE" task check.

fix: passCheck should only accept finished checks

---

frontend/src/plugins/issue/logic/initialize/index.ts
frontend/src/router/index.ts
frontend/src/views/IssueDetail.vue

By now, we have a problem that is when clicking on an issue link, the page might stall for several seconds and then redirect to the issue detail page.
That's because we are doing some data fetching jobs in the router before routing. When the issue is very big (e.g., tens of tasks within), the stalling time will be as long as 30 seconds. Users won't know whether the page is still alive, and they might do some monkey clicks.
We don't really speed the loading procedure up. We just put it into the issue detail page (rather than the router). So when clicking on an issue link, the page will redirect ASAP and show a loading indicator.

feat(frontend): speed-up issue detail page

---

plugin/db/mysql/mysql.go
plugin/db/mysql/mysql_test.go

Without truncating, MySQL query will fail with the following error.
packet for query is too large. Try adjusting the 'max_allowed_packet' variable on the server

feat: truncate statement to 2M size for MySQL

---

api/task.go
server/task.go
store/task.go
tests/schema_update_test.go

We want to differentiate skipped tasks from completed tasks. They all have the status "DONE" currently, and we have no way to tell them apart.
We add the following fields to `Task.Payload` and use `Skipped` to mark skipped tasks.
```go
Skipped       bool   `json:"skipped,omitempty"`
SkippedReason string `json:"skippedReason,omitempty"`
```
Next, we will differentiate them on the frontend and in our webhooks.
@LiuJi-Jim FYI
Completing BYT-2171

feat(backend): differentiate skipped (mark as done) tasks

---

plugin/advisor/utils_for_tests.go
plugin/db/clickhouse/sync.go
plugin/db/driver.go
plugin/db/mongodb/sync.go
plugin/db/mysql/sync.go
plugin/db/pg/sync.go
plugin/db/snowflake/sync.go
plugin/db/sqlite/sync.go
server/runner/schemasync/syncer.go
server/runner/schemasync/syncer_test.go
tests/syncer_test.go

This PR support to get foreign keys for MySQL.
Because we haven't used protobuf in /pulgin/db yet, I implement this feature in this ugly way. This situation will be improved when protobuf is introduced later.
I also add the integration test to check this PR.
I'll support PostgreSQL in the following PR.

feat: support to get foreign keys for MySQL

---

plugin/webhook/webhook.go
server/component/activity/manager.go
server/utils/utils.go

Note that the comment, "skip it!", the user left when marking a task as done is shown both in the first line and the **Skipped Reason** row.
Completing BYT-2171

feat: in IM webhook show mark-as-done task as skipped

---

frontend/src/store/modules/issue.ts

Thanks for the reporting from @Megrax 
Due to performance considerations, the `[GET] /api/issue` issue list API endpoint is a compact one, returning incomplete issue entities without composed `database` and `instance` relationships. So we shouldn't store them as a cache item.

fix(frontend): 🔥 wrong issue entity cache

---

frontend/src/components/Issue/IssueDetailLayout.vue
frontend/src/components/Issue/IssueTaskStatementPanel.vue
frontend/src/components/Issue/logic/GhostModeProvider.ts
frontend/src/components/Issue/logic/IssueLogic.ts
frontend/src/components/Issue/logic/TenantModeProvider.ts
frontend/src/components/Issue/logic/base.ts

refactor `applyStatementToOtherTasks` to `applyTaskStateToOthers`. 
Task's state including its statement and sheetId. And sheetId has a higher priority than statement.

fix: apply task's sheet id to others

---

store/task.go

We've made changes in the scheduler that would avoid doing concurrent task creation.

chore: remove serializable level from transaction

---

api/activity.go
api/stage.go
server/component/activity/manager.go
server/issue.go
server/runner/taskrun/scheduler.go

Add stage status update activity.
Note that Stage doesn't have a so-called `Status` field. The "StageStatusUpdate" is a computed property of a stage.
A stage begins if
- it's the first stage
- every task status of the previous stage is DONE
A stage ends if every task status of the stage is one of DONE, FAILED, or CANCELED.
A stage can only begin once.
A stage can end multiple times.
1. webhook message improvement
The information in the webhook messages is not quite useful currently. I'm planning to add a summary of the terminated tasks of the stage to it.
2. the setting page
need to add a new selectable.
Close BYT-2172

feat: stage status update activity

---

plugin/db/mongodb/migrate.go

We use `id` instead of `_id`, so we don't need to generate ObjectID object anymore.

fix(mongodb): using id directly

---

frontend/src/components/CreateInstanceForm.vue
plugin/db/mysql/mysql.go
server/sql.go

close BYT-2177
Maybe there's still some front-end work left unfinished. cc @LiuJi-Jim @boojack 
I do the local test with MySQL and TiDB.
1. open the ssl feature in the database engine
2. create the user REQUIRE SSL
3. connect in Bytebase
MySQL without SSL
MySQL with SSL
TiDB without SSL
TiDB with SSL

feat: support mysql/tidb ssl

---

api/task.go
server/runner/taskrun/scheduler.go
server/task.go
store/task.go
tests/schema_update_test.go

We've moved batch to a different function.

refactor: remove the batch ids from patch task status

---

frontend/src/components/CreateInstanceForm.vue

If defaultauthdb is unspecified, then [authSource](https://www.mongodb.com/docs/manual/reference/connection-string/#mongodb-urioption-urioption.authSource) defaults to admin.

chore(mongodb): using admin as placeholder in authSource

---

frontend/src/components/InstanceEngineIcon.vue
frontend/src/components/Issue/IssueTaskStatementPanel.vue
frontend/src/components/MonacoEditor/MonacoEditor.vue
frontend/src/components/MonacoEditor/useMonaco.ts
frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json
frontend/src/types/sqlEditor.ts
frontend/src/utils/instance.ts
frontend/src/views/sql-editor/EditorPanel/SQLEditor.vue
frontend/src/views/sql-editor/SQLEditorPage.vue
frontend/src/views/sql-editor/TerminalPanel/CompactSQLEditor.vue

- Only enable SQL Editor for MongoDB database in admin mode (BYT-2207).
- Use javascript language support in MonacoEditor for MongoDB.
- Show "Statement" instead of "SQL" on the issue detail page for MongoDB tasks.
- Horizontal center aligned MongoDB engine icon.

feat(frontend): better MongoDB support while using MonacoEditor

---

go.mod
go.sum
store/cache.go

`fastcache` cannot get/set the big item which is bigger than 64K.
Considering that Bytebase does not need cache evict for the time being, we use map instead of `fastcache`.
If we need real cache later, remove it.

fix: use map instead of fastcache

---

frontend/src/components/SchemaDiagram/ER/TableNode.vue

We found that lot's of `<NEllipsis>`s will make the component's `unmount` lifecycle very very slow.
We should find another way to display the complete info of columns' types.

fix(schema-editor): performance issue when there's lot's of <NEllipsis>

---

frontend/src/components/CreateDataSourceExample.vue

In order to run	`db.runCommand({usersInfo: {forAllDBs: true}});`, we need `viewUser` and `viewRole` privileges in all databases.

fix(mongodb): add userAdminAnyDatabase role in mongodb connection info

---

frontend/src/components/SchemaDiagram/ER/TableNode.vue
frontend/src/components/SchemaDiagram/SchemaDiagram.vue
frontend/src/components/SchemaDiagram/index.ts
frontend/src/components/SchemaDiagram/types/context.ts
frontend/src/components/SchemaDiagram/types/edit.ts
frontend/src/components/SchemaDiagram/types/index.ts
frontend/src/components/SchemaEditor/Panels/DatabaseEditor.vue
frontend/src/components/SchemaEditor/utils/useMetadataForDiagram.ts

Close BYT-2166
FYI @tianzhou @Candybase 
We now support colorizing these kinds of schema changes (basically the same as Schema Editor)
- Table
- Created / Dropped / Changed
- Column
- Created / Dropped
https://user-images.githubusercontent.com/2749742/210339533-7cbf9f64-8a27-4c6f-b25f-7c52ee4db818.mp4

feat(schema-diagram): preview schema changes in schema diagram from schema editor

---

server/deploy.go
server/runner/schemasync/syncer.go
server/runner/taskrun/executor.go

This can reduce the amount of time and customer instance resources on automatic schema syncs. We will update the database schema version on database changes.

chore: skip schema version sync except for force sync

---

plugin/db/spanner/dump.go
plugin/db/spanner/migrate.go
plugin/db/spanner/spanner.go
plugin/db/spanner/sync.go

This PR implements syncing database schema for the spanner driver.
Note that only databases using google standard SQL are supported currently.
Also need to fix the instance/database detail page for spanner, as some fields are unavailable.
Completing BYT-2241

feat(spanner): backend sync db schema

---

frontend/src/components/SchemaDiagram/Canvas/Canvas.vue
frontend/src/components/SchemaDiagram/ER/TableNode.vue
frontend/src/components/SchemaDiagram/SchemaDiagram.vue
frontend/src/components/SchemaDiagram/common/useDraggable.ts
frontend/src/components/SchemaDiagram/types/context.ts
frontend/src/components/SchemaEditor/Panels/DatabaseEditor.vue
frontend/src/components/SchemaEditor/Panels/TableEditor.vue
frontend/src/components/SchemaEditor/utils/useMetadataForDiagram.ts

Close BYT-2167
FYI @tianzhou @Candybase 
- Keep the zoom and position when switching back from editor to diagram.
- Click on a foreign key line to edit it.
https://user-images.githubusercontent.com/2749742/210506763-79c9ef60-254c-4e0c-adb0-1564c8976685.mp4

feat(schema-diagram): call Schema Editor UI via Schema Diagram

---

frontend/src/components/ProjectTable.vue
frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json

It was there but didn't provide meaningful information. And we're unlikely to provide this information in v1 API.

chore: remove created time from project list

---

plugin/db/pg/pg.go

"postgres" is a more commonly used default database. Let's make most of guesses right.

chore: change the ordering of guessing databases

---

api/database.go
server/database.go
server/runner/schemasync/syncer.go
server/runner/taskrun/database_create_executor.go
server/runner/taskrun/pitr_cutover_executor.go
server/runner/taskrun/pitr_restore_executor.go
server/runner/taskrun/schema_baseline_executor.go
server/runner/taskrun/schema_update_executor.go
server/runner/taskrun/schema_update_ghost_cutover_executor.go
server/runner/taskrun/schema_update_sdl_executor.go
server/sql.go
store/instance.go

In addition, removed the default charset and collation for wildcard dummy database because they should always be empty string.

refactor: simplify the interface of database schema sync

---

bin/server/cmd/root.go
server/component/config/profile.go
server/server.go
store/pg_engine.go

Reduce confusion since our schema version is not always the same as server version.

chore: include schema version in the server startup log

---

frontend/src/components/AccessControl/AddRuleForm.vue
frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json
frontend/src/views/SettingWorkspaceAccessControl.vue

- Add a "Learn more" link. (Close BYT-2197)
- Add wordings for empty "Add rule" dialog. (Close BYT-2197)
- Show "Inactive rules" if some of the rules are in unprotected environments. (Close BYT-2075)
FYI @Candybase

feat(frontend): access control settings improvements

---

common/log/logger.go

chore: use zap Encoding “console” to print readable stacktrace

---

api/instance.go
api/task.go
api/task_run.go
plugin/advisor/utils_for_tests.go
plugin/db/clickhouse/migrate.go
plugin/db/driver.go
plugin/db/mongodb/migrate.go
plugin/db/mysql/migrate.go
plugin/db/pg/migrate.go
plugin/db/snowflake/migrate.go
plugin/db/spanner/migrate.go
plugin/db/sqlite/migrate.go
plugin/db/util/driverutil.go
server/instance.go
server/runner/rollbackrun/runner.go
server/runner/taskrun/executor.go
server/runner/taskrun/pitr_restore_executor.go
server/runner/taskrun/schema_update_ghost_cutover_executor.go
store/migration/dev/20230106000000##change_migration_history_id_type_to_string.sql
tests/instance.go
tests/schema_update_test.go
tests/sync_schema_test.go
tests/tenant_test.go

Change MigrationHistory.ID type to string because the ID of the migration_history table of Spanner is of string type.

refactor: change migrationHistoryID to string from int64

---

store/pg_engine.go
tests/start_test.go
tests/tests.go

Bug is introduced in https://github.com/bytebase/bytebase/pull/4186 where we added getLatestVersion to fetch the schema version. However, there is a hidden order dependency, and calling getLatestVersion after d.GetDBConnection would invalidate the connection, thus causing `sql: connection is closed` error in readonly mode

fix: fix failure in readonly mode

---

plugin/db/spanner/spanner.go
plugin/db/spanner/spanner_test.go
plugin/db/spanner/statement_parser.go

Implement query for spanner driver.
The query func expects to take a single SQL statement and returns the result.
We don't support spanner [STURCT](https://cloud.google.com/spanner/docs/reference/standard-sql/data-types#struct_type) type for now, which should be fine as it's also not supported in the official spanner database/sql driver.

feat(spanner): implement query

---

frontend/src/views/sql-editor/AsidePanel/AsidePanel.vue
frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue
frontend/src/views/sql-editor/AsidePanel/TreeNode/InstancePrefix.vue
frontend/src/views/sql-editor/AsidePanel/TreeNode/Prefix.vue
frontend/src/views/sql-editor/AsidePanel/TreeNode/Suffix.vue
frontend/src/views/sql-editor/TabList/TabItem/AdminLabel.vue
frontend/src/views/sql-editor/TabList/TabList.vue

- Show parentheses and instance icons for project-database view nodes. (Close BYT-2275, BYT-2286)
- Make instance-database view only available for high-privileged users. (Close BYT-2281)
- Tuning spacings for tree nodes without prefix icons. (Close BYT-2289)
- Make the tree not text-selectable. (Close BYT-2280)
- Fix Admin mode tabs' text wrapping issue. (Close BYT-2279)
- Hide table schema panel when switching databases/instances. (Close BYT-2291)
- Hide the overflow indicator gradient. (Close BYT-2282)
FYI @Candybase @tianzhou

feat(sql-editor): some minor improvements and fixes

---

frontend/src/components/SchemaDiagram/ER/TableNode.vue
frontend/src/components/SchemaEditor/utils/useMetadataForDiagram.ts

Benefiting from #4234, we can now also highlight changed columns in Schema Diagram.
Close BYT-2260
We've tried but still can't find a perfect position to place a "DOT" indicator (like VSCode tabs). Maybe consider more about this and bring it next time.
FYI @Candybase @tianzhou

feat(schema-diagram): render changed columns in yellow

---

frontend/src/components/AccessControl/AddRuleForm.vue
frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
frontend/src/components/AlterSchemaPrepForm/ProjectStandardView.vue
frontend/src/components/TransferDatabaseForm/TransferMultipleDatabaseForm.vue
frontend/src/views/SettingWorkspaceAccessControl.vue

We did some kind of style tunings on small screens to prevent double scrollbars for the popup database list windows.
Close BYT-2229
FYI @Candybase

chore(frontend): prevent double scrollbars on small screens

---

frontend/src/components/CreateInstanceForm.vue
frontend/src/components/InstanceForm.vue
plugin/db/pg/pg.go

close BYT-2178
Add SSL config in DSN for PostgreSQL only supports the file path, so we use the Package stdlib which is the compatibility layer from pgx to database/sql.
To connection PG:
1. generate the DSN without SSL config
2. parse the DSN to pgx.ConnConfig
3. add the SSL config into pgx.ConnConfig
4. register the new pgx.ConnConfig and get the connection string
5. use the connection string to connection PG with SSL
Also, we need to unregister the connection string if we don't need the pgx.ConnConfig.

feat(db): support PostgreSQL SSL connection

---

plugin/db/clickhouse/clickhouse.go

Reverts bytebase/bytebase#4113
`tlsConfig = &fls.Config{}` means that we use the CA in local operation system, such as `/etc/ssl/cert.pem` in MacOS.
`tlsConfig = nil` means that we don't use the SSL connection.
The #4113 will cause that bytebase always connects clickhouse with SSL
Close BYT-2305

fix: revert "fix(clickhouse): using empty tls config instead of nil"

---

frontend/src/components/MonacoEditor/MonacoEditor.vue

We didn't implement auto-completion logic and algorithms for JavaScript language (mongosh) yet. That will be quite a long way to go.
So we need to temporarily turn off this feature for JavaScript language.
FYI @Candybase @h3n4l

chore(sql-editor): disable auto-complement for JavaScript language (MongoDB)

---

store/database.go

Only PostgreSQL 14+ can use the key word `values` as the alias without `AS`.
Remove the key word `values` in queries to ensure higher robustness.

fix: remove key words in SQL

---

frontend/src/composables/useCancelableTimeout.ts
frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/webTerminal.ts
frontend/src/types/webTerminal.ts
frontend/src/views/sql-editor/TerminalPanel/TerminalPanel.vue

The **Cancel** button will be displayed if a query keeps running longer than 5 seconds.
Close BYT-1922
I've tried to add a "Ctrl+C" keybinding to this feature, but that will conflict with the keyboard shortcut of "Copy" so I give up.
https://user-images.githubusercontent.com/2749742/212594704-f93a3c1f-a4ae-412f-9a12-e2bf7b0ce8f1.mp4

feat(sql-editor): cancel running query

---

plugin/db/pg/dump.go
tests/schema_update_test.go

> Scanning stops unrecoverably at EOF, the first I/O error, or a token too large to fit in the buffer. When a scan stops, the reader may have advanced arbitrarily far past the last token. Programs that need more control over error handling or large tokens, or must run sequential scans on a reader, should use bufio.Reader instead.
Reference
- https://pkg.go.dev/bufio#Scanner
close BYT-2352

fix: use reader instead of scanner to fix "bufio.Scanner: token too long"
