bytebase/bytebase

frontend/src/components/CreateInstanceForm.vue
frontend/src/components/InstanceForm.vue
plugin/db/spanner/spanner.go

Don't require `database` field for spanner instance anymore.
We needed it before because we want to connect to a database when Ping, now we just use ListDatabases for Ping.
also update spanner instance description in InstanceForm.vue. Forgot about that in #4309 ...
Close BYT-2349

chore: don't require database field for spanner instance

---

frontend/src/components/SchemaDiagram/Canvas/Canvas.vue
frontend/src/components/SchemaDiagram/Canvas/DummyCanvas.vue
frontend/src/components/SchemaDiagram/Canvas/libs/fitView.ts
frontend/src/components/SchemaDiagram/common/geometry.ts

- Limit the exported PNG in a 4096*4096 box (keeping its width:height ratio).
FYI @tianzhou

feat(schema-diagram): limit exported png size

---

frontend/src/components/DatabaseListSidePanel.vue

We've hidden NOT_FOUND databases by default since #3973, but this place is missed.

fix(frontend): hide NOT_FOUND databases in sidebar

---

frontend/src/components/SchemaDiagram/Canvas/DummyCanvas.vue

- When exporting the schema diagram to PNG, we also try to copy the binary image data to the clipboard.
- Due to some security limitations of browsers, users might be asked when the exported image is large (> 1MB, I guess).
FYI @tianzhou

feat(schema-diagram): (experimental) copy exported png to clipboard

---

plugin/db/util/driverutil.go

The migration might include the drop database statement.

fix: ignore database not found error after executing migration statement

---

store/data_source.go
store/database.go
store/instance.go

We’ve introduced the bug in this PR https://github.com/bytebase/bytebase/pull/4226/commits/d304a3eaa266e91213a1a522af98755b0f0e0d4d#diff-ee528d2122bdba561819021a044c90843bd46a95aa7071c144849e485d0788afL821
This will fail the data source creation for a new instance

fix: create database before create the data source

---

frontend/src/components/Issue/IssueTaskStatementPanel.vue
frontend/src/components/Issue/logic/useSQLAdviceMarkers.ts
frontend/src/components/MonacoEditor/MonacoEditor.vue
frontend/src/components/MonacoEditor/index.ts
frontend/src/components/MonacoEditor/plugins/useAdvices.ts
frontend/src/components/MonacoEditor/types.ts
frontend/src/types/pipeline/task.ts
frontend/src/utils/index.ts
frontend/src/utils/string.ts

- The wavy lines are only visible when we are NOT editing SQL statements.
- Only SQL advices are ready to visualize since we are starting from #4350 
- We don't know the column numbers, so we put the wavy lines at the end of the line, once we get the line numbers, they could be soon optimized.
- I tried to add a hyper link to the error code but failed since monaco-editor doesn't support this.
Close BYT-2382
FYI @rebelice @Candybase

feat(sql-editor): visualize sql advice errors and warnings

---

server/webhook.go

- #4372
We introduce `commit filter` in #3411, which extract the `before` and `after` field in the `push event` payload, and then request GitLab/GitHub for more information with them to get the "correct" commit list to filter the original `commits` field.
But for the new branch, the `before` field always be zero, and the VCS returns `404` status code, and then we return `500` status code to VCS.
For example:
```bash
git checkout -b foo
[do some change]
git add .
git commit -m "msg"
```
The `before` field in the push event is zero, and the `commits` field contains the file Bytebase wants:
Skip the filter if the before field is zero.
**This is a temporary fix to unblock customers. we need to evaluate the GitOps workflow later carefully and come up with a cleaner fix.**
The screenshots after …

feat(vcs): don't filter diff if the before field is zero

---

frontend/src/components/Quickstart.vue

Currently, it's showing all checked:
After fix:
Fix BYT-2404

fix: fix quickstart item status

---

backend/bin/server/cmd/profile.go
backend/bin/server/cmd/profile_dev.go
backend/bin/server/cmd/profile_release.go
backend/common/util.go
backend/component/config/profile.go
backend/server/server.go
backend/tests/schema_update_test.go
backend/tests/sql_editor_test.go
backend/tests/sql_review_test.go
backend/tests/start_test.go
backend/tests/sync_schema_test.go
backend/tests/syncer_test.go
backend/tests/tests.go

Because we reset data when running demo and this prevents we accidentally removing production data (if user first starts in normal mode and then starts in demo mode).
Fix BYT-1815

feat: put demo data under separate pgdata-demo/<<demo-name>> directory

---

backend/store/migration/dev/LATEST.sql
backend/store/migration/prod/1.12/0004##drop_pipeline_status.sql
backend/store/migration/prod/LATEST.sql
backend/store/pg_engine_test.go
backend/store/pipeline.go

The pipeline status is no longer used. This field was used to get active pipeline in the task scheduler which is already optimized.

chore: drop pipeline status

---

backend/server/acl.go
backend/server/jwt.go

We should pass GET `/api/feature` even if user not login in. e.g. Sign in with SSO will a paid feature.

fix: skip get `/api/feature`

---

backend/api/v1/auth_service.go
backend/bin/server/cmd/profile.go
backend/common/util.go
backend/component/config/profile.go
backend/legacyapi/project.go
backend/resources/postgres/employee.sql
backend/resources/postgres/postgres.go
backend/server/server.go
backend/tests/start_test.go
backend/tests/tests.go

With this, the first signup user will have a ready-to-be used instance to play with
* Always start a sample pg instance on startup, it will consume another port (--port + 3).
* Set up that sample database data, this PR contains the example data for an employee table. The sample data stays in a separate `pgdata-sample` dir
* Generate onboarding data after the first user signup, create a sample project, transfer the sample database to that project and etc.
* Generate more fruitful sample data.
* Clean up the existing sample database creation using hard-coded 23333.
* Implement the onboarding flow based on this sample instance.
Fix BYT-1815

feat: start sample pg instance and generate onboarding data after first signup

---

backend/api/v1/auth_service.go
backend/legacyapi/project.go
backend/server/server.go
frontend/src/components/Breadcrumb.vue
frontend/src/components/Issue/IssueActivityPanel.vue
frontend/src/components/ProfileDropdown.vue
frontend/src/components/Quickstart.vue
frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json
frontend/src/views/IssueDetail.vue

* Create a schema update issue
* Bookmark the issue
* Create a sheet
Accordingly, the PR also changes:
* Move the onboarding logic to a postCreateUser callback, otherwise, it would be hard to call the server.CreateIssue
* Create the sample instance under prod environment, so that user can click `approve` to review the schema change
* Simplify Quickstart panel, remove `bookmark an issue` and `add a comment`. And add "Visit an issue".
Fix BYT-1815

feat: generate more onboarding data

---

backend/api/v1/idp_service.go

Otherwise, any random user can get both the client ID and secret by just visiting the `/auth` page.

fix(idp): do not expose client secret in responses

---

frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/webTerminal.ts
frontend/src/types/webTerminal.ts
frontend/src/views/sql-editor/EditorCommon/EditorAction.vue
frontend/src/views/sql-editor/TerminalPanel/CompactSQLEditor.vue
frontend/src/views/sql-editor/TerminalPanel/TerminalPanel.vue

- Limit maximum query history count to 20 to prevent memory inflation.
- Add a button and keyboard shortcut to clear query history. (Close BYT-1919)

feat(sql-editor): query history improvement

---

backend/api/v1/auth_service.go
backend/store/principal.go

fix: empty value of `IdentityProviderResourceID` in finding users (#4489)

---

frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json
frontend/src/views/sql-editor/EditorCommon/EditorAction.vue
frontend/src/views/sql-editor/TerminalPanel/CompactSQLEditor.vue
frontend/src/views/sql-editor/TerminalPanel/TerminalPanel.vue
frontend/src/views/sql-editor/TerminalPanel/useHistory.ts

Close BYT-2448
FYI @tianzhou 
- Split history items and query items.
- Display up to 20 query items (per tab) on the screen to prevent consuming hundreds of megabytes of system memory.
- Remember up to 1000 history items (per tab) for cmd+up/down searching. (not persistent, will lose after refreshing the page).
- Rename "Clear history" to "Clear screen". It will only clear the query items on the screen but keep statements searchable via cmd+up/down. (like `clear` or `cls` in an actual terminal).

feat(sql-editor): split history items and query items

---

frontend/src/components/InstanceForm/SslCertificateForm.vue
frontend/src/components/misc/DroppableTextarea.vue

Close BYT-2253
This is a quick way to support uploading files without changing UI too much. FYI @Candybase 
Support file size up to 1MB (cert files are tens of KBs typically, so this is fairly enough).
https://user-images.githubusercontent.com/2749742/216528711-95876380-862c-4403-95ab-eebd1233da1f.mp4

feat(frontend): support drag-and-drop to upload SSL certification file

---

frontend/src/views/sql-editor/EditorCommon/AdminModeButton.vue

This won't be displayed but will be used as part of the filename while exporting query results.
Close BYT-2480

chore(sql-editor): default name of admin tab

---

frontend/src/views/MigrationHistoryDetail.vue

The ID field is UUID for spanner, so we can't use ID to get the previous migration history list. Fortunately, the returned migrationHistoryList is ordered descending either by ID (others) or (namespace, sequence) pair (spanner). We can get the previous migration history list by obtaining the one that has the migrationHistoryId and every one after.
Close BYT-2485

fix(frontend): migration history cannot filter by ID as spanner's ID is UUID, use sequence

---

frontend/vite.config.ts

This tells vite to proxy all `/hook/**` API requests to backend.

chore(frontend): proxy for /hook/** api in vite for git push webhooks

---

backend/plugin/db/spanner/migrate.go
backend/runner/taskrun/database_create_executor.go

We can pass extra statements (DDLs) when creating a new spanner database. So we don't need to (and cannot) switch database using "USE db1" statement.
First, we concat 'CREATE DATABASE Xxx' and the schema from the peer. Then we split them by ';', and the first is the "CREATE DATABASE" statement, others go to the extra statements.
Close BYT-2439

fix(spanner): create database in tenant mode

---

frontend/src/components/InstanceForm/SpannerHostInput.vue

Will handle some edge cases such as the InstanceID ends with "/"

fix(frontend): use stricter regexp for spanner host

---

backend/legacyapi/issue.go
backend/legacyapi/task.go
backend/runner/rollbackrun/runner.go
backend/runner/taskrun/executor.go
backend/server/issue.go
backend/tests/rollback_test.go

Add `RollbackEnabled` boolean to control whether to build the rollback SQL.
We don't want to build the rollback SQL for every DML task which consumes CPU, memory, network bandwidth, etc.
Completing BYT-2496
FYI @LiuJi-Jim 
Patching RollbackEnabled will be in the following PR.

feat: add a switch to control whether to build the rollback sql

---

.github/workflows/backend-tests.yml

Our golangci-lint jobs are timing out recently.
Increase goangci-lint job to 10m according to https://github.com/golangci/golangci-lint-action/issues/297

chore: increase golangci-lint timeout to 10m

---

backend/legacyapi/task.go
backend/runner/taskrun/scheduler.go
backend/server/task.go
backend/server/webhook.go
backend/store/task.go
backend/tests/issue.go
backend/tests/rollback_test.go

previous PR #4639 
support patching rollbackEnabled
Enqueue the task to the rollback generation queue if rollbackEnabled is patched to true.
Remove it from the queue if false.
Also need to cancel the ongoing generation if we were to remove it from the queue. But that's left for another PR.
@LiuJi-Jim FYI
Completing BYT-2496

feat: patch task rollbackEnabled

---

backend/runner/rollbackrun/runner.go

Should reset payload.RollbackStatement and payload.RollbackError as we can retry generating rollback SQL now.

fix: reset payload rollback statement and error

---

quickstart/clickhouse-quickstart.docker-compose.yml

New versions are located in `clickhouse/clickhouse-server` only.

Change ClickHouse Docker repository.

---

backend/runner/taskrun/scheduler.go

Only enqueue the task if it's DONE.
If we enable rollback for pending tasks. it should be picked up after finishing running.

fix: enqueue task for rollback sql generation if it's done

---

frontend/src/views/sql-editor/TerminalPanel/TerminalPanel.vue
frontend/src/views/sql-editor/TerminalPanel/useAttractFocus.ts

As discussed in BYT-2475, clicking on the page will cause the active SQL Editor to lose its focus. This PR tries to re-focus the active SQL Editor while appropriate keystroke events are emitted.
FYI @tianzhou 
https://user-images.githubusercontent.com/2749742/217706587-d40e9d67-efa0-4ea3-9baa-337d0d4d4b39.mp4

feat(sql-editor): auto-re-focus to active SQL Editor when needed

---

backend/legacyapi/plan.go
frontend/src/bbkit/BBComboBox.vue
frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json
frontend/src/types/plan.ts
frontend/src/views/SettingWorkspaceAccessControl.vue
frontend/src/views/SettingWorkspaceAuditLog.vue
frontend/src/views/SettingWorkspaceSensitiveData.vue

WIP BYT-2520
- Move the Audit Log feature to the Enterprise plan
- Apply the same UX to Audit Log, Sensitive Data and Access Control

feat(frontend): move audit log to enterprise version

---

frontend/src/components/Issue/IssueRollbackButton.vue

remove the original task link from rollback issue description because it's already displayed on the header.

fix: remove original task link from rollback issue description

---

frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json

It is quite unclear what to do when there is more than one scope needed for the OAuth 2 "Scopes" field.
Updated the field description to inform the user to use space as the separator.

fix(sso): improve description of the OAuth 2 scopes

---

.golangci.yaml
backend/api/v1/auth_service.go
backend/api/v1/project_service.go
backend/server/auth.go
backend/server/webhook.go
backend/store/principal.go
backend/store/store.go

Since `email` isn't an identifier of `principal` table, the `userEmailCache` will cause bytebase user cannot login if there is an idp user with same email.

fix: remove user email cache

---

backend/plugin/db/pg/dump.go

We collect the pg_dump error by using pipeline, we should collect the error message until the following cases:
1. meet `io.EOF`
2. had collected 1024 bytes
@rebelice How to reproduce the problem in [BYT-2463]? I cannot reproduce this by using:
```SQL
CREATE TABLE tbl(id INT UNIQUE, id2 INT UNIQUE);
CREATE TABLE tbl2(id INT UNIQUE, id2 INT UNIQUE, CONSTRAINT fk_id_tbl_id2 FOREIGN KEY (id) REFERENCES tbl(id2));
ALTER TABLE tbl ADD CONSTRAINT fk_id_tbl2_id2 FOREIGN KEY (id) REFERENCES tbl2(id2);
```

feat: read error message until EOF

---

frontend/src/components/PricingTable/PricingTable.vue
frontend/src/locales/subscription/en-US.json
frontend/src/views/BannerSubscription.vue
frontend/src/views/SettingWorkspaceSubscription.vue

* Decrease banner height to save space, align center and use icon to signal.
* The purchase links to the console pricing page instead of the website pricing page.
* Console pricing page links to the hub instead of the website pricing page, which is kind of duplicate info.
* Fix upload license style.

feat: improving purchase flow

---

backend/api/v1/idp_service.go
backend/bin/server/cmd/root.go
frontend/src/components/Breadcrumb.vue
frontend/src/components/IdentityProviderCreateForm.vue
frontend/src/components/IdentityProviderTable.vue
frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json
frontend/src/router/index.ts
frontend/src/store/modules/idp.ts
frontend/src/store/modules/router.ts
frontend/src/types/common.ts
frontend/src/views/Archive.vue
frontend/src/views/SettingWorkspaceSSO.vue
frontend/src/views/SettingWorkspaceSSODetail.vue

1. Support archive/restore SSO;
2. Use list style for SSO setting page;
3. Use page instead of dialog for creating SSO;
Close BYT-2530

feat: update SSO setting pages style

---

backend/legacyapi/task.go
backend/runner/rollbackrun/runner.go
backend/runner/taskrun/scheduler.go
backend/server/issue.go
backend/store/task.go

retry #4690 
Add a status field because we thought we could calculate the status by rollbackStatement and rollbackError by assuming that rollbackStatement is not "" for a completed generation but it turns out not.

feat: rollback generation status

---

backend/plugin/idp/oauth2/oauth2.go
backend/plugin/idp/oidc/oidc.go

Adds debug-level logging after we unmarshaled user claims from the IdP response for easier troubleshooting.
```
2023-02-13T11:54:50.981+0800	DEBUG	oidc/oidc.go:109	User info	{"claims": {"email_verified":false,"family_name":"REDACTED","given_name":"REDACTED","name":"REDACTED","preferred_username":"admin","sub":"3c2f21e3-0abd-4f58-bf15-c9551a7bf713"}}
```

chore(idp): debug log for user claims

---

frontend/src/components/Issue/rollback/RollbackStatus.vue
frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json
frontend/src/types/pipeline/task.ts

Use the new field introduced by #4716 to make the logic more stable.
We can now detect the scene that the rollback statement was generated successfully as an empty string (usually 0 rows affected by the original SQL).

chore(frontend): use RollbackSQLStatus

---

backend/api/v1/auth_service.go
backend/store/principal.go

This PR add the backfill code for principal table. 
We will update `idp_id` and `idp_user_info` fields for those Bytebase user has the same email with userinfo from SSO provider.

chore: backfill bytebase user to SSO

---

frontend/src/components/ColumnTable.vue
frontend/src/views/sql-editor/EditorCommon/DataTable.vue

Before the column is offset by 1
Also move the icon to the right of the column header so the text is aligned properly

fix: correct postgres column list to account for sensitive column

---

backend/runner/anomaly/scanner.go

e.g. 
This change will leave the anomaly forever if there was one already. Because we now skip in the first place, there is no chance to archive it. However, this should be fine as MongoDB and Spanner are both in beta.
close BYT-2552

fix: skip checking backup anomalies for unsupported databases

---

backend/tests/issue.go

If we see "invalid task status transition" error, we silently ignore and wait for another round.
Close BYT-2498

fix(tests): waitIssuePipeline ignore invalid transition error

---

backend/legacyapi/task.go
backend/runner/taskrun/scheduler.go
backend/store/task.go

Filter out rollback tasks when fetching tasks that are to be approved automatically. Because we want to always manually approve rollback issues with which we should always be careful.
Also change `StageBlocked *bool` to `FilterOutBlockedStage` because it seems bizarre to me. It uses a bool pointer and does the filtering if the pointer is not nil. I think using a bool is more straightforward.
/cherry-pick-me
Close BYT-2569

feat: no auto approve for rollback tasks

---

frontend/src/components/Issue/rollback/common.ts

fix: when the project is in tenant mode and we use "manual selection", we use multiple migrationDetail in the issue creation context.

fix(frontend): set migrationDetail.rollbackEnabled respectively

---

backend/plugin/parser/differ/mysql/constraint_test.go
backend/plugin/parser/differ/mysql/differ.go

1. trim outer parentheses for CHECK expression.
2. skip DEFAULT NULL column option.
3. skip default charset and collation.

chore: improve MySQL differ

---

frontend/src/layouts/BodyLayout.vue
frontend/src/layouts/DashboardLayout.vue
frontend/src/views/DashboardHeader.vue

- Changed the overall layout from `T-LR` to `L-TD`
- Still keep the logo on small screens.

chore(frontend): adjust dashboard layout

---

backend/runner/rollbackrun/runner.go

We need row-based binlog enabled to build rollback SQL. We'd better check that beforehand.
Close BYT-2591

fix: check binlog settings before generating

---

backend/plugin/db/snowflake/sync.go

> <html>
SCHEMA_NAME | TEXT | Name of the schema
-- | -- | --
</html>
For the [Snowflake docs](https://docs.snowflake.com/en/sql-reference/info-schema/schemata#columns), we need to use the `SCHEMA_NAME` field to filter out the excluded schemata instead of `TABLE_SCHEMA`.

fix(snowflake): using SCHEMA_NAME instead of TABLE_SCHEMA in *.INFORMATION_SCHEMA.SCHEMATA to sync schema

---

frontend/src/components/SchemaDiagram/Canvas/DummyCanvas.vue
frontend/src/components/SchemaDiagram/Navigator/TreeNode/Label.vue

- Include the table count beside the schema title (Close BYT-2607)
- Add a timestamp to the bottom right of the exported image file. (Close BYT-2606)

feat(schema-diagram): schema diagram minor improvements

---

backend/api/v1/auth_service.go
backend/api/v1/idp_service.go

When the unique identifier is the email, email is the email identifier. Otherwise, we use identifier@domain to generate the email identifier.

fix: identify the email generation by unique identifier field mapping

---

frontend/src/bbkit/BBContextMenuButton.vue
frontend/src/bbkit/BBTooltipButton.vue

A weird bug. The **Approve / Approve current state** button is fine.
- Before (hovering)
- After (hovering)

fix(frontend): style of BBContextMenuButton

---

backend/legacyapi/vcs.go
backend/plugin/vcs/github/github.go
backend/plugin/vcs/github/github_test.go
backend/plugin/vcs/gitlab/gitlab.go
backend/plugin/vcs/gitlab/gitlab_test.go
backend/plugin/vcs/vcs.go
frontend/src/store/modules/repository.ts

Not all code hosts use numberic ID for repositories (i.e. Bitbucket Cloud uses UUID), so we need to use the string representation to be most compatible. Turns out our store layer is already using string type for persisting external repository ID: 
https://github.com/bytebase/bytebase/blob/8ed1b98b600e08052f01c6371a1f353b48074559/backend/store/repository.go#L34

fix(vcs): use string to represent external repository ID

---

scripts/demo.sh

Seems that we were relying on testing the file to check if postgres has started. But the file changed unfortunately.
It would be more reliable if bytebase creates the file indicating that postgres has finished setup though...

fix(demo): test filename

---

backend/server/database.go
backend/tests/database.go
backend/tests/schema_update_test.go

The frontend can use `sdl` parameters to get the SDL format schema.

chore: add sdl parameters for GET /database/:databaseID/schema

---

backend/server/instance.go
backend/tests/instance.go
backend/tests/schema_update_test.go

The frontend can use `sdl` parameters to get the SDL format schema.

chore: add sdl parameters for GET /instance:instanceID/migration/history/:historyID

---

backend/plugin/db/snowflake/role.go

ACCOUNT_USAGE can have multiple entries for the same name if there is DELETED_ON entry
Fix BYT-2669

fix: only fetch active snowflake users

---

frontend/src/components/Issue/IssueTaskSDLPanel.vue

Known flaws: we cannot detect the accurate line where things happened. So the markers will be displayed at the end of each statement by now.
Close BYT-2663
FYI @rebelice

feat(frontend): display error lines for SDL syntax checks

---

frontend/src/views/sql-editor/TerminalPanel/CompactSQLEditor.vue

Close BYT-2474
Still, we don't know if this will conflict with some of MonacoEditor's common native key-bindings and features. So we need to test this more carefully.
FYI @tianzhou

feat(sql-editor): press up/down arrow keys to walk through history items

---

backend/utils/utils.go

Don't create tasks for a not found database.
Close BYT-2670

fix: skip not found db in task generation

---

frontend/src/composables/useExecuteSQL.ts
frontend/src/store/modules/sql.ts
frontend/src/store/modules/sqlEditor.ts
frontend/src/types/tab.ts
frontend/src/types/webTerminal.ts
frontend/src/views/sql-editor/EditorCommon/TableView.vue
frontend/src/views/sql-editor/TerminalPanel/TerminalPanel.vue

- Display a simple line of text when the executed statement is not a query (like `alter table` or `set @var...` commands). Close BYT-2542 
- Put the error messages into the result part instead of push notifications. Close BYT-2541
These changes will make our SQL Editor behaves more like familiar native db clients such as Navicat and TablePlus.
FYI @Candybase @tianzhou

feat(sql-editor): optimize result display

---

backend/store/migration/dev/20230303000001##remove_idp_fields_in_principal.sql
backend/store/migration/dev/LATEST.sql

Since `idp_id` and `idp_user_info` are not used, we should remove them from the schema to avoid confusing users.
Close BYT-2708

chore: remove idp fields for principal table

---

frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
frontend/src/components/Issue/IssueTaskStatementPanel.vue
frontend/src/components/Issue/logic/common.ts
frontend/src/components/MonacoEditor/MonacoEditor.vue
frontend/src/components/MonacoEditor/sqlFormatter.ts
frontend/src/components/SyncDatabaseSchemaPrepForm.vue
frontend/src/plugins/sql-lsp/server/complete/index.ts
frontend/src/plugins/sql-lsp/server/complete/utils/common.ts
frontend/src/plugins/sql-lsp/server/complete/utils/parser-helper.ts
frontend/src/plugins/sql-lsp/server/server.ts
frontend/src/plugins/sql-lsp/types/sql.ts
frontend/src/types/sqlEditor.ts
frontend/src/utils/instance.ts
frontend/src/views/sql-editor/EditorPanel/SQLEditor.vue
frontend/src/views/sql-editor/TerminalPanel/CompactSQLEditor.vue

- Before: MYSQL -> "mysql", POSTGRES -> "postgresql", others -> "mysql"
- After: Each EngineType is mapped to a dedicated dialect type.

chore(frontend): normalize engines' languages and sql dialects

---

backend/plugin/vcs/github/github.go
backend/plugin/vcs/github/github_test.go
backend/plugin/vcs/gitlab/gitlab.go
backend/plugin/vcs/vcs.go
backend/runner/taskrun/executor.go
backend/server/webhook.go

close BYT-2695
We add this information for writing back LATEST commit to ignore redundantly GitOps issue

chore: add AuthorName and AuthorEmail for GitOps

---

frontend/src/components/Issue/IssueTaskSDLPanel.vue
frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json
frontend/src/main.ts
frontend/src/plugins/silent-request.ts

- Adjust the layout (Close BYT-2700)
- Remove the "SQL" label
- Add a tooltip to the "Schema change" tab (The Learn More link's URL might be updated while our new user docs about this are done FYI @Candybase @rebelice )
- Error handling while the SDL has syntax errors.
- Won't push notifications. But display user-readable error messages on the panel.
- Also, the "Schema change" and "Generated DML statement" tabs are disabled since they are unavailable.
- Tooltip
- Error displaying

feat(frontend): improve SDL issue display

---

frontend/src/components/RepositoryForm.vue

For DDL, it's optional. But required for SDL.
FYI @Candybase @rebelice

chore(frontend): add a required star to "Schema path template" for SDL projects

---

backend/plugin/vcs/github/github.go
backend/plugin/vcs/github/github_test.go
backend/plugin/vcs/vcs.go
backend/runner/taskrun/executor.go
backend/server/project.go
frontend/src/components/Issue/IssueActivityPanel.vue

close BYT-2689
For GitHub.com, it needs file SHA and commit ID for different APIs. Before this PR, we treated these two different things as one thing.

fix: generate correct commit link for GitHub.com

---

frontend/src/components/CreateDatabasePrepForm.vue
frontend/src/components/InstanceSelect.vue
frontend/src/utils/instance.ts
frontend/src/views/InstanceDetail.vue

- Don't list redis instances in the "Instance" selector of the "Create dialog" dialog.
- Don't show "New database" button for redis on the instance detail page.

feat(frontend): redis shouldn't have "Create database"

---

backend/server/server.go
backend/store/instance_change_history.go

- support batch create instance change history
- backfill instance change history
- fix another unfortunate mis-revert in [`cc06dfd` (#5007)](https://github.com/bytebase/bytebase/pull/5007/commits/cc06dfdff9e36b2bc7cbb9f18f4286f505232f1c#diff-9c0baf0b3b25f2377005705d5a7478204e53f0252c392597f2409ec6291ecf76L465)

feat: backfill instance change history

---

.github/workflows/backend-tests.yml

Run `golangci-lint` locally often takes up too many resources, especially trigger golangci-lint while saving in VSCode. : \\
And the default value of  [`golangci-lint --max-same-issues` is `3`](https://golangci-lint.run/usage/configuration/#issues-configuration), it is too little and will result in the need for repeated commits to pass the check.

chore(ci): show more issues of golangci-lint

---

frontend/src/components/InstanceEngineIcon.vue

fix(frontend): hide tooltip for empty engine versions

---

backend/runner/taskrun/database_create_executor.go
backend/server/issue.go

Creating an Oracle database is an elaborative/physical process, and users will usually do it themselves. We don't support it for now.

feat: disable database creation for Oracle

---

backend/server/server.go

should use info from migrationHistory

fix: stored version

---

backend/plugin/db/redis/redis.go

type information is lost because we use the universal `Cmd` to handle user inputs.
The returned values could be a map[interface{}]interface{} value which cannot be parsed by `encoding/json`. And we fall back to cmd.String() in that case.

fix: redis json marshal cannot handle map[any]any

---

backend/runner/taskrun/executor.go
backend/server/instance.go
backend/server/server.go
backend/utils/utils.go

And handle migration history well for Oracle.

chore: skip instance change backfill for schemaless or new types of databases

---

backend/legacyapi/activity.go
backend/server/activity.go
backend/store/activity.go
frontend/src/types/activity.ts
frontend/src/views/SettingWorkspaceAuditLog.vue

This pull request adds a new feature to the audit logging functionality, allowing users to list audit logs within a specified time range. With this new feature, users can easily filter audit logs by specifying a start and end time, which makes it much easier to find and review relevant audit logs.
To achieve this, we have accepted a start and end time as query parameters and returned a list of audit logs that fall within the specified time range. Additionally, we have updated the UI to allow users to enter a start and end time when viewing the audit log by using [Naive UI date picker](https://www.naiveui.com/en-US/os-theme/components/date-picker#DatePicker-Slots).
Overall, this feature adds a new level of flexibility to the audit logging functionality, making it more useful for our users.

feat(audit-log): support list audit logs in a specify time range

---

frontend/src/components/Issue/rollback/RollbackStatus.vue

chore(frontend): add a learn-more link to the "rollback statement is empty" tooltip

---

backend/plugin/db/redis/sync.go

Cloud vendors may have disabled the command to get the databases' count. We return 1 in that case.

fix: make cloud redis more robust

---

backend/server/issue.go

For MySQL, how table and database names are stored on disk and used in MySQL is affected by the [lower_case_table_names](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_lower_case_table_names) system variable.
We should use the lowercase if we find that the value of `lower_case_table_names` is `1`. Otherwise, we cannot find the database we create because we depend on the database name in the create database task.

fix(mysql): using lower case for database name if the lower case table name is 1

---

frontend/src/components/GeneralSetting/AIAugmentationSetting.vue

Close BYT-2807
WARNING: this only hides the UI display. Developers still can analyze the API key from devtools.
FYI @Candybase

chore(frontend): display OpenAI API key as sk-***

---

backend/plugin/vcs/bitbucket/bitbucket.go
backend/plugin/vcs/bitbucket/bitbucket_test.go
backend/plugin/vcs/github/github.go
backend/plugin/vcs/github/github_test.go
backend/plugin/vcs/gitlab/gitlab.go
backend/plugin/vcs/gitlab/gitlab_test.go
backend/server/oauth.go
backend/server/project.go
backend/server/server_frontend_embed.go
backend/server/server_frontend_not_embed.go

This PR fixes various problems related to OAuth:
1. Fixed a place where we pass `nil` as the token refresher, it panics when the access token is expired.
2. Use the correct format (POST form) for token refresh requests instead of JSON.
3. Remove `BB_REDIRECT_URL`, it is no longer relevant with the use of [pgrok](https://github.com/pgrok/pgrok).
---
Close https://linear.app/bytebase/issue/BYT-2809/gitops-oauth-does-not-refresh-on-token-expire

fix(oauth): correctly handle access token refresh

---

frontend/src/components/InstanceForm.vue

This PR improves the MongoDB SRV record UX.
1. Disable `port` input if the users using SRV record.
2. Clear the `port` input if the users using SRV record.

chore(mongodb): improve MongoDB SRV UX

---

backend/plugin/parser/differ/mysql/differ_test.go
backend/plugin/parser/differ/mysql/utils.go
backend/plugin/parser/utils.go
backend/plugin/parser/utils_test.go

Previously, we assume that `mysqldump` gives us the trigger statement likes
``` SQL 
CREATE DEFINER=`root`@`%` TRIGGER `tri` ...
```
But recently, we found that the mysqldump may trim the backquotes on both sides of the object name, a MySQL Server  version known to be affected is `5.7.20-log`. I haven't tried reproducing it yet, but I think this PR can handle the situation properly.

fix(parser): handle the case where there are no backquotes on both sides of the object name

---

backend/legacyapi/task.go
backend/plugin/db/oracle/migrate.go
backend/plugin/db/oracle/oracle.go
backend/runner/rollbackrun/runner.go
backend/runner/taskrun/database_create_executor.go
backend/runner/taskrun/executor.go
backend/runner/taskrun/pitr_cutover_executor.go
backend/runner/taskrun/pitr_restore_executor.go
backend/utils/utils.go
frontend/src/components/Issue/rollback/common.ts

This PR implements the feature that allows user rollback DML on Oracle instance. We get the transaction id in the Oracle data update task and store it in the rollback runner if the user turns on the `ROLLBACK` switch. And we get the undo SQL by using transaction id.
1. Our Oracle rollback DML feature depends on [Oracle Flashback Transaction Query](https://docs.oracle.com/cd/B14117_01/appdev.101/b10795/adfns_fl.htm) features. Users should **turn on the [supplemental logging](https://docs.oracle.com/database/121/SUTIL/GUID-D2DDD67C-E1CC-45A6-A2A7-198E4C142FA3.htm#SUTIL1583)**.
> **Warning**
> We use `SELECT RAWTOHEX(tx.xid) FROM v$transaction tx JOIN v$session s ON tx.ses_addr = s.saddr;` to get the transaction id, but the underlying Golang oracle driver `go-ora` may reuse the …

feat(oracle): support Oracle rollback DML

---

backend/store/migration/prod/1.15/0000##risk.sql
backend/store/migration/prod/LATEST.sql
backend/store/pg_engine_test.go

The most important part of a risk is the `expression`.
On the frontend, risks having the same level will be grouped and displayed as e.g. High risk with many expressions.
We hard code low, mid, high as 1e9, 2e9, 3e9 at the moment.

feat(schema): risk

---

backend/server/server.go

chore: reduce backfilling error level

---

frontend/src/utils/instance.ts

Oracle database creation is a heavy process. We don't support it as users will most likely do it themselves.

chore: disable new db for oracle

---

backend/store/migration/dev/20230317000000##sqlserver.sql
backend/store/migration/dev/LATEST.sql
backend/store/migration/prod/1.15/0001##drop_engine_check.sql
backend/store/migration/prod/LATEST.sql
backend/store/pg_engine_test.go

We don't want to check the schema version for introducing new database types.

chore: remove instance engine check

---

backend/plugin/parser/parser.go
backend/plugin/parser/validate_sql_for_editor.go
backend/plugin/parser/validate_sql_for_editor_test.go
backend/server/sql.go
backend/server/sql_test.go

close BYT-2820
ValidateSQLForEditor validates the SQL statement for SQL editor.
We support the following SQLs:
1. EXPLAIN statement, except EXPLAIN ANALYZE
2. SELECT statement
We also support CTE with SELECT statements, but not with DML statements
Consider that the tokenizer cannot handle the dollar-sign($), so we use pg_query_go to parse the statement.
For EXPLAIN and normal SELECT statements, we can directly use regexp to check.
For CTE, we need to parse the statement to JSON and check the JSON keys.
We validate the statement by following steps:
1. Remove all quoted text(quoted identifier, string literal) and comments from the statement.
2. Use regexp to check if the statement is a normal SELECT statement and EXPLAIN statement.
3. For CTE, use regexp to check if the statement has …

fix: disallow EXPLAIN ANAYZE and CTE for DML in SQL editor

---

backend/server/acl.go
backend/server/acl_issue_test.go
backend/server/acl_test_helper.go

We just allow workspace developer operating the issue in the following cases:
1. The creator of the issue.
2. The member of the project that the issue belongs to.

fix(BAC): avoid workspace developer operating the issue in some cases

---

frontend/src/store/modules/subscription.ts

```
export enum PlanType {
PLAN_TYPE_UNSPECIFIED = 0,
FREE = 1,
TEAM = 2,
ENTERPRISE = 3,
UNRECOGNIZED = -1,
}
```
A feature matrix item is [ boolean, boolean, boolean ] so we should use `currentPlan - 1` as the array index.
@ecmadao PTAL

fix(frontend): feature guard array index

---

frontend/src/store/modules/subscription.ts

- #5238 was incorrectly cherry-picked into release/1.15.0
- #5248 reverts #5238, and cherry-picked into release/1.15.0 via #5249 
Now we will roll forward this change again and we SHOULD NOT cherry-pick this into release/1.15.0

fix(frontend): roll forward pr 5248

---

frontend/package.json
frontend/pnpm-lock.yaml

This may solve the problem
> ERROR: failed to solve: process "/bin/sh -c pnpm install --frozen-lockfile" did not complete successfully: exit code: 1
[658](https://github.com/bytebase/bytebase/actions/runs/4542359744/jobs/8005701832#step:6:662)Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c pnpm install --frozen-lockfile" did not complete successfully: exit code: 1
> #24 0.668  ERR_PNPM_FROZEN_LOCKFILE_WITH_OUTDATED_LOCKFILE  Cannot perform a frozen installation because the lockfile needs updates

chore(frontend): upgrade npm deps

---

backend/server/acl.go

We should restore the http request body after consume it in middleware, because our API(or other milddleware) will consume it again.
Close BYT-2896.
Close BYT-2895.

fix: read twice for http request body

---

backend/plugin/advisor/catalog/test/pg_walk_through.yaml
backend/plugin/advisor/catalog/walk_through.go
backend/plugin/advisor/catalog/walk_through_for_pg.go
backend/plugin/advisor/catalog/walk_through_test.go
backend/plugin/advisor/code.go
backend/plugin/advisor/sql_review.go

close BYT-2543
On the other hand, we cannot display the error content in the pretty format

chore: get view definition when view dependence error appears

---

backend/legacyapi/task_check_run.go
backend/plugin/advisor/advisor.go
backend/plugin/advisor/sql_review.go
backend/runner/taskcheck/statement_advisor_composite_executor.go
backend/runner/taskcheck/statement_advisor_simple_executor.go

close BYT-2543
The advice will be 
```json
{
"resultList": [
{
"code": 421,
"line": 1,
"title": "Column is referenced by view",
"status": "ERROR",
"content": "Cannot drop column \"d\" in table \"public\".\"t\", it's referenced by view: \"public\".\"v2\"",
"details": "The definition of view \"public\".\"v2\" is \n SELECT t.a,\n    t.b,\n    t.d\n   FROM t;\n\n",
"namespace": "bb.advisor"
}
]
}
```
FYI @boojack

chore: add details member for advice

---

backend/runner/approval/runner.go

- should respect risk.Active
- convert db.Type to string type otherwise cel-go will complain

fix: approval runner

---

backend/server/task.go
backend/server/webhook.go

- retry finding if task status is patched to pending approval
- retry finding if task statement is patched and the task status is pending approval

fix: retry finding if task status is patched to pending approval

---

backend/plugin/db/redshift/dump.go
backend/plugin/db/redshift/migrate.go
backend/plugin/db/redshift/redshift.go
backend/plugin/db/redshift/role.go
backend/plugin/db/redshift/sync.go
backend/plugin/db/redshift/sync_test.go
backend/plugin/parser/parser.go
backend/plugin/parser/utils.go
backend/runner/anomaly/scanner.go
backend/runner/taskrun/database_create_executor.go
backend/server/database.go
backend/server/issue.go
backend/server/server.go
backend/server/sql.go
backend/store/data_source.go
frontend/src/components/CreateDatabasePrepForm.vue
frontend/src/components/DatabaseBackupPanel.vue
frontend/src/components/InstanceForm.vue
frontend/src/types/common.ts
frontend/src/types/instance.ts
frontend/src/utils/instance.ts

This PR supports user add Redshift in Bytebase, and supports the following features:
- Create database
- DML/DDL issues
- SQL Editor Readonly/Admin mode
Unfortunately, I do not support `dump schema` in this PR because I found that we use [pg_dump 15 which doesn't support PostgreSQL 8.0 anymore](https://sourcegraph.com/github.com/postgres/postgres@REL_15_0/-/blob/src/bin/pg_dump/pg_dumpall.c?L1643)(which pg_dump 14 supports). But when users need it, we can easily embed pg_dump 14.

feat(backend): support add redshift in backend

---

frontend/src/components/CustomApproval/Settings/components/CustomApproval/RulesPanel/RuleSelect.vue
frontend/src/components/CustomApproval/Settings/components/CustomApproval/RulesPanel/RulesSection.vue
frontend/src/components/CustomApproval/Settings/components/common/ExprEditor/components/common.ts

- make the flow selector filterable (Close BYT-2910)
- use `environment.resource_id` as the options' display label for environment_id dropdowns (Close BYT-2920)
- use edit icon for the approval flow popup button (Close BYT-2923)
- keep the order stable (by level desc) while changing the level filters (Close BYT-2922)

feat(frontend): minor optimizations for risk center and custom approval

---

frontend/src/components/RepositoryForm.vue

Fixes BYT-2875
No "SQL Review" section for Bitbucket Cloud:

fix(bbc): hide SQL Review section in repo settings

---

backend/plugin/db/snowflake/dump.go
backend/plugin/db/snowflake/migrate.go
backend/plugin/db/snowflake/snowflake.go
backend/plugin/db/snowflake/sync.go
frontend/src/components/CreateDataSourceExample.vue

* chore: remove the use ACCOUNTADMIN role before dump database
* chore: update the SQL statement to get the shared databases
* chore: remove the use ACCOUNTADMIN role before get database
* chore: remove use ACCOUNTADMIN before sync instance and database
* chore: update the privileges we use for snowflake
* chore: update the css for connection info hint
* chore: update the connection info hint for non-enterprise edition user
* chore: update the connection info hint for non-enterprise edition user

chore(snowflake): update the privileges we need for Snowflake (#5356)

---

frontend/src/components/EnvironmentForm.vue
frontend/src/components/EnvironmentForm/AssigneeGroupEditor.vue
frontend/src/components/Issue/IssueBanner.vue
frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json

Though "rollout" is noun and "roll out" is verb, let's still use word "rollout" consistently because it looks in a nicer form and it's commonly used in other tech products.
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

chore: use word rollout

---

backend/migrator/migrator.go

Some previous bytebase instances may not have instance_change_history table yet prior to upgrades.

chore: use environment table to determine schema initialization

---

backend/store/instance_change_history.go
backend/utils/utils.go

We should not check and enforce the sequencing in the backend engine but warn users in the frontend instead.

chore: disable schema version checks during migration

---

backend/api/v1/database_service.go

close BYT-2459
we can use `-` in the project id, so fix the regexp.
FYI @LiuJi-Jim

fix: get projects id

---

backend/plugin/db/pg/pg.go

We no longer create a separate "bytebase" database to store migration history.

chore: remove “bytebase” as one of the PG guess dbs

---

frontend/src/components/SlowQuery/Panel/LogTable.vue

Making it easier to distinguish databases with the same names.

feat(frontend): add instance column to slow query log table

---

frontend/src/components/Issue/BatchIssueActions.vue
frontend/src/components/Issue/IssueSidebar.vue
frontend/src/components/Issue/logic/assignee.ts
frontend/src/components/Issue/logic/transition.ts
frontend/src/plugins/issue/logic/initialize/assignee.ts
frontend/src/types/issue.ts

Close BYT-2924
See also #5520 
- Roll out (including cancel, mark as done aka skip and retry)
- only the assignee
- Re-assign (to another capable assignee)
- only the current assignee
- nit: applicable to the issue creator when the current assignee is SYSTEM_BOT
- Resolve/Cancel/Reopen the issue
- the current assignee and issue creator.

feat(frontend): update task and issue status transition limitations for assignee

---

frontend/src/bbkit/BBGrid/BBGrid.vue
frontend/src/components/DatabaseSlowQueryPanel.vue
frontend/src/components/ProjectSlowQueryPanel.vue
frontend/src/components/SlowQuery/Panel/DetailPanel.vue
frontend/src/components/SlowQuery/Panel/LogFilter.vue
frontend/src/components/SlowQuery/Panel/LogTable.vue
frontend/src/components/SlowQuery/Panel/SlowQueryPanel.vue
frontend/src/components/SlowQuery/Panel/types.ts
frontend/src/components/v2/Model/ProjectName.vue
frontend/src/components/v2/Model/index.ts
frontend/src/components/v2/TabFilter/EnvironmentTabFilter.vue
frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/review.ts
frontend/src/store/modules/slowQueryPolicy.ts

- Hide instances without slow query log enabled. (Close BYT-2998)
- Detail panel improvements (Close BYT-2989)
- Add **SQL Statement** column.
- Expandable detail rows to display full SQL detail.
- Improvements for log table and log filter.
- Update log filters.
- Adjust the slow query log table's column layout according to different usage
- project slow query log table: hide **Project** column
- database slow query log table: hide **Project**, **Environment**, **Instance** and **Database** columns
- FYI @Candybase 
- Adjust the order of Environment filters. The higher ones to the left.

feat(frontend): slow query improvements 2

---

backend/migrator/migration/prod/1.16/0002##delete_email_duplicated_principal.sql

This PR will disable all triggers then enable them after migration finished to prevent the `updated_ts` will be updated by trigger.

fix: prevent updated_ts will be updated by trigger

---

frontend/src/components/Issue/table/WaitingForMyApprovalIssueTable.vue
frontend/src/components/ProjectOverviewPanel.vue
frontend/src/views/Home.vue

To save the loading cost and save the performance.
- Use `<PagedIssueTable>` for "Waiting approval" section
- The page size is set to 20. Sometimes none of the 20 issues matches the condition. So when we click "Load more" we may see nothing new.

chore(frontend): don't load too much issues

---

frontend/src/components/Issue/IssueTaskStatementPanel.vue

chore(frontend): set default visibility of uploaded SQL as sheet to "PROJECT"

---

backend/plugin/db/util/driverutil.go

We use sql.Query() for executing admin statements. However, clickhouse will throw bad connection error for non-SELECT statements. We should ignore its error for now.

fix: ignore errors from clickhouse admin query

---

backend/server/project.go

Principals with custom roles can list the projects that they are in.

fix: custom roles can see projects

---

frontend/src/components/CreateDatabasePrepForm.vue
frontend/src/components/InstanceUserSelect.vue
frontend/src/types/InstanceUser.ts

Close BYT-2527
Will only hide them when creating databases

feat(frontend): filter internal RDS users when creating databases in PG

---

frontend/src/locales/en-US.json
frontend/src/locales/zh-CN.json
frontend/src/views/SyncDatabaseSchema/SelectTargetDatabasesView.vue
frontend/src/views/SyncDatabaseSchema/index.vue

* use latest schema when database has no migration history;
* add a loading overlay;

chore: use latest schema when database has no migration history

---

frontend/src/components/SlowQuery/Panel/LogFilter.vue

We don't support manual timezone selection now. So it's good to display the local timezone explicitly to inform user the information.

chore(frontend): display timezone while filtering slow query time

---

backend/legacyapi/task.go
backend/runner/taskrun/database_create_executor.go
backend/runner/taskrun/schema_update_ghost_sync_executor.go
backend/runner/taskrun/schema_update_sdl_executor.go

We want to completely rely on sheet.Statement to reduce unnecessary duplicates.
This PR adds sheet.ID to task payload and uses sheet statement.

chore: replace payload.Statement with sheet.Statement

---

frontend/src/components/SlowQuery/Panel/DetailPanel.vue
frontend/src/components/SlowQuery/Panel/LogTable.vue
frontend/src/store/modules/slowQuery.ts

- Adjust column widths and column gaps
- Set decimal precision to 2 digits (Close BYT-3072)

feat(frontend): minor style tuning for slow query log table

---

frontend/src/components/Issue/logic/base.ts
frontend/src/views/SyncDatabaseSchema/index.vue

In sync schema, we should allow different statements in tenant mode tasks. The easiest way is treat it as normal project.

chore: set issue mode to normal for tenant mode project in sync schema

---

backend/legacyapi/activity.go
backend/runner/taskrun/scheduler.go
backend/utils/utils.go

Reuse `ActivityPipelineTaskStatementUpdatePayload` to record task.SheetID updated activities.

feat: add sheet id to task statement update acitivity payload

---

backend/plugin/db/mysql/sync.go

The MySQL function `convert_tz` requires loading the time zone table into MySQL.
So we convert time zone in backend instead of MySQL server
References:
- https://stackoverflow.com/questions/14454304/convert-tz-returns-null

fix: convert time zone in backend instead of MySQL server

---

backend/migrator/demo/reset.sql
backend/migrator/migrator.go

instance_change_history is the table recording the migration history. It's the metadata table instead of the data table.
We need to retain it, otherwise the backfillHIstory will attempt to find the deleted migration_history table
First run success
Because the instance_change_history is reset and has no record, we will attempt to query the deleted table and fail to start

fix: should not reset instance_change_history in demo reset

---

backend/plugin/db/driver.go
backend/server/webhook.go
backend/store/project_member.go
backend/tests/schema_update_test.go
backend/tests/tenant_test.go

Append a type suffix to the schema version. This will create two different tasks with different version for two files from GitOps.

chore: append a suffix to the schema version string

---

frontend/src/components/Breadcrumb.vue
frontend/src/components/Project/ProjectSetting/ProjectGeneralSettingPanel.vue
frontend/src/components/Project/ProjectSetting/ProjectMemberTable/PrincipalTable.vue
frontend/src/components/Project/ProjectSetting/ProjectMemberTable/ProjectMemberTable.vue
frontend/src/components/ProjectMemberPanel.vue
frontend/src/components/ProjectSettingPanel.vue
frontend/src/router/index.ts
frontend/src/utils/v1/project.ts
frontend/src/views/ProjectDetail.vue

- Fetch v1 project in routers
- Use v1 project in project settings
- Use v1 project in breadcrumb

refactor(frontend): use v1 API in project settings

---

frontend/src/components/Issue/IssueTaskStatementPanel.vue

I see that sometimes the auto-wrap of MonacoEditor will fire a little bit later and it probably breaks our auto-height adjustment logic.
So I postpone the timing of auto-height. This will fix BYT-3148 (hopefully).

fix(frontend): auto adjust editor height later

---

frontend/src/components/ProvideDashboardContext.vue

We are using implicit data dependencies somewhere that imagine a project entity is pre-fetched. But we are not after shipping to v1 partly.
So we pre-fetch the project list globally for legacy compatibility. After shipping to project v1 totally, we should remove this.

chore(frontend): legacy project API compatibility

---

frontend/src/bbkit/BBCheckbox.vue

It is pretty counter-intuitive to have the default value being `true`.

chore: set BBCheckbox default value to false

---

frontend/src/components/MonacoEditor/MonacoEditor.vue
frontend/src/plugins/sql-lsp/client/useLanguageClient.ts
frontend/src/plugins/sql-lsp/server/complete/index.ts
frontend/src/plugins/sql-lsp/server/server.ts
frontend/src/plugins/sql-lsp/types/index.ts
frontend/src/views/sql-editor/EditorPanel/SQLEditor.vue
frontend/src/views/sql-editor/TerminalPanel/CompactSQLEditor.vue

- Show database suggestions only when connected to instance scope.
- Add database name prefix to table suggestions only when connected to instance scope.
Close BYT-2782

fix(sql-editor): restrict instance/database connection scope to provide different suggestion items

---

backend/store/sheet.go

`octet_length(string)` is using to get the number of bytes in binary string.
reference: https://www.postgresql.org/docs/9.0/functions-binarystring.html

fix: use length instead of octet_length

---

frontend/src/components/SchemaEditor/DatabaseTree.vue
frontend/src/store/modules/schemaEditor.ts

Close BYT-3150
Don't expand the first database to prevent rendering too many nodes causing the page to hang out.

chore(schema-editor): don't expand the first database

---

frontend/src/components/v2/Select/ProjectSelect.vue

Remove the filter by user role because we already did it in [`projectV1Store.getProjectListByUser`](https://github.com/bytebase/bytebase/blob/main/frontend/src/store/modules/v1/project.ts#L51).

chore: update v2 project select

---

frontend/src/components/ProjectVersionControlPanel.vue
frontend/src/components/RepositoryPanel.vue
frontend/src/components/RepositorySetupWizard.vue
frontend/src/store/modules/project.ts
frontend/src/views/ProjectDetail.vue

It's awful to use mixed new and legacy APIs but it just works by now.
FYI @h3n4l 
close BYT-3209

refactor(frontend): use V1 api to patch project's schema change type and workflow type

---

frontend/src/components/ProvideDashboardContext.vue
frontend/src/store/modules/v1/project.ts

- call `fetchProjectList` one time when the page is initialized.
- `useProjectV1List()` will now default to be lazy.

fix(frontend): avoid calling ListProjects too many times

---

frontend/src/components/QuickActionPanel.vue

`ProjectV1.name` already has `/projects` prefix.

chore: fix project name

---

backend/api/v1/database_service.go

We consider that is safe to use the `uid` logic branch if `{database}` is pure digits, since pure digits won't be a valid resource name.

chore(backend): support uid for DatabaseService.GetDatabase

---

backend/legacyapi/task_check_run.go
backend/runner/taskcheck/statement_affected_rows_report_executor.go
backend/runner/taskcheck/statement_type_report_executor.go

There are some common processes in `backend/runner/taskcheck/statement_affected_rows_report_executor.go` so I refactored this file when adding support for OceanBase explain response.

feat: add task check for OceanBase

---

frontend/src/components/CustomApproval/Settings/components/RiskCenter/RiskDialog/RuleTemplateTable.vue

chore(frontend): don't break word

---

frontend/src/components/DatabaseGroup/common/ExprEditor/Condition.vue
frontend/src/components/DatabaseGroup/common/ExprEditor/ConditionGroup.vue
frontend/src/components/DatabaseGroup/common/ExprEditor/ExprEditor.vue
frontend/src/components/DatabaseGroup/common/ExprEditor/components/FactorSelect.vue
frontend/src/components/DatabaseGroup/common/ExprEditor/components/OperatorSelect.vue
frontend/src/components/DatabaseGroup/common/ExprEditor/components/StringInput.vue
frontend/src/components/DatabaseGroup/common/ExprEditor/components/ValueInput.vue
frontend/src/components/DatabaseGroup/common/ExprEditor/components/index.ts
frontend/src/components/DatabaseGroup/common/ExprEditor/context.ts
frontend/src/components/DatabaseGroup/common/ExprEditor/factor.ts
frontend/src/components/DatabaseGroup/common/ExprEditor/index.ts
frontend/src/components/DatabaseGroup/common/utils.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/plugins/cel/types/factor.ts
frontend/src/plugins/cel/types/operator.ts

A simple expr editor was copied from the risk center, containing factors `database-name`/`table-name` and operators `==`/`startWith`.
https://github.com/bytebase/bytebase/assets/24653555/2630b569-7ebf-4904-a914-334d58a51b36

feat: expr editor for database group

---

backend/store/principal.go

When email is updated, we need to invalid the project policy cache because the policy kept the email.

chore: clear project policy cache

---

frontend/package.json

And then, the backend engineers can modify the `scripts/.air.toml` to develop the backend with hot reloading!
**NOTE: DO NOT FORGET TO RUN `pnpm dev-embed` UNDER THE `frontend/` FIRST!**
THANKS @rebelice !!

chore: allow backend engineer dev with hot reloading easily

---

backend/server/issue.go

```go
fmt.Sprintf("-%03d-%03d-%03d", migrationDetailIdx, schemaGroupIdx, matchIdx)
```
However, according to the current design, migrationDetailIdx, schemaGroupIdx should always be 0.

fix: add different suffixes to the schema version of different tasks of a database

---

frontend/src/types/oauth.ts
frontend/src/utils/sso.ts
frontend/src/views/OAuthCallback.vue
frontend/src/views/auth/Signin.vue

- Why we don't use `redirect_uri`?
- 
Some OAuth/OIDC providers (like Google) strict the `redirect_uri` to exactly equals what the administrator has configured in Google API Console. So we cannot push parameters dynamically to `redirect_uri`. 
That's why we use `state`

refactor(oauth/oidc): use state param instead of session storage

---

backend/plugin/advisor/snowflake/advisor_column_maximum_varchar_length.go
backend/plugin/advisor/snowflake/snowflake_rules_test.go
backend/plugin/advisor/snowflake/test/column_maximum_varchar_length.yaml

> If no length is specified, the default is the maximum allowed length (16,777,216).
https://docs.snowflake.com/en/sql-reference/data-types-text

fix(sql-review): handle the default varchar length of snowflake

---

backend/bin/bb/cmd/migrate.go
backend/migrator/migrator.go
backend/migrator/migrator_test.go
backend/plugin/advisor/utils_for_tests.go
backend/plugin/db/clickhouse/clickhouse.go
backend/plugin/db/driver.go
backend/plugin/db/mongodb/mongodb.go
backend/plugin/db/mssql/mssql.go
backend/plugin/db/mysql/mysql.go
backend/plugin/db/oracle/oracle.go
backend/plugin/db/pg/pg.go
backend/plugin/db/redis/redis.go
backend/plugin/db/redshift/redshift.go
backend/plugin/db/snowflake/snowflake.go
backend/plugin/db/spanner/spanner.go
backend/plugin/db/sqlite/sqlite.go
backend/resources/postgres/postgres.go
backend/runner/taskrun/database_create_executor.go
backend/runner/taskrun/executor.go
backend/runner/taskrun/pitr_cutover_executor.go
backend/runner/taskrun/pitr_restore_executor.go
backend/runner/taskrun/schema_update_ghost_cutover_executor.go
backend/store/pg_engine.go
backend/tests/rollback_test.go
backend/utils/utils.go

Previously, we do the following
1) create a connection to get connection ID and binlog;
2) dump schema using a different connection;
3) use the connection from the 1st step to execute migration script.
If step 2) takes long time, the execution in 3rd step will fail because the connection is already closed.

chore: don't pre-create the connection for mysql migration

---

frontend/src/components/DatabaseGroup/DatabaseGroupSelect.vue

Before 
After 
@d-bytebase up to u to decide whether to backport this to 2.3.0 . It's harmless but quite confusing and annoying

fix(frontend): use correct field to display database group selector

---

frontend/src/components/Issue/table/IssueTable.vue
frontend/src/components/ProjectOverviewPanel.vue

* Remove Status title, the icon is obvious and the column is too narrow
* Merge the project into the name column
* Fix the waiting approval issue list in project view
Before
After
Before
After

chore: optimize issue table UX

---

backend/bin/server/cmd/profile.go
backend/bin/server/cmd/root.go
backend/component/config/profile.go
backend/server/server.go
backend/tests/tests.go

We can now set the `external-url` in the UI. We no longer need to include `external-url` in the cmd options. The pain is over.

feat(breaking-change): deprecate external url cli option

---

frontend/src/utils/workspaceApprovalSetting.ts

Since we've migrated the expressions from binary expression trees to string source codes. It is not guarded that the a "and and and and ..." or "or or or or or ..." tree is strictly aligned to the left or to the right sub-tree.
It's hard and even impossible to convert a complex tree to a perfect, clear "and and and ..." or "or or or ..." array (aka. Condition Group in Bytebase). So we loosen the workspace approval setting resolving procedure.

chore:(frontend) loosen workspace approval setting resolving

---

frontend/src/components/Issue/panel/RequestQueryPanel/SelectDatabaseResourceForm/index.vue
frontend/src/components/Issue/panel/RequestQueryPanel/index.vue
frontend/src/composables/useExecuteSQL.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/v1/sql.ts
frontend/src/types/v1/sql.ts
frontend/src/views/sql-editor/EditorCommon/ResultView/RequestQueryButton.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue

https://github.com/bytebase/bytebase/assets/2749742/e456e00a-d695-4dd1-b6ce-fe04f9675035
We don't actually know which schema/table is denied to access from the frontend. So we can just pre-set the database when opening the panel.
Close BYT-3449

feat(sql-editor): shortcut to request access when ACCESS_DENIED

---

.github/workflows/backend-tests.yml
.github/workflows/build-artifacts-and-draft-release.yml
README.md
scripts/.goreleaser-for-darwin.yaml
scripts/.goreleaser-for-linux.yaml
scripts/Dockerfile
scripts/Dockerfile.bb
scripts/Dockerfile.render-demo
scripts/Dockerfile.sql-service
scripts/build_bytebase.sh

Reverts bytebase/bytebase#6776
This may cause:

fix: Revert "chore: go 1.20.5"

---

frontend/src/components/Issue/IssueTaskStatementPanel.vue
frontend/src/components/misc/UploadProgressButton.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

- An oversized sheet can be overridden by "upload" another SQL file.
- If the newly updated SQL file is NOT oversized, the sheet will be UI-editable again.
Close BYT-3457

feat(frontend): allow to upload and override oversized sheets

---

frontend/src/components/v2/Model/Instance/InstanceV1Table/InstanceV1Table.vue
frontend/src/views/InstanceDashboard.vue

Also use "Y" instead of literal "Assigned" to avoid i18n translation

feat: hide license column for FREE plan

---

backend/migrator/migration/prod/1.0/0001##initial_data.sql
backend/migrator/migration/prod/LATEST_DATA.sql
frontend/src/store/modules/v1/policy.ts

* The default policy should be the one without extra control
* Also change the seed environment data to use the policy without requiring paid features. Otherwise, user will immediately see the subscription banner, which is bad for 1st time impression
Fix BYT-3506

feat: automatic rollout should be the default rollout policy

---

frontend/src/layouts/BodyLayout.vue

They use different font size and co-locating them together looks bad
Before
After

chore: plan and version should align left/right respectively

---

backend/migrator/migrator.go
backend/store/instance_change_history.go

The new version of migrator should not rely on the sheet_id if it hasn't yet exist in the old version of schema yet.

fix: sheet_id doesn't exist in change history table

---

frontend/src/components/MarkdownEditor.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

* Use `Write` instead of `Editor` (follow GitHub)
* Insert SQL snippet should not introduce new line (follow GitHub)
* Shorten the space between Write and Preview button
* Use text color instead of bold font to highlight selection.

chore: minor markdown editor style tweak

---

frontend/src/components/TenantDatabaseTable/DeployDatabaseTable.vue

Center in the big box. Left to the small box.
Close BYT-3537

chore(frontend): tenant deployment matrix layout improvement

---

backend/api/v1/sql_service.go
frontend/src/utils/v1/instance.ts

Users have to setup read-only data source to make sure queries to be immutable.

chore: allow Mongo and Redis to query in SQL Editor

---

frontend/src/components/UpgradeSubscriptionButton.vue
frontend/src/views/SettingWorkspaceAccessControl.vue

Keep it has a same behavior with subscription banner.

chore: update `Upgrade trial` button in access control setting

---

frontend/src/components/ProjectMember/ProjectMemberTable/ProjectMemberRolePanel.vue

chore: update project role drawer width

---

frontend/src/store/modules/v1/activity.ts

We are mixing results from two requests (container=issue_id and container=pipeline_id), so it's difficult to implement pagination or "load more" features.
This fix is somehow ugly but it works.
Close BYT-3526

chore(frontend): issue activity section pageSize

---

backend/plugin/idp/ldap/ldap.go
backend/plugin/idp/ldap/ldap_test.go
go.mod
go.sum

This PR implements the BindDN-based LDAP authentication client, which works as follows:
1. Use a bind account (aka. BindDN) to authenticate the connection, in the OAuth world, it's like using the client ID and client secret, but it acts as a service account in LDAP.
1. Search for the user (via its username) and other attributes (i.e. identifier, display name and email).
1. Verify the user's password.
For the security protocol, although the LDAP RFC allows unencrypted connections, any reasonable service would require either LDAPS (SSL) or StartTLS (TLS), so the unencrypted option is deliberately disallowed.
1. Set up a bind account (`system`) and a regular account (`alice`) on jumpcloud.com
2. Used the following program to test:
```go
package main
import (
"fmt"
"log" …
```

feat(idp): add BindDN-based LDAP authentication client

---

backend/resources/postgres/postgres.go

Followup of #7064. Though the bug exists before that.
Symptom

fix: recursively chown of all created intermediate directory during initdb

---

frontend/src/components/InstanceForm/InstanceForm.vue
frontend/src/components/InstanceForm/OracleSyncModeInput.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

- Wording changes
- Default value to `schemaTenantMode=false` aka "Manage based on database (supports CDB and non-CDB mode)"
Close BYT-3612

chore(frontend): wording and default value for Oracle schema tenant mode

---

go.mod
go.sum

There are 1 security vulnerabilities found in nhooyr.io/websocket v1.8.6
- [MPS-2022-13514](https://www.oscs1024.com/hd/MPS-2022-13514)
Upgrade nhooyr.io/websocket from v1.8.6 to 1.8.7 for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS

fix(sec): upgrade nhooyr.io/websocket to 1.8.7

---

frontend/src/views/sql-editor/EditorCommon/AdminModeButton.vue
frontend/src/views/sql-editor/EditorCommon/EditorAction.vue
frontend/src/views/sql-editor/SQLEditorPage.vue
frontend/src/views/sql-editor/TabList/TabItem/TabItem.vue
frontend/src/views/sql-editor/TabList/TabList.vue

Before
After
1. Add top margin above the tab
2. Make choose sheet button bigger
3. Make toolbar buttons smaller

feat: optimize SQL Editor tab and toolbar button

---

backend/migrator/migration/dev/LATEST.sql
backend/migrator/migration/prod/2.6/0000##task_run_remove_useless_update_status.sql
backend/migrator/migration/prod/LATEST.sql
backend/migrator/migrator_test.go
backend/store/task.go
backend/store/task_run.go

Remove `type`,`comment`,`payload` from `task_run` table.
Update `task_run.status` constraint.

feat: remove task run useless columns

---

frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue

chore: condense database tree node in sql editor

---

frontend/src/bbkit/BBModal.vue

fix: bb modal max width

---

frontend/src/bbkit/BBOutline.vue
frontend/src/components/DatabaseDetail/Settings/DatabaseSettingsPanel.vue
frontend/src/components/DatabaseListSidePanel.vue
frontend/src/store/modules/tab.ts
frontend/src/views/sql-editor/AsidePanel/AsidePanel.vue
frontend/src/views/sql-editor/AsidePanel/SheetList/SheetList.vue

- Condense SQL Editor sheet list spacing
- Condense database list spacing in the dashboard sidebar
- Switch the tab to "database" after adding a new sheet (because users need to select a database to continue editing)
- Fix database list grouping in the database sidebar
Close BYT-3705

chore: ui update

---

frontend/src/views/SyncDatabaseSchema/DatabaseSchemaSelector.vue

Close BYT-3710
Fix https://github.com/bytebase/bytebase/commit/66f92960915540392601403190c5bb86868cd76f
We should show this button only if users have the sync schema feature.
Related background https://linear.app/bytebase/issue/BYT-3541/the-dialog-box-should-not-be-displayed-when-choosing-a-database
FYI @boojack

fix: sync schema show more button

---

frontend/src/components/IdentityProviderCreateForm.vue

This mapping field is required but not visually informed like other required fields.

fix(idp): display `*` next to field mapping identifier

---

backend/api/v1/idp_service.go

Minor fix, no need to call the same method 6 times when we can just call it once.

chore(oidc): reduce `GetOidcConfig` calls

---

backend/api/v1/auth_service.go
frontend/src/views/auth/Signin.vue

This PR updates the sign-in UI to provide LDAP as a sign-in option when configured.
Because the LDAP authentication flow does not involve redirecting users to the IdP's site, we need to provide the input boxes for username and password similar to standard sign-in.
**What UI looks like when no IdP is configured:**
(I made some attempts to hide the "Standard" text but did not succeed)
**Demo of both a failure and success sign-in with LDAP:**
https://github.com/bytebase/bytebase/assets/2946214/071d619c-9901-4a25-920b-562b5d173142
Used JumpCloud as the LDAP server.
---
Part of https://linear.app/bytebase/issue/BYT-3128/support-ldap-in-sso

feat(sso): support login through LDAP

---

frontend/src/components/DatabaseOverviewPanel.vue
frontend/src/components/FeatureGuard/FeatureBadge.vue
frontend/src/components/IssueV1/logic/assignee.ts
frontend/src/components/TableTable.vue
frontend/src/views/IssueDetailV1.vue
frontend/src/views/SettingWorkspaceSensitiveData.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable.vue

Create DB and restore/PITR issues are not created via "preview" but created directly via create issue API endpoint.
Like the issue detail page, we added a compatibility layer to hide new things behind `--development-use-v2-scheduler`
- WITH `--development-use-v2-scheduler`, these issues will be created via the new V1 `IssueService.CreateIssue` API. And they can be displayed ONLY via the new issue UI.
- WITHOUT `--development-use-v2-scheduler`, these issues will be create via the legacy `[POST] /api/issue` API. They will be legacy issues in the future. And they can be displayed BOTH via the new and the old UI. But will be READONLY via new UI.

feat(frontend): migrate create db and PITR issue creation to v1 API with a compatibility layer

---

frontend/src/components/SlowQuery/Settings/SlowQuerySettings.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

For PG, we no longer require to enable pg_stat_statements on all databases

chore: adjust slow query description wording

---

frontend/src/components/RepositoryForm.vue
frontend/src/views/SettingWorkspaceSQLReview.vue

It's available in all plans. Also fix the vcs-sql-review title

fix: sql review does not require instance license binding

---

frontend/src/views/sql-editor/TabList/TabItem/Suffix.vue

chore: make sql editor tab unsaved icon obvious

---

frontend/src/components/InstanceForm/DataSourceSection/DataSourceTabs.vue

fix(frontend): Deleting read-only data source does not update the tab if there are >=3 data sources

---

frontend/src/components/SQLReview/components/RuleEngineIcons.vue

fix(frontend): SQL review rule table engine icon list

---

frontend/src/views/sql-editor/AsidePanel/SchemaPanel/DatabaseSchema.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPanel/TableSchema.vue

chore(sql-editor): tighten the gaps in schema panel

---

backend/runner/approval/runner.go

Return 0 and an unknown risk source if we cannot conclude the risk source. What would be an error before will be a nil approval template now.

chore: make approval finder more tolerant

---

frontend/src/components/Issue/TaskRunTable.vue

#7352 removed taskRun.Status and the server always returns "bb.task.general". However, this will cause errors if the task type is "bb.task.database.create". Fortunately, we can presume that taskRun.Type equals task.Type and use task.Type instead.
Close BYT-3770

fix: legacy task run table

---

backend/runner/taskrun/scheduler.go
backend/runner/taskrun/schedulerv2.go

database can be nil if e.g. database.SyncStatus = NOT_FOUND.

fix: check nil database in scheduler

---

frontend/src/bbkit/BBTabFilter.vue

chore: update BBTabFilter padding

---

frontend/src/components/v2/Select/ProjectSelect.vue

chore: update unassigned i18n in project selector

---

frontend/src/assets/css/tailwind.css

chore: update radio set row style

---

frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
frontend/src/components/IssueV1/logic/index.ts
frontend/src/components/IssueV1/logic/legacy-issue-compatibility.ts

If an issue has no plan, which means it's a legacy issue, we will fallback to use legacy task patch API to update statements.

feat(frontend): use legacy task patch API to update statement for legacy issues in new UI

---

frontend/src/views/sql-editor/AsidePanel/QueryHistoryContainer.vue

chore: reduce SQL Editor history size to accommodate more entries 

---

frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/views/SheetDashboard.vue
frontend/src/views/sql-editor/AsidePanel/AsidePanel.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable.vue
frontend/src/views/sql-editor/Sheet/SheetTable/Dropdown.vue
frontend/src/views/sql-editor/Sheet/common/Dropdown.vue
frontend/src/views/sql-editor/SheetPanel/SheetPanel.vue

* Also swap the order of `shared` and `starred`.
* Use a small drop shadow for result table header, a little bit subtle shadow is enough to distinguish the boarder while scrolling.
Before
After

chore: consolidate sheet wording

---

frontend/src/views/sql-editor/EditorCommon/ConnectionPathBar.vue

* Revert the prod alert style change in https://github.com/bytebase/bytebase/pull/7659. As I realize the original height just aligns with the admin mode top border perfectly.
* Remove the bottom rounded corner to look sharper.
Before
After

chore: revert the production alert style

---

frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckDetail.vue

Will display `error` field as the content when the status is `FAILED(3)` or `CANCELED(4)`

chore(frontend): display failed or canceled plan check runs in CI/CD UI

---

frontend/src/components/EnvironmentSelect.vue
frontend/src/components/IssueV1/components/StageSection/StageInfo/DatabaseInfo.vue
frontend/src/components/v2/Model/EnvironmentV1Name.vue
frontend/src/components/v2/Model/Instance/InstanceV1Name.vue

database environment same to instance environment
database environment differ from instance environment

chore(frontend): improve database info display in CICD UI

---

frontend/src/components/IssueV1/components/ActivitySection/ActivityList.vue

TODO: change to v1 issue and deprecate the legacy store.

chore: bring back the legacy issue list for markdown editor

---

frontend/src/components/IssueV1/components/ActivitySection/Activity/ActionIcon.vue
frontend/src/components/IssueV1/components/ActivitySection/Activity/ActionSentence.vue
frontend/src/components/IssueV1/components/ActivitySection/Activity/ActivityItem.vue
frontend/src/types/activity.ts
frontend/src/types/pipeline/task.ts

"SKIP" is a task status change rather than a task-run status change, so it's still not implemented.

feat(frontend): display task run status change activity in CI/CD UI

---

frontend/src/layouts/SQLEditorLayout.vue
frontend/src/views/sql-editor/SQLEditorPage.vue

Save the mode into the local storage. The mode won't be changed even if users remove the query unless they manually use the BUNDLED in the query.

fix: mode changed after refreshed

---

backend/plugin/parser/sql/differ/mysql/differ.go

We introduce `getDiffView` to handle the view dependency likes `mysqldump` does. Getting the field list of the `CreateViewStmt` is the major task:
We only handle the simple select ast node previously, it will cause panic if meeting other select clause ast node type. We do not have bandwidth to handle other select clause right now, but we can return error instead of panic to avoid cannot boot Bytebase.

chore: return error if the select clause in create view statement is not a select ast node

---

backend/api/v1/common.go
backend/api/v1/setting_service.go
backend/legacyapi/setting.go
frontend/src/types/proto/store/setting.ts
frontend/src/types/proto/v1/setting_service.ts
proto/gen/grpc-doc/store/README.md
proto/gen/grpc-doc/v1/README.md
proto/generated-go/store/setting.pb.go
proto/generated-go/v1/setting_service.pb.go
proto/store/setting.proto
proto/v1/setting_service.proto

BTW, using uuid format for category item instead of custom id.

feat(advanced-masking-policy): crud for semantic category setting

---

backend/api/v1/sql_service.go
backend/plugin/db/driver.go
backend/plugin/db/util/driverutil_test.go
backend/plugin/db/util/mask_sensitive_data.go
backend/plugin/db/util/mask_sensitive_data_mysql.go

We need to add the `maskingLevel` and `maskingAlgorithm` in database schema, I do not want to add that two field duplicately in `Database.SchemaList.TableList` and `Database.TableList`.

refactor: move the MySQL to use schemaList instead of tableList in databaseSchema

---

frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/bbkit/BBAvatar.vue
frontend/src/components/ActivityTable/ActivityTable.vue
frontend/src/components/Issue/review/CurrentApprover.vue
frontend/src/components/Issue/table/IssueTable.vue
frontend/src/components/PrincipalAvatar.vue
frontend/src/components/User/UserAvatar.vue

- Display name improvements, with priority as
1. First Chinese character
2. At most the first 2 letters in email
Fallback if email is invalid (won't happen if works as expected)
1. The first and the last initial letter in title
2. The first initial letter in title
- Bytebase (systembot) will always show "BB"
- Bytebase (systembot) will always use the branding color
Close BYT-3574

chore(frontend): avatar component improvements

---

frontend/src/utils/issue/cel.ts

We still keep "\_=\_" operator above for legacy data.

fix: handle row limit

---

backend/api/v1/common.go
backend/api/v1/sql_service.go
backend/api/v1/sql_service_test.go
backend/common/convert.go
backend/plugin/db/driver.go

`evalMaskingLevelOfDatabaseColumn` is not use for now.
Return if cannot go to the next status.

feat(advanced-masking): evaluate the masking level of column

---

backend/legacyapi/policy.go
backend/server/server.go

Need to cherry-pick to 2.7.0 otherwise new users will get exceptions for sensitive data policy

fix: 🔥retire legacy SensitiveDataPolicy

---

backend/migrator/migration/prod/2.7/0000##migrate_sensitive_data_policy_to_proto_json.sql

The legacy data contains `{"sensitiveDataList": []}`, it would make the following query return `NULL`:
```sql
UPDATE
policy
SET
payload = jsonb_set(
payload,
'{sensitiveDataList}',
(
SELECT
jsonb_agg(item - 'maskType')
FROM
jsonb_array_elements(payload -> 'sensitiveDataList') AS arr(item)
)
)
WHERE
TYPE = 'bb.policy.sensitive-data'
AND payload != '{}' :: jsonb;
```

fix: delete the legacy data

---

backend/migrator/migration/prod/2.7/0006##clean_pushevent.sql
backend/migrator/migrator_test.go

We've migrated pushEvent from task to sheet.
We've also deprecated fileCommit.

chore: clear push event

---

backend/plugin/db/util/driverutil_test.go
backend/plugin/db/util/mask_sensitive_data.go
backend/plugin/db/util/mask_sensitive_data_tsql.go

Follow #7906.
After this PR, `sensitive` field is ready to retire.

feat(advanced-masking-policy): retire sensitive in tsql calculator

---

backend/api/v1/project_service.go
backend/store/project.go

Add we will set the classification to all projects when we update the classification setting BTW: https://sourcegraph.com/github.com/bytebase/bytebase/-/blob/backend/api/v1/setting_service.go?L523

chore: set classification to project during creation

---

backend/plugin/idp/oauth2/oauth2.go
backend/server/webhook.go

Passing nil to `log.BBError` causes panic.

fix: remove log.BBError(err) if nil

---

frontend/src/assets/css/tailwind.css
frontend/src/bbkit/BBSelect.vue
frontend/src/components/v2/Select/DatabaseSelect.vue
frontend/src/views/SyncDatabaseSchema/DatabaseSchemaSelector.vue

* use v2 selectors in sync schema;
* use `rounded` instead of `rounded-md` for bbkits;

chore: use v2 selectors in sync schema

---

frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue
frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
frontend/src/components/IssueV1/components/TaskStatusIcon.vue
frontend/src/components/IssueV1/logic/initialize/create.ts
frontend/src/components/IssueV1/logic/rollout.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/utils/v1/deploymentConfig.ts

- In batch mode
- Expand the pipeline using deploymentConfig as `spec.changeDatabaseConfig.target` on server-side
- All tasks in a batch mode rollout targeting a deploymentConfig will share ONE plan/spec. This means they share ONE sheet, rollbackEnabled and earliestAllowedTime and cannot be changed independently.
- Once any one of the tasks is done, the sheet cannot be changed. Means that the SQL statement of any other tasks cannot be changed. 
FYI @d-bytebase @RainbowDashy 
Close BYT-3939

feat(frontend): migrate batch mode deployment to CI/CD v2 in backend

---

backend/plugin/db/pg/dump.go

fix: https://github.com/bytebase/bytebase/issues/7738

fix(pg_dump): split large sslca to mutli smaller sslcas

---

frontend/src/components/ExprEditor/components/MultiSelect.vue

chore(frontend): fixed dropdown menu width for expr editor

---

frontend/src/views/sql-editor/SecondarySidebar/HistoryTabPane/HistoryTabPane.vue

The engine icon is not clickable, so do not co-locate it with the clickable paste icon.

chore: move engine icon before the timestamp

---

frontend/src/components/IssueV1/components/ActivitySection/ActivityList.vue
frontend/src/components/IssueV1/components/IssueTableV1.vue
frontend/src/components/IssueV1/components/PagedIssueTableV1.vue
frontend/src/components/IssueV1/components/WaitingForMyApprovalIssueTableV1.vue
frontend/src/components/IssueV1/logic/initialize/create.ts
frontend/src/components/MarkdownEditor.vue
frontend/src/components/ProjectOverviewPanel.vue
frontend/src/store/modules/v1/experimental-issue.ts
frontend/src/store/modules/v1/issue.ts
frontend/src/views/Home.vue
frontend/src/views/IssueDashboard.vue

- Legacy [GET] /api/issues (issue list) endpoint has been migrated to IssueService.ListIssues and IssueService.SearchIssues
- No longer display `environment` and `progress` columns in issue list. Environment filter is also retired.
- Markdown editor's issue list has been migrated to `ComposedIssue` type.
- issueV1Store's `listIssues` and `searchIssues` now return shallow-composed issue list. By which "shallow-composed" means that their `planEntity`, `rolloutEntity`, `planCheckRunList`, `taskRunList` are empty.
FYI @RainbowDashy @ecmadao @d-bytebase

chore(frontend): migrate issue list API and components

---

frontend/src/components/IssueV1/components/BatchIssueActionsV1.vue
frontend/src/components/IssueV1/components/IssueTableV1.vue
frontend/src/components/IssueV1/components/Panel/BatchIssueStatusActionPanel.vue
frontend/src/components/IssueV1/components/Panel/index.ts
frontend/src/views/Home.vue
frontend/src/views/IssueDashboard.vue

- `[PATCH] /api/issue/${issue_id}/status` now could be retired. FYI @d-bytebase @RainbowDashy 
- Batch issue status ops in the issue list is back! Plus the new drawer UI! FYI @ecmadao

refactor(frontend): migrate issue list batch status ops to v1 api

---

frontend/src/bbkit/BBTab.vue

I guess this is caused by the package upgrade?
Before:
After:

fix: the active tab style

---

frontend/src/views/sql-editor/TerminalPanel/CompactSQLEditor.vue

chore(sql-editor): update line-numbers gutter width in compact editor

---

frontend/src/locales/subscription/en-US.json
frontend/src/locales/subscription/es-ES.json
frontend/src/views/DashboardHeader.vue
frontend/src/views/DashboardSidebar.vue

* SQL Editor is the only item that requires opening a new tab.
* Still need to make it available on all pages.
* Logically to make SQL Editor a more standalone component. The other items on the left sidebar and the incoming `Change Center` are more coherent.

chore: move SQL Editor link to the top right

---

frontend/package.json
frontend/pnpm-lock.yaml
frontend/tailwind.config.js

Remove the unused plugin `@tailwindcss/line-clamp` as it's included in the framework by default after tailwindcss v3.
Reference: https://github.com/tailwindlabs/tailwindcss-line-clamp#tailwindcssline-clamp

chore: remove tailwind line-clamp

---

backend/api/v1/issue_service.go
backend/api/v1/org_policy_service.go
backend/legacyapi/issue.go
backend/migrator/migration/prod/2.8/0004##issue_type.sql
backend/migrator/migrator_test.go
backend/runner/approval/runner.go

Note: we will still keep the legacy issue type in deployment policy. We will fix CD policy in the future.

chore: deprecate legacy issue type with DML

---

frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
frontend/src/components/SchemaEditorV1/Aside/DatabaseTree.vue

chore: update schema editor styles

---

frontend/src/components/v2/Model/DatabaseV1Table/DatabaseTableRow.vue
frontend/src/components/v2/Model/DatabaseV1Table/DatabaseV1Table.vue

We always show active databases so the column was unnecessary.

chore: remove sync status from database list

---

frontend/vite.config.ts

#72 CANCELED
------
> [linux/arm64 frontend 9/9] RUN pnpm "release-docker":
#66 91.91 dist/assets/errorMessage-f72ee830.js                                                            2,005.51 kB │ gzip:   519.16 kB
#66 91.91 dist/assets/explain-visualizer-25d54b76.js                                                      2,045.82 kB │ gzip:   719.37 kB
#66 91.91 dist/assets/main-7e06a445.js                                                                    4,729.29 kB │ gzip: 1,150.55 kB
#66 91.91 
#66 91.91 (!) Some chunks are larger than 500 kBs after minification. Consider:
#66 91.91 - Using dynamic import() to code-split the application
#66 91.91 - Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
#66 91.91 - …

chore: adjust chunkSizeWarningLimit

---

backend/api/v1/schema_design_service.go
frontend/src/components/Branch/BranchDetailView.vue

As we'll create draft branches when saving edits, we should use the baseline schema from api not the latest schema of parent branch.
Frontend changes: https://github.com/bytebase/bytebase/pull/8445
FYI @tianzhou

fix: create personal draft baseline schema

---

frontend/src/components/IssueV1/logic/action/task.ts
frontend/src/components/IssueV1/logic/assignee.ts

- Who can change the assignee?
- Issue creator
- Current assignee
- Project owners - always
- Super users - always
- Who can press the rollout button?
- Anyone in the project - if the rollout policy is "auto rollout"
- Project owners - if the rollout policy is "project owners"
- Super users - always
- Warning task checks will block the rollout button by default
- Still allowed to rollout if the "Rollout anyway" is checked.
FYI @d-bytebase 
Close BYT-4089

chore(frontend): adjust assignee and rollout permissions

---

frontend/src/components/SchemaEditorV1/Panels/TableColumnEditor.vue

- For tidbparser, one column can have both attributes that can be `NOT NULL` and  the default value is `NULL`, so restrictions are made on the frontend.

fix: disable setting default value to null for nonnullable columns

---

README.md

```bash
PG_URL=postgresql://bbdev@localhost/bbdev
air -c scripts/.air.toml
```
The command doesn't work in my MacOS and uses embed pg. I tried `PG_URL=postgresql://bbdev@localhost/bbdev air -c scripts/.air.toml`. It working well! So I change the document.
And I also find the database need a password. otherwise it will throw a error like :
```
time=2023-09-28T15:00:57.270+08:00 level=ERROR source=cmd/root.go:255 msg="Cannot new server" error="cannot open metadb: failed to get max_connections from metaDB: failed to connect to `host=localhost user=bbdev database=bbdev`: failed SASL auth (FATAL: password authentication failed for user \"bbdev\" (SQLSTATE 28P01))
```
But I can't sure the problem caused by my pg or a document error. If it is indeed a document error, I will submit a new PR to …

chore: fix document error

---

frontend/src/components/SchemaEditorV1/Panels/TableColumnEditor.vue

fix: schema editor column table ui

---

backend/api/v1/sql_service.go
backend/plugin/parser/pg/query.go
backend/plugin/parser/tidb/tidb.go
backend/plugin/parser/tidb/tidb_test.go
backend/tests/sensitive_data_test.go

Also converted tidb and postgres parser error to base.SyntaxError so that we know which line and column hits the error.

chore: include SqlReviewReport as query/export error detail

---

backend/plugin/parser/sql/edit/mysql/deparse.go

From the Go specification [^1]:
> "1. For a nil slice, the number of iterations is 0."
`len` returns 0 if the slice is nil [^2]. Therefore, checking `len(v) > 0` or `len(v) != 0` before a loop is unnecessary.
[^1]: https://go.dev/ref/spec#For_range
[^2]: https://pkg.go.dev/builtin#len

refactor: remove redundant `len` check

---

frontend/src/components/IssueV1/components/IssueTableV1.vue

revert of https://github.com/bytebase/bytebase/pull/8314
- scaling issue: we called external project GitOps N times, if there are N issues returned. It hits network bottleneck if users have thousands issues.
- correctness: we got the current project GitOps info which wasn't correctly identifying the source of an issue. Users can still create issue from UI even if they setup project GitOps.

fix: revert PR/8314 prepend the VCS provider icon if the issure is created via VCS

---

frontend/src/components/GeneralSetting/AIAugmentationSetting.vue

Otherwise, there is no way to unset it in non-enterprise version and will always see the upgrade required banner

fix: always allow to unset the OpenAI settings

---

frontend/src/composables/useExecuteSQL.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/sqlEditor.ts
frontend/src/store/modules/v1/sql.ts
frontend/src/types/tab.ts
frontend/src/views/sql-editor/ResultPanel/ResultPanel.vue
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/DatabaseSchema.vue

- Show an execution timer
- Allow to cancel a query
- Once any one of a batch queries is aborted, the rest of the queries won't execute and will mock an "Aborted blah blah" result for them as if they have been really aborted. But the queries that are already finished will still be displayed.
Close BYT-4149

feat(sql-editor): cancel query

---

frontend/src/views/sql-editor/EditorPanel/SQLEditor.vue

* remove the unwanted padding area;

chore: update sql editor overflow styles

---

frontend/src/views/sql-editor/EditorCommon/BatchQueryDatabasesSelector.vue

It’s now quite straightforward and no need to hint user to check further

chore: remove learn more link in batch query

---

backend/common/log/slog_utils.go

since https://github.com/bytebase/bytebase/pull/8540, we can use our stacktrace function to replace `debug.Stack()`

feat: use bb stacktrace to replace debug.Stack()

---

backend/plugin/parser/sql/ast/constraint_def.go
backend/plugin/parser/sql/engine/pg/convert.go
backend/plugin/parser/sql/engine/pg/deparse.go
backend/plugin/parser/sql/engine/pg/test-data/test_create_table_data.yaml

this pr can only handle `GENERATED ALWAYS AS ( generation_expr ) STORED` for pg. I want fix `GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY [ ( sequence_options ) ]  ` in another pr.

fix: handle GENERATED ALWAYS AS constraint for pg

---

backend/api/v1/database_service.go
backend/runner/rollbackrun/runner.go
backend/store/instance_change_history.go
backend/tests/change_history_test.go
backend/tests/schema_update_test.go
backend/tests/sync_schema_test.go

Known issues: frontend uses List rather than Get in ChangeHistoryDetail page, so the truncate size will be 512.

feat: different change history truncate size for Get/List

---

backend/api/v1/database_service.go
backend/server/grpc_routes.go

Expose problem early in dev env if we use any truncated strings.

chore: use different truncate size for different mode

---

frontend/src/components/Issue/panel/RequestExportPanel/index.vue
frontend/src/components/Issue/panel/RequestQueryPanel/index.vue
frontend/src/components/QuickActionPanel.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/views/ExportCenter/index.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/RequestQueryButton.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue

Though underlying they both use the IAM model, from the user’s perception, they behave differently. Export data is requested via SQL Editor and Export Center, which require supplying the SQL query.
Only change for Chinese. For English/Spanish, just use `Request Export` since we don't have enough space

feat: distinguish between request export permission and export data

---

frontend/src/store/modules/sqlEditorTree.ts

- Environment nodes: order by `env.order` DESC
- Label nodes: order label value ASC (lexical) but put "<Empty>" to the last
- Project nodes: use the original server-returned order but put "Unassigned databases" to the last
- Other nodes: use the original server-returned order

chore(sql-editor): sort tree nodes on demand

---

frontend/src/components/AlterSchemaPrepForm/SchemaEditorSQLCheckButton/useSchemaEditorSQLCheck.ts

We will show the SQL review error even if nothing changes while altering the schema.
This is because we won't fetch the schema list until users expand the database tree:
- https://sourcegraph.com/github.com/bytebase/bytebase/-/blob/frontend/src/components/SchemaEditorV1/index.vue?L86
- https://sourcegraph.com/github.com/bytebase/bytebase/-/blob/frontend/src/components/SchemaEditorV1/Aside/DatabaseTree.vue?L600
So that the schema list in the local state is empty, this will be treated as dropping the schema during the diff.

fix: skip SQL check if nothing changed in the local state

---

frontend/src/components/Branch/BaselineSchemaSelector.vue
frontend/src/components/Branch/BranchCreateView.vue
frontend/src/components/Branch/BranchDetailView.vue
frontend/src/components/Branch/BranchTable.vue
frontend/src/components/Branch/MergeBranchPanel.vue
frontend/src/components/Branch/SchemaDesignEditor.vue
frontend/src/components/Branch/SchemaDesignSQLCheckButton.vue
frontend/src/components/SQLCheck/SQLCheckButton.vue
frontend/src/components/SchemaEditorV1/index.vue
frontend/src/components/SchemaEditorV1/utils/branch.ts
frontend/src/router/index.ts
frontend/src/store/modules/schemaDesign.ts
frontend/src/store/modules/v1/changelist.ts
frontend/src/views/Changelist/ChangelistDetail/AddChangePanel/AddChangePanel.vue
frontend/src/views/Changelist/ChangelistDetail/AddChangePanel/form/BranchChangeItem.vue
frontend/src/views/Changelist/ChangelistDetail/AddChangePanel/form/BranchForm.vue
frontend/src/views/Changelist/ChangelistDetail/BranchDetailPanel/BranchDetailPanel.vue
frontend/src/views/Changelist/ChangelistDetail/ChangeTable/ChangeTable.vue
frontend/src/views/Changelist/ChangelistDetail/ChangeTable/DatabaseForChange.vue
frontend/src/views/Changelist/ChangelistDetail/ChangeTable/Source.vue
frontend/src/views/Changelist/ChangelistDetail/NavBar/export.ts
frontend/src/views/SyncDatabaseSchema/SchemaDesignSelector.vue
frontend/src/views/SyncDatabaseSchema/SelectTargetDatabasesView.vue
frontend/src/views/SyncDatabaseSchema/index.vue
frontend/src/views/branch/BranchDetail.vue

- results in ListSchemaDesigns will no longer be written to the local cache since they might be just a truncated brief view in the future
- calling no more `getSchemaDesignByName` and `getOrFetchSchemaDesignByName`. Call `fetchSchemaDesignByName` instead, with an explicit `useCache` flag.
- Baseline selector when creating branches now will no longer auto-select invalid (DML, actually) change history.
- Loading indicators for
- Branch list in "Sync Schema -> Branches"
- Merge branch panel
- Make linter happy

chore(frontend): schema design store refactor

---

frontend/src/components/CreateDatabasePrepForm/CreateDatabasePrepForm.vue
frontend/src/components/DatabaseBackup/BackupTable.vue
frontend/src/components/DatabaseDetail/PITRRestoreButton.vue

If the first stage's environment rollout policy is set to "auto" or "creator", we will set the default assignee as the creator.
FYI @RainbowDashy 
Close BYT-4251

fix(frontend): set creator field before creating issue

---

frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

Customer accidentally creates a GitHub app instead of an OAuth app.

chore: improve github application id error msg

---

backend/plugin/db/mssql/mssql.go

Previously, we split the statements into single statement. But it is meaningless for SQL Server which support sending multiple single statement to driver in a batch. **[The scope of a local variable is the batch in which it's declared.](https://learn.microsoft.com/en-us/sql/t-sql/language-elements/declare-local-variable-transact-sql?view=sql-server-ver16#remarks)**

fix(SQL-Server): support using variable in mssql execute

---

backend/plugin/vcs/azure/bytebase-sql-review.yml

Azure test pipeline cannot show the warning, and will pass the check if the result only contains warnings
Close BYT-4256

chore: fail the pipeline if the sql review result doesn't succeed

---

backend/plugin/db/redshift/sync.go

feat: add redshift character/bit type length to metadata

---

frontend/src/components/v2/Model/Instance/InstanceV1Table/InstanceOperations.vue

The "dismiss" event has been triggered but not declared on `defineEmits`

fix: emit warning

---

backend/runner/approval/runner.go

instance.Engine was changed to enums in protobuf and string(Engine) returns "2", we need to use the `name`.

fix: should use engine string

---

.gitignore
scripts/.air.toml

1. Use -gcflags="all= -N -l" to disable inlining and optimization, and then the dlv can read values of some process variable which would be optimized originally. `(dlv) (unreadable could not find loclist entry at 0x49e7a for address 0x44f9b9)`
2. add .air.toml to gitignore, parser members use ultimate tag most of time. Use `git add scripts/.air.toml -f` can staged it forcely`.

chore: update air.toml to disable optimization

---

frontend/src/components/DatabaseGroup/ProjectDatabaseGroupPanel.vue
frontend/src/components/ProjectActivityPanel.vue

The component already says what it is. There is no need to say it again.
Before:
After:

chore: remove activity and database group from panel

---

frontend/src/components/Project/ProjectSidebar.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

1. Reordered the items in the project sidebar. "Integration / GitOps" is more interesting and valuable than managing members.
2. "Database Groups" to "Groups". Since we've already put it under database section, there is no need to mention it again. This also reduces its form in Español.
Before:
After:

chore: reorder project sidebar items

---

frontend/src/views/DashboardHeader.vue
frontend/src/views/DashboardSidebar.vue

Move branches from header to sidebar.
1. Branches should not belong to header since it's not as important as other resources such as projects, databases, instances.
2. There is limited space in the header.
3. We will renovate the header later so let's make a little change now.
Before:
After:

chore: move branches from header to sidebar

---

frontend/src/store/modules/schemaDesign.ts
frontend/src/views/branch/BranchDetail.vue

Close BYT-4284
The `data.branch` will always remain the same value with `asyncComputed`. But it should comes from the latest data in store.

fix: data source in branch detail page

---

frontend/src/components/IssueV1/components/HeaderSection/Assignee/Assignee.vue
frontend/src/components/IssueV1/logic/assignee.ts
frontend/src/components/misc/ErrorList.vue

- Error info with indention
- Any valid candidates of the last approval node should be valid assignee candidates.

chore(cicd): fix last approver rollout policy

---

frontend/src/components/v2/Model/DatabaseV1Table/DatabaseTableRow.vue
frontend/src/components/v2/Model/DatabaseV1Table/LabelsColumn.vue

The "Labels" column now has consistent height whenever with or without contents

chore(frontend): tuning labels column style for database tables

---

frontend/src/assets/css/tailwind.css
frontend/src/components/Branch/BranchSelector.vue
frontend/src/components/CustomApproval/Settings/components/CustomApproval/RulesPanel/RuleSelect.vue
frontend/src/components/v2/Model/DatabaseV1Table/DatabaseLabelFilter.vue
frontend/src/components/v2/Select/DatabaseSelect.vue
frontend/src/components/v2/Select/EnvironmentSelect.vue
frontend/src/components/v2/Select/InstanceSelect.vue
frontend/src/components/v2/Select/ProjectMemberRoleSelect.vue
frontend/src/components/v2/Select/ProjectSelect.vue
frontend/src/components/v2/Select/UserSelect.vue
frontend/src/components/v2/Select/WorkspaceRoleSelect.vue
frontend/src/plugins/ai/components/MockInputPlaceholder.vue
frontend/src/plugins/ai/components/PromptInput.vue

maybe introduced by upgrading tailwindcss' version sometime. but we now fix it globally.

chore(frontend): remove duplicated rings for naive-ui input components globally

---

backend/plugin/parser/mysql/differ.go

the return value of `extractor.mysqlExtractCreateView` is out of order. so sometimes go tests will fail, like https://github.com/bytebase/bytebase/actions/runs/6662460038/job/18106845688?pr=8957#logs . 
but we only use this result for create temp view. the final column order is decided by createView statement.
ref: https://github.com/bytebase/bytebase/pull/3032

fix: sort temp view columns order

---

frontend/src/components/ChangeHistory/AffectedTableSelect.vue
frontend/src/components/ChangeHistory/ChangeHistoryTable.vue
frontend/src/components/ChangeHistory/index.ts
frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/form/ChangeHistoryForm.vue
frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/form/ChangeHistoryTable/Tables.vue
frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/form/utils.ts
frontend/src/components/DatabaseChangeHistoryPanel.vue
frontend/src/components/v2/Button/TooltipButton.vue
frontend/src/types/index.ts
frontend/src/utils/v1/changeHistory.ts

- Use naive-ui buttons
- Create `<AffectedTableSelect>` component using naive-ui select and shared with changelist-related UI

chore(frontend): use naive-ui components in database change histories page

---

backend/plugin/vcs/bitbucket/bitbucket.go

For the rename file operation, gitlab.com(16.4) treated it as added only in push event:
But in bitbucket, it treats it as renamed changed type:
After this PR, bitbucket will treated renamed as a added changed type to be consistent with GitLab.

fix(bit-bucket): rename file should trigger creating issue

---

backend/plugin/vcs/azure/bytebase-sql-review.yml
backend/plugin/vcs/gitlab/bytebase-sql-review.yml

Why:
Sometimes, the pipeline return sql review passed but when deploy on Bytebase, the sql checking (UI) return some warning/error check.
We re-review log in cicd and noticed that script return
```
sh: 0: unknown operand
```
that cause next steps in script will always failed because there is no data.
Fix:
The `echo` command is wrapped in `double quotes` to preserve the JSON structure stored in the `content` variable.
in some case, it'll return
```
sh: 0: unknown operand
```
and cause script run incorrectly

fix: update bytebase-sql-review.yml for CICD

---

backend/store/task.go

We should refer `COALESCE(latest_task_run.status, 'NOT_STARTED')` to get the latest_task_run_status, otherwise, t cannot list the `NOT_STARTED` task, then the GitOps cannot update the task content unless the task had failed. https://sourcegraph.com/github.com/bytebase/bytebase/-/blob/backend/api/gitops/webhook.go?L2118

fix: list tasks sql

---

backend/store/db_schema.go
frontend/src/components/Branch/BranchCreateView.vue

- The cache in the `UpsertDBSchema` will clear the database config by mistake.
- Fetch database config history via the change history sheet.

fix: database config change

---

backend/api/lsp/fs.go
backend/api/lsp/fs_handler.go
backend/api/lsp/handler.go
backend/api/lsp/utls.go
go.mod
go.sum

close BYT-3953
Currently, we create one in-memory file system per connection. They are not shared.
cc @LiuJi-Jim

feat(LSP): implement initialize and file system request

---

backend/api/lsp/commands.go
backend/api/lsp/handler.go

close BYT-3953
The client can use `workspace/executeCommand` to execute the `setMetadata` command to identify instances and databases.

feat(LSP): implement setMetadata command to identify instances and databases

---

backend/bin/server/cmd/root.go

An extra safety measure to prevent accidentally resetting the user data with the demo data

chore: disallow using demo mode when using external pg

---

backend/demo/demo.go
backend/migrator/migrator.go
backend/plugin/db/driver.go
backend/server/server.go
backend/store/pg_engine.go

Already set when constructing the metadb connection config

refactor: cleanup strictUseDb

---

backend/api/gitops/webhook.go
backend/api/v1/externalvs_service.go
backend/api/v1/project_service.go
backend/plugin/vcs/azure/azure.go
backend/plugin/vcs/azure/sql_review.go
backend/plugin/vcs/bitbucket/bitbucket.go
backend/plugin/vcs/bitbucket/bitbucket_test.go
backend/plugin/vcs/github/github.go
backend/plugin/vcs/github/github_test.go
backend/plugin/vcs/gitlab/gitlab.go
backend/plugin/vcs/gitlab/gitlab_test.go
backend/plugin/vcs/vcs.go
backend/runner/taskrun/executor.go

Previously, the follow up VCS api call after the token refresh will failed because they take the legacy access token. For example in Azure DevOps:
The token refresh patch the store but do not update the value in memory correctly because the we pass the struct which is a value type in golang. This pr switch to pass the `*common.OauthContext` which is a pointer instead of struct.

fix(GitOps): pass oauthContext pointer to make the following api call work well

---

frontend/src/plugins/window-events.ts

useful if Bytebase is opened via `window.open` (popup window, for example)

chore(frontend): also emit window events to window.opener

---

frontend/src/components/IssueV1/components/PagedIssueTableV1.vue
frontend/src/components/IssueV1/components/WaitingForMyApprovalIssueTableV1.vue
frontend/src/components/Project/ProjectIssuesPanel.vue
frontend/src/views/Home.vue
frontend/src/views/IssueDashboard.vue

The current issue filter takes much space and causes distraction. The filter isn't useful at all because the page-size is set to a low number. Chrome Ctrl+F serves better purpose for searching keywords on the page. Dev tools don't usually have a keyword filter. For complex scenarios, users should use advanced search for searching issues.
This PR also increased page size to 50 and made advanced search button consistent.
Before:
After:

chore: deprecate issue keyword filter

---

backend/api/v1/project_service.go
frontend/src/store/modules/v1/projectIamPolicy.ts

Make binding members unique both in frontend and backend when setting project iam policy

chore: unique binding members when setting project iam policy

---

frontend/src/components/Project/ProjectSidebar.vue
frontend/src/views/ProjectDetail.vue

- For the default page, use different cache for different project
- Issue creator should have at least one permission, so we just need to check the permission before fetch the activities.

chore: use different cache for different project

---

backend/api/v1/sql_service_v2.go
backend/component/masker/masker.go
backend/plugin/parser/base/interface.go
backend/plugin/parser/base/masking.go
backend/plugin/parser/pg/v2/masking.go
backend/plugin/parser/pg/v2/query_span.go

Previously, our masking was strongly coupled with the column attributes. We had to spend a lot of time repeatedly modifying the masking logic in different engine packages whenever we extended the masking feature.
We introduce `QuerySpan`, which returns only the query span (including the accessed resources, the source columns of each result column). This allows us to implement access control/masking logic in the caller outside.

feat: implement the framework of get query span

---

backend/api/v1/schema_design_transformer.go
backend/api/v1/testdata/design.yaml
backend/api/v1/testdata/schema.yaml

now: we use default to store `auto_increment` attribute for mysql.
https://github.com/bytebase/bytebase/assets/71714656/32eca4df-714e-4c48-8879-d8dff783a78c

chore(mysql): use default expression to add auto_increment

---

frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
frontend/src/components/v2/Model/DatabaseV1Table/DatabaseTableRow.vue
frontend/src/views/DatabaseDashboard.vue

* hide `transfer`/`sync`/`edit labels` buttons in standalone mode;
* hide sql editor entry in standalone mode;
* skip schema editor dialog in standalone mode;
https://github.com/bytebase/bytebase/assets/24653555/dd7523ea-56e4-4e3c-873a-c28667920412

chore: update db dashboard in standalone mode

---

frontend/src/components/IssueV1/components/StageSection/Actions/GhostSection/GhostSection.vue
frontend/src/components/IssueV1/components/StageSection/Actions/GhostSection/GhostSwitch.vue
frontend/src/components/IssueV1/components/StageSection/Actions/GhostSection/common.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

- The "Online migration" section will show when previewing any DDL issues. (Except database group changes)
- If some tasks are not applicable for gh-ost (MySQL >= 5.7) we will still show the section with an error tooltip. And the switch will be unclickable.
- Online migration will be not applicable if any of the tasks' instances are missing licenses. This comes with an error tooltip.
- The "missing instance license" indicator (aka. the lock icon) will correctly disappear after assigning licenses to the instance s via the popover drawer.
FYI @RainbowDashy @adela-bytebase

chore(frontend): ghost improvements

---

frontend/src/bbkit/BBModal.vue
frontend/src/components/IssueV1/components/ActivitySection/Activity/ActionSentence.vue
frontend/src/components/IssueV1/components/ActivitySection/Activity/StatementUpdate.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

- Statement changed activity will be unreadable in real-world scenes if statements are very long.
- Sheets will be pre-loaded even if they are actually not rendered to the screen.
- Show only the activity brief in the activity list. Show the full statement diff when clicking on "View details".
- Full statements will only be loaded when the detail dialog opens.
https://github.com/bytebase/bytebase/assets/2749742/3c14442a-684f-4d18-94ce-73e9f91b9fbf
FYI @adela-bytebase

chore(frontend): statement change activity improvements

---

frontend/src/components/Issue/activity/common.ts
frontend/src/components/IssueV1/components/ActivitySection/Activity/common.ts
frontend/src/components/IssueV1/components/ActivitySection/ActivityList.vue

Before: same `oldStatement` and same `newStatement`
After: same `newSheetId`
Reason: old/newStatement fields are legacy. Activities generated by batch "apply to current stage" or "apply to all tasks" statement update operations will share the same `newSheetId`
Also removed unused duplicated legacy codes.

chore(frontend): update similar tasks logic

---

frontend/src/components/DatabaseListSidePanel.vue
frontend/src/components/ProvideDashboardContext.vue

It's bad practice to implicitly depend on some components' data. So we move the data initialize logic from `DatabaseListSidePanel` to `ProvideDashboardContext`
Close BYT-4408

chore(frontend): move some data initialize logic to root component

---

frontend/src/components/CommonSidebar.vue

1. Both GitLab and GitHub lack this button in the sidebar. It appears that clicking on the logo icon is a commonly used method to return to the home page. Taking an experiment to remove this button in the next release.
2. Save the space taken by go back button.
3. Answer from GPT "Users often expect the logo or company/brand name in the top left corner of a website or application to serve as a link to the home page. It's a widely recognized convention. Therefore, if you have your logo in the header, users may already know that they can click it to go back home."

chore: remove go back button (experiment)

---

frontend/src/components/AdvancedSearch.vue
frontend/src/components/Project/ProjectIssuesPanel.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/utils/v1/issue/ui-filter.ts
frontend/src/views/Home.vue
frontend/src/views/IssueDashboard.vue

1. Changed word review to approval to be consistent with other approval related wording within the product, e.g. custom approval.
2. (Experiment) Reorder default filter tabs. Moved "Created" to the left because it's more friendly to developers.

chore: reword review to approval

---

backend/api/v1/issue_service.go
backend/store/issue.go
frontend/src/components/AdvancedSearch.vue
frontend/src/utils/v1/issue/advanced-search.ts
frontend/src/views/Home.vue
frontend/src/views/IssueDashboard.vue

The principal should also cover approver and releaser ideally, but it's difficult to implement such principal filter. In this case, let's deprecate the principal filter to eliminate the confusion and making the issue role more explicit. Future work includes adding releaser filter and making advanced search and simple filter compatible.

chore: deprecate issue principal filter

---

frontend/src/components/AdvancedSearch.vue
frontend/src/components/Project/ProjectIssuesPanel.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/utils/v1/issue/ui-filter.ts
frontend/src/views/Home.vue
frontend/src/views/IssueDashboard.vue

- `review_status` -> `approval`
- `pending_review` -> `pending`
- `approved` -> `approved` (no change)

chore(frontend): re-terminology "review_status" issue filter to "approval"

---

frontend/src/views/DatabaseDashboard.vue

Unassigned databases should be visible on the dashboard when an instance is added, providing a more intuitive user experience. Additionally, consider implementing an unassigned database filter rather than directing users to a separate page.

chore: show all databases in the database dashboard

---

frontend/src/components/TableDetailDrawer.vue

- Remove unnecessary information to give it more space. It's already showed in the database overview page.
- Change the font to be consistent with section in  the database overview page.
After:
Before:

chore: improve table detail drawer

---

backend/server/server.go

Sometimes fail due to mac docker engine bug with mac os file system

feat: emit log instead of fail when generating onboarding data fails

---

frontend/src/components/ProvideSQLEditorContext.vue
frontend/src/store/modules/sqlEditorTree.ts
frontend/src/types/sqlEditorTree.ts
frontend/src/views/sql-editor/AsidePanel/GroupingBar/GroupingBar.vue

Once a project is specified in the routing query (e.g., `?project=bytebase`), the tree will display its database directly.
https://github.com/bytebase/bytebase/assets/24653555/61c7166f-f10a-4847-9e63-3f60070eb8e4

feat: add project mode to sql editor tree store

---

frontend/src/components/SchemaDiagram/Canvas/Canvas.vue

Sometimes the screenshot is generated successfully and downloaded, but an error notification is displayed.

chore: tweak generate screenshot error

---

backend/runner/taskrun/schedulerv2.go

1. We only run task run once.
2. We don't have huge amount of task runs. It's not quite costly if we keep it in memory.
3. There is a race condition between task runs from ListTaskRuns() and evicting the task run ID on completion.

chore: avoid race condition by keeping task run set

---

frontend/src/components/IssueV1/components/PagedIssueTableV1.vue
frontend/src/components/Project/ProjectIssuesPanel.vue
frontend/src/components/v2/TabFilter/TabFilter.vue
frontend/src/views/Home.vue

Following #9350 
- Repurpose "Recently Closed" to "All", and enable both "OPEN" and "CLOSED" for it.
- "Approval Requested", "Waiting Approval" and "Waiting Rollout" now only enable "OPEN" in the secondary tab bar.
- Remove redundant `ListIssues` requests.
- Display a loading spinner when changing tabs.

chore(frontend): issue search improvements

---

frontend/src/components/IssueV1/components/TaskRunSection/TaskRunComment.vue

close BYT-4455
The change history info is in ghost cutover payload.

fix: fix online migration change link

---

frontend/src/views/sql-editor/EditorCommon/EditorAction.vue

We cannot open this feature to public till we allow user to set which data source can be used for query.

chore: limit showQueryContextSettingPopover

---

frontend/src/components/CommonSidebar.vue

It's common to see 1) right (unexpanded) and down (expanded), 2) up (unexpanded) and down (expanded), and 3) many others. We have up (unexpanded) and down (expanded) - first one. I haven't figured out a design pattern yet. But GitLab/Chrome/Google Admin and a few tools use right and down - second one for some reasons. Let's try out the second.
Now:
Before:
GitLab/Google Admin/Chrome:

chore: update sidebar chevron direction

---

frontend/src/components/IssueV1/components/IssueSearch/ScopeTags.vue
frontend/src/components/Project/ProjectIssuesPanel.vue
frontend/src/views/Home.vue

1. Remove time range from home issue dashboard and project issue dashboard. Time range is considered to be an advanced search. It's also a bit ambiguous whether it's created time or last update time. Maybe we will add it back later if we combine the classic issue dashboard and advanced issue search dashboard. Or maybe it should be part of constructing scope tags instead of having a separate space for it.
2. Use "-" instead of " -> " separator and localized format to represent the time range.
https://learn.microsoft.com/en-us/style-guide/punctuation/dashes-hyphens/enes
https://day.js.org/docs/en/display/format
Now:
Before:
Now:
Before:

chore: update time range in issue dashboard

---

frontend/src/components/Role/Setting/components/RoleTableRow.vue
frontend/src/components/User/Settings/UserTable.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/utils/role.ts
frontend/src/utils/v1/role.ts

Make a distinction between the developer (workspace developer) and the developer (project developer) by calling workspace developer -> member.

chore: rename workspace developer to member

---

frontend/src/components/IssueV1/components/HeaderSection/Assignee/Assignee.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

1. Show current assignee, otherwise we will get unknown user error.
2. Remove project member group since it could be too noisy to show.
Before:

chore: update assignee options

---

frontend/src/components/ProvideSQLEditorContext.vue
frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue

- Explicitly set tree height to avoid virtual list overheads
- Recover `tabList` and `expandedKeys` correctly after the `localStorage` has been cleared. FYI @boojack

chore(sql-editor): some minor fixes

---

backend/plugin/advisor/catalog/test/mysqlv2_walk_through.yaml
backend/plugin/advisor/catalog/walk_through_for_mysql_v2.go

Support create constraint in `create table` statement. 
Although antlr parser. supports creating index in the `create table` statement which tidb parser does not support, we only do migration this time.

chore: support table constraint in create-table statement

---

frontend/src/views/sql-editor/ResultPanel/ResultPanel.vue

use `.hide-scrollbar` since horizontal scrollbars are ugly and space-consuming
Close BYT-4457

chore(frontend): allow horizontal scroll for batch query tabs

---

frontend/src/components/Project/ProjectSidebar.vue

This should close BYT-4492. Need CP to 2.11.1

fix: project developer can only see "Databases" in the sidebar

---

backend/component/dbfactory/dbfactory.go
backend/plugin/db/pg/pg.go

Previously, it's 9.624. Now it should be 9.6.24.

fix: pg semantic version

---

backend/utils/database_group.go

This allows handling the below case, where strings.Contains("test") matches both "test" and "sbtest".
```
UPDATE test SET <<column>> = <<value>> WHERE <<condition>>;
UPDATE sbtest SET <<column>> = <<value>> WHERE <<condition>>
```
Thanks @LiuJi-Jim

chore: match word boundary, more robust

---

frontend/src/components/ProvideSQLEditorContext.vue
frontend/src/grpcweb/middlewares/authInterceptorMiddleware.ts
frontend/src/grpcweb/middlewares/errorNotificationMiddleware.ts
frontend/src/store/modules/sqlEditorTree.ts
frontend/src/store/modules/v1/database.ts
frontend/src/views/sql-editor/EditorCommon/SaveSheetModal.vue
frontend/src/views/sql-editor/Sheet/context.ts

If user A creates a sheet and makes some queries while he has query access to the `employee` database. When his query privileges expire or are removed, SQL Editor will keep redirecting to 403 page unless the local cache is cleared. Because the user does not have permissions to the `employee` database.
This PR will fix the above problem.
https://github.com/bytebase/bytebase/assets/24653555/9544ca2e-de41-4ff5-8b7f-e9ae73d5127c

chore(sql-editor): add `silent` option to fetch database

---

frontend/src/components/ProvideSQLEditorContext.vue

It's better to have a loading view under a large number of data requests.

chore: add loading view to sql editor

---

backend/plugin/parser/mysql/statement_type_check.go
backend/runner/plancheck/statement_type_executor.go
backend/runner/plancheck/statement_type_executor_test.go
backend/runner/plancheck/test/mysql_statement_type_check.yaml

- rename old `mysqlStatementTypeCheck` to `tidbStatementTypeCheck`.
- rename old `mysqlSDLTypeCheck` to `tidbSDLTypeCheck`.
- rename old `mysqlCreateAndDropDatabaseCheck` to `tidbCreateAndDropDatabaseCheck`
- add new `mysqlStatementTypeCheck`
- add new `mysqlSDLTypeCheck` 
- add new `mysqlCreateAndDropDatabaseCheck`

chore: migrate_statement_type_executor_mysql to antlr

---

frontend/src/components/ProvideSQLEditorContext.vue
frontend/src/views/sql-editor/SecondarySidebar/HistoryTabPane/HistoryTabPane.vue

- Moved query history fetching to history tab panel mounting. Save one request on opening SQL Editor initially.
- Added project filter to list databases if SQL Editor is opened in project mode.

perf: optimize database and query history fetching in SQL Editor

---

backend/tests/sql.go

If the advise task panic, the status of task will be set to `failed`, I think it would be better to let the test exit. Otherwise the rpc client will keep idling.

fix(sql-review): exit if advise task failed

---

frontend/src/components/ProvideSQLEditorContext.vue
frontend/src/store/modules/sqlEditorTree.ts
frontend/src/views/sql-editor/SQLEditorPage.vue
scripts/.air.toml

We should just show all databases to the users in SQL Editor. Users should see all databases, query, and request permissions if not. Hiding databases would just cause confusion especially we hide databases but not schemas or tables with right ACL check.

chore: remove isDatabaseQueriable check in SQL Editor

---

frontend/src/views/DashboardSidebar.vue

1. Increased the spacing between resources and feature sections.
2. Removed sync schema because it fits better within the project.

chore: workspace left sidebar tweak

---

backend/store/model/database.go
backend/store/model/database_test.go

We flatten the partition tables in model.DatabaseMetadata, enabling smooth auto-completion and query functionality. I avoid using slices to represent the partition tree structure as it would negatively impact lookup performance.
By the way, **there is still a long way to go before being production-ready**, such as inheriting the parent's database configuration and implementing a masking policy.

feat: flatten the parition tables in build table metadata

---

frontend/src/components/AnomalyCenter/AnomalyTable.vue
frontend/src/components/Changelist/ChangelistDetail/RawSQLEditor/RawSQLEditor.vue
frontend/src/components/IssueV1/components/GrantRequest/GrantRequestExporterForm.vue
frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
frontend/src/components/IssueV1/components/StatementSection/SDLView/SDLView.vue
frontend/src/components/MonacoEditor/DiffEditor.vue
frontend/src/components/MonacoEditor/MonacoEditor.vue
frontend/src/components/MonacoEditor/MonacoTextModelEditor.vue
frontend/src/components/MonacoEditor/WrappedDiffEditor.vue
frontend/src/components/MonacoEditor/WrappedMonacoEditor.vue
frontend/src/components/MonacoEditor/types.ts
frontend/src/views/sql-editor/EditorPanel/EditorPanel.vue
frontend/src/views/sql-editor/EditorPanel/SQLEditor.vue
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/HoverPanel/ViewInfo.vue
frontend/src/views/sql-editor/TerminalPanel/CompactSQLEditor.vue
frontend/src/views/sql-editor/TerminalPanel/TerminalPanelV1.vue

- Make only the entrance component async, the inner components are synchronous. This helps keep the code simple.
- Add loading spinners for each `<MonacoEditor>` and `<DiffEditor>` use cases.

chore(sql-editor): loading spinner for monaco-editor

---

backend/plugin/advisor/sql_review.go

We have separated the TiDB syntax check and MySQL syntax check, so there is no need to use the MySQL parser in the TiDB syntax check.
For the MySQL parser, we add a semicolon if needed in the `ParseMySQL`, there is no need to add a semicolon here.

chore(syntax-check): remove useless code for TiDB and MySQL

---

frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue

The Editor's height varies from 120px to 240px (~= 5 rows to 10 rows). The expand button shows once the editor's height exceeds the upper limit (240px). Clicking on it will open the fullscreen editor.
https://github.com/bytebase/bytebase/assets/2749742/b8b2d063-a2c7-4132-97d1-4605085ee8e4
Close BYT-4407

feat(frontend): SQL Editor height improvement for issue detail page

---

backend/api/v1/schema_design_service.go
frontend/src/components/SchemaEditorV1/Aside/BranchTree.vue
frontend/src/components/SchemaEditorV1/utils/branch.ts
frontend/src/components/SchemaEditorV1/utils/database.ts

* Skip check if schema changed for branches. (Because checking for changes is very resource intensive, especially if there are a lot of tables.)
* Add `markRaw` to those objects don't need to be reactive.

chore: update branch tree checks

---

backend/api/v1/schema_design_transformer_tidb.go

use more appropriate restore flag instead of ` tidbformat.RestoreKeyWordLowercase | tidbformat.RestoreStringSingleQuotes`
ref https://github.com/bytebase/bytebase/pull/8975

chore: use default restore flag with lowercase keyword

---

frontend/src/components/Branch/BranchDetailView.vue
frontend/src/components/Branch/BranchSQLCheckButton.vue
frontend/src/components/Branch/SchemaDesignEditor.vue
frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/AddChangePanel.vue
frontend/src/components/SchemaEditorV1/utils/branch.ts

Child branch should never depend on parent branch for anything. Once we've created a branch, it has nothing to do with the parent branch even for merging branches.

chore: remove fetchBaselineMetadataOfBranch since branches are independent

---

backend/plugin/db/mongodb/mongodb.go

Generate the test dataset:
```go
func TestInsert(t *testing.T) {
a := require.New(t)
ctx := context.Background()
url := "mongodb://h3n4l:010424@localhost:28018/large?authSource=admin"
opts := options.Client().ApplyURI(url)
client, err := mongo.Connect(ctx, opts)
a.NoError(err)
db := client.Database("large")
coll := db.Collection("test")
batch := strings.Repeat("Bytebase", 1024*1024) // 1MB
for i := 0; i < 500; i++ {
_, err := coll.InsertOne(ctx, map[string]interface{}{
"placeholder": batch,
"index":       i,
})
a.NoError(err)
}
}
```
In 2.11.1 Docker Image:
After this PR, in docker:

chore: let shell take the responsibility of reading pipe

---

frontend/src/components/Branch/BranchDataTable.vue
frontend/src/components/SchemaEditorLite/Panels/TableList/TableList.vue

- Branch list dashboard don't display the child branch id as "parent-branch-id"/"child-branch-id". Just should the child branch ID.
- Don't show row count and data size in the branch table design.

chore: update branch list and branch table content

---

frontend/src/components/IssueV1/components/IssueSearch/useSearchScopeOptions.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/utils/v1/issue/search/common.ts
frontend/src/views/DatabaseDashboard.vue

I'd like to get rid of default project/unassigned magic in both backend and frontend. In this case, the current project scope search by "default" or "unassigned" will force project-id != default/unassigned. I couldn't think of a better way than introducing "project-assigned" filter scope.

chore: search databases by project assigned status

---

backend/plugin/db/mysql/mysql.go

By using transaction, TiDB cannot execute create table and create index together in the same transaction. This is a work-around for now.

chore: do not use transaction for tidb execution

---

frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
frontend/src/components/Branch/BranchDetailView.vue
frontend/src/components/SchemaEditorLite/algorithm/index.ts
frontend/src/components/SchemaEditorLite/common.ts
frontend/src/components/SchemaEditorLite/context/edit.ts

1. Cleanup unused schema/table/column configs when saving editing metadata.
2. Strict conditions to avoid confusing edit status coloring when a table's name is another's prefix.

fix(schema-editor): minor bug fixes

---

frontend/src/components/ProjectVersionControlPanel.vue

Use `watch` dependencies instead of `watchEffect` to prevent duplicated requests. Close BYT-4669

chore: use watch instead of watchEffect

---

frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/ColumnSortedIcon.vue

> `@tanstack/vue-table` re-exports all of `@tanstack/table-core`'s and the following. https://tanstack.com/table/v8/docs/adapters/vue-table#exports
Close BYT-4674

chore: remove unused table-core package

---

backend/resources/postgres/sample_instance.go

starting sample instance in SaaS always fails, need to turn on debug log

chore: enable debug log when starting sample instance

---

frontend/pnpm-lock.yaml

Run `pnpm update` to generate the latest `pnpm-lock.yaml`.

chore: update `pnpm-lock.yaml`

---

backend/resources/postgres/sample_instance.go

otherwise port number is messed up if previous instance does not start properly

fix: increase port number right after starting sample instance

---

frontend/src/bbkit/BBAttention.vue
frontend/src/components/ProfileDropdown.vue
frontend/src/layouts/SplashLayout.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/views/auth/PasswordForgot.vue
frontend/src/views/auth/Signin.vue

If the URL query has a hint..
Otherwise if is self host
Or is SaaS
BTW, actually we need different hints for different roles, for example, the hint might be:
```
For the workspace owner, please go to the Bytebase Hub and reset your password;
For other users, please contact your Bytebase admin to reset the password
```
But that would be too complicated.

chore: update login hint

---

scripts/Dockerfile.render-demo

enable preloading database engine utils for render-demo

chore: preloading database engine utils at build time

---

helm-charts/bytebase/templates/service.yaml

To make service `bytebase-entrypoint` better cooperate with Ingress
- `bytebase-entrypoint` expose 80 port
- use `ClusterIP` type

chore: change helm svc to use 80 port

---

frontend/src/components/QuickActionPanel.vue

Only show tooltip when ellipsis happened.
https://github.com/bytebase/bytebase/assets/24653555/10c1cf28-9002-427b-bf35-0a6b01b333f8

chore: fix ellipsis style for quick action buttons

---

backend/plugin/schema/mysql/structurer.go
backend/plugin/schema/mysql/structurer_test.go
backend/plugin/schema/mysql/testdata/get_design_schema.yaml
backend/plugin/schema/mysql/testdata/parse_to_metadata.yaml

This PR is the part of support `INDEX` object in our Branch feature.
Our store protobuf schema metadata struct lacks the fields about `field length` and `direction` of index, and we should align with out store protobuf, so I remove these fields in expression.
THIS MAY CAUSE US LOSE THESE INFORMATION. But it's not a big deal, let's support index step by step.

fix(structurer): remove field length and direction in index expressions

---

backend/api/v1/changelist_service.go
frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/AddChangePanel.vue
frontend/src/components/IssueV1/logic/initialize/create.ts

Without assigning version to change in changelist, we will get "Apply change list to target db failed with a duplicate version error" since the version are generated in the backend and all versions are based on now().

chore: use the change history schema version to create plan

---

frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckDetail.vue
frontend/src/components/ProjectDatabasesPanel.vue
frontend/src/components/SQLCheck/SQLCheckDetail.vue
frontend/src/components/v2/Model/DatabaseV1Table/DatabaseLabelFilter.vue
frontend/src/components/v2/Model/ProjectV1Table.vue
frontend/src/views/DatabaseDashboard.vue

- Fix: SQL review check view style tweaks. Close BYT-4798
Before:
After:
- Fix: Force to reload page if project changed. Close BYT-4792
- Fix: Label selector out of the window. Close BYT-4794
Looks like a bug for navie-ui. Change the dropdown position from `bottom-start` to `left-start` to avoid this issue

fix: SQL review check view style tweaks

---

backend/api/v1/instance_service.go
backend/runner/schemasync/syncer.go
backend/server/onboard.go
frontend/src/components/DatabaseDetail/Settings/DatabaseSettingsPanel.vue
frontend/src/components/SQLReview/SQLReviewPolicyTable.vue

- fix BYT-4800: I found we will sync necessary instance info synchronously ([code](https://sourcegraph.com/github.com/bytebase/bytebase@22e61ae527f824dedf445be45c75ca1940954381/-/blob/backend/api/v1/instance_service.go?L198)), but the returned data is out of data.
- fix: cannot change the effective environment for database

fix: return valid instance after creation

---

frontend/src/components/Branch/BranchMergeView/BranchMergeView.vue
frontend/src/components/Branch/BranchMergeView/SelectBranchStep.vue
frontend/src/components/Branch/BranchRebaseView/BranchRebaseView.vue
frontend/src/components/Branch/BranchRebaseView/SelectBranchStep.vue

We believe that this only occurs when the window's height is reduced after the initial rendering.
Close BYT-4813

chore(frontend): always show next button on the branch page

---

backend/api/v1/database_service.go
backend/store/slow_query.go
frontend/src/components/Project/ProjectSidebar.vue
frontend/src/components/SlowQuery/Panel/IndexAdvisor.vue
frontend/src/components/SlowQuery/Panel/LogFilter.vue
frontend/src/components/SlowQuery/Panel/LogTable.vue
frontend/src/components/SlowQuery/Panel/types.ts
frontend/src/store/modules/slowQuery.ts
frontend/src/types/slowQuery.ts

- Use `NDataTable` for slow query table, and support sorting. Close BYT-4816
- Fix: invalid slow query time filter.
Before this, if users select the time range `[2024-01-02, 2024-01-09]`, the request filter is `startTime >= 2024-01-01T16:00:00.000Z AND startTime <= 2024-01-09T15:59:59.999Z`, this will be formatted as `logDate >= 20240101 && logDate < 20240110`, which is incorrect. We just simply convert them to the UTC time and drop the time and timezone info.

fix: slow query panel

---

backend/plugin/db/pg/pg.go

The issue has existed for a while, it is likely unmasked by https://github.com/bytebase/bytebase/pull/10132
I noticed this when seeing sample instance that throws an error during startup. In startup, we will try to drop the default postgres database https://github.com/bytebase/bytebase/blob/21fe05caa1e4ff2b21e0162723a3c5681b9e05d3/backend/resources/postgres/sample_instance.go#L289

fix: add DROP DATABASE to the PG non-transactional statement

---

frontend/src/components/Branch/BranchRolloutView/useVirtualBranch.ts
frontend/src/components/SchemaEditorLite/algorithm/apply-selected.ts
frontend/src/components/SchemaEditorLite/algorithm/diff-merge.ts
frontend/src/utils/schemaEditor/filter.ts
frontend/src/utils/schemaEditor/index.ts

like the backend does, we filter the database metadata fields we supported to compare and edit.
When diffing and coloring, we also only consider fields that we supported.
PTAL @h3n4l

chore(frontend): filter database metadata

---

frontend/src/components/ProvideDashboardContext.vue
frontend/src/store/modules/v1/database.ts
frontend/src/store/modules/v1/instance.ts
frontend/src/store/modules/v1/project.ts
frontend/src/views/ProjectDashboard.vue

e.g., if user has `bb.instances.list`, we'll use `listInstance` instead of `searchInstance`.

chore: update list/search api usage

---

frontend/src/components/IssueV1/components/IssueTableV1.vue

fix(frontend): duplicated escaping in issue list

---

backend/plugin/parser/mysql/mysql.go
backend/plugin/parser/mysql/mysql_test.go

After `DealWithDelimiter`, cannot distinguish the semicolon is the end of sql statement or routine body statement. So assuming contains only one sql statement between two delimiter comment after `DealWithDelimiter`.
Previous:
After:

fix(structurer): restore delimiter

---

frontend/src/components/Branch/BranchRolloutView/useVirtualBranch.ts

This fixes:
If we altered the schema of a database via issue. Then (WITHOUT refreshing the page) the page and rollout a branch of this database. We will see the schema diff with the old version of the database.

chore(frontend): fix skipCache when rollout branch

---

frontend/src/App.vue
frontend/src/grpcweb/middlewares/authInterceptorMiddleware.ts

Fix unwanted return void in auth middleware error handler.

chore: handle auth middleware error handler

---

backend/common/convert.go

`Complie` has an additional check step compared to `Parse`.

chore: use compile to validate cel expr

---

frontend/src/components/SchemaEditorLite/algorithm/diff-merge.ts

Sometimes a branch's `baselineMetadata` and `metadata` have same indexes but in different order.
This brings unexpected frontend diff coloring.
Fix part of BYT-4912
FYI @h3n4l

fix(frontend): diff indexes ignoring order

---

frontend/src/layouts/BodyLayout.vue

chore: fix dashboard padding

---

backend/plugin/schema/mysql/get_design_schema.go
backend/plugin/schema/mysql/get_design_schema_test.go
backend/plugin/schema/mysql/parse_to_metadata.go
backend/plugin/schema/mysql/state.go
backend/plugin/schema/mysql/testdata/get_design_schema.yaml
backend/plugin/schema/mysql/testdata/parse_to_metadata.yaml
backend/plugin/schema/mysql/utils.go

This PR handles default NULL/other carefully.
Our protobuf defines the default value as:
```protobuf
// The default_value is the default value of a column.
oneof default_value {
// The default is the default of a column. Use google.protobuf.StringValue to distinguish between an empty string default value or no default.
google.protobuf.StringValue default = 3;
bool default_null = 4;
string default_expression = 5;
}
```
We define the `default_null` to make us can distinguish the `DEFAULT NULL` and no default in `NOT NULL` column.
We get the column info from `INFORMATION_SCHEMA.COLUMNS`, and get the default from `COLUMN_DEFAULT` field.
>[The default value for the column. This is NULL if the column has an explicit default of NULL, or if the column definition includes no DEFAULT …

chore(structurer): handle default value in structurer for MySQL

---

backend/api/v1/branch_service.go
backend/api/v1/schema_design_merge.go

Consider the following steps:
1. Create branch `main`
2. Create branch `child` which parent is `main` created in step 1.
3. Add column `t1.c1` on branch `child`.
4. Add column `t1.c1` on database.
5. Rebase branch `child`.
6. Merge `child` to `main`.
Previous, we use `child`'s base as ancestor, and our tryDiff will compute the diff between `ancestor and child's head`, `ancestor and main's head`, merge them, and apply the result(drop column `t1.c1` in this case) to `ancestor`(`child`'s base in this case), finally, set the apply result as main's new head.

chore(branch): using head of merge to as ancestor

---

frontend/src/views/ChangeHistoryDetail.vue

using `<highlight-code-block>` might kill the render process when the SQL is large.

chore(frontend): render change history SQLs with monaco editor

---

backend/api/lsp/completion.go
frontend/src/components/MonacoEditor/composables/useSuggestOptionByLanguage.ts
go.mod
go.sum

Close part of BYT-4637
`sourcegraph/go-lsp` is a bit outdated and missing `CompletionItemLabelDetails`, so I forked it to add the needed parameter. https://github.com/bytebase/go-lsp/commit/c04b5c75010c6c20a7a5a1aa35109fd892aaada4

chore: add label details to completion item

---

backend/api/lsp/completion.go
frontend/src/components/MonacoEditor/composables/useSuggestOptionByLanguage.ts

Close part of BYT-4637
We don't need to show the second panel about details.

chore: remove detail field from completion item

---

frontend/src/components/IssueV1/components/HeaderSection/Actions/review/ReviewActionButton.vue
frontend/src/components/IssueV1/components/HeaderSection/Actions/rollout/RolloutActionButton.vue
frontend/src/components/IssueV1/logic/review.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

- Respect `issue.releasers`.
- Respect current review step's `groupValue` and `role`. (The `step.nodes` is an array but actually have exact 1 value by now)
Close BYT-4955

feat(frontend): show candidate roles when rollout/review action is not allowed

---

backend/plugin/db/starrocks/query.go
backend/plugin/db/starrocks/query_test.go
backend/plugin/db/starrocks/starrocks.go

""SELECT * FROM (%s) result LIMIT %d;" doesn't guarantee the order if the subquery has a sorting term. We will use parser to add limit clause if possible.

chore: best effort adding limit clause

---

backend/common/retry.go

The default 500ms is too short.

chore: set backoff initial interval to 5s

---

backend/api/v1/branch_service.go
backend/api/v1/schema_design_merge.go
frontend/src/components/SchemaEditorLite/edit.ts

The reason is we do not support modify them, but we include them in `filterDatabaseMetadata` to display.

fix(branch): diff should not consider engine and collation

---

frontend/src/components/Branch/BranchDetailView.vue
frontend/src/components/SchemaEditorLite/Panels/TableColumnEditor/TableColumnEditor.vue

- "Show diff with branch baseline" is now default ON to child branches and default OFF to main branches
- Fix disabling column coloring

chore(frontend): branch minor fixes

---

backend/plugin/parser/pg/query_span_extractor.go
backend/plugin/parser/pg/test-data/query_span.yaml
backend/plugin/parser/tidb/query_span_extractor.go
backend/plugin/parser/tidb/test-data/query_span.yaml

Previous, we regard the `JOIN` returns a single pseudo, by example:
```
SELECT * FROM t1 JOIN t2;
```
We will generate a pseudo table to contains the result of `t1 JOIN t2`.
But users can refer to the t1 or t2 in target field list for the above case, likes `SELECT t1.*, t2.c FROM t1 JOIN t2`, so we add the `t1` and `t2` to the from field list to search.

fix(span): table asterisk in target field and from contains join for pg

---

backend/common/cel.go

Wrap a nil error will return nil in `errors.Wrapf`.

fix: errors wrapf should wrap non-nil err

---

frontend/src/types/sql-review-schema.yaml

chore: add mysql to naming identifier no keyword rule

---

frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/form/ChangeHistoryForm.vue
frontend/src/components/Changelist/ChangelistDetail/NavBar/export.ts
frontend/src/components/SyncDatabaseSchema/DatabaseSchemaSelector.vue
frontend/src/components/SyncDatabaseSchema/index.vue
frontend/src/store/cache.ts
frontend/src/store/index.ts
frontend/src/store/modules/v1/changeHistory.ts
frontend/src/store/modules/v1/changelist.ts
frontend/src/utils/v1/instance.ts
frontend/src/views/ChangeHistoryDetail.vue

- New cache mechanism
- Cache requests along with entities (to avoid duplicated requests)
- Cache keys can now be multi-dimensional ([key1, key2, ...])
- Refactored ChangeHistory store
- ChangeHistories with BASIC or FULL view now have independent caches

refactor(frontend): change history store with new cache mechanism

---

backend/plugin/db/oracle/oracle.go

The driver timeout is 2-minute by default. We change it to zero meaning no timeout.

chore: change oracle default timeout

---

frontend/src/components/ProvideSQLEditorContext.vue

Like console dashboard, we use two-step initialization to ensure resource dependencies.

chore(sql-editor): adjust resource initialize sequence

---

frontend/src/components/ExprEditor/ConditionGroup.vue
frontend/src/components/ExprEditor/components/MultiSelect.vue
frontend/src/components/ExprEditor/components/MultiStringInput.vue
frontend/src/components/ExprEditor/components/NumberInput.vue
frontend/src/components/ExprEditor/components/OperatorSelect.vue
frontend/src/components/ExprEditor/components/SingleSelect.vue
frontend/src/components/ExprEditor/components/StringInput.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json
frontend/src/plugins/cel/logic/build.ts
frontend/src/plugins/cel/logic/resolve.ts
frontend/src/plugins/cel/types/operator.ts

The standard expr doesn't support `not in` syntax, but `!` instead.
So the expression for `database not in (a, b, c)` should be `!(database in (a, b, c))`
I'm not sure if we need to support `!` in the backend (I guess we need?)

chore: support not in operator in the frontend

---

frontend/src/store/cache.ts
frontend/src/store/modules/v1/projectProtectionRoles.ts

Useful to avoid duplicated requests when calling `getOrFetchProjectProtectionRules` concurrently
Before
After

chore(frontend): refactor project protection rules store cache

---

backend/plugin/db/pg/dump.go

Following #10890, we no longer need to split multiple SSL CAs as we now store the file path in an environment variable. It is highly unlikely to encounter the length limit of the environment variable. I have tested this with AWS RDS using global-bundle.pem.

refactor(pg_dump/tls): remove split multiple ca

---

backend/api/v1/setting_service.go
backend/enterprise/plugin/hub/hub.go
frontend/src/components/GeneralSetting/BrandingSetting.vue
frontend/src/components/GeneralSetting/SecuritySetting.vue
frontend/src/components/SensitiveData/components/ClassificationExampleModal.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json
frontend/src/types/setting.ts

- Check workspace id in claims for enterprise plan (only if the license contains the workspace id filed)
- Expose the workspace id to the frontend

chore: check workspace id in claims

---

backend/common/db_schema.go

We only support three-level classification before

fix: extract classification

---

frontend/src/components/AnomalyCenter/AnomalyCenterDashboard.vue
frontend/src/components/Issue/panel/RequestExportPanel/ExportResourceForm/DatabaseResourceSelector.vue
frontend/src/components/Issue/panel/RequestQueryPanel/DatabaseResourceForm/DatabaseResourceSelector.vue
frontend/src/components/IssueV1/logic/initialize/create.ts
frontend/src/components/ProvideDashboardContext.vue
frontend/src/components/ProvideSQLEditorContext.vue
frontend/src/components/TransferDatabaseForm.vue
frontend/src/store/modules/v1/database.ts
frontend/src/utils/database.ts
frontend/src/utils/iam/permission.ts
frontend/src/views/InstanceDetail.vue
frontend/src/views/SettingSidebar.vue

- `fetchDatabaseList` is now split into `searchDatabases` and `listDatabases`, and exposed as `searchOrListDatabases` according to `hasWorkspaceLevelProjectPermission`
- `hasWorkspaceLevelProjectPermission` now checks if the user has the given permission on workspace-level-assigned project roles
- introducing `hasWorkspaceLevelProjectPermissionInAnyProject` for special use cases
Close BYT-5071

refactor(frontend-iam): workspace level project permission and list/searchDatabases

---

frontend/src/components/Issue/panel/RequestExportPanel/index.vue
frontend/src/components/v2/Select/ProjectSelect.vue

hardcoded to be `[PresetRoleType.PROJECT_OWNER, PresetRoleType.PROJECT_DEVELOPER, PresetRoleType.PROJECT_VIEWER]`
anyone with `bb.databases.get` permission in a project.
Part of BYT-5103

chore: fix project selector filter

---

frontend/src/components/Role/Setting/components/ImportPermissionFromRoleModal.vue
frontend/src/components/Role/Setting/components/RolePanel.vue
frontend/src/utils/permission.ts

Remove the redundant `bb.` prefix.

chore: update display title of permissions

---

frontend/src/router/index.ts

There is no reason to open the sample sheet by default in the onboarding process.

chore: remove the magic sql editor onboarding

---

frontend/src/bbkit/BBTextField.vue
frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckDetail.vue
frontend/src/components/SQLReview/SQLReviewCreation.vue
frontend/src/components/SQLReview/components/SQLReviewCategoryTabFilter.vue
frontend/src/components/SQLReview/components/utils.ts
frontend/src/router/dashboard/workspaceSetting.ts
frontend/src/store/modules/sqlReview.ts
frontend/src/types/sql-review-schema.yaml
frontend/src/types/sqlReview.ts
frontend/src/views/SettingWorkspaceSQLReviewDetail.vue

- Remove `RuleType` in the frontend. We only need to update the rule convert function if the rule has its custom payload.
- Remove `CategoryType` in the frontend.
- Remove `categoryList` in `sql-review-schema.yaml`, we can build it from the rule list.
- Don't need to add `componentList: []` in `sql-review-schema.yaml` if the rule doesn't have its custom payload.

chore: simplify sql review rule definition in the frontend

---

backend/runner/slowquerysync/syncer.go
frontend/src/components/SlowQuery/Panel/types.ts

fix(slow-query): use right end timestamp and sync slow query for all PG databases

---

frontend/src/components/SensitiveData/GlobalMaskingRulesView.vue
frontend/src/layouts/BodyLayout.vue
frontend/src/layouts/common.ts
frontend/src/utils/css.ts
frontend/src/views/project/ProjectIssueDetail.vue

chore(frontend): introduce a way to override body layout style

---

frontend/src/components/VCS/VCSProviderBasicInfoPanel.vue

chore: update gitops styles

---

backend/plugin/db/mysql/sync.go
backend/plugin/parser/mysql/equal.go
backend/plugin/parser/mysql/normalize.go
backend/plugin/schema/mysql/get_design_schema.go
backend/plugin/schema/mysql/get_design_schema_test.go
backend/plugin/schema/mysql/state.go
backend/plugin/schema/mysql/testdata/get-design-schema/view/add-new-view.yaml
backend/plugin/schema/mysql/testdata/get-design-schema/view/drop-view.yaml
backend/plugin/schema/mysql/testdata/get-design-schema/view/modify-view.yaml

1. Reconcile the view def in dump and view.Definition proto field. We use dump format to trim all the leading database field in identifiers. (i.e. select \`db\`.\`table\`.\`column\` to select \`table\`.\`column\`)
2. Our dump contains temporary view definition to avoid causes view dependency error while applying the dump. But it's not-worth for us the depend query-span to get all the fields name to generate the temporary views. So we follow the strategies below:
- If user do not modify the view, we keep the temporary view.
- If user modified the view, we drop the temporary view, and rewrite the "true" view.
- If user drop view, we drop the temporary view.
- If user add view, we do not generate the temporary view.

feat: get design schema for mysql views

---

backend/plugin/parser/mysql/differ.go

> Partition, subpartition, column, index, stored routine, event, and resource group names are not case-sensitive on any platform, nor are column aliases.
https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html
close BYT-5234

fix(differ): use lower case as mysql fk names

---

backend/plugin/advisor/sql_review.go
backend/plugin/parser/base/base.go
backend/plugin/parser/mysql/mysql.go

fix: return the right syntax error line for MySQL and TiDB

---

frontend/src/components/IssueV1/components/ActivitySection/Activity/ActionSentence.vue

chore(frontend): use local timezone for change rollout time activity

---

backend/api/v1/rollout_service.go
backend/store/task.go
frontend/src/components/IssueV1/logic/action/task.ts

For data export issues, only creators are allowed to perform rollout action.

chore: update rollout permission checks

---

frontend/.gitignore
frontend/i18n.ts
frontend/package.json
frontend/pnpm-lock.yaml

1. Create `.env.i18n` file under frontend/
1. Set GOOGLE_TRANSLATE_API_KEY=xxx in the file
1. Add the key to en-US.json
1. Run `pnpm i18n`. It will call the google translate API to translate the text in other locales, and preserve the order
1. Manually inspect the translation, the translation API may go a bit far to translate the placeholder (which shouldn't be translated)
1. Start the frontend app to make sure it runs.

feat: automate i18n translation via Google Translate API

---

frontend/src/assets/css/github-markdown-style.css
frontend/src/components/MarkdownEditor/useRenderMarkdown.ts

chore: update minHeight of markdown renderer

---

backend/plugin/parser/pg/system_objects.go

As I was trying to dump schemas from TDSQL with version 16.0 of pg_dump, I got these errors from the output:
`Query was: LOCK TABLE squeeze.tables, squeeze.tables_internal, squeeze.tasks, squeeze.log, squeeze.errors, public.tbase_subscription, public.tbase_subscription_parallel IN ACCESS SHARE MODE`
According to PostgreSQL's [release note](https://www.postgresql.org/docs/current/release-16.html#RELEASE-16-PRIVILEGES) on 2023-09-14:
> Previously a user's ability to perform LOCK TABLE at various lock levels was limited to the lock levels required by the commands they had permission to execute on the table. For example, someone with [UPDATE](https://www.postgresql.org/docs/current/sql-update.html) permission could perform all lock levels except ACCESS SHARE, even though it was a lesser lock …

chore: update PostgreSQL binaries from 16.0 to 16.2

---

frontend/src/components/ColumnDataTable/MaskingLevelCell.vue
frontend/src/components/ColumnDataTable/SemanticTypeCell.vue
frontend/src/store/modules/v1/dbSchema.ts

Fix the cache for metadata, for example, 
- Semantic type is not updated because of the wrong cache (we get FULL but cache BASIC)
- Cache override by mistake
- Inconsistent view for request and cache
The metadata cache is really hard to maintain or debug
- Different views (FULL vs BASIC)
- Partial update & cache
- Invalid cache override

fix: chaos of metadata cache

---

frontend/src/views/DashboardSidebar.vue

Instead of moving all settings to the dashboard layout, I prefer remove the setting entrance from the dashboard sidebar (keep the only one in the header)

chore: remove setting entrance from dashboard sidebar

---

backend/api/lsp/completion.go
backend/api/lsp/handler.go

feat(completion): add newline as a trigger symbol

---

frontend/i18n.ts
frontend/src/locales/ja-JP.json

- Update i18n script, support specific the source and target. For example:
```bash
$ pnpm i18n
$ pnpm --source=zh-CN --target=ja-JP,es-ES i18n
```
- Replace all templates like `{user}` in the text before translation. For example, `创建用户 {user}，密码 {password}` will be formatted to `创建用户 {0}，密码 {1}`. This can avoid translation for the template text in mistake.
- Use ZH to translate the JP

chore: update i18n script

---

backend/api/v1/common.go
backend/api/v1/database_service.go
backend/api/v1/issue_service.go
backend/api/v1/logging_service.go
backend/api/v1/rollout_service.go
backend/api/v1/sql_service.go
backend/store/database.go

- Extract page token logic
- Fix `filterProjectDatabasesV2`. It looks like contains duplicate logic and inefficient
TODO:
Support search/list databases with the page token.
Because we will [filter databases with permission](https://github.com/bytebase/bytebase/blob/8230b4c6917fe0f77b4e3802d73770204b8c2139/backend/api/v1/database_service.go#L134), we need to move it (the project & database filter) to the `FindDatabaseMessage` before we support the page token.

chore: search database

---

backend/store/stats.go
frontend/src/components/Quickstart.vue
frontend/src/router/dashboard/workspace.ts

- We will check the permission in the store and switch the API (list or search), so don't need to hide the UI anymore
- Update active user count

fix: remove permission guard

---

frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
frontend/src/components/IssueV1/logic/rollout.ts

For db group related issues, we only allow to update statement to all tasks. Close BYT-5463

chore: allow to edit statement for db group related issues

---

backend/component/state/state.go
backend/runner/taskrun/schedulerv2.go

At any given time, we want at most one migration running on a database. However, with our current logic, it's not always true.
consider task 1, task 2, both changing database 1. 
1. Update task 1 status to RUNNING
2. The scheduler picks up task 1 and executes
3. Update task 2 status to RUNNING
4. nothing is stopping the scheduler from executing task 2!

fix: one migration at the same time

---

frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckDetail.vue
frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckPanel.vue
frontend/src/components/SQLCheck/SQLCheckPanel.vue

No need to show error lines for the previous SQL review result.
Part of BYT-5556

chore: only show error line for latest plan check run

---

frontend/src/components/IssueV1/components/IssueLabelSelector.vue
frontend/src/components/IssueV1/components/IssueTableV1.vue
frontend/src/components/IssueV1/components/Sidebar/IssueLabels.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

GitHub will redirect you to the label management page, while Linear will pop up a model to configure the new label.
I prefer to add the new label on the issue page, but before we figure out a better UX experience, just simply redirect users to the project setting page.

chore: redirect to configure labels

---

frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
frontend/src/components/Branch/BranchRebaseView/RebaseBranchStep.vue
frontend/src/components/Branch/BranchRebaseView/SelectBranchStep.vue
frontend/src/components/Branch/BranchRolloutView/BranchRolloutView.vue
frontend/src/components/Branch/SchemaDesignEditorLite.vue
frontend/src/components/Branch/common/BranchComparison.vue
frontend/src/components/Branch/common/BranchDetailViewer.vue
frontend/src/components/SchemaEditorLite/Panels/CommonCodeEditor.vue
frontend/src/components/SchemaEditorLite/Panels/FunctionEditor.vue
frontend/src/components/SchemaEditorLite/Panels/ProcedureEditor.vue
frontend/src/components/SchemaEditorLite/Panels/TableEditor.vue
frontend/src/components/SchemaEditorLite/Panels/common/LastUpdater.vue
frontend/src/components/SchemaEditorLite/Panels/common/common.ts
frontend/src/components/SchemaEditorLite/Panels/common/index.ts
frontend/src/components/SchemaEditorLite/SchemaEditorLite.vue
frontend/src/components/SchemaEditorLite/algorithm/utils.ts
frontend/src/components/SchemaEditorLite/context/index.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

@h3n4l It's weird that when a branch is merged or rebased, all `updater`s and `updateTime`s will be refreshed (including those not edited tables/functions blahblah). I consider this is not working as intended.

feat(branch): display the latest updater info in branch

---

frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
frontend/src/components/AlterSchemaPrepForm/DatabaseGroupPrevEditorModal.vue
frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
frontend/src/components/Branch/BranchDetailView.vue
frontend/src/components/ColumnDataTable/index.vue
frontend/src/components/SchemaEditorLite/index.ts
frontend/src/components/SchemaTemplate/FieldTemplateForm.vue
frontend/src/components/SchemaTemplate/FieldTemplateTable.vue
frontend/src/components/SchemaTemplate/TableTemplateForm.vue
frontend/src/components/SchemaTemplate/utils.ts
frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
frontend/src/utils/schemaEditor/index.ts
frontend/src/views/DatabaseDetail.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/HoverPanel/ColumnInfo.vue
frontend/src/views/sql-editor/SQLEditorPage.vue

SchemaEditorV1 and related store codes will be removed in the following PR.

refactor(schema-editor): use SchemaEditorLite to replace SchemaEditorV1

---

frontend/src/components/CustomApproval/Settings/components/CustomApproval/RuleDialog/RuleDialog.vue
frontend/src/components/CustomApproval/Settings/components/RiskCenter/RiskDialog/RiskDialog.vue
frontend/src/components/ExprEditor/ConditionGroup.vue
frontend/src/components/IssueV1/components/IssueTableV1.vue

- Sort issues in the frontend
Query in the backend is fuzzy match, but at least we can sort the response and put the full matched issues in the head.
- Optimize UI for ExprEditor

chore: sort issues

---

backend/plugin/db/mongodb/mongodb.go

Related to #11885
Adds support for MongoDB SSL options in the connection string for AWS DocumentDB connections. This enhancement allows users to specify SSL options directly in the MongoDB connection URI, improving the flexibility and security of database connections.
- **SSL Options Handling**: Implements parsing and inclusion of SSL options (`tlsCAFile`, `tlsCertificateKeyFile`, `tlsCertificateKeyFilePassword`, and `tlsAllowInvalidHostnames`) in the MongoDB connection URI. This allows users to configure SSL connections more granularly.
- **Connection String Construction**: Modifies the `getBasicMongoDBConnectionURI` function to append SSL parameters to the connection URI if provided in the connection configuration. This ensures that the SSL settings are correctly applied when …

Add SSL options support for MongoDB connections

---

frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/DetailCell/common.ts

chore(frontend): TaskRunLogTable row span calculation

---

frontend/src/components/IssueV1/components/Sidebar/EarliestAllowedTime.vue

Close BYT-5641
It's a bug for navie-ui `NDatePicker` component. When users click the "clear" in the datetime panel, will trigger twice for "on-update:value"

fix: trigger twice when clear rollout time

---

frontend/src/components/ProjectMember/ProjectMemberPanel.vue
frontend/src/store/modules/user.ts
frontend/src/store/modules/v1/issue.ts
frontend/src/store/modules/v1/projectIamPolicy.ts
frontend/src/utils/iam/permission.ts
frontend/src/utils/v1/project.ts

Approval flow for workspace-level project roles never worked before. Same for other features using `roleListInProjectV1`

fix: respect workspace level project role and all_users

---

frontend/src/components/Plan/PlanDetailPage.vue
frontend/src/components/Plan/components/HeaderSection/Actions/Actions.vue
frontend/src/components/Plan/components/PlanCheckSection/PlanCheckSection.vue
frontend/src/components/Plan/components/PlanDataTable/PlanDataTable.vue

* redirect to related issue directly if plan has an issue;
* remove the creator field from data table, as users can only see their own plans.

chore: update plan detail page

---

frontend/src/components/ChangeHistory/AffectedTablesSelect.vue
frontend/src/components/ChangeHistory/index.ts
frontend/src/components/Database/DatabaseChangeHistoryPanel.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/types/changeHistory.ts

Close BYT-5677
* show table options from database metadata instead of change histories;
* allow to input table name;
https://github.com/bytebase/bytebase/assets/24653555/0701e973-4a47-43cc-a216-d28cc198e356

chore(frontend): update affection table selector

---

backend/plugin/db/mssql/mssql.go
frontend/src/components/InstanceForm/DataSourceSection/SslCertificateForm.vue
frontend/src/utils/v1/instance.ts

Test Steps:
Using openssl to generate self sign certificate with SAN:
```bash
openssl req -x509 -nodes -newkey rsa:2048 -subj '/CN=ec2-18-163-181-181.ap-east-1.compute.amazonaws.com' -addext 'subjectAltName = DNS:ec2-18-163-181-181.ap-east-1.compute.amazonaws.com' -keyout mssql.key -out mssql.pem -days 365
sudo chown mssql:mssql mssql.pem mssql.key
sudo chmod 600 mssql.pem mssql.key
#Saving the certificate to the certs folder under /etc/ssl/ which has the following permission 755(drwxr-xr-x)
sudo mv mssql.pem /var/opt/mssql/sslcert
#Saving the private key to the private folder under /etc/ssl/ with permissions set to 755(drwxr-xr-x)
sudo mv mssql.key /var/opt/mssql/sslcert
```
Configuring SQL Server enforce TLS/SSL:
```bash
systemctl stop mssql-server
sudo cat /var/opt/mssql/mssql.conf …
```

feat: support sql server tls

---

backend/component/iam/manager.go
frontend/src/components/Role/Setting/components/RoleDataTable/cells/RoleOperationsCell.vue
frontend/src/components/User/Settings/UserDataTable/cells/UserRolesCell.vue
frontend/src/components/User/Settings/UserDataTable/index.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json

I'm also considering to hide removed roles for users in the frontend.
It's better to also update the binding for users in the backend when the role is removed, but it's inefficient. So for now just optimize the remove role alert

chore: update remove role alert

---

backend/common/util.go
backend/plugin/db/mysql/mysql.go
backend/plugin/db/pg/pg.go
backend/plugin/db/redshift/redshift.go
backend/plugin/db/risingwave/risingwave.go
backend/plugin/db/tidb/tidb.go

oneshot if too many commands, otherwise too many task run logs and round-trips will cause pain.

chore: add exceeded commands

---

frontend/src/components/ChangeHistory/ChangeHistoryDetail.vue

fix: affected tables layout

---

frontend/src/components/SchemaEditorLite/Panels/TableColumnEditor/components/DefaultValueCell.vue

- The text input box is disabled when the default option is "No default" or "Default NULL".
- Only the down arrow is clickable.
- The text input box is accessible. While typing in anything, the default option changes to "Default value".

chore(frontend): default value input user interaction

---

frontend/src/views/sql-editor/TerminalPanel/CompactSQLEditor.vue
frontend/src/views/sql-editor/TerminalPanel/utils.ts

If I typed `GET a;`, the key is `a;` instead of `a`.

chore: enter without semi will trigger execute for redis in sql editor admin mode

---

frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
frontend/src/components/AlterSchemaPrepForm/SchemalessDatabaseTable.vue
frontend/src/components/DataExportPrepForm/DataExportPrepForm.vue
frontend/src/components/DatabaseInfo.vue
frontend/src/components/IssueV1/components/StageSection/StageInfo/DatabaseInfo.vue
frontend/src/components/v2/Model/DatabaseV1Table/DatabaseV1Table.vue
frontend/src/components/v2/Model/DatabaseV1Table/cells/DatabaseNameCell.vue
frontend/src/views/sql-editor/Setting/Project/Detail.vue

Only show SQL editor button in 
* database detail page;
* table detail drawer;
* external table detail drawer.

chore: remove sql editor button in database table

---

frontend/src/components/MonacoEditor/editor.ts
frontend/src/components/MonacoEditor/lsp-client.ts

- Handle WebSocket "onerror" event
- Fallback to legacy browser-side LSP when WebSocket error occurred.
Close BYT-5632

chore(sql-editor): improve SQL Editor's WebSocket experience 

---

frontend/src/views/sql-editor/EditorCommon/ReadonlyDatasourceHint.vue

A temp way to BYT-5378. Not the final answer.

chore(sql-editor): use warning color for RO datasource indicator

---

frontend/src/grpcweb/index.ts
frontend/src/grpcweb/middlewares/index.ts
frontend/src/grpcweb/middlewares/simulateLatencyMiddleware.ts

Useful for testing and debugging.
Disabled by default. Can be enabled by some magical JavaScript console codes.

chore(frontend-dev): simulate latency middleware

---

frontend/src/components/SchemaEditorLite/Panels/PartitionsEditor/PartitionsEditor.vue
frontend/src/components/SchemaEditorLite/Panels/PartitionsEditor/components/OperationCell.vue

By "new partition" we mean
- New partition on an existing table.
- Any partitions on a newly created table.
Close BYT-5841

chore(frontend): allow editing and dropping newly created partitions

---

backend/plugin/db/elasticsearch/spliter.go
backend/plugin/db/elasticsearch/spliter_test.go

fix:elasticsearch split statements chinese garbled code(#12658)

fix: elasticsearch split statements chinese garbled code(#12658)

---

frontend/src/components/Branch/BranchCreateView.vue
frontend/src/components/Branch/BranchDetailView.vue
frontend/src/components/Branch/BranchMergeView/BranchMergeView.vue
frontend/src/components/Branch/BranchRebaseView/BranchRebaseView.vue
frontend/src/components/KBar/useDatabaseActions.ts
frontend/src/components/KBar/useProjectActions.ts
frontend/src/components/Project/ProjectSidebarV1.vue
frontend/src/components/ProvideDashboardContext.vue
frontend/src/components/v2/Select/ProjectSelect.vue
frontend/src/layouts/BodyLayout.vue
frontend/src/store/modules/user.ts
frontend/src/store/modules/v1/index.ts
frontend/src/store/modules/v1/permission.ts
frontend/src/store/modules/v1/projectIamPolicy.ts
frontend/src/utils/iam/permission.ts
frontend/src/utils/v1/database.ts
frontend/src/utils/v1/project.ts
frontend/src/utils/v1/worksheet.ts
frontend/src/views/DashboardSidebar.vue

- Add a full-screen mask spinner when needed. Especially switching between projects or the workspace. (Will fetch instance and database resources, which might be slow). Blocking users from clicking the page elements too quickly. This request will be cached if possible.
- [IMPORTANT] permission module refactored
- Cache workspace-level and project-level permission calculation results, which might be called tens of thousands of times. The cache entries will be and should be expired manually when a user is updated (e.g. role changed) or a `projectIamPolicy` is updated (e.g. a project's iam bindings changed).
- Permission check utility functions have been refactored to `usePermissionStore`.
- Optimize `<BodyLayout>` implementation, will not render 2 `<router-view>`s for desktop/mobile view's …

chore(frontend): performance optimization (part.2)

---

frontend/src/components/MonacoEditor/MonacoTextModelEditor.vue
frontend/src/components/MonacoEditor/composables/index.ts
frontend/src/components/MonacoEditor/composables/useLSPConnectionState.ts
frontend/src/components/MonacoEditor/dev.ts
frontend/src/components/MonacoEditor/editor.ts
frontend/src/components/MonacoEditor/lsp-client.ts
frontend/src/components/MonacoEditor/utils.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/utils/util.ts

- Initializing LSP will not block the editor itself from loading. Still, we can write something without auto-completion.
- Automatically reconnect 5 times after disconnected
- Error notification when disconnected and failed to retry.
- Visual indicator for connection state.

chore(sql-editor): WebSocket auto reconnect and error notification

---

backend/store/role.go

fix the following error in the latest main branch
```
time=2024-07-12T13:46:42.850+08:00 level=ERROR source=server/server.go:291 msg="v1 server panic error" error="error: assignment to entry in nil map\nruntime.mapassign_faststr\n\t/usr/local/go/src/runtime/map_faststr.go:205\ngithub.com/bytebase/bytebase/backend/store.(*Store).ListRoles\n\t/Users/steven/Projects/bytebase/bytebase/backend/store/role.go:173\ngithub.com/bytebase/bytebase/backend/api/v1.(*RoleService).ListRoles\n\t/Users/steven/Projects/bytebase/bytebase/backend/api/v1/role_service.go:40\ngithub.com/bytebase/bytebase/proto/generated-go/v1._RoleService_ListRoles_Handler.func1\n\t/Users/steven/Projects/bytebase/bytebase/proto/generated-go/v1/role_service_grpc.pb.go:140\ngithub.com/grpc-ecosystem/go-grpc-middleware/v2/intercepto …
```

fix: nil map error

---

backend/plugin/parser/mysql/differ.go
backend/plugin/parser/mysql/differ_test.go
backend/plugin/parser/tidb/differ.go
backend/plugin/parser/tidb/differ_test.go

Dropping table referenced by a foreign key is the only case we don't support well. But we probably should not allow users do so as it will leave the schema in a strange state.

chore: move setting foreign key checks

---

backend/plugin/db/redis/redis.go

GCP Managed redis do not support it.
https://github.com/redis/go-redis/discussions/2537

chore: remove client set app name in redis

---

backend/api/v1/instance_service.go
backend/runner/slowquerysync/syncer.go

We should not limit the project when checking if pg slow query is enabled

fix: remove project for pg slow query log

---

frontend/src/components/IssueV1/components/TaskRunSection/TaskRunSession/PostgresSessionTable.vue

We have space to put wording, no need to use an icon

chore: remove unnecessary blocking session icon

---

frontend/src/views/sql-editor/EditorCommon/AdminModeButton.vue
frontend/src/views/sql-editor/EditorCommon/EditorAction.vue

chore: improve SQL Editor button bar style

---

backend/plugin/db/redis/redis.go

fix wrong error message when explaining redis command, which was "MongoDB does not support EXPLAIN"

fix: error message when explaining redis command

---

backend/api/v1/database_group_service.go

Close BYT-6057
Background: If only basic information is returned in CreateDatabaseGroup/UpdateDatabaseGroup, we need to call GetDatabaseGroup with full view in frontend to get the match/unmatched databases again.

chore: return full view of db group in CreateDatabaseGroup/UpdateDatabaseGroup

---

frontend/src/components/Icon/ColumnIcon.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/SchemaPane.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/ColumnNode.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/CommonNode.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/DatabaseNode.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/DummyNode.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/ExternalTableNode.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/FunctionNode.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/PartitionTableNode.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/ProcedureNode.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/SchemaNode.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/TableNode.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/TextNode.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/ViewNode.vue

- Add `ColumnIcon` to non-pk and non-index columns
- Introduce "folder" icon to "Tables", "Views", etc. 
- Pixel-perfect icon alignment
- <img width="347" alt="image" src="https://github.com/user-attachments/assets/a3f9958a-e0c2-4673-becb-baf8fa01a48b">
- <img width="347" alt="image" src="https://github.com/user-attachments/assets/f7bfaf5a-31f0-4599-a36f-e72a13c8f6ad">
- <img width="300" alt="image" src="https://github.com/user-attachments/assets/b87dafc9-818d-49db-94f8-58544c2c5072">
- <img width="348" alt="image" src="https://github.com/user-attachments/assets/b82b23e4-1658-474a-a26e-a34e9cd91f9a">

chore(sql-editor): icons improvements

---

backend/api/v1/project_service.go
backend/api/v1/workspace_service.go

https://google.aip.dev/154
Let's use the weak consistency requirement for simpler usages such as Terraform.
```
If the user does not send an etag value at all, the service should permit the request. However, services with strong consistency or parallelism requirements may require users to send etags all the time and reject the request with an INVALID_ARGUMENT error in this case.
```

chore: write-through for empty etags

---

frontend/src/components/BytebaseLogo.vue
frontend/src/customAppProfile.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/types/appProfile.ts
frontend/src/utils/v1/sql.ts
frontend/src/views/sql-editor/AsidePanel/SchemaPane/actions.tsx
frontend/src/views/sql-editor/EditorPanel/EditorPanel.vue
frontend/src/views/sql-editor/EditorPanel/Panels/FunctionsPanel/FunctionsTable.vue
frontend/src/views/sql-editor/EditorPanel/Panels/ProceduresPanel/ProceduresTable.vue
frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/ColumnsTable.vue
frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/TablesPanel.vue
frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/TablesTable.vue
frontend/src/views/sql-editor/EditorPanel/Panels/ViewsPanel/ViewsTable.vue
frontend/src/views/sql-editor/EditorPanel/StandardPanel/StandardPanel.vue
frontend/src/views/sql-editor/EditorPanel/Welcome/Button.vue
frontend/src/views/sql-editor/EditorPanel/Welcome/Welcome.vue
frontend/src/views/sql-editor/EditorPanel/Welcome/index.ts
frontend/src/views/sql-editor/EditorPanel/context/index.ts
frontend/src/views/sql-editor/EditorPanel/context/scroll.ts
frontend/src/views/sql-editor/EditorPanel/types.ts
frontend/src/views/sql-editor/SQLEditorHomePage.vue

* "View detail" now goes to corresponding right metadata panel rather than database detail page
* Double-clicking, "Preview table data" and "Generate SQL" are now more powerful
* <img width="544" alt="image" src="https://github.com/user-attachments/assets/d8ac1232-807c-40cb-bf80-d61566fbff94">
* <img width="656" alt="image" src="https://github.com/user-attachments/assets/16e82fa0-5244-4135-ac7f-4b15ba715af4">
* When coming from "View detail" of the schema tree, the list will scroll to the element automatically.
- Tile-style welcome page
- ![localhost_3000_sql-editor_projects_default(720P)](https://github.com/user-attachments/assets/c62aec0d-e142-468a-8baa-2c15442fce23)
Close BYT-5490, BYT-5773

chore(sql-editor): some UI improvements

---

frontend/src/components/AdvancedSearch/useCommonSearchScopeOptions.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/utils/v1/advanced-search/common.ts
frontend/src/views/DatabaseDashboard.vue

* hide instance/database scope if no project selected;
* remove `project-assigned` scope, as users can select Unassigned project instead;

chore: update common search options

---

frontend/src/components/AdvancedSearch/useCommonSearchScopeOptions.ts
frontend/src/components/PasswordSigninForm.vue
frontend/src/components/v2/Model/Instance/InstanceV1Table/InstanceV1Table.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/utils/v1/advanced-search/common.ts
frontend/src/utils/v1/instance.ts
frontend/src/views/InstanceDashboard.vue
frontend/src/views/sql-editor/EditorCommon/QueryContextSettingPopover.vue

- Show multi-data sources in the instance table
- Support filter by address
- The address can be filtered by host, port or type

chore: support filter by address

---

frontend/src/components/ProvideSQLEditorContext.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/sqlEditor/tab.ts
frontend/src/utils/sqlEditor.ts
frontend/src/views/sql-editor/AsidePanel/SchemaPane/actions.tsx
frontend/src/views/sql-editor/ConnectionPanel/ConnectionPanel.vue
frontend/src/views/sql-editor/EditorCommon/AdminModeButton.vue
frontend/src/views/sql-editor/EditorCommon/EditorAction.vue
frontend/src/views/sql-editor/EditorCommon/QueryContextSettingPopover.vue
frontend/src/views/sql-editor/EditorCommon/SheetConnectionIcon.vue
frontend/src/views/sql-editor/EditorPanel/Panels/ExternalTablesPanel/ExternalTableColumnsTable.vue
frontend/src/views/sql-editor/EditorPanel/Panels/ExternalTablesPanel/ExternalTablesTable.vue
frontend/src/views/sql-editor/EditorPanel/Panels/FunctionsPanel/FunctionsTable.vue
frontend/src/views/sql-editor/EditorPanel/Panels/ProceduresPanel/ProceduresTable.vue
frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/ColumnsTable.vue
frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/ForeignKeysTable.vue
frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/IndexesTable.vue
frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/PartitionsTable.vue
frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/TableDetail.vue
frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/TablesPanel.vue
frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/TablesTable.vue
frontend/src/views/sql-editor/EditorPanel/Panels/ViewsPanel/ViewsTable.vue
frontend/src/views/sql-editor/EditorPanel/types.ts
frontend/src/views/sql-editor/TabList/TabItem/AdminLabel.vue
frontend/src/views/sql-editor/TabList/TabItem/Prefix.vue

Following #13407
- Add indexes, foreign keys and partition tables table in the right, and can be navigated through the tree.
- Minor changes
- The set connection drawer now opens from the right side of the window.
- "Explain" button is removed. While cmd/ctrl + E keyboard shortcut is still working. Same to "Explain" in the context menu.
- Show no "Run / Run selected" text in the run button.
- Admin mode changes
- Show no "Run" button in admin mode.
- Entering admin mode will not open a new tab, either bringing the current tab's statements.
- Admin mode is dangerous, so when the page is refreshed or reopened, all admin mode tabs will be turned back to normal tabs.

feat(sql-editor): UI improvements (part.2)

---

backend/plugin/db/clickhouse/query.go

In the original code, if ClickHouse executed a query and encountered an error, the error was ignored, and the code returned `nil, nil`. This behavior led to potential panics later in the code, which expected non-nil results.
This fix ensures that any error encountered during a ClickHouse query is directly returned, preventing panics and allowing proper error handling.

fix: handle error properly in ClickHouse query

---

frontend/src/components/CommonSidebar.vue
frontend/src/components/ProfileDropdown.vue
frontend/src/components/misc/Version.vue
frontend/src/customAppProfile.ts
frontend/src/layouts/BodyLayout.vue
frontend/src/types/appProfile.ts
frontend/src/views/SettingSidebar.vue
frontend/src/views/sql-editor/AsidePanel/GutterBar/GutterBar.vue
frontend/src/views/sql-editor/SQLEditorSettingPage.vue
frontend/src/views/sql-editor/Setting/SettingButton.vue
frontend/src/views/sql-editor/Setting/Sidebar/Sidebar.vue
frontend/src/views/sql-editor/TabList/TabList.vue

- Move subscription and version info to the profile dropdown
- Move SQL Editor setting button to the top-right corner next to the profile icon, similar to console
- Unify sidebar and back button style for workspace and SQL Editor settinggg

chore(frontend): tweaking setting sidebar style

---

backend/plugin/parser/mysql/query_span_extractor.go
backend/plugin/parser/mysql/query_span_test.go
backend/plugin/parser/mysql/test-data/query-span/case_insensitive.yaml
backend/plugin/parser/mysql/test-data/query-span/standard.yaml
backend/plugin/parser/pg/query_span_extractor.go
backend/plugin/parser/pg/query_span_test.go
backend/plugin/parser/pg/test-data/query_span.yaml
backend/plugin/parser/plsql/query_span_extractor.go
backend/plugin/parser/plsql/query_span_test.go
backend/plugin/parser/plsql/test-data/query_span.yaml
backend/plugin/parser/snowflake/query_span_extractor.go
backend/plugin/parser/snowflake/query_span_test.go
backend/plugin/parser/snowflake/test-data/query-span/cte.yaml
backend/plugin/parser/snowflake/test-data/query-span/pivot.yaml
backend/plugin/parser/snowflake/test-data/query-span/set-operator.yaml
backend/plugin/parser/snowflake/test-data/query-span/standard.yaml
backend/plugin/parser/snowflake/test-data/query-span/subquery.yaml
backend/plugin/parser/tidb/query_span_extractor.go
backend/plugin/parser/tidb/query_span_test.go
backend/plugin/parser/tidb/test-data/query_span.yaml
backend/plugin/parser/tsql/query_span_extractor.go
backend/plugin/parser/tsql/query_span_test.go
backend/plugin/parser/tsql/test-data/query-span/case-sensitivity.yaml
backend/plugin/parser/tsql/test-data/query-span/join.yaml
backend/plugin/parser/tsql/test-data/query-span/standard.yaml
frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue

"default" is better than "connected". It's consistent with other products, and database/schema in views with fully qualified names are not "connected".

chore: connected wording

---

backend/plugin/db/mysql/query.go
backend/plugin/db/mysql/query_test.go

This will be consistent behavior with fmt.Sprintf("SELECT * FROM (%s) result LIMIT %d;", util.TrimStatement(stmt), limit).

chore: respect the min(user limit, request limit)

---

backend/api/lsp/fs_handler.go

In backend, we follow the LSP spec which requires the row/character are 0-based. For ANTLR, the line is 1-based and the column is 0-based.
Previous:
After:

feat(syntax-check): more precise error position

---

frontend/src/components/MonacoEditor/editor.ts

chore: disable monaco-editor's inline suggest toolbar

---

backend/plugin/schema/mysql/stringify_table.go

Generate `default '1'` instead of  `DEFAULT 'value:"1"'`.

fix: stringify table default value

---

backend/plugin/db/pg/pg.go

fix: use correct regexp to check VACUUM statements

---

backend/plugin/db/redshift/redshift.go
backend/plugin/db/risingwave/risingwave.go
backend/plugin/db/snowflake/snowflake.go
backend/plugin/parser/pg/query_span_extractor.go
backend/plugin/parser/plsql/query_span_test.go
backend/plugin/parser/snowflake/query_span_extractor.go
backend/plugin/parser/tsql/query_span_extractor.go

Part of BYT-6223, except SQL Server.
Refer to the schema engine required by the frontend.

chore: use queryContext.schema for other engines

---

backend/api/lsp/fs_handler.go
backend/plugin/parser/base/base.go

chore: expose antlr runtime raw error message in syntax checking

---

frontend/src/components/IssueV1/components/IssueTableV1.vue

chore: tweak position of issue action bar

---

frontend/src/components/ColumnDataTable/MaskingLevelCell.vue
frontend/src/components/User/Settings/RemoveGroupButton.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/router/dashboard/workspace.ts
frontend/src/router/dashboard/workspaceRoutes.ts
frontend/src/views/DashboardSidebar.vue
frontend/src/views/SettingWorkspaceDataAccessControl.vue
frontend/src/views/SettingWorkspaceDataClassification.vue
frontend/src/views/SettingWorkspaceDataMasking.vue
frontend/src/views/sql-editor/EditorCommon/DataTable/SensitiveDataIcon.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/SensitiveDataIcon.vue

**BREAK CHANGES**
- Deprecate `/anomaly-center`
- Deprecate `/sensitive-data`, and split it into `/data-masking`, `/data-classification`, `/data-access-control`

chore: restructure workspace sidebar

---

backend/plugin/parser/plsql/plsql_test.go
go.mod
go.sum

chore: oracle parser compatibility

---

backend/plugin/db/cockroachdb/sync.go
backend/plugin/parser/cockroachdb/system_objects.go

Skip sync system objects for cockroachdb to align with other engines.

chore(cockroachdb): skip sync system object

---

backend/plugin/parser/pg/query_span_extractor.go
backend/plugin/parser/pg/test-data/query_span.yaml
backend/store/model/database.go

Let's take a look at it from the PostgreSQL's point of view, there are some cases we need to consider:
1. Different argument counts, for example foo(a int, b int) and foo(a int), users call foo(1), we know they want to call the first one.
2. Variadic argument type, for example foo(a int, b int) and foo(VARIADIC a []int),  users call foo(1, 2). We cannot distinguish which one is desired. Actually, PostgreSQL doesn't know either. Just an example of the complexity of VARIADIC.
3. Default argument type, for example foo(a int) and foo(a int, b int default 1), users call foo(1). We cannot distinguish.
Argument counts are the same, but different argument types. The implicit type casting is complex.
We handle the case 1, 2, 3 only.

feat: PostgreSQL query span support overloaded functions

---

frontend/src/components/DeploymentConfigTool/DeploymentMatrix.vue
frontend/src/components/DeploymentConfigTool/SelectorItemV2.vue
frontend/src/components/TenantDatabaseTable/DeploymentMatrixDataTable.vue
frontend/src/utils/label.ts

We still want to show the matrix in empty db state. However there was a bug removing the last row. The intended logic was only to remove the last empty label row. But as the screenshot shows, it would remove the valid label row as well.

feat: render empty deployment matrix properly

---

frontend/src/views/sql-editor/EditorCommon/ResultView/DataTableLite/ColumnHeader.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTableLite/DataTableLite.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTableLite/TableCell.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTableLite/useTableResize.ts

Now we only estimate the first 1 screen (~= 10+ rows * 20 cols) that makes the performance acceptable.
Double-clicking to auto-resize one column is on the way

feat(sql-editor): bring auto-column-sizing back

---

frontend/src/components/GeneralSetting/DatabaseChangeModeSetting.vue
frontend/src/components/MonacoEditor/MonacoTextModelEditor.vue
frontend/src/components/v2/Form/SearchBox.vue
frontend/src/store/modules/sqlEditor/tab.ts
frontend/src/views/sql-editor/AsidePanel/SchemaPane/SchemaPane.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/DependentColumnNode.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/actions.tsx
frontend/src/views/sql-editor/AsidePanel/SchemaPane/common.ts
frontend/src/views/sql-editor/AsidePanel/WorksheetPane/WorksheetPane.vue
frontend/src/views/sql-editor/EditorCommon/SaveSheetModal.vue
frontend/src/views/sql-editor/EditorPanel/Panels/ExternalTablesPanel/ExternalTableColumnsTable.vue
frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/ColumnsTable.vue
frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/IndexesTable.vue
frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/TablesTable.vue
frontend/src/views/sql-editor/EditorPanel/Panels/ViewsPanel/ColumnsTable.vue
frontend/src/views/sql-editor/EditorPanel/Panels/ViewsPanel/ViewsTable.vue
frontend/src/views/sql-editor/EditorPanel/common/EllipsisCell.vue
frontend/src/views/sql-editor/EditorPanel/common/common.ts
frontend/src/views/sql-editor/EditorPanel/common/index.ts
frontend/src/views/sql-editor/EditorPanel/context/index.ts
frontend/src/views/sql-editor/TabList/TabList.vue

- tooltips for comment columns. (Close BYT-6383)
- disable database change mode radio buttons when not allowed to editor. (Close BYT-6385)
- adjust gaps. (Close BYT-6394)
- double click on folders now toggle collapse/expand. (Close BYT-6392)
- hide filename in monaco-editor problem viewer widgets. (Close BYT-6391)
- handle saving empty worksheets. (Close BYT-6389)
- clone ui state from current tab when opening new tab. (Close BYT-6390)
- clicking on dependent column nodes now goes to the referenced column's definition. (Close BYT-6387)
- capture keydown inputs in sidebar, and auto focus the search box when keys pressed. (Close BYT-6386)

chore(sql-editor): some fixes

---

backend/component/iam/acl.yaml

fix: add `bb.sheets.get` permission to project releaser

---

backend/plugin/parser/pg/split.go

chore: return syntax error instead of panic for pg splitter

---

frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTableLite/DataTableLite.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTableLite/TableCell.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTableLite/useTableResize.ts

using bi-directional virtual scroll NDataTable
possible to 
- render mass data (1000 rows * 1000 cols) rapidly (~= 2 seconds)
- smooth scrolling
- pixel-perfect auto adjust column width (rows * cols in the first screen)
- char-width based guessed column width for the reset columns
- drag the header gaps to manually adjust column width
- double clicking the header gap to auto adjust width (excel-like)

feat(sql-editor): mass query result data rendering in SQL Editor

---

backend/migrator/migrator.go
backend/plugin/db/driver.go
backend/runner/taskrun/database_create_executor.go
backend/runner/taskrun/executor.go
backend/runner/taskrun/schema_update_ghost_cutover_executor.go
backend/utils/utils.go

copy paste utils.ExecuteMigration to separate places, because
1. we are about to change taskrun executor logic
2. migrator ExecuteMigration stays unchanged

refactor: execute migration

---

frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/plugins/ai/components/ActionBar.vue
frontend/src/plugins/ai/components/ChatPanel.vue
frontend/src/plugins/ai/components/ChatView/AIMessageView.vue
frontend/src/plugins/ai/components/ChatView/Markdown/CodeBlock.vue
frontend/src/plugins/ai/components/ChatView/Markdown/InsertAtCaretIcon.vue
frontend/src/plugins/ai/components/ChatView/Markdown/Markdown.vue
frontend/src/plugins/ai/components/ChatView/UserMessageView.vue
frontend/src/plugins/ai/components/DynamicSuggestions.vue
frontend/src/plugins/ai/components/HistoryPanel/HistoryPanel.vue
frontend/src/plugins/ai/components/PromptInput.vue
frontend/src/plugins/ai/components/editor-actions.ts
frontend/src/plugins/ai/logic/prompt.ts
frontend/src/plugins/ai/logic/useDynamicSuggestions.ts
frontend/src/views/sql-editor/EditorCommon/OpenAIButton/OpenAIButton.vue
frontend/src/views/sql-editor/EditorPanel/Panels/Panels.vue
frontend/src/views/sql-editor/EditorPanel/Panels/ViewsPanel/DefinitionViewer.vue
frontend/src/views/sql-editor/EditorPanel/Panels/ViewsPanel/ViewDetail.vue
frontend/src/views/sql-editor/EditorPanel/Panels/common/CodeViewer.vue
frontend/src/views/sql-editor/EditorPanel/StandardPanel/SQLEditor.vue
frontend/src/views/sql-editor/EditorPanel/StandardPanel/StandardPanel.vue
frontend/src/views/sql-editor/SQLEditorHomePage.vue
frontend/src/views/sql-editor/context.ts

- Re-layout AI message and add "Insert at caret" button. (Close BYT-6468, BYT-6470)
- "Explain code" and "Find problems" will always respect code editor's selection state. (Close BYT-6469)
- Display and consume prompt suggestions one-by-one. (Close BYT-6471)
- Remember AI Assistant panel's width. (Close BYT-6472)
- Re-org AI Assistant actions (Close BYT-6473)
- Remove "New chat"
- Clicking the AI button now toggles the panel (instead of opening only)
- Remove sparkle icon in AI prompt input box. (Close BYT-6474)
- Update the default input template of "New chat using selection". (Close BYT-6475)

feat(sql-editor): AI Assistant improvements

---

backend/plugin/parser/pg/system_objects.go

AlloyDB has two internal DBs: alloydbmetadata is the other.

feat: ignore alloydbmetadata database

---

frontend/src/plugins/ai/components/ChatPanel.vue
frontend/src/plugins/ai/components/DynamicSuggestions.vue
frontend/src/plugins/ai/components/ProvideAIContext.vue
frontend/src/plugins/ai/logic/prompt.ts
frontend/src/plugins/ai/logic/useDynamicSuggestions.ts
frontend/src/plugins/ai/types/context.ts
frontend/src/views/sql-editor/EditorPanel/Panels/Panels.vue
frontend/src/views/sql-editor/EditorPanel/StandardPanel/SQLEditor.vue
frontend/src/views/sql-editor/EditorPanel/StandardPanel/state.ts

- Improved "Insert at caret" implementation to make this feature more robust. (Close BYT-6483)
- Hidden metadata text in prompts now only sends tables in selected schema and won't add schema prefixes before table names (if selected). That's because AI seems to consider "public.employee" and "employee" as different tables, making the answers very weird. (Close BYT-6478)
- Tweak some prompts. Now AI assistant will not answer "Bytebase" which is weird. And will not repeat incomplete SQL statements back when asking "Explain the following SQL code". (Close BYT-6475)
prompts are magic...

chore(sql-editor): AI assistant minor updates

---

backend/bin/server/cmd/profile.go
backend/bin/server/cmd/root.go
backend/component/config/profile.go
backend/runner/taskrun/schedulerv2.go
backend/store/task.go

pass `--development-versioned` to enable.
The scheduler schedules tasks on the same database by the order of the version. The order is undefined if the version is the same.

feat: scheduler versioned

---

frontend/src/types/sql-review-schema.yaml

Since we add engine-specific rules.
This caused the problem in generating SQL review guide for bytebase.com

fix: remove sql review rule without engine

---

backend/api/v1/branch_service.go
backend/api/v1/database_converter.go
backend/plugin/db/pg/sync.go
frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/FunctionNode.vue

close BYT-6512
We only support function signatures for Postgres currently.

feat(sql-editor): show function signature instead of name

---

backend/server/server.go

Help API users find URL errors.
```
{
"code": 5,
"message": "Routing error. Please check request URI /v1/projets/tnt/releases",
"details": []
}
```
```
{
"code": 5,
"message": "Not Found",
"details": []
}
```

chore: better error for wrong API url

---

frontend/vite.config.ts

Refer to 
* https://stackoverflow.com/questions/72795666/how-to-fix-vite-build-parser-error-unexpected-token-in-third-party-dependenc
* https://github.com/posva/unplugin-vue-router/discussions/429

chore: fix build error

---

frontend/src/bbkit/BBButtonConfirm.vue
frontend/src/bbkit/types.ts
frontend/src/components/Branch/BranchDetailView.vue
frontend/src/components/EnvironmentForm/Form.vue
frontend/src/components/Instance/InstanceArchiveRestoreButton.vue
frontend/src/components/InstanceForm/DataSourceSection/DataSourceTabs.vue
frontend/src/components/Member/EditMemberRoleDrawer.vue
frontend/src/components/Project/ProjectArchiveRestoreButton.vue
frontend/src/components/ProjectMember/ProjectMemberRolePanel/EditProjectRolePanel.vue
frontend/src/components/ProjectMember/ProjectMemberRolePanel/index.vue
frontend/src/components/ProjectWebhookForm.vue
frontend/src/components/RepositoryPanel.vue
frontend/src/components/SQLReview/components/SQLReviewPolicyDataTable.vue
frontend/src/components/SQLReview/components/SQLReviewPolicyTable.vue
frontend/src/components/SSO/IdentityProviderCreateForm.vue
frontend/src/components/User/Settings/UserDataTable/cells/UserOperationsCell.vue
frontend/src/views/SettingWorkspaceSQLReviewDetail.vue
frontend/src/views/SettingWorkspaceVCSDetail.vue

* `style: BBButtonConfirmStyle` -> `type: BBButtonConfirmType` to avoid conflicts with the HTML element "style" attribute.
* `type: "text" | "default"` -> `text: boolean`

chore: update `BBButtonConfirm` props

---

quickstart/.env

When running `docker compose` in the [quickstart guide](https://github.com/bytebase/bytebase/tree/main/quickstart), I noticed that BB_VERSION wasn't specified. I resolved this by creating a .env file to define it.

chore: add BB_VERSION for docker-compose quickstart

---

frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue

- Use `<DataTable>` for small result sets.
- Use `<DataTableLite>` for large ones (either >= 200 rows or >= 50 cols)

chore(sql-editor): mixed table rendering strategy

---

frontend/src/components/ChangeHistory/ChangeHistoryDataTable.vue
frontend/src/components/ChangeHistory/ChangeHistoryDetail.vue
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunComment.vue
frontend/src/components/Release/ReleaseDataTable.vue
frontend/src/components/SyncDatabaseSchema/DatabaseSchemaSelector.vue
frontend/src/utils/v1/changeHistory.ts
frontend/src/views/DatabaseDetail/DatabaseDetail.vue

Part of BYT-6409
* don't show `releaseVersion`, `description`, `source` and `executionDuration`  of `ChangeHistory` in UI, as the new `Changelog` doesn't has these fields.

chore: update change history display

---

backend/api/v1/instance_service.go

Optimize memory allocation and string concatenation in instance service:
1. Replace fmt.Sprintf with strings.Builder in convertToInstanceRoles
2. Pre-allocate Builder capacity to avoid reallocation
3. Extract buildRoleName function to improve code reusability
4. Keep using simple string concatenation for one-time operations
This change reduces memory allocations and improves performance in hot paths.
Fixes profile showing high memory usage from fmt.Sprintf.

perf: optimize string concatenation in instance service

---

frontend/src/store/modules/v1/projectIamPolicy.ts
frontend/src/types/iam/permission.ts
frontend/src/types/utils.ts
frontend/src/utils/v1/database.ts

roles with
- `bb.databases.execute` 
- `bb.databases.queryDML`
- `bb.databases.queryDDL`
- `bb.databases.queryInfo`
- `bb.databases.queryExplain`
should also be allowed to choose databases in SQL Editor. 
That allows admins to set up some roles that can only access the database schema but cannot query the data.

chore(sql-editor): update isDatabaseV1Queryable logic

---

frontend/src/components/IssueV1/components/TaskListSection/TaskCard.vue

* always show schema version in UI;
* for unversioned tasks, the schema version of task should be empty;

chore: handle task schema version

---

backend/api/v1/auth_service.go
backend/api/v1/group_service.go
frontend/src/components/Quickstart.vue

- Only allow adding end users to the group. Close BYT-6610
- Only throw errors when the email is duplicate and not the same user. Close BYT-6485
- Only show "book demo" banner for users with workspace admin roles. Close BYT-6522

chore: several fix

---

frontend/src/components/GrantRequestPanel/DatabaseResourceForm/DatabaseResourceSelector.vue
frontend/src/components/GrantRequestPanel/DatabaseResourceForm/common.ts
frontend/src/components/GrantRequestPanel/GrantRequestPanel.vue
frontend/src/components/IssueV1/components/GrantRequest/DatabaseResourceTable.vue
frontend/src/components/IssueV1/components/HeaderSection/Actions/request/TinySQLEditorButton.vue
frontend/src/components/ProjectMember/AddProjectMember/AddProjectMemberForm.vue
frontend/src/components/ProjectMember/ProjectMemberRolePanel/index.vue
frontend/src/components/SensitiveData/MaskingExceptionUserTable.vue
frontend/src/components/SensitiveData/utils.ts
frontend/src/store/modules/v1/projectIamPolicy.ts
frontend/src/types/member.ts
frontend/src/utils/issue/cel.ts
frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/DatabaseNode.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/RequestQueryButton.vue

- Cel parser in the frontend should not care about the expression order.
- Use `databaseFullName` instead of `databaseName` to avoid misunderstanding.
Close BYT-6616

chore: cel parse should not care about the expression order

---

frontend/src/components/IssueV1/components/TaskRunSection/TaskRunComment.vue

chore: fix link styles in task comment

---

backend/api/gitops/webhook.go
backend/api/v1/branch_service.go
backend/api/v1/database_group_service.go
backend/api/v1/database_service.go
backend/api/v1/database_service_revision.go
backend/api/v1/issue_service_convert.go
backend/api/v1/project_service.go
backend/api/v1/rollout_service_converter.go
backend/api/v1/sheet_service.go
backend/api/v1/vcs_connector_service.go
backend/api/v1/worksheet_service.go
backend/common/resource_name.go
backend/component/webhook/manager.go
backend/plugin/webhook/webhook.go
backend/runner/taskrun/schedulerv2.go

- Use resource name formatter
- Use `projects/{project resource id}` in `webhook.project.name` instead of the project title.

chore: resource names

---

frontend/src/components/HelpDrawer/HelpDrawer.vue
frontend/src/views/sql-editor/TabList/TabItem/TabItem.vue

chore: tweak UI

---

frontend/src/components/EnvironmentForm/AccessControlConfigure.vue

This policy not work for the free plan, so we can always show "on" for "allow DDL/DML" (they're "on" by default)
Close BYT-6669

chore: always show on for allow ddl/dml in the free plan

---

frontend/src/components/InstanceForm/Form.vue
frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
frontend/src/components/Plan/components/StatementSection/EditorView/EditorView.vue
frontend/src/main.ts
frontend/src/shims-vue-globals.d.ts

following #14644
Some global functions that are not widely used are now removed from global shims.

chore(frontend): improve type definitions

---

backend/plugin/parser/mysql/backup.go
backend/plugin/parser/mysql/test-data/test_backup.yaml
backend/plugin/parser/plsql/backup.go
backend/plugin/parser/plsql/test-data/test_backup.yaml
backend/plugin/parser/tidb/backup.go
backend/plugin/parser/tidb/test-data/test_backup.yaml
backend/plugin/parser/tsql/backup.go
backend/plugin/parser/tsql/test-data/test_backup.yaml

Add the database name for the backup table to avoid timestamp conflict in database group tenant mode.
close BYT-5642

fix: add database name for backup table

---

frontend/src/composables/useExecuteSQL.ts

This also works when one (or some) of the database of batch queries doesn't have a queriable data source.
This happens when the admin data source is not allowed to query, and not allowed to fallback to the admin data source either, and there is no read-only data source.
Close BYT-6756

chore(sql-editor): fail when no queriable data source

---

frontend/eslint.config.mjs
frontend/package.json

1. "pnpm lint --fix" should already work because "--fix" can be appended to the "lint" command. We don't need the extra "lint:fix" command.
2. Enable "enableFix" by default.

chore: update eslint config

---

backend/api/v1/instance_service.go

- Updated the database listing method to use ProjectID instead of InstanceID, ensuring accurate retrieval of databases associated with the project.
- This change improves the correctness of the slow query synchronization process by aligning the database query with the intended project context.

fix(instance_service): correct project ID usage in database listing

---

frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/ActionSentence.vue

Revert part of #15032. `params.target` is not a string, so it cannot be translated inside `t()`.

fix(i18n): internal error

---

go.mod
go.sum

The current timestamptz respects the session timezone.
https://github.com/bytebase/pgx/commit/a7c1db04baf8f53687876b15acd74b55e77174f5

chore: patch pgx

---

frontend/src/utils/v1/sql.ts

---
---
---
---
BTW, some `zone` in the response is not supported so we cannot use the dayjs timezone plugin.

fix: respect the timezone

---

.github/workflows/build-push-ci-image-depot.yml
.github/workflows/build-push-release-image.yml
.github/workflows/frontend-tests.yml
frontend/package.json
frontend/pnpm-lock.yaml

Fix error in https://github.com/bytebase/bytebase/actions/runs/13141213934/job/36692397588?pr=15105
> Run pnpm install --frozen-lockfile
pnpm install --frozen-lockfile
shell: /usr/bin/bash -e {0}
env:
PNPM_HOME: /home/runner/setup-pnpm/node_modules/.bin
 ERR_PNPM_LOCKFILE_CONFIG_MISMATCH  Cannot proceed with the frozen installation. The current "pnpmfileChecksum" configuration doesn't match the value found in the lockfile
> 
> Update your lockfile using "pnpm install --no-frozen-lockfile"
Error: Process completed with exit code 1.

chore: bump pnpm version

---

backend/demo/data/default/README.md
backend/migrator/migration/3.4/0000##sheet_statement.sql
backend/migrator/migrator_test.go

demo.bytebase.com failed to start since 3.3.1 because it took too long to feed the dataset.

chore: minimal demo data

---

frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue

- Fix: visualize explain cannot handle multiple query results
- Remove `sqlResultSet` props in the  `SingleResultViewV1`

fix: visualize explain cannot handle multiple query results

---

frontend/src/components/MonacoEditor/editor.ts

References:
* https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IEditorConstructionOptions.html#autoClosingQuotes
Currently Bytebase automatically adds a " when the user types one ", which users have said is annoying.

chore: change auto-close quote to never

---

backend/api/lsp/completion.go

MSSQL already has keyword check implemented; removing brackets to be consistent with the display in PG/SQL

chore: remove brackets for mssql

---

backend/server/server.go

Previous default: https://github.com/grpc-ecosystem/grpc-gateway/blob/c705c3cd08417413979ce1519cd4062ba728d784/runtime/marshaler_registry.go#L20
With this behavior change,
- we will not accept unrecognized fields in the request.
- we will not emit unpopulated fields to the response payload, e.g. ("hello": false) if hello is not set.

chore: change grpcruntime marshal option

---

backend/runner/plancheck/ghost_sync_executor.go
backend/runner/taskrun/schema_update_ghost_executor.go

so that gh-ost can build the correct instant ddl statement.

chore: trim trailing semicolons for ghost

---

backend/component/sheet/sheet.go

> // LastLine is the line number of the last line of the SQL in the original SQL.
> // HINT: ZERO based.
> LastLine int
> 
> https://github.com/bytebase/bytebase/blob/main/backend/plugin/parser/base/base.go#L22

fix: pg error line

---

frontend/src/views/EnvironmentDashboard.vue

fix: environment tab style

---

frontend/src/router/dashboard/projectV1.ts

`/projects/xxx/plans` -> `/projects/xxx/review-center`, maybe we'd deprecate the review center later.

chore: add plans redirect route

---

frontend/src/components/Member/MemberDataTable/cells/UserOperationsCell.vue
frontend/src/utils/pagination.ts
frontend/src/utils/permission.ts

- Show the raw permission name. Since we don't have the permissions docs, the API/Terraform users need to check permissions from the UX.
- Increase the hack for default pagination to 10 (thus it's still easy to test in the local, but not much effect for regular use)
- Not support editing the member binding for support@bytebase.com, but should support edit "allUsers"

chore: minor updates

---

go.mod
go.sum

7.13.1 is the latest version without product check, downgrade to this version to allow users connect to OpenSearch instance
https://stackoverflow.com/questions/68802324/elasticsearch-in-go-err-the-client-noticed-that-the-server-is-not-elasticsear

feat: downgrade the elastic driver from 7.17.10 to 7.13.1

---

backend/api/lsp/commands.go
backend/api/lsp/completion.go
backend/api/lsp/custom.go
backend/api/lsp/fs.go
backend/api/lsp/fs_handler.go
backend/api/lsp/handler.go
backend/api/lsp/utils.go
backend/api/lsp/utils_test.go
backend/plugin/parser/base/diagnose.go
go.mod
go.sum

go-lsp is legacy, switch to use [lsp-protocol](https://github.com/bytebase/lsp-protocol)
cc @rebelice

chore: replace go-lsp with lsp-protocol

---

backend/component/ghost/config.go
frontend/src/components/IssueV1/components/Sidebar/GhostSection/FlagsForm/constants.ts

gh-ost `assume-master-host` receives the `host:port` string. I changed it to receive a bool on Bytebase to save the copy & paste.
Close BYT-7169

feat: add ghost flags assume master host

---

frontend/src/components/IssueV1/components/SQLCheckSection/AdviceStatusIcon.vue
frontend/src/components/IssueV1/components/TaskListSection/CurrentTaskSection.vue
frontend/src/components/IssueV1/components/TaskListSection/TaskFilter.vue
frontend/src/components/IssueV1/components/TaskListSection/TaskListSection.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

chore(issue): current task view

---

.github/workflows/build-push-release-image.yml

failure: https://github.com/bytebase/bytebase/actions/runs/14368395351/job/40288191192
fix: step 3 in https://github.com/depot/build-push-action?tab=readme-ov-file#authentication
Don't know why the depot builds start failing this week.

fix: depot build

---

frontend/src/components/IssueV1/components/TaskListSection/TaskListSection.vue
frontend/src/components/IssueV1/logic/poll.ts

Otherwise will trigger infinite UI refresh with API fetch

fix: infinite update for issue

---

frontend/src/components/MonacoEditor/MonacoTextModelEditor.vue
frontend/src/components/MonacoEditor/composables/useActiveRangeByCursor.ts

Before:
If the two statements don't have the blank line between them, for example:
The ranges from the WS is `[{startLineNumber: 1, endLineNumber: 3, startColumn: 1, endColumn: 1}, {startLineNumber: 3, endLineNumber: 3, startColumn: 1, endColumn: 11}]`, and the active cursor is `line: 3, column: 6`, we cannot get the valid active block.
After:

fix: get active statement range

---

frontend/src/store/modules/v1/instanceResource.ts
frontend/src/views/sql-editor/SQLEditorHomePage.vue

Will encounter endless process if we use the `ready.value` in the `useInstanceResourceByName` in the SQL editor. It's strange and seems triggered by `tabStore.isDisconnected`

fix: use instance resource

---

frontend/src/views/sql-editor/AsidePanel/ActionBar/ActionBar.vue
frontend/src/views/sql-editor/AsidePanel/ActionBar/TabItem.vue
frontend/src/views/sql-editor/AsidePanel/ActionBar/common.ts
frontend/src/views/sql-editor/AsidePanel/ActionBar/index.ts
frontend/src/views/sql-editor/AsidePanel/AsidePanel.vue
frontend/src/views/sql-editor/AsidePanel/SchemaPane/actions.tsx

---
Background: we move them into the schema context menu few versions before
However, there's no way to show these actions for schemaless databases

chore: action bar for database info

---

backend/plugin/parser/mysql/differ.go
backend/plugin/parser/mysql/test-data/differ/test_differ_trigger.yaml

Previously, when diffing MySQL schemas, the differ would always generate a CREATE TRIGGER statement for triggers present in both the old and new schemas, even if their definitions were identical. This led to unnecessary DDL statements and could cause errors if the trigger already existed.
- Updated the trigger diff logic to only generate CREATE TRIGGER statements when:
- The trigger is new (does not exist in the old schema), or
- The trigger definition has changed (requires DROP and CREATE).
- If a trigger exists in both schemas and is unchanged, no DDL is generated for it.
This change ensures that the diff output is minimal and accurate, avoiding redundant operations and potential errors. It also aligns the trigger diff behavior with best practices for schema migration.
- Updated/added …

fix: avoid unnecessary CREATE TRIGGER when trigger definition is unchanged in schema diff

---

scripts/Dockerfile.action

azure devops pipeline runs a nodejs binary on startup.
```
/usr/bin/docker create --name 41a7b9d666bf40529413de24cd686f6f_bytebasebytebaseaction362_97c922 --label 76f4a4 --network vsts_network_1762cd09e20c468cb912c62a65b01f74  -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/vsts/work/1":"/__w/1" -v "/home/vsts/work/_temp":"/__w/_temp" -v "/home/vsts/work/_tasks":"/__w/_tasks" -v "/opt/hostedtoolcache":"/__t" -v "/home/vsts/agents/4.255.0/externals":"/__a/externals":ro -v "/home/vsts/work/.taskkey":"/__w/.taskkey" bytebase/bytebase-action:3.6.2 bash -c "'/__a/externals/node20_1/bin/node' --version && echo 'container-startup-using-node-20' && '/__a/externals/node20_1/bin/node' -e 'setInterval(function(){}, 24 * 60 * 60 * 1000);' || '/__a/externals/node16/bin/node' --version && …
```

chore(action): add gcompat

---

backend/migrator/migration/3.7/0007##backfill_task_sheet_id.sql
backend/migrator/migrator_test.go

```
bbdev=# select * from task;
id  | pipeline_id | stage_id | instance | db_name |              type              |                                           payload                                           
-----+-------------+----------+----------+---------+--------------------------------+---------------------------------------------------------------------------------------------
102 |         102 |      102 | pg       | bbdev   | bb.task.database.schema.update | {"specId": "ebd956de-626d-4088-914f-13cfbeaacf51", "sheetId": 102, "taskReleaseSource": {}}
101 |         101 |      101 | pg       | bbdev   | bb.task.database.schema.baseline | {"specId": "9480d8fd-457c-4adb-a6de-96b14ef7b066", "taskReleaseSource": {}}
```

chore: dml for baseline task and plan backfill

---

backend/plugin/parser/bigquery/query_span_extractor.go
backend/plugin/parser/bigquery/test-data/query-span/standard.yaml
backend/plugin/parser/mysql/query_span_extractor.go
backend/plugin/parser/mysql/test-data/query-span/case_insensitive.yaml
backend/plugin/parser/pg/query_span_extractor.go
backend/plugin/parser/plsql/query_span_extractor.go
backend/plugin/parser/snowflake/query_span_extractor.go
backend/plugin/parser/spanner/query_span_extractor.go
backend/plugin/parser/spanner/test-data/query-span/standard.yaml
backend/plugin/parser/tidb/query_span_extractor.go
backend/plugin/parser/trino/query_span_listener.go
backend/plugin/parser/trino/test-data/query-span/masking.yaml
backend/plugin/parser/trino/test-data/query-span/trino-specific.yaml
backend/plugin/parser/tsql/query_span_extractor.go

- Updated all SQL dialect parsers to use proto object names for table view identifiers instead raw input names.
- Ensured consistent and accurate naming aligned with underlying metadata structures.
- Improved schema extraction reliability across PostgreSQL, MySQL, TSQL, PL/SQL, Trino, TiDB, Snowflake, and other parsers.![CleanShot 2025-06-09 at 14.57.32@2x.png](https://app.gitbutler.com/uploads/57feb638-7327-4f4a-8693-6ddf96fde3fc)
Close BYT-6530

fix(parser): use proto name for table and view identifiers

---

backend/server/grpc_routes.go

During the migration, the migrated services are not registered and not available on the grpc server.
When we complete the migration, the grpc traffic will be directed to connect rpc handlers. The connect rpc can talk multiple protocols, so only echo server is needed. The routes setup will be simplified.
```
{
"code": 12,
"message": "unknown service bytebase.v1.ActuatorService"
}
```

fix: cmux grpc

---

frontend/src/components/IdentityProvider/IdentityProviderEditForm.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

Detailed warning explaining the impact of deleting an identity provider, including potential user lockout if password sign-in is disabled

chore(identity-provider): add detailed delete confirmation message

---

backend/plugin/parser/pg/resource_change.go

Adds a nil check for  when processing  statements
in the PostgreSQL parser. This prevents a nil pointer dereference panic that occurs when  returns nil for a non-existent index, and  is subsequently called on the nil object.

fix(pg-parser): handle nil index metadata in DropIndexStmt

---

backend/common/engine.go
backend/migrator/migration/LATEST.sql
backend/plugin/db/pg/sync.go
backend/plugin/db/pg/sync_column_default_test.go
backend/plugin/schema/pg/generate_migration.go
backend/plugin/schema/pg/get_database_definition.go
backend/runner/migrator/column_default_migrator.go
backend/runner/schemasync/syncer.go
backend/runner/schemasync/syncer_test.go
backend/server/server.go
backend/store/db_schema.go

Implements Step 4 of the Column Default Protobuf Design for PostgreSQL, fixing ambiguity in column default metadata representation.
Changes
1. PostgreSQL Sync Update
- Modified backend/plugin/db/pg/sync.go to write to the default field instead of default_expression
- Added schema qualification using SET search_path = '' for pg_dump compatibility
2. Test Coverage
- Added 27 comprehensive test cases covering all PostgreSQL default types
- Tests include string literals, expressions, serial columns, enums, binary data, and escaped strings
3. Performance Optimization
- PostgreSQL databases now set todo=false in schema sync (no migration needed)
- Consolidated engine check logic into common.EngineNeedsColumnDefaultMigration()
Impact
- PostgreSQL now syncs column defaults with proper …

feat: implement PostgreSQL column default migration

---

frontend/src/components/SchemaEditorLite/Panels/TableColumnEditor/components/DefaultValueCell.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

Replaces the dropdown-based default value selector with a simple text input for PostgreSQL columns in the schema editor.
Changes:
- Replace 3-option dropdown (NULL/expression/value) with single input field for PostgreSQL
- Use column.defaultString to store PostgreSQL default expressions
- Add universal useSimpleInput computed property for future engine migrations
- Fix BigInt serialization error in preview pane
- Fix preview updates when column defaults are modified
- Add PostgreSQL-specific placeholder text via i18n
Benefits:
- Simplified UX for PostgreSQL users - no need to select default type first
- Prepares codebase for migrating other engines to simplified input
- Resolves schema editor hanging issues caused by BigInt serialization
PostgreSQL:
Part of BYT-7410

feat: use simple input block for PostgreSQL column default in schema editor

---

frontend/src/store/modules/v1/worksheet.ts

Close BYT-7604.
protobuf-es removes the VISIBILITY prefix, causing enum string mismatches between the frontend and backend. This is unfortunate. I am thinking if we should use enum numbers to avoid this issue.
```
If all enum values share a prefix that corresponds with the enum's name, the prefix is dropped from all enum value names. For example, given the following enum declaration:
enum PhoneType {
PHONE_TYPE_UNSPECIFIED = 0;
PHONE_TYPE_MOBILE = 1;
PHONE_TYPE_LAND_LINE = 2;
}
Protobuf-ES generates the following TypeScript enum:
/**
* @generated from enum example.PhoneType
*/
export enum PhoneType {
UNSPECIFIED = 0,
MOBILE = 1,
LAND_LINE = 2,
}
```

fix: visibility enum

---

frontend/src/components/SchemaEditorLite/Panels/TableColumnEditor/components/DefaultValueCell.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

Replace Postgres-specific default value input with a simplified input
component used for both PostgreSQL and MySQL engines. Update computed
properties, event handlers, and placeholders to support this change.
Add a generic placeholder translation for the simplified input and adjust
locales accordingly to improve consistency across supported languages.
This change prepares the codebase for future engine migrations to the
simplified input approach and streamlines default value handling logic.

feat(schema-editor): unify default value input for Postgres and MySQL

---

backend/common/engine.go
backend/plugin/db/mssql/sync.go
frontend/src/components/SchemaEditorLite/Panels/TableColumnEditor/components/DefaultValueCell.vue

Change column.DefaultExpression to column.Default in MSSQL sync code to
match expected field usage. Update engine checks to include MSSQL for
simple input handling in the frontend schema editor. Remove MSSQL from
excluded engine list to ensure consistent behavior across supported
engines. These changes improve default value support and UI consistency
for MSSQL.

fix(mssql): align default value handling with other engines

---

backend/api/v1/sql_service.go
backend/plugin/db/pg/pg.go
backend/plugin/db/pg/query.go
backend/plugin/db/pg/query_limit_test.go

Add a new test suite for getStatementWithResultLimit to verify correct
behavior of appending or adjusting LIMIT clauses in various SQL queries.
Cover cases including simple SELECTs, queries with WHERE, ORDER BY,
GROUP BY, HAVING, UNION, OFFSET, FOR UPDATE, and nested or parenthesized
SELECTs. Also test non-SELECT statements to ensure they remain unchanged.
These tests improve confidence in query limiting logic and help prevent
regressions when modifying SQL statement handling in the PostgreSQL plugin.

fix: add limit for PostgreSQL

---

frontend/src/components/GeneralSetting/PasswordRestrictionSetting.vue
frontend/src/components/User/Settings/UserPassword.vue
frontend/src/views/ProfileDashboard.vue
frontend/src/views/SettingWorkspaceUsers.vue

- Do not hard-code the URL path
- The behavior for optional fields in the proto message is a little different, we got nothing (the field not even exist) from the proto, and it's not equal to `key: undefined`

chore: minor fix

---

frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorActionPopover.vue
frontend/src/components/IssueV1/components/StatementSection/EditorView/InstanceRoleSelect.vue
frontend/src/components/IssueV1/components/StatementSection/EditorView/TransactionModeToggle.vue
frontend/src/components/IssueV1/components/StatementSection/EditorView/directiveUtils.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json
frontend/src/utils/v1/instance.ts

Implements user-configurable transaction control for database migrations via SQL script directives.
Changes:
- Added transaction mode parser for `-- txn-mode = on|off` directive
- Implemented dual-mode execution engine in Redshift driver (transactional vs auto-commit)
- Added UI toggle in SQL editor for transaction mode selection
- Created centralized directive management to handle multiple directives properly
- Added i18n support for all languages (en-US, zh-CN, es-ES, ja-JP, vi-VN)
Backend:
- `backend/plugin/parser/base/transaction_mode.go`: Parser for transaction mode directive
- `backend/plugin/db/redshift/redshift.go`: Dual-mode execution with proper transaction logging
Frontend:
- `TransactionModeToggle.vue`: UI component for transaction mode selection
- `directiveUtils.ts`: …

feat(editor): add transaction mode toggle for Redshift DDL/DML tasks

---

backend/plugin/db/bigquery/bigquery.go
backend/plugin/db/hive/hive.go
backend/plugin/db/trino/trino.go

Remove parsing and handling of transaction mode in BigQuery, Hive, and Trino
database drivers. These drivers have limited or no support for traditional
transactions, making the transaction mode parsing redundant. This cleanup
simplifies the Execute methods and aligns the code with the actual capabilities
of these databases.

refactor(db): remove unused transaction mode parsing in drivers

---

backend/plugin/schema/mysql/get_database_definition.go
backend/plugin/schema/tidb/get_database_definition.go

Remove the ON UPDATE clause generation in MySQL and TiDB schema
plugins to prevent incorrect or unsupported syntax in database
definitions. This change ensures compatibility and correctness when
retrieving column definitions.

fix(mysql, tidb): remove redundant ON UPDATE clause from column definitions

---

backend/plugin/advisor/pg/advisor_column_maximum_character_length.go
backend/plugin/advisor/pg/advisor_index_create_concurrently.go
backend/plugin/advisor/pg/test/index_create_concurrently.yaml
backend/plugin/advisor/pg/utils.go

This PR fixes an issue where the PostgreSQL advisor incorrectly flagged CREATE INDEX statements for missing the CONCURRENTLY keyword when the index was being created on a newly created table in the
same script.
Since newly created tables are empty, there's no need for the CONCURRENTLY keyword as there are no existing operations to block.
When running a script like:
```sql
CREATE TABLE feed_subscription (
id uuid NOT NULL DEFAULT uuid_generate_v4(),
userId uuid NOT NULL,
CONSTRAINT PK_feed_subscription PRIMARY KEY (id)
);
CREATE INDEX IDX_feed_subscription_userId ON feed_subscription (userId);
```
The advisor would incorrectly report:
"Creating indexes will block writes on the table, unless use CONCURRENTLY"
This warning is unnecessary because the table is newly created and empty.
Solution …

fix: skip CONCURRENTLY check for indexes on newly created tables

---

backend/plugin/parser/pg/query_span_extractor.go

Add initialization of sourceColumnsInFunction to the subqueryExtractor struct
in querySpanExtractor. This ensures that source columns used within functions
are properly tracked when extracting table sources from subqueries, preventing
potential issues with column resolution in nested queries.
Close BYT-7839

fix(parser): initialize sourceColumnsInFunction in subquery extractor

---

frontend/src/views/DatabaseDetail/DatabaseDetail.vue

If the project not matched. Happens if users assign or transfer the database via other tools like API or Terraform.

fix: redirect to correct url

---

helm-charts/bytebase/templates/statefulset.yaml
helm-charts/bytebase/values.yaml

Many users are unknow that by default, all taints are tolerated, which leads to pods being scheduled on nodes where they shouldn't be. It is recommended not to set tolerations in the default configuration. Refer to:
- https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L1093
- https://github.com/grafana/helm-charts/blob/main/charts/tempo/values.yaml#L350
- https://github.com/bitnami/charts/blob/main/bitnami/etcd/values.yaml#L496

chore(helm-charts): remove tolerance for all taint

---

backend/runner/taskrun/executor.go
backend/tests/schema_update_test.go

Add Task_DATABASE_CREATE and Task_DATABASE_DATA_UPDATE to the list of
task types that return true in the executor's task type check. This
corrects the classification logic to ensure these database-related tasks
are properly recognized and handled during execution.

fix(executor): update task type handling for database tasks

---

frontend/src/components/Plan/components/IssueReviewView/OverviewSection.vue
frontend/src/components/Plan/components/RolloutView/StageCard.vue
frontend/src/components/Plan/components/RolloutView/StageView.vue
frontend/src/components/Plan/components/RolloutView/TaskTable.vue
frontend/src/components/Plan/components/RolloutView/TaskView.vue
frontend/src/components/Plan/components/SpecDetailView/FailedTaskRunsSection.vue
frontend/src/components/v2/Model/EnvironmentV1Name.vue
frontend/src/router/dashboard/projectV1.ts

* Use placeholder "_" in routes for empty stageId (null environment)
* Handle missing stageId in navigation and routing logic

fix: handle null environments in rollout UI

---

backend/plugin/db/pg/sync.go
backend/plugin/schema/pg/get_database_metadata_testcontainer_test.go
backend/tests/syncer_test.go

This PR replaces pg_query_go parsing with direct SQL queries for index metadata extraction in PostgreSQL sync, and enhances index metadata to capture ASC/DESC ordering information.
- **Enhanced `backend/plugin/db/pg/sync.go`**: Replaced pg_query_go parsing with direct SQL queries
- **New comprehensive query**: Uses `pg_get_indexdef()`, `pg_class`, `pg_index`, and `pg_am` system catalogs for complete index metadata
- **Removed dependencies**: Eliminated pg_query_go imports from sync.go
- **Added ASC/DESC ordering support**: New `parseIndexOptions()` function parses PostgreSQL's `indoption` bitmasks
- **Enhanced SQL query**: Added `ix.indoption as index_options` to extract sort order information
- **Populated `descending` field**: Now captures sort order for each index key column using …

refactor: remove pg_query_go usage in sync

---

backend/plugin/db/mysql/sync.go

GetDatabaseDefinition will use the following code to generate the comment clause:
```golang
if column.Comment != "" {
if _, err := fmt.Fprintf(buf, " COMMENT '%s'", column.Comment); err != nil {
return err
}
}
```
This PR retains the escaping of comment field, only remove the single quote brought by QUOTE() function in SQL query.

fix: string single quote only for mysql comment in sync

---

backend/api/v1/org_policy_service.go
frontend/src/store/modules/v1/policy.ts

BREAKING
Per AIP, update mask should be
1. field names
2. oneofs are omitted
```
Field masks treat fields in oneofs just as regular fields. Consider the
following message:
message SampleMessage {
oneof test_oneof {
string name = 4;
SubMessage sub_message = 9;
}
}
The field mask can be:
mask {
paths: "name"
}
Or:
mask {
paths: "sub_message"
}
Note that oneof type names ("test_oneof" in this case) cannot be used in
paths.
```
https://protobuf.dev/reference/java/api-docs/com/google/protobuf/FieldMask.html#:~:text=%23%20Field%20Masks%20and,used%20in%0A%20paths.

fix: UpdatePolicy update mask

---

frontend/src/components/Plan/components/HeaderSection/Actions/Actions.vue
frontend/src/components/Plan/components/HeaderSection/Actions/create/CreateButton.vue
frontend/src/components/Plan/components/HeaderSection/HeaderSection.vue
frontend/src/components/Plan/components/SpecDetailView/SpecListSection.vue
frontend/src/components/Plan/components/common/validateSpec.ts

- Fix reactivity issue in useSpecsValidation hook by accepting reactive refs
- Auto-enable statement editing when new specs are created

fix: improve plan spec validation reactivity and auto-enable editing

---

frontend/src/components/Plan/components/HeaderSection/DescriptionSection.vue
frontend/src/components/Plan/components/HeaderSection/HeaderSection.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

- Add collapsed/expanded state management to DescriptionSection
- Show compact one-line view by default with clickable description text

feat: implement collapsed view for plan description section

---

frontend/src/components/ProvideSQLEditorContext.vue
frontend/src/store/modules/sqlEditor/tab.ts
frontend/src/views/sql-editor/Sheet/context.ts

- Fix: during the initialization, the tab is changed but the UI (MonacoEditor content) is not reactive to the content
- Fix: initial database for worksheet
Close BYT-7953

fix: sql editor initial

---

frontend/src/utils/v1/sql.ts

fix mongodb collection name contains special characters
like: "#/\\"
```bash
[mongos] admin> use xxx;
switched to db xxx
[mongos] xxx> show collections;
_test_audit
#RES_DATA
xxxx
restaurant
test_audit
test_audit(AI)
test_audit(Password***)
testData
[mongos] xxx> db."#RES_DATA".find()
Uncaught:
SyntaxError: Unexpected token (1:3)
> 1 | db."#RES_DATA".find()
|    ^
2 |
[mongos] xxx> db.getCollection("#RES_DATA").find()
[
{
_id: ObjectId('68a3f78a3d554cd5087c5020'),
idx: 0,
time: ISODate('2025-08-19T04:03:22.422Z')
}
]
[mongos] xxx> db['#RES_DATA'].find()
[
{
_id: ObjectId('68a3f78a3d554cd5087c5020'),
idx: 0,
time: ISODate('2025-08-19T04:03:22.422Z')
}
]
```

fix(mongodb): fix mongodb collection name contains special characters

---

backend/plugin/parser/tokenizer/tokenizer.go
backend/plugin/parser/tokenizer/tokenizer_test.go

- Fixed tokenizer crash when processing PostgreSQL partition table CREATE statements
- Added early return for CREATE TABLE statements without column/constraint definitions
- Prevents attempting to scan for opening parenthesis when none exists
The tokenizer was failing when processing PostgreSQL partition table syntax like:
- `CREATE TABLE partition_name PARTITION OF parent_table DEFAULT`
- `CREATE TABLE partition_name PARTITION OF parent_table FOR VALUES FROM (...) TO (...)`
These statements don't have the traditional column definition syntax `CREATE TABLE name (columns...)`, causing the tokenizer to fail when trying to find the opening parenthesis.
Added a check at the beginning of `SetLineForPGCreateTableStmt` to return early when there are no columns or constraints to process. This …

fix: handle PostgreSQL partition table syntax in tokenizer

---

frontend/src/components/User/Settings/UserDataTable/cells/UserNameCell.vue
frontend/src/components/v2/Button/CopyButton.vue
frontend/src/components/v2/Form/ResourceIdField.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/TableCell.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/VirtualDataBlock.vue

- Support copy for the whole block
- Allow selection for the single field
Close BYT-8053

chore: optimize result selection/copy

---

frontend/src/components/Plan/components/SpecDetailView/SpecDetailView.vue
frontend/src/components/Plan/components/StatementSection/EditorView/EditorView.vue
frontend/src/components/Plan/components/StatementSection/StatementSection.vue

Close BYT-8041
- Make SpecDetailView responsive with proper flex layout and height constraints
- Expand editor to use available vertical space while maintaining minimum height
- Add viewport-based height limits to prevent oversized components

chore: improve editor height and responsive layout

---

frontend/src/components/Plan/components/RolloutView/TaskView.vue
frontend/src/components/Project/ProjectSwitch/ProjectSwitchPopover.vue
frontend/src/views/DashboardHeader.vue

- Hide SQL Editor and My Issues button text on mobile screens to reduce header crowding
- Make TaskView layout responsive with flex-wrap for better content overflow handling
- Improve ProjectSwitchPopover max width on mobile devices
- Use conditional rendering based on window width for better mobile UX

chore: improve mobile UI responsiveness

---

frontend/src/components/Plan/components/Configuration/TransactionModeSection/TransactionModeSwitch.vue
frontend/src/components/Plan/components/StatementSection/EditorView/EditorView.vue
frontend/src/components/Plan/logic/utils.ts

- Fix TransactionModeSwitch not reading initial state from statement directives
- Add proper distinction between created and uncreated plans
- Extract reusable updateSpecSheetWithStatement utility function

fix: transaction mode switch initialization and api calls

---

backend/api/v1/sql_service.go
frontend/src/components/Plan/components/HeaderSection/Actions/export/ExportArchiveDownloadAction.vue
frontend/src/components/Plan/components/HeaderSection/Actions/unified/UnifiedActionGroup.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

- Fix SQL service to handle both rollout and stage name formats in doExportFromIssue
- Improve task run filtering to get latest task runs for export tasks using proper UID extraction
- Enhance export archive download action with better expired file handling
- Update export download logic to show file expired status instead of downloaded status

chore: improve export archive task run handling

---

frontend/src/components/IssueV1/components/TaskRunSection/TaskRunDetail.vue
frontend/src/components/Plan/components/IssueReviewView/DatabaseExportView.vue
frontend/src/components/Plan/components/IssueReviewView/DatabaseExportView/ExecutionHistorySection.vue
frontend/src/components/Plan/components/IssueReviewView/DatabaseExportView/TasksSection.vue
frontend/src/components/Plan/components/IssueReviewView/DatabaseExportView/index.ts
frontend/src/components/Plan/components/RolloutView/TaskRunTable.vue
frontend/src/components/Plan/components/RolloutView/TaskView.vue

Close BYT-8129
- Remove clickable task selection that was confusing with rollout actions
- Add dedicated ExecutionHistorySection with database column for clarity

refactor: remove confusing task selection in database export view
