bytebase/bytebase

- backend/api/v1/acl.go
- backend/api/v1/auth_service.go
- backend/api/v1/database_service.go
- backend/api/v1/environment_service.go
- backend/api/v1/externalvs_service.go
- backend/api/v1/idp_service.go
- backend/api/v1/instance_role_service.go
- backend/api/v1/instance_service.go
- backend/api/v1/org_policy_service.go
- backend/api/v1/project_service.go
- backend/api/v1/review_service.go
- backend/api/v1/risk_service.go
- frontend/src/store/modules/idp.ts
- frontend/src/store/modules/review.ts
- frontend/src/store/modules/risk.ts
- frontend/src/store/modules/user.ts
- frontend/src/store/modules/v1/environment.ts
- frontend/src/views/ProfileDashboard.vue
- frontend/src/views/TwoFactorSetup.vue
https://google.aip.dev/161
>   // The list of fields to update.
// Fields are specified relative to the book
// (e.g. `title`, `rating`; *not* `book.title` or `book.rating`).
google.protobuf.FieldMask update_mask = 2;
> fix: field mask should use relative path

- backend/runner/metricreport/reporter.go
Remove the goroutine as we have cache for the setting store.
> fix: remove goroutine

- frontend/src/components/CustomApproval/Settings/components/CustomApproval/RulesPanel/RiskTips.vue
- frontend/src/components/CustomApproval/Settings/components/CustomApproval/RulesPanel/RulesSection.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/views/SettingWorkspaceCustomApproval.vue
> feat(frontend): show a tips to configure risk rule if needed

- frontend/src/utils/sso.ts
- frontend/src/views/OAuthCallback.vue
- frontend/src/views/auth/Signin.vue
> chore: add redirect to SSO login

- frontend/src/components/ProjectDatabasesPanel.vue
> feat(frontend): support filtering databases in project detail page's "Databases" panel

- frontend/src/components/IdentityProviderCreateForm.vue
- frontend/src/components/MemberTable.vue
- frontend/src/store/modules/setting.ts
- frontend/src/views/SettingWorkspaceSSODetail.vue
- frontend/src/views/auth/MultiFactor.vue
> fix: fetch the latest server info

- frontend/src/components/ProjectOverviewPanel.vue
- frontend/src/views/Home.vue
Show "Waiting for my approval" section in the issue list only when Custom Approval feature is available.
> chore(frontend): feature guard for "waiting for my approval" issue list section

- frontend/src/components/ProjectOverviewPanel.vue
Make it looks like the home page
> chore(frontend): update style for project overview page

- frontend/src/types/plan.ts
> fix: plan type

- backend/legacyapi/plan.go
- frontend/src/locales/subscription/en-US.json
- frontend/src/locales/subscription/zh-CN.json
- frontend/src/types/plan.yaml
1. GitOps CI will be free.
2. Latest schema / sync scheet writeback will be team feature.
> chore: update gitops plan

- backend/legacyapi/plan.go
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/types/plan.ts
- frontend/src/types/plan.yaml
- frontend/src/views/sql-editor/EditorCommon/EditorAction.vue
> chore: remove shared SQL script feature from free plan

- backend/legacyapi/plan.go
- frontend/src/components/PricingTable/PricingTable.vue
- frontend/src/locales/subscription/en-US.json
- frontend/src/locales/subscription/zh-CN.json
- frontend/src/types/plan.yaml
* Change team plan to pro plan
* Make SQL Review available in free plan
* Make sync schema all version available in pro plan
* Re-position Free plan and pro plan since they both can serve teams
* Add slow query and custom approval
> feat: update pricing and plan

- frontend/src/components/InstanceForm.vue
- frontend/src/utils/instance.ts
Also, remove it out of dev guard. I forgot commit `instance.ts` in #5530 : \
> chore: using 5439 as default port for redshift

- frontend/src/components/ProjectTable.vue
- frontend/src/views/Archive.vue
- frontend/src/views/ProjectDashboard.vue
- frontend/src/views/SettingWorkspaceProject.vue
> chore: minor touchup on setting project dashboard

- frontend/src/store/modules/review.ts
> chore(frontend): hide service accounts in candidate list

- backend/api/v1/instance_service.go
- backend/plugin/advisor/utils_for_tests.go
- backend/plugin/db/clickhouse/sync.go
- backend/plugin/db/driver.go
- backend/plugin/db/mongodb/sync.go
- backend/plugin/db/mssql/sync.go
- backend/plugin/db/mysql/sync.go
- backend/plugin/db/oracle/sync.go
- backend/plugin/db/pg/sync.go
- backend/plugin/db/redis/sync.go
- backend/plugin/db/redshift/sync.go
- backend/plugin/db/snowflake/sync.go
- backend/plugin/db/spanner/sync.go
- backend/plugin/db/sqlite/sync.go
- backend/runner/slowquerysync/syncer.go
- backend/server/server.go
> feat: support check slow query log enabled

- frontend/src/views/Home.vue
- frontend/src/views/auth/Signup.vue
> chore: disable auto trial

- backend/runner/taskrun/scheduler.go
- backend/server/stage.go
- backend/server/task.go
- backend/tests/backup_restore_test.go
- backend/tests/database.go
- backend/tests/ghost_test.go
- backend/tests/project_test.go
- backend/tests/rollback_test.go
- backend/tests/schema_update_test.go
- backend/tests/sensitive_data_test.go
- backend/tests/sql_editor_test.go
- backend/tests/sql_review_test.go
- backend/tests/sync_schema_test.go
- backend/tests/syncer_test.go
- backend/tests/tenant_test.go
- backend/tests/tests.go
> chore: only assignee can change task status

- frontend/src/components/ProjectDatabasesPanel.vue
- frontend/src/components/v2/Form/SearchBox.vue
- frontend/src/components/v2/Select/DatabaseSelect.vue
- frontend/src/components/v2/Select/InstanceSelect.vue
- frontend/src/components/v2/Select/PrincipalSelect.vue
- frontend/src/components/v2/Select/ProjectSelect.vue
- frontend/src/components/v2/Select/index.ts
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/views/DatabaseDashboard.vue
- frontend/src/views/Home.vue
- frontend/src/views/IssueDashboard.vue
- frontend/src/views/ProjectDashboard.vue
- Support filtering by instance in
- **Databases** dashboard page
- **Project -> Databases** panel
- Others
- New implementations for Project/Instance/Database/Member selectors.
> feat(frontend): filter improvements

- frontend/src/components/SlowQuery/Panel/LogFilter.vue
> chore(frontend): update slow log filter layout

- frontend/src/components/TransferDatabaseForm.vue
- frontend/src/components/TransferDatabaseForm/TransferSourceSelector.vue
Now this dropdown selector will hide irrelevant instances (zero databases in the instance).
> feat(frontend): hide irrelevant instances in selector for transferring database

- frontend/src/types/proto/store/setting.ts
- proto/gen/grpc-doc/store/README.md
- proto/generated-go/store/setting.pb.go
- proto/store/setting.proto
> feat(proto): the store proto definition of mail delivery setting

- backend/api/v1/common.go
- backend/api/v1/role_service.go
- backend/server/server.go
- backend/store/role.go
Hardcoded `roles/OWNER` and `roles/DEVELOPER` correspond to the project owner and project member before. 
They are not stored in the database. And users cannot edit these two roles. 
@LiuJi-Jim FYI
> feat: impl role crud

- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/views/SettingWorkspaceMember.vue
Add a checkbox to toggle show inactive members in **Settings > Members**. Only available if the count of inactive members > 0.
Close BYT-3007
> feat(frontend): add a checkbox to toggle show inactive members

- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/views/SettingWorkspaceProject.vue
Close BYT-2954
- Hide archived projects by default. Add a checkbox to control this.
- Always put "Unassigned" project to the top of the list.
> feat(frontend): hide archived projects in "Settings->Projects" by default

- frontend/src/components/Quickstart.vue
- frontend/src/layouts/BodyLayout.vue
> feat(frontend): new layout for Quickstart

- frontend/src/components/Role/Setting/RoleSetting.vue
- frontend/src/components/Role/Setting/components/RolePanel.vue
- frontend/src/components/Role/Setting/components/RoleTable.vue
- frontend/src/components/Role/Setting/components/RoleTableRow.vue
- frontend/src/components/Role/Setting/components/index.ts
- frontend/src/components/Role/Setting/index.ts
- frontend/src/components/Role/index.ts
- frontend/src/components/v2/Form/SpinnerButton.vue
- frontend/src/components/v2/Form/index.ts
- frontend/src/grpcweb/index.ts
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/router/index.ts
- frontend/src/store/modules/index.ts
- frontend/src/store/modules/role.ts
- frontend/src/utils/role.ts
- frontend/src/views/SettingSidebar.vue
- frontend/src/views/SettingWorkspaceRole.vue
> feat(frontend): workspace-level custom role settings

- backend/migrator/migration/prod/1.16/0002##delete_email_duplicated_principal.sql
* set related principal/member's creator_id and updater_id to SystemBotID;
* handle duplicated project member data;
> fix: delete duplicated email script

- backend/plugin/db/mysql/role.go
Also try to read `information_schema.user_attributes` if fail on query `mysql.users`.
> fix(mysql): fail open for sync mysql user

- frontend/src/components/Issue/table/WaitingForMyApprovalIssueTable.vue
- frontend/src/components/ProjectOverviewPanel.vue
- frontend/src/views/Home.vue
* chore: don't load too much issues
* chore: use paged issue table for waiting approval section
* chore: simplify
> chore(frontend): don't load too much issues (cherry-pick #5639)

- backend/migrator/migration/prod/1.16/0002##delete_email_duplicated_principal.sql
fix the missing project_member's fk.
> fix: update all principal's fk

- backend/api/v1/review_service.go
- backend/runner/approval/runner.go
- backend/store/principal.go
- backend/utils/utils.go
we use the system bot as the approver.
> chore: skip approval steps if no real users can approve the step

- backend/api/v1/instance_service.go
- backend/legacyapi/policy.go
- backend/runner/slowquerysync/syncer.go
> chore: add database list in SlowQueryPolicy

- backend/utils/utils.go
> fix: no need to skip if there is no template

- frontend/src/components/CustomApproval/Settings/components/CustomApproval/common/RoleSelect.vue
- frontend/src/components/CustomApproval/Settings/components/CustomApproval/common/StepsTable.vue
- frontend/src/components/CustomApproval/Settings/components/CustomApproval/logic/validate.ts
- frontend/src/components/Issue/review/ApprovalTimeline.vue
- frontend/src/components/Issue/review/Candidates.vue
- frontend/src/components/Issue/review/IssueReviewSidebarSection.vue
- frontend/src/layouts/ProjectLayout.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/store/modules/review.ts
- frontend/src/store/modules/v1/projectIamPolicy.ts
- frontend/src/utils/workspaceApprovalSetting.ts
- frontend/src/views/ProjectDetail.vue
Close BYT-3024
- Setting custom roles as approval flow steps.
Auto approve if no member has such a role in the project
> feat(frontend): using custom roles in approval node

- backend/plugin/db/mysql/sync.go
> fix: fix merge MySQL slow query log

- backend/api/v1/acl_config.go
> fix(rbac): only workspace owner and dba can access SettingService/Setting

- backend/api/v1/review_service.go
- backend/runner/approval/runner.go
- backend/server/server.go
- backend/utils/utils.go
> feat: create activities when skipping approval steps

- frontend/src/components/Issue/activity/ActionCreator.vue
- frontend/src/components/Issue/activity/ActionSentence.vue
- frontend/src/components/Issue/activity/ActivityAction.vue
> chore(frontend): show system bot name while auto skip approval node

- backend/runner/taskrun/database_create_executor.go
> fix(mongodb): mongodb create database

- backend/api/v1/role_service.go
- backend/store/project_member.go
> chore: forbid deleting roles in use

- frontend/src/components/DatabaseOverviewPanel.vue
- frontend/src/components/FunctionDefinitionView.vue
- frontend/src/components/FunctionTable.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/store/modules/dbSchema.ts
https://user-images.githubusercontent.com/24653555/233249942-6276a445-7ab1-4cea-b272-9f6d0b9ca8c8.mp4
> chore: add function table

- backend/plugin/advisor/utils_for_tests.go
- backend/plugin/db/clickhouse/clickhouse.go
- backend/plugin/db/driver.go
- backend/plugin/db/mongodb/mongodb.go
- backend/plugin/db/mssql/mssql.go
- backend/plugin/db/mysql/mysql.go
- backend/plugin/db/oracle/oracle.go
- backend/plugin/db/pg/pg.go
- backend/plugin/db/redis/redis.go
- backend/plugin/db/redshift/redshift.go
- backend/plugin/db/snowflake/snowflake.go
- backend/plugin/db/spanner/spanner.go
- backend/plugin/db/sqlite/sqlite.go
- backend/server/sql.go
Reverts bytebase/bytebase#5672
We need to maintain the session of a connection.
> fix: Revert "chore: cleanup driver QueryConn() interface"

- frontend/src/components/Project/ProjectSetting/ProjectMemberTable/PrincipalTable.vue
- frontend/src/components/Role/Setting/components/RolePanel.vue
- frontend/src/components/Role/Setting/components/RoleTable.vue
- frontend/src/components/Role/Setting/components/RoleTableRow.vue
- frontend/src/components/v2/Form/ResourceIdField.vue
- frontend/src/components/v2/Form/index.ts
- frontend/src/components/v2/Select/ProjectRolesSelect.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/store/modules/role.ts
- frontend/src/store/modules/utils.ts
- frontend/src/types/utils.ts
- frontend/src/utils/role.ts
- frontend/src/utils/workspaceApprovalSetting.ts
Split role name for resource id and title for human readable role name.
> feat(frontend): custom role title

- frontend/src/layouts/BodyLayout.vue
> chore(frontend): update layout for quickstart

- backend/api/v1/instance_service.go
- backend/legacyapi/policy.go
- backend/plugin/db/pg/dump.go
- backend/plugin/db/pg/pg.go
- backend/plugin/db/pg/sync.go
- backend/runner/slowquerysync/syncer.go
FYI @LiuJi-Jim 
Remove the database list in SlowQueryPolicy. We think the PostgreSQL instance enables the slow query if all databases created pg_stat_statements extensions, except system databases.
> chore: update pg check slow query enabled

- frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable.vue
> fix(sql-editor): optimize empty cells

- backend/api/v1/database_service.go
> chore: support ACL for ListSlowQueries

- frontend/src/components/Project/ProjectSetting/ProjectMemberTable/PrincipalTable.vue
- frontend/src/components/Project/ProjectSetting/ProjectMemberTable/ProjectMemberTable.vue
- frontend/src/components/Project/ProjectSetting/common.ts
- frontend/src/components/ProjectMemberPanel.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
> feat(frontend): split display for inactive project members

- docs/design/source-code-tour.snb.md
Fix https://github.com/bytebase/bytebase/issues/5676
> chore: fix source code tour link

- proto/buf.gen.yaml
https://buf.build/community/stephenh-ts-proto
> chore: use remote plugin for generating ts proto

- frontend/src/components/TransferDatabaseForm.vue
- frontend/src/components/TransferDatabaseForm/TransferMultipleDatabaseForm.vue
- frontend/src/store/modules/database.ts
> fix(frontend): high-privileged workspace roles can see all databases while transferring

- backend/runner/taskrun/scheduler.go
- backend/store/issue.go
- backend/store/task.go
- backend/store/task_run.go
task runs should also be patched to CANCELED
> fix: clear running tasks should handle task runs as well

- backend/api/v1/database_service.go
> fix: fix panic in ListSlowQueries

- frontend/src/components/CustomApproval/Settings/components/CustomApproval/RuleDialog/RuleForm.vue
> chore(frontend): auto focus

- frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue
> chore(sql-editor): hide irrelevant nodes while searching

- frontend/src/components/RepositoryForm.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/store/modules/subscription.ts
> feat(frontend): SDL is available on free plan with out latest schema writeback

- backend/api/v1/mail_templates/testmail/hahaha/need_configure.html
- backend/api/v1/mail_templates/testmail/hahaha/weekly_for_dba.html
- backend/api/v1/mail_templates/testmail/hahaha/weekly_for_dba_example.html
- backend/api/v1/mail_templates/testmail/hahaha/weekly_for_project_owner.html
- backend/api/v1/mail_templates/testmail/hahaha/weekly_for_project_owner_example.html
Including 3 templates:
- `need_configure.html`: It should be sent if users had not configure slow query.
- `weekly_for_dba.html`: It should be sent to workspace dba.
- `weekly_for_project_owner.html`: It should be sent to project owner.
The field likes `{{XXXXX}}` is a place holder, should be replaced with the real data.
**NOTE: It's backend's responsibility to hide the same database name within the records in a database. Because we cannot including javascript in email.**
> feat(mail): slow query log weekly report template

- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
> feat(frontend): update rollback sql tips

- frontend/src/components/Issue/PipelineStageList.vue
- frontend/src/components/Issue/TaskStatusIcon.vue
- frontend/src/utils/task.ts
> feat(frontend): display task check error / warning for each task

- frontend/src/components/Issue/IssueDetailLayout.vue
- frontend/src/components/Issue/IssueTaskStatementPanel.vue
- frontend/src/components/Issue/logic/GhostModeProvider.ts
- frontend/src/components/Issue/logic/IssueLogic.ts
- frontend/src/components/Issue/logic/TenantModeProvider.ts
- frontend/src/components/Issue/logic/common.ts
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
> feat(frontend): allow apply statement change to all pending tasks when possible

- frontend/src/components/Issue/IssueBanner.vue
- frontend/src/components/ProjectOverviewPanel.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/views/Home.vue
- Don't override issue status with task status. Display it as-is. Close BYT-3050
- Update section titles on the home page and project overview page. Close BYT-3009
> chore(frontend): minor updates for issue-related wordings

- backend/migrator/migration/dev/LATEST.sql
- backend/migrator/migration/prod/1.17/0002##db_secrets.sql
- backend/migrator/migration/prod/LATEST.sql
- backend/migrator/migrator_test.go
> feat(schema): add secrets column in db table

- .github/workflows/proto-linter.yml
ref: https://sourcegraph.com/github.com/prometheus/prometheus/-/blob/.github/workflows/buf.yml
> chore: specify check path

- backend/plugin/db/mssql/sync.go
> chore: pretty mssql version

- frontend/src/components/Quickstart.vue
- frontend/src/layouts/BodyLayout.vue
- frontend/src/views/sql-editor/SQLEditorPage.vue
> feat(frontend): show quickstart for sql editor

- frontend/src/views/TwoFactorSetup.vue
> fix(frontend): redirect url when setup complete at first login

- frontend/src/components/Quickstart.vue
> feat(frontend): Follow up action after user finishes Quickstart

- frontend/src/components/CustomApproval/Settings/components/CustomApproval/FlowsPanel/FlowTable.vue
- frontend/src/components/CustomApproval/Settings/components/CustomApproval/RuleDialog/RuleDialog.vue
- frontend/src/components/CustomApproval/Settings/components/CustomApproval/RulesPanel/RulesSection.vue
- frontend/src/store/modules/workspaceApprovalSetting.ts
> chore(frontend): error handling and status resuming for custom approval setting

- backend/server/sql.go
- frontend/src/utils/instance.ts
Enable ssl config for OceanBase instance.
> feat: ssl support for OceanBase

- frontend/src/components/MemberTable.vue
> chore: filter service account owner

- frontend/src/components/Issue/TaskRunTable.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/main.ts
- frontend/src/shims-vue-globals.d.ts
- frontend/src/utils/util.ts
> feat(frontend): display task execution time

- backend/plugin/advisor/catalog/walk_through.go
- backend/plugin/advisor/mysql/advisor_syntax.go
- backend/plugin/advisor/mysql/parser.go
- backend/plugin/db/mysql/mysql.go
- backend/plugin/parser/split_multi_sql_test.go
- backend/plugin/parser/utils.go
> fix: support CREATE/DROP PROCEDURE with mysql client style

- frontend/src/components/InstanceForm.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
> chore: add optional info text to readonly inputs

- backend/plugin/db/pg/pg.go
- backend/plugin/db/pg/sync.go
> fix: support to sync slow query logs from PostgreSQL 11+

- frontend/src/components/ProjectMemberPanel.vue
- frontend/src/components/Role/Setting/RoleSetting.vue
- frontend/src/components/Role/Setting/components/RolePanel.vue
- frontend/src/components/Role/Setting/components/RoleTableRow.vue
- frontend/src/components/Role/Setting/context.ts
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
- frontend/src/router/index.ts
- frontend/src/types/plan.ts
- frontend/src/views/SettingSidebar.vue
- Rename "Roles" to "Custom Roles" (Close BYT-3060)
- Custom roles should be an ENTERPRISE feature (Close BYT-3059)
- Reset selected roles to empty after adding a project member (Close BYT-3069)
> fix(frontend): custom roles fixes

- frontend/src/components/QuickActionPanel.vue
- frontend/src/views/sql-editor/EditorPanel/SQLEditor.vue
* Quickstart use shortcut to invoke query should also check query data item. Fix BYT-3062
* consolidate quick action to make Spanish look better. Fix BYT-3063
Before
After
> fix: quickstart and quickaction button style

- frontend/src/utils/util.ts
- frontend/src/views/sql-editor/EditorCommon/EditorAction.vue
* chore: show keyboard shortcut text according to different platforms
* chore: format and layout
* chore: format code
> cherrypick: chore(sql-editor): keyboard shortcuts for windows/linux (#5774)

- frontend/src/views/SyncDatabaseSchema/SelectTargetDatabasesView.vue
- frontend/src/views/SyncDatabaseSchema/TargetDatabasesSelectPanel.vue
- frontend/src/views/SyncDatabaseSchema/index.vue
> chore: don't show code diffs for those same schema

- backend/api/v1/database_service.go
- backend/legacyapi/plan.go
- backend/server/server.go
> feat: only allow pro or enterprise plan to update and delete secret

- frontend/src/components/QuickActionPanel.vue
> chore(frontend): quick action layout improvements

- backend/resources/postgres/postgres.go
> feat: turn pg_stat_statements for sample database

- backend/plugin/advisor/config/sql-review.dev.yaml
- backend/plugin/advisor/config/sql-review.prod.yaml
- frontend/src/types/sql-review-schema.yaml
> fix: PK key type allow list supports PostgreSQL

- backend/legacyapi/sheet.go
- backend/legacyapi/task.go
- backend/runner/taskrun/scheduler.go
- backend/server/project.go
- backend/server/webhook.go
- backend/store/task.go
TODO:
- update sheets' payload to backtrace the created issues.
- support updating tasks by modifying files.
> feat: use sheet for gitops issues

- frontend/src/components/Issue/IssueActivityPanel.vue
- frontend/src/components/Issue/IssueDetailLayout.vue
- frontend/src/components/Issue/RunTaskCheckButton.vue
- frontend/src/components/Issue/TaskCheckBar.vue
- frontend/src/components/v2/Button/ContextMenuButton.vue
- frontend/src/components/v2/Button/index.ts
- frontend/src/components/v2/Button/types.ts
- frontend/src/components/v2/index.ts
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
> feat(frontend): support run task checks in batch mode

- docs/design/source-code-tour.snb.md
per https://github.com/bytebase/bytebase.com/pull/896
> chore: update the doc link to the new rollout policy page

- frontend/src/components/QuickActionPanel.vue
- frontend/src/layouts/BodyLayout.vue
> chore: update quick action panel style

- frontend/src/views/SettingWorkspaceMailDelivery.vue
> chore: update layout of mail delivery

- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/views/SettingWorkspaceMailDelivery.vue
> chore: update mail delivery i18n

- backend/plugin/advisor/mysql/advisor_insert_row_limit.go
- backend/plugin/advisor/mysql/advisor_statement_affected_row_limit.go
- backend/runner/taskcheck/statement_affected_rows_report_executor.go
- backend/runner/taskcheck/statement_affected_rows_report_executor_test.go
the first not-NULL value of column 9 (rows) is considered as the affected rows count.
> fix: extract affected rows from mysql query plan

- frontend/src/components/SlowQuery/Panel/AdviseIndex.vue
- frontend/src/components/SlowQuery/Panel/DetailPanel.vue
- frontend/src/components/v2/Model/DatabaseName.vue
- frontend/src/components/v2/Model/EnvironmentName.vue
- frontend/src/components/v2/Model/InstanceName.vue
- frontend/src/components/v2/Model/ProjectName.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
> chore: add advise index view

- frontend/src/views/SyncDatabaseSchema/SelectTargetDatabasesView.vue
> chore: auto select the first diff database

- frontend/src/components/Issue/logic/base.ts
fix the following bug
1. upload sql
2. apply to other tasks
3. no tasks are showing statements
> fix: upload task statement display

- backend/plugin/parser/mybatis/ast/data_node.go
- backend/plugin/parser/mybatis/ast/node.go
- backend/plugin/parser/mybatis/ast/query_node.go
- backend/plugin/parser/mybatis/parser.go
- backend/plugin/parser/mybatis/parser_test.go
- backend/plugin/parser/mybatis/test-data/test_simple_mapper.yaml
After this PR, the AST of mybatis XML looks like this:
And we restore `${xx}` and `#{xx}` to `?`;
> feat(mybatis): support placeholder in mybatis xml

- backend/migrator/migration/dev/LATEST.sql
- backend/migrator/migration/prod/1.18/0002##update_instance_unique_index.sql
- backend/migrator/migration/prod/LATEST.sql
- backend/migrator/migrator_test.go
This reverts commit 816a7700a46ffc79ed4957d1fbe2e95de55b9932.
> chore: Revert "chore: update instance index (#5845)"

- backend/api/v1/instance_service.go
- frontend/src/components/InstanceForm.vue
cc https://github.com/bytebase/bytebase/pull/5791#issuecomment-1528123755
> chore: update check instance id duplicated

- backend/migrator/migration/dev/LATEST.sql
- backend/migrator/migration/prod/1.18/0002##update_project_member_index.sql
- backend/migrator/migration/prod/LATEST.sql
- backend/migrator/migrator_test.go
We are introducing IAM condition similar to https://cloud.google.com/iam/docs/conditions-overview. This will have a (project, principal, role) having multiple entries with different conditions.
> chore: update project member index

- backend/legacyapi/plan.go
- frontend/src/components/GeneralSetting/SecuritySetting.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/subscription/en-US.json
- frontend/src/locales/subscription/es-ES.json
- frontend/src/locales/subscription/zh-CN.json
- frontend/src/locales/zh-CN.json
- frontend/src/types/plan.ts
- frontend/src/types/plan.yaml
> chore: move disallow-signup feature to enterprise plan

- frontend/src/plugins/issue/logic/initialize/assignee.ts
Corresponding Backend PR https://github.com/bytebase/bytebase/pull/5884
> chore: select project owners who are not workspace owner or DBA first (Frontend)

- frontend/src/components/SlowQuery/Panel/AdviseIndex.vue
> feat: fetch index advice

- backend/plugin/db/clickhouse/role.go
Add backquotes for username in "SHOW GRANT FOR %username%" query to prevent sql errors
> chore: update role.go

- frontend/src/components/SlowQuery/Panel/DetailPanel.vue
- frontend/src/components/SlowQuery/Panel/LogTable.vue
- frontend/src/components/SlowQuery/Panel/SlowQueryPanel.vue
> feat: allow click slow query log item for PostgreSQL to display index advice

- backend/api/v1/database_service.go
- frontend/src/components/SlowQuery/Panel/AdviseIndex.vue
- frontend/src/components/SlowQuery/Panel/DetailPanel.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
close BYT-3097
@boojack Adding FeatureBadge is a bit difficult for me, I can't get it to be on the same line as the CREATE-INDEX button. Help me, please.
> chore: remove dev guard and add feature guard for index advisor

- backend/plugin/parser/sql/differ/mysql/column_test.go
> chore(differ): add test for column format

- backend/plugin/db/oracle/sync.go
1) Oracle11 doesn't have collation so we're removing it for now.
2) Use predefined system schemas instead of using ORACLE_MAINTAINED.
3) Use a better version string.
> chore: oracle11 compatible

- frontend/src/components/SQLReview/components/useSQLRuleFilter.ts
> feat(frontend): support searching SQL review rule title and description

- frontend/src/components/Issue/IssueDetailLayout.vue
- frontend/src/components/Issue/logic/common.ts
- frontend/src/components/Issue/rollback/RollbackStatus.vue
> fix: use sheetId in rollback issue creation

- frontend/src/components/InstanceForm.vue
- frontend/src/components/InstanceForm/SshConnectionForm.vue
- frontend/src/components/InstanceForm/index.ts
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
> feat(frontend): instance ssh form improvement

- frontend/src/bbkit/BBNotification.vue
- frontend/src/components/SlowQuery/Panel/DetailPanel.vue
- frontend/src/components/SlowQuery/Panel/IndexAdvisor.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
> chore: add feature guard for index advisor

- backend/plugin/parser/mybatis/mapper/ast/data_node.go
- backend/plugin/parser/mybatis/mapper/ast/node.go
- backend/plugin/parser/mybatis/mapper/ast/query_node.go
- backend/plugin/parser/mybatis/mapper/parser.go
- backend/plugin/parser/mybatis/mapper/parser_test.go
- backend/plugin/parser/mybatis/mapper/test-data/test_dynamic_sql_mapper.yaml
- backend/server/webhook.go
> chore: support line mapping to point the precise line number in mybatis mapper xml

- frontend/src/components/Issue/logic/common.ts
Convert sheetId to number first when creating new issue.
> fix: convert sheetId to number

- backend/server/webhook.go
- backend/server/webhook_test.go
- backend/tests/schema_update_test.go
> chore: update gitlab ci summary message

- backend/legacyapi/plan.go
- frontend/src/components/InstanceForm.vue
- frontend/src/components/InstanceForm/SshConnectionForm.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/types/plan.ts
> chore(frontend): feature guard to instance SSH connection

- frontend/src/components/AnomalyTable.vue
> fix(frontend): migration change history shows "<<Unknown database>>" error

- frontend/src/components/DatabaseDetail/Settings/components/Secrets.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
> chore: add secret description

- backend/server/webhook.go
Previously, we match the Bytebase environment id, after this PR, we will match the Bytebase environment name case insensitive.
> chore: mybatis sql review match name case insensitive

- backend/migrator/migration/prod/2.0/0001##migrate_task_payload_statement_to_sheet.sql
There could be tasks without issues for corrupted data.
> chore: fix sheet backfill DML

- backend/runner/taskrun/scheduler.go
- backend/server/stage.go
- backend/server/task.go
- backend/tests/backup_restore_test.go
- backend/tests/database.go
- backend/tests/ghost_test.go
- backend/tests/project_test.go
- backend/tests/rollback_test.go
- backend/tests/schema_update_test.go
- backend/tests/sensitive_data_test.go
- backend/tests/sql_editor_test.go
- backend/tests/sql_review_test.go
- backend/tests/sync_schema_test.go
- backend/tests/syncer_test.go
- backend/tests/tenant_test.go
- backend/tests/tests.go
- frontend/src/components/Issue/logic/transition.ts
Now, any project owner is allowed to rollout tasks even if they are not the current assignee of the issue.
Close BYT-3115
> chore(frontend): allow project owners to rollout tasks

- frontend/src/components/Issue/logic/common.ts
> fix: route params format transform for task statements

- frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
> fix(frontend): should not show schemaless database list for change data scenario

- .golangci.yaml
- backend/plugin/advisor/advisor.go
- backend/plugin/advisor/db/db.go
- backend/plugin/advisor/oracle/advisor_table_require_pk.go
- backend/plugin/advisor/oracle/oracle_rules_test.go
- backend/plugin/advisor/oracle/parser.go
- backend/plugin/advisor/oracle/test/table_require_pk.yaml
- backend/plugin/advisor/sql_review.go
- backend/plugin/advisor/utils_for_tests.go
- backend/plugin/parser/sql/plsql.go
- backend/plugin/parser/sql/plsql_test.go
> feat: implement Oracle require PK rule

- frontend/src/components/Issue/IssueTaskStatementPanel.vue
> fix(frontend): editor height on issue detail page

- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
- frontend/src/views/SyncDatabaseSchema/DiffViewPanel.vue
- frontend/src/views/SyncDatabaseSchema/SelectTargetDatabasesView.vue
> feat(frontend): put diff and generated DDL in separate tabs

- frontend/src/components/DeploymentConfigTool/LabelSelect.vue
- frontend/src/components/DeploymentConfigTool/SelectorItem.vue
> chore(frontend): use single selector for environment condition when configuring deployment pipeline

- backend/plugin/advisor/advisor.go
- backend/plugin/advisor/generator/main.go
- backend/plugin/advisor/generator/oracle.template
- backend/plugin/advisor/oracle/advisor_table_no_foreign_key.go
- backend/plugin/advisor/oracle/oracle_rules_test.go
- backend/plugin/advisor/oracle/test/table_no_foreign_key.yaml
- backend/plugin/advisor/sql_review.go
> feat: implement Oracle table no FK rule and add oracle advisor template

- backend/migrator/migration/dev/20230509000000##drop_issue_pipeline_id_not_null.sql
- backend/migrator/migration/dev/LATEST.sql
We will add a new issue type, which has no pipeline, for requesting grant.
> chore: drop issue pipeline_id not null

- frontend/src/components/QuickActionPanel.vue
- frontend/src/components/TransferOutDatabaseForm/Label.vue
- frontend/src/components/TransferOutDatabaseForm/TransferOutDatabaseForm.vue
- frontend/src/components/TransferOutDatabaseForm/common.ts
- frontend/src/components/TransferOutDatabaseForm/index.ts
- frontend/src/components/v2/Model/InstanceName.vue
- frontend/src/components/v2/Select/ProjectSelect.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
- frontend/src/router/index.ts
- frontend/src/types/common.ts
Close BYT-3091
https://user-images.githubusercontent.com/2749742/237022638-9f81bcdc-ea12-4042-a06d-a59bc85b3620.mp4
> feat(frontend): batch transfer out databases from project

- frontend/src/plugins/ai/components/ChatView/CodeView.vue
> fix(frontend): auto resize for sql chat mode

- frontend/src/components/SchemaDiagram/ER/TableNode.vue
> chore(frontend): add a dot to updated columns in schema diagram

- frontend/src/components/DeploymentConfigTool/DeploymentMatrix.vue
- frontend/src/components/Project/ProjectSetting/ProjectGeneralSettingPanel.vue
- frontend/src/components/ProjectActivityPanel.vue
- frontend/src/components/ProjectDatabasesPanel.vue
- frontend/src/components/ProjectDeploymentConfigPanel.vue
- frontend/src/components/ProjectMigrationHistoryPanel.vue
- frontend/src/components/ProjectOverviewPanel.vue
- frontend/src/store/modules/v1/project.ts
- frontend/src/utils/v1/project.ts
- frontend/src/views/ProjectDetail.vue
- Project overview panel
- Project databases panel
- Project activities panel
- Project change history panel
> refactor(frontend): ship to project V1 API (part.4)

- backend/plugin/advisor/advisor.go
- backend/plugin/advisor/oracle/advisor_column_require.go
- backend/plugin/advisor/oracle/oracle_rules_test.go
- backend/plugin/advisor/oracle/parser.go
- backend/plugin/advisor/oracle/test/column_required.yaml
- backend/plugin/advisor/sql_review.go
> feat: implement Oracle required column rule

- frontend/src/views/sql-editor/AsidePanel/AsidePanel.vue
- frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue
> fix(sql-editor): filter bugs

- frontend/src/components/DeploymentConfigTool/DeploymentMatrix.vue
An even stronger fix to close BYT-2141
> chore(frontend): adjust horizontal scrollable range for deployment matrix

- frontend/src/components/Issue/GrantRequestIssueSidebar.vue
- frontend/src/components/Issue/IssueBanner.vue
- frontend/src/components/Issue/IssueSidebar.vue
- frontend/src/components/Issue/IssueStatusTransitionButtonGroup.vue
- frontend/src/components/Issue/form/GrantRequestExporterForm.vue
- frontend/src/components/Issue/form/GrantRequestQuerierForm.vue
- frontend/src/components/Issue/logic/GrantRequestModeProvider.ts
- frontend/src/components/Issue/logic/transition.ts
- frontend/src/components/QuickActionPanel.vue
- frontend/src/plugins/issue/logic/review/index.ts
- frontend/src/store/modules/database.ts
- frontend/src/types/issue.ts
* create and view grant request issue for exporter role.
TODO:
* export data with one click;
> feat: implement grant request exporter issue

- backend/plugin/advisor/advisor.go
- backend/plugin/advisor/oracle/advisor_column_maximum_character_length.go
- backend/plugin/advisor/oracle/oracle_rules_test.go
- backend/plugin/advisor/oracle/test/column_maximum_character_length.yaml
- backend/plugin/advisor/sql_review.go
> feat: implement Oracle maximum char length rule

- backend/plugin/db/util/ssh.go
> fix: fail open for connect to local ssh agent

- backend/server/sql.go
We require querier for query() and exporter for export(). When exportFormat is empty string or "QUERY", it's query().
> chore: evaluate project IAM policy in query

- frontend/src/store/modules/v1/project.ts
- frontend/src/utils/pipeline.ts
- frontend/src/views/Home.vue
- frontend/src/views/IssueDashboard.vue
> fix(frontend): user id in [GET] /api/issue

- backend/api/v1/project_service.go
> fix: compose project webhook in v1 api

- backend/plugin/advisor/advisor.go
- backend/plugin/advisor/oracle/advisor_where_require.go
- backend/plugin/advisor/oracle/oracle_rules_test.go
- backend/plugin/advisor/oracle/test/statement_where_require.yaml
- backend/plugin/advisor/sql_review.go
> feat: implement Oracle require WHERE rule

- backend/plugin/advisor/advisor.go
- backend/plugin/advisor/oracle/advisor_insert_must_specify_column.go
- backend/plugin/advisor/oracle/oracle_rules_test.go
- backend/plugin/advisor/oracle/test/statement_insert_must_specify_column.yaml
- backend/plugin/advisor/sql_review.go
> feat: implement Oracle INSERT must specify column rule

- frontend/src/bbkit/BBSpin.vue
- frontend/src/components/Issue/IssueBanner.vue
- frontend/src/components/Issue/IssueHighlightPanel.vue
- frontend/src/components/Issue/IssueStatusTransitionButtonGroup.vue
- frontend/src/components/Issue/action/ExportDataButton.vue
- frontend/src/components/Issue/form/GrantRequestExporterForm.vue
- frontend/src/router/index.ts
> feat: implement export button in grant exporter issue

- frontend/src/main.ts
- frontend/src/store/modules/project.ts
> chore: initial project and database list in global

- frontend/src/components/Issue/action/ExportDataButton.vue
- frontend/src/components/Issue/form/GrantRequestExporterForm.vue
- frontend/src/components/Issue/form/GrantRequestQuerierForm.vue
- frontend/src/components/Issue/logic/GrantRequestModeProvider.ts
- frontend/src/layouts/ProjectLayout.vue
- frontend/src/store/modules/v1/projectIamPolicy.ts
- frontend/src/views/DatabaseDetail.vue
* project detail page
* database detail page
> chore: hide db changes buttons

- backend/plugin/vcs/bitbucket/bitbucket.go
Fixes https://github.com/bytebase/bytebase/issues/5991
Temporarily change the `apiPageSize` to `1` and print the value of the `next` variable.
> fix(bbc): correctly handle `next` field in pagination

- frontend/src/components/Issue/IssueDescriptionPanel.vue
- frontend/src/components/Issue/form/GrantRequestExporterForm.vue
- frontend/src/components/Issue/form/GrantRequestQuerierForm.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
Use `reason` for grant request issue type.
> chore: update issue description title

- backend/plugin/advisor/advisor.go
- backend/plugin/advisor/oracle/advisor_index_key_number_limit.go
- backend/plugin/advisor/oracle/oracle_rules_test.go
- backend/plugin/advisor/oracle/test/index_key_number_limit.yaml
- backend/plugin/advisor/sql_review.go
> feat: implement Oracle index key number limit rule

- frontend/src/components/DatabaseSelect.vue
- frontend/src/components/Issue/form/GrantRequestExporterForm.vue
In grant request issue, we allow user to select all databases.
> chore: add all mode to database select

- backend/plugin/advisor/advisor.go
- backend/plugin/advisor/oracle/advisor_column_no_null.go
- backend/plugin/advisor/oracle/oracle_rules_test.go
- backend/plugin/advisor/oracle/test/column_no_null.yaml
- backend/plugin/advisor/sql_review.go
> feat: implement Oracle column no null rule

- frontend/src/components/Issue/form/GrantRequestExporterForm.vue
- frontend/src/components/Issue/form/GrantRequestQuerierForm.vue
- frontend/src/components/Issue/logic/GrantRequestModeProvider.ts
- frontend/src/components/ProjectListSidePanel.vue
- frontend/src/components/ProjectSelect.vue
- frontend/src/components/ProvideDashboardContext.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
- frontend/src/store/modules/project.ts
- frontend/src/store/modules/v1/project.ts
- frontend/src/views/Archive.vue
- frontend/src/views/DatabaseDashboard.vue
- frontend/src/views/ProjectDashboard.vue
* only show user's project in the project table;
* show all projects in the selector of grant request issue.
> chore: update project data prepare

- backend/plugin/advisor/advisor.go
- backend/plugin/advisor/code.go
- backend/plugin/advisor/oracle/advisor_column_maximum_varchar_length.go
- backend/plugin/advisor/oracle/oracle_rules_test.go
- backend/plugin/advisor/oracle/test/column_maximum_varchar_length.yaml
- backend/plugin/advisor/sql_review.go
- backend/plugin/advisor/utils_for_tests.go
> feat: implement Oracle max varchar length rule

- frontend/src/components/AlterSchemaPrepForm/ProjectStandardView.vue
> fix(frontend): always show search box

- backend/plugin/advisor/advisor.go
- backend/plugin/advisor/code.go
- backend/plugin/advisor/oracle/advisor_naming_table_no_keyword.go
- backend/plugin/advisor/oracle/oracle_rules_test.go
- backend/plugin/advisor/oracle/test/naming_table_no_keyword.yaml
- backend/plugin/advisor/sql_review.go
- backend/plugin/advisor/utils_for_tests.go
- backend/plugin/parser/sql/plsql.go
> feat: implement Oracle table name no keyword rule

- frontend/src/components/AnomalyTable.vue
- frontend/src/components/CustomApproval/Settings/components/common/ExprEditor/components/common.ts
- frontend/src/components/DatabaseListSidePanel.vue
- frontend/src/components/EnvironmentForm.vue
- frontend/src/components/InstanceTable.vue
- frontend/src/components/ProvideDashboardContext.vue
- frontend/src/components/SQLReview/SQLReviewCreation.vue
- frontend/src/components/SQLReview/SQLReviewPolicyTable.vue
- frontend/src/components/TransferDatabaseForm/TransferMultipleDatabaseForm.vue
- frontend/src/components/v2/Model/EnvironmentV1Name.vue
- frontend/src/components/v2/Model/ProductionEnvironmentV1Icon.vue
- frontend/src/components/v2/Model/index.ts
- frontend/src/store/modules/v1/environment.ts
- frontend/src/store/modules/v1/index.ts
- frontend/src/utils/v1/environment.ts
- frontend/src/utils/v1/index.ts
- Anomaly table
- Environment ID selector in Risk config
- Database list in the sidebar
- Environment detail form
- Instance table component
- Transfer IN databases
> refactor(frontend): ship several usages to environment v1

- frontend/src/components/Issue/IssueHighlightPanel.vue
- frontend/src/components/Issue/action/ExportDataButton.vue
- frontend/src/layouts/ProjectLayout.vue
- frontend/src/store/modules/v1/projectIamPolicy.ts
- frontend/src/utils/policy.ts
- frontend/src/utils/role.ts
- frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultView.vue
* update project layout items for each user role;
* fix database list in sql editor;
> chore: update project layout items for each user role

- backend/api/v1/project_service.go
- backend/api/v1/project_service_test.go
> fix: validing iam bindings

- frontend/src/store/modules/v1/project.ts
- frontend/src/store/modules/v1/projectIamPolicy.ts
Say goodbye to tongs of "GetIamPolicy" request and "Too many requests" DOS (Hopefully)
> refactor(frontend): batch compose project iam policy

- frontend/src/components/BannersWrapper.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
- frontend/src/views/BannerUpgradeSubscription.vue
> feat: add subscription upgrade banner

- backend/plugin/advisor/advisor.go
- backend/plugin/advisor/code.go
- backend/plugin/advisor/oracle/advisor_naming_identifier_case.go
- backend/plugin/advisor/oracle/oracle_rules_test.go
- backend/plugin/advisor/oracle/test/naming_identifier_case.yaml
- backend/plugin/advisor/sql_review.go
- backend/plugin/advisor/utils_for_tests.go
> feat: implement Oracle identifier case rule

- backend/api/v1/review_service.go
- backend/runner/taskcheck/scheduler.go
> feat: on retrying generating approval flow, rerun task check report

- frontend/src/views/BannerUpgradeSubscription.vue
https://github.com/bytebase/bytebase/assets/24653555/89ab2e35-f280-425f-8dad-0e27d01462f4
> chore: add scroll animation to banner

- frontend/src/components/DatabaseSelect.vue
- frontend/src/components/DatabasesSelectPanel.vue
- frontend/src/components/EnvironmentSelect.vue
- frontend/src/components/Issue/IssueDescriptionPanel.vue
- frontend/src/components/Issue/form/GrantRequestExporterForm.vue
- frontend/src/components/Issue/form/GrantRequestQuerierForm.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
* add i18n of expire days;
* update text styles;
> chore: update grant request issue styles

- backend/plugin/advisor/config/sql-review.dev.yaml
- backend/plugin/advisor/config/sql-review.prod.yaml
- backend/plugin/advisor/oracle/advisor_naming_identifier_case.go
- backend/plugin/advisor/sql_review.go
- backend/plugin/advisor/utils_for_tests.go
- frontend/src/locales/sql-review/en-US.json
- frontend/src/locales/sql-review/es-ES.json
- frontend/src/locales/sql-review/zh-CN.json
- frontend/src/types/sql-review-schema.yaml
- frontend/src/types/sqlReview.ts
close https://github.com/bytebase/bytebase/pull/6104#discussion_r1194917902
> chore: use boolean as identifier case payload

- backend/plugin/parser/sql/validate_sql_for_editor.go
- backend/plugin/parser/sql/validate_sql_for_editor_test.go
> fix: fix validateSQL to support "SELECT* FROM ..."

- frontend/src/components/ProjectCreate.vue
> fix(frontend): disallow tenant project creation in free plan

- frontend/src/components/Issue/form/GrantRequestQuerierForm.vue
- frontend/src/components/Project/ProjectSetting/ProjectMemberTable/PrincipalTable.vue
- frontend/src/components/Project/ProjectSetting/ProjectMemberTable/ProjectMemberRolePanel.vue
- frontend/src/components/Project/ProjectSetting/ProjectMemberTable/RoleDescription.vue
- frontend/src/components/ProjectMemberPanel.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
- frontend/src/utils/issue/expr.ts
- frontend/src/views/BannerUpgradeSubscription.vue
> feat: implement edit project member roles panel

- frontend/src/components/DatabaseListSidePanel.vue
- frontend/src/components/Issue/form/GrantRequestQuerierForm.vue
- frontend/src/components/ProjectListSidePanel.vue
- frontend/src/components/ProjectSelect.vue
- frontend/src/store/modules/database.ts
- frontend/src/store/modules/project.ts
- frontend/src/store/modules/v1/project.ts
- frontend/src/store/modules/v1/projectIamPolicy.ts
- frontend/src/utils/project.ts
- frontend/src/views/DatabaseDashboard.vue
- frontend/src/views/ProjectDashboard.vue
* workspace owner and DBA can see all databases in /db page;
* workspace owner and DBA can only see their projects in /project page;
* workspace owner and DBA can get all databases and projects in selectors;
> fix: the visibility of projects and dbs for workspace owner and DBA

- frontend/src/components/CustomApproval/Settings/components/CustomApproval/logic/utils.ts
- frontend/src/components/DatabaseListSidePanel.vue
- frontend/src/components/Issue/AssigneeAttentionButton.vue
- frontend/src/components/Issue/IssueActivityPanel.vue
- frontend/src/components/Issue/IssueHighlightPanel.vue
- frontend/src/components/Issue/logic/common.ts
- frontend/src/components/Issue/logic/transition.ts
- frontend/src/components/Issue/table/IssueTable.vue
- frontend/src/components/KBar/KBarWrapper.vue
- frontend/src/components/OnboardingGuide.vue
- frontend/src/components/ProfileDropdown.vue
- frontend/src/components/ProvideSQLEditorContext.vue
- frontend/src/components/misc/Watermark.vue
- frontend/src/layouts/BodyLayout.vue
- frontend/src/plugins/pitr/index.ts
- frontend/src/store/modules/activity.ts
- frontend/src/store/modules/auth.ts
- frontend/src/store/modules/sheet.ts
- frontend/src/store/modules/slowQueryPolicy.ts
- frontend/src/store/modules/v1/policy.ts
- frontend/src/utils/role.ts
- frontend/src/views/DashboardHeader.vue
- frontend/src/views/Home.vue
[Caution] Some stuff still using legacy `useCurrentUser`
- Bookmark
- Inbox
- Issue subscriber
- Issue context
> refactor(frontend): ship to useCurrentUserV1

- backend/plugin/db/oracle/dump.go
> feat: implement Oracle Dump interface

- frontend/src/store/modules/v1/projectIamPolicy.ts
- frontend/src/utils/issue/expr.ts
- frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultView.vue
* hide the button in enterprise plan;
* disallow for those non-exporter users in free/pro plan;
* fix export data as json format;
> fix: export data button in sql editor

- frontend/src/store/modules/v1/setting.ts
- frontend/src/views/BannerUpgradeSubscription.vue
fix https://github.com/bytebase/bytebase/pull/6140#issuecomment-1553267672
> fix: upgrade subscription banner feature items

- frontend/src/components/ProjectCreate.vue
- frontend/src/components/ProjectSettingPanel.vue
> fix(frontend): respect errors when archiving/restoring projects

- backend/plugin/parser/sql/mysql.go
- backend/plugin/parser/sql/tidb.go
- backend/server/sql.go
> chore: parse SQL before execute

- frontend/src/components/TransferDatabaseForm.vue
- frontend/src/components/TransferOutDatabaseForm/TransferOutDatabaseForm.vue
- frontend/src/store/modules/database.ts
- frontend/src/views/DatabaseDetail.vue
> fix(frontend): remove database from old project map when transferred

- backend/server/acl.go
- backend/server/member.go
- backend/server/sheet.go
- backend/server/stage.go
- backend/server/task.go
401 is authentication error, and 403 is authorization error. We should use http.StatusForbiden for 403's.
> chore: use 403 for permission denied

- frontend/src/bbkit/BBStepTab.vue
- frontend/src/views/SyncDatabaseSchema/DiffViewPanel.vue
- frontend/src/views/SyncDatabaseSchema/SelectTargetDatabasesView.vue
- frontend/src/views/SyncDatabaseSchema/index.vue
- Using a "hamburger" layout that the middle part of the pane is auto-weighted.
- The code diff view and the code editor view is partially scrollable.
Close BYT-3167
> chore(frontend): sync-schema panel layout improvement

- frontend/index.html
Tested on Xiaomi's stock browser. Might need to be tested on more devices.
Close BYT-3158
> chore(frontend): prefer light color scheme

- frontend/src/components/QuickActionPanel.vue
- frontend/src/store/modules/v1/projectIamPolicy.ts
- frontend/src/utils/v1/project.ts
- frontend/src/views/DashboardSidebar.vue
> chore: hide change database entries for those users without privileges

- backend/store/sheet.go
> chore: add back sheet payload since it's still useful

- frontend/src/components/Issue/logic/transition.ts
> chore(frontend): allow dba/owner to close any issues

- frontend/src/components/Issue/logic/transition.ts
> chore(frontend): also allow project owners to apply issue status transition

- frontend/src/components/v2/Select/UserSelect.vue
> fix(frontend): hide system-bot in UserSelect correctly

- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
- frontend/src/views/BannerUpgradeSubscription.vue
https://github.com/bytebase/bytebase/pull/6187
> cherrypick: manual cherrypick https://github.com/bytebase/bytebase/pull/6187

- frontend/src/views/sql-editor/TerminalPanel/CompactSQLEditor.vue
- frontend/src/views/sql-editor/TerminalPanel/utils.ts
> fix(sql-editor): update condition variables eagerly

- frontend/src/views/EnvironmentDetail.vue
> fix(frontend): environment tier feature check

- frontend/src/components/Issue/layout/GrantRequestDetail.vue
- frontend/src/store/modules/database.ts
- frontend/src/store/modules/v1/projectIamPolicy.ts
- frontend/src/types/store.ts
* change the key of Map to string; Close BYT-3233
* fetch the latest project IAM policy when issue's review is done; Close BYT-3228
> fix: id type in database store map

- frontend/src/store/modules/v1/projectIamPolicy.ts
- frontend/src/utils/policy.ts
- frontend/src/views/DashboardSidebar.vue
* For those databases in UNPROTECTED env, we should check IAM policy; Close BYT-3246
* Fix error project resource name; Close BYT-3250
> fix: `isDatabaseAccessible` in SQL editor

- frontend/src/components/TransferOutDatabaseForm/TransferOutDatabaseForm.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
> chore(frontend): transfer out improvements

- frontend/src/utils/slug.ts
@RainbowDashy PTAL
Close BYT-3255
> chore(frontend): extract migrationHistoryId from slug

- backend/api/v1/common.go
- backend/api/v1/rollout_service.go
- backend/server/server.go
- backend/store/plan.go
Implement basic listing and creating plans.
> feat: impl plan service list & create

- frontend/src/layouts/ProjectLayout.vue
> fix: project tabs selected state

- frontend/src/components/CustomApproval/Settings/components/common/ExprEditor/ConditionGroup.vue
- frontend/src/components/CustomApproval/Settings/components/common/ExprEditor/components/FactorSelect.vue
- frontend/src/components/CustomApproval/Settings/components/common/ExprEditor/factor.ts
- frontend/src/components/Issue/IssueTaskSDLPanel.vue
- frontend/src/grpcweb/index.ts
- frontend/src/plugins/cel/logic/build.ts
- frontend/src/plugins/cel/logic/resolve.ts
- frontend/src/plugins/cel/types/factor.ts
- frontend/src/plugins/cel/types/operator.ts
- frontend/src/plugins/cel/types/simple.ts
Make the resolveCELExpr works for grant request issue's expr.
> feat: update cel plugin for grant request issue's expr

- backend/legacyapi/anomaly.go
- backend/store/anomaly.go
> fix: fill in anomaly severity when convert store anomaly message to api anomaly

- frontend/src/components/DatabaseBackup/DatabaseBackupSettingForm.vue
> fix(frontend): i18n resource key

- frontend/src/components/SlowQuery/Panel/SlowQueryPanel.vue
- Ensure the policy-related instance is correctly fetched
- Show error message if error occurs
Safe to backport to 2.1.0
> fix(frontend): handle slow query sync more gracefully

- frontend/src/components/Issue/form/GrantRequestExporterForm.vue
- frontend/src/components/Issue/form/GrantRequestQuerierForm.vue
- frontend/src/components/Project/ProjectSetting/ProjectMemberTable/ProjectMemberRolePanel.vue
- frontend/src/store/modules/sqlEditor.ts
- frontend/src/utils/issue/cel.ts
- frontend/src/utils/issue/expr.ts
> chore: update role display in project member role panel

- frontend/src/utils/policy.ts
> chore: update database accessible checks

- frontend/src/views/SyncDatabaseSchema/SelectTargetDatabasesView.vue
> fix: copy statement in sync database schema

- frontend/src/components/ProjectMemberPanel.vue
- frontend/src/components/v2/Select/UserSelect.vue
> feat: support adding members to a project

- frontend/src/components/Project/ProjectSetting/ProjectMemberTable/ProjectMemberRolePanel.vue
- frontend/src/components/Project/ProjectSetting/ProjectMemberTable/UserTable.vue
> chore: add view button into member table

- backend/api/v1/common.go
- backend/api/v1/rollout_service.go
- backend/legacyapi/issue.go
- backend/legacyapi/task.go
- backend/runner/taskrun/database_backup_executor.go
- backend/runner/taskrun/pitr_restore_executor.go
- backend/server/issue.go
- backend/server/server.go
- backend/store/backup.go
- Add a new issue type `IssueDatabaseGeneral IssueType = "bb.issue.database.general"` to cover these issue types we used before:
- `IssueDatabaseCreate IssueType = "bb.issue.database.create"`
- `IssueDatabaseSchemaUpdate IssueType = "bb.issue.database.schema.update"`
- `IssueDatabaseSchemaUpdateGhost IssueType = "bb.issue.database.schema.update.ghost"`
- `IssueDatabaseDataUpdate IssueType = "bb.issue.database.data.update"`
- `IssueDatabaseRestorePITR IssueType = "bb.issue.database.restore.pitr"`
- Seems that we also need to add new issue types to policy `PolicyType_DEPLOYMENT_APPROVAL`. Will do it later.
split #6258 part 2
> feat: create rollout & review via createPlan

- frontend/src/types/proto/store/plan.ts
- frontend/src/types/proto/v1/rollout_service.ts
- proto/gen/grpc-doc/store/README.md
- proto/gen/grpc-doc/v1/README.md
- proto/generated-go/store/plan.pb.go
- proto/generated-go/v1/rollout_service.pb.go
- proto/store/plan.proto
- proto/v1/rollout_service.proto
add deployment config to change database config as an available target.
remove logicalTable target, let's add them when we start working on it.
> chore(proto): add deployment config as an available target

- frontend/src/views/DatabaseDetail.vue
- frontend/src/views/sql-editor/SQLEditorPage.vue
> fix: string type database id

- frontend/src/components/AlterSchemaPrepForm/ProjectStandardView.vue
- frontend/src/components/InstanceForm/InstanceForm.vue
> chore(frontend): minor fixes for database/instance api migration 

- frontend/src/components/InstanceForm/InstanceForm.vue
> chore(frontend): early feature check for creating/editing RO datasource

- frontend/src/components/Issue/logic/transition.ts
> chore(frontend): review state check for RESOLVE operation

- frontend/src/components/BannersWrapper.vue
- frontend/src/components/GeneralSetting/SecuritySetting.vue
- frontend/src/components/IdentityProviderCreateForm.vue
- frontend/src/components/InstanceForm/InstanceForm.vue
- frontend/src/components/ProfileDropdown.vue
- frontend/src/components/Quickstart.vue
- frontend/src/components/ReleaseRemindModal.vue
- frontend/src/grpcweb/index.ts
- frontend/src/layouts/BodyLayout.vue
- frontend/src/layouts/DashboardLayout.vue
- frontend/src/layouts/SQLEditorLayout.vue
- frontend/src/layouts/SheetDashboardLayout.vue
- frontend/src/main.ts
- frontend/src/plugins/issue/logic/initialize/helper.ts
- frontend/src/router/index.ts
- frontend/src/store/modules/help.ts
- frontend/src/store/modules/index.ts
- frontend/src/store/modules/v1/actuator.ts
- frontend/src/store/modules/v1/index.ts
- frontend/src/store/modules/v1/setting.ts
- frontend/src/types/actuator.ts
- frontend/src/types/store.ts
- frontend/src/views/BannerDemo.vue
- frontend/src/views/ProfileDashboard.vue
- frontend/src/views/SettingWorkspaceGeneral.vue
- frontend/src/views/auth/Signin.vue
- frontend/src/views/auth/Signup.vue
We already have the actuator v1 API, just use the gRPC in the frontend and remove useless legacy code
> chore: use grpc for actuator

- frontend/src/components/SlowQuery/Panel/DetailPanel.vue
- frontend/src/components/SlowQuery/Panel/IndexAdvisor.vue
- frontend/src/components/SlowQuery/Panel/LogTable.vue
- frontend/src/store/modules/slowQuery.ts
- frontend/src/store/modules/v1/database.ts
- frontend/src/types/slowQuery.ts
- frontend/src/utils/slowQuery.ts
- frontend/src/utils/tab.ts
- frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue
- Slow query displaying
- SQL editor tab store
> refactor(frontend): database v1 use cases (part)

- frontend/src/assets/css/tailwind.css
- frontend/src/components/DatabaseGroup/DatabaseGroupForm.vue
- frontend/src/components/DatabaseGroup/MatchedDatabaseView.vue
- frontend/src/components/DatabaseGroup/MatchedTableView.vue
- frontend/src/components/v2/Form/ResourceIdInput.vue
- frontend/src/components/v2/Model/DatabaseView.vue
- frontend/src/components/v2/Model/index.ts
- frontend/src/store/modules/dbGroup.ts
- frontend/src/views/DatabaseGroupDetail.vue
- frontend/src/views/SchemaGroupDetail.vue
> feat: implement view matched/unmatched databases/tables

- frontend/src/components/InstanceForm/InstanceForm.vue
- frontend/src/plugins/pitr/index.ts
- frontend/src/store/modules/instance.ts
- frontend/src/store/modules/sql.ts
> fix(frontend): remove unused calls

- frontend/src/components/DatabaseDetail/SQLEditorButtonV1.vue
- frontend/src/components/v2/Model/DatabaseTableRow.vue
- frontend/src/components/v2/Model/DatabaseV1Table.vue
- frontend/src/store/modules/dbGroup.ts
- frontend/src/types/dbGroup.ts
- frontend/src/types/index.ts
- frontend/src/views/DatabaseDashboard.vue
> feat: show database group list in db page

- backend/api/v1/sql_service.go
> feat: limit the size of query results

- frontend/package.json
- frontend/pnpm-lock.yaml
> chore(frontend): upgrade @popperjs/core to 2.11.8

- frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
- frontend/src/components/DatabaseGroup/DatabaseGroupForm.vue
- frontend/src/components/DatabaseGroup/DatabaseGroupPanel.vue
- frontend/src/components/DatabaseGroup/DatabaseGroupTable.vue
- frontend/src/components/DatabaseGroup/MatchedDatabaseView.vue
- frontend/src/components/DatabaseGroup/MatchedTableView.vue
- frontend/src/components/DatabaseGroup/ProjectDatabaseGroupPanel.vue
- frontend/src/components/DatabaseGroup/SelectSchemaGroupsTable.vue
- frontend/src/store/modules/dbGroup.ts
- frontend/src/utils/databaseGroup/issue.ts
- frontend/src/views/DatabaseGroupDetail.vue
- frontend/src/views/SchemaGroupDetail.vue
https://github.com/bytebase/bytebase/assets/24653555/38ea0bfa-40e5-44f7-a18a-e24c34bfda5c
> feat: implement database/schema group selector in alter schema form

- frontend/src/components/Issue/form/GrantRequestQuerierForm.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
> chore: add tooltip to all database in querier request issue

- backend/plugin/db/clickhouse/clickhouse.go
- backend/plugin/db/util/driverutil.go
> fix: fix query panic

- frontend/src/components/Issue/IssueTaskStatementPanel.vue
- Add min height
- Trigger auto-height feature more eagerly.
> chore(frontend): better auto height for sql editor

- frontend/src/components/QuickActionPanel.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
- frontend/src/router/index.ts
- frontend/src/types/common.ts
- frontend/src/types/index.ts
- frontend/src/types/quickAction.ts
> feat(frontend): update quick action list according to roles and subscription plan

- backend/api/v1/sql_service.go
- backend/plugin/db/mysql/mysql.go
- backend/plugin/parser/sql/plsql.go
1. trim right `;` for MySQL
2. allow cross-database query for MySQL
3. support validation multi-SQL for the editor
close BYT-3201
> fix: fix three bugs in Query API

- backend/migrator/migration/prod/2.2/0004##update_vcs_type_in_payload.sql
- backend/migrator/migrator_test.go
#4876 forgot the vcs type in payloads.
> fix: migrate vcs type in payload

- frontend/src/store/modules/v1/instance.ts
Prevent get an unknown environment.
> fix: compose environment of instance

- backend/server/issue.go
https://github.com/bytebase/bytebase/assets/87714218/478da787-4875-40ee-9133-9a7c3dda9c97
> feat: support create issue using table group

- backend/common/retry.go
> chore: typo

- frontend/src/components/OnboardingGuide.vue
- frontend/src/components/ProvideDashboardContext.vue
- frontend/src/layouts/ProjectLayout.vue
- frontend/src/router/index.ts
- frontend/src/store/modules/project.ts
- frontend/src/store/modules/v1/projectIamPolicy.ts
- frontend/src/views/ProjectDetail.vue
- legacy project restful APIs are no longer used
- legacy project types and store modules are now only used for composing
> refactor(frontend): clean up legacy project use cases

- backend/api/v1/risk_service.go
- backend/common/convert.go
- backend/runner/approval/runner.go
- backend/server/server.go
- backend/store/risk.go
> chore: change risk expression to unparsed struct

- backend/api/v1/sql_service.go
- backend/plugin/parser/sql/plsql.go
- backend/plugin/parser/sql/plsql_test.go
- backend/plugin/parser/sql/utils.go
- backend/store/db_schema.go
I'll implement table-level query permission check for PostgreSQL in the following PR.
> feat: implement table-level query permission check for MySQL and Oracle

- frontend/src/components/Issue/IssueTaskStatementPanel.vue
- frontend/src/main.ts
- frontend/src/store/modules/v1/sheet.ts
> fix(frontend): clean up temp edit statement state when they are no more valid

- frontend/src/components/Issue/IssueTaskStatementPanel.vue
Close BYT-3292
| Before | After |
|--------|--------|
| <img width="1858" alt="image" src="https://github.com/bytebase/bytebase/assets/24653555/f084ea7d-4d4e-48db-ad8d-54e0aa53874c"> | <img width="1855" alt="image" src="https://github.com/bytebase/bytebase/assets/24653555/d7869f66-58c1-4b9b-b973-f8067c97fb76"> |
> chore: update edit button style

- backend/api/v1/sql_service.go
- backend/plugin/parser/sql/utils.go
- backend/plugin/parser/sql/utils_test.go
> feat: implement Postgres table-level query permission check

- frontend/src/components/Issue/form/GrantRequestExporterForm.vue
- frontend/src/components/Issue/form/GrantRequestQuerierForm.vue
- frontend/src/components/Issue/logic/GrantRequestModeProvider.ts
> chore: add expired time field to exporter form

- frontend/src/components/Issue/form/GrantRequestExporterForm.vue
- frontend/src/plugins/issue/logic/initialize/grantRequest.ts
- frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
> chore: add back export button in SQL Editor

- backend/api/v1/debug_interceptor.go
- backend/server/server.go
Log internal errors encountered in gprc calls so that we won't miss anything!
> feat: log grpc call error

- frontend/src/plugins/issue/logic/common.ts
> chore: handle schema group list empty value

- backend/server/issue.go
> chore: remove the number of table groups checked by the backend creation issue

- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
- frontend/src/router/index.ts
- frontend/src/store/modules/v1/sql.ts
- frontend/src/views/DashboardSidebar.vue
- frontend/src/views/ExportCenter/ExportDataButton.vue
- frontend/src/views/ExportCenter/ExportRecordTable.vue
- frontend/src/views/ExportCenter/index.vue
- frontend/src/views/ExportCenter/types.ts
> feat: implement export center

- frontend/src/components/DatabaseGroup/MatchedDatabaseView.vue
- frontend/src/components/DatabaseGroup/MatchedTableView.vue
- frontend/src/layouts/ProjectLayout.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/subscription/en-US.json
- frontend/src/locales/zh-CN.json
- frontend/src/plugins/cel/logic/stringify.ts
Close BYT-3342, BYT-3345, BYT-3339
> chore: update empty expression string to `true`

- backend/migrator/migration/prod/2.2/0005##update_vcs_push_event_field_name.sql
fix https://github.com/bytebase/bytebase/pull/4634/files#diff-e1a74c5341dea654a19f347617331a06a97374f76f1d288f6e7685cd11b16d2eR46
Should backport to 2.2.0 and also need to update the schema version when backporting.
Tested locally with 
```
{
"pushEvent": {
"ref": "refs/heads/main",
"baseDir": "bytebase",
"commits": [
{
"ID": "id1",
"URL": "http://gitlab.bytebase.com/cy/employee/-/commit/e8917d670f192376ded2bd54248cc99c2bd65f19",
"Title": "Update bytebase/Test/DEMO__20220922002__migrate__test.sql",
"Message": "Update bytebase/Test/DEMO__20220922002__migrate__test.sql",
"AddedList": ["bytebase/Test/DEMO__20220922002__migrate__test.sql"],
"CreatedTs": 1664531654,
"AuthorName": "cy",
"AuthorEmail": "[cy@bytebase.com](mailto:cy@bytebase.com)",
"ModifiedList": []
},
{
"ID": "id2",
"URL": …
```
> fix: pushEvent commits field name

- frontend/src/components/DatabaseGroup/DatabaseGroupForm.vue
- frontend/src/components/DatabaseGroup/DatabaseGroupPanel.vue
- frontend/src/components/DatabaseGroup/DatabaseGroupTable.vue
- frontend/src/components/DatabaseGroup/MatchedDatabaseView.vue
- frontend/src/components/DatabaseGroup/SelectSchemaGroupsTable.vue
- frontend/src/components/v2/Form/ResourceIdField.vue
- frontend/src/components/v2/Model/DatabaseV1Table.vue
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
- frontend/src/store/modules/dbGroup.ts
> feat: add placeholder field to db group

- frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
- frontend/src/components/AlterSchemaPrepForm/DatabaseGroupPrevEditorModal.vue
- frontend/src/components/DatabaseGroup/SelectDatabaseGroupTable.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
- frontend/src/plugins/issue/logic/common.ts
- frontend/src/plugins/issue/logic/initialize/tenant.ts
- frontend/src/store/modules/dbGroup.ts
- frontend/src/utils/databaseGroup/issue.ts
- frontend/src/views/DatabaseGroupDetail.vue
- frontend/src/views/SchemaGroupDetail.vue
> chore: add database group prev editor modal

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/bbkit/BBAlert.vue
- frontend/src/bbkit/BBAlertDialog.vue
- frontend/src/bbkit/BBModal.vue
- frontend/src/bbkit/BBModalStack.vue
- frontend/src/components/CustomApproval/Settings/components/common/ExprEditor/factor.ts
- frontend/src/plugins/ai/components/AIChatToSQL.vue
- frontend/src/plugins/sql-lsp/client/useLanguageClient.ts
- Better universal z-index management to prevent modals, drawers, and popovers from twisting altogether.
- Double-check to prevent race conditions to stop monaco editor's language client.
- Remove `request.row_limit` from risk condition editor.
- Fix wrong parameter use case.
> chore(frontend): minor improvements and bug fixes

- backend/api/v1/review_service.go
Revert of revert https://github.com/bytebase/bytebase/pull/6082
> chore: resolve the approved query approval issue

- backend/api/v1/review_service.go
Reverts bytebase/bytebase#6529
> chore: Revert "chore: resolve the approved query approval issue"

- frontend/src/components/Issue/IssueTaskStatementPanel.vue
- frontend/src/components/Issue/logic/TenantModeProvider.ts
- frontend/src/components/Issue/logic/common.ts
- frontend/src/plugins/issue/logic/initialize/helper.ts
- frontend/src/types/issue.ts
- frontend/src/types/pipeline/task.ts
- frontend/src/views/ProfileDashboard.vue
> chore: disallow edit task for grouping issue

- backend/common/retry.go
- backend/component/activity/manager.go
- add context to common.Retry
- fix the blocking postWebhookList func
> fix: post webhook list

- frontend/src/grpcweb/index.ts
- frontend/src/grpcweb/middlewares/authInterceptorMiddleware.ts
- frontend/src/grpcweb/middlewares/index.ts
- Response code UNAUTHENTICATED will lead to a "kick out" of login status and redirection to the login page.
- Response code PERMISSION_DENIED will lead to redirection to the 403 page.
Close BYT-3310
> chore(frontend): introduce grpc-web auth interceptor middleware

- frontend/src/components/ProjectWebhookForm.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
> fix: localization

- frontend/src/bbkit/BBTooltipButton.vue
- frontend/src/components/Issue/review/IssueReviewButtonGroup.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
> feat(frontend): disallow to approve review when some task checks didn't pass

- frontend/src/bbkit/BBModal.vue
- frontend/src/components/AlterSchemaPrepForm/ProjectTenantView.vue
- frontend/src/components/v2/Model/DatabaseV1Table.vue
> fix(frontend): minor bug fixes

- frontend/src/components/DatabaseGroup/DatabaseGroupForm.vue
- frontend/src/components/DatabaseGroup/DatabaseGroupPanel.vue
- frontend/src/components/DatabaseGroup/MatchedDatabaseView.vue
- frontend/src/components/DatabaseGroup/SchemaGroupTable.vue
- frontend/src/components/DatabaseGroup/common/ExprEditor/ConditionGroup.vue
- frontend/src/components/v2/Model/DatabaseGroupName.vue
- frontend/src/plugins/cel/types/operator.ts
- frontend/src/router/index.ts
- frontend/src/store/modules/router.ts
- frontend/src/views/DatabaseGroupDetail.vue
- frontend/src/views/SchemaGroupDetail.vue
Close BYT-3374, BYT-3369, BYT-3373, BYT-3375
> chore: fix lots of issues of database grouping

- frontend/src/components/DatabaseGroup/DatabaseGroupForm.vue
- frontend/src/components/DatabaseGroup/DatabaseGroupPanel.vue
- frontend/src/components/DatabaseGroup/SchemaGroupTable.vue
- frontend/src/components/DatabaseGroup/SelectDatabaseGroupTable.vue
- frontend/src/components/DatabaseGroup/common/ExprEditor/ConditionGroup.vue
- frontend/src/components/Issue/logic/TenantModeProvider.ts
- frontend/src/components/v2/Model/DatabaseGroupName.vue
- frontend/src/plugins/cel/logic/resolve.ts
- frontend/src/views/DatabaseGroupDetail.vue
> chore: fix some grouping issues

- frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
- frontend/src/components/AlterSchemaPrepForm/DatabaseGroupPrevEditorModal.vue
- frontend/src/components/DatabaseGroup/DatabaseGroupForm.vue
- frontend/src/store/modules/dbGroup.ts
> chore: add validate issue in prev editor

- frontend/src/components/EnvironmentForm.vue
> chore(frontend): fix displayed environment id

- backend/plugin/db/mysql/dump.go
MySQL parser cannot parse OceanBase-specific table option
> chore: skip create table option for OceanBase

- frontend/src/components/Issue/IssueTaskSDLPanel.vue
- frontend/src/types/pipeline/task.ts
* fix: task statement
* fix: eslint
> cherrypick: fix: task statement (#6592)

- backend/api/v1/auth_service.go
- frontend/src/views/ProfileDashboard.vue
> fix: allow set empty phone

- frontend/src/bbkit/BBAvatar.vue
- frontend/src/components/Issue/IssueBanner.vue
- frontend/src/components/Issue/activity/ActionIcon.vue
- frontend/src/components/Issue/activity/ActionSentence.vue
- frontend/src/components/Issue/review/ApprovalTimeline.vue
- frontend/src/components/Issue/review/IssueReviewButtonGroup.vue
- frontend/src/components/Issue/review/IssueReviewForm.vue
- frontend/src/components/PrincipalAvatar.vue
- frontend/src/components/User/UserAvatar.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
- frontend/src/plugins/issue/logic/review/context.ts
- frontend/src/plugins/issue/logic/review/index.ts
- frontend/src/store/modules/review.ts
- frontend/src/types/review.ts
- frontend/src/utils/pipeline.ts
> feat(frontend): implement issue review rejection

- frontend/src/components/InstanceForm/InstanceForm.vue
- frontend/src/store/modules/v1/instance.ts
A quick way to solve BYT-3388. Though it's not very graceful.
> chore(frontend): suppress unnecessary error notifications

- backend/runner/taskrun/executor.go
- backend/server/openapi_sql.go
> feat: enable OceanBase SDL

- frontend/src/components/ProvideSQLEditorContext.vue
- frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable.vue
- frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/TableCell.vue
> feat(sql-editor): truncate long data and display full detail in popup

- frontend/src/components/ProjectMember/AddProjectMember/AddProjectMemberForm.vue
- frontend/src/components/ProjectMember/AddProjectMember/AddProjectMembersPanel.vue
- frontend/src/components/ProjectMember/AddProjectMember/EditProjectMemberPanel.vue
- frontend/src/components/ProjectMember/ProjectMemberPanel.vue
- frontend/src/components/ProjectMember/ProjectMemberTable/ProjectMemberRolePanel.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
Close BYT-3173, BYT-3335, BYT-3323
> feat: implement setting expiration time for project members

- frontend/src/components/QuickActionPanel.vue
- frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultView.vue
- frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
following https://github.com/bytebase/bytebase/pull/6633
> chore: update request export entries

- frontend/src/components/CustomApproval/Settings/components/CustomApproval/CustomApproval.vue
- frontend/src/components/CustomApproval/Settings/components/CustomApproval/ExternalApprovalNodesPanel/ExternalApprovalNodesPanel.vue
- frontend/src/components/CustomApproval/Settings/components/CustomApproval/ExternalApprovalNodesPanel/NodeDrawer.vue
- frontend/src/components/CustomApproval/Settings/components/CustomApproval/ExternalApprovalNodesPanel/NodeTable.vue
- frontend/src/components/CustomApproval/Settings/components/CustomApproval/ExternalApprovalNodesPanel/Toolbar.vue
- frontend/src/components/CustomApproval/Settings/components/CustomApproval/ExternalApprovalNodesPanel/index.ts
- frontend/src/components/CustomApproval/Settings/components/CustomApproval/Toolbar.vue
- frontend/src/components/CustomApproval/Settings/components/CustomApproval/common/RoleSelect.vue
- frontend/src/components/CustomApproval/Settings/components/CustomApproval/context.ts
- frontend/src/components/CustomApproval/Settings/components/CustomApproval/index.ts
- frontend/src/components/CustomApproval/Settings/components/CustomApproval/logic/validate.ts
- frontend/src/components/Issue/review/ApprovalTimeline.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
- frontend/src/store/modules/v1/setting.ts
- frontend/src/types/setting.ts
- frontend/src/utils/workspaceApprovalSetting.ts
- frontend/src/views/SettingWorkspaceCustomApproval.vue
**[CAUTION]** this node cannot be approved yet.
> feat(frontend): define external approval nodes and use in custom approval flows

- frontend/src/components/Issue/IssueTaskStatementPanel.vue
- Show the [Edit] button correctly
> fix(frontend): show edit statement button correctly

- frontend/src/components/Issue/IssueHighlightPanel.vue
- Remove duplicated [Cancel issue] button
> fix(frontend): remove duplicated [Cancel issue] button for grant request issues

- frontend/src/components/Issue/panel/RequestExportPanel/SelectTableForm/Label.vue
- frontend/src/components/Issue/review/IssueReviewSidebarSection.vue
> chore: hide approval tooltip for grant request issue

- backend/api/v1/review_service.go
revert https://github.com/bytebase/bytebase/pull/6531
> chore: revert "revert auto resolve grant request issues"

- frontend/src/components/Issue/form/GrantRequestExporterForm.vue
- frontend/src/components/Issue/form/GrantRequestQuerierForm.vue
- frontend/src/components/Issue/panel/RequestExportPanel/index.vue
- frontend/src/components/Issue/table/DatabaseResourceTable.vue
- frontend/src/components/QuickActionPanel.vue
- frontend/src/views/DashboardSidebar.vue
- frontend/src/views/ExportCenter/ExportRecordTable.vue
- frontend/src/views/ExportCenter/index.vue
- frontend/src/views/ExportCenter/types.ts
> chore: update request export and export center

- frontend/src/components/SchemaEditor/Panels/TableEditor.vue
> fix(schema-editor): dropdown popover teleport target

- backend/store/anomaly.go
Fix anomaly update syntax error
> fix: update anomaly

- backend/plugin/db/mysql/mysql.go
* chore: log more from mysql driver
* chore: override the database connection configuration
> chore: override the database connection configuration (#6661)

- frontend/src/components/AnomalyTable.vue
> fix(frontend): "check instance" link to 404 in anomaly table

- frontend/src/components/Breadcrumb.vue
> fix(frontend): wrong field usecase

- frontend/src/plugins/issue/logic/review/index.ts
> fix(frontend): don't go further when rejected

- backend/plugin/db/util/driverutil_test.go
- backend/plugin/db/util/mask_sensitive_data.go
- backend/plugin/db/util/mask_sensitive_data_plsql.go
- backend/plugin/parser/sql/plsql.go
> feat: implement Oracle anonymization for simple cases

- frontend/src/components/DatabaseGroup/common/ExprEditor/factor.ts
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
- frontend/src/plugins/cel/types/factor.ts
- frontend/src/plugins/cel/types/operator.ts
Rename factor `resource.instance_name` to `resource.instance_id`.
> chore: rename factor name in database grouping

- frontend/src/bbkit/BBModal.vue
- frontend/src/components/AccessControl/AddRuleForm.vue
- frontend/src/components/CustomApproval/Settings/components/RiskCenter/RiskDialog/RuleTemplateTable.vue
- frontend/src/components/CustomApproval/Settings/components/RiskCenter/RiskDialog/ViewTemplate.vue
- frontend/src/components/SchemaEditor/Panels/TableEditor.vue
- frontend/src/views/SettingWorkspaceAccessControl.vue
To avoid z-index twisting with the Drawer, we re-implement BBModal via NModal. Keeping the APIs and styles not changed.
> refactor(frontend): re-implement BBModal via NModal

- frontend/src/components/Issue/review/ApprovalTimeline.vue
- frontend/src/components/Issue/review/ExternalApprovalNodeSyncButton.vue
- frontend/src/store/modules/review.ts
> feat(frontend): implement sync external approval node button

- frontend/src/components/Issue/rollback/RollbackStatus.vue
> fix(frontend): use correct original sheet id to generate rollback issue's description

- backend/api/v1/database_service.go
https://github.com/bytebase/bytebase/blob/release/2.0.0/backend/server/database.go#L221
> chore: sync through on getting database metadata and schema

- backend/legacyapi/plan.go
- frontend/src/components/DatabaseTable.vue
- frontend/src/components/Project/ProjectCreatePanel.vue
- frontend/src/components/Project/ProjectGeneralSettingPanel.vue
- frontend/src/components/v2/Model/DatabaseTableRow.vue
- frontend/src/components/v2/Model/ProjectV1Table.vue
- frontend/src/layouts/ProjectLayout.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
Will add the corresponding doc link afterwards.
Fix BYT-3420
> feat: rebrand project tenant mode as batch mode

- frontend/src/components/Issue/review/IssueReviewButtonGroup.vue
> chore(frontend): color

- frontend/src/grpcweb/middlewares/authInterceptorMiddleware.ts
- frontend/src/store/modules/v1/sql.ts
Close BYT-3427
further improvements not included
> chore: allow to ignore some status codes when needed

- frontend/src/components/ProjectMember/AddProjectMember/AddProjectMemberForm.vue
- frontend/src/components/ProjectMember/AddProjectMember/AddProjectMembersPanel.vue
Close BYT-3428
Only shows when number of pending add members > 1
> chore(frontend): allow to delete pending create members

- frontend/src/components/CustomApproval/Settings/components/RiskCenter/RiskDialog/RiskForm.vue
> fix(frontend): check field correctness

- frontend/src/grpcweb/middlewares/errorNotificationMiddleware.ts
> chore(frontend): mute NOT_FOUND notifications globally

- frontend/src/components/Issue/IssueHighlightPanel.vue
- frontend/src/views/ExportCenter/index.vue
Only shown when
- The issue status is "DONE", which means the approval flow is passed
- Current user is the creator of this issue.
> feat(frontend): add direct link to export center / sql editor for request export / querier issues

- backend/plugin/db/util/driverutil_test.go
- backend/plugin/db/util/mask_sensitive_data_plsql.go
> feat: extract Oracle Expression

- backend/plugin/db/util/driverutil_test.go
- backend/plugin/db/util/mask_sensitive_data_plsql.go
> feat: extract Oracle set operation and JOIN

- backend/api/v1/sql_service.go
- frontend/src/components/ColumnTable.vue
> feat: enable Oracle data anonymization

- frontend/src/components/Issue/form/GrantRequestExporterForm.vue
- frontend/src/components/Issue/form/GrantRequestQuerierForm.vue
- frontend/src/components/Issue/panel/RequestExportPanel/SelectTableForm/common.ts
- frontend/src/components/Issue/panel/RequestExportPanel/SelectTableForm/index.vue
- frontend/src/components/Issue/panel/RequestExportPanel/index.vue
- frontend/src/components/Issue/panel/RequestQueryPanel/SelectDatabaseResourceForm/common.ts
- frontend/src/components/Issue/panel/RequestQueryPanel/index.vue
- frontend/src/components/Issue/table/DatabaseResourceTable.vue
- frontend/src/components/ProjectMember/ProjectMemberTable/ProjectMemberRolePanel.vue
- frontend/src/components/ProjectMember/ProjectMemberTable/types.ts
- frontend/src/types/issue.ts
- frontend/src/types/member.ts
- frontend/src/utils/issue/cel.ts
- frontend/src/views/ExportCenter/types.ts
- frontend/src/views/SchemaGroupDetail.vue
> chore: merge database resource types declare

- frontend/src/views/SettingSidebar.vue
Make it has the same overflow behavior as the dashboard sidebar.
> chore: update setting sidebar style

- frontend/src/components/Issue/IssueStagePanel.vue
- frontend/src/components/Issue/layout/DatabaseRelatedDetail.vue
> chore(frontend): don't show task run list if there is no task runs

- frontend/src/components/ProjectMember/AddProjectMember/AddProjectMembersPanel.vue
> fix: delete project member item when adding

- backend/plugin/db/redshift/redshift.go
> chore: don't use read-only transactions for redshift datashare

- frontend/src/components/Issue/IssueHighlightPanel.vue
- frontend/src/components/Issue/logic/transition.ts
> chore: remove reopen issue button for request granting issues

- frontend/src/bbkit/BBAlert.vue
- frontend/src/bbkit/BBButtonConfirm.vue
- frontend/src/components/Project/ProjectArchiveRestoreButton.vue
- frontend/src/components/ProjectSettingPanel.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
- frontend/src/store/modules/v1/project.ts
> feat(frontend): support --force option when archiving projects

- frontend/src/components/ProjectMember/ProjectMemberPanel.vue
- frontend/src/components/ProjectMember/ProjectMemberTable/ProjectMemberRolePanel.vue
- frontend/src/components/ProjectMember/ProjectMemberTable/ProjectMemberTable.vue
> chore: update style for project member table

- frontend/src/components/Issue/IssueDescriptionPanel.vue
- frontend/src/components/Issue/IssueTaskStatementPanel.vue
- frontend/src/components/misc/UploadProgressButton.vue
> chore: issue detail page buttons improvements

- backend/plugin/advisor/catalog/walk_through_for_pg.go
- backend/plugin/parser/sql/ast/index_def.go
- backend/plugin/parser/sql/engine/pg/convert.go
- backend/plugin/parser/sql/engine/pg/deparse.go
https://github.com/bytebase/bytebase/issues/6783
> chore: support ivfflat index type from pgvector

- backend/plugin/db/mysql/restore.go
https://github.com/bytebase/bytebase/issues/6767
MySQL 5.7 and 8.0 are different.
https://dev.mysql.com/doc/refman/5.7/en/show-binary-logs.html
https://dev.mysql.com/doc/refman/8.0/en/show-binary-logs.html
> chore: support variable results from SHOW BINARY LOGS

- backend/bin/server/cmd/profile.go
- backend/bin/server/cmd/root.go
- backend/component/config/profile.go
- backend/server/server.go
- backend/tests/tests.go
Reverts bytebase/bytebase#6781
> chore: Revert "feat(breaking-change): deprecate external url cli option"

- frontend/src/views/SyncDatabaseSchema/index.vue
Have to define the function before callers.
> chore: fix cannot access isValidID error

- backend/plugin/db/oracle/sync.go
https://github.com/bytebase/bytebase/issues/6663
Though it's better to display the columns and show them as invisible, this is the quick fix getting things to work.
> chore: filter out Oracle invisible columns

- frontend/src/components/TableTable.vue
> fix(frontend): url encoding

- frontend/src/components/ProjectMember/ProjectMemberPanel.vue
- frontend/src/components/ProjectMember/ProjectMemberTable/ProjectMemberRolePanel.vue
- frontend/src/components/ProjectMember/ProjectMemberTable/ProjectMemberTable.vue
- frontend/src/components/ProjectMember/ProjectMemberTable/RoleExpiredTip.vue
- frontend/src/components/ProjectMember/ProjectMemberTable/types.ts
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
> chore: show warning for expired roles

- frontend/src/bbkit/BBOutline.vue
- frontend/src/bbkit/types.ts
- frontend/src/components/DatabaseGroupIcon.vue
- frontend/src/components/DatabaseListSidePanel.vue
- frontend/src/types/dbGroup.ts
> chore: add database groups into dashboard sidebar

- backend/api/v1/sql_service.go
> fix: deal with empty resource list for QUERY

- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
- frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue
- frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
> feat(frontend): display query elapsed time

- frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
Following #6810 
Close BYT-3397
> chore(frontend): display executed sql statement

- frontend/src/components/Issue/review/Candidates.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
> feat(frontend): show a tooltip if there's no user in a role of a review step

- backend/api/v1/sql_service.go
- backend/plugin/advisor/catalog/walk_through.go
- backend/plugin/advisor/mysql/parser.go
- backend/plugin/db/mysql/mysql.go
- backend/plugin/db/util/driverutil.go
- backend/plugin/parser/sql/mysql.go
- backend/plugin/parser/sql/mysql_test.go
- backend/plugin/parser/sql/split_multi_sql_test.go
- backend/plugin/parser/sql/transform/mysql/transform_test.go
- backend/plugin/parser/sql/utils.go
- backend/plugin/parser/sql/utils_test.go
* fix: optimize MySQL parser performance
* chore: fix linter
* fix: fix tests
* fix: fix tests
> cherrypick: fix: optimize MySQL parser performance (#6777)

- backend/server/webhook.go
> chore: update vcs sql review result order

- backend/plugin/advisor/mysql/parser.go
- backend/plugin/advisor/mysql/test/column_disallow_change.yaml
- backend/plugin/advisor/mysql/test/column_disallow_changing_order.yaml
- backend/plugin/advisor/mysql/test/statement_disallow_commit.yaml
- backend/plugin/advisor/mysql/test/system_charset_allowlist.yaml
- backend/plugin/advisor/mysql/test/system_collation_allowlist.yaml
- backend/tests/test-data/sql_review_mysql.yaml
> chore: use TiDB parser before MySQL parser

- frontend/src/components/Instance/InstanceArchiveRestoreButton.vue
- frontend/src/components/Instance/index.ts
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
- frontend/src/store/modules/v1/instance.ts
- frontend/src/views/InstanceDetail.vue
> feat(frontend): support --force option when archiving instance

- backend/api/v1/sql_service.go
- backend/plugin/advisor/snowflake/advisor_column_no_null.go
- backend/plugin/advisor/snowflake/advisor_column_require.go
- backend/plugin/advisor/snowflake/advisor_naming_identifier_case.go
- backend/plugin/advisor/snowflake/advisor_naming_identifier_no_keyword.go
- backend/plugin/advisor/snowflake/advisor_naming_table_no_keyword.go
- backend/plugin/advisor/snowflake/advisor_table_no_foreign_key.go
- backend/plugin/advisor/snowflake/advisor_table_require_pk.go
- backend/plugin/advisor/snowflake/parser.go
- backend/plugin/parser/sql/plsql.go
- backend/plugin/parser/sql/snowsql.go
- backend/plugin/parser/sql/snowsql_test.go
- backend/plugin/parser/sql/utils.go
- backend/plugin/parser/sql/utils_test.go
- backend/store/policy.go
> feat(snowflake, data-access-control): support data access control database/table level for snowflake

- frontend/src/components/InstanceForm/InstanceForm.vue
- frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/TableCell.vue
A naive implementation. Not good, but it works.
Close BYT-3470
> feat(sql-editor): disallowing copy/paste the query result

- frontend/src/components/Issue/logic/TenantModeProvider.ts
- frontend/src/components/Issue/logic/common.ts
> chore(frontend): allow workspace owner/dba to edit sql statement of issues

- frontend/src/components/TenantDatabaseTable/DeployDatabaseTable.vue
> chore(frontend): left-align for databases in the batch deployment matrix

- backend/api/v1/org_policy_service.go
- backend/api/v1/setting_service.go
- backend/server/issue.go
- frontend/src/components/BannersWrapper.vue
- frontend/src/components/InstanceForm/InstanceForm.vue
- frontend/src/layouts/BodyLayout.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
- frontend/src/store/modules/v1/subscription.ts
- frontend/src/types/setting.ts
- frontend/src/views/BannerSubscription.vue
> fix: check if the trial already exists

- frontend/src/components/Issue/IssueTaskStatementPanel.vue
- frontend/src/components/misc/UploadProgressButton.vue
> chore(frontend): error handling when upload sheet max size exceeded

- frontend/src/components/SlowQuery/Panel/LogFilter.vue
- frontend/src/components/SlowQuery/Panel/LogTable.vue
- frontend/src/components/SlowQuery/Panel/SlowQueryPanel.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
> feat(frontend): slow query guide improvements

- frontend/src/views/ExportCenter/index.vue
> chore: add feature badge to request export button

- frontend/src/components/DatabaseGroup/DatabaseGroupForm.vue
- frontend/src/components/FunctionDefinitionView.vue
> chore: fix typo

- backend/api/v1/sql_service.go
- frontend/src/components/ProvideDashboardContext.vue
- frontend/src/components/ProvideSQLEditorContext.vue
- frontend/src/utils/policy.ts
- frontend/src/utils/v1/database.ts
> chore: update database accessible with workspace IAM policy

- backend/migrator/migration/dev/LATEST.sql
- backend/migrator/migration/prod/2.4/0001##add_service_name_to_db.sql
- backend/migrator/migration/prod/LATEST.sql
- backend/migrator/migrator_test.go
> feat: add service_name to db

- frontend/src/components/CustomApproval/Settings/components/RiskCenter/RiskCenter.vue
- frontend/src/components/CustomApproval/Settings/components/common/ExprEditor/components/FactorSelect.vue
- frontend/src/components/CustomApproval/Settings/components/common/ExprEditor/factor.ts
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
- frontend/src/plugins/cel/types/factor.ts
- frontend/src/plugins/cel/types/operator.ts
- frontend/src/types/risk.ts
> feat(frontend): configure risk levels for request query / request export and use them in custom approval flows

- frontend/src/store/modules/connectionTree.ts
- frontend/src/views/sql-editor/TerminalPanel/CompactSQLEditor.vue
A down-grade implement to close BYT-3260
> chore(frontend): don't fetch db schema eagerly when connecting to instance scope

- frontend/src/components/DatabaseOverviewPanel.vue
- frontend/src/components/DefinitionView.vue
- frontend/src/components/FunctionTable.vue
- frontend/src/components/StreamTable.vue
- frontend/src/components/TaskTable.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
> chore: add stream and task table for snowflake database

- frontend/naive-ui.config.ts
- frontend/src/bbkit/BBAttention.vue
- frontend/src/components/Issue/IssueTaskStatementPanel.vue
- frontend/src/components/Sheet/DownloadSheetButton.vue
- frontend/src/views/sql-editor/EditorPanel/SheetForIssueTipsBar.vue
> feat(frontend): download sheet 

- frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue
- frontend/src/views/sql-editor/EditorCommon/index.ts
- Enable virtual scrolling
- Throttle the search pattern, won't update the filter more than once in each 100ms.
Close BYT-3425
> chore(sql-editor): performance tuning for searching the database tree

- backend/bin/server/cmd/root.go
- backend/migrator/demo/default/10110##task.sql
- backend/migrator/demo/default/10130##issue.sql
- docs/schema-update-guide.md
- frontend/src/views/BannerUpgradeSubscription.vue
Do not use bb.task.general/bb.issue.general since that's not implemented in the UI.
The SQL statement is not displayed though since the underlying data structure has been changed. But at least we can show the issue.
> chore: disable subscription banner in demo mode and fix demo data

- frontend/src/components/InstanceForm/InstanceForm.vue
> chore: add a link to the subscription page in instance license assignment control

- backend/tests/backup_restore_test.go
- backend/tests/external_approval_test.go
- backend/tests/sql_review_test.go
https://github.com/bytebase/bytebase/pull/6897 changes the default.
> chore: fix test from default rollout policy

- frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
> chore: enlarge y spacing between query result and toolbar

- frontend/naive-ui.config.ts
- frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
> fix(sql-editor): button color in dark mode

- backend/api/v1/sql_service.go
> fix: use correct err variable

- frontend/src/views/SettingWorkspaceAccessControl.vue
> chore: change skip approval value to `false` in free/pro plans

- frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
- frontend/src/views/sql-editor/EditorCommon/ResultView/useExportData.ts
> chore(frontend): add `admin` flag to `export` when needed

- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
- frontend/src/views/sql-editor/EditorPanel/EditorPanel.vue
- Display part of (10k) the sheet
- Updated wording
Before
After
> chore(sql-editor): improve displaying for oversize sheets

- frontend/src/views/sql-editor/EditorCommon/ResultView/ErrorView.vue
- frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue
> chore(sql-editor): update layout for "Request Query" button

- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
Environment tier no longer determines data access control
> feat: remove access control description for env tier

- backend/api/v1/instance_service.go
- backend/component/dbfactory/dbfactory.go
- backend/plugin/db/driver.go
- backend/plugin/db/oracle/dump.go
- backend/plugin/db/oracle/oracle.go
- backend/plugin/db/oracle/sync.go
> feat: impl sync and dump for schema as db

- frontend/src/components/Issue/IssueTaskStatementPanel.vue
> chore(frontend): allow update sql files multiple times when creating issues

- frontend/src/store/modules/v1/projectIamPolicy.ts
- frontend/src/utils/v1/database.ts
- frontend/src/views/sql-editor/AsidePanel/SchemaPanel/DatabaseSchema.vue
> feat: filter unavailable tables in sql editor panel

- frontend/src/components/FeatureGuard/FeatureAttention.vue
- frontend/src/components/FeatureGuard/FeatureModal.vue
- frontend/src/layouts/BodyLayout.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
- frontend/src/utils/role.ts
- frontend/src/views/SettingWorkspaceSubscription.vue
- frontend/src/views/SyncDatabaseSchema/index.vue
> chore: update for feature guard

- backend/api/v1/sql_service.go
- backend/plugin/db/oracle/oracle.go
> feat: impl Query for schema tenant mode Oracle

- backend/api/v1/rollout_service.go
- backend/api/v1/sheet_service.go
- backend/runner/rollbackrun/runner.go
- backend/runner/taskcheck/statement_advisor_composite_executor.go
- backend/runner/taskcheck/statement_affected_rows_report_executor.go
- backend/runner/taskcheck/statement_type_executor.go
- backend/runner/taskcheck/statement_type_report_executor.go
- backend/runner/taskrun/database_create_executor.go
- backend/server/issue.go
- backend/server/server.go
- backend/server/webhook.go
- backend/store/database.go
- backend/store/sheet.go
- backend/store/stats.go
* move `CountSheetGroupByRowstatusVisibilitySourceAndType` to `stats.go`;
* remove `V2` suffix string of methods;
> chore: update sheet store

- frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
> fix(sql-editor): export query result with split SQL statement

- frontend/src/store/modules/v1/policy.ts
> chore: add `toLowerCase` when getting policy

- backend/plugin/db/util/driverutil_test.go
- backend/plugin/db/util/mask_sensitive_data_plsql.go
- go.mod
- go.sum
> feat: support CTE for oracle data anonymization

- backend/plugin/advisor/snowflake/snowflake_rules_test.go
- backend/plugin/advisor/snowflake/test/statement_where_require.yaml
- backend/plugin/db/util/driverutil_test.go
- backend/plugin/db/util/mask_sensitive_data_snowsql.go
- go.mod
- go.sum
> chore(snowsql-parser): upgrade the snowsql parser version

- backend/utils/utils.go
- frontend/src/components/CustomApproval/Settings/components/CustomApproval/ExternalApprovalNodesPanel/NodeTable.vue
- frontend/src/components/CustomApproval/Settings/components/CustomApproval/ExternalApprovalNodesPanel/Toolbar.vue
- frontend/src/components/CustomApproval/Settings/components/CustomApproval/FlowsPanel/FlowTable.vue
- frontend/src/components/CustomApproval/Settings/components/CustomApproval/FlowsPanel/Toolbar.vue
- frontend/src/components/CustomApproval/Settings/components/CustomApproval/RulesPanel/RuleSelect.vue
- frontend/src/components/CustomApproval/Settings/components/RiskCenter/RiskCenter.vue
- frontend/src/components/CustomApproval/Settings/components/RiskCenter/RiskTable.vue
- Bugfix: Looks like we can only find the first approval flow
- Add missing feature guard for custom approval
> fix: 🔥approval flow and feature guard

- frontend/src/views/ChangeHistoryDetail.vue
- frontend/src/views/SyncDatabaseSchema/index.vue
> chore: add view full params when list change histories

- frontend/src/components/TransferDatabaseForm.vue
> chore(frontend): fix filter when transfer in databases

- frontend/src/components/TransferOutDatabaseForm/TransferOutDatabaseForm.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
> chore(frontend): ui update for transferring out databases

- backend/api/v1/sql_service.go
- backend/api/v1/sql_service_test.go
Following https://github.com/bytebase/bytebase/pull/7005
> fix: encode statement for cel matching in backend

- backend/api/v1/instance_service.go
> feat: impl update mask for instance options

- frontend/src/components/InstanceForm/InstanceForm.vue
- frontend/src/components/InstanceForm/OracleSyncModeInput.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
> feat(frontend): support oracle schema tenant mode

- backend/api/v1/common.go
- backend/api/v1/schema_design_service.go
- backend/store/instance_change_history.go
- backend/store/sheet.go
- frontend/src/types/proto/v1/schema_design_service.ts
- proto/gen/grpc-doc/v1/README.md
- proto/generated-go/v1/schema_design_service.pb.go
- proto/v1/schema_design_service.proto
Implements `GetSchemaDesign`, `ListSchemaDesigns`, `convertSheetToSchemaDesign`.
> feat: implement schema design service

- frontend/src/components/Issue/TaskCheckRunPanel.vue
Close BYT-3441
FYI @adela-bytebase
> chore(frontend): update review code format

- backend/api/v1/sql_service.go
- backend/plugin/advisor/oracle/test/column_required.yaml
- backend/plugin/advisor/oracle/test/table_require_pk.yaml
- backend/plugin/advisor/sql_review.go
- backend/plugin/db/util/mask_sensitive_data_plsql.go
- backend/plugin/parser/sql/plsql.go
- backend/plugin/parser/sql/plsql_test.go
- backend/plugin/parser/sql/split_multi_sql_test.go
- backend/plugin/parser/sql/utils.go
> chore: use parser to split multi-plsql

- backend/api/v1/org_policy_service.go
- backend/api/v1/rollout_service.go
- backend/legacyapi/policy.go
We should do the sheet existence check in the plan functions.
> chore: skip sheet check

- frontend/src/components/ProvideSQLEditorContext.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
- frontend/src/views/SettingWorkspaceAccessControl.vue
- frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/TableCell.vue
- frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue
- frontend/src/views/sql-editor/EditorCommon/ResultView/context.ts
> feat(frontend): Environment policy for disabling copy data in SQL Editor

- backend/plugin/db/mysql/dump.go
https://dev.mysql.com/doc/refman/8.0/en/show-create-trigger.html
https://dev.mysql.com/doc/refman/5.7/en/show-create-trigger.html
http://www.innodbcluster.com/?depth=13070513
> chore: get trigger statement compatible with mysql 5.6

- frontend/src/components/SchemaDesigner/AsidePanel.vue
- frontend/src/components/SchemaDesigner/DatabaseTree.vue
- frontend/src/components/SchemaDesigner/EmptyTips.vue
- frontend/src/components/SchemaDesigner/Modals/ActionConfirmModal.vue
- frontend/src/components/SchemaDesigner/Modals/EditColumnForeignKeyModal.vue
- frontend/src/components/SchemaDesigner/Modals/SchemaNameModal.vue
- frontend/src/components/SchemaDesigner/Modals/TableNameModal.vue
- frontend/src/components/SchemaDesigner/Panels/TableEditor.vue
- frontend/src/components/SchemaDesigner/PrepForm/SchemaDesignTable.vue
- frontend/src/components/SchemaDesigner/PrepForm/index.vue
- frontend/src/components/SchemaDesigner/TabsContainer.vue
- frontend/src/components/SchemaDesigner/common/context.ts
- frontend/src/components/SchemaDesigner/common/index.ts
- frontend/src/components/SchemaDesigner/common/type.ts
- frontend/src/components/SchemaDesigner/index.vue
- frontend/src/components/SchemaDesigner/utils/column.ts
- frontend/src/components/SchemaDesigner/utils/schema.ts
- frontend/src/components/SchemaDesigner/utils/table.ts
- frontend/src/store/modules/v1/common.ts
This PR initials schema designer components from schema editor. 
Compared to schema editor, we use the proto generated objects(`DatabaseMetadata`/`SchemaMetadata`/`TableMetadata`...) as the state object definition in schema designer.
> feat: initial schema designer components

- backend/plugin/db/pg/pg.go
- backend/plugin/db/pg/sync.go
> fix: deal with lower version pg_stat_statements

- frontend/src/components/FeatureGuard/FeatureBadge.vue
- frontend/src/components/v2/Select/ProjectMemberRoleSelect.vue
> feat(frontend): feature badge for custom roles in plans not supported

- backend/api/v1/auth_service.go
- backend/api/v1/environment_service.go
- backend/api/v1/idp_service.go
- backend/api/v1/instance_role_service.go
- backend/api/v1/instance_service.go
- backend/api/v1/project_service.go
> chore: fix deleted resource behavior

- backend/plugin/db/oracle/oracle.go
> fix: skip empty schema for schema tenant mode

- frontend/src/components/InstanceForm/InstanceForm.vue
> chore(frontend): use deep copy of instance.option

- frontend/src/components/InstanceForm/InstanceForm.vue
Don't shout out twice
Close BYT-3550
> chore(frontend): reduce redundant error notifications

- backend/api/v1/schema_design_service.go
- backend/api/v1/schema_design_service_test.go
- backend/api/v1/testdata/schema.yaml
> test: add tests for transformSchemaToMetadata

- frontend/src/views/SettingWorkspaceAccessControl.vue
Only post update access control when page loaded.
> fix: update access control policy

- frontend/src/components/FeatureGuard/FeatureModal.vue
Really strange..I wonder if this has the same reason as https://github.com/bytebase/bytebase/pull/7082 (maybe because of dependencies update?
Close BYT-3603
> fix: BYT-3603

- backend/api/v1/schema_design_service.go
- backend/api/v1/testdata/design.yaml
> feat: impl column type for schema design

- .github/workflows/build-artifacts-and-draft-release.yml
Reverts bytebase/bytebase#6773
> chore: Revert "chore: update release draft action"

- scripts/.goreleaser-for-darwin.yaml
- scripts/.goreleaser-for-linux.yaml
https://goreleaser.com/deprecations/#archivesreplacements
> chore: deprecate archive

- backend/api/v1/common.go
- backend/api/v1/rollout_service.go
- backend/store/task_run.go
> feat: impl list rollout task runs

- frontend/src/components/CreateDatabasePrepForm/CreateDatabasePrepForm.vue
- frontend/src/components/DatabaseBackup/BackupTable.vue
- frontend/src/components/DatabaseBackupPanel.vue
- frontend/src/components/DatabaseDetail/PITRRestoreButton.vue
- frontend/src/views/SyncDatabaseSchema/index.vue
> chore(frontend): use database name field correctly

- backend/api/v1/auth_service.go
- backend/api/v1/auth_service_test.go
- frontend/src/utils/idp.ts
* update the default value to email for idp templates;
* add extract domain function and tests;
> chore: update idp default value

- backend/runner/metricreport/reporter.go
> chore: update metric for subscription start&end time

- backend/bin/server/cmd/root.go
- backend/migrator/migrator.go
- backend/migrator/migrator_test.go
* docs: add book demo to readme
* chore: pass —disable-sample to .air.toml
* chore: update startup log
> cherrypick: chore: update startup log (#7113)

- backend/api/v1/schema_design_service.go
- backend/api/v1/testdata/design.yaml
- backend/api/v1/testdata/schema.yaml
> feat: impl design schema for column attr

- frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue
> chore(frontend): disableCopyDataPolicy should be only applicable to workspace developers

- backend/api/v1/instance_service.go
Useful for Oracle changing schema as database flag.
> chore: sync instance on update

- backend/api/v1/schema_design_service.go
- backend/api/v1/testdata/design.yaml
- backend/api/v1/testdata/schema.yaml
- backend/plugin/parser/sql/mysql.go
> feat: impl design schema for PK

- frontend/src/components/InstanceAssignment.vue
- frontend/src/components/InstanceForm/InstanceForm.vue
- Close BYT-3608: Developers won't be able to update the instance license.
- Close BYT-3613: Patch the instance license once users click the toggle.
> chore: optimize instance license

- backend/plugin/parser/sql/transform/mysql/transform.go
> fix: skip invalid statements for TiDB parser

- backend/api/v1/schema_design_service.go
- backend/api/v1/testdata/design.yaml
- backend/api/v1/testdata/schema.yaml
- backend/plugin/parser/sql/mysql.go
> feat: impl design schema for FK

- frontend/src/components/ProjectMember/ProjectMemberTable/ProjectMemberRolePanel.vue
- frontend/src/locales/en-US.json
> chore(frontend): fix translation

- backend/api/v1/schema_design_service.go
- backend/api/v1/schema_design_service_test.go
- backend/api/v1/testdata/check.yaml
> feat: impl check user defined schema metadata

- frontend/src/components/SchemaDesigner/CreateSchemaDesignPanel.vue
- frontend/src/components/SchemaDesigner/PrepForm/index.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
https://github.com/bytebase/bytebase/assets/24653555/bc09fd41-235d-4c76-bb19-2310adb8554b
> feat: add create schema design drawer

- frontend/src/components/v2/Model/Instance/InstanceV1EngineIcon.vue
> chore(frontend): fix icon squeezing

- backend/api/v1/schema_design_service.go
> fix: missing semicolon and new line for other constraints

- backend/api/v1/schema_design_service.go
- backend/api/v1/testdata/design.yaml
> fix: missing column type

- backend/plugin/advisor/code.go
- backend/plugin/advisor/sql_review.go
> chore: refine error message

- backend/api/v1/schema_design_service.go
- backend/api/v1/testdata/design.yaml
> fix: distinguish between no default and default null

- frontend/src/components/QuickActionPanel.vue
- frontend/src/components/SchemaDesigner/CreateSchemaDesignPanel.vue
- frontend/src/components/SchemaDesigner/PrepForm/SchemaDesignTable.vue
- frontend/src/components/SchemaDesigner/PrepForm/index.vue
- frontend/src/views/SyncDatabaseSchema/SchemaDesignSelector.vue
- frontend/src/views/SyncDatabaseSchema/SelectTargetDatabasesView.vue
* Update additional information when viewing schema design;
* Update some detail styles;
* Remove `isDev` flag in the quick action bar.
> chore: update schema design table

- backend/api/v1/schema_design_service.go
- frontend/src/components/SchemaDesigner/BaselineSchemaSelector.vue
- frontend/src/components/SchemaDesigner/CreateSchemaDesignPanel.vue
- frontend/src/store/modules/v1/changeHistory.ts
- frontend/src/views/SyncDatabaseSchema/DatabaseSchemaSelector.vue
> feat(schema-designer): allow to use the latest schema of database as baseline

- backend/api/v1/issue_service.go
- backend/store/issue.go
> feat: convert plan id in get issue

- frontend/src/components/ChangeHistory/ChangeHistoryTable.vue
> fix(frontend): display enum value

- frontend/src/components/Issue/IssueTaskStatementPanel.vue
Postpone the sheet creation to when the issue is really created.
Close BYT-3566
> chore(frontend): allow editing uploaded SQL statements before issue is created

- backend/api/v1/sql_service.go
- backend/store/db_schema.go
> chore: support view for access control feature

- frontend/src/components/DatabaseChangeHistoryPanel.vue
> chore: fetch full view change history when exporting

- frontend/src/components/SchemaDesigner/DatabaseTree.vue
- frontend/src/components/SchemaEditor/DatabaseTree.vue
It's able to successfully render my test data of 4000 tables.
https://github.com/bytebase/bytebase/assets/24653555/0794b678-1f8f-4691-aa37-643ac6ec7ca8
> chore: use virtual list for rendering large list in database tree

- frontend/src/components/SchemaDesigner/DatabaseTree.vue
- frontend/src/components/SchemaDesigner/Modals/TableNameModal.vue
- frontend/src/components/SchemaDesigner/Panels/TableEditor.vue
- frontend/src/components/SchemaDesigner/TabsContainer.vue
- frontend/src/components/SchemaDesigner/common/type.ts
- frontend/src/components/SchemaDesigner/index.vue
- frontend/src/components/SchemaDesigner/utils/column.ts
- frontend/src/components/SchemaDesigner/utils/schema.ts
- frontend/src/components/SchemaDesigner/utils/table.ts
> chore: add computed class list to schema designer

- frontend/src/components/SchemaDesigner/Modals/EditColumnForeignKeyModal.vue
> fix(schema-designer): edit foreign keys

- backend/plugin/db/oracle/dump.go
> chore: handle error in oracle server when dumping schemas

- frontend/src/views/Home.vue
- frontend/src/views/IssueDashboard.vue
> chore(frontend): use case insensitive search for issue table

- frontend/src/components/SchemaDesigner/index.vue
- frontend/src/components/SchemaEditor/SchemaEditor.vue
* Only regenerate editing state when baseline schema changed.
* Add min-width to database tree.
> chore: update editing state regeneration

- frontend/src/components/Issue/table/DatabaseResourceTable.vue
- frontend/src/components/ProjectMember/ProjectMemberTable/ProjectMemberRolePanel.vue
- frontend/src/components/v2/Model/EnvironmentV1Name.vue
- frontend/src/components/v2/Model/Instance/InstanceV1Name.vue
- frontend/src/components/v2/Model/InstanceV1EngineIcon.vue
- frontend/src/components/v2/Model/InstanceV1Name.vue
> fix: text overflow in tables

- backend/legacyapi/task_check_run.go
- backend/plugin/advisor/advisor.go
- backend/plugin/advisor/sql_review.go
- backend/runner/taskcheck/statement_advisor_composite_executor.go
- backend/tests/test-data/sql_review_mysql.yaml
> chore: add column information for syntax error advice

- frontend/src/components/Issue/logic/common.ts
Check query existing before use it.
> chore: update `isGroupingChangeIssue`

- frontend/src/components/ChangeHistory/ChangeHistoryTable.vue
- frontend/src/components/DatabaseChangeHistoryPanel.vue
* allow to select DML change history
* adjust table cells width
* add select all button
> feat: add select all in database change history list

- frontend/src/types/proto/store/common.ts
- frontend/src/types/proto/v1/common.ts
The missing part from https://github.com/bytebase/bytebase/pull/7230
> chore: buf generate

- backend/api/v1/auth_service.go
- backend/api/v1/idp_service.go
- backend/plugin/idp/oauth2/oauth2.go
- backend/plugin/idp/oidc/oidc.go
> feat: add auth style field in backend

- backend/legacyapi/task_check_run.go
- frontend/src/components/Issue/TaskCheckRunPanel.vue
- frontend/src/components/Issue/logic/useSQLAdviceMarkers.ts
- frontend/src/types/pipeline/task.ts
> feat(frontend): support locating advisors errors with column

- backend/api/v1/schema_design_service.go
- frontend/src/components/SchemaDesigner/CreateSchemaDesignPanel.vue
- frontend/src/components/SchemaDesigner/EditSchemaDesignPanel.vue
- frontend/src/components/SchemaDesigner/PrepForm/index.vue
- frontend/src/components/SchemaDesigner/common/util.ts
- frontend/src/components/SchemaDesigner/index.vue
* extract view&edit schema design to a new drawer;
* fix duplicated comment when generating design schema;
> chore: update schema designer

- backend/server/issue.go
> fix: issue creation activity for grant access issues

- frontend/src/components/IdentityProviderCreateForm.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
- frontend/src/router/index.ts
- frontend/src/utils/idp.ts
> feat: add auth style radio group in frontend

- frontend/src/components/DatabaseSelect.vue
- frontend/src/components/SchemaDesigner/BaselineSchemaSelector.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
- frontend/src/views/SyncDatabaseSchema/DatabaseSchemaSelector.vue
> chore: update database selector placeholder

- frontend/src/views/SyncDatabaseSchema/SchemaDesignSelector.vue
> chore: add view button to schema design table

- backend/api/v1/acl.go
- backend/api/v1/anomaly_service.go
- backend/api/v1/database_service.go
- backend/api/v1/org_policy_service.go
- backend/api/v1/rollout_service.go
- backend/api/v1/schema_design_service.go
- backend/api/v1/sheet_service.go
- backend/api/v1/sql_service.go
- backend/runner/approval/runner.go
- backend/runner/plancheck/converter.go
- backend/runner/taskrun/pitr_restore_executor.go
- backend/server/openapi_sql.go
- backend/server/server.go
- backend/server/webhook.go
- backend/store/database.go
- backend/store/instance.go
- backend/store/slow_query.go
> feat: support MySQL/TiDB case insensitive database name

- backend/api/v1/sql_service.go
- backend/plugin/db/driver.go
- backend/plugin/db/util/mask_sensitive_data.go
- backend/store/db_schema.go
> feat: implement ignore case sensitive for extractResourceList and maskSensitiveData

- backend/api/auth/auth.go
- backend/api/auth/header.go
- backend/api/v1/auth_service.go
- backend/api/v1/setting_service.go
- backend/server/jwt.go
- backend/server/server.go
The server should be restarted to take the updated refresh token duration.
> feat: use refresh token duration

- frontend/src/components/Issue/StatusTransitionButtonGroup/BatchTaskActionDialog.vue
- frontend/src/components/Issue/StatusTransitionButtonGroup/CombinedRolloutButtonGroup.vue
- frontend/src/components/Issue/StatusTransitionButtonGroup/TaskStatusTransitionButtonGroup.vue
- frontend/src/components/Issue/logic/transition.ts
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
- frontend/src/plugins/issue/logic/initialize/assignee.ts
> feat(frontend): batch retry current stage

- frontend/src/components/GeneralSetting/SecuritySetting.vue
- frontend/src/components/GeneralSetting/SignInFrequencySetting.vue
I'll add i18n and new feature flag in another PR.
> chore: update sign-in frequency setting UI

- frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable.vue
- frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/TableCell.vue
- frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/useTableResize.ts
- frontend/src/views/sql-editor/EditorCommon/ResultView/DetailPanel.vue
- frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue
- frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
- frontend/src/views/sql-editor/EditorCommon/ResultView/context.ts
> feat(sql-editor): Improve experience of MongoDB query output

- backend/api/v1/acl.go
- backend/api/v1/anomaly_service.go
- backend/api/v1/database_service.go
- backend/api/v1/org_policy_service.go
- backend/api/v1/rollout_service.go
- backend/api/v1/schema_design_service.go
- backend/api/v1/sheet_service.go
- backend/api/v1/sql_service.go
- backend/plugin/parser/sql/differ/differ.go
- backend/plugin/parser/sql/differ/mysql/differ.go
- backend/plugin/parser/sql/differ/mysql/differ_test.go
- backend/plugin/parser/sql/differ/mysql/utils.go
- backend/plugin/parser/sql/differ/pg/differ.go
- backend/plugin/parser/sql/differ/pg/differ_test.go
- backend/runner/approval/runner.go
- backend/runner/plancheck/converter.go
- backend/runner/taskrun/pitr_restore_executor.go
- backend/runner/utils/sdl_utils.go
- backend/server/openapi_sql.go
- backend/server/server.go
- backend/server/webhook.go
- backend/store/instance.go
- backend/store/slow_query.go
> feat: implement case sensitivity for diffSchema

- backend/api/auth/header.go
- backend/server/jwt.go
This reverts commit 42acb96fa4d11c3f12185f6501d31f816ac7d7d3.
> revert: "chore: use refresh duration for cookie duration (#7289)"

- frontend/src/components/ChangeHistory/ChangeHistoryTable.vue
- frontend/src/components/DatabaseChangeHistoryPanel.vue
Only allow to select DONE change history.
> fix: filter selected change history status

- frontend/src/components/SchemaDesigner/EditSchemaDesignPanel.vue
- frontend/src/components/SchemaDesigner/PrepForm/SchemaDesignTable.vue
- frontend/src/views/SyncDatabaseSchema/SchemaDesignSelector.vue
- frontend/src/views/SyncDatabaseSchema/SelectTargetDatabasesView.vue
* remove engine icon column and add it into title column;
* add view mode in edit schema design panel to hide apply button;
* add a view button in schema schema page.
> fix: some schema designer issues

- frontend/src/components/RepositorySelectionPanel.vue
- frontend/src/components/VCSProviderConfirmPanel.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
> chore(azure-devops, style): update the style of the vcs setup

- frontend/src/components/QuickActionPanel.vue
- frontend/src/components/SchemaDesigner/EditSchemaDesignPanel.vue
- frontend/src/components/SchemaDesigner/Modals/EditColumnForeignKeyModal.vue
- frontend/src/components/SchemaDesigner/Panels/TableEditor.vue
- frontend/src/components/SchemaDesigner/PrepForm/index.vue
- frontend/src/components/SchemaDesigner/common/util.ts
- frontend/src/components/v2/Container/Drawer.vue
- frontend/src/types/schemaEditor/atomType.ts
- frontend/src/views/SyncDatabaseSchema/SelectTargetDatabasesView.vue
- frontend/src/views/SyncDatabaseSchema/index.vue
* fix schema design cache in sync schema
* update closing with esc in Drawer
> fix: schema design cache in sync schema

- backend/api/v1/subscription_service.go
- backend/enterprise/api/limit.go
- backend/enterprise/service/license.go
- backend/store/setting.go
- backend/tests/subscription_test.go
> chore: add user comment to parser

- backend/legacyapi/task_check_run.go
- backend/plugin/parser/sql/mysql.go
- backend/plugin/parser/sql/mysql_test.go
- backend/plugin/parser/sql/utils.go
- backend/runner/taskcheck/statement_type_report_executor.go
> feat: implement changed resources generation for MySQL

- frontend/src/components/SchemaEditor/Panels/TableEditor.vue
> chore: update field template drawer width

- backend/api/v1/setting_service.go
- frontend/src/store/modules/v1/setting.ts
- frontend/src/views/SchemaTemplate/ColumnTypes.vue
- frontend/src/views/SchemaTemplate/ColumnTypesUpdateFailedModal.vue
- frontend/src/views/SettingWorkspaceSchemaTemplate.vue
The related `i18n` will be updating in another PR.
> feat: implement column types template

- frontend/src/components/CustomApproval/Settings/components/common/RiskFilter/LevelFilter.vue
> chore: add risk label to indicate what high, moderate, low means

- frontend/src/components/SchemaDesigner/Panels/TableEditor.vue
- frontend/src/components/SchemaDesigner/index.vue
- frontend/src/views/SchemaTemplate/ColumnTypes.vue
> feat: use column types in schema designer

- backend/runner/taskrun/executor.go
- backend/store/task_check_run.go
> feat: store changed resources in instance migration history payload

- backend/api/v1/sql_service.go
- backend/plugin/parser/sql/parser.go
- backend/plugin/parser/sql/tsql.go
- backend/plugin/parser/sql/tsql_test.go
- backend/plugin/parser/sql/utils.go
- backend/store/instance.go
> feat(sql-server, data-access-control): data access control for sql server

- backend/bin/server/cmd/profile.go
- backend/bin/server/cmd/root.go
- backend/component/config/profile.go
- backend/component/state/state.go
- backend/legacyapi/task_run.go
- backend/runner/taskrun/schedulerv2.go
- backend/server/server.go
- backend/store/task.go
- backend/store/task_run.go
pass `--development-use-v2-scheduler` to activate v2 scheduler.
> feat: task scheduler v2

- frontend/src/components/DatabaseOverviewPanel.vue
> chore: set default schema to `public`

- frontend/src/store/modules/v1/sheet.ts
- frontend/src/views/SyncDatabaseSchema/RawSQLEditor.vue
- frontend/src/views/SyncDatabaseSchema/RawSQLEditorPanel.vue
- frontend/src/views/SyncDatabaseSchema/SelectTargetDatabasesView.vue
- frontend/src/views/SyncDatabaseSchema/TargetDatabasesSelectPanel.vue
- frontend/src/views/SyncDatabaseSchema/index.vue
- frontend/src/views/SyncDatabaseSchema/types.ts
> feat: support raw SQL in sync schema

- frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
- frontend/src/components/QuickActionPanel.vue
> fix(frontend): don't trap-focus is not needed

- frontend/src/utils/v1/sql.ts
- frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/TableCell.vue
> chore: update null value display style in sql editor

- frontend/src/composables/useExecuteSQL.ts
- frontend/src/utils/v1/database.ts
> chore: only show create issue hint for developers in sql editor

- frontend/src/components/InstanceForm/DataSourceSection/DataSourceTabs.vue
- frontend/src/components/InstanceForm/InstanceForm.vue
- frontend/src/components/InstanceForm/context.ts
some minor supplements to #7379
> chore(frontend): extract readonlyDataSourceList

- backend/runner/taskcheck/statement_type_report_executor.go
> feat: pg extract changed resources

- frontend/src/components/User/Settings/UserTable.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
> chore: update change role tooltip for archived users

- backend/runner/taskcheck/statement_type_report_executor.go
> feat: tidb extract changed resources

- backend/tests/change_history_test.go
> test: add integration tests for filter changed resources

- backend/api/v1/project_service.go
- frontend/src/components/ProjectWebhookForm.vue
- frontend/src/views/ProjectWebhookDetail.vue
Previously, we only allow to test webhook after it's created.
> chore: allow to test webhook on creation

- backend/api/v1/idp_service.go
- frontend/src/components/IdentityProviderCreateForm.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
- frontend/src/utils/idp.ts
> feat: add phone field into frontend

- backend/api/v1/rollout_service.go
- backend/store/task_run.go
- improve err msg
- allow running stages out of order.
- forbid running task runs if there are DONE taskruns.
> fix: refine BatchRunTasks

- backend/server/openapi_sql.go
- frontend/src/views/SyncDatabaseSchema/DatabaseSchemaSelector.vue
> feat: enable Sync Schema for TiDB

- backend/plugin/db/mongodb/mongodb.go
- backend/plugin/db/mongodb/mongodb_test.go
> chore: flatten _id for mongo

- frontend/src/components/QuickActionPanel.vue
> chore: remove `whitespace-nowrap` for quick action button

- backend/api/v1/instance_service.go
- backend/runner/slowquerysync/syncer.go
> chore: ignore no extension pg when sync slow queries

- frontend/src/components/DatabaseListSidePanel.vue
- frontend/src/components/ProjectListSidePanel.vue
- frontend/src/views/DatabaseDashboard.vue
* filter those unaccessible databases and database groups.
> fix: databases list display in sidebar and dashboard

- backend/server/webhook.go
> feat: enable SDL GitOps CI SQL review

- frontend/src/components/InstanceForm/InstanceForm.vue
- frontend/src/views/InstanceDetail.vue
> feat(frontend): new tab view for instance detail

- frontend/src/components/ColumnTable.vue
- frontend/src/components/TableDetailDrawer.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
Update table view, prepare to show the data classification
Before:
After:
> chore: update table view

- frontend/src/components/IdentityProviderCreateForm.vue
- Closes https://linear.app/bytebase/issue/BYT-3128/support-ldap-in-sso
- Closes https://github.com/bytebase/bytebase/issues/22
> chore(sso): remove `isDev` for LDAP

- backend/api/v1/sql_service.go
- backend/common/convert.go
- backend/common/convert_test.go
- frontend/src/components/Issue/panel/RequestExportPanel/index.vue
- frontend/src/plugins/cel/types/factor.ts
- frontend/src/utils/issue/cel.ts
- frontend/src/views/ExportCenter/ExportDataButton.vue
* Remove `removeExportBinding`;
* Select the export format in exporting not requesting.
> feat: remove export format field

- frontend/src/components/Issue/panel/RequestExportPanel/ExportResourceForm/DatabaseResourceSelector.vue
- frontend/src/components/Issue/panel/RequestExportPanel/ExportResourceForm/index.vue
- frontend/src/components/Issue/panel/RequestQueryPanel/DatabaseResourceForm/DatabaseResourceSelector.vue
- frontend/src/components/Issue/panel/RequestQueryPanel/DatabaseResourceForm/index.vue
- frontend/src/components/ProjectMember/AddProjectMember/AddProjectMemberForm.vue
- frontend/src/components/ProjectMember/AddProjectMember/AddProjectMembersPanel.vue
- frontend/src/components/v2/Select/DatabaseSelect.vue
> feat: add database resources selector in adding project member panel

- backend/migrator/migration/prod/2.5/0000##add_pipeline_project_id.sql
> fix: delete task and stage in pipelines

- backend/runner/approval/runner.go
This reverts commit 42e316ba9d9edee2e11633e1adc5dcc9916f17fc.
It is user UID.
> chore: revert "fix: user email (#7468)"

- backend/api/v1/schema_design_service.go
- backend/api/v1/testdata/design.yaml
> chore: fix order for schema design

- frontend/src/components/IssueV1/logic/action/review.ts
> chore(frontend): allowing only proper candidates to click the "Approve" and "Send Back" button in new issue UI

- frontend/src/components/IssueV1/components/Panel/IssueReviewActionPanel.vue
- frontend/src/components/IssueV1/components/Panel/IssueStatusActionPanel.vue
- frontend/src/components/IssueV1/components/Panel/TaskRolloutActionPanel.vue
- frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckBar.vue
> chore(frontend): update layout and style for new issue UI action panels

- backend/api/v1/sql_service.go
- backend/plugin/db/util/driverutil.go
- backend/tests/sql_export_test.go
- test: failed to execute the statement exported because data too long for column 'gender(bit)'
- fix: failed to execute the statement exported because data too long for column 'gender(bit)'
> fix: sql export for bit type

- frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue
- frontend/src/components/IssueV1/components/Panel/IssueStatusActionPanel.vue
- frontend/src/components/IssueV1/logic/action/issue.ts
Resolve/Cancel/Reopen issue
Following #7515
> feat(frontend): issue status action for new issue UI

- README.md
- docs/dev-guide.md
For https://github.com/bytebase/bytebase/pull/7442
> docs: update dev guide on how to locate frontend code

- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
- frontend/src/views/AnomalyCenterDashboard.vue
Plus minor wording and style change
> chore: only keep single attention box for anomaly center

- frontend/src/components/Issue/IssueSidebar.vue
> fix: BYT-3741

- frontend/src/components/GeneralSetting/SignInFrequencySetting.vue
- frontend/src/types/index.ts
- frontend/src/types/setting.ts
- frontend/src/views/BannerUpgradeSubscription.vue
> fix: check if sign-in frequency feature is used

- frontend/src/components/AlterSchemaPrepForm/ProjectStandardView.vue
- frontend/src/components/DatabaseDetail/Settings/DatabaseSettingsPanel.vue
- frontend/src/components/DatabaseSelect.vue
- frontend/src/components/EnvironmentSelect.vue
- frontend/src/components/SchemaDesigner/BaselineSchemaSelector.vue
- frontend/src/components/TransferOutDatabaseForm/common.ts
- frontend/src/components/v2/Model/DatabaseV1Table.vue
- frontend/src/components/v2/Model/EnvironmentV1Name.vue
- frontend/src/store/modules/v1/database.ts
- frontend/src/views/DatabaseDashboard.vue
- frontend/src/views/DatabaseDetail.vue
- frontend/src/views/SyncDatabaseSchema/DatabaseSchemaSelector.vue
- frontend/src/views/SyncDatabaseSchema/SelectTargetDatabasesView.vue
Close BYT-3744
Close BYT-3745
Close BYT-3731
Close BYT-3728:
> fix: database effected environment

- frontend/src/views/sql-editor/AsidePanel/TreeNode/Prefix.vue
> fix: BYT-3750

- backend/plugin/db/pg/sync.go
- backend/plugin/parser/sql/differ/pg/differ.go
- backend/plugin/parser/sql/differ/pg/test-data/test_differ_data.yaml
> fix: ignore Postgres system schemas for differ

- frontend/src/components/SchemaTemplate/FieldTemplateForm.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
- frontend/src/views/SchemaTemplate/ColumnTypes.vue
Close BYT-3740
* fixed some UX/UI issue in column types restriction;
* added column types restriction checkes when create column template;
> fix: column restriction in schema template

- frontend/src/components/IssueV1/components/StageSection/Actions/EarliestAllowedTime.vue
> chore(frontend): find spec from planPatch

- frontend/src/store/modules/v1/activity.ts
> chore(frontend): activity list pagesize

- frontend/src/store/modules/tab.ts
- frontend/src/views/sql-editor/Sheet/context.ts
> fix(sql-editor): switch to databases tab only when needed

- backend/runner/taskcheck/statement_type_report_executor.go
- backend/runner/taskcheck/statement_type_report_executor_test.go
> feat: support COMMENT statement for Postgres changed resources

- backend/api/v1/instance_service.go
- backend/component/state/state.go
- backend/runner/slowquerysync/syncer.go
- backend/server/server.go
> chore: allow no enabled database for Postgres slow queries

- frontend/src/bbkit/BBBadge.vue
- frontend/src/components/CustomApproval/Settings/components/common/RiskFilter/LevelFilter.vue
- frontend/src/components/SQLReview/components/SQLRuleLevelBadge.vue
- frontend/src/views/SettingWorkspaceSQLReviewDetail.vue
> fix: rename style props to badge-style

- frontend/src/components/ProjectMember/AddProjectMember/AddProjectMemberForm.vue
- frontend/src/components/ProjectMember/AddProjectMember/AddProjectMembersPanel.vue
- frontend/src/components/ProjectMember/ProjectMemberPanel.vue
- frontend/src/components/ProjectMember/ProjectMemberTable/ProjectMemberRolePanel.vue
- frontend/src/components/ProjectMember/ProjectRoleTable/EditProjectRolePanel.vue
- frontend/src/components/ProjectMember/ProjectRoleTable/ProjectRoleTable.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
* update description of action buttons: e.g. `add member` -> `grant access`;
* remove role name field in grant access panel;
* add condition name to project member role table;
* fix deleting condition;
> fix: project members related issues

- frontend/src/components/v2/Select/DatabaseSelect.vue
* add instance engine icon and name to database v2 selector;
> chore: update database v2 selector

- backend/runner/approval/runner.go
> fix: approval runner

- frontend/src/bbkit/BBAvatar.vue
- frontend/src/components/ProjectMember/AddProjectMember/AddProjectMemberForm.vue
- frontend/src/components/ProjectMember/ProjectMemberPanel.vue
- frontend/src/components/ProjectMember/ProjectMemberTable/ProjectMemberRolePanel.vue
- frontend/src/components/ProjectMember/ProjectMemberTable/ProjectMemberTable.vue
- frontend/src/components/ProjectMember/ProjectRoleTable/EditProjectRolePanel.vue
- frontend/src/components/ProjectMember/ProjectRoleTable/ProjectRoleTable.vue
Close BYT-3766, BYT-3768
* change the default expiration to `Never`;
* fix the font size in user avatar;
* update disable to remove member role checks: disable remove project owner when there is only one owner with no expiration time;
* update data table columns;
> fix: update remove member role checks

- frontend/src/components/DatabaseChangeHistoryPanel.vue
> fix: remove duplicated affected table

- backend/api/v1/database_service.go
- frontend/src/components/DatabaseChangeHistoryPanel.vue
Fetching all most change histories in database detail page.
> chore: add page size when fetching database's change histories

- frontend/src/bbkit/BBSelect.vue
- frontend/src/components/DatabaseChangeHistoryPanel.vue
* order affected tables by name;
* fix BBSelect selected checks;
> chore: update affected table selector

- frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckBar.vue
- frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckDetail.vue
- frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckPanel.vue
- frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckResultDefinitionModal.vue
- frontend/src/components/IssueV1/components/StatementSection/useSQLAdviceMarkers.ts
> feat(frontend): support SQL review checks in new issue CI/CD UI

- frontend/src/components/RepositoryForm.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
> chore: expose webhook link for Azure DevOps in debug mode

- frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/TableCell.vue
> chore: improve mongodb result

- frontend/src/components/SlowQuery/Panel/LogFilter.vue
- frontend/src/components/v2/Select/DatabaseSelect.vue
> chore(frontend): don't render prefix and suffix for "All databases"

- frontend/src/bbkit/BBButtonConfirm.vue
- frontend/src/components/ExpirationSelector.vue
- frontend/src/components/ProjectMember/AddProjectMember/AddProjectMemberForm.vue
- frontend/src/components/ProjectMember/AddProjectMember/AddProjectMembersPanel.vue
- frontend/src/components/ProjectMember/ProjectMemberTable/ProjectMemberRolePanel.vue
- frontend/src/components/ProjectMember/ProjectRoleTable/EditProjectRolePanel.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
Close BYT-3774, BYT-3772
* update i18n of project member role panel;
* use translated props to BBButtonConfirm;
> chore: update i18n of project member role panel

- backend/api/v1/auth_service.go
- backend/api/v1/environment_service.go
- backend/api/v1/instance_service.go
- backend/enterprise/api/license.go
- backend/enterprise/service/license.go
- backend/server/issue.go
- frontend/src/store/modules/v1/subscription.ts
> chore: use free plan quota for trial

- frontend/src/components/DatabaseListSidePanel.vue
> chore: add engine icon in database list

- frontend/src/components/DatabaseListSidePanel.vue
> chore: reduce database list indentation

- frontend/src/components/FeatureGuard/FeatureAttention.vue
- frontend/src/components/FeatureGuard/FeatureModal.vue
- frontend/src/views/InstanceDashboard.vue
> fix: quota guard wording

- frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
> chore(sql-editor): update local state correctly

- backend/api/v1/sql_service.go
Move exporter workspace IAM policy checks out of `checkQueryRights`.
> chore: update allow export checks

- frontend/src/components/SchemaDesigner/DatabaseTree.vue
> chore: support duplicate table

- frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckDetail.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
> feat(frontend): support displaying sql summary report check result

- frontend/src/store/modules/issue.ts
- frontend/src/types/issue.ts
- frontend/src/utils/issue/index.ts
> chore(frontend): support ci/cd new database.general issue type in legacy issue API

- frontend/src/components/v2/Select/UserSelect.vue
> chore(frontend): fix user select display

- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
- frontend/src/views/sql-editor/EditorCommon/ConnectionHolder.vue
> chore: update connection intro

- frontend/src/components/ProjectMember/ProjectMemberTable/ProjectMemberTable.vue
- frontend/src/components/ProjectMember/ProjectRoleTable/ProjectRoleTable.vue
- frontend/src/components/ProjectMember/ProjectRoleTable/utils.ts
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
> chore: add delete line through for expired time

- frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
- frontend/src/components/CreateDatabasePrepForm/CreateDatabasePrepForm.vue
- frontend/src/components/Project/ProjectCreatePanel.vue
- frontend/src/components/v2/Container/Drawer.vue
Close BYT-3752
But I'm not sure why the `:close-on-esc="true"` props on `NDrawer` didn't work..
> chore: support close drawer on esc

- frontend/src/views/sql-editor/AsidePanel/AsidePanel.vue
- frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue
- frontend/src/views/sql-editor/AsidePanel/QueryHistoryContainer.vue
- frontend/src/views/sql-editor/AsidePanel/SchemaPanel/ColumnList.vue
- frontend/src/views/sql-editor/AsidePanel/SchemaPanel/DatabaseSchema.vue
- frontend/src/views/sql-editor/AsidePanel/SchemaPanel/SchemaDiagramButton.vue
- frontend/src/views/sql-editor/AsidePanel/SchemaPanel/SchemaPanel.vue
- frontend/src/views/sql-editor/AsidePanel/SchemaPanel/TableList.vue
- frontend/src/views/sql-editor/AsidePanel/SchemaPanel/TableSchema.vue
- frontend/src/views/sql-editor/AsidePanel/SheetList/SheetList.vue
hopefully to bring a performance boost.
tested with 2000 tables and 1000 columns.
> feat(sql-editor): implement table list and column list with virtual list

- frontend/src/components/IssueV1/logic/plan-check.ts
- frontend/src/components/IssueV1/logic/plan.ts
> chore(frontend): find plan check run list by target from spec (new CICD UI)

- frontend/src/views/sql-editor/SQLEditorPage.vue
> chore: reduce SQL Editor tab top padding by 1

- frontend/src/views/sql-editor/EditorCommon/ConnectionPathBar.vue
- frontend/src/views/sql-editor/EditorCommon/EditorAction.vue
* Use consistent button icon size
* Reduce readonly connection hint and prod env alert size
Before
After
> chore: improve SQL Editor toolbar UI

- frontend/src/views/DashboardSidebar.vue
> chore: co-locate xxx center in the sidebar

- frontend/src/components/BookmarkListSidePanel.vue
- frontend/src/components/ProjectListSidePanel.vue
> chore: reduce bookmark/project sidebar spacing

- backend/api/v1/issue_service.go
- backend/server/server.go
> chore: migrate sample issue to CI/CD

- README.md
- add missing period
- correct misspelling of `tooling`
> docs: fix readme.md spelling and punctuation

- frontend/src/views/sql-editor/Sheet/context.ts
> fix(sql-editor): don't overwrite when switching sheets

- frontend/src/components/SQLReview/components/SQLReviewCategorySummaryFilter.vue
- frontend/src/components/SQLReview/components/SQLRuleFilter.vue
> chore: fix sql review layout in small screen

- frontend/src/components/DatabaseOverviewPanel.vue
- frontend/src/views/DatabaseDetail.vue
- frontend/src/views/sql-editor/AsidePanel/SchemaPanel/TableSchema.vue
> fix(sql-editor): table schema url

- frontend/src/views/ExportCenter/ExportRecordTable.vue
> fix: handle the unknown issue id

- frontend/src/store/modules/v1/sql.ts
> chore(frontend): don't go to 403 page when exporting permission denied.

- frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue
> chore: remove the connected icon

- frontend/src/components/IssueV1/IssueDetailPage.vue
- frontend/src/components/IssueV1/components/StageSection/StageCard.vue
- frontend/src/components/IssueV1/components/StageSection/StageSection.vue
> chore(frontend): bring stage bar back in CICD UI

- frontend/src/components/IssueV1/IssueDetailPage.vue
- frontend/src/components/IssueV1/components/HeaderSection/Assignee/Assignee.vue
- frontend/src/components/IssueV1/components/HeaderSection/Description.vue
- frontend/src/components/IssueV1/components/HeaderSection/HeaderSection.vue
- frontend/src/components/IssueV1/components/HeaderSection/ReviewSection/ReviewSection.vue
- frontend/src/components/IssueV1/components/StageSection/StageSection.vue
- frontend/src/components/v2/Select/UserSelect.vue
* Horizontal alignment between issue general info and review flow control
* Expand assignee and review flow control width to avoid clipping
* Use normal text for user selection email otherwise the email is not aligned with the name
> chore: tweak issue UI

- frontend/src/components/Issue/IssueSidebar.vue
- frontend/src/components/IssueV1/components/StageSection/Actions/EarliestAllowedTime.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
> chore: improve wording for rollout time

- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
> chore: change wording for schema sync

- frontend/src/views/sql-editor/AsidePanel/SheetList/SheetItem.vue
- frontend/src/views/sql-editor/AsidePanel/SheetList/TabItem.vue
> chore(sql-editor): text should not wrap to new line if too long

- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
- frontend/src/plugins/ai/components/MockInputPlaceholder.vue
- frontend/src/plugins/ai/components/state.ts
- frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
> chore(sql-editor): add a button to allow bring the chatsql back

- frontend/src/composables/useEmitteryEventListener.ts
- frontend/src/views/sql-editor/AsidePanel/AsidePanel.vue
- frontend/src/views/sql-editor/AsidePanel/SheetList/SheetList.vue
- frontend/src/views/sql-editor/Sheet/context.ts
- frontend/src/views/sql-editor/SheetPanel/SheetPanel.vue
- frontend/src/views/sql-editor/TabList/TabList.vue
> feat(sql-editor): add create and search control in the sheet drawer

- frontend/src/views/sql-editor/AsidePanel/TreeNode/InstancePrefix.vue
> chore(sql-editor): update database node layout and text

- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
- frontend/src/views/sql-editor/SheetPanel/SheetTable/SheetConnection.vue
- frontend/src/views/sql-editor/SheetPanel/SheetTable/SheetTable.vue
> feat(sql-editor): Add connection column to the Sheet Drawer

- frontend/src/components/IssueV1/components/Panel/CommonDrawer.vue
- frontend/src/components/IssueV1/components/Panel/IssueReviewActionPanel.vue
- frontend/src/components/IssueV1/components/Panel/IssueStatusActionPanel.vue
- frontend/src/components/IssueV1/components/Panel/TaskRolloutActionPanel.vue
> chore(frontend): reset input state when drawer reopens in CI/CD UI

- frontend/src/components/ProjectMember/ProjectMemberTable/ProjectMemberRolePanel.vue
> chore(frontend): disallow to click the trash button for the last owner role

- frontend/src/components/IssueV1/components/ActivitySection/Activity/ActionIcon.vue
- frontend/src/components/IssueV1/components/ActivitySection/Activity/ActionSentence.vue
- frontend/src/components/IssueV1/components/Panel/TaskRolloutActionPanel.vue
- frontend/src/types/pipeline/task.ts
> chore(frontend): support task skip and run/skip/cancel task reason in CI/CD UI

- frontend/src/components/User/Settings/UserTable.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
> chore(frontend): Double confirmation when workspace OWNER is about to revoke him/herself OWNER role

- frontend/src/store/modules/auth.ts
- frontend/src/store/modules/user.ts
> chore(frontend): mute error notification when not needed

- frontend/src/views/sql-editor/TabList/TabItem/Label.vue
> chore(sql-editor): show tooltip when text truncated

- backend/api/v1/sql_service.go
- backend/plugin/db/driver.go
- backend/plugin/db/util/mask_sensitive_data.go
> feat: mysql sensitive data supports view

- backend/api/v1/schema_design_service.go
- frontend/src/components/MonacoEditor/DiffEditor.vue
- frontend/src/components/SchemaDesigner/CreateSchemaDesignPanel.vue
- frontend/src/components/SchemaDesigner/EditSchemaDesignPanel.vue
- frontend/src/components/SchemaDesigner/common/util.ts
- frontend/src/components/SchemaDesigner/index.vue
- frontend/src/types/schemaEditor/atomType.ts
> feat(schema-designer): rebuild editable schema state

- frontend/src/components/SchemaDesigner/EditSchemaDesignPanel.vue
- frontend/src/components/SchemaDesigner/common/util.ts
* filter personal drafts for current user;
* handle renamed column;
> fix(schema-design): filter personal drafts for current user

- frontend/src/views/sql-editor/AsidePanel/TreeNode/Prefix.vue
> chore(sql-editor): remove instance prefix in instance view

- backend/runner/plancheck/executor.go
- backend/runner/plancheck/scheduler.go
- backend/runner/taskcheck/executor.go
- backend/runner/taskcheck/scheduler.go
* fix: recover from task panic
* Update backend/runner/taskcheck/executor.go
---------
> cherrypick: fix: recover from check panic (#7763)

- frontend/src/types/proto/store/policy.ts
- proto/gen/grpc-doc/store/README.md
- proto/generated-go/store/policy.pb.go
- proto/store/policy.proto
> feat: add masking rule policy in store proto

- frontend/src/components/IssueV1/IssueDetailPage.vue
- frontend/src/components/IssueV1/components/HeaderSection/Actions/rollout/RolloutActionButton.vue
- frontend/src/components/IssueV1/components/StageSection/StageSection.vue
- frontend/src/components/IssueV1/components/TaskListSection/TaskListSection.vue
- frontend/src/components/v2/Button/ContextMenuButton.vue
- rollout button size
- refine task list height
- lighter task list tracker shadow
- gap and height above stage section
> chore(frontend): CI/CD UI minor improvements

- frontend/src/components/IssueV1/logic/plan-check.ts
> chore(frontend): show plan checks for baseline issue in CI/CD UI

- frontend/src/components/AlterSchemaPrepForm/SchemalessDatabaseTable.vue
- frontend/src/components/v2/Model/DatabaseV1Table/DatabaseGroupTableRow.vue
- frontend/src/components/v2/Model/DatabaseV1Table/DatabaseTableRow.vue
- frontend/src/components/v2/Model/DatabaseV1Table/DatabaseV1Table.vue
- frontend/src/components/v2/Model/DatabaseV1Table/ProjectCol.vue
- frontend/src/components/v2/Model/DatabaseV1Table/index.ts
- frontend/src/components/v2/Model/index.ts
- frontend/src/views/IssueDetailV1.vue
> chore(frontend): database group in database v1 table

- backend/api/v1/rollout_service.go
- backend/api/v1/rollout_service_converter.go
- backend/legacyapi/task.go
- backend/legacyapi/task_run.go
- backend/runner/approval/runner.go
- backend/runner/rollbackrun/runner.go
- backend/runner/taskrun/schedulerv2.go
- backend/server/issue.go
- backend/server/server.go
- backend/server/webhook.go
- backend/store/task.go
coalesce NULL latestTaskRunStatus to NOT_STARTED in order to support searching tasks by latestTaskRunStatus.
> fix: update plan rollback enabled

- frontend/src/components/IssueV1/components/HeaderSection/VCSInfo.vue
- frontend/src/components/IssueV1/components/HeaderSection/useActiveTaskSheet.ts
- frontend/src/components/IssueV1/components/StatementSection/SDLView/useSDLState.ts
> feat(frontend): display vcs push info in CI/CD UI

- backend/api/v1/org_policy_service.go
- backend/common/convert.go
- backend/legacyapi/policy.go
BTW, supporting list all project polices.
> feat(advanced-masking-policy): crud for masking exception policy

- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
* Add missing updater translation back
* Improve branch "apply-to-database" translation
> chore: i18n update

- frontend/src/components/CreateDataSourceExample.vue
> fix: show how to create user for PostgreSQL

- frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
> chore(sql-editor): only carry the statement from current single query when requesting export

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/components/MonacoEditor/DiffEditor.vue
> chore(frontend): downgrade monaco-editor to 0.34

- backend/plugin/db/util/driverutil.go
The length of the `columnTypes` always equal to `columnTypeNames`. We do not need to pass the redundant `columnTypes`.
> refactor: remove the columnTypes argument

- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
> chore: update schema migraiton type wording

- frontend/src/components/IssueV1/components/HeaderSection/ReviewSection/Timeline.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
> chore(frontend): update review approver candidates display in CI/CD UI

- frontend/src/components/DatabaseInfo.vue
- frontend/src/components/ProjectBranchesPanel.vue
- frontend/src/components/SchemaDesigner/PrepForm/SchemaDesignTable.vue
- frontend/src/layouts/ProjectLayout.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
- frontend/src/store/modules/schemaDesign.ts
- frontend/src/views/ProjectDetail.vue
- frontend/src/views/SyncDatabaseSchema/SchemaDesignSelector.vue
> chore: update schema design table fields

- frontend/src/components/BranchTablePanel.vue
- frontend/src/components/ProjectBranchesPanel.vue
- frontend/src/components/SchemaDesigner/CreateSchemaDesignPanel.vue
- frontend/src/components/SchemaDesigner/EditSchemaDesignPanel.vue
- frontend/src/components/SchemaDesigner/MergeBranchPanel.vue
- frontend/src/components/SchemaDesigner/PrepForm/SchemaDesignTable.vue
- frontend/src/components/SchemaDesigner/PrepForm/index.vue
- frontend/src/components/SchemaDesigner/common/util.ts
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
- frontend/src/views/SyncDatabaseSchema/SchemaDesignSelector.vue
> chore: update branch detail panel

- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
- frontend/src/store/modules/tab.ts
- frontend/src/views/sql-editor/TabList/ContextMenu.vue
- frontend/src/views/sql-editor/TabList/TabItem/Label.vue
- frontend/src/views/sql-editor/TabList/TabItem/Suffix.vue
- frontend/src/views/sql-editor/TabList/TabItem/TabItem.vue
- frontend/src/views/sql-editor/TabList/TabList.vue
- frontend/src/views/sql-editor/TabList/context.ts
> feat(sql-editor): add batch close and rename context menu to tab list

- frontend/src/components/ColumnTable.vue
> fix: column order

- frontend/src/components/IssueV1/IssueDetailPage.vue
> chore: improve issue ui separator

- frontend/src/views/SchemaTemplate/FieldTemplates.vue
- frontend/src/views/SettingWorkspaceSchemaTemplate.vue
> chore(frontend): show engine filter in column template panel only when needed

- backend/runner/taskrun/executor.go
should loop over all runs and filter by instance_id, databaseName
> fix: changed resources migration info

- backend/api/v1/sql_service.go
Break in #7810 https://github.com/bytebase/bytebase/pull/7810/files#diff-808a8c0c206597e9ef3129681613850ab1003ef38e9db978f0da114ca21d54caR1477-R1478
> fix(sensitive-data): fix the sensitive data for PostgreSQL

- frontend/src/components/BranchTablePanel.vue
- frontend/src/components/SchemaDesigner/BranchTable.vue
* rename `SchemaDesignTable` to `BranchTable`
> chore: rename schema design to branch

- frontend/src/components/InstanceForm/specs.ts
> chore(frontend): bring database input back for pg instance

- frontend/src/components/AdvancedSearch.vue
> chore: don’t localize search filter and style tweak

- frontend/src/store/modules/v1/sheet.ts
- frontend/src/views/sql-editor/SheetPanel/SheetPanel.vue
- frontend/src/views/sql-editor/SheetPanel/SheetTable/SheetTable.vue
Every single user is assumed to have no lots of sheets. So we implemented this in a quick and dirty way by filtering issues' titles at frontend.
Close BYT-3811
> feat(sql-editor): add search box to sheet panel

- frontend/src/components/BytebaseLogo.vue
> chore: update custom branding max height

- backend/plugin/db/util/driverutil_test.go
- backend/plugin/db/util/mask_sensitive_data.go
- backend/plugin/db/util/mask_sensitive_data_mysql.go
- backend/plugin/db/util/mask_sensitive_data_psql.go
> feat(advanced-masking-policy): retire senstive in MySQL calculator

- backend/enterprise/api/plan.yaml
- frontend/src/components/PricingTable/PricingTable.vue
- frontend/src/components/PricingTable/types.ts
- frontend/src/locales/subscription/en-US.json
- frontend/src/locales/subscription/es-ES.json
- frontend/src/locales/subscription/zh-CN.json
* Highlight enterprise plan
* Fix pricing
* Clarify wording
> chore: adjust pricing table

- frontend/src/bbkit/BBTabFilter.vue
- frontend/src/components/v2/TabFilter/TabFilter.vue
> chore: make tab more condensed

- frontend/src/layouts/BodyLayout.vue
- frontend/src/views/DashboardSidebar.vue
- frontend/src/views/SettingSidebar.vue
> chore: condense sidebar

- backend/api/v1/database_service.go
- backend/runner/schemasync/syncer.go
- backend/store/database.go
- syncer respects sync interval
- update last_sync_time when syncing
> feat: schemasyncer sync interval

- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
FYI @zll600  Please take care of the JSON format.
> fix: localization json format

- frontend/src/locales/subscription/en-US.json
- frontend/src/locales/subscription/es-ES.json
- frontend/src/locales/subscription/zh-CN.json
- frontend/src/views/SettingWorkspaceSubscription.vue
> chore: update instance count wording for FREE plan

- backend/plugin/db/util/driverutil_test.go
- backend/plugin/db/util/mask_sensitive_data.go
- backend/plugin/db/util/mask_sensitive_data_plsql.go
> feat(advanced-masking-policy): retire sensitive in plsql calculator

- backend/plugin/db/util/driverutil_test.go
- backend/plugin/db/util/mask_sensitive_data.go
- backend/plugin/db/util/mask_sensitive_data_snowsql.go
> feat(advanced-masking-policy): retire sensitive in snowsql calculator

- backend/enterprise/api/plan.yaml
- frontend/src/components/GeneralSetting/AnnouncementSetting.vue
- frontend/src/components/v2/Select/AnnouncementLevelSelect.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/subscription/en-US.json
- frontend/src/locales/subscription/es-ES.json
- frontend/src/locales/subscription/zh-CN.json
- frontend/src/locales/zh-CN.json
- frontend/src/utils/role.ts
- frontend/src/views/BannerAnnouncement.vue
- frontend/src/views/BannerUpgradeSubscription.vue
- allow workspace owner or DBA to set `announcement` feature
- only workspace owner or DBA can set `Announcement Level`
- fix styles of Title Field of `AnnouncementSetting`
- fix styles of `AnnouncementBanner`
- fix typo in `BannerUpgradeSubscribtion`
- add `announcement-banner` to PLAN
related pr: https://github.com/bytebase/bytebase/pull/7526
> fix: announcement banner

- backend/migrator/migration/prod/2.7/0005##delete_general_issue_related.sql
> fix: delete data refer issue table

- frontend/src/components/IssueV1/components/StageSection/Actions/EarliestAllowedTime.vue
> chore(frontend): respect feature guard for task rollout schedule time feature

- frontend/src/components/IssueV1/components/ActivitySection/Activity/ActionIcon.vue
- frontend/src/components/IssueV1/components/ActivitySection/Activity/ActionSentence.vue
- frontend/src/types/pipeline/task.ts
> chore(frontend): support SKIPPED task run status

- frontend/src/views/sql-editor/SecondarySidebar/HistoryTabPane/HistoryTabPane.vue
> chore: change the query history clipboard icon

- frontend/src/components/ProfileDropdown.vue
> chore: change “setting” to “profile” under profile dropdown

- frontend/src/views/BannerAnnouncement.vue
@tianzhou 
reduce the height of the BannerAnnouncement
> fix: update styles of elements

- frontend/src/components/BytebaseLogo.vue
- frontend/src/components/ProfileBrandingLogo.vue
- frontend/src/components/ProfileDropdown.vue
- frontend/src/views/DashboardHeader.vue
To save precious vertical space
Before
After
> chore: condense dashboard header

- backend/legacyapi/activity.go
- backend/migrator/migration/prod/2.7/0009##remove_task_status_update_from_project_webhook.sql
- backend/migrator/migrator_test.go
- frontend/src/types/v1/projectWebhook.ts
> chore: retire ActivityPipelineTaskStatusUpdate in project webhook activities

- backend/plugin/db/oracle/dump.go
> feat: impl dump indexes for Oracle

- frontend/src/components/QuickActionPanel.vue
- frontend/src/layouts/BodyLayout.vue
- frontend/src/router/index.ts
- frontend/src/types/quickAction.ts
Before
After
Also remove some unused quick action
> chore: condense quickaction button to save vertical space

- backend/legacyapi/plan.go
- frontend/src/components/InstanceForm/InstanceForm.vue
- frontend/src/components/InstanceForm/ScanIntervalInput.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
- frontend/src/types/plan.ts
> feat(frontend): custom instance scan interval configuration

- frontend/src/components/DatabaseListSidePanel.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
- frontend/src/utils/collections.ts
Note that if the user no longer has privilege to visit a database in their stored recent visit list, the database will not show in the list but still count 1 out of 10 recent items in storage.
FYI @tianzhou 
Close BYT-3911
> feat: sidebar recent database list

- frontend/src/components/InstanceForm/ScanIntervalInput.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
> chore(frontend): instance sync interval's default description changed to "never"

- frontend/src/components/Role/Setting/RoleSetting.vue
- frontend/src/locales/en-US.json
- frontend/src/locales/es-ES.json
- frontend/src/locales/zh-CN.json
> chore: annotate custom role description

- frontend/src/views/sql-editor/EditorCommon/EditorAction.vue
- frontend/src/views/sql-editor/SecondarySidebar/SecondarySidebar.vue
- Show shortcut texts only when the space is large enough
- Jump to Info tab automatically when possible.
> chore(sql-editor): minor updates

- backend/api/v1/rollout_service.go
- backend/migrator/migration/dev/LATEST.sql
- backend/migrator/migration/prod/2.8/0000##task_run_attempt.sql
- backend/migrator/migration/prod/LATEST.sql
- backend/migrator/migrator_test.go
- backend/store/task.go
- backend/store/task_run.go
Add attempt to task_run table for optimistic locking.
> feat: task_run attempt for optimistic locking
