bytebase/bytebase

frontend/src/components/ProjectMember/ProjectMemberPanel.vue
frontend/src/components/ProjectMember/ProjectMemberTable/ProjectMemberTable.vue
frontend/src/components/ProjectMember/ProjectRoleTable/ProjectRoleTable.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

* add clean up expired roles button;
* don't show exporter role with statement condition;

chore: add clean up expired roles button

---

frontend/src/components/Issue/panel/RequestExportPanel/ExportResourceForm/index.vue
frontend/src/components/Issue/panel/RequestExportPanel/index.vue
frontend/src/views/ExportCenter/index.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue

chore: add statement only props to request export form for SQL Editor

---

backend/api/v1/auth_service.go
backend/store/stats.go

Right now, there is no way to delete principal entirely. Let's count by active users.

chore: count by active users

---

frontend/src/components/IssueV1/components/HeaderSection/Actions/review/ReviewActionButton.vue
frontend/src/components/IssueV1/components/HeaderSection/Actions/rollout/RolloutActionButton.vue
frontend/src/components/IssueV1/components/HeaderSection/HeaderSection.vue
frontend/src/components/IssueV1/components/Panel/IssueReviewActionPanel.vue
frontend/src/components/IssueV1/components/Panel/IssueStatusActionPanel.vue
frontend/src/components/IssueV1/components/Panel/TaskRolloutActionPanel.vue
frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckBadgeBar.vue
frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckBar.vue
frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckDetail.vue
frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckPanel.vue
frontend/src/components/IssueV1/components/StageSection/StageCard.vue
frontend/src/components/IssueV1/components/StageSection/StageSection.vue
frontend/src/components/IssueV1/components/common/ErrorList.vue
frontend/src/components/IssueV1/logic/plan-check.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/sqlReview.ts

- Show plan check error/warning indicator for stage. (Close BYT-3892)
- Allow force perform review/rollout action explicitly when some plan check didn't pass. (Close BYT-3912)
- Adjust horizontal split lines.

feat(frontend): ci/cd UI improvements

---

frontend/src/components/ChangeHistory/ChangeHistoryTable.vue
frontend/src/components/DatabaseChangeHistoryPanel.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/utils/v1/changeHistory.ts

chore: update change history table

---

frontend/src/components/Issue/IssueHighlightPanel.vue
frontend/src/components/Issue/form/GrantRequestExporterForm.vue
frontend/src/components/Issue/panel/RequestExportPanel/index.vue
frontend/src/components/ProjectMember/AddProjectMember/AddProjectMemberForm.vue
frontend/src/components/ProjectMember/AddProjectMember/AddProjectMembersPanel.vue
frontend/src/components/ProjectMember/ProjectRoleTable/EditProjectRolePanel.vue

Close BYT-3867
* allow to select multi databases in grant exporter access;
* remove statement field in request exporter form;
* only show export center button for those requests with statement condition in issue detail page.

feat: update grant access and request export fields

---

frontend/src/components/CustomApproval/Settings/components/common/utils.ts

- add `affected_rows` to DDL
- remove `level` and `source` from DDL and DML
Completing BYT-3813

fix: risk factors

---

backend/runner/plancheck/statement_report_executor.go
backend/runner/plancheck/statement_report_executor_affected_rows.go

feat: get affected rows for ddl

---

frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/views/sql-editor/EditorCommon/ConnectionPathBar.vue

chore: show different read-only connection tip depending on the role

---

frontend/src/views/sql-editor/AsidePanel/AsidePanel.vue
frontend/src/views/sql-editor/SQLEditorPage.vue
frontend/src/views/sql-editor/TabList/TabList.vue

feat(sql-editor): re-layout SQL Editor

---

frontend/src/components/InstanceForm/InstanceForm.vue
frontend/src/views/SettingWorkspaceSubscription.vue

chore: hide the entrey if users don't have permission

---

frontend/src/store/modules/task.ts

Seems maybe the backend missed some composed fields. But it works now.

chore(frontend): robustness++

---

frontend/src/views/BannerAnnouncement.vue

fix(announcement): only display text when link does not exist

---

backend/plugin/parser/sql/differ/plsql/differ.go
backend/server/openapi_sql.go
backend/server/server.go
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/views/SyncDatabaseSchema/DatabaseSchemaSelector.vue

close BYT-3667
IMPORTANT: Oracle database MUST have ONE schema, or use "Manage based on schema" sync mode.

feat: enable Oracle sync schema

---

backend/plugin/db/util/mask_sensitive_data.go
backend/plugin/db/util/mask_sensitive_data_tidb.go

chore: rename extractMySQLSensitiveField to extractTiDBSensitiveField

---

frontend/src/components/ProjectMember/AddProjectMember/AddProjectMemberForm.vue

chore: update condition title generator when granting access

---

frontend/src/components/SensitiveData/SensitiveColumnView.vue

fix: forbid edit masking rules if the instance is missing required license

---

frontend/src/components/IssueV1/components/StageSection/Actions/RollbackSection/common.ts
frontend/src/components/IssueV1/logic/legacy-issue-compatibility.ts

FYI @d-bytebase @RainbowDashy 
note that the merge target is release/2.7.0

feat(cicd): use legacy API to patch tasks' rollbackEnabled for legacy issues

---

frontend/src/components/CustomApproval/Settings/components/CustomApproval/common/StepsTable.vue
frontend/src/components/User/Settings/MemberAddOrInvite.vue
frontend/src/components/User/Settings/UserTable.vue
frontend/src/components/v2/Select/ProjectMemberRoleSelect.vue
frontend/src/components/v2/Select/WorkspaceRoleSelect.vue
frontend/src/components/v2/Select/index.ts

* add filterable to v2 selects
* rename `RoleSelect` to `WorkspaceRoleSelect`

chore: add filterable to v2 selects

---

backend/api/v1/schema_design_merge.go
backend/api/v1/schema_design_merge_test.go
backend/api/v1/schema_design_merger.go
backend/api/v1/schema_design_service.go

https://github.com/bytebase/bytebase/assets/87714218/69ecd415-f105-422a-b772-e70337901ea9
https://share.cleanshot.com/BGQdBqlb

feat(branching): auto merging skeleton

---

frontend/src/components/SchemaDesigner/DatabaseTree.vue
frontend/src/components/SchemaDesigner/Modals/TableNameModal.vue

chore(branching): add rename table function

---

frontend/src/components/AlterSchemaPrepForm/DatabaseGroupPrevEditorModal.vue

`validateOnly` is no longer supported
FYI @RainbowDashy @boojack

chore(frontend): skip validateOnly for db group issue preview

---

backend/api/v1/rollout_service.go
backend/api/v1/rollout_service_task.go
backend/common/resource_name.go
backend/utils/utils.go

feat: support deployement config as spec target

---

backend/plugin/parser/sql/differ/mysql/differ.go
backend/plugin/parser/sql/differ/mysql/table_test.go

fix(mysql-differ): handle union case in get temporary view

---

frontend/src/components/CreateDatabasePrepForm/CreateDatabasePrepForm.vue
frontend/src/components/CreateDatabasePrepForm/DatabaseLabelForm.vue
frontend/src/components/InstanceRoleSelect.vue
frontend/src/components/ProjectDatabasesPanel.vue
frontend/src/components/SensitiveData/SensitiveColumnView.vue
frontend/src/components/SlowQuery/Panel/LogFilter.vue
frontend/src/components/TransferDatabaseForm/TransferSourceSelector.vue
frontend/src/components/v2/Select/EnvironmentSelect.vue
frontend/src/components/v2/Select/InstanceSelect.vue
frontend/src/components/v2/Select/ProjectSelect.vue
frontend/src/components/v2/Select/index.ts
frontend/src/views/DatabaseDashboard.vue
frontend/src/views/ExportCenter/index.vue

* use v1 selectors in creating database form;
* add environment v1 select;

feat: use v1 selectors in creating database form

---

frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/plugins/ai/components/ActionBar.vue
frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue
frontend/src/views/sql-editor/SecondarySidebar/HistoryTabPane/HistoryTabPane.vue
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/DatabaseSchema.vue
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/SchemaPanel.vue
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/TableSchema.vue
frontend/src/views/sql-editor/SecondarySidebar/SecondaryGutterBar/SecondaryGutterBar.vue
frontend/src/views/sql-editor/SecondarySidebar/SheetTabPane/SheetList/SheetList.vue
frontend/src/views/sql-editor/SecondarySidebar/SheetTabPane/SheetTabPane.vue
frontend/src/views/sql-editor/TabList/TabList.vue

Before
After
Before
After
Before
After
1. Search field spacing and alignment
2. Schema/Table header style
3. Gutter style
4. Profile dropdown alignment

chore: various SQL Editor Style tweak

---

frontend/src/components/Issue/panel/RequestExportPanel/index.vue
frontend/src/components/Issue/panel/RequestQueryPanel/index.vue
frontend/src/components/v2/Select/DatabaseSelect.vue

chore: use v2 selectors for requesting querier/exporter roles

---

frontend/src/views/ChangeHistoryDetail.vue

fix: cannot show the affected table drawer

---

frontend/src/components/ProvideSQLEditorContext.vue
frontend/src/store/modules/connectionTree.ts
frontend/src/types/connectionTree.ts
frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue
frontend/src/views/sql-editor/AsidePanel/TreeNode/Prefix.vue
frontend/src/views/sql-editor/AsidePanel/common.ts
frontend/src/views/sql-editor/SQLEditorPage.vue
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/SchemaPanel.vue
frontend/src/views/sql-editor/SecondarySidebar/SecondaryGutterBar/SecondaryGutterBar.vue
frontend/src/views/sql-editor/context.ts

feat(sql-editor): expand schema and tables in connection tree dynamically

---

frontend/src/components/Quickstart.vue

Showing an enterprise upgrade is premature since we haven't shown any enterprise feature yet.

chore: only show booking demo after quickstart

---

frontend/src/components/GeneralSetting/SignInFrequencySetting.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

chore: fix setting updated message

---

frontend/src/components/IssueV1/components/Panel/TaskRolloutActionPanel.vue

chore(frontend): cancel PENDING task runs

---

backend/plugin/parser/sql/mysql.go
backend/plugin/parser/sql/mysql_test.go

fix: sikp empty statement for MySQL

---

frontend/src/components/IssueV1/components/StageSection/Actions/EarliestAllowedTime.vue
frontend/src/components/IssueV1/logic/task-run.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

FYI @RainbowDashy 
Close BYT-3686

chore(frontend): improve rollout time editing logic and UX

---

backend/plugin/db/util/driverutil_test.go
backend/plugin/db/util/mask_sensitive_data.go
backend/plugin/db/util/mask_sensitive_data_mysql.go
backend/plugin/parser/sql/mysql.go

feat: implement MySQL parser-based sensitive data

---

frontend/src/components/SensitiveData/GlobalMaskingRulesView.vue
frontend/src/components/SensitiveData/GrantAccessDrawer.vue
frontend/src/components/SensitiveData/SensitiveColumnDrawer.vue
frontend/src/components/SensitiveData/SensitiveColumnView.vue
frontend/src/components/SensitiveData/components/MaskingRuleConfig.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/views/SettingWorkspaceSensitiveData.vue

Related issues: https://bytebase.feishu.cn/docx/An7ndRjX6orVNpxFfrscuUefnaf

fix: ux issue for masking

---

backend/api/v1/issue_service.go
backend/common/convert.go
backend/common/resource_name.go
backend/runner/approval/runner.go
frontend/src/types/proto/store/issue.ts
frontend/src/types/proto/v1/issue_service.ts
proto/gen/grpc-doc/store/README.md
proto/gen/grpc-doc/v1/README.md
proto/generated-go/store/issue.pb.go
proto/generated-go/v1/issue_service.pb.go
proto/store/issue.proto
proto/v1/issue_service.proto

Do notice that in storage the format for `user` is `users/{userUID}` because we already had it wrong in the first place. We can migrate it but not in this PR.

feat: impl create grant request issue

---

frontend/src/components/ColumnTable.vue
frontend/src/components/SchemaDesigner/Panels/TableEditor.vue
frontend/src/components/SchemaTemplate/ClassificationLevelBadge.vue
frontend/src/components/SchemaTemplate/FieldTemplateForm.vue
frontend/src/components/SchemaTemplate/FieldTemplateTable.vue

original PR https://github.com/bytebase/bytebase/pull/8107

refactor: unify classification badge

---

frontend/src/components/Issue/panel/RequestExportPanel/index.vue
frontend/src/components/Issue/panel/RequestQueryPanel/index.vue

@boojack PTAL
@RainbowDashy FYI

refactor(frontend): migrate grant issue creation to v1 API

---

frontend/src/plugins/ai/components/ChatPanel.vue

Remove the explanation, just provide raw sql

chore: make ChatSQL response terse

---

frontend/src/components/BranchTablePanel.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

chore: add search name input to branch list

---

backend/api/v1/sql_service.go
backend/common/convert.go

feat(advanced-masking-policy): support column name as a factor of masking level rule

---

frontend/src/components/SchemaTemplate/FieldTemplateForm.vue
frontend/src/locales/en-US.json
frontend/src/plugins/ai/components/ChatPanel.vue

* Use text field to indicate empty state for data classification when disabled
* Proper casing

chore: improve field template form

---

frontend/src/components/DatabaseGroup/common/ExprEditor/components/ValueInput.vue
frontend/src/components/ExprEditor/components/ValueInput.vue

chore(frontend): clear value input when changing factor

---

frontend/src/components/SchemaDesigner/DatabaseTree.vue

chore: improve schema designer table sidebar

---

frontend/src/App.vue
frontend/src/AppRootContext.ts
frontend/src/components/Instance/InstanceArchiveRestoreButton.vue
frontend/src/components/Project/ProjectArchiveRestoreButton.vue
frontend/src/store/modules/v1/database.ts
frontend/src/store/modules/v1/instance.ts
frontend/src/store/modules/v1/project.ts

Close BYT-3924
"Soft restart" means that we change the `key` of the root component, which causes the entire component tree re-mounts. And we clear (most of) frontend in-memory store contents and reload them when needed.

chore(frontend): soft restart app when force archive/restore instance and project

---

frontend/src/components/SchemaDesigner/EditSchemaDesignPanel.vue
frontend/src/components/SchemaDesigner/Panels/TableEditor.vue
frontend/src/components/SchemaEditor/Panels/TableEditor.vue
frontend/src/views/SchemaTemplate/FieldTemplates.vue

fix: schema template issues

---

backend/api/v1/issue_service.go
backend/api/v1/sql_service.go
backend/common/convert.go
backend/common/convert_test.go

chore: validate statement in requesting querier/exporter

---

frontend/src/components/ExpirationSelector.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

chore: use “custom” instead of “customize” to make wording consistent

---

frontend/src/components/ChangeHistory/ChangeHistoryTable.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

chore: shorten change history type column

---

frontend/src/components/SchemaDesigner/DatabaseTree.vue
frontend/src/components/SchemaDesigner/Panels/TableEditor.vue
frontend/src/components/SchemaDesigner/TabsContainer.vue

chore: make schema designer more condensed

---

frontend/src/views/sql-editor/EditorCommon/ConnectionPathBar.vue

chore(frontend): layout improvement

---

frontend/src/components/SensitiveData/components/MaskingRuleConfig.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

* Make it smaller
* Use "Condition order 1" instead of "Condition 1" to indicate order explicitly

chore: adjust global masking rule condition title text field

---

frontend/src/store/modules/v1/sheet.ts

chore(sql-editor): fix content size check logic

---

frontend/src/components/IssueV1/components/HeaderSection/ReviewSection/Timeline.vue

chore(frontend): fix approval timeline style

---

frontend/src/components/SchemaTemplate/FieldTemplateForm.vue
frontend/src/components/SchemaTemplate/FieldTemplateTable.vue
frontend/src/store/modules/schemaEditor.ts
frontend/src/store/modules/schemaEditorV1.ts
frontend/src/types/schemaEditorV1/atomType.ts
frontend/src/types/schemaEditorV1/index.ts
frontend/src/types/schemaEditorV1/state.ts

* add schema editor v1 store definition(unused right now);
* remove schema template related functions from schema editor store.

chore: add schema editor v1 store definition

---

frontend/src/components/ExprEditor/components/ValueInput.vue
frontend/src/components/SensitiveData/GlobalMaskingRulesView.vue
frontend/src/components/SensitiveData/SensitiveColumnDrawer.vue
frontend/src/components/SensitiveData/components/MaskingRuleConfig.vue

chore: update global masking rules

---

backend/api/v1/debug_interceptor.go
backend/common/log/slog_utils.go

add debug log in grcp debug_interceptor middleware.
do grpc-http status code mapping by following this guide https://www.howico.de/2020/03/http-grpc-status-codes-guidelines/

feat: add log in debug_interceptor

---

frontend/src/components/ColumnTable.vue
frontend/src/components/TableDetailDrawer.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

chore: show effective masking level

---

frontend/src/components/ProjectMember/ProjectMemberTable/RoleDescription.vue
frontend/src/views/ExportCenter/ExportRecordTable.vue

PTAL @boojack 
Still cannot fully get rid of the legacy `[GET] /api/issue/{issue_id}` 💔 @d-bytebase

chore(frontend): migrate some legacy api use cases

---

frontend/src/components/DataExportButton.vue
frontend/src/store/modules/export.ts
frontend/src/store/modules/v1/activity.ts
frontend/src/store/modules/v1/sql.ts
frontend/src/views/ExportCenter/ExportDataButton.vue
frontend/src/views/SettingWorkspaceAuditLog.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue

- Get export logs via backend API
- Refactor the export button
Close BYT-3956

chore: export logs

---

frontend/src/components/ColumnTable.vue
frontend/src/components/SensitiveData/SensitiveColumnView.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

chore: update masking

---

frontend/src/locales/subscription/en-US.json
frontend/src/locales/subscription/es-ES.json
frontend/src/locales/subscription/zh-CN.json

Free is the pricing tag instead of the plan name

chore: free plan -> community plan

---

frontend/src/components/SensitiveData/GlobalMaskingRulesView.vue
frontend/src/components/SensitiveData/SensitiveColumnView.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

chore: add masking help doc link

---

frontend/src/components/SchemaDesigner/CreateSchemaDesignPanel.vue
frontend/src/components/SchemaDesigner/EditSchemaDesignPanel.vue
frontend/src/components/SchemaEditorV1/Aside/BranchTree.vue
frontend/src/components/SchemaEditorV1/Modals/EditColumnForeignKeyModal.vue
frontend/src/components/SchemaEditorV1/Modals/TableNameModal.vue
frontend/src/components/SchemaEditorV1/Panels/TableEditor.vue
frontend/src/components/SchemaEditorV1/index.vue
frontend/src/store/modules/v1/schemaEditor.ts
frontend/src/types/v1/schemaEditor/state.ts

* remove engine field, we will get engine from each resource(database/branch);
* make readonly field optional;

chore: update schema editor v1 state definition

---

frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
frontend/src/components/SchemaDiagram/SchemaDiagram.vue
frontend/src/components/SchemaEditorV1/Aside/DatabaseTree.vue
frontend/src/components/SchemaEditorV1/Aside/index.vue
frontend/src/components/SchemaEditorV1/Editor.vue
frontend/src/components/SchemaEditorV1/Panels/DatabaseEditor.vue
frontend/src/components/SchemaEditorV1/Panels/TableEditor.vue
frontend/src/components/SchemaEditorV1/TabsContainer.vue
frontend/src/components/SchemaEditorV1/utils/useMetadataForDiagram.ts
frontend/src/utils/schemaEditor/diffSchema.ts

* add `DatabaseTree` and `DatabaseEditor` into schema editor v1 components;
* use schema editor v1 in edit schema;

refactor: use schema editor v1 in edit schema

---

frontend/src/components/ProjectOverviewPanel.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/views/DashboardHeader.vue
frontend/src/views/DashboardSidebar.vue
frontend/src/views/Home.vue

1. Show the issue tab for the workspace developer as well.
2. Make search button more obvious.
1. Make search button more obvious.
2. Add issue name filter.

feat: enhance issue finding experience

---

backend/plugin/parser/sql/ast/attach_partition_stmt.go
backend/plugin/parser/sql/ast/create_table_stmt.go
backend/plugin/parser/sql/ast/node.go
backend/plugin/parser/sql/ast/parition_key_def.go
backend/plugin/parser/sql/ast/partition_def.go
backend/plugin/parser/sql/differ/pg/differ.go
backend/plugin/parser/sql/engine/pg/convert.go
backend/plugin/parser/sql/engine/pg/convert_test.go
backend/plugin/parser/sql/engine/pg/deparse.go
backend/plugin/parser/sql/engine/pg/test-data/test_create_table_data.yaml

feat(differ): support table partition def for pg and skip partitions def

---

frontend/package.json
frontend/pnpm-lock.yaml

Reverts bytebase/bytebase#8276

fix: Revert "chore(deps): update dependency vscode-textmate to v9"

---

frontend/src/locales/subscription/en-US.json
frontend/src/locales/subscription/es-ES.json

chore: shorten plan name

---

frontend/src/views/DashboardHeader.vue

chore: move setting entry to right part in header

---

frontend/src/components/QuickActionPanel.vue
frontend/src/components/SchemaDesigner/BranchTable.vue
frontend/src/router/index.ts
frontend/src/types/quickAction.ts
frontend/src/views/DashboardHeader.vue
frontend/src/views/branch/BranchDashboard.vue
frontend/src/views/branch/BranchDetail.vue

* The branch detail page will be push in a seperated PR.

feat: add branch page and entry

---

backend/plugin/db/oracle/dump.go
backend/plugin/db/oracle/oracle.go

fix: fix Oracle dump for 11g

---

frontend/public/help/en/help.member.md
frontend/public/help/zh/help.member.md
frontend/src/components/ProjectMember/ProjectMemberPanel.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

chore: improve workspace member and project member in-app guide

---

frontend/src/components/GeneralSetting/AnnouncementSetting.vue

related pr: https://github.com/bytebase/bytebase/pull/8087

fix(announcement): use ref to store originalAnnouncement

---

backend/plugin/db/pg/pg.go

ref: https://www.postgresql.org/docs/current/libpq-status.html#LIBPQ-PQSERVERVERSION

feat: convert pg server_version_num

---

backend/migrator/demo/next/demo.sql

LIst all instances that Bytebase currently supports.

feat(demo-next): add instances

---

frontend/src/components/IssueV1/components/IssueTableV1.vue
frontend/src/components/ProjectOverviewPanel.vue
frontend/src/views/Home.vue
frontend/src/views/IssueDashboard.vue

feat(frontend): put issue category onto issue navigation bar

---

frontend/src/components/Branch/BranchDataTable.vue
frontend/src/views/branch/BranchDashboard.vue

chore: implement data table for branch

---

frontend/src/components/IssueV1/components/IssueTableV1.vue

feat: prepend the VCS provider icon if the issure is created via VCS

---

frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

chore: improve tenant database template comment

---

frontend/src/components/Branch/BranchDataTable.vue

* add project and baseline version fields to branch data table

chore: update data table fields

---

frontend/src/components/Project/ProjectDBNameTemplateSettingPanel.vue
frontend/src/components/ProjectDeploymentConfigPanel.vue
frontend/src/components/ProjectSettingPanel.vue

chore(frontend): move project db name template setting to settings tab

---

backend/server/webhook.go
backend/tests/tenant_test.go

chore: support multiple files in a commit for batch projects

---

frontend/src/views/IssueDashboard.vue

Don't need CP, only have this bug in dev.

fix: extract project resource id for issue search

---

frontend/src/components/SchemaEditorV1/Modals/TableNameModal.vue
frontend/src/components/SchemaEditorV1/Panels/DatabaseEditor.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

The resource type is incorrect https://sourcegraph.com/github.com/bytebase/bytebase/-/blob/frontend/src/types/v1/schemaEditor/state.ts?L47
PTAL @boojack

fix: cannot edit table name in editor

---

frontend/src/views/sql-editor/AsidePanel/AsidePanel.vue
frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue
frontend/src/views/sql-editor/EditorCommon/ExecuteHint.vue
frontend/src/views/sql-editor/SQLEditorPage.vue
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/InfoTabPane.vue
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/DatabaseSchema.vue
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/SchemaPanel.vue
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/TableSchema.vue
frontend/src/views/sql-editor/SecondarySidebar/SecondarySidebar.vue
frontend/src/views/sql-editor/context.ts

do avoid deep nested event listeners

refactor(sql-editor): extract alter-schema events

---

backend/api/v1/schema_design_service.go
frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
frontend/src/components/SchemaEditorV1/Aside/DatabaseTree.vue

* use `SchemaDesignService.DiffMetadata` in schema editor for MySQL;

chore: use diff metadata in schema editor for MySQL

---

frontend/src/components/SchemaEditorV1/Aside/BranchTree.vue
frontend/src/components/SchemaEditorV1/Aside/DatabaseTree.vue

Shrink the padding of tree nodes.

chore(schema-editor): update tree styles

---

frontend/src/views/Home.vue

chore(frontend): remember last selected tab in home page's issue list

---

frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckBadge.vue
frontend/src/components/IssueV1/components/common/TaskSpinner.vue
frontend/src/components/IssueV1/components/common/index.ts

chore: bring task check running spinner back

---

backend/plugin/db/mongodb/mongodb.go
backend/plugin/db/mongodb/mongodb_test.go

chore: flatten mongo result

---

frontend/src/components/ExprEditor/components/ValueInput.vue

chore(frontend): clean up value when factor changed

---

frontend/src/components/SchemaEditorV1/Panels/TableColumnEditor.vue
frontend/src/components/SchemaEditorV1/Panels/TableEditor.vue

We will use the table column editor for the table template later.

refactor: extract table column editor

---

frontend/src/components/ViewTable.vue

chore(frontend): improve view table column layout

---

frontend/src/components/DatabaseTable.vue
frontend/src/components/TenantIcon.vue
frontend/src/components/v2/Model/DatabaseV1Table/ProjectCol.vue
frontend/src/components/v2/Model/ProjectV1Table.vue

chore: fix tenant icon size

---

frontend/src/components/DatabaseChangeHistoryPanel.vue
scripts/.air.toml

chore: tweak change history list toolbar

---

frontend/src/components/CreateDatabasePrepForm/CreateDatabasePrepForm.vue

chore: allow to change environment when creating database

---

frontend/src/views/auth/Signin.vue

chore(frontend): sign-in page style

---

frontend/src/components/Branch/BranchDetailView.vue
frontend/src/components/Branch/SchemaDesignSQLCheckButton.vue
frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckBadge.vue
frontend/src/components/SQLCheck/SQLCheckButton.vue
frontend/src/components/SQLCheck/SQLCheckDetail.vue
frontend/src/components/SQLCheck/SQLCheckPanel.vue
frontend/src/components/SQLCheck/SQLCheckSummary.vue
frontend/src/components/SQLCheck/index.ts
frontend/src/components/misc/ErrorList.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

The button is only clickable when the branch schema is valid. (We cannot perform metadata diff if one of the source or target metadata is invalid)
Close BYT-4030

feat(frontend): sql check for branching

---

backend/plugin/db/mysql/sync.go

fix: mysql sync EXPRESSION column not found

---

backend/api/v1/schema_design_service.go

* add metadata checks before transform it into schema string;

chore: add validate metadata

---

frontend/src/components/AdvancedSearch.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/views/IssueDashboard.vue

chore: support search by creator/assignee/subscriber

---

backend/api/v1/auth_service.go

https://www.virtuesecurity.com/kb/username-enumeration/

chore: prevent username enumeration

---

frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
frontend/src/components/AlterSchemaPrepForm/SchemaEditorSQLCheckButton/SchemaEditorSQLCheckButton.vue
frontend/src/components/AlterSchemaPrepForm/SchemaEditorSQLCheckButton/index.ts
frontend/src/components/AlterSchemaPrepForm/SchemaEditorSQLCheckButton/useSchemaEditorSQLCheck.ts
frontend/src/components/AlterSchemaPrepForm/utils.ts
frontend/src/store/modules/v1/dbSchema.ts

feat(frontend): sql check for schema editor

---

frontend/src/App.vue

@boojack do you think this can help fix BYT-4014?

chore(frontend): always clear help timer when route changed

---

frontend/src/layouts/BodyLayout.vue
frontend/src/layouts/ProjectLayout.vue

Before
After
Also fix mobile sidebar icon

chore: improve project detail spacing

---

frontend/src/components/Branch/BranchDetailView.vue
frontend/src/components/SchemaEditorV1/Panels/TableColumnEditor.vue

* Use internal link navigating to the project detail
* Better spacing between project and branch
* Add border around table column editor

chore: Branch / TableEditor style tweak

---

frontend/src/components/Branch/BranchCreateView.vue
frontend/src/components/Branch/BranchDataTable.vue
frontend/src/components/SchemaEditorV1/TabsContainer.vue
frontend/src/views/branch/BranchDetail.vue

fix: creating branch handler

---

frontend/src/components/IssueV1/components/ActivitySection/Activity/ActionIcon.vue

chore: update re-request review activity icon

---

frontend/src/components/Branch/BranchDataTable.vue

* enlarge trigger icon;
* add hover styles to the trigger element;

chore: update trigger style of data table

---

frontend/src/components/Branch/BranchDetailView.vue
frontend/src/components/SchemaEditorV1/index.vue

* create draft branch before saving edits but not edit branch.

refactor(branching): create draft branch before saving edits

---

frontend/src/components/AlterSchemaPrepForm/SchemaEditorSQLCheckButton/SchemaEditorSQLCheckButton.vue
frontend/src/components/SQLCheck/SQLCheckButton.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

chore(frontend): tips for SQL check button when no SQL review policy configured

---

backend/runner/mail/slow_query_weekly_mail.go
backend/runner/mail/templates/for-dba/database_table_header.html
backend/runner/mail/templates/for-dba/database_table_item.html
backend/runner/mail/templates/for-project-owner/environment_header.html
backend/runner/mail/templates/for-project-owner/table_item.html

feat: add more fields to slow query weekly mail

---

frontend/src/views/sql-editor/AsidePanel/AsidePanel.vue

chore: use singular form in the SQL Editor left sidebar tab

---

frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
frontend/src/components/AlterSchemaPrepForm/SchemaEditorSQLCheckButton/SchemaEditorSQLCheckButton.vue
frontend/src/components/Branch/BranchDetailView.vue
frontend/src/components/IssueV1/IssueDetailPage.vue
frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue
frontend/src/components/SQLCheck/SQLCheckButton.vue
frontend/src/components/SQLCheck/SQLCheckPanel.vue
frontend/src/components/SQLCheck/context.ts
frontend/src/components/SQLCheck/index.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

- Disable SQL check button when schema is too large (> 500KiB) (Close BYT-4073)
- Run SQL Check automatically when needed if possible (BYT-4074)
- Show confirmation dialog when saving schema with SQL check violations (Close BYT-4075)

feat(frontend): SQL Check improvements

---

backend/plugin/db/pg/pg.go

chore: support vacuum command

---

frontend/src/components/Branch/BranchDetailView.vue
frontend/src/components/Breadcrumb.vue
frontend/src/router/index.ts
frontend/src/store/modules/router.ts
frontend/src/views/branch/BranchDetail.vue

chore(branch): add project link to breadcrumb

---

frontend/src/components/Branch/BranchDetailView.vue

chore: adjust edit button in branch detail

---

backend/plugin/db/mysql/mysql.go
backend/plugin/db/mysql/query.go
backend/plugin/db/mysql/query_test.go

feat(sql-editor): use parser to set query limit for TiDB

---

frontend/src/components/CustomApproval/Settings/components/CustomApproval/RulesPanel/RuleSelect.vue
frontend/src/components/v2/Select/DatabaseSelect.vue
frontend/src/components/v2/Select/EnvironmentSelect.vue
frontend/src/components/v2/Select/InstanceSelect.vue
frontend/src/components/v2/Select/ProjectMemberRoleSelect.vue
frontend/src/components/v2/Select/ProjectSelect.vue
frontend/src/components/v2/Select/UserSelect.vue

It's weird. Maybe involved by upgrading tailwindcss. But anyway we can fix it, even though case by case.
Close BYT-4087

chore(frontend): fix duplicated rings for focused input elements

---

frontend/src/components/DatabaseGroup/common/ExprEditor/components/ValueInput.vue

Related fix: https://github.com/bytebase/bytebase/commit/e4e00a2a290b4fe54e1b7f05ce0bbff1aa3b98e7#diff-27e1cc4242d5678ab88066f07a67e52b35610ab1ada83267d22ba4fbb34eabc9R155
PTAL @LiuJi-Jim

fix: expr input reset

---

frontend/src/components/Breadcrumb.vue

chore: update project link in breadcrumb

---

frontend/src/components/DatabaseGroup/common/ExprEditor/components/ValueInput.vue
frontend/src/views/SettingWorkspaceSQLReviewDetail.vue

fix: duplicate rule

---

frontend/src/components/DatabaseGroup/common/ExprEditor/components/ValueInput.vue
frontend/src/store/modules/dbGroup.ts
frontend/src/utils/databaseGroup/cel.ts
frontend/src/utils/v1/cel.ts
frontend/src/utils/v1/index.ts
frontend/src/utils/workspaceApprovalSetting.ts

refactor: use cel batch api

---

frontend/src/layouts/SQLEditorLayout.vue
frontend/src/views/sql-editor/SQLEditorPage.vue
frontend/src/views/sql-editor/TabList/TabList.vue

Hide the banners, user avatar and quick start guides in the bundled mode of SQL editor

chore: hide unwanted elements in the bundled mode of SQL editor

---

backend/api/v1/database_service.go

fix: schema version

---

frontend/src/components/GeneralSetting/AnnouncementSetting.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

chore: hint to leave text empty to clear announcement.

---

backend/api/v1/schema_design_service.go
backend/store/sheet.go
frontend/src/components/Branch/BranchDetailView.vue
frontend/src/components/SchemaEditorV1/index.vue
frontend/src/components/SchemaEditorV1/utils/branch.ts

* auto delete references of main branch when it's deleted for personal branches;
* fix save drafts action handler;
Close BYT-4109, BYT-4110, BYT-4111, BYT-4112

fix: branch issues of personal draft

---

frontend/src/components/Branch/BranchDetailView.vue

fix: branch state handler after merging

---

frontend/src/layouts/SQLEditorLayout.vue
frontend/src/views/sql-editor/SQLEditorPage.vue
frontend/src/views/sql-editor/TabList/TabList.vue

```
// SQL Editor is bundled with main console.
| "BUNDLED"
// SQL Editor is by its own.
| "STANDALONE";
```

fix: sql editor standalone mode🔥

---

frontend/src/views/DashboardSidebar.vue
frontend/src/views/Home.vue

chore: expose issue advanced search explicitly

---

frontend/src/components/CustomApproval/Settings/components/RiskCenter/RiskCenter.vue
frontend/src/components/CustomApproval/Settings/components/RiskCenter/RiskDialog/RiskDialog.vue
frontend/src/components/CustomApproval/Settings/components/RiskCenter/RiskDialog/RiskForm.vue
frontend/src/components/CustomApproval/Settings/components/RiskCenter/RiskDialog/RiskLevelSelect.vue
frontend/src/components/CustomApproval/Settings/components/RiskCenter/RiskDialog/RiskSourceSelect.vue
frontend/src/components/CustomApproval/Settings/components/RiskCenter/RiskDialog/RuleTemplateTable.vue
frontend/src/components/CustomApproval/Settings/components/RiskCenter/RiskDialog/template.ts
frontend/src/components/CustomApproval/Settings/components/RiskCenter/RiskTable.vue
frontend/src/components/CustomApproval/Settings/components/common/RiskFilter/LevelFilter.vue
frontend/src/components/CustomApproval/Settings/components/common/RiskFilter/RiskFilter.vue
frontend/src/components/CustomApproval/Settings/components/common/utils.ts
frontend/src/components/DatabaseGroup/common/ExprEditor/ConditionGroup.vue
frontend/src/components/DatabaseGroup/common/ExprEditor/components/StringInput.vue
frontend/src/components/ExprEditor/ConditionGroup.vue
frontend/src/components/ExprEditor/components/MultiSelect.vue
frontend/src/components/ExprEditor/components/MultiStringInput.vue
frontend/src/components/ExprEditor/components/NumberInput.vue
frontend/src/components/ExprEditor/components/SingleSelect.vue
frontend/src/components/ExprEditor/components/StringInput.vue
frontend/src/components/SensitiveData/components/SemanticTypesTable.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

chore: change wording "Security rule" to "Risk rule"

---

backend/server/ultimate.go
scripts/.air.toml
scripts/Dockerfile.render-demo

We will not compile oracle, snowflake, mssql parser in these cases.

chore: add minimal tag to demo and local

---

backend/api/v1/sql_service.go
backend/plugin/parser/base/interface.go
backend/plugin/parser/mysql/mysql.go
backend/plugin/parser/mysql/query.go
backend/plugin/parser/mysql/query_test.go
backend/plugin/parser/pg/query.go
backend/plugin/parser/pg/query_test.go
backend/plugin/parser/plsql/query.go
backend/plugin/parser/plsql/split_test.go
backend/plugin/parser/standard/query.go
backend/plugin/parser/standard/query_test.go
backend/plugin/parser/tidb/query.go

TODO: make error as structured message.

fix: query error

---

frontend/src/components/GeneralSetting/NetworkSetting.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

chore: improve gitops webhook url help

---

frontend/src/components/SchemaEditorV1/Panels/TableColumnEditor.vue

Use BBGrid component instead.
After fixed

fix: table column editor layout

---

frontend/src/components/DatabaseGroup/MatchedDatabaseView.vue
frontend/src/composables/useExecuteSQL.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/sqlEditor.ts
frontend/src/store/modules/tab.ts
frontend/src/store/modules/v1/webTerminal.ts
frontend/src/types/tab.ts
frontend/src/views/sql-editor/EditorCommon/BatchQueryDatabasesSelector.vue
frontend/src/views/sql-editor/EditorCommon/ConnectionPathBar.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
frontend/src/views/sql-editor/EditorPanel/SQLEditor.vue
frontend/src/views/sql-editor/ResultPanel/ResultPanel.vue
frontend/src/views/sql-editor/SQLEditorPage.vue

https://github.com/bytebase/bytebase/assets/24653555/708e3670-abd9-4240-87cc-fc2d424f016b

feat: implement query multi databases in the standard mode of sql editor 

---

backend/legacyapi/plan.go
frontend/src/composables/useExecuteSQL.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/types/plan.ts
frontend/src/views/sql-editor/EditorCommon/AdminModeButton.vue
frontend/src/views/sql-editor/EditorCommon/BatchQueryDatabasesSelector.vue
frontend/src/views/sql-editor/EditorCommon/EditorAction.vue
frontend/src/views/sql-editor/ResultPanel/ResultPanel.vue

chore: add feature type for batch query

---

frontend/src/components/Project/ProjectCreatePanel.vue
frontend/src/components/Project/ProjectGeneralSettingPanel.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

chore: adjust project key hint

---

frontend/src/views/sql-editor/EditorCommon/ConnectionPathBar.vue
frontend/src/views/sql-editor/EditorCommon/ReadonlyDatasourceHint.vue

chore(sql-editor): adjust connection path bar layout and style

---

frontend/src/views/sql-editor/EditorCommon/BatchQueryDatabasesSelector.vue

chore: add learn more link for batch query

---

backend/api/v1/schema_design_transformer_tidb.go
backend/api/v1/testdata/tidb/design.yaml
backend/api/v1/testdata/tidb/schema.yaml

fix: support tidb binary column type

---

frontend/src/components/FeatureGuard/FeatureBadge.vue
frontend/src/views/SettingWorkspaceSSO.vue

Noticed this when trying to fix the Create SSO button

fix: custom style is not applied to FeatureBadge

---

frontend/src/views/BannerAnnouncement.vue

Adds a hover effect to announcement banners.
Closes #8401

feat(frontend): Adds a hover effect when hovering an announcement

---

backend/store/model/change_history.go

Will move all string type of version to this model.

chore: introduce version (change history version) model

---

backend/enterprise/api/plan.yaml
frontend/src/components/InstanceForm/DataSourceSection/DataSourceForm.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/subscription/en-US.json
frontend/src/locales/subscription/es-ES.json
frontend/src/locales/subscription/zh-CN.json
frontend/src/locales/zh-CN.json
frontend/src/types/plan.ts

chore: support external secret manager in frontend

---

frontend/src/composables/useExecuteSQL.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/views/sql-editor/EditorCommon/BatchQueryDatabasesSelector.vue
frontend/src/views/sql-editor/EditorCommon/ConnectionPathBar.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue
frontend/src/views/sql-editor/ResultPanel/ResultPanel.vue

chore: fix batch query issues

---

frontend/src/App.vue
frontend/src/layouts/SQLEditorLayout.vue
frontend/src/views/OAuthCallback.vue
frontend/src/views/sql-editor/EditorCommon/ExecuteHint.vue

* Hide OAuth2 succeed message on oauth callback page;

chore: hide OAuth2 succeed message and non-select warning dialog buttons

---

frontend/src/components/ProjectDatabasesPanel.vue
frontend/src/components/TransferOutDatabaseForm/TransferOutDatabaseForm.vue
frontend/src/components/TransferOutDatabaseForm/common.ts
frontend/src/components/v2/Model/DatabaseV1Table/DatabaseGroupTableRow.vue
frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
frontend/src/components/v2/Model/DatabaseV1Table/DatabaseTableRow.vue
frontend/src/components/v2/Model/DatabaseV1Table/DatabaseV1Table.vue
frontend/src/components/v2/Model/DatabaseV1Table/utils.ts
frontend/src/components/v2/Select/ProjectSelect.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/views/DatabaseDashboard.vue

- database batch operations
- show labels in database table

chore: database batch operations

---

backend/api/v1/database_service.go
backend/store/database.go
backend/utils/utils.go

chore: don't return environment label

---

frontend/src/components/SchemaEditorV1/Aside/BranchTree.vue

fix: cannot expand pg schema

---

frontend/src/App.vue
frontend/src/CustomThemeProvider.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/utils/customTheme.ts
frontend/src/views/sql-editor/AsidePanel/AsidePanel.vue

chore: add custom theme provider

---

backend/api/v1/sql_service.go

We'll support query cancellation.

chore: change query timeout from 1min to 10min

---

frontend/src/components/CustomApproval/Settings/components/CustomApproval/RulesPanel/RuleSelect.vue
frontend/src/components/IdentityProviderCreateForm.vue
frontend/src/components/IssueV1/components/ActivitySection/Activity/ActionIcon.vue
frontend/src/components/v2/Select/DatabaseSelect.vue
frontend/src/components/v2/Select/EnvironmentSelect.vue
frontend/src/components/v2/Select/InstanceSelect.vue
frontend/src/components/v2/Select/ProjectMemberRoleSelect.vue
frontend/src/components/v2/Select/UserSelect.vue

fix all warning of compiler-sfc

chore: fix warning of compiler-sfc

---

frontend/src/composables/useExecuteSQL.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/types/tab.ts
frontend/src/views/sql-editor/EditorCommon/BatchQueryDatabasesSelector.vue

chore: update batch query selector

---

frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue
frontend/src/views/sql-editor/ResultPanel/ResultPanel.vue

chore: add query failed icon in each tabs

---

frontend/src/components/v2/Select/WorkspaceRoleSelect.vue

chore(frontend): fix double border for dropdown select

---

backend/plugin/db/mongodb/sync.go

We have found that the MongoDB Atlas Cloud M0/M2/M5 tier do not support `usersInfo` commands for all databases, because they are sandbox(shared) cluster.
In this PR, we ignore the different error reported by M10/M20/M30 tier cluster at least, although they are general cluster.

fix(mongodb-atlas): ignore atlas general cluster error of usersInfo command

---

frontend/src/views/Changelist/ChangelistDetail/AddChangePanel/AddChangePanel.vue
frontend/src/views/Changelist/ChangelistDetail/AddChangePanel/form/BranchTable/BranchTable.vue
frontend/src/views/Changelist/ChangelistDetail/AddChangePanel/form/ChangeHistoryTable/ChangeHistoryTable.vue
frontend/src/views/Changelist/ChangelistDetail/ChangeTable/ChangeTable.vue
frontend/src/views/Changelist/ChangelistDetail/ChangeTable/Source.vue
frontend/src/views/Changelist/ChangelistDetail/RawSQLEditor/RawSQLEditor.vue

chore: changelist ux tweak

---

frontend/src/components/Branch/BranchCreateView.vue
frontend/src/components/Branch/BranchDetailView.vue
frontend/src/components/Breadcrumb.vue
frontend/src/components/ProjectBranchesPanel.vue
frontend/src/router/index.ts
frontend/src/store/modules/router.ts
frontend/src/store/modules/v1/common.ts
frontend/src/types/common.ts
frontend/src/utils/slug.ts
frontend/src/views/DashboardHeader.vue
frontend/src/views/SyncDatabaseSchema/SchemaDesignSelector.vue
frontend/src/views/SyncDatabaseSchema/SelectTargetDatabasesView.vue
frontend/src/views/branch/BranchDashboard.vue
frontend/src/views/branch/BranchDetail.vue

* Branches: `/branches`;
* Create new branch: `/projects/{projectName}/branches/new`;
* Branch detail: `/projects/{projectName}/branches/{branchName}`;

chore: update branch routes

---

frontend/src/views/branch/BranchDashboard.vue

chore: add project filter to branch dashboard

---

backend/common/stacktrace/stack.go
backend/common/stacktrace/stack_test.go
backend/server/server.go

refer: https://github.com/DataDog/dd-trace-go/pull/436/files

fix: recovery interceptor stacktrace

---

frontend/src/components/Breadcrumb.vue
frontend/src/views/Changelist/ChangelistDashboard/context.ts
frontend/src/views/Changelist/ChangelistDetail/AddChangePanel/AddChangePanel.vue
frontend/src/views/Changelist/ChangelistDetail/BranchDetailPanel/BranchDetailPanel.vue
frontend/src/views/Changelist/ChangelistDetail/ChangeHistoryDetailPanel/ChangeHistoryDetailPanel.vue
frontend/src/views/Changelist/ChangelistDetail/ChangeTable/Source.vue
frontend/src/views/Changelist/ChangelistDetail/RawSQLPanel/RawSQLPanel.vue

- Breadcrumb improvements
- Adjust drawers' widths
- Add detail version / branch name to the "source" column

feat(frontend): changelist improvements

---

frontend/src/components/Branch/BranchDetailView.vue
frontend/src/components/Branch/SchemaDesignEditor.vue
frontend/src/components/Branch/SchemaDesignSQLCheckButton.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

chore: add raw sql preview to branch design

---

frontend/src/components/Branch/BranchDetailView.vue
frontend/src/views/Changelist/ChangelistDetail/NavBar/NavBar.vue
frontend/src/views/Changelist/ChangelistDetail/NavBar/TitleEditor.vue

chore: make title edit control consistent between branch and changelist

---

frontend/src/views/sql-editor/EditorCommon/BatchQueryDatabasesSelector.vue

Be consistent with other controls on the SQL Editor

chore: make batch query control size smaller

---

backend/plugin/parser/pg/differ.go
backend/plugin/parser/pg/pg.go
backend/plugin/parser/pg/test-data/test_differ_data.yaml
backend/plugin/parser/sql/engine/pg/convert.go
backend/plugin/parser/sql/engine/pg/convert_test.go
backend/plugin/parser/sql/engine/pg/deparse.go
backend/plugin/parser/sql/engine/pg/deparse_test.go
backend/plugin/parser/sql/engine/pg/test-data/test_comment_data.yaml
backend/plugin/schema-engine/pg/structurer.go
backend/plugin/schema-engine/pg/testdata/get_design_schema.yaml

feat: support Branching and Differ for PostgreSQL COMMENT TABLE/COLUMN

---

frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/components/SchemaEditorV1/Aside/DatabaseTree.vue
frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue

need to specify `nodeHeight` manually.
FYI @ecmadao @boojack

chore(frontend): fix tree height when virtual-scroll is true

---

frontend/src/views/Changelist/ChangelistDetail/BranchDetailPanel/BranchBaseline.vue
frontend/src/views/Changelist/ChangelistDetail/BranchDetailPanel/BranchDetailPanel.vue

- Use <SchemaDesignEditor> by @boojack, Thanks!
- Add branch baseline info section to the panel

chore(frontend): changelist branch detail panel improvements

---

frontend/src/components/Label/LabelListEditor.vue
frontend/src/utils/label.ts

chore: remove validating label key

---

backend/runner/approval/runner.go

fix: risk level eval order

---

backend/store/instance_change_history.go

- write statement if sheet_id is NULL
- read from sheet, then statement

feat(instance change history): write one of sheet, statement

---

backend/api/v1/schema_design_transformer.go
backend/plugin/schema-engine/pg/structurer.go

feat: enable raw sql preview for pg and tidb

---

backend/plugin/db/mysql/mysql.go

fix: cut mysql version and return the numbers

---

frontend/src/components/Branch/utils.ts
frontend/src/components/SchemaTemplate/FieldTemplateTable.vue
frontend/src/components/SchemaTemplate/SelectClassificationDrawer.vue
frontend/src/components/SchemaTemplate/TableTemplateForm.vue
frontend/src/components/SchemaTemplate/TableTemplateTable.vue
frontend/src/types/v1/schemaEditor/atomType.ts

chore: support classification in table template

---

frontend/src/components/AnomalyTable.vue
frontend/src/views/ChangeHistoryDetail.vue

chore(frontend): fix schema drift popup dialog style

---

frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/views/Changelist/ChangelistDetail/DeleteChangelistButton.vue

chore: tweak wording to “Delete this changelist”

---

backend/api/v1/issue_service.go

fix: create activities on updating issue fields

---

backend/plugin/schema-engine/pg/structurer.go
backend/plugin/schema-engine/pg/testdata/get_design_schema.yaml

fix: fix multi-schema for PostgreSQL schema design

---

frontend/src/components/Branch/BranchCreateView.vue

see the comments if interested.

chore(frontend): fix full schema for non-existed latest change history

---

frontend/src/CustomThemeProvider.vue
frontend/src/layouts/SQLEditorLayout.vue

Since the page will be redirected multiple times during the OAuth2 process, we need to check the parameters when the route changes.

fix: custom theme provider

---

frontend/naive-ui.config.ts
frontend/src/CustomThemeProvider.vue

fix: detect custom theme changes

---

frontend/src/components/SchemaEditorV1/Aside/BranchTree.vue

* add create schema button for Postgres;
* fix drop/restore schema action handlers;

fix: schema resource actions in branch tree

---

backend/api/v1/schema_design_service.go
frontend/src/store/modules/schemaDesign.ts

Frontend changes later in this PR.

feat: ListSchemaDesigns view

---

backend/resources/postgres/meta_instance.go
backend/resources/postgres/postgres.go
backend/resources/postgres/sample_instance.go
backend/server/server.go

1. start old server.
2. dump SQL.
3. stop old server.
4. start new server.
5. create database.
6. run SQL.
7. restart server.

chore: support metadata postgres server upgrade

---

backend/resources/README.md
backend/resources/postgres/meta_instance.go
backend/resources/postgres/postgres.go
backend/resources/postgres/sample_instance.go
backend/server/server.go
backend/tests/syncer_test.go

- stats_temp_directory isn't supported in pg_ctl.
- The view definition is slightly changed.

chore: pg16

---

frontend/src/components/SchemaEditorV1/Editor.vue
frontend/src/components/SchemaEditorV1/Panels/DatabaseEditor.vue
frontend/src/components/SchemaEditorV1/Panels/TableEditor.vue
frontend/src/components/SchemaEditorV1/TabsContainer.vue

https://linear.app/bytebase/issue/BYT-4094/schema-editor-move-search-field-to-the-tab-bar
after:
search table
search column

feat: move search field to the tab bar

---

frontend/src/components/Branch/utils.ts
frontend/src/components/SchemaEditorV1/Modals/ColumnDefaultValueExpressionModal.vue
frontend/src/components/SchemaEditorV1/Panels/TableColumnEditor.vue
frontend/src/components/SchemaEditorV1/utils/columnDefaultValue.ts
frontend/src/components/SchemaEditorV1/utils/metadata.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/types/v1/schemaEditor/atomType.ts

https://github.com/bytebase/bytebase/assets/24653555/aae791ab-9d20-4798-9f79-56d8c393317e

chore(schema-editor): update column default value field

---

backend/plugin/db/snowflake/query.go
backend/plugin/db/snowflake/query_test.go
backend/plugin/db/snowflake/snowflake.go
backend/plugin/db/snowflake/test-data/test_limit.yaml

- use antlr parser to add limit clause for snowflake.

feat: add snwoflake limit clause

---

backend/api/v1/anomaly_service.go
backend/api/v1/database_service.go
backend/api/v1/issue_service.go

chore: handle get instance gracefully

---

frontend/src/components/IssueV1/components/TaskRunSection/TaskRunTable.vue
frontend/src/components/misc/HumanizeDate.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

chore(frontend): show task run start time column

---

frontend/src/layouts/BodyLayout.vue
frontend/src/views/DashboardHeader.vue

chore: use outline style for SQL Editor icon to make style consistent

---

frontend/src/components/Branch/BranchDetailView.vue

Be consistent with the rest of text

chore: make branch basline text small

---

backend/api/v1/schema_design_transformer.go
frontend/src/components/SchemaEditorV1/Aside/BranchTree.vue
frontend/src/components/SchemaEditorV1/Editor.vue
frontend/src/components/SchemaEditorV1/Panels/DatabaseEditor.vue
frontend/src/components/SchemaEditorV1/Panels/TableList.vue
frontend/src/components/SchemaEditorV1/TabsContainer.vue
frontend/src/components/SchemaEditorV1/utils/metadata.ts

* implement table list in branching;
* implement table-level comment stringify for MySQL in backend;
https://github.com/bytebase/bytebase/assets/24653555/1c474926-a1d4-4070-95cc-3ddc0747f092

chore: update table level classification for MySQL

---

frontend/src/components/CreateDatabasePrepForm/CreateDatabasePrepForm.vue
frontend/src/components/DatabaseBackup/BackupTable.vue
frontend/src/components/DatabaseDetail/PITRRestoreButton.vue
frontend/src/components/IssueV1/components/HeaderSection/Actions/rollout/CombinedRolloutButtonGroup.vue
frontend/src/components/IssueV1/components/HeaderSection/Actions/rollout/RolloutActionButton.vue
frontend/src/components/IssueV1/components/HeaderSection/Assignee/Assignee.vue
frontend/src/components/IssueV1/components/IssueTableV1.vue
frontend/src/components/IssueV1/components/TaskListSection/TaskExtraActionsButton.vue
frontend/src/components/IssueV1/logic/action/task.ts
frontend/src/components/IssueV1/logic/assignee.ts
frontend/src/components/IssueV1/logic/base.ts
frontend/src/components/IssueV1/logic/context.ts
frontend/src/components/IssueV1/logic/initialize/assignee.ts
frontend/src/components/IssueV1/logic/initialize/create.ts
frontend/src/components/v2/Select/UserSelect.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/v1/policy.ts
frontend/src/utils/role.ts
frontend/src/views/EnvironmentDashboard.vue
frontend/src/views/EnvironmentDetail.vue
frontend/src/views/IssueDetailV1.vue

refactor(frontend): use CD policy in issue

---

frontend/src/components/SchemaEditorV1/utils/metadata.ts
frontend/src/store/modules/schemaDesign.ts
frontend/src/types/v1/schemaEditor/atomType.ts

fix: rebuild editable metadata in branching

---

go.mod
go.sum

relat: https://github.com/bytebase/tsql-parser/pull/2

chore: upgrade tsql parser version

---

frontend/src/components/Branch/BaselineSchemaSelector.vue
frontend/src/components/Branch/BranchCreateView.vue
frontend/src/components/Branch/BranchDataTable.vue
frontend/src/components/Branch/BranchDetailView.vue
frontend/src/components/Branch/BranchSelector.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

Close BYT-4242
https://github.com/bytebase/bytebase/assets/24653555/a9822065-f743-4dd6-aa23-97b42aff1c58

feat: support creating branch from parent

---

backend/api/v1/schema_design_service.go
frontend/src/components/Branch/BranchDetailView.vue
frontend/src/components/Branch/BranchSelector.vue
frontend/src/components/Branch/MergeBranchPanel.vue
frontend/src/components/SchemaEditorV1/utils/metadata.ts

Close BYT-4228
https://github.com/bytebase/bytebase/assets/24653555/d803829f-1d0d-4922-aa1e-89107ed485b6

feat: allow to select target branch when merging

---

frontend/src/components/IssueV1/components/Panel/TaskRolloutActionPanel.vue

chore(frontend): add stage section in rollout panel

---

frontend/src/components/misc/TextOverflowPopover.vue
frontend/src/views/Changelist/ChangelistDetail/ChangeTable/DatabaseForChange.vue
frontend/src/views/Changelist/ChangelistDetail/ChangeTable/SQL.vue

- Strip line breaks for SQL in changelist change table
- limit the SQL popover's content size to prevent it to be too laggy
Close BYT-4212

chore(frontend): changelist ui improvements

---

frontend/src/components/User/Settings/MemberAddOrInvite.vue

chore: reduce 3 empty users to 1 empty user on member page

---

frontend/src/components/ColumnTable.vue
frontend/src/components/SchemaEditorV1/Panels/TableColumnEditor.vue
frontend/src/components/SchemaTemplate/FieldTemplateForm.vue
frontend/src/components/SensitiveData/SemanticTypesView.vue

The proto changed https://github.com/bytebase/bytebase/commit/2028c917f91b0b119196a1fe1b508a1d4f7ef3ee#diff-2b58a68b875969a9b949ffd3508988cd5025a0626cb6492b69f59a5677f508bbL109

fix: update frontend due to proto changed

---

frontend/src/components/Branch/BaselineSchemaSelector.vue
frontend/src/components/Branch/BranchCreateView.vue
frontend/src/views/SyncDatabaseSchema/SelectTargetDatabasesView.vue

* use naive selector instead BBSelector in creating branch view.
Close BYT-4084

chore: update baseline v1 selectors

---

frontend/src/components/Branch/BranchCreateView.vue
frontend/src/components/Branch/BranchSelector.vue

chore(branching): hide project selector under project view

---

frontend/src/components/ProjectMember/AddProjectMember/AddProjectMemberForm.vue
frontend/src/components/ProjectMember/AddProjectMember/AddProjectMembersPanel.vue
frontend/src/components/ProjectMember/ProjectMemberTable/ProjectMemberRolePanel.vue

chore: add grant access button to project member roles panel

---

frontend/src/components/CreateDataSourceExample.vue
frontend/src/components/DatabaseDetail/CreatePITRDatabaseForm.vue
frontend/src/components/InstanceForm/DataSourceSection/CreateReadOnlyDataSourceTips.vue
frontend/src/components/InstanceForm/DataSourceSection/DataSourceForm.vue
frontend/src/components/InstanceForm/DataSourceSection/OracleSIDAndServiceNameInput.vue
frontend/src/components/InstanceForm/DataSourceSection/SpannerCredentialInput.vue
frontend/src/components/InstanceForm/DataSourceSection/SshConnectionForm.vue
frontend/src/components/InstanceForm/DataSourceSection/SslCertificateForm.vue
frontend/src/components/InstanceForm/DataSourceSection/common.ts
frontend/src/components/InstanceForm/InstanceForm.vue
frontend/src/components/InstanceForm/OracleSyncModeInput.vue
frontend/src/components/InstanceForm/SpannerHostInput.vue
frontend/src/components/misc/DroppableTextarea.vue
frontend/src/components/v2/Select/DatabaseSelect.vue

Radios, Inputs, and Buttons are all migrated to naive-ui components.
`<DroppableTextarea>` is complex and TBD.

chore(frontend): migrate instance page to naive-ui components 

---

frontend/src/components/Branch/BaselineSchemaSelector.vue
frontend/src/components/Project/ProjectGeneralSettingPanel.vue
frontend/src/components/ProjectSettingPanel.vue
frontend/src/views/ProjectDetail.vue

chore: move deployment config to project setting page

---

frontend/src/components/ProjectSettingPanel.vue

Attribute "v-if" should go before "class"

fix: linter warning

---

backend/plugin/db/pg/sync.go

feat: add pg character/bit string type length to metadata

---

frontend/src/components/InstanceForm/DataSourceSection/SpannerCredentialInput.vue
frontend/src/components/InstanceForm/DataSourceSection/SshConnectionForm.vue
frontend/src/components/InstanceForm/DataSourceSection/SslCertificateForm.vue
frontend/src/components/misc/DroppableTextarea.vue

chore(frontend): use naive-ui components to implement DroppableTextarea

---

frontend/src/components/GeneralSetting/BrandingSetting.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

feat(frontend): allow to delete custom branding logo

---

backend/api/v1/schema_design_transformer.go
backend/api/v1/testdata/design.yaml
backend/api/v1/testdata/schema.yaml

feat: support table comment for MySQL

---

backend/store/stats.go

Breaking by https://github.com/bytebase/bytebase/pull/8456/files#diff-5572ea7c6df5bf6dd4180992924b8ebe9cb9fd4a4f5ccdf7d620d2f306e916a4L345-L361 which approved by me 😂

fix(collector): sheet collector sql

---

backend/api/v1/project_service.go
frontend/src/components/Branch/utils.ts
frontend/src/components/Project/CreateProjectBranchProtectionRulePanel.vue
frontend/src/components/Project/ProjectBranchProtectionRulesSettingPanel.vue
frontend/src/components/Project/ProjectGeneralSettingPanel.vue
frontend/src/components/ProjectSettingPanel.vue
frontend/src/components/v2/Button/DeleteConfirmButton.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/v1/common.ts
frontend/src/store/modules/v1/projectProtectionRoles.ts

https://github.com/bytebase/bytebase/assets/24653555/9a3882e3-05fd-4993-8817-c54b07e5c09c

feat(frontend): branch protection rules

---

frontend/src/composables/useDelayedValue.ts
frontend/src/utils/dom.ts
frontend/src/views/sql-editor/AsidePanel/DatabaseHoverPanel.vue
frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue
frontend/src/views/sql-editor/AsidePanel/hover-state.ts

Close BYT-4230
https://github.com/bytebase/bytebase/assets/2749742/72b1f8d6-88cb-42f5-837b-d2f53408af2b

feat(sql-editor): display database hover popover panel

---

frontend/src/components/EnvironmentForm/RolloutPolicyConfig.vue

'Dedicated roles' and 'last approver' now use radio buttons and cannot be checked simultaneously

chore(frontend): rollout policy configuration update

---

frontend/src/views/Changelist/ChangelistDetail/NavBar/export.ts

Exporting changes from change histories now won't fetch the change history entity. We use the statements stored in the change's sheet.
Close BYT-4273

chore(frontend): update export changelist logic 

---

frontend/src/components/CustomApproval/Settings/components/common/utils.ts

chore(frontend): remove level and source factors for request query and export type risk configuration

---

frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue

chore(schema-editor): update issue generation logic

---

frontend/src/views/Changelist/ChangelistDetail/ChangeTable/ChangeTable.vue
frontend/src/views/Changelist/ChangelistDetail/ChangelistDetail.vue
frontend/src/views/Changelist/ChangelistDetail/NavBar/ExportButton.vue

default to export all changes.
Close BYT-4274

chore(frontend): remove changelist selection to export

---

frontend/src/components/Project/ProjectGeneralSettingPanel.vue
frontend/src/components/Project/ProjectSidebar.vue
frontend/src/components/ProjectSettingPanel.vue
frontend/src/layouts/ProjectLayout.vue

* update some detail styles;
* use icons from lucide;
* sxpand project setting panel;

chore: update project sidebar

---

backend/plugin/vcs/util.go

Other VCS providers (e.g. GitHub/GitLab) list commits in the order in which they appeared, but in Azure DevOps, it's reverse totally. So that, we need to patch the previous fileChangeType from `Modified` to `Added` when we iterate commits list in positive order.

fix(Azure-DevOps): azure devops add and then modify cannot trigger create issue

---

frontend/src/views/DashboardHeader.vue

Switching language and debug mode is part of settings.

chore: clear top header for dev

---

frontend/src/components/Breadcrumb.vue
frontend/src/layouts/ProjectLayout.vue

1. Add batch mode icon to breadcrumb.
2. Remove project name from project layer since it's taking space and already showed in the breadcrumb.
Before: 
After:

chore: update project layout

---

frontend/src/components/ProfileDropdown.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/views/DashboardHeader.vue

chore: move license switch to profile dropdown

---

backend/migrator/migration/prod/2.10/0003##environment_rollout_policy.sql

otherwise violates NOT NULL constraint

fix: rollout policy default case

---

frontend/src/components/SyncDatabaseSchema/index.vue

Warning "Attribute ':disableProjectSelect' must be hyphenated" from https://github.com/bytebase/bytebase/pull/8902/files

fix: hyphenated the attribute

---

backend/plugin/advisor/mysqlwip/advisor_use_innodb.go
backend/plugin/advisor/mysqlwip/mysqlwip_rules_test.go
backend/plugin/advisor/mysqlwip/test/engine_mysql_use_innodb.yaml
backend/plugin/advisor/sql_review.go
backend/plugin/parser/mysql/normalize.go

migrate mysql `use_innodb` rule and its test.

chore: migrate mysql_use_innodb rule

---

backend/api/v1/common.go
backend/plugin/db/obo/obo.go
backend/plugin/db/obo/sync.go
frontend/src/components/InstanceForm/constants.ts
frontend/src/utils/v1/instance.ts

TODO: dump schema and frontend tweaks.

feat: add obo to instance list

---

backend/plugin/advisor/mysqlwip/advisor_naming_column.go
backend/plugin/advisor/mysqlwip/mysqlwip_rules_test.go
backend/plugin/advisor/mysqlwip/test/naming_column.yaml
backend/plugin/advisor/sql_review.go

I'll fix line number issue in https://github.com/bytebase/bytebase/pull/8907 and https://github.com/bytebase/bytebase/pull/8897 later.

chore: migrate column_naming rule

---

backend/plugin/advisor/mysqlwip/advisor_naming_table.go
backend/plugin/advisor/mysqlwip/test/naming_table.yaml

fix https://github.com/bytebase/bytebase/pull/8897

fix: add baseLine for each statement

---

backend/plugin/advisor/mysqlwip/advisor_use_innodb.go
backend/plugin/advisor/mysqlwip/test/engine_mysql_use_innodb.yaml

fix: https://github.com/bytebase/bytebase/pull/8907

fix: add baseLine for use_innodb rule

---

frontend/src/utils/v1/issue/rollout.ts

Should list the assignee candidates for the first stage when previewing issues.

chore(cicd): compatibility when previewing stage

---

backend/plugin/schema-engine/pg/structurer.go
backend/plugin/schema-engine/pg/testdata/get_design_schema.yaml

fix: correctly drop table in pg schema design

---

frontend/src/components/IssueV1/components/TaskRunSection/TaskRunComment.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

chore: update task run comment

---

frontend/src/components/InstanceForm/InstanceForm.vue
frontend/src/components/v2/Model/Instance/RichEngineName.vue
frontend/src/components/v2/Model/Instance/index.ts

chore: improve engine name display

---

backend/plugin/advisor/mysqlwip/advisor_stmt_no_select_all.go
backend/plugin/advisor/mysqlwip/test/statement_select_no_select_all.yaml

throw all error from the statements

chore: throw multi error

---

frontend/src/components/IssueV1/components/TaskRunSection/TaskRunTable.vue

chore: update execution time

---

frontend/src/types/sql-review-schema.yaml

feat: sql review rules for obo

---

frontend/src/components/IssueV1/components/TaskRunSection/TaskRunComment.vue
frontend/src/utils/v1/changeHistory.ts

fix(frontend): broken change history link when db name contains special chars

---

backend/api/v1/database_service.go
backend/api/v1/schema_design_service.go
backend/api/v1/sheet_service.go
frontend/src/components/IssueV1/logic/initialize/create.ts
frontend/src/components/SyncDatabaseSchema/index.vue
frontend/src/store/modules/v1/sheet.ts

Close BYT-4291
https://github.com/bytebase/bytebase/assets/24653555/57b77acf-79aa-439b-81a3-1a91661499f6

chore: initial database configs from branch sheet when creating issue

---

frontend/src/components/RepositoryPanel.vue
frontend/src/components/TroubleshootLink.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

chore: add troubleshoot link to project GitOps panel

---

frontend/src/components/IssueV1/components/BatchIssueActionsV1.vue
frontend/src/components/IssueV1/components/CurrentApproverV1.vue
frontend/src/components/IssueV1/components/IssueTableV1.vue

- Hide certain columns when horizontal space is limited
- Adjust column widths
- Use naive-ui components

chore(frontend): tuning issue-table styles

---

frontend/src/components/Issue/panel/RequestExportPanel/ExportResourceForm/DatabaseResourceSelector.vue
frontend/src/components/Issue/panel/RequestExportPanel/ExportResourceForm/Label.vue
frontend/src/components/Issue/panel/RequestQueryPanel/DatabaseResourceForm/DatabaseResourceSelector.vue
frontend/src/components/Issue/panel/RequestQueryPanel/DatabaseResourceForm/Label.vue

**Order**
- by `effectiveEnvironment.order` desc. Putting prod to the top.
- then by `effectiveEnvironment.title` asc
- then by `databaseName` asc
- then by `instance.title` asc
Close BYT-4260

chore(frontend): sort databases in tree

---

backend/api/v1/testdata/tidb/design.yaml

relat: https://github.com/bytebase/bytebase/pull/8975

chore: add tidb enum test

---

frontend/src/bbkit/BBAttention.vue

chore: fix eslint warning

---

backend/api/v1/rollout_service.go

feat: update task statement & earliest allowed time activities

---

frontend/src/components/IssueV1/components/ActivitySection/Activity/ActionSentence.vue

- i18n for "Updated rollout time from ... to ..."
- SQL content for "Update SQL from ... to ..."

chore(frontend): fix issue activity displaying

---

frontend/src/components/Branch/BranchDetailView.vue

https://github.com/bytebase/bytebase/assets/24653555/ed8ce431-6f28-4941-b9f8-fc7c6574b11a

chore: update apply change to databases

---

frontend/src/utils/v1/instance.ts

chore: re-order instance engine list

---

frontend/src/components/VCS/VCSProviderOAuthPanel.vue

chore(Bitbucket): add bitbucket oauth2 consumer permissions required by bytebase

---

frontend/src/components/DatabaseDetail/SQLEditorButtonV1.vue

chore(sql-editor-button): popup request query panel when permission denied

---

backend/plugin/advisor/code.go
backend/plugin/advisor/mysqlwip/advisor_naming_unique_key_convention.go
backend/plugin/advisor/mysqlwip/test/naming_index_uk.yaml

fix: https://github.com/bytebase/bytebase/pull/8957
we only check name  of unique key(index) with regular expression;

fix: cancel naming exists check

---

frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

chore: reword unassigned database hint

---

backend/api/lsp/completion.go
backend/api/lsp/handler.go

feat(LSP): implement hello-world for completion

---

frontend/src/components/SchemaTemplate/FieldTemplateForm.vue
frontend/src/components/SchemaTemplate/FieldTemplateTable.vue
frontend/src/components/SchemaTemplate/TableTemplateForm.vue
frontend/src/components/SchemaTemplate/TableTemplateTable.vue
frontend/src/views/SchemaTemplate/FieldTemplates.vue
frontend/src/views/SchemaTemplate/TableTemplates.vue

chore: use userComment instead of comment in schema templates

---

backend/api/gitops/webhook.go
backend/plugin/vcs/azure/azure.go

fix(azure-devops): azure devops rename file should trigger issue

---

frontend/vite.config.ts

Missed in https://github.com/bytebase/bytebase/pull/9054

chore: use the shared LOCAL_ENDPOINT variable

---

frontend/src/layouts/BodyLayout.vue
frontend/src/router/index.ts
frontend/src/views/SettingSidebar.vue

chore: move archive from sidebar to setting tab

---

frontend/src/components/RepositoryPanel.vue

fix: format repo url for azure

---

frontend/src/store/modules/v1/dbSchema.ts

1) the column will not show the correct effective masking level till we apply filter on showing the table schema info.
2) we will work on performance (basic view for most general cases) later.

chore: use full view for now

---

frontend/src/components/IssueV1/components/DescriptionSection/DescriptionSection.vue
frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue
frontend/src/components/IssueV1/components/HeaderSection/Assignee/Assignee.vue
frontend/src/components/IssueV1/components/HeaderSection/Title.vue
frontend/src/components/IssueV1/components/StageSection/Actions/EarliestAllowedTime.vue
frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
frontend/src/plugins/index.ts
frontend/src/plugins/window-events.ts

feat(frontend): emit window events

---

frontend/src/App.vue
frontend/src/bbkit/BBNotification.vue
frontend/src/bbkit/types.ts
frontend/src/components/ActivityTable/ActivityTypeLink.vue
frontend/src/components/ActivityTable/utils.ts
frontend/src/components/AuditLog/AuditLogTable.vue
frontend/src/components/Project/ProjectSidebar.vue
frontend/src/store/modules/v1/common.ts
frontend/src/store/modules/v1/project.ts
frontend/src/types/activity.ts
frontend/src/types/notification.ts
frontend/src/views/ProjectDetail.vue

- Cache the last viewed page in the project detail
- Show notification for the last activity on the project detail page
Close BYT-4320

chore: cache last viewed page & show activity notification

---

frontend/src/views/DashboardHeader.vue

The current issue page primarily serves as an advanced issue dashboard and is infrequently utilized by first-time users. Additionally, users can access this page through both the 'My Issue' and 'Project Issue' dashboards.

chore: remove issue header

---

frontend/src/components/v2/Form/PhoneNumberInput.vue

chore: update default country code

---

frontend/src/store/modules/v1/projectIamPolicy.ts
frontend/src/views/ExportCenter/index.vue

fix: skip cache in export center

---

frontend/naive-ui.config.ts
frontend/src/CustomThemeProvider.vue
frontend/src/utils/customTheme.ts
frontend/src/views/sql-editor/AsidePanel/GroupingBar/FactorTag.vue
frontend/src/views/sql-editor/AsidePanel/GroupingBar/GroupingBar.vue

This is weird but it works.
Close BYT-4337

fix(sql-editor): infinite re-evaluations of getCustomProjectTitle when customTheme is not empty

---

go.mod
go.sum

chore: upgrade antlr for performance

---

backend/plugin/parser/base/complete.go
backend/plugin/parser/base/interface.go
backend/plugin/parser/base/scanner.go

chore: introduce completion framework

---

backend/resources/postgres/sample_instance.go
backend/server/onboard.go
backend/server/server.go
scripts/.air.toml

To create better demo. Also reduce logging generated by sample instance

feat: add hr_prod_[1~6] to sample instance in demo mode

---

frontend/src/views/ProjectDetail.vue

Also, link to the activities page.

chore: only pop up for repo push activity

---

frontend/src/components/BytebaseLogo.vue
frontend/src/views/ProjectDetail.vue

We can fetch the activities by action and limit last 1 activity

chore: update the pop notification in project page

---

backend/api/v1/database_service.go
frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
frontend/src/components/AlterSchemaPrepForm/SchemaEditorSQLCheckButton/useSchemaEditorSQLCheck.ts
frontend/src/components/Branch/BaselineSchemaSelector.vue
frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/form/ChangeHistoryForm.vue
frontend/src/components/DatabaseChangeHistoryPanel.vue
frontend/src/components/DatabaseOverviewPanel.vue
frontend/src/components/Issue/panel/RequestExportPanel/ExportResourceForm/DatabaseResourceSelector.vue
frontend/src/components/Issue/panel/RequestQueryPanel/DatabaseResourceForm/DatabaseResourceSelector.vue
frontend/src/components/IssueV1/components/StatementSection/EditorView/useEditorAutoCompletion.ts
frontend/src/components/SchemaEditorV1/utils/database.ts
frontend/src/components/SensitiveData/SensitiveColumnDrawer.vue
frontend/src/components/SyncDatabaseSchema/DatabaseSchemaSelector.vue
frontend/src/components/TableDetailDrawer.vue
frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
frontend/src/router/index.ts
frontend/src/store/modules/v1/dbSchema.ts
frontend/src/views/ChangeHistoryDetail.vue
frontend/src/views/DatabaseDetail.vue
frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue
frontend/src/views/sql-editor/AsidePanel/common.ts
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/SchemaPanel.vue
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/TableSchema.vue

- SQL editor
- Database detail page

chore: migrate part code to getMedata wit filter

---

frontend/src/components/IssueV1/logic/plan-check.ts
frontend/src/components/IssueV1/logic/plan.ts

FYI @RainbowDashy 
Close BYT-4355

chore(frontend): filter planCheckRun with `target` and `sheet` combination

---

frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue

fix: cannot check database

---

frontend/src/views/sql-editor/AsidePanel/DatabaseHoverPanel.vue
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/ColumnList.vue
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/DatabaseSchema.vue
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/HoverPanel/ColumnInfo.vue
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/HoverPanel/HoverPanel.vue
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/HoverPanel/InfoItem.vue
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/HoverPanel/TableInfo.vue
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/HoverPanel/hover-state.ts
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/HoverPanel/index.ts
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/SchemaPanel.vue
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/TableList.vue
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/TableSchema.vue

Similar to #8860 
https://github.com/bytebase/bytebase/assets/2749742/bd68556f-b498-4715-b940-39f02d08a8f7
Video recorded with 1280x800 resolution
Some items are not displayed since they are not included in `DATABASE_METADATA_VIEW_BASIC` and it's too expensive to load those data.
- Table classification config 
- Column masking level
- Column semantic type
- Column labels
Close BYT-4210

feat(sql-editor): table and column info hover popover panel

---

backend/demo/data/next3/dump.sql
backend/resources/postgres/sample_instance.go

next3 contains more comprehensive Bytebase features to be used for demo
* GitOps
* Batch
* Data classification
* Schema template
* Custom approval
* Data masking

feat: add sample hr_prod_vcs db and next3 demo data

---

backend/api/v1/logging_service.go
frontend/src/views/ProjectDetail.vue

Also fixed a bug in listing logs. Previously, we don't respect the action filter if specified.

chore: show push notification only for issue creator and owners

---

frontend/src/components/CustomApproval/Settings/components/CustomApproval/FlowsPanel/FlowTable.vue
frontend/src/components/Role/Setting/components/RoleTableRow.vue
frontend/src/components/SystemLabel.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

feat: add system label to system objects

---

frontend/src/types/sql-review-schema.yaml

fix(frontend): add mariadb to sql_review_schema.yaml

---

backend/demo/demo.go
backend/server/server.go

So the demo file can be used in release mode as well.

chore: in release mode, replace demo dump owner “bbdev” with “bb”

---

frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckDetail.vue
frontend/src/components/SQLCheck/SQLCheckDetail.vue
frontend/src/components/SQLReview/components/RuleConfigComponents/BooleanComponent.vue
frontend/src/components/SQLReview/components/RuleConfigComponents/NumberComponent.vue
frontend/src/components/SQLReview/components/RuleConfigComponents/StringComponent.vue
frontend/src/components/SQLReview/components/RuleConfigComponents/TemplateComponent.vue
frontend/src/components/SQLReview/components/RuleLevelSwitch.vue
frontend/src/components/SQLReview/components/SQLRuleEditDialog.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/types/sql-review-schema.yaml

chore: readonly rule dialog

---

frontend/src/components/Changelist/ChangelistDetail/ApplyToDatabasePanel/ApplyToDatabasePanel.vue

chore(frontend): applying changelist to database should fallback to DDL instead of DML

---

frontend/src/components/CustomApproval/Settings/components/common/utils.ts
frontend/src/components/SensitiveData/components/utils.ts

chore(frontend): use dropdowns for project_id in rule expr editors

---

frontend/src/components/InstanceAssignment.vue

Add tooltips for the instance address

fix: long instance address

---

frontend/src/views/IssueDashboard.vue

chore: update issue page style

---

backend/api/v1/sql_service.go

A member can have multiple exceptions.

fix(masking): do not break early in finding masking exception

---

frontend/src/components/FeatureGuard/FeatureBadgeForInstanceLicense.vue
frontend/src/components/IssueV1/components/StageSection/Actions/GhostSection/GhostSection.vue
frontend/src/components/IssueV1/components/StageSection/Actions/GhostSection/GhostSwitch.vue
frontend/src/components/IssueV1/components/StageSection/Actions/GhostSection/common.ts

chore(frontend): feature guard for gh-ost

---

backend/plugin/parser/base/c3.go
backend/plugin/parser/base/complete.go
backend/plugin/parser/base/interface.go
backend/plugin/parser/mysql/completion.go
backend/plugin/parser/mysql/completion_test.go
backend/plugin/parser/mysql/test-data/test_completion.yaml
backend/store/model/database.go

feat(completion): implement basic MySQL completion

---

frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

https://docs.gitlab.com/ee/user/project/issues/managing_issues.html#assignee
The following i18n are kept since the code will be updated later for selecting assignees.
- no-assignee-candidates
- allow-any-following-roles-to-be-assignee

chore: reword assignee description

---

frontend/src/layouts/DashboardLayout.vue
frontend/src/layouts/SQLEditorLayout.vue

chore: remove page loading text

---

frontend/src/components/IssueV1/components/HeaderSection/Assignee/Assignee.vue
frontend/src/components/IssueV1/logic/assignee.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

Allow any project members and workspace owner/DBA to be assignee candidates. Project owners are the top candidates. We will make assignee optional later.

chore: update issue assignee candidate

---

backend/api/lsp/completion.go
backend/api/lsp/handler.go
backend/api/lsp/lsp.go
backend/plugin/parser/base/interface.go
backend/plugin/parser/mysql/completion.go
backend/plugin/parser/mysql/completion_test.go

Leave ACL filter for following PR.
close BYT-3953

feat(LSP): implement completion for LSP

---

frontend/src/components/DatabaseDetail/SQLEditorButtonV1.vue
frontend/src/components/HelpDrawer/HelpDrawer.vue
frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
frontend/src/components/v2/Model/DatabaseV1Table/DatabaseTableRow.vue
frontend/src/layouts/SQLEditorLayout.vue
frontend/src/store/modules/v1/actuator.ts
frontend/src/views/DatabaseDashboard.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
frontend/src/views/sql-editor/EditorPanel/EditorPanel.vue
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/DatabaseSchema.vue
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/TableSchema.vue

chore: always show database operation in standalone mode

---

frontend/src/components/DataExportButton.vue
frontend/src/components/IssueV1/components/StageSection/Actions/GhostSection/common.ts
frontend/src/components/v2/Button/ErrorTipsButton.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue

feat(sql-editor): allow specify row count for exports from sql editor

---

backend/plugin/parser/mysql/completion.go
backend/plugin/parser/mysql/completion_test.go
backend/plugin/parser/mysql/test-data/test_completion.yaml
backend/store/model/database.go

feat(completion): support MySQL views

---

frontend/src/types/sql-review-schema.yaml

chore: enable tidb dry run review

---

backend/plugin/advisor/mysqlwip/advisor_statement_affected_row_limit.go
backend/plugin/advisor/mysqlwip/mysqlwip_rules_test.go
backend/plugin/advisor/mysqlwip/test/statement_affected_row_limit.yaml
backend/plugin/advisor/sql_review.go

this pr still need more live tests. mark it as draft now.

chore: migrate statement_affected_row_limit

---

frontend/vite.config.ts

dev only
Special thanks to @RainbowDashy and @rebelice

chore(frontend): fix ws proxy path for dev mode

---

frontend/src/components/IssueV1/components/StageSection/StageInfo/DatabaseInfo.vue

The issue may happen when AFTER a create DB issue is done and BEFORE the page is refreshed.
Close BYT-4375

chore(frontend): link to just-in-time created db

---

backend/api/lsp/handler.go

chore(LSP): add panic recover for LSP server

---

backend/api/lsp/completion.go

chore(LSP): log database error for LSP

---

frontend/src/router/index.ts
frontend/src/utils/role.ts
frontend/src/views/DashboardHeader.vue
frontend/src/views/SettingSidebar.vue

chore: setting page guard

---

frontend/src/components/IssueV1/components/HeaderSection/Actions/common/IssueStatusActionButtonGroup/IssueStatusActionButtonGroup.vue
frontend/src/components/IssueV1/components/HeaderSection/Actions/review/IssueReviewButtonGroup.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

Only to workspace owners and DBAs for emergency use.
Close BYT-4329

feat(frontend): allow workspace owners and DBAs to force rollout

---

frontend/src/views/SchemaTemplate/ColumnTypes.vue

fix: column type restriction checks

---

backend/api/v1/auth_service.go
frontend/src/components/InboxList.vue
frontend/src/components/Issue/activity/ActionCreator.vue
frontend/src/components/IssueV1/components/ActivitySection/Activity/ActionCreator.vue
frontend/src/components/IssueV1/components/HeaderSection/Description.vue
frontend/src/components/ProjectMember/ProjectMemberTable/ProjectMemberTable.vue
frontend/src/components/SensitiveData/SensitiveColumnDrawer.vue
frontend/src/components/User/Settings/UserTable.vue
frontend/src/components/v2/Model/User/UserByEmail.vue
frontend/src/router/index.ts
frontend/src/store/modules/router.ts
frontend/src/types/common.ts
frontend/src/types/proto/v1/auth_service.ts
proto/gen/grpc-doc/v1/README.md
proto/generated-go/v1/auth_service.pb.go
proto/v1/auth_service.proto

**BROKEN CHANGE**
Deprecate the `/u/{uid}`, use `/users/{email}` instead.

chore: change user page link

---

backend/plugin/db/mysql/rollback.go
backend/plugin/db/mysql/rollback_test.go

fix: rollback sql NULL-safe equal op

---

go.mod
go.sum

fix: fix plsql parser for MODIFY PARTITION

---

frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
frontend/src/components/AlterSchemaPrepForm/ProjectStandardView.vue
frontend/src/components/ChangeHistory/ChangeHistoryTable.vue
frontend/src/components/DatabasesSelectPanel.vue
frontend/src/components/ExprEditor/components/MultiSelect.vue
frontend/src/components/InstanceAssignment.vue
frontend/src/components/IssueV1/components/IssueTableV1.vue
frontend/src/components/ProjectDatabasesPanel.vue
frontend/src/components/ProjectMember/ProjectMemberPanel.vue
frontend/src/components/SensitiveData/components/MaskingAlgorithmsCreateDrawer.vue
frontend/src/components/SensitiveData/components/MaskingAlgorithmsTable.vue
frontend/src/components/SensitiveData/components/SensitiveColumnTable.vue
frontend/src/components/SyncDatabaseSchema/TargetDatabasesSelectPanel.vue
frontend/src/components/TransferDatabaseForm/TransferMultipleDatabaseForm.vue
frontend/src/components/v2/Model/Instance/InstanceV1Table/InstanceV1Table.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/v1/dbSchema.ts
frontend/src/views/DatabaseDashboard.vue

- Partly close BYT-4421 (frontend part)
- Close BYT-4415
- Close BYT-4420
- Close BYT-4414

chore: several fix for data masking

---

frontend/src/views/IssueDashboard.vue

Before: was surprisingly confusing.

chore: remove project key button

---

backend/api/v1/setting_service.go
frontend/src/components/SensitiveData/components/MaskingAlgorithmsCreateDrawer.vue

chore: check slice overlap

---

backend/store/task.go

Move `COALESCE` into the join so that we don't have to do so twice on the outside.

chore: simplify task latest task run

---

backend/store/database_group.go
backend/store/store.go
backend/store/vcs.go

Also fixed some bugs for invalid keys.

chore: migrate cache (part 2)

---

backend/plugin/advisor/mysqlwip/advisor_colum_require_default.go
backend/plugin/advisor/mysqlwip/advisor_column_comment_convention.go
backend/plugin/advisor/mysqlwip/advisor_column_required.go
backend/plugin/advisor/mysqlwip/advisor_column_set_default_for_not_null.go
backend/plugin/advisor/mysqlwip/advisor_column_type_restriction.go
backend/plugin/advisor/mysqlwip/test/column_comment.yaml
backend/plugin/advisor/mysqlwip/test/column_require_default.yaml
backend/plugin/advisor/mysqlwip/test/column_required.yaml
backend/plugin/advisor/mysqlwip/test/column_set_default_for_not_null.yaml

I forget to consider this situation for some rules.
> ALTER TABLE t1 ADD COLUMN (c1 INT, c2 INT)

fix: handle multi columns when adding column

---

frontend/src/components/Branch/BranchCreateView.vue

Extract the `title` from state might help with sluggish problem.

chore: use ref instead of state for branch title

---

backend/api/gitops/webhook.go
backend/api/v1/sql_service.go
backend/runner/plancheck/statement_advise_executor.go

chore(sql-review): use admin driver instead of read only driver

---

frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/TableCell.vue

chore: add whitespace-pre to table cell

---

frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/TableCell.vue

chore: add font-mono to table cell

---

backend/plugin/db/pg/sync.go

close BYT-4220
for partitions
for multi-level partitions
Need to change the frontend display.

feat: implement sync partitions for postgres

---

frontend/src/views/sql-editor/SecondarySidebar/SheetTabPane/SheetList/SheetItem.vue
frontend/src/views/sql-editor/SecondarySidebar/SheetTabPane/SheetList/TabItem.vue

chore: add tooltip to sheet item

---

frontend/src/components/CreateDatabasePrepForm/CreateDatabasePrepForm.vue
frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue
frontend/src/components/IssueV1/components/HeaderSection/Assignee/Assignee.vue

chore(frontend): make assignee optional

---

frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
frontend/src/components/Branch/BranchDetailView.vue
frontend/src/components/ColumnTable.vue
frontend/src/components/SchemaEditorV1/Panels/TableColumnEditor.vue
frontend/src/components/SchemaEditorV1/Panels/TableList.vue
frontend/src/components/TableTable.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/views/SettingWorkspaceSensitiveData.vue

- Database config must changed with the schema
- Remove `isDev` guard

chore: database config must changed with the schema

---

backend/server/onboard.go

fix: onboard data

---

frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/components/ProvideSQLEditorContext.vue
frontend/src/composables/useExecuteSQL.ts
frontend/src/store/modules/sqlEditor.ts
frontend/src/store/modules/tab.ts
frontend/src/types/sql.ts
frontend/src/types/tab.ts
frontend/src/views/sql-editor/EditorCommon/EditorAction.vue
frontend/src/views/sql-editor/EditorCommon/QueryContextSettingPopover.vue

https://github.com/bytebase/bytebase/assets/24653555/88e6d4e9-478f-463b-a58c-86eafeeab5b6

feat: allow set data source in sql editor

---

backend/plugin/db/dm/dm.go
backend/plugin/db/obo/obo.go
backend/plugin/db/oracle/oracle.go
backend/plugin/parser/plsql/split.go

fix: support running oracle procedures

---

frontend/src/components/ProvideSQLEditorContext.vue
frontend/src/store/modules/v1/projectIamPolicy.ts
frontend/src/utils/v1/database.ts
frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/TableCell.vue

* Add loading flag in `ProvideSQLEditorContext.vue`;
* Enhance the selected font weight of tree nodes;
* Fix `allUsers` checks in IAM policy;

chore: fix sql editor issues

---

frontend/src/components/SyncDatabaseSchema/DatabaseSchemaSelector.vue

chore(frontend): refactor schema version select to naive-ui

---

frontend/src/components/Branch/BaselineSchemaSelector.vue
frontend/src/components/SyncDatabaseSchema/DatabaseSchemaSelector.vue
frontend/src/utils/v1/changeHistory.ts
frontend/src/views/branch/BranchDetail.vue

- Before
- After
See also: #9356

chore(frontend): use naive-ui select in baseline schema selector

---

frontend/src/components/SchemaTemplate/ClassificationLevelBadge.vue
frontend/src/components/SchemaTemplate/SelectClassificationDrawer.vue

fix: add missing level badge

---

frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue

fix: fix batch project deployment config link

---

frontend/src/views/sql-editor/ResultPanel/ResultPanel.vue

chore: add close button in single query result view

---

backend/runner/taskrun/schedulerv2.go

fix: data race

---

frontend/src/components/ProvideSQLEditorContext.vue

It will show an empty database list.

chore(sql-editor): use unknown project when project not found

---

backend/store/model/database.go

Masking requires finding the column semantic type id in constant time complexity.

feat(model): add config internal in model.DBSchema

---

frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/form/ChangeHistoryForm.vue

chore: filter failed change history for changelist

---

frontend/src/components/v2/Model/DatabaseV1Table/DatabaseGroupTableRow.vue
frontend/src/components/v2/Model/DatabaseV1Table/DatabaseV1Table.vue

Should close BYT-4478 (hopefully)
FYI @RainbowDashy  plz test

chore(frontend): don't call allowQuery on DatabaseGroup

---

frontend/src/components/IssueV1/logic/plan-check.ts

In planCheckRunSummaryForIssue
1. filter out plan checks with sheets that are not used anymore.
2. group plan checks by (type, target, sheet)
3. get the latest one from each group

fix: plan check runs group by type target sheet

---

frontend/src/components/SQLCheck/SQLCheckDetail.vue

fix: add definition link and panel for pre check

---

backend/plugin/parser/mysql/completion.go
backend/plugin/parser/mysql/test-data/test_completion.yaml
go.mod
go.sum

feat: add mysql function lists

---

frontend/src/components/ProjectMember/AddProjectMember/AddProjectMemberForm.vue
frontend/src/store/modules/v1/subscription.ts

Also uses the localized time format.

chore: don't add condition title if the role has no condition

---

backend/api/v1/sql_service.go
backend/common/error.go
backend/common/util.go
backend/runner/plancheck/statement_advise_executor.go
backend/runner/plancheck/statement_report_executor.go
backend/runner/plancheck/statement_type_executor.go
frontend/src/components/SQLCheck/SQLCheckButton.vue

Show check warning for large SQL.

chore: consolidate check size and show check warning for large SQL

---

backend/runner/approval/runner.go

Reverts bytebase/bytebase#9415

chore: Revert "refactor: refactor risk evaluator"

---

frontend/src/components/SchemaEditorV1/Panels/TableColumnEditor/TableColumnEditor.vue
frontend/src/components/SchemaEditorV1/Panels/TableColumnEditor/components/OperationCell.vue
frontend/src/components/SchemaEditorV1/Panels/TableList/TableList.vue
frontend/src/components/SchemaEditorV1/Panels/TableList/components/OperationCell.vue

Some things left behind #9423. Pardon me plz

fix(frontend): dropped icon

---

backend/api/v1/sql_service.go
backend/api/v1/sql_service_v2.go

feat(span): switch to use query span for PostgreSQL in Export

---

frontend/src/components/Branch/BranchCreateView.vue
frontend/src/components/DatabaseDetail/SQLEditorButtonV1.vue
frontend/src/components/SchemaEditorV1/Aside/BranchTree.vue
frontend/src/components/SchemaEditorV1/Aside/DatabaseTree.vue
frontend/src/components/SchemaEditorV1/Panels/TableColumnEditor/TableColumnEditor.vue
frontend/src/components/SchemaEditorV1/Panels/TableList/TableList.vue
frontend/src/components/SchemaEditorV1/Panels/TableList/components/NameCell.vue
frontend/src/components/SchemaEditorV1/index.vue
frontend/src/components/SchemaEditorV1/utils/metadata.ts
frontend/src/components/misc/MaskSpinner.vue
frontend/src/types/v1/schemaEditor/atomType.ts
frontend/src/utils/dom.ts

Works with 2k tables or 1k columns. Will be laggy but won't freeze or kill the browser.
https://github.com/bytebase/bytebase/assets/2749742/0076a688-31bb-4d9c-b416-ddd1ef8a60c5

chore(frontend): schema editor speed-up and loading indicators

---

backend/plugin/advisor/catalog/test/mysqlv2_walk_through.yaml
backend/plugin/advisor/catalog/walk_through_for_mysql_v2.go
backend/plugin/parser/mysql/normalize.go

1. support check create table ... select
2. support check auto_increment
3. support create table ... like

chore: improve create table

---

backend/plugin/advisor/catalog/test/mysqlv2_walk_through.yaml
backend/plugin/advisor/catalog/walk_through_for_mysql_v2.go

1. alter table add column statement.
2. alter table drop column statements.
3. alter table modify column statements.
4. alter table change column statements.
4. alter table rename column statements.
5. alter table alter column statements.

chore(mysqlv2): walk through alter table column

---

frontend/src/components/Breadcrumb.vue
frontend/src/components/Project/ProjectSidebar.vue
frontend/src/router/index.ts

Database detail page
Change history detail page

chore: change sidebar for database and change history detail page

---

frontend/src/components/SchemaTemplate/TableTemplateForm.vue

Should be backported to 2.11.1 FYI @d-bytebase

chore(frontend): fix wrong event name

---

frontend/src/store/modules/v1/activity.ts

chore(frontend): comment activity pagesize

---

backend/plugin/advisor/catalog/test/mysqlv2_walk_through.yaml
backend/plugin/advisor/catalog/walk_through_for_mysql_v2.go

1. alter table add index.
2. alter table drop primary.
3. alter table drop index
4. alter table alter index visibility.
5. alter table rename index.
6. alter table rename table.

chore(mysqlv2): support alter index

---

frontend/src/components/Icon/TableIcon.vue
frontend/src/components/Icon/ViewIcon.vue
frontend/src/components/Icon/index.ts
frontend/src/store/modules/sqlEditorTree.ts
frontend/src/types/sqlEditorTree.ts
frontend/src/views/sql-editor/AsidePanel/TreeNode/Label.vue
frontend/src/views/sql-editor/AsidePanel/TreeNode/TextNode.vue
frontend/src/views/sql-editor/AsidePanel/TreeNode/ViewNode.vue
frontend/src/views/sql-editor/AsidePanel/common.ts
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/HoverPanel/HoverPanel.vue
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/HoverPanel/ViewInfo.vue
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/HoverPanel/hover-state.ts
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/TableList.vue

feat(sql-editor): display views in SQL Editor

---

backend/demo/data/next/README.md
backend/demo/data/next/dump.sql

chore: add semantic type and masking algo to demo

---

frontend/src/components/SchemaEditorV1/Panels/TableColumnEditor/TableColumnEditor.vue
frontend/src/components/SchemaTemplate/FieldTemplateForm.vue
frontend/src/components/SchemaTemplate/FieldTemplateTable.vue
frontend/src/components/SchemaTemplate/FieldTemplateView.vue
frontend/src/components/SchemaTemplate/TableTemplateForm.vue
frontend/src/components/SchemaTemplate/TableTemplateTable.vue
frontend/src/components/SchemaTemplate/TableTemplateView.vue
frontend/src/components/SchemaTemplate/utils.ts
frontend/src/components/misc/NoData.vue
frontend/src/components/v2/Form/DropdownInput.vue
frontend/src/views/SchemaTemplate/FieldTemplates.vue
frontend/src/views/SchemaTemplate/TableTemplates.vue

chore(frontend): settings -> schema template using naive-ui

---

backend/plugin/advisor/catalog/test/mysqlv2_walk_through.yaml
backend/plugin/advisor/catalog/walk_through_for_mysql_v2.go

Now, we only support following create_table_opions:
- Engine
- Collation
- Comment

chore(mysqlv2): support create table options

---

frontend/src/components/InstanceForm/InstanceForm.vue
frontend/src/components/SchemaTemplate/FieldTemplateForm.vue
frontend/src/components/SchemaTemplate/TableTemplateForm.vue
frontend/src/components/SensitiveData/components/MaskingAlgorithmsCreateDrawer.vue
frontend/src/components/v2/Form/RadioGrid.vue
frontend/src/components/v2/Form/index.ts
frontend/src/components/v2/Form/types.ts
frontend/src/components/v2/Model/Instance/InstanceEngineRadioGrid.vue
frontend/src/components/v2/Model/Instance/index.ts

refactor(frontend): extract RadioGrid component

---

frontend/src/components/ColumnDataTable/index.vue
frontend/src/components/DatabaseOverviewPanel.vue
frontend/src/components/TableDataTable.vue
frontend/src/components/TableDetailDrawer.vue

chore: add search box to table/column data table

---

frontend/src/components/LearnMoreLink.vue
frontend/src/components/SensitiveData/GlobalMaskingRulesView.vue
frontend/src/components/SensitiveData/GrantAccessDrawer.vue
frontend/src/components/SensitiveData/MaskingAlgorithmsView.vue
frontend/src/components/SensitiveData/SemanticTypesView.vue
frontend/src/components/SensitiveData/SensitiveColumnDrawer.vue
frontend/src/components/SensitiveData/SensitiveColumnView.vue
frontend/src/components/SensitiveData/components/MaskingAlgorithmsCreateDrawer.vue
frontend/src/components/SensitiveData/components/MaskingAlgorithmsTable.vue
frontend/src/components/SensitiveData/components/MaskingLevelDropdown.vue
frontend/src/components/SensitiveData/components/MaskingLevelRadioGroup.vue
frontend/src/components/SensitiveData/components/MaskingRuleConfig.vue
frontend/src/components/SensitiveData/components/SemanticTemplateDrawer.vue
frontend/src/components/SensitiveData/components/SemanticTypesDrawer.vue
frontend/src/components/SensitiveData/components/SemanticTypesTable.vue
frontend/src/components/SensitiveData/components/SensitiveColumnTable.vue

chore(frontend): consolidate data masking settings UI to naive-ui

---

frontend/src/components/Project/ProjectIssuesPanel.vue
frontend/src/views/Home.vue

@adela-bytebase this may help but I'm still not sure about that.
plz try later after the docker image is updated.

chore(frontend): issue search bar robustness

---

backend/plugin/advisor/catalog/test/mysqlv2_walk_through.yaml
backend/plugin/advisor/catalog/walk_through_for_mysql_v2.go
backend/plugin/parser/mysql/normalize.go

1. create database.
2. drop database
3. alter database(only charset change and collation change)

chore(mysqlv2): support statements about database

---

frontend/src/components/Project/ProjectSidebar.vue

chore(frontend): dedupe unnecessary issue creation requests

---

frontend/src/components/SchemaTemplate/ClassificationLevelBadge.vue
frontend/src/components/SchemaTemplate/FieldTemplateTable.vue
frontend/src/components/SchemaTemplate/TableTemplateTable.vue
frontend/src/components/SensitiveData/SensitiveColumnDrawer.vue
frontend/src/components/SensitiveData/components/MaskingAlgorithmsTable.vue
frontend/src/components/SensitiveData/components/SemanticTypesTable.vue
frontend/src/components/SensitiveData/components/SensitiveColumnTable.vue
frontend/src/components/v2/Model/DatabaseV1Table/DatabaseV1Table.vue
frontend/src/components/v2/Model/DatabaseV1Table/ProjectCol.vue
frontend/src/components/v2/Model/Instance/InstanceV1Table/InstanceV1Table.vue
frontend/src/components/v2/Model/ProjectV1Name.vue
frontend/src/components/v2/Model/ProjectV1Table.vue
frontend/src/views/DatabaseDashboard.vue
frontend/src/views/SettingWorkspaceSubscription.vue

For example, for the database table,

chore: update table ui

---

frontend/src/components/v2/Form/SearchBox.vue
frontend/src/views/sql-editor/EditorCommon/BatchQueryDatabasesSelector.vue

* update column name to `Database`;
* add `Labels` column;

chore: update batch query database table

---

backend/plugin/db/mongodb/mongodb.go
backend/server/minimal.go
backend/server/ultimate.go

Don't ask me why. Wish you good luck never touching this again.

fix: sleepy mongo needs some rest

---

frontend/src/locales/zh-CN.json

For Chinese users, it would be better to have a subject.

chore: reword some archive description

---

frontend/src/views/sql-editor/EditorCommon/BatchQueryDatabasesSelector.vue
frontend/src/views/sql-editor/EditorCommon/QueryContextSettingPopover.vue

chore: add connection info popover to data source selector

---

backend/plugin/advisor/catalog/test/mysqlv2_walk_through.yaml
backend/plugin/advisor/catalog/walk_through_for_mysql_v2.go

1. fix create index statement for unique index.
2. add more accurate line number in error info.

fix: mysqlv2 create index

---

frontend/src/components/EnvironmentForm.vue
frontend/src/components/EnvironmentForm/RolloutPolicyConfig.vue
frontend/src/components/v2/Form/Switch.vue
frontend/src/components/v2/Form/index.ts
frontend/src/views/EnvironmentDashboard.vue
frontend/src/views/EnvironmentDetail.vue

- Use naive-ui components if possible
- consistent section gaps

chore(frontend): use naive-ui in environment page

---

frontend/src/components/Breadcrumb.vue
frontend/src/layouts/BodyLayout.vue
frontend/src/views/DashboardHeader.vue
frontend/src/views/DashboardSidebar.vue

chore: refactor header and sidebar

---

backend/api/v1/sql_service_v2.go
backend/plugin/parser/base/interface.go
backend/plugin/parser/errors/resources.go
backend/plugin/parser/pg/v2/query_span_extractor.go

chore(span): refine error message if table not found

---

frontend/src/components/AlterSchemaPrepForm/DatabaseGroupPrevEditorModal.vue

chore(frontend): remove comments from group change sql template

---

frontend/src/bbkit/BBModal.vue
frontend/src/components/AlterSchemaPrepForm/DatabaseGroupPrevEditorModal.vue
frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
frontend/src/components/DatabaseGroup/DatabaseGroupForm.vue
frontend/src/components/DatabaseGroup/DatabaseGroupSelect.vue
frontend/src/components/DatabaseGroup/ProjectDatabaseGroupPanel.vue
frontend/src/components/SchemaEditorV1/Modals/ActionConfirmModal.vue
frontend/src/components/v2/Select/EnvironmentSelect.vue
frontend/src/views/DatabaseGroupDetail.vue
frontend/src/views/ProfileDashboard.vue

chore(frontend): consolidate database group UI to naive-ui

---

frontend/src/components/ProvideDashboardContext.vue
frontend/src/components/ProvideSQLEditorContext.vue
frontend/src/main.ts
frontend/src/store/modules/utils.ts

optimize the initialization order to reduce race conditions caused by data dependencies.

chore(frontend): optimize base store initialization order

---

backend/api/v1/rollout_service_converter.go
backend/plugin/db/driver.go
backend/plugin/db/mysql/mysql.go
backend/runner/taskrun/schedulerv2.go
frontend/src/components/IssueV1/components/TaskRunSection/TaskRunComment.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

feat: display position information for execution error

---

frontend/src/components/KBar/KBarWrapper.vue
frontend/src/components/KBar/useDatabaseActions.ts
frontend/src/components/KBar/utils.ts
frontend/src/components/Project/ProjectSidebar.vue
frontend/src/views/DashboardHeader.vue
frontend/src/views/DashboardSidebar.vue

- Pages with default sidebar and pages with project sidebar now have different kbar actions respectively
- Different navigation actions
- Database actions filtered by the project

refactor(frontend): refactor kbar actions

---

backend/api/v1/instance_service.go
backend/store/instance.go
scripts/.air.toml

Find all instances that have databases in the given project.

chore: support instance project filter

---

backend/api/v1/acl.go
backend/api/v1/acl_config.go

chore: use full method name in grpc middleware

---

frontend/src/components/v2/Select/UserSelect.vue

chore: close the dropdown when user selected in multi-selection

---

frontend/src/components/Issue/panel/RequestExportPanel/index.vue
frontend/src/components/Issue/panel/RequestQueryPanel/index.vue
frontend/src/components/TransferDatabaseForm/TransferSingleDatabase.vue
frontend/src/components/TransferDatabaseForm/TransferSourceSelector.vue
frontend/src/components/TransferOutDatabaseForm/TransferOutDatabaseForm.vue
frontend/src/components/v2/Select/ProjectSelect.vue

chore: add allowed project role list to request privilege

---

scripts/check_link_test.go

fix: https://github.com/bytebase/bytebase/pull/9544

fix: close reponse body

---

frontend/src/utils/v1/project.ts
frontend/src/views/ProjectDashboard.vue
frontend/src/views/SettingWorkspaceAccessControl.vue

* remove user's role checks in project dashboard;

chore: fix project dashboard filter

---

frontend/src/grpcweb/middlewares/authInterceptorMiddleware.ts

chore: don't redirect to `signin` page in standalone mode

---

frontend/src/components/IssueV1/components/StageSection/Actions/GhostSection/GhostSection.vue

chore(frontend): don't show gh-ost section when not needed

---

frontend/src/components/ColumnDataTable/index.vue
frontend/src/components/DatabaseOverviewPanel.vue
frontend/src/components/PartitionTablesDataTable.vue
frontend/src/components/TableDataTable.vue
frontend/src/components/TableDetailDrawer.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/router/index.ts

chore: add partition tables data table

---

backend/api/lsp/completion.go

chore(LSP): map lsp type for candidates

---

backend/api/lsp/completion.go

feat(LSP): sort candidates triggered by dot

---

backend/api/v1/database_service.go
frontend/src/components/DatabaseOverviewPanel.vue
frontend/src/router/index.ts
frontend/src/store/modules/sqlEditorTree.ts
frontend/src/types/sqlEditorTree.ts
frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue
frontend/src/views/sql-editor/AsidePanel/TreeNode/Label.vue
frontend/src/views/sql-editor/AsidePanel/TreeNode/PartitionTableNode.vue
frontend/src/views/sql-editor/AsidePanel/common.ts

chore: show partition tables in sql editor

---

backend/api/lsp/completion.go

feat(LSP): set sortText for completion items

---

frontend/src/components/KBar/useProjectActions.ts
frontend/src/views/DashboardSidebar.vue

Only available when the sidebar is DashboardSidebar

chore(frontend): bring project kbar actions back for dashboard

---

backend/plugin/parser/mysql/completion.go
backend/plugin/parser/mysql/test-data/test_completion.yaml

fix(LSP): skip nil table

---

frontend/src/store/modules/sqlEditorTree.ts
frontend/src/utils/v1/sql.ts
frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue

It is awkward that `SELECT * FROM <<table>>` may violate some prod SQL review rules like 
- statement.select.no-select-all
- statement.where.require
making the query execution failure
Close BYT-4243

feat(sql-editor): double click on table should issue SELECT * FROM <<table>> query

---

frontend/src/components/AlterSchemaPrepForm/SchemaEditorSQLCheckButton/SchemaEditorSQLCheckButton.vue
frontend/src/components/AlterSchemaPrepForm/SchemaEditorSQLCheckButton/useSchemaEditorSQLCheck.ts
frontend/src/components/Branch/SchemaDesignSQLCheckButton.vue
frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckSection.vue
frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
frontend/src/components/SQLCheck/SQLCheckButton.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

Now the SQL checks will execute when
- Manually
- "Preview Issue" in schema editor modal
- "Create" when previewing the issue

chore(frontend): make SQL checks manual

---

frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/views/sql-editor/EditorCommon/ResultView/DetailPanel.vue

chore(frontend): tooltips and wordings for large results' detail panel

---

frontend/src/components/MonacoEditor/dev.ts

chore(frontend): support CLI lsp flag in release mode

---

.github/workflows/backend-tests.yml
scripts/.air.toml
scripts/build_bytebase.sh

chore: increase parallel

---

backend/plugin/parser/mysql/completion.go
backend/plugin/parser/mysql/completion_test.go
backend/plugin/parser/mysql/test-data/test_completion.yaml

feat(Completion): skip heading sqls

---

frontend/src/components/CommonSidebar.vue
frontend/src/components/Project/ProjectSidebar.vue
frontend/src/components/Project/ProjectSwitchModal.vue
frontend/src/components/v2/Model/ProjectV1Table.vue
frontend/src/views/DashboardHeader.vue

chore: resolve project ui issues

---

backend/plugin/parser/base/c3.go
backend/plugin/parser/base/scanner.go
backend/plugin/parser/mysql/completion.go
backend/plugin/parser/mysql/test-data/test_completion.yaml

feat(Completion): support column alias

---

backend/plugin/parser/mysql/completion.go

feat(LSP): enable OB

---

backend/api/v1/schema_design_transformer.go
backend/api/v1/testdata/design.yaml
backend/api/v1/testdata/schema.yaml
backend/plugin/db/mysql/sync.go

chore: use upper case for AUTO_INCREMENT

---

backend/api/v1/branch_service.go

Copy the entire file without breaking existing service.

chore: branch branch service

---

frontend/src/components/InstanceForm/InstanceForm.vue
frontend/src/components/InstanceForm/ScanIntervalInput.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

chore(frontend): re-invent instance scan interval input

---

frontend/src/components/GeneralSetting/SecuritySetting.vue
frontend/src/components/SQLCheck/SQLCheckPanel.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

chore(frontend): add restrict issue creation setting

---

backend/api/v1/schema_design_transformer_tidb.go
backend/api/v1/testdata/tidb/design.yaml

chore: use upper case AUTO_INCREMENT for tidb

---

backend/api/auth/config.go

Relate PR https://github.com/bytebase/hub/pull/503

chore: add DeleteCache to allow list

---

backend/api/auth/config.go
frontend/src/components/Project/ProjectBranchProtectionRulesSettingPanel.vue
frontend/src/components/ProjectDeploymentConfigPanel.vue
frontend/src/components/ProjectSettingPanel.vue

fix: project deployment config ui

---

frontend/src/components/IssueV1/components/HeaderSection/Assignee/Assignee.vue
frontend/src/components/v2/Select/UserSelect.vue

chore(frontend): avoid unexpected  assignee reset when assignee is SYSTEM_BOT

---

backend/plugin/advisor/mysql/advisor_use_innodb.go
backend/plugin/advisor/mysql/test/engine_mysql_use_innodb.yaml

fix(sql-review): fix check-innodb rule

---

frontend/src/components/SchemaEditorV1/Panels/DatabaseEditor.vue

chore: tweak database editor button css style

---

backend/api/v1/branch_service.go

fix: pass to argument to getDesignSchema

---

frontend/src/components/Branch/BranchCreateView.vue
frontend/src/components/Branch/MergeBranchPanel.vue
frontend/src/store/modules/branch.ts
frontend/src/views/branch/BranchDetail.vue

- Remove createBranchDraft().
- Make deleteBranchAfterMerged default false.

chore: improve branch

---

frontend/src/components/Branch/BranchDetailView.vue
frontend/src/components/Branch/MergeBranchPanel.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

- Rename the panel to head and bae following GitHub.
- Removed the incorrect branch merge. Will add todo later.

chore: update branch merge

---

backend/api/v1/schema_design_transformer_tidb.go
backend/api/v1/testdata/tidb/design.yaml
backend/api/v1/testdata/tidb/schema.yaml

fix(branch): get type string by restoring for tidb

---

backend/plugin/db/pg/sync.go
backend/plugin/db/redshift/sync.go

fix: fix that char with null max length

---

frontend/src/components/BytebaseLogo.vue
frontend/src/components/ProfileBrandingLogo.vue
frontend/src/layouts/BodyLayout.vue
frontend/src/views/SchemaTemplate/ColumnTypes.vue

fix: custom logo size

---

backend/demo/data/next/dump.sql

chore: update branch hierarchy in demo data

---

frontend/src/components/IssueV1/components/IssueSearch/AdvancedSearchBox.vue
frontend/src/components/Project/ProjectSidebar.vue
frontend/src/components/Project/useCurrentProject.ts
frontend/src/components/ProjectDatabasesPanel.vue
frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
frontend/src/layouts/ProjectV1Layout.vue
frontend/src/router/index.ts
frontend/src/views/project/ProjectDatabaseDashboard.vue
frontend/src/views/project/ProjectIssueDashboard.vue

Added `/projects/{projectId}/databases` and `/projects/{projectId}/issues` routes without entries in UI yet.

chore: add project databases and issues routes

---

frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
frontend/src/components/MonacoEditor/text-model.ts
frontend/src/components/MonacoEditor/utils.ts
frontend/src/views/sql-editor/EditorPanel/SQLEditor.vue

May close BYT-4611, maybe not.
I cannot reproduce either on the demo site or my machine (with the release build). But I've added some robustness and logs.

chore(frontend): add some robustness and logs

---

frontend/src/components/SQLReview/components/SQLRuleTable.vue

fix: invalid custom description

---

frontend/src/components/ProjectDatabasesPanel.vue
frontend/src/layouts/ProjectLayout.vue
frontend/src/layouts/ProjectV1Layout.vue
frontend/src/views/project/ProjectDatabaseDashboard.vue
frontend/src/views/sql-editor/TabList/TabList.vue

* filter database with alterable checks in project databases page; (standalone mode)
* update project layout's padding style;

chore(standalone): minor fixes

---

frontend/src/components/TableDetailDrawer.vue

chore(frontend): don't show n/a cells in table details panel

---

frontend/src/components/IssueV1/components/ActivitySection/Activity/ActionCreator.vue
frontend/src/components/IssueV1/components/ActivitySection/ActivitySection.vue
frontend/src/components/IssueV1/components/HeaderSection/Actions/review/IssueReviewButtonGroup.vue
frontend/src/components/IssueV1/components/HeaderSection/HeaderSection.vue
frontend/src/components/IssueV1/components/StageSection/StageInfo/DatabaseInfo.vue
frontend/src/components/IssueV1/components/StageSection/StageInfo/StageInfo.vue
frontend/src/components/v2/Model/DatabaseV1Name.vue
frontend/src/components/v2/Model/EnvironmentV1Name.vue
frontend/src/components/v2/Model/Instance/InstanceV1Name.vue

* hide review buttons for some customers;
* use plain text instead of link for instance/environment/database/user name;
* hide issue subscribers section;

chore: hide issue buttons in standalone mode

---

frontend/src/components/IssueV1/components/BannerSection.vue
frontend/src/components/IssueV1/components/HeaderSection/HeaderSection.vue
frontend/src/components/IssueV1/components/IssueStatusIcon.vue
frontend/src/components/IssueV1/logic/utils.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

[CAUTION] The special icon is available only on issue detail pages but not on the issue list. Since this status is calculated from the rollout pipeline status, which is not composed in the list views.
Close BYT-4539

feat(frontend): unfinished resolved issue tooltip

---

frontend/src/components/IssueV1/components/IssueStatusIcon.vue

fix(frontend): remove unused

---

backend/runner/plancheck/statement_report_executor.go

fix: use singleSQL instead of original statement

---

backend/plugin/db/mysql/mysql.go
backend/plugin/db/mysql/mysql_test.go

fix: mysql parse version

---

frontend/src/locales/en-US.json

docs: capitalize data classification tab

---

frontend/src/components/TableDataTable.vue

fix: table comment display

---

backend/plugin/db/pg/dump.go

chore: return pg dump errors

---

frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/views/sql-editor/EditorCommon/QueryContextSettingPopover.vue

chore(sql-editor): update i18n of data source type

---

frontend/src/store/modules/sqlEditorTree.ts
frontend/src/types/sqlEditorTree.ts
frontend/src/views/sql-editor/AsidePanel/DatabaseHoverPanel.vue
frontend/src/views/sql-editor/AsidePanel/TreeNode/DatabaseNode.vue

Move `factorListInLocalStorage` into store to prevent it from being automatically initialized.

chore(sql-editor): update default factors

---

frontend/src/bbkit/BBModal.vue
frontend/src/components/Project/ProjectSwitchModal.vue

chore: update BBModal styles

---

frontend/src/components/SchemaEditorLite/context/config.ts

chore(schema-editor): fix reactivity

---

backend/plugin/advisor/advisor.go
backend/plugin/advisor/mysql/advisor_column_maximum_character_length.go
backend/plugin/advisor/mysql/test/column_maximum_character_length.yaml

fix: handle char without maximum length

---

backend/demo/data/next/README.md
backend/demo/data/next/dump.sql

1. Schema drift anomaly
2. Request Query / Export approval flow
3. GitOps with schema latest file writeback
4. Schema to 2.12.0

chore: update demo data

---

frontend/src/views/auth/Signin.vue

Otherwise, it's hard to switch user in local demo mode

chore: only auto login for demo.bytebase.com

---

frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
frontend/src/components/v2/Model/DatabaseV1Table/DatabaseTableRow.vue
frontend/src/components/v2/Model/DatabaseV1Table/DatabaseV1Table.vue
frontend/src/views/ProjectDetail.vue

- Close BYT-4656
- Close BYT-4657

fix: add quick action for tenant project

---

frontend/src/components/InboxList.vue
frontend/src/views/Inbox.vue

* add page padding;
* use naive button;

chore: update inbox page

---

frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
frontend/src/components/SchemaEditorLite/common.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

chore: disallow preview issue if database not changed

---

backend/api/v1/schema_design_transformer.go
backend/plugin/schema-engine/pg/structurer.go
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/StringifyMetadataButton.vue

chore: stringify IndexMetadata

---

backend/api/v1/branch_service.go
backend/api/v1/branch_service_test.go

fix: trimDatabaseMetadata should compare user comment

---

.github/workflows/build-artifacts-and-draft-release.yml
.github/workflows/build-push-ci-image-depot.yml
.github/workflows/build-push-release-image.yml
.github/workflows/frontend-tests.yml
frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/store/modules/branch.ts
scripts/build_bytebase.sh

20.10.0 LTS: https://nodejs.org/en

chore: node 20

---

frontend/src/components/IssueV1/components/TaskRunSection/TaskRunComment.vue
frontend/src/types/instance.ts

https://www.bytebase.com/docs/change-database/troubleshoot/#postgresql

feat: add troubleshoot link beside PG migration error

---

frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue

consistent with quick actions.

chore: edit schema then change data

---

frontend/src/components/Branch/BranchRolloutView/BranchRolloutView.vue

Prepare to add preview statement similar to layout below.

chore: adjust branch rollout layout

---

frontend/src/components/Branch/BranchRolloutView/BranchRolloutView.vue

chore: preview DDL in branch rollout view

---

frontend/src/views/auth/Signin.vue

Hint user during SaaS onboarding

feat: accept hint query parameter in login page

---

backend/component/activity/manager.go
backend/plugin/webhook/dingtalk.go
backend/plugin/webhook/webhook.go

feat: dingtalk zh

---

backend/enterprise/service/license.go
frontend/src/views/BannerUpgradeSubscription.vue

- Clear subscription cache if is free
- Skip disallow-signup feature alert in SaaS mode.

chore: close issue BYT-4676

---

frontend/src/components/ProfileDropdown.vue
frontend/src/views/auth/Signin.vue

For normal mode
For demo
For other cases with hint in the query (for now only in SaaS)

chore: tiny ui update

---

frontend/src/router/index.ts
frontend/src/store/modules/v1/projectIamPolicy.ts
frontend/src/utils/v1/project.ts
frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue

* hide request export button for querier/exporter;
* add navigation guard for sql editor in standalone mode;

chore: add navigation guard in standalone mode

---

backend/plugin/db/mysql/mysql.go

Reverts bytebase/bytebase#9975

chore: Revert "chore: add more logs"

---

frontend/src/components/Branch/BranchDetailView.vue

* only show **apply to database** button for parent branches;
* add parent branch navigator;

chore: only show apply button for parent branches

---

frontend/src/views/ProjectDetail.vue

chore: swap the database group action order

---

backend/api/lsp/completion.go
backend/plugin/parser/pg/completion.go

feat: enable lsp for RedShift and RisingWave

---

frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/TableCell.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DetailPanel.vue

https://github.com/bytebase/bytebase/assets/24653555/c21251bd-2cc9-47f6-9948-e31999194a74

chore(sql-editor): only show 1 line in result cell

---

scripts/Dockerfile.depot

ref: https://github.com/bytebase/bytebase/pull/9974

chore: support depot preloading

---

backend/api/v1/branch_service.go
go.mod
go.sum

POC github.com/epiclabs-io/diff3, which is LGPLv3 license.

feat(branch): generate conflict string in rebase branch

---

backend/resources/utils/install_util_not_embeded.go
scripts/Dockerfile
scripts/Dockerfile.depot
scripts/Dockerfile.render-demo

for compatibility reasons, we cannot set the preload directory to `/var/opt/bytebase/resources`

fix: change preloading path

---

backend/resources/postgres/sample_instance.go

Reverts bytebase/bytebase#10028

chore: Revert "chore: start one sample pg to testify OOM"

---

backend/resources/postgres/sample_instance.go
scripts/.air.toml

1. initdb and start postgres server in sequence.
2. use table existence to determine whether we need to start the sample database.

chore: update sample instance

---

backend/api/v1/branch_service.go

1. The wrong result of diff3.
2. Previously, set head to base after rebased.
3. Improve conflict text likes following separator:

fix(branch): some branch issues

---

backend/api/v1/schema_design_merge.go
backend/api/v1/testdata/schema_design_merge/try_merge.yaml

This pr computes the diff of index node, and fixes the error message when update nodes were conflicted.

fix(branch): compute index diff

---

frontend/src/components/Branch/BranchRolloutView/BranchRolloutView.vue
frontend/src/components/SchemaEditorLite/Aside/BranchTree.vue
frontend/src/components/SchemaEditorLite/Aside/DatabaseTree.vue
frontend/src/components/SchemaEditorLite/Aside/NodeCheckbox/ColumnNodeCheckbox.vue
frontend/src/components/SchemaEditorLite/Aside/NodeCheckbox/NodeCheckbox.vue
frontend/src/components/SchemaEditorLite/Aside/NodeCheckbox/SchemaNodeCheckbox.vue
frontend/src/components/SchemaEditorLite/Aside/NodeCheckbox/TableNodeCheckbox.vue
frontend/src/components/SchemaEditorLite/Aside/NodeCheckbox/index.ts
frontend/src/components/SchemaEditorLite/Aside/types.ts
frontend/src/components/SchemaEditorLite/Modals/SchemaNameModal.vue
frontend/src/components/SchemaEditorLite/Modals/TableNameModal.vue
frontend/src/components/SchemaEditorLite/Panels/DatabaseEditor.vue
frontend/src/components/SchemaEditorLite/Panels/TableColumnEditor/TableColumnEditor.vue
frontend/src/components/SchemaEditorLite/Panels/TableEditor.vue
frontend/src/components/SchemaEditorLite/Panels/TableList/TableList.vue
frontend/src/components/SchemaEditorLite/SchemaEditorLite.vue
frontend/src/components/SchemaEditorLite/algorithm/rebuild.ts
frontend/src/components/SchemaEditorLite/context/edit.ts
frontend/src/components/SchemaEditorLite/context/index.ts
frontend/src/components/SchemaEditorLite/context/selection.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

- Show columns in tree
- Picking columns to rollout is now also available via tree (see #10032 )
- Update the tree property when adding / dropping / renaming new tables and columns
- Editing "created" columns will no longer pollute their edit status to "updated" unexpectedly
- BranchTree and DatabaseTree now share common node structure and types.

feat(schema-editor): columns in tree

---

frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/ColumnList.vue
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/HoverPanel/ColumnInfo.vue
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/HoverPanel/ExternalTableInfo.vue
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/HoverPanel/InfoItem.vue
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/HoverPanel/TableInfo.vue
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/HoverPanel/ViewInfo.vue
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/TableList.vue

chore(sql-editor): use NEllipsis in hover panel

---

backend/runner/taskrun/data_update_executor.go
backend/runner/taskrun/data_update_executor_test.go

chore: change the name of a backup

---

frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
frontend/src/components/AlterSchemaPrepForm/ProjectStandardView.vue
frontend/src/components/ChangeHistory/ChangeHistoryTable.vue
frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/form/BranchTable/BranchTable.vue
frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/form/ChangeHistoryTable/ChangeHistoryTable.vue
frontend/src/components/InstanceAssignment.vue
frontend/src/components/IssueV1/components/IssueTableV1.vue
frontend/src/components/ProjectDatabasesPanel.vue
frontend/src/components/ProjectMember/ProjectMemberPanel.vue
frontend/src/components/SensitiveData/components/SensitiveColumnTable.vue
frontend/src/components/SyncDatabaseSchema/TargetDatabasesSelectPanel.vue
frontend/src/components/TransferDatabaseForm/MultipleDatabaseSelector.vue
frontend/src/components/v2/Model/Instance/InstanceV1Table/InstanceV1Table.vue
frontend/src/views/DatabaseDashboard.vue

fix: checkbox click event

---

frontend/src/components/SQLCheck/SQLCheckButton.vue

fix(frontend): should run sql check before submitting

---

frontend/src/utils/tab.ts
frontend/src/views/sql-editor/AsidePanel/AsidePanel.vue
frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue
frontend/src/views/sql-editor/AsidePanel/SearchBox/index.vue
frontend/src/views/sql-editor/AsidePanel/SearchBox/useSearchHistory.ts

https://github.com/bytebase/bytebase/assets/24653555/8901ee73-b776-4491-9f42-22eee55c6bca

chore(sql-editor): add search history in database tree

---

frontend/src/views/sql-editor/AsidePanel/SearchBox/index.vue

chore(sql-editor): add truncate to search result

---

backend/api/v1/setting_service.go
backend/component/config/profile.go

fix: setting control for saas

---

frontend/src/components/IssueV1/components/PagedIssueTableV1.vue
frontend/src/components/PagedActivityTable.vue

fix: missing load more button

---

frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue

chore(frontend): always show the fullscreen button for sql editor in issue detail page

---

frontend/src/NotificationContext.vue
frontend/src/views/BannerDemo.vue
frontend/src/views/BannerExternalUrl.vue
frontend/src/views/auth/Activate.vue
frontend/src/views/auth/Signin.vue
frontend/src/views/auth/Signup.vue

- Fix the button style in the banner
- Add margin for notification title
- Fix autocomplete

fix: several ui update

---

frontend/src/components/ActivityTable/utils.ts
frontend/src/components/IssueV1/components/ActivitySection/Activity/ActionSentence.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/types/activity.ts

chore: show prior backup activities

---

backend/runner/taskrun/data_update_executor.go
backend/runner/taskrun/data_update_executor_test.go

chore: backup table issue comment

---

backend/plugin/db/pg/pg.go
backend/plugin/db/redshift/redshift.go
backend/plugin/db/risingwave/risingwave.go
backend/runner/taskrun/executor.go

chore: pg execute details

---

backend/bin/server/cmd/profile.go
backend/bin/server/cmd/root.go
backend/component/config/profile.go
backend/runner/taskrun/executor.go

chore: execute detail flag

---

frontend/src/components/EnvironmentForm.vue

chore: add learn more link to rollout policy

---

frontend/src/components/Issue/panel/RequestExportPanel/ExportResourceForm/DatabaseResourceSelector.vue
frontend/src/components/Issue/panel/RequestQueryPanel/DatabaseResourceForm/DatabaseResourceSelector.vue

fix(frontend): listElRef undefined since NTree with virtual-scroll has no height explicitly

---

frontend/src/components/SyncDatabaseSchema/DatabaseSchemaSelector.vue
frontend/src/components/SyncDatabaseSchema/index.vue
frontend/src/views/ProjectDetail.vue

fix(frontend): sync schema page won't refresh when changing project

---

frontend/src/components/ProjectMember/ProjectMemberTable/ProjectMemberTable.vue
frontend/src/components/v2/Model/DatabaseV1Name.vue
frontend/src/store/modules/user.ts
frontend/src/store/modules/v1/projectIamPolicy.ts
frontend/src/types/v1/user.ts
frontend/src/utils/v1/project.ts
frontend/src/views/SettingWorkspaceAccessControl.vue
frontend/src/views/SettingWorkspaceMember.vue
frontend/src/views/sql-editor/SecondarySidebar/SheetTabPane/SheetList/SheetList.vue

* rename `ALL_USERS_USER_NAME` to `ALL_USERS_USER_EMAIL`;
* hide `allUsers` in workspace member list;

chore: hide allUsers in member list

---

backend/plugin/parser/base/interface.go
backend/plugin/parser/mysql/normalize.go
backend/plugin/parser/mysql/rollback.go
backend/plugin/parser/mysql/rollback_test.go
backend/plugin/parser/mysql/test-data/test_rollback.yaml

feat: implement rollback UPDATE for MySQL

---

backend/api/v1/auth_service.go

May be part of https://github.com/bytebase/bytebase/pull/10173

chore: fix role format

---

backend/plugin/db/tidb/tidb.go
backend/plugin/db/tidb/tidb_test.go
backend/runner/taskrun/executor.go

chore: move tidb create index to separate transactions

---

frontend/src/components/IssueV1/components/Sidebar/Assignee/Assignee.vue
frontend/src/components/IssueV1/components/Sidebar/EarliestAllowedTime.vue

chore(frontend): adjust items' vertical spacing for issue sidebar

---

frontend/src/components/Icon/IndexIcon.vue
frontend/src/components/Icon/index.ts
frontend/src/components/SchemaEditorLite/Panels/IndexesEditor/IndexesEditor.vue
frontend/src/components/SchemaEditorLite/Panels/IndexesEditor/components/ColumnsCell.vue
frontend/src/components/SchemaEditorLite/Panels/IndexesEditor/components/OperationCell.vue
frontend/src/components/SchemaEditorLite/Panels/IndexesEditor/components/index.ts
frontend/src/components/SchemaEditorLite/Panels/IndexesEditor/index.ts
frontend/src/components/SchemaEditorLite/Panels/TableColumnEditor/TableColumnEditor.vue
frontend/src/components/SchemaEditorLite/Panels/TableEditor.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

- Comments edited but won't generate DDL. FYI @h3n4l 
Close BYT-4756

feat(branch): support index in schema editor

---

backend/store/principal.go

Call GetUserByID at the end of UpdateUser to fetch roles.

fix: update user

---

frontend/src/components/User/Settings/CreateUserDrawer.vue

Update disabled attr of confirm button in creating/updating user drawer.

chore: update disabled attr of confirm button

---

backend/bin/server/cmd/profile_dev.go
backend/bin/server/cmd/root.go
backend/component/iam/acl.yaml

* enable IAM flag by default in dev mode;
* remove unused permissions;

chore: update IAM flag default value

---

frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/form/ChangeHistoryChangeItem.vue
frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/form/ChangeHistoryForm.vue
frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/form/ChangeHistoryTable/ChangeHistoryTable.vue
frontend/src/components/Changelist/ChangelistDetail/ChangeTable/Source.vue

- Extended checkbox clickable area for ChangeHistory list (Close BYT-4745)
- Auto sort Change histories when adding to changelist (Close BYT-4746)
- Show issue id for change histories (Close BYT-4746)

chore(frontend): changelist improvements

---

frontend/src/components/SensitiveData/SensitiveColumnDrawer.vue
frontend/src/store/modules/v1/dbSchema.ts
frontend/src/views/ProfileDashboard.vue

fix: update schema cache

---

frontend/src/components/Branch/BaselineSchemaSelector.vue
frontend/src/components/Branch/BranchCreateView.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

chore(frontend): branch creating ui improvements

---

backend/api/v1/branch_service.go

Follow #10205, passing the table collation and engine to enhance the UX (frontend display), even though we do not support modifying them.

chore(branch): pass table collation and engine

---

backend/component/ghost/config.go
backend/runner/plancheck/ghost_sync_executor.go
backend/runner/taskrun/schema_update_ghost_cutover_executor.go
backend/runner/taskrun/schema_update_ghost_sync_executor.go

Avoid race between two parallel test suites.

chore: add task created_ts to ghost filename

---

backend/runner/plancheck/statement_type_executor.go

close BYT-4790
The `tidbStatementTypeCheck` is only used for TiDB now. No need to extract TiDB unsupported statements.

fix: tidb statement type check

---

backend/store/principal.go
backend/store/role.go

* fix default role to `WorkspaceMember` when creating user;
* remove dev guard of role list as we'll show all renamed roles in `Custom Roles`;

fix: create user

---

frontend/src/components/EnvironmentForm/RolloutPolicyConfig.vue
frontend/src/components/ProjectMember/AddProjectMember/AddProjectMemberForm.vue
frontend/src/components/v2/Select/ProjectRoleSelect.vue
frontend/src/components/v2/Select/index.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/types/project.ts
frontend/src/utils/projectIamPolicy.ts
frontend/src/utils/role.ts

feat(frontend): allow using custom role for environment rollout releaser policy

---

frontend/src/views/BannerUpgradeSubscription.vue

Related backend change: https://github.com/bytebase/bytebase/pull/10235

chore: update upgrade subscription banner

---

backend/api/v1/resource_id.go
backend/api/v1/resource_id_test.go
backend/api/v1/role_service.go

regex copied from https://github.com/bytebase/bytebase/blob/88e3b3d7df42366c88daa8b456c78558b377ce4f/frontend/src/components/v2/Form/ResourceIdField.vue#L73

feat: validate role resource id

---

frontend/src/components/EllipsisText.vue
frontend/src/components/IssueV1/components/IssueTableV1.vue
frontend/src/utils/util.ts

chore(frontend): fix issue table text overflow

---

backend/api/v1/sql_service.go
backend/tests/sql_export_test.go
frontend/src/components/DataExportButton.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/views/ExportCenter/ExportDataButton.vue
frontend/src/views/SettingWorkspaceAuditLog.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue

chore: download raw file if not provide the password

---

frontend/src/components/Branch/BranchCreateView.vue

chore(frontend): only allow to create child branches from main (parent-less) branches

---

frontend/src/layouts/SplashLayout.vue
frontend/src/router/auth.ts
frontend/src/router/index.ts
frontend/src/utils/iam/permission.ts
frontend/src/views/TwoFactorSetup.vue
frontend/src/views/auth/MultiFactor.vue

* split auth related routes from all routes;

chore: split auth routes

---

backend/plugin/schema/mysql/get_design_schema.go
backend/plugin/schema/mysql/get_design_schema_test.go

fix(structurer): compare index in get design schema

---

frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
frontend/src/components/Branch/BranchMergeView/MergeBranchStep.vue
frontend/src/components/Branch/BranchRolloutView/BranchRolloutView.vue
frontend/src/components/Branch/SchemaDesignEditorLite.vue
frontend/src/components/MonacoEditor/MonacoTextModelEditor.vue
frontend/src/components/MonacoEditor/editor.ts
frontend/src/components/SQLCheck/SQLCheckButton.vue
frontend/src/components/SchemaEditorLite/Panels/IndexesEditor/components/OperationCell.vue
frontend/src/components/SchemaEditorLite/common.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json

- Better tips when generated DDL is empty. (Close BYT-4785)
- fix missing i18n
- keep both sides' word wrapping consistent

chore(frontend): branch and schema editor UI improvements

---

frontend/src/components/Branch/BranchCreateView.vue

chore(frontend): fix parent-less branch logic

---

backend/plugin/schema/mysql/get_design_schema.go
backend/plugin/schema/mysql/state.go
backend/plugin/schema/mysql/testdata/get_design_schema.yaml
backend/plugin/schema/mysql/utils.go

chore(structurer): nullable for text/blob/geometry/json

---

backend/store/database.go

Sheet and database/project should be weakly related.

chore: don't update sheet project for database project update

---

backend/store/stats.go

fix: use principal.status

---

backend/plugin/parser/tidb/strings.go
backend/plugin/parser/tidb/strings_test.go
backend/plugin/parser/tidb/test-data/test_strings_manipulate.yaml
go.mod
go.sum

feat: implement column def manipulate

---

backend/store/principal.go
frontend/src/views/sql-editor/SecondarySidebar/SheetTabPane/SheetList/SheetList.vue

fix: should show sheet even if the database is transfer out

---

backend/plugin/db/pg/pg.go
backend/plugin/db/redshift/redshift.go
backend/plugin/db/risingwave/risingwave.go

fix(driver/risingwave/redshift): trim space before call strings.HasPrefix

---

frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue

chore(frontend): show "apply to other tasks" when the project is batch mode but the database list is manually selected

---

frontend/src/components/Changelist/ChangelistDashboard/ChangelistDashboard.vue

The filter is implemented on the backend

chore: remove changelist filter on the frontend

---

frontend/src/store/modules/v1/database.ts

chore: only use searchDatabases if iam

---

backend/plugin/parser/tidb/normalize.go
backend/plugin/parser/tidb/strings.go
backend/plugin/parser/tidb/strings_test.go
backend/plugin/parser/tidb/test-data/test_strings_manipulate.yaml
go.mod
go.sum

feat: implement table constraint actions

---

backend/plugin/db/tidb/sync.go
backend/plugin/parser/tidb/strings.go
backend/plugin/parser/tidb/strings_test.go
backend/plugin/parser/tidb/test-data/test_strings_manipulate.yaml
backend/plugin/schema/tidb/get_design_schema.go
backend/plugin/schema/tidb/parse_to_metadata.go
backend/plugin/schema/tidb/testdata/get_design_schema.yaml

feat: branch for tidb use manipulator

---

frontend/src/layouts/BodyLayout.vue
frontend/src/layouts/ProjectLayout.vue

Close BYT-4835
Needs to cherry-pick to 2.13.1

fix: ui padding without quick action buttons

---

frontend/src/components/IssueV1/components/Sidebar/EarliestAllowedTime.vue

chore(frontend): don's show earliest allowed time if not needed

---

backend/plugin/parser/mysql/split_test.go
go.mod
go.sum

fix: fix mysql splitter when escaping double quote

---

frontend/src/components/Branch/BranchDetailView.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/branch.ts

chore(frontend): double warning and force delete parent branch

---

frontend/src/store/modules/v1/changeHistory.ts

We can cherry-pick this to 2.13.1

fix: compare statement and schema size

---

backend/plugin/schema/tidb/get_design_schema.go
backend/plugin/schema/tidb/parse_to_metadata.go
backend/plugin/schema/tidb/testdata/get_design_schema.yaml

feat: support tidb index

---

frontend/src/layouts/SettingLayout.vue
frontend/src/router/index.ts
frontend/src/views/SettingSidebar.vue

* move permission check out of router because the data isn't ready;

fix: setting permission check

---

backend/api/v1/environment_service.go
backend/api/v1/project_service.go
frontend/public/help/routeMapList.json
frontend/src/components/DatabaseBackup/DatabaseBackupSettingForm.vue
frontend/src/components/DatabaseBackupPanel.vue
frontend/src/components/KBar/useRecentVisit.ts
frontend/src/components/Quickstart.vue
frontend/src/components/SQLReview/SQLReviewPolicyTable.vue
frontend/src/components/SyncDatabaseSchema/SelectTargetDatabasesView.vue
frontend/src/components/v2/Model/EnvironmentName.vue
frontend/src/components/v2/Model/EnvironmentV1Name.vue
frontend/src/components/v2/Model/EnvironmentV1Table.vue
frontend/src/main.ts
frontend/src/router/dashboard/environmentV1.ts
frontend/src/router/dashboard/index.ts
frontend/src/router/index.ts
frontend/src/shims-vue-globals.d.ts
frontend/src/store/modules/router.ts
frontend/src/types/common.ts
frontend/src/utils/slug.ts
frontend/src/views/DashboardSidebar.vue
frontend/src/views/EnvironmentDashboard.vue
frontend/src/views/EnvironmentDetail.vue
frontend/src/views/SettingWorkspaceSQLReviewDetail.vue

* move `/environment` to `/environments`;
* move `/environment/:slug` to `/environments/:environmentId`;

refactor(frontend): environment routes

---

backend/plugin/parser/mysql/mysql.go
backend/plugin/parser/tokenizer/testdata/test_split_tidb_multi_sql.yaml
backend/plugin/parser/tokenizer/tokenizer.go
backend/plugin/parser/tokenizer/tokenizer_test.go
backend/plugin/schema/mysql/get_design_schema.go
backend/plugin/schema/mysql/testdata/get_design_schema.yaml

feat(tokenizer): add options to allow keep empty lines between blocks

---

backend/plugin/parser/mysql/split.go
backend/plugin/parser/mysql/split_test.go

feat: effective splitter for MySQL

---

backend/plugin/schema/mysql/get_design_schema.go
backend/plugin/schema/mysql/get_design_schema_test.go
backend/plugin/schema/mysql/testdata/get_design_schema.yaml

chore(structurer): generate continuous create table stmt

---

backend/plugin/parser/tidb/strings.go
backend/plugin/parser/tidb/test-data/test_strings_manipulate.yaml

chore: create new table before set foreign key checks

---

frontend/src/NotificationContext.vue
frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
frontend/src/components/Branch/BranchRolloutView/BranchRolloutView.vue
frontend/src/components/SchemaEditorLite/algorithm/apply-selected.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/zh-CN.json
frontend/src/types/notification.ts

chore(frontend): better notifications when schema/branch editor generated DDL is empty

---

backend/plugin/db/clickhouse/sync.go

reverts https://github.com/bytebase/bytebase/pull/10155

chore: revert clickhouse sync query

---

backend/plugin/db/clickhouse/sync.go

chore: use lowercase names to sync clickhouse schema

---

frontend/src/components/DatabaseGroup/DatabaseGroupPanel.vue
frontend/src/components/DatabaseGroup/DatabaseGroupTable.vue
frontend/src/components/DatabaseGroup/ProjectDatabaseGroupPanel.vue
frontend/src/components/DatabaseGroup/SchemaGroupTable.vue
frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckDetail.vue
frontend/src/components/SQLCheck/SQLCheckDetail.vue
frontend/src/components/v2/Model/DatabaseGroupName.vue
frontend/src/components/v2/Model/DatabaseV1Table/DatabaseV1Table.vue
frontend/src/layouts/ProjectV1Layout.vue
frontend/src/views/DatabaseGroupDetail.vue
frontend/src/views/SchemaGroupDetail.vue
frontend/src/views/project/ProjectDatabaseGroupDashboard.vue

- Update database group permission
- Use route name instead of path for database group and table group
- Add padding for SQL review advice panel. Close BYT-4857

chore: database group permission

---

backend/plugin/schema/mysql/get_design_schema.go
backend/plugin/schema/mysql/get_design_schema_test.go
backend/plugin/schema/mysql/state.go
backend/plugin/schema/mysql/testdata/get_design_schema.yaml

chore(structurer): do not write null in get design schema for mysql

---

backend/api/v1/branch_service.go

chore(branch): using new base as baseline in get design schema

---

backend/plugin/parser/tidb/split.go
backend/plugin/parser/tidb/strings.go
backend/plugin/parser/tidb/test-data/test_strings_manipulate.yaml
backend/plugin/schema/tidb/testdata/get_design_schema.yaml

chore(branch): keep empty blocks for TiDB

---

frontend/src/components/v2/Model/DatabaseV1Table/DatabaseV1Table.vue
frontend/src/router/dashboard/database.ts
frontend/src/router/dashboard/workspace.ts
frontend/src/router/dashboard/workspaceRoutes.ts
frontend/src/router/index.ts
frontend/src/store/modules/router.ts
frontend/src/types/common.ts
frontend/src/views/ChangeHistoryDetail.vue
frontend/src/views/DatabaseDashboard.vue
frontend/src/views/ProfileDashboard.vue

* remove duplicated policy requests;
* move fetch user into component self;
* fix BYT-4834;

chore: update user profile page

---

backend/plugin/parser/tidb/strings.go
backend/plugin/parser/tidb/test-data/test_strings_manipulate.yaml
backend/plugin/schema/tidb/get_design_schema.go
backend/plugin/schema/tidb/parse_to_metadata.go
backend/plugin/schema/tidb/testdata/get_design_schema.yaml
backend/plugin/schema/tidb/testdata/parse_to_metadata.yaml

refactor(branch): tidb branch for column options

---

backend/api/v1/issue_service.go
backend/component/iam/acl.yaml
backend/legacyapi/issue.go
backend/store/issue.go

1. if the user is the issue creator
2. with bb.issues.get/list permission, users can see grant request type issues.
3. with bb.issues.get/list and bb.plans.get/list permissions, users can see change database type issues.

feat: issue iam permission filter

---

frontend/src/components/IssueV1/components/Sidebar/PreBackupSection/PreBackupSection.vue

chore(frontend): add beta badge for DML Prior Backup feature

---

backend/plugin/parser/tidb/strings.go
backend/plugin/parser/tidb/strings_test.go
backend/plugin/parser/tidb/test-data/test_strings_manipulate.yaml
backend/plugin/schema/tidb/get_design_schema.go
backend/plugin/schema/tidb/testdata/get_design_schema.yaml

chore(strings): build schema as show create table in TiDB

---

frontend/src/components/ProvideSQLEditorContext.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/zh-CN.json
frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue
frontend/src/views/sql-editor/AsidePanel/common.ts
frontend/src/views/sql-editor/SecondarySidebar/SecondaryGutterBar/SecondaryGutterBar.vue

- Check bb.databases.getSchema permission before displaying database metadata
- Check bb.databases.get before loading sheets

chore(frontend): migrate sql editor IAM (part.2)

---

frontend/src/components/User/Settings/UserDataTable/cells/UserRolesCell.vue
frontend/src/utils/iam/role.ts
frontend/src/views/ProfileDashboard.vue

chore: display sorted member roles

---

backend/plugin/db/mysql/sync.go
backend/plugin/db/tidb/sync.go
backend/plugin/parser/tidb/strings.go

chore: deal with current_timestamp

---

frontend/src/components/IssueV1/logic/context.ts

Trying to fix issue BYT-4633, I'm wondering if is caused by the cache, @RainbowDashy maybe you can take a try in your local environment

chore: random issue context key

---

backend/plugin/parser/tidb/strings.go

chore: deal with index comment

---

backend/plugin/parser/tidb/test-data/test_strings_manipulate.yaml
backend/plugin/schema/tidb/get_design_schema.go
backend/plugin/schema/tidb/parse_to_metadata.go
backend/plugin/schema/tidb/testdata/get_design_schema.yaml
backend/plugin/schema/tidb/testdata/parse_to_metadata.yaml

feat(branch): deal with key length

---

frontend/src/components/Branch/BranchRebaseView/BranchRebaseView.vue

- Parent branch for child branches
- Database for non-child branches
- Won't override the URL params
Close BYT-4889

chore(frontend): auto select source branch when rebasing

---

frontend/src/components/IssueV1/components/Sidebar/PreBackupSection/PreBackupSection.vue
frontend/src/components/IssueV1/components/Sidebar/ReviewSection/ReviewSection.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

- adjust tooltip position for "Approval Flow" (Close BYT-4893)
- add tooltip for "Prior Backup" (Close BYT-4885)

chore(frontend): issue sidebar tooltip improvements

---

frontend/src/components/Role/Setting/components/RolePanel.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json
frontend/src/store/modules/role.ts

https://github.com/bytebase/bytebase/assets/24653555/957e7948-80c5-4577-ba09-45f07943708c

feat(frontend): implement custom permissions in custom roles

---

frontend/src/store/modules/branch.ts

This is not yet smart enough. We may cache basic and full view independently
Close BYT-4902

chore(frontend): do not cache branch basic view

---

frontend/src/components/IssueV1/components/CurrentApproverV1.vue

chore(frontend): prevent forever loading spinner

---

backend/store/issue.go

`FROM issue, query LEFT JOIN project` doesn't work.
Changed to `FROM issue LEFT JOIN query LEFT JOIN project`

fix: search issue sql

---

frontend/src/components/IssueV1/components/CurrentApproverV1.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

chore(frontend): show review sent back in issue list

---

backend/api/v1/auth_service.go

Check if the updating/deleting user is the only workspace admin.

chore(backend): update update/delete workspace admin checks

---

backend/api/v1/branch_service.go
backend/api/v1/database_service.go
backend/plugin/parser/base/diff.go
backend/plugin/parser/base/interface.go
backend/plugin/parser/mysql/differ.go
backend/plugin/parser/mysql/differ_test.go
backend/plugin/parser/pg/differ.go
backend/plugin/parser/pg/differ_test.go
backend/plugin/parser/plsql/differ.go
backend/plugin/parser/plsql/differ_test.go
backend/plugin/parser/tidb/differ.go
backend/plugin/parser/tidb/differ_test.go
backend/runner/utils/sdl_utils.go

chore(differ): introduce diff context and strict mode

---

frontend/.vscode/settings.json
frontend/src/components/CustomApproval/Settings/components/common/utils.ts
frontend/src/components/IssueV1/components/IssueSearch/useSearchScopeOptions.ts
frontend/src/components/KBar/useProjectActions.ts
frontend/src/components/Project/ProjectSwitchModal.vue
frontend/src/components/QuickActionPanel.vue
frontend/src/components/SensitiveData/components/utils.ts
frontend/src/components/v2/Select/ProjectSelect.vue
frontend/src/store/modules/v1/project.ts
frontend/src/utils/iam/permission.ts
frontend/src/views/Archive.vue
frontend/src/views/DatabaseDashboard.vue
frontend/src/views/ExportCenter/index.vue
frontend/src/views/ProjectDashboard.vue

Use project list from backend directly instead of the filtered result from frontend;
Close https://github.com/bytebase/bytebase/issues/10478

chore: retire use projects by current user

---

frontend/src/views/DashboardHeader.vue

chore: update dashboard header styles

---

frontend/src/components/IssueV1/components/StageSection/StageSection.vue

chore(frontend): stage list mobile view improvements

---

frontend/src/components/MonacoEditor/DiffEditor.vue
frontend/src/components/MonacoEditor/WrappedDiffEditor.vue
frontend/src/components/SyncDatabaseSchema/DiffViewPanel.vue

https://github.com/bytebase/bytebase/assets/24653555/9872e81e-dd7a-4a19-814b-bd556743fed7

chore: add navigator to diff editor in sync schema

---

frontend/src/views/sql-editor/EditorCommon/ResultView/DataBlock.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/TableCell.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DetailPanel.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/context.ts

chore(sql-editor): fix: wrong detail index after the result table is sorted by manually clicking the table headers

---

backend/plugin/schema/mysql/parse_to_metadata.go
backend/plugin/schema/mysql/testdata/parse_to_metadata.yaml

chore(structurer): handle charset in data type for MySQL in parseToMetadata

---

frontend/src/components/v2/Model/DatabaseV1Table/ProjectCol.vue
frontend/src/components/v2/Model/ProjectV1Name.vue
frontend/src/views/DashboardHeader.vue

chore: fix project selector max width

---

frontend/src/components/DataExportButton.vue
frontend/src/locales/zh-CN.json

- Fix: export always export as CSV data. Close BYT-4914
- Fix: use plain text for export password to avoid auto-complete. Close BYT-4915
- Update localization. "Raw SQL" is clear in English so I just changed the Chinese. Close BYT-4923

fix: data export

---

frontend/src/components/SensitiveData/components/ClassificationExampleModal.vue
frontend/src/views/SettingWorkspaceDebugLog.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/DetailPanel.vue
frontend/src/views/sql-editor/EditorCommon/SharePopover.vue
frontend/src/views/sql-editor/SecondarySidebar/HistoryTabPane/HistoryTabPane.vue
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/StringifyMetadataButton.vue

Enable `legacy` to useClipboard
Reference: https://github.com/vueuse/vueuse/blob/main/packages/core/useClipboard/index.ts#L34

chore: enable legacy to useClipboard

---

frontend/src/components/IdentityProviderCreateForm.vue

Close https://github.com/bytebase/bytebase/issues/10535

chore: fix ldap form

---

frontend/src/components/ProjectBranchesPanel.vue
frontend/src/components/ProjectWebhookPanel.vue
frontend/src/components/Role/Setting/RoleSetting.vue
frontend/src/components/SensitiveData/GlobalMaskingRulesView.vue
frontend/src/views/SettingWorkspaceMember.vue
frontend/src/views/SettingWorkspaceSubscription.vue
frontend/src/views/SettingWorkspaceVCS.vue

If you find something inconsistent, issue me plz.
Close BYT-4901

chore(frontend): using capitalized texts for hero actions

---

frontend/src/components/Branch/BranchMergeView/BranchMergeView.vue
frontend/src/components/Branch/BranchMergeView/SelectBranchStep.vue
frontend/src/components/Branch/BranchMergeView/types.ts

chore(frontend): show merge error message for failed branch merges

---

frontend/src/plugins/ai/components/ChatPanel.vue

Close part of https://github.com/bytebase/bytebase/issues/10472

chore: update prompts for escaping column name

---

frontend/src/components/IssueV1/components/Panel/RolloutTaskDatabaseName.vue
frontend/src/components/IssueV1/components/Panel/TaskRolloutActionPanel.vue
frontend/src/components/IssueV1/logic/rollout.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json

- Prevent the stage section to be squeezed when we have many tasks
- Improved task name displaying
Close BYT-4807

chore(frontend): style improvement for task list when batch rollouting

---

backend/plugin/parser/plsql/concise_test.go
backend/plugin/parser/plsql/replace.go
backend/plugin/parser/plsql/test-data/test_concise_schema.yaml

feat: ignore store option

---

frontend/src/components/IssueV1/components/ActivitySection/Activity/ActionIcon.vue
frontend/src/components/PrincipalAvatar.vue

chore(frontend): fix user name initials in avatar

---

frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/TableList.vue

A quick and dirty workaround
Close BYT-4939

chore(frontend): use browser native tooltip to prevent VirtualList jitters with NEllipsis within

---

backend/api/v1/sql_service.go
backend/plugin/db/pg/pg.go
backend/plugin/parser/pg/query.go
backend/plugin/parser/pg/query_span_extractor.go
backend/plugin/parser/sql/ast/variable_set_stmt.go
backend/plugin/parser/sql/engine/pg/convert.go
backend/plugin/parser/sql/engine/pg/convert_test.go

chore(sql-editor): allow set stmt in export for PostgreSQL

---

frontend/src/components/DataExportButton.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue
frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
frontend/src/views/sql-editor/ResultPanel/ResultPanel.vue

fix(sql-editor): Incorrect export index with multiple result tabs

---

frontend/src/router/dashboard/projectV1.ts

chore(frontend): fall through bb.issues.get check to server-side

---

frontend/src/composables/useExecuteSQL.ts

fix(sql-editor): server returns "Support SELECT sql statement only" but FE displays "No rows found"

---

frontend/src/router/index.ts

chore(frontend): reset stores when signed out

---

frontend/src/views/sql-editor/EditorCommon/ResultView/RequestQueryButton.vue

chore: fix database id checks

---

backend/plugin/parser/mysql/normalize.go
backend/plugin/parser/tidb/rollback.go

feat: implement rollback dml for TiDB

---

frontend/src/components/ProjectWebhookPanel.vue
frontend/src/components/TransferDatabaseForm.vue
frontend/src/components/TransferDatabaseForm/TransferSourceSelector.vue
frontend/src/store/modules/v1/database.ts

- Close BYT-4944, will check project permission while transferring the database
- Close BYT-4958, hide the "Add webhook" button if users don't have permission.

chore: update permission check

---

backend/plugin/parser/base/span.go
backend/plugin/parser/pg/query_span_extractor.go
backend/plugin/parser/tidb/query_span.go
backend/plugin/parser/tidb/query_span_extractor.go
backend/plugin/parser/tidb/query_span_test.go
backend/plugin/parser/tidb/test-data/query_span.yaml

feat(querySpan): implement query span for TiDB

---

frontend/src/components/CustomApproval/Settings/components/common/utils.ts
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json
frontend/src/plugins/cel/types/factor.ts
frontend/src/plugins/cel/types/operator.ts

feat(frontent): risk factor: table rows

---

backend/plugin/parser/pg/query_span_extractor.go
backend/plugin/parser/pg/test-data/query_span.yaml
backend/plugin/parser/tidb/query_span_extractor.go
backend/plugin/parser/tidb/test-data/query_span.yaml

fix(query-span): query span extractor for asterisk and column name in target field list together

---

frontend/src/components/ProvideDashboardContext.vue
frontend/src/components/v2/Model/Instance/InstanceV1Table/InstanceV1Table.vue
frontend/src/views/Archive.vue
frontend/src/views/InstanceDashboard.vue

fix: cannot find archived projects

---

frontend/src/components/Branch/BranchRebaseView/BranchRebaseView.vue

Validate conflict markers only when conflicts existed.

chore(frontend): fix rebase validation

---

frontend/src/App.vue
frontend/src/components/ProjectDatabasesPanel.vue
frontend/src/components/ProvideDashboardContext.vue
frontend/src/components/ProvideSQLEditorContext.vue
frontend/src/store/modules/filter.ts
frontend/src/store/modules/index.ts
frontend/src/store/modules/sqlEditorTree.ts
frontend/src/store/modules/tab.ts

Close BYT-4963 and BYT-4962
https://github.com/bytebase/bytebase/assets/24653555/320fc919-eb04-4097-8143-9ca987852789

chore: add global filter store to specify a database

---

.github/dependabot.yml

- Add frontend to dependabot.yml

chore: dependabot.yml

---

backend/plugin/parser/pg/query.go
backend/plugin/parser/pg/query_test.go
backend/plugin/parser/sql/ast/explain_stmt.go
backend/plugin/parser/sql/engine/pg/convert.go
backend/plugin/parser/sql/engine/pg/convert_test.go

Also, support explain analyze select statement

fix: remove select regexp check

---

backend/plugin/advisor/advisor.go
backend/plugin/advisor/mysql/advisor_disallow_procedure.go
backend/plugin/advisor/mysql/advisor_naming_identifier_no_keyword.go
backend/plugin/advisor/mysql/mysql_rules_test.go
backend/plugin/advisor/mysql/test/naming_identifier_no_keyword.yaml
backend/plugin/advisor/mysql/utils.go
backend/plugin/advisor/sql_review.go

chore: add identifier no keyword rule for mysql

---

frontend/src/components/EnvironmentForm.vue
frontend/src/views/DatabaseDetail.vue

chore(frontend): hide database backup & restore feature

---

frontend/src/components/User/Settings/CreateUserDrawer.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json
frontend/src/types/iam/role.ts

chore: add tip for workspace role

---

frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/components/Branch/BranchRolloutView/useVirtualBranch.ts
frontend/src/components/ColumnDataTable/MaskingLevelCell.vue
frontend/src/components/Database/DatabaseOverviewPanel.vue
frontend/src/components/DatabaseDetail/SchemaDiagramButton.vue
frontend/src/components/ExternalTableDetailDrawer.vue
frontend/src/components/SensitiveData/SensitiveColumnDrawer.vue
frontend/src/components/SyncDatabaseSchema/DatabaseSchemaSelector.vue
frontend/src/components/TableDetailDrawer.vue
frontend/src/components/v2/Container/DrawerContent.vue
frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
frontend/src/plugins/ai/components/AIChatToSQL.vue
frontend/src/plugins/sql-lsp/client/useLegacyAutoComplete.ts
frontend/src/store/modules/v1/dbSchema.ts
frontend/src/views/ChangeHistoryDetail.vue
frontend/src/views/DatabaseDetail.vue
frontend/src/views/sql-editor/AsidePanel/common.ts
frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/SchemaPanel.vue

- using new cache mechanism
- no duplicated requests in very short time
- do not fetch FULL view db_schema when not really needed

chore(frontend): refactor dbSchema store cache

---

frontend/src/components/EnvironmentForm.vue
frontend/src/components/IdentityProviderTable.vue
frontend/src/locales/en-US.json
frontend/src/locales/es-ES.json
frontend/src/locales/ja-JP.json
frontend/src/locales/vi-VN.json
frontend/src/locales/zh-CN.json
frontend/src/views/EnvironmentDashboard.vue

chore: avoid page change without saving

---

backend/api/lsp/completion.go
backend/api/v1/sql_service.go
backend/api/v1/sql_service_v2.go
backend/component/dbfactory/dbfactory.go
backend/plugin/parser/base/interface.go
backend/plugin/parser/base/span.go
backend/plugin/parser/mysql/completion.go
backend/plugin/parser/mysql/completion_test.go
backend/plugin/parser/pg/completion.go
backend/plugin/parser/pg/completion_test.go
backend/plugin/parser/pg/query_span.go
backend/plugin/parser/pg/query_span_extractor.go
backend/plugin/parser/pg/query_span_test.go
backend/plugin/parser/plsql/query_span.go
backend/plugin/parser/plsql/query_span_extractor.go
backend/plugin/parser/plsql/query_span_test.go
backend/plugin/parser/plsql/test-data/query_span.yaml
backend/plugin/parser/tidb/query_span.go
backend/plugin/parser/tidb/query_span_extractor.go
backend/plugin/parser/tidb/query_span_test.go

close BYT-4752
Schema-based
Database-based

feat: enable Oracle query span

---

frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue

chore(sql-editor): hide row limit tips in admin mode

---

frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue

```
SELECT * FROM "database"."table" WHERE ROWNUM <= 50
```
```
SELECT * FROM `salary` LIMIT 50
```
Close BYT-4913

chore(sql-editor): specify row limit clause for oracle
